# Automatic entity type detection

In [1]:
import os
import sys
import pandas as pd
import numpy as np
from pathlib import Path
import logging
import warnings
warnings.filterwarnings('ignore')

# Add the project root to the Python path
project_root = Path().absolute().parent
sys.path.insert(0, str(project_root))

# Import AAAIM functions
from core import annotate_model, curate_model
from core.database_search import force_clear_chromadb, get_species_recommendations_rag
from utils.evaluation import (
    evaluate_single_model,
    evaluate_models_in_folder,
    print_evaluation_results,
    compare_results,
    process_saved_llm_responses
)

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# LLM configuration
llm_model = "openrouter/free"
# llm_model = "Llama-4-Maverick-17B-128E-Instruct-FP8"
# llm_model = "Llama-3.3-70B-Instruct"
# llm_model = "meta-llama/llama-3.3-70b-instruct:free"
# llm_model = "gpt-4.1-nano"

output_dir = "./autoType/"  # Output directory for results

In [2]:
test_model_file = "/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels/BIOMD0000000023.xml"
# test_model_file = "190_few_anno.xml"
# Check if test model exists
if os.path.exists(test_model_file):
    print(f"✓ Test model found: {test_model_file}")
else:
    print(f"✗ Test model not found: {test_model_file}")

✓ Test model found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels/BIOMD0000000023.xml

In [3]:
from core.model_info import format_prompt, find_species_with_annotations_and_qualifiers
# extract species that have chebi annotation
existing_annotations, qualifiers = find_species_with_annotations_and_qualifiers(test_model_file, 'chebi')
existing_annotations

{'Fru': ['15824'],
 'Glc': ['17634'],
 'HexP': ['16218', '15946', '14314', '18066'],
 'Suc6P': ['16308'],
 'Suc': ['17992'],
 'Sucvac': ['17992'],
 'glycolysis': ['28013'],
 'phos': ['18367'],
 'UDP': ['17659'],
 'ADP': ['16761'],
 'ATP': ['15422'],
 'Glcex': ['17634'],
 'Fruex': ['15824']}

In [6]:
# get the prompt for this model
prompt = format_prompt(test_model_file, existing_annotations.keys(), 'chemical')
print(prompt)

Now annotate these:
Chemical to annotate: Fru, Glc, HexP, Suc6P, Suc, Sucvac, glycolysis, phos, UDP, ADP, ATP, Glcex, Fruex
Model: "Rohwer2001_Sucrose"

// Reactions:
$Fruex -> Fru
$Glcex -> Glc
$ATP + Glc -> HexP + $ADP
Fru + $ATP -> HexP + $ADP
Fru + $ATP -> HexP + $ADP
2 HexP -> $UDP + Suc6P
Suc6P -> Suc + $phos
HexP + Fru -> Suc + $UDP
Suc -> Fru + Glc
HexP -> $glycolysis
Suc -> $Sucvac

// Notes:
"SBML
Level 2 code generated for the JWS Online project by Jacky Snoep using
PySCeS
.
Run this model online at
http://jjj.biochem.sun.ac.za
.
Web-based modelling using JWS Online
, Bioinformatics, 20:2143-2144.
For more information see the
.
for more information."

Return up to 3 standardized names or common synonyms for each chemical, ranked by likelihood. Provide components names for complexes, which may exceed the limit of 3.
Use the below format, do not include any other text except the synonyms, and give short reasons for all chemicals after 'Reason:' by the end.

SpeciesA: "name1", "name2", …
SpeciesB: …
Reason: …

In [5]:
result_df = evaluate_single_model(
    model_file=test_model_file,
    llm_model=llm_model,
    method = 'direct',
    top_k = 5,
    entity_type='chemical',
    database='chebi',
    save_llm_results=False,
    output_dir=output_dir,
    verbose=True
)

2025-11-24 13:13:33,786 - INFO - Evaluating model: BIOMD0000000023.xml
2025-11-24 13:13:33,889 - INFO - Evaluating 13 entities in BIOMD0000000023.xml
2025-11-24 13:13:37,702 - INFO - HTTP Request: POST https://api.llama.com/compat/v1/chat/completions "HTTP/1.1 200 OK"

LLM response:
Fru: "fructose", "D-fructose", "beta-D-fructose"
Glc: "glucose", "D-glucose", "alpha-D-glucose"
HexP: "hexose phosphate", "fructose-6-phosphate", "glucose-6-phosphate"
Suc6P: "sucrose-6-phosphate", "sucrose phosphate", "6-phosphosucrose"
Suc: "sucrose", "alpha-D-glucopyranosyl beta-D-fructofuranoside", "beta-D-fructofuranosyl alpha-D-glucopyranoside"
Sucvac: "sucrose", "vacuolar sucrose", "sucrose in vacuole"
Glcex: "glucose", "extracellular glucose", "external glucose"
Fruex: "fructose", "extracellular fructose", "external fructose"
phos: "phosphate", "inorganic phosphate", "orthophosphate"
UDP: "uridine diphosphate", "uridine 5'-diphosphate", "UDP"
ADP: "adenosine diphosphate", "adenosine 5'-diphosphate", "ADP"
ATP: "adenosine triphosphate", "adenosine 5'-triphosphate", "ATP"
glycolysis: "glycolytic pathway", "glycolysis intermediate", "UNK"
Reason: The model appears to be a metabolic model of sucrose metabolism, with reactions involving glucose, fructose, and sucrose. The names are standardized based on common biochemical nomenclature. Glycolysis is a pathway rather than a specific chemical, so it is annotated as such. Sucvac is likely referring to sucrose in the vacuole, but without more context, it is difficult to provide a more specific name.
Synonyms dict: {'Fru': ['fructose', 'D-fructose', 'beta-D-fructose'], 'Glc': ['glucose', 'D-glucose', 'alpha-D-glucose'], 'HexP': ['hexose phosphate', 'fructose-6-phosphate', 'glucose-6-phosphate'], 'Suc6P': ['sucrose-6-phosphate', 'sucrose phosphate', '6-phosphosucrose'], 'Suc': ['sucrose', 'alpha-D-glucopyranosyl beta-D-fructofuranoside', 'beta-D-fructofuranosyl alpha-D-glucopyranoside'], 'Sucvac': ['sucrose', 'vacuolar sucrose', 'sucrose in vacuole'], 'Glcex': ['glucose', 'extracellular glucose', 'external glucose'], 'Fruex': ['fructose', 'extracellular fructose', 'external fructose'], 'phos': ['phosphate', 'inorganic phosphate', 'orthophosphate'], 'UDP': ['uridine diphosphate', "uridine 5'-diphosphate", 'UDP'], 'ADP': ['adenosine diphosphate', "adenosine 5'-diphosphate", 'ADP'], 'ATP': ['adenosine triphosphate', "adenosine 5'-triphosphate", 'ATP'], 'glycolysis': ['glycolytic pathway', 'glycolysis intermediate', 'UNK']}

In [6]:
result_df

,model,species_id,display_name,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,match_score,...,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier,detected_entity_type
0,BIOMD0000000023.xml,Fru,,"[fructose, D-fructose, beta-D-fructose]",Chunk 1: The model appears to be a metabolic m...,[15824],D-fructose,"[28645, 28757, 15824, 37721, 48095]","beta-D-fructofuranose, fructose, D-fructose, D...","[0.6666666666666666, 0.3333333333333333, 0.333...",...,1.00,0.20,1,5.373753,3.784719,1.589034,None,None,is,unknown
1,BIOMD0000000023.xml,Glc,,"[glucose, D-glucose, alpha-D-glucose]",,[17634],D-glucose,"[4167, 42758, 17234, 17634, 17925]","D-glucopyranose, aldehydo-D-glucose, glucose, ...","[0.6666666666666666, 0.6666666666666666, 0.333...",...,1.00,0.20,1,5.373753,3.784719,1.589034,None,None,is,unknown
2,BIOMD0000000023.xml,HexP,,"[hexose phosphate, fructose-6-phosphate, gluco...",,"[16218, 15946, 14314, 18066]","beta-D-glucose 1-phosphate, keto-D-fructose 6-...","[47878, 16084, 15946, 88003]","hexose phosphate, beta-D-fructofuranose 6-phos...","[0.3333333333333333, 0.3333333333333333, 0.333...",...,0.25,0.25,1,5.373753,3.784719,1.589034,None,None,"hasVersion, hasVersion, hasVersion, hasVersion",unknown
3,BIOMD0000000023.xml,Suc6P,,"[sucrose-6-phosphate, sucrose phosphate, 6-pho...",,[16308],sucrose 6(F)-phosphate,"[131603, 16308]","sucrose 6(G)-phosphate, sucrose 6(F)-phosphate","[0.6666666666666666, 0.6666666666666666]",...,1.00,0.50,1,5.373753,3.784719,1.589034,None,None,is,unknown
4,BIOMD0000000023.xml,Suc,,"[sucrose, alpha-D-glucopyranosyl beta-D-fructo...",,[17992],sucrose,[17992],sucrose,[0.6666666666666666],...,1.00,1.00,1,5.373753,3.784719,1.589034,None,None,is,unknown
5,BIOMD0000000023.xml,Sucvac,,"[sucrose, vacuolar sucrose, sucrose in vacuole]",,[17992],sucrose,[17992],sucrose,[0.3333333333333333],...,1.00,1.00,1,5.373753,3.784719,1.589034,None,None,is,unknown
6,BIOMD0000000023.xml,glycolysis,,"[glycolytic pathway, glycolysis intermediate, ...",,[28013],"beta-D-fructofuranose 1,6-bisphosphate",[],NA,[],...,0.00,0.00,0,5.373753,3.784719,1.589034,None,None,is,unknown
7,BIOMD0000000023.xml,phos,,"[phosphate, inorganic phosphate, orthophosphate]",,[18367],phosphate(3-),"[18367, 26020, 26078, 35780, 43474]","phosphate(3-), phosphate, phosphoric acid, pho...","[0.6666666666666666, 0.3333333333333333, 0.333...",...,1.00,0.20,1,5.373753,3.784719,1.589034,None,None,is,unknown
8,BIOMD0000000023.xml,UDP,,"[uridine diphosphate, uridine 5'-diphosphate, ...",,[17659],UDP,"[17659, 58223]","UDP, UDP(3-)","[1.0, 0.6666666666666666]",...,1.00,0.50,1,5.373753,3.784719,1.589034,None,None,is,unknown
9,BIOMD0000000023.xml,ADP,,"[adenosine diphosphate, adenosine 5'-diphospha...",,[16761],ADP,"[16761, 456216, 177051, 73342]","ADP, ADP(3-), Adenosine_Diphosphate, Ala-Asp-Pro","[0.6666666666666666, 0.6666666666666666, 0.333...",...,1.00,0.25,1,5.373753,3.784719,1.589034,None,None,is,unknown
10,BIOMD0000000023.xml,ATP,,"[adenosine triphosphate, adenosine 5'-triphosp...",,[15422],ATP,"[15422, 30616]","ATP, ATP(4-)","[1.0, 0.3333333333333333]",...,1.00,0.50,1,5.373753,3.784719,1.589034,None,None,is,unknown
11,BIOMD0000000023.xml,Glcex,,"[glucose, extracellular glucose, external gluc...",,[17634],D-glucose,"[4167, 42758, 17234]","D-glucopyranose, aldehydo-D-glucose, glucose","[0.3333333333333333, 0.3333333333333333, 0.333...",...,0.00,0.00,1,5.373753,3.784719,1.589034,None,None,is,unknown
12,BIOMD0000000023.xml,Fruex,,"[fructose, extracellular fructose, external fr...",,[15824],D-fructose,"[28645, 28757]","beta-D-fructofuranose, fructose","[0.3333333333333333, 0.3333333333333333]",...,0.00,0.00,1,5.373753,3.784719,1.589034,None,None,is,unknown

# Test on auto detection

In [7]:
import sys
import importlib
importlib.reload(sys.modules['core.model_info'])
importlib.reload(sys.modules['utils.evaluation'])
from core.model_info import format_prompt, find_species_with_annotations_and_qualifiers
from utils.evaluation import evaluate_single_model

In [8]:
prompt = format_prompt(test_model_file, existing_annotations.keys(), 'auto')
print(prompt)

Now annotate these species:
Species to annotate: Fru, Glc, HexP, Suc6P, Suc, Sucvac, glycolysis, phos, UDP, ADP, ATP, Glcex, Fruex
Model: "Rohwer2001_Sucrose"

// Reactions:
$Fruex -> Fru
$Glcex -> Glc
$ATP + Glc -> HexP + $ADP
Fru + $ATP -> HexP + $ADP
Fru + $ATP -> HexP + $ADP
2 HexP -> $UDP + Suc6P
Suc6P -> Suc + $phos
HexP + Fru -> Suc + $UDP
Suc -> Fru + Glc
HexP -> $glycolysis
Suc -> $Sucvac

// Notes:
"SBML
Level 2 code generated for the JWS Online project by Jacky Snoep using
PySCeS
.
Run this model online at
http://jjj.biochem.sun.ac.za
.
Web-based modelling using JWS Online
, Bioinformatics, 20:2143-2144.
For more information see the
.
for more information."

For each species, determine its entity type (auto, chemical, gene, protein, complex, unknown).
Return up to 3 standardized names or common synonyms for each species, ranked by likelihood. Provide components names for complexes, which may exceed the limit of 3.
Specify the entity type in parentheses after each species ID.
Use the below format, do not include any other text except the synonyms, and give short reasons for all species after 'Reason:' by the end.

SpeciesA (entity_type): "name1", "name2", …
SpeciesB (entity_type): …
Reason: …

In [9]:
result_df = evaluate_single_model(
    model_file=test_model_file,
    llm_model=llm_model,
    method = 'rag',
    top_k = 3,
    entity_type='auto',
    database=["chebi", "uniprot"],
    save_llm_results=False,
    output_dir=output_dir,
    verbose=True
)

2026-08-28 16:29:38,955 - INFO - Evaluating model: BIOMD0000000023.xml
2026-08-28 16:29:38,957 - INFO - Using default tax_id: 9606
2026-08-28 16:29:39,051 - INFO - Evaluating 13 entities in BIOMD0000000023.xml
2026-08-28 16:30:44,500 - INFO - Detected entity types: {'chemical': 11, 'unknown': 2}
2026-08-28 16:30:44,503 - INFO - Searching chebi for 11 chemical entities
2026-08-28 16:30:44,535 - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2026-08-28 16:30:44,928 - INFO - Load pretrained SentenceTransformer: all-MiniLM-L6-v2

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-08-28 16:30:48,923 - WARNING - There are 2 species with unknown entity type: ['Sucvac', 'glycolysis']

In [10]:
result_df

,model,species_id,display_name,detected_entity_type,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,...,precision_formula,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier
0,BIOMD0000000023.xml,Fru,,chemical,"[fructose, D-fructose, fructopyranose]","Chunk 1: Fru, Glc, HexP, Suc6P, Suc, phos, UDP...",[15824],D-fructose,"[28757, 28645, 48095]","fructose, beta-D-fructofuranose, keto-D-fructose",...,1.0,0.00,0.000000,1,69.829449,65.406248,4.423201,9606,None,is
1,BIOMD0000000023.xml,Glc,,chemical,"[glucose, D-glucose, glucopyranose]",,[17634],D-glucose,"[4167, 42758, 17234]","D-glucopyranose, aldehydo-D-glucose, glucose",...,1.0,0.00,0.000000,1,69.829449,65.406248,4.423201,9606,None,is
2,BIOMD0000000023.xml,HexP,,chemical,"[hexose phosphate, glucose-6-phosphate, fructo...",,"[16218, 15946, 14314, 18066]","beta-D-glucose 1-phosphate, keto-D-fructose 6-...","[47878, 16084, 15946]","hexose phosphate, beta-D-fructofuranose 6-phos...",...,1.0,0.25,0.333333,1,69.829449,65.406248,4.423201,9606,None,"hasVersion, hasVersion, hasVersion, hasVersion"
3,BIOMD0000000023.xml,Suc6P,,chemical,"[sucrose-6-phosphate, sucrose 6-phosphate, C12...",,[16308],sucrose 6(F)-phosphate,"[131603, 16308, 84067]","sucrose 6(G)-phosphate, sucrose 6(F)-phosphate...",...,0.5,1.00,0.333333,1,69.829449,65.406248,4.423201,9606,None,is
4,BIOMD0000000023.xml,Suc,,chemical,"[sucrose, table sugar, β-D-glucopyranosyl-(1→2...",,[17992],sucrose,"[17992, 32528, 50661]","sucrose, turanose, loliose",...,0.5,1.00,0.333333,1,69.829449,65.406248,4.423201,9606,None,is
5,BIOMD0000000023.xml,phos,,chemical,"[phosphate, inorganic phosphate, Pi]",,[18367],phosphate(3-),"[26078, 35780, 43474]","phosphoric acid, phosphate ion, hydrogenphosphate",...,1.0,0.00,0.000000,1,69.829449,65.406248,4.423201,9606,None,is
6,BIOMD0000000023.xml,UDP,,chemical,"[uridine diphosphate, UDP, uridine-5′-diphosph...",,[17659],UDP,"[17659, 15713, 58223]","UDP, UTP, UDP(3-)",...,0.5,1.00,0.333333,1,69.829449,65.406248,4.423201,9606,None,is
7,BIOMD0000000023.xml,ADP,,chemical,"[adenosine diphosphate, ADP, adenosine-5′-diph...",,[16761],ADP,"[16761, 456216, 73342]","ADP, ADP(3-), Ala-Asp-Pro",...,0.5,1.00,0.333333,1,69.829449,65.406248,4.423201,9606,None,is
8,BIOMD0000000023.xml,ATP,,chemical,"[adenosine triphosphate, ATP, adenosine-5′-tri...",,[15422],ATP,"[15422, 30616, 27775]","ATP, ATP(4-), P(1),P(3)-bis(5'-adenosyl) triph...",...,0.5,1.00,0.333333,1,69.829449,65.406248,4.423201,9606,None,is
9,BIOMD0000000023.xml,Glcex,,chemical,"[extracellular glucose, Glc_ex, glucose (extra...",,[17634],D-glucose,"[4167, 42758, 17234]","D-glucopyranose, aldehydo-D-glucose, glucose",...,1.0,0.00,0.000000,1,69.829449,65.406248,4.423201,9606,None,is
10,BIOMD0000000023.xml,Fruex,,chemical,"[extracellular fructose, Fru_ex, fructose (ext...",,[15824],D-fructose,"[28757, 28645, 136629]","fructose, beta-D-fructofuranose, N-(1-Deoxy-1-...",...,0.5,0.00,0.000000,1,69.829449,65.406248,4.423201,9606,None,is
11,BIOMD0000000023.xml,Sucvac,,unknown,"[sucrose vacuole, sucrose storage compartment,...",,[17992],sucrose,[],NA,...,0.0,0.00,0.000000,0,69.829449,65.406248,4.423201,9606,None,is
12,BIOMD0000000023.xml,glycolysis,,unknown,"[glycolytic pathway, Embden-Meyerhof pathway, ...",,[28013],"beta-D-fructofuranose 1,6-bisphosphate",[],NA,...,0.0,0.00,0.000000,0,69.829449,65.406248,4.423201,9606,None,is

In [8]:
from core.llm_interface import SYSTEM_PROMPT, query_llm, parse_llm_response, get_system_prompt
llm_response = """
Ca_cyt (chemical): "calcium(2+)", "calcium ion", "Ca2+"
CaER (chemical): "calcium", "endoplasmic reticulum calcium", "Ca2+ in endoplasmic reticulum"
CaM (chemical): "calmodulin", "calcium-modulated protein", "CaM protein"
CaPr (complex): "calcium-protein complex", "protein-calcium complex", "calcium bound protein"

Reason: The model "Marhl2000_CaOscillations" suggests a focus on calcium oscillations
"""
chunk_synonyms_dict, chunk_entity_type_dict, chunk_reason = parse_llm_response(llm_response)

In [29]:
# Test with a single model using automatic entity type detection
recommendations_df, metrics = annotate_model(
    model_file=test_model_file,
    llm_model=llm_model,
    method="direct",
    top_k=3,
    entity_type="auto",
    database=["chebi", "uniprot"]
)

2025-11-17 14:57:08,492 - INFO - Starting annotation for model: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels/BIOMD0000000039.xml
2025-11-17 14:57:08,493 - INFO - Using LLM model: Llama-3.3-70B-Instruct
2025-11-17 14:57:08,493 - INFO - Using method: direct for database search
2025-11-17 14:57:08,494 - INFO - Entity type: auto, Database: ['chebi', 'uniprot']
2025-11-17 14:57:08,494 - INFO - >>>Step 1: Getting species from model...<<<
2025-11-17 14:57:08,500 - INFO - Found 5 species in model
2025-11-17 14:57:08,501 - WARNING - Entity type auto with database ['chebi', 'uniprot'] not yet supported
2025-11-17 14:57:08,501 - INFO - Annotate all 5 entities
2025-11-17 14:57:08,501 - INFO - >>>Step 2: Extracting model context...<<<
2025-11-17 14:57:08,526 - INFO - Extracted context for model: Marhl2000_CaOscillations
2025-11-17 14:57:08,526 - INFO - >>>Step 3: Querying LLM (Llama-3.3-70B-Instruct)...<<<
2025-11-17 14:57:08,546 - WARNING - Auto entity type detection not yet implemented
2025-11-17 14:57:08,547 - ERROR - Failed to format prompt

## uniprot

In [2]:
test_model_file = "/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106/BIOMD0000000137.xml"
tax_id = 9606
# Check if test model exist
if os.path.exists(test_model_file):
    print(f"✓ Test model found: {test_model_file}")
else:
    print(f"✗ Test model not found: {test_model_file}")

✓ Test model found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106/BIOMD0000000137.xml

In [3]:
# Running with auto entity type
result_df = evaluate_single_model(
    model_file=test_model_file,
    tax_id=tax_id,
    llm_model=llm_model,
    entity_type='auto',
    database='uniprot',
    save_llm_results=False,
    output_dir=output_dir
)

2025-12-11 17:30:12,649 - INFO - Evaluating model: BIOMD0000000137.xml
2025-12-11 17:30:12,650 - INFO - Using organism-specific search for tax_id: 9606
2025-12-11 17:30:12,676 - INFO - Evaluating 18 entities in BIOMD0000000137.xml
2025-12-11 17:30:17,355 - INFO - HTTP Request: POST https://api.llama.com/compat/v1/chat/completions "HTTP/1.1 200 OK"
2025-12-11 17:30:17,366 - INFO - Detected entity types: {'chemical': 1, 'protein': 13, 'complex': 4}
2025-12-11 17:30:17,366 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-11 17:30:17,366 - WARNING - No valid database found for entity type 'chemical' in ['uniprot'] for 1 species
2025-12-11 17:30:17,367 - INFO - Searching uniprot for 13 protein entities
2025-12-11 17:30:17,643 - INFO - Searching all databases ['uniprot'] for 4 complex entities

In [4]:
result_df

,model,species_id,display_name,detected_entity_type,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,...,precision_formula,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier
0,BIOMD0000000137.xml,x1,Insulin,chemical,"[Insulin, human insulin, insulin hormone]","Chunk 1: x1 is a hormone (chemical), x2 is a r...",[P01308],INS,[],NA,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,is
1,BIOMD0000000137.xml,x2,Unbound Insulin Receptor,protein,"[Insulin receptor, INSR, CD220]",,[P06213],INSR,"[P01308, P06213]","INS, INSR",...,0.5,1.0,0.5,1,4.963253,4.643137,0.320116,9606,None,isVersionOf
2,BIOMD0000000137.xml,x6,Unbound unphosphorylated intracellular receptor,protein,"[Insulin receptor substrate, IRS, IRS-1]",,[P06213],INSR,"[P01308, P41252, P35568]","INS, IARS1, IRS1",...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
3,BIOMD0000000137.xml,x7,Phosphorylated twice bound intracellular receptor,protein,"[Phosphorylated IRS, pIRS, IRS-1]",,[P06213],INSR,"[P41252, P35568]","IARS1, IRS1",...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
4,BIOMD0000000137.xml,x8,Phosphorylated once bound intracellular receptor,protein,"[Phosphorylated IRS, pIRS, IRS-1]",,[P06213],INSR,"[P41252, P35568]","IARS1, IRS1",...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
5,BIOMD0000000137.xml,x9,Unphosphorylated IRS1,protein,"[IRS1, Insulin receptor substrate 1, IRS-1]",,[P35568],IRS1,[P35568],IRS1,...,1.0,1.0,1.0,1,4.963253,4.643137,0.320116,9606,None,isVersionOf
6,BIOMD0000000137.xml,x10,Phosphorylated IRS1,protein,"[Phosphorylated IRS1, pIRS1, IRS-1]",,[P35568],IRS1,[P35568],IRS1,...,1.0,1.0,1.0,1,4.963253,4.643137,0.320116,9606,None,isVersionOf
7,BIOMD0000000137.xml,x11,PI3 Kinase,protein,"[PI3K, Phosphatidylinositol 3-kinase, PI3 kinase]",,[Q8WYR1],PIK3R5,[P19957],PI3,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
8,BIOMD0000000137.xml,x16,Unactivated Akt,protein,"[Akt, Protein kinase B, PKB]",,[Q9Y243],AKT3,[P31749],AKT1,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
9,BIOMD0000000137.xml,x17,Activated Akt,protein,"[Phosphorylated Akt, pAkt, Akt1]",,[Q9Y243],AKT3,[P31749],AKT1,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
10,BIOMD0000000137.xml,x18,Unactivated PKC,protein,"[PKC, Protein kinase C, PRKCA]",,[P41743],PRKCI,[P17252],PRKCA,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
11,BIOMD0000000137.xml,x19,Activated PKC,protein,"[Phosphorylated PKC, pPKC, PRKCA]",,[P41743],PRKCI,[P17252],PRKCA,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
12,BIOMD0000000137.xml,x20,Intracellular GLUT4,protein,"[GLUT4, Glucose transporter type 4, SLC2A4]",,[P14672],SLC2A4,[P14672],SLC2A4,...,1.0,1.0,1.0,1,4.963253,4.643137,0.320116,9606,None,isVersionOf
13,BIOMD0000000137.xml,x21,Cell surface GLUT4,protein,"[GLUT4, Glucose transporter type 4, SLC2A4]",,[P14672],SLC2A4,[P14672],SLC2A4,...,1.0,1.0,1.0,1,4.963253,4.643137,0.320116,9606,None,isVersionOf
14,BIOMD0000000137.xml,x3,Unphosphorylated once bound receptor,complex,"[Insulin, Insulin receptor]",,[P06213],INSR,[P01308],INS,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
15,BIOMD0000000137.xml,x5,Phosphorylated once bound receptor,complex,"[Insulin, Insulin receptor]",,[P06213],INSR,[P01308],INS,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
16,BIOMD0000000137.xml,x4,Phosphorylated twice bound receptor,complex,"[Insulin, Insulin receptor]",,[P06213],INSR,[P01308],INS,...,0.0,0.0,0.0,0,4.963253,4.643137,0.320116,9606,None,isVersionOf
17,BIOMD0000000137.xml,x12,IRS1- PI3 Kinase Complex,complex,"[PI3K, Phosphorylated IRS1, IRS1]",,"[P35568, Q8WYR1]","IRS1, PIK3R5",[P35568],IRS1,...,1.0,0.5,1.0,1,4.963253,4.643137,0.320116,9606,None,"hasPart, hasPart"

In [5]:
# Running with auto entity type
result_df = evaluate_single_model(
    model_file=test_model_file,
    tax_id=tax_id,
    llm_model=llm_model,
    entity_type='auto',
    database=['chebi', 'uniprot'],
    save_llm_results=False,
    output_dir=output_dir
)

2025-12-10 12:49:39,955 - INFO - Evaluating model: BIOMD0000000137.xml
2025-12-10 12:49:39,955 - INFO - Using organism-specific search for tax_id: 9606
2025-12-10 12:49:40,043 - INFO - Evaluating 21 entities in BIOMD0000000137.xml
2025-12-10 12:49:45,437 - INFO - HTTP Request: POST https://api.llama.com/compat/v1/chat/completions "HTTP/1.1 200 OK"
2025-12-10 12:49:45,438 - INFO - Detected entity types: {'chemical': 4, 'protein': 16, 'complex': 1}
2025-12-10 12:49:45,439 - INFO - Searching chebi for 4 chemical entities
2025-12-10 12:49:46,359 - INFO - Searching uniprot for 16 protein entities
2025-12-10 12:49:46,501 - INFO - Searching all databases ['chebi', 'uniprot'] for 1 complex entities

In [6]:
result_df

,model,species_id,display_name,detected_entity_type,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,...,precision_formula,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier
0,BIOMD0000000137.xml,x13,"PI3,4,5P3",chemical,"[Phosphatidylinositol (3,4,5)-trisphosphate, P...",Chunk 1: The entity types were determined base...,[16618],"1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosp...",[16618],"1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosp...",...,1.0,1.0,1.0,1,6.49642,5.355494,1.140926,9606,None,is
1,BIOMD0000000137.xml,x14,"PI4,5P2",chemical,"[Phosphatidylinositol 4,5-bisphosphate, PIP2, ...",,[18348],"1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate","[18348, 232300]","1-phosphatidyl-1D-myo-inositol 4,5-bisphosphat...",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,is
2,BIOMD0000000137.xml,x15,"PI3,4P2",chemical,"[Phosphatidylinositol (3,4)-bisphosphate, PI(3...",,[16152],"1-phosphatidyl-1D-myo-inositol 3,4-bisphosphate",[],NA,...,0.0,0.0,0.0,0,6.49642,5.355494,1.140926,9606,None,is
3,BIOMD0000000137.xml,x1,Insulin,chemical,"[Insulin, human insulin, insulin hormone]",,[P01308],INS,"[5931, 145810]","insulin (human), insulin",...,0.0,0.0,0.0,0,6.49642,5.355494,1.140926,9606,None,is
4,BIOMD0000000137.xml,x2,Unbound Insulin Receptor,protein,"[Insulin receptor, INSR, IR]",,[P06213],INSR,"[P06213, P01308]","INSR, INS",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
5,BIOMD0000000137.xml,x3,Unphosphorylated once bound receptor,protein,"[Unphosphorylated insulin receptor, Insulin re...",,[P06213],INSR,"[P01308, P06213]","INS, INSR",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
6,BIOMD0000000137.xml,x5,Phosphorylated once bound receptor,protein,"[Phosphorylated insulin receptor, Insulin rece...",,[P06213],INSR,"[P01308, P06213]","INS, INSR",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
7,BIOMD0000000137.xml,x4,Phosphorylated twice bound receptor,protein,"[Phosphorylated insulin receptor, Insulin rece...",,[P06213],INSR,"[P01308, P06213]","INS, INSR",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
8,BIOMD0000000137.xml,x6,Unbound unphosphorylated intracellular receptor,protein,[Unbound unphosphorylated intracellular recept...,,[P06213],INSR,"[P01308, P06213]","INS, INSR",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
9,BIOMD0000000137.xml,x7,Phosphorylated twice bound intracellular receptor,protein,[Phosphorylated twice bound intracellular rece...,,[P06213],INSR,"[P01308, P06213]","INS, INSR",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
10,BIOMD0000000137.xml,x8,Phosphorylated once bound intracellular receptor,protein,[Phosphorylated once bound intracellular recep...,,[P06213],INSR,"[P01308, P06213]","INS, INSR",...,0.5,1.0,0.5,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
11,BIOMD0000000137.xml,x9,Unphosphorylated IRS1,protein,"[IRS1, Insulin receptor substrate 1, IRS-1]",,[P35568],IRS1,[P35568],IRS1,...,1.0,1.0,1.0,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
12,BIOMD0000000137.xml,x10,Phosphorylated IRS1,protein,"[Phosphorylated IRS1, IRS1, Insulin receptor s...",,[P35568],IRS1,[P35568],IRS1,...,1.0,1.0,1.0,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
13,BIOMD0000000137.xml,x11,PI3 Kinase,protein,"[PI3K, Phosphatidylinositol 3-kinase, PI3 kinase]",,[Q8WYR1],PIK3R5,[P19957],PI3,...,0.0,0.0,0.0,0,6.49642,5.355494,1.140926,9606,None,isVersionOf
14,BIOMD0000000137.xml,x16,Unactivated Akt,protein,"[Akt, Protein kinase B, PKB]",,[Q9Y243],AKT3,[P31749],AKT1,...,0.0,0.0,0.0,0,6.49642,5.355494,1.140926,9606,None,isVersionOf
15,BIOMD0000000137.xml,x17,Activated Akt,protein,"[Phosphorylated Akt, Akt, Protein kinase B]",,[Q9Y243],AKT3,[],NA,...,0.0,0.0,0.0,0,6.49642,5.355494,1.140926,9606,None,isVersionOf
16,BIOMD0000000137.xml,x18,Unactivated PKC,protein,"[PKC, Protein kinase C, PRKCA]",,[P41743],PRKCI,[P17252],PRKCA,...,0.0,0.0,0.0,0,6.49642,5.355494,1.140926,9606,None,isVersionOf
17,BIOMD0000000137.xml,x19,Activated PKC,protein,"[Phosphorylated PKC, PKC, Protein kinase C]",,[P41743],PRKCI,[],NA,...,0.0,0.0,0.0,0,6.49642,5.355494,1.140926,9606,None,isVersionOf
18,BIOMD0000000137.xml,x20,Intracellular GLUT4,protein,"[GLUT4, Glucose transporter type 4, SLC2A4]",,[P14672],SLC2A4,[P14672],SLC2A4,...,1.0,1.0,1.0,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
19,BIOMD0000000137.xml,x21,Cell surface GLUT4,protein,"[Cell surface GLUT4, GLUT4, Glucose transporte...",,[P14672],SLC2A4,[P14672],SLC2A4,...,1.0,1.0,1.0,1,6.49642,5.355494,1.140926,9606,None,isVersionOf
20,BIOMD0000000137.xml,x12,IRS1- PI3 Kinase Complex,complex,"[IRS1, PI3K, Phosphatidylinositol 3-kinase]",,"[P35568, Q8WYR1]","IRS1, PIK3R5",[P35568],IRS1,...,1.0,0.5,1.0,1,6.49642,5.355494,1.140926,9606,None,"hasPart, hasPart"

# Batch evaluation
## chebi

In [2]:
model_dir = "/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106"
# model_dir = "test_models"
# Check if model directory exists
if os.path.exists(model_dir):
    model_files = [f for f in os.listdir(model_dir) if f.endswith('.xml')]
    print(f"✓ Model directory found: {model_dir}")
    print(f"  - Found {len(model_files)} XML files")
    # print(f"  - Will test first {min(num_models_to_test, len(model_files))} models")

✓ Model directory found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106
  - Found 1075 XML files

In [ ]:
# Run batch evaluation on updated BioModels
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database='chebi',
    method="rag",
    top_k = 3,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv",
    start_at=1
)

In [ ]:
# Run batch evaluation 
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database='chebi',
    method="rag",
    top_k = 10,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts_updated.csv",
    start_at=1
)

In [ ]:
# Run batch evaluation on updated BioModels
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model=llm_model,
    entity_type='auto',
    database='chebi',
    method="rag",
    top_k = 10,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi_rag_llama-3_top10_autoType.csv",
    start_at=1
)

In [5]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-3_top10_autoType.csv")

Filtered results to 9312 entries that exist in reference: /Users/luna/Desktop/CRBM/AMAS_proj/Results/biomd_species_accuracy_AMAS.csv
Number of models assessed: 303
Number of models with predictions: 303
Number of annotations evaluated: 9312
Average accuracy (per model): 0.94
Ave. recall (formula): 0.94
Ave. precision (formula): 0.23
Ave. recall (exact): 0.88
Ave. precision (exact): 0.09
Average accuracy (per species): 0.94
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.22
Ave. recall (exact, per species): 0.74
Ave. precision (exact, per species): 0.11
Ave. total time (per model): 21.80
Ave. total time (per element, per model): 0.71
Ave. LLM time (per model): 21.00
Ave. LLM time (per element, per model): 0.68
Average number of predictions per species: 9.94

## Uniprot

In [4]:
# Run batch evaluation on updated BioModels
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database='uniprot',
    method="direct",
    top_k = 3,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_uniprot_direct_llama-4_top3_autoType_complex_improved.csv",
    start_at=1,
    tax_id = 9606
)

2025-12-07 13:30:55,663 - WARNING - Skipping BIOMD0000000001.xml - no results generated
2025-12-07 13:30:55,674 - WARNING - Skipping BIOMD0000000002.xml - no results generated
2025-12-07 13:30:55,680 - WARNING - Skipping BIOMD0000000003.xml - no results generated
2025-12-07 13:30:55,684 - WARNING - Skipping BIOMD0000000004.xml - no results generated
2025-12-07 13:30:55,691 - WARNING - Skipping BIOMD0000000005.xml - no results generated
2025-12-07 13:30:55,695 - WARNING - Skipping BIOMD0000000006.xml - no results generated
2025-12-07 13:30:55,707 - WARNING - Skipping BIOMD0000000007.xml - no results generated
2025-12-07 13:30:55,713 - WARNING - Skipping BIOMD0000000008.xml - no results generated
2025-12-07 13:30:55,724 - WARNING - Skipping BIOMD0000000009.xml - no results generated
2025-12-07 13:30:55,730 - WARNING - Skipping BIOMD0000000010.xml - no results generated
2025-12-07 13:30:55,744 - WARNING - Skipping BIOMD0000000011.xml - no results generated
2025-12-07 13:30:55,751 - WARNING - Skipping BIOMD0000000012.xml - no results generated
2025-12-07 13:30:55,768 - WARNING - Skipping BIOMD0000000013.xml - no results generated
2025-12-07 13:30:55,841 - WARNING - Skipping BIOMD0000000014.xml - no results generated

LLM results will be saved to: ./autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330
Saved configuration to ./autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/config.txt
Evaluating 1/1075: BIOMD0000000001.xml
Evaluating 2/1075: BIOMD0000000002.xml
Evaluating 3/1075: BIOMD0000000003.xml
Evaluating 4/1075: BIOMD0000000004.xml
Evaluating 5/1075: BIOMD0000000005.xml
Evaluating 6/1075: BIOMD0000000006.xml
Evaluating 7/1075: BIOMD0000000007.xml
Evaluating 8/1075: BIOMD0000000008.xml
Evaluating 9/1075: BIOMD0000000009.xml
Evaluating 10/1075: BIOMD0000000010.xml
Evaluating 11/1075: BIOMD0000000011.xml
Evaluating 12/1075: BIOMD0000000012.xml
Evaluating 13/1075: BIOMD0000000013.xml
Evaluating 14/1075: BIOMD0000000014.xml
Evaluating 15/1075: BIOMD0000000015.xml

2025-12-07 13:30:55,859 - WARNING - Skipping BIOMD0000000015.xml - no results generated
2025-12-07 13:30:55,865 - WARNING - Skipping BIOMD0000000016.xml - no results generated
2025-12-07 13:30:55,875 - WARNING - Skipping BIOMD0000000017.xml - no results generated

Evaluating 16/1075: BIOMD0000000016.xml
Evaluating 17/1075: BIOMD0000000017.xml
Evaluating 18/1075: BIOMD0000000018.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000018.txt
Evaluating 19/1075: BIOMD0000000019.xml

2025-12-07 13:31:03,599 - WARNING - Skipping BIOMD0000000020.xml - no results generated
2025-12-07 13:31:03,608 - WARNING - Skipping BIOMD0000000021.xml - no results generated
2025-12-07 13:31:03,619 - WARNING - Skipping BIOMD0000000022.xml - no results generated
2025-12-07 13:31:03,628 - WARNING - Skipping BIOMD0000000023.xml - no results generated
2025-12-07 13:31:03,631 - WARNING - Skipping BIOMD0000000024.xml - no results generated
2025-12-07 13:31:03,635 - WARNING - Skipping BIOMD0000000025.xml - no results generated
2025-12-07 13:31:03,641 - WARNING - Skipping BIOMD0000000026.xml - no results generated
2025-12-07 13:31:03,645 - WARNING - Skipping BIOMD0000000027.xml - no results generated
2025-12-07 13:31:03,655 - WARNING - Skipping BIOMD0000000028.xml - no results generated
2025-12-07 13:31:03,660 - WARNING - Skipping BIOMD0000000029.xml - no results generated
2025-12-07 13:31:03,670 - WARNING - Skipping BIOMD0000000030.xml - no results generated
2025-12-07 13:31:03,674 - WARNING - Skipping BIOMD0000000031.xml - no results generated
2025-12-07 13:31:03,693 - WARNING - Skipping BIOMD0000000032.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000019.txt
Evaluating 20/1075: BIOMD0000000020.xml
Evaluating 21/1075: BIOMD0000000021.xml
Evaluating 22/1075: BIOMD0000000022.xml
Evaluating 23/1075: BIOMD0000000023.xml
Evaluating 24/1075: BIOMD0000000024.xml
Evaluating 25/1075: BIOMD0000000025.xml
Evaluating 26/1075: BIOMD0000000026.xml
Evaluating 27/1075: BIOMD0000000027.xml
Evaluating 28/1075: BIOMD0000000028.xml
Evaluating 29/1075: BIOMD0000000029.xml
Evaluating 30/1075: BIOMD0000000030.xml
Evaluating 31/1075: BIOMD0000000031.xml
Evaluating 32/1075: BIOMD0000000032.xml
Evaluating 33/1075: BIOMD0000000033.xml

2025-12-07 13:31:05,820 - WARNING - Skipping BIOMD0000000034.xml - no results generated
2025-12-07 13:31:05,828 - WARNING - Skipping BIOMD0000000035.xml - no results generated
2025-12-07 13:31:05,831 - WARNING - Skipping BIOMD0000000036.xml - no results generated
2025-12-07 13:31:05,836 - WARNING - Skipping BIOMD0000000037.xml - no results generated
2025-12-07 13:31:05,844 - WARNING - Skipping BIOMD0000000038.xml - no results generated
2025-12-07 13:31:05,848 - WARNING - Skipping BIOMD0000000039.xml - no results generated
2025-12-07 13:31:05,851 - WARNING - Skipping BIOMD0000000040.xml - no results generated
2025-12-07 13:31:05,858 - WARNING - Skipping BIOMD0000000041.xml - no results generated
2025-12-07 13:31:05,869 - WARNING - Skipping BIOMD0000000042.xml - no results generated
2025-12-07 13:31:05,875 - WARNING - Skipping BIOMD0000000043.xml - no results generated
2025-12-07 13:31:05,880 - WARNING - Skipping BIOMD0000000044.xml - no results generated
2025-12-07 13:31:05,885 - WARNING - Skipping BIOMD0000000045.xml - no results generated
2025-12-07 13:31:05,892 - WARNING - Skipping BIOMD0000000046.xml - no results generated
2025-12-07 13:31:05,896 - WARNING - Skipping BIOMD0000000047.xml - no results generated
2025-12-07 13:31:05,910 - WARNING - Skipping BIOMD0000000048.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000033.txt
Evaluating 34/1075: BIOMD0000000034.xml
Evaluating 35/1075: BIOMD0000000035.xml
Evaluating 36/1075: BIOMD0000000036.xml
Evaluating 37/1075: BIOMD0000000037.xml
Evaluating 38/1075: BIOMD0000000038.xml
Evaluating 39/1075: BIOMD0000000039.xml
Evaluating 40/1075: BIOMD0000000040.xml
Evaluating 41/1075: BIOMD0000000041.xml
Evaluating 42/1075: BIOMD0000000042.xml
Evaluating 43/1075: BIOMD0000000043.xml
Evaluating 44/1075: BIOMD0000000044.xml
Evaluating 45/1075: BIOMD0000000045.xml
Evaluating 46/1075: BIOMD0000000046.xml
Evaluating 47/1075: BIOMD0000000047.xml
Evaluating 48/1075: BIOMD0000000048.xml
Evaluating 49/1075: BIOMD0000000049.xml

2025-12-07 13:31:07,769 - WARNING - Skipping BIOMD0000000050.xml - no results generated
2025-12-07 13:31:07,787 - WARNING - Skipping BIOMD0000000051.xml - no results generated
2025-12-07 13:31:07,791 - WARNING - Skipping BIOMD0000000052.xml - no results generated
2025-12-07 13:31:07,794 - WARNING - Skipping BIOMD0000000053.xml - no results generated
2025-12-07 13:31:07,799 - WARNING - Skipping BIOMD0000000054.xml - no results generated
2025-12-07 13:31:07,812 - WARNING - Skipping BIOMD0000000055.xml - no results generated
2025-12-07 13:31:07,847 - WARNING - Skipping BIOMD0000000056.xml - no results generated
2025-12-07 13:31:07,852 - WARNING - Skipping BIOMD0000000057.xml - no results generated
2025-12-07 13:31:07,858 - WARNING - Skipping BIOMD0000000058.xml - no results generated
2025-12-07 13:31:07,868 - WARNING - Skipping BIOMD0000000059.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000049.txt
Evaluating 50/1075: BIOMD0000000050.xml
Evaluating 51/1075: BIOMD0000000051.xml
Evaluating 52/1075: BIOMD0000000052.xml
Evaluating 53/1075: BIOMD0000000053.xml
Evaluating 54/1075: BIOMD0000000054.xml
Evaluating 55/1075: BIOMD0000000055.xml
Evaluating 56/1075: BIOMD0000000056.xml
Evaluating 57/1075: BIOMD0000000057.xml
Evaluating 58/1075: BIOMD0000000058.xml
Evaluating 59/1075: BIOMD0000000059.xml
Evaluating 60/1075: BIOMD0000000060.xml

2025-12-07 13:31:09,544 - WARNING - Skipping BIOMD0000000061.xml - no results generated
2025-12-07 13:31:09,549 - WARNING - Skipping BIOMD0000000062.xml - no results generated
2025-12-07 13:31:09,563 - WARNING - Skipping BIOMD0000000063.xml - no results generated
2025-12-07 13:31:09,582 - WARNING - Skipping BIOMD0000000064.xml - no results generated
2025-12-07 13:31:09,591 - WARNING - Skipping BIOMD0000000065.xml - no results generated
2025-12-07 13:31:09,604 - WARNING - Skipping BIOMD0000000066.xml - no results generated
2025-12-07 13:31:09,611 - WARNING - Skipping BIOMD0000000067.xml - no results generated
2025-12-07 13:31:09,616 - WARNING - Skipping BIOMD0000000068.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000060.txt
Evaluating 61/1075: BIOMD0000000061.xml
Evaluating 62/1075: BIOMD0000000062.xml
Evaluating 63/1075: BIOMD0000000063.xml
Evaluating 64/1075: BIOMD0000000064.xml
Evaluating 65/1075: BIOMD0000000065.xml
Evaluating 66/1075: BIOMD0000000066.xml
Evaluating 67/1075: BIOMD0000000067.xml
Evaluating 68/1075: BIOMD0000000068.xml
Evaluating 69/1075: BIOMD0000000069.xml

2025-12-07 13:31:12,527 - WARNING - Skipping BIOMD0000000070.xml - no results generated
2025-12-07 13:31:12,539 - WARNING - Skipping BIOMD0000000071.xml - no results generated
2025-12-07 13:31:12,544 - WARNING - Skipping BIOMD0000000072.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000069.txt
Evaluating 70/1075: BIOMD0000000070.xml
Evaluating 71/1075: BIOMD0000000071.xml
Evaluating 72/1075: BIOMD0000000072.xml
Evaluating 73/1075: BIOMD0000000073.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000073.txt
Evaluating 74/1075: BIOMD0000000074.xml

2025-12-07 13:31:24,589 - WARNING - Skipping BIOMD0000000075.xml - no results generated
2025-12-07 13:31:24,592 - WARNING - Skipping BIOMD0000000076.xml - no results generated
2025-12-07 13:31:24,597 - WARNING - Skipping BIOMD0000000077.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000074.txt
Evaluating 75/1075: BIOMD0000000075.xml
Evaluating 76/1075: BIOMD0000000076.xml
Evaluating 77/1075: BIOMD0000000077.xml
Evaluating 78/1075: BIOMD0000000078.xml

2025-12-07 13:31:32,654 - WARNING - Skipping BIOMD0000000079.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000078.txt
Evaluating 79/1075: BIOMD0000000079.xml
Evaluating 80/1075: BIOMD0000000080.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000080.txt
Evaluating 81/1075: BIOMD0000000081.xml

2025-12-07 13:31:37,099 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000081.txt
Evaluating 82/1075: BIOMD0000000082.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000082.txt
Evaluating 83/1075: BIOMD0000000083.xml

2025-12-07 13:31:44,961 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000083.txt
Evaluating 84/1075: BIOMD0000000084.xml

2025-12-07 13:31:47,742 - WARNING - Skipping BIOMD0000000085.xml - no results generated
2025-12-07 13:31:47,752 - WARNING - Skipping BIOMD0000000086.xml - no results generated
2025-12-07 13:31:47,771 - WARNING - Skipping BIOMD0000000087.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000084.txt
Evaluating 85/1075: BIOMD0000000085.xml
Evaluating 86/1075: BIOMD0000000086.xml
Evaluating 87/1075: BIOMD0000000087.xml
Evaluating 88/1075: BIOMD0000000088.xml

2025-12-07 13:32:17,369 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:32:17,996 - WARNING - Skipping BIOMD0000000089.xml - no results generated
2025-12-07 13:32:18,006 - WARNING - Skipping BIOMD0000000090.xml - no results generated
2025-12-07 13:32:18,014 - WARNING - Skipping BIOMD0000000091.xml - no results generated
2025-12-07 13:32:18,017 - WARNING - Skipping BIOMD0000000092.xml - no results generated
2025-12-07 13:32:18,036 - WARNING - Skipping BIOMD0000000093.xml - no results generated
2025-12-07 13:32:18,054 - WARNING - Skipping BIOMD0000000094.xml - no results generated
2025-12-07 13:32:18,071 - WARNING - Skipping BIOMD0000000095.xml - no results generated
2025-12-07 13:32:18,089 - WARNING - Skipping BIOMD0000000096.xml - no results generated
2025-12-07 13:32:18,107 - WARNING - Skipping BIOMD0000000097.xml - no results generated
2025-12-07 13:32:18,112 - WARNING - Skipping BIOMD0000000098.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000088.txt
Evaluating 89/1075: BIOMD0000000089.xml
Evaluating 90/1075: BIOMD0000000090.xml
Evaluating 91/1075: BIOMD0000000091.xml
Evaluating 92/1075: BIOMD0000000092.xml
Evaluating 93/1075: BIOMD0000000093.xml
Evaluating 94/1075: BIOMD0000000094.xml
Evaluating 95/1075: BIOMD0000000095.xml
Evaluating 96/1075: BIOMD0000000096.xml
Evaluating 97/1075: BIOMD0000000097.xml
Evaluating 98/1075: BIOMD0000000098.xml
Evaluating 99/1075: BIOMD0000000099.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000099.txt
Evaluating 100/1075: BIOMD0000000100.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000100.txt
Evaluating 101/1075: BIOMD0000000101.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000101.txt
Evaluating 102/1075: BIOMD0000000102.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000102.txt
Evaluating 103/1075: BIOMD0000000103.xml

2025-12-07 13:32:36,730 - WARNING - Skipping BIOMD0000000104.xml - no results generated
2025-12-07 13:32:36,751 - WARNING - Skipping BIOMD0000000105.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000103.txt
Evaluating 104/1075: BIOMD0000000104.xml
Evaluating 105/1075: BIOMD0000000105.xml
Evaluating 106/1075: BIOMD0000000106.xml

2025-12-07 13:32:40,884 - WARNING - Skipping BIOMD0000000107.xml - no results generated
2025-12-07 13:32:40,888 - WARNING - Skipping BIOMD0000000108.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000106.txt
Evaluating 107/1075: BIOMD0000000107.xml
Evaluating 108/1075: BIOMD0000000108.xml
Evaluating 109/1075: BIOMD0000000109.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000109.txt
Evaluating 110/1075: BIOMD0000000110.xml

2025-12-07 13:32:57,396 - WARNING - Skipping BIOMD0000000111.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000110.txt
Evaluating 111/1075: BIOMD0000000111.xml
Evaluating 112/1075: BIOMD0000000112.xml

2025-12-07 13:33:02,445 - WARNING - Skipping BIOMD0000000113.xml - no results generated
2025-12-07 13:33:02,448 - WARNING - Skipping BIOMD0000000114.xml - no results generated
2025-12-07 13:33:02,451 - WARNING - Skipping BIOMD0000000115.xml - no results generated
2025-12-07 13:33:02,456 - WARNING - Skipping BIOMD0000000116.xml - no results generated
2025-12-07 13:33:02,459 - WARNING - Skipping BIOMD0000000117.xml - no results generated
2025-12-07 13:33:02,464 - WARNING - Skipping BIOMD0000000118.xml - no results generated
2025-12-07 13:33:02,468 - WARNING - Skipping BIOMD0000000119.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000112.txt
Evaluating 113/1075: BIOMD0000000113.xml
Evaluating 114/1075: BIOMD0000000114.xml
Evaluating 115/1075: BIOMD0000000115.xml
Evaluating 116/1075: BIOMD0000000116.xml
Evaluating 117/1075: BIOMD0000000117.xml
Evaluating 118/1075: BIOMD0000000118.xml
Evaluating 119/1075: BIOMD0000000119.xml
Evaluating 120/1075: BIOMD0000000120.xml

2025-12-07 13:33:04,763 - WARNING - Skipping BIOMD0000000121.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000120.txt
Evaluating 121/1075: BIOMD0000000121.xml
Evaluating 122/1075: BIOMD0000000122.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000122.txt
Evaluating 123/1075: BIOMD0000000123.xml

2025-12-07 13:33:16,195 - WARNING - Skipping BIOMD0000000124.xml - no results generated
2025-12-07 13:33:16,199 - WARNING - Skipping BIOMD0000000125.xml - no results generated
2025-12-07 13:33:16,206 - WARNING - Skipping BIOMD0000000126.xml - no results generated
2025-12-07 13:33:16,208 - WARNING - Skipping BIOMD0000000127.xml - no results generated
2025-12-07 13:33:16,213 - WARNING - Skipping BIOMD0000000128.xml - no results generated
2025-12-07 13:33:16,216 - WARNING - Skipping BIOMD0000000129.xml - no results generated
2025-12-07 13:33:16,218 - WARNING - Skipping BIOMD0000000130.xml - no results generated
2025-12-07 13:33:16,220 - WARNING - Skipping BIOMD0000000131.xml - no results generated
2025-12-07 13:33:16,223 - WARNING - Skipping BIOMD0000000132.xml - no results generated
2025-12-07 13:33:16,225 - WARNING - Skipping BIOMD0000000133.xml - no results generated
2025-12-07 13:33:16,228 - WARNING - Skipping BIOMD0000000134.xml - no results generated
2025-12-07 13:33:16,230 - WARNING - Skipping BIOMD0000000135.xml - no results generated
2025-12-07 13:33:16,233 - WARNING - Skipping BIOMD0000000136.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000123.txt
Evaluating 124/1075: BIOMD0000000124.xml
Evaluating 125/1075: BIOMD0000000125.xml
Evaluating 126/1075: BIOMD0000000126.xml
Evaluating 127/1075: BIOMD0000000127.xml
Evaluating 128/1075: BIOMD0000000128.xml
Evaluating 129/1075: BIOMD0000000129.xml
Evaluating 130/1075: BIOMD0000000130.xml
Evaluating 131/1075: BIOMD0000000131.xml
Evaluating 132/1075: BIOMD0000000132.xml
Evaluating 133/1075: BIOMD0000000133.xml
Evaluating 134/1075: BIOMD0000000134.xml
Evaluating 135/1075: BIOMD0000000135.xml
Evaluating 136/1075: BIOMD0000000136.xml
Evaluating 137/1075: BIOMD0000000137.xml

2025-12-07 13:33:21,217 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:33:21,367 - WARNING - Skipping BIOMD0000000138.xml - no results generated
2025-12-07 13:33:21,381 - WARNING - Skipping BIOMD0000000139.xml - no results generated
2025-12-07 13:33:21,396 - WARNING - Skipping BIOMD0000000140.xml - no results generated
2025-12-07 13:33:21,398 - WARNING - Skipping BIOMD0000000141.xml - no results generated
2025-12-07 13:33:21,400 - WARNING - Skipping BIOMD0000000142.xml - no results generated
2025-12-07 13:33:21,410 - WARNING - Skipping BIOMD0000000143.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000137.txt
Evaluating 138/1075: BIOMD0000000138.xml
Evaluating 139/1075: BIOMD0000000139.xml
Evaluating 140/1075: BIOMD0000000140.xml
Evaluating 141/1075: BIOMD0000000141.xml
Evaluating 142/1075: BIOMD0000000142.xml
Evaluating 143/1075: BIOMD0000000143.xml
Evaluating 144/1075: BIOMD0000000144.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000144.txt
Evaluating 145/1075: BIOMD0000000145.xml

2025-12-07 13:33:26,332 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000145.txt
Evaluating 146/1075: BIOMD0000000146.xml

2025-12-07 13:33:27,650 - WARNING - Skipping BIOMD0000000147.xml - no results generated
2025-12-07 13:33:27,654 - WARNING - Skipping BIOMD0000000148.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000146.txt
Evaluating 147/1075: BIOMD0000000147.xml
Evaluating 148/1075: BIOMD0000000148.xml
Evaluating 149/1075: BIOMD0000000149.xml

2025-12-07 13:33:35,691 - WARNING - Skipping BIOMD0000000150.xml - no results generated
2025-12-07 13:33:35,716 - WARNING - Skipping BIOMD0000000151.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000149.txt
Evaluating 150/1075: BIOMD0000000150.xml
Evaluating 151/1075: BIOMD0000000151.xml
Evaluating 152/1075: BIOMD0000000152.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000152.txt
Evaluating 153/1075: BIOMD0000000153.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000153.txt
Evaluating 154/1075: BIOMD0000000154.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000154.txt
Evaluating 155/1075: BIOMD0000000155.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000155.txt
Evaluating 156/1075: BIOMD0000000156.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000156.txt
Evaluating 157/1075: BIOMD0000000157.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000157.txt
Evaluating 158/1075: BIOMD0000000158.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000158.txt
Evaluating 159/1075: BIOMD0000000159.xml

2025-12-07 13:34:19,599 - WARNING - Skipping BIOMD0000000160.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000159.txt
Evaluating 160/1075: BIOMD0000000160.xml
Evaluating 161/1075: BIOMD0000000161.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000161.txt
Evaluating 162/1075: BIOMD0000000162.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000162.txt
Evaluating 163/1075: BIOMD0000000163.xml

2025-12-07 13:34:43,095 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000163.txt
Evaluating 164/1075: BIOMD0000000164.xml

2025-12-07 13:34:51,857 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000164.txt
Evaluating 165/1075: BIOMD0000000165.xml

2025-12-07 13:34:56,468 - WARNING - Skipping BIOMD0000000166.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000165.txt
Evaluating 166/1075: BIOMD0000000166.xml
Evaluating 167/1075: BIOMD0000000167.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000167.txt
Evaluating 168/1075: BIOMD0000000168.xml

2025-12-07 13:35:02,135 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000168.txt
Evaluating 169/1075: BIOMD0000000169.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000169.txt
Evaluating 170/1075: BIOMD0000000170.xml

2025-12-07 13:35:08,699 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:35:08,756 - WARNING - Skipping BIOMD0000000171.xml - no results generated
2025-12-07 13:35:08,771 - WARNING - Skipping BIOMD0000000172.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000170.txt
Evaluating 171/1075: BIOMD0000000171.xml
Evaluating 172/1075: BIOMD0000000172.xml
Evaluating 173/1075: BIOMD0000000173.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000173.txt
Evaluating 174/1075: BIOMD0000000174.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000174.txt
Evaluating 175/1075: BIOMD0000000175.xml

2025-12-07 13:35:31,306 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:35:31,354 - WARNING - Skipping BIOMD0000000176.xml - no results generated
2025-12-07 13:35:31,373 - WARNING - Skipping BIOMD0000000177.xml - no results generated
2025-12-07 13:35:31,377 - WARNING - Skipping BIOMD0000000178.xml - no results generated
2025-12-07 13:35:31,383 - WARNING - Skipping BIOMD0000000179.xml - no results generated
2025-12-07 13:35:31,390 - WARNING - Skipping BIOMD0000000180.xml - no results generated
2025-12-07 13:35:31,397 - WARNING - Skipping BIOMD0000000181.xml - no results generated
2025-12-07 13:35:31,416 - WARNING - Skipping BIOMD0000000182.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000175.txt
Evaluating 176/1075: BIOMD0000000176.xml
Evaluating 177/1075: BIOMD0000000177.xml
Evaluating 178/1075: BIOMD0000000178.xml
Evaluating 179/1075: BIOMD0000000179.xml
Evaluating 180/1075: BIOMD0000000180.xml
Evaluating 181/1075: BIOMD0000000181.xml
Evaluating 182/1075: BIOMD0000000182.xml
Evaluating 183/1075: BIOMD0000000183.xml

2025-12-07 13:35:39,795 - WARNING - Skipping BIOMD0000000184.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000183.txt
Evaluating 184/1075: BIOMD0000000184.xml
Evaluating 185/1075: BIOMD0000000185.xml

2025-12-07 13:35:41,521 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000185.txt
Evaluating 186/1075: BIOMD0000000186.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000186.txt
Evaluating 187/1075: BIOMD0000000187.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000187.txt
Evaluating 188/1075: BIOMD0000000188.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000188.txt
Evaluating 189/1075: BIOMD0000000189.xml

2025-12-07 13:36:01,797 - WARNING - Skipping BIOMD0000000190.xml - no results generated
2025-12-07 13:36:01,802 - WARNING - Skipping BIOMD0000000191.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000189.txt
Evaluating 190/1075: BIOMD0000000190.xml
Evaluating 191/1075: BIOMD0000000191.xml
Evaluating 192/1075: BIOMD0000000192.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000192.txt
Evaluating 193/1075: BIOMD0000000193.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000193.txt
Evaluating 194/1075: BIOMD0000000194.xml

2025-12-07 13:36:11,431 - WARNING - Skipping BIOMD0000000195.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000194.txt
Evaluating 195/1075: BIOMD0000000195.xml
Evaluating 196/1075: BIOMD0000000196.xml

2025-12-07 13:36:14,322 - WARNING - Skipping BIOMD0000000197.xml - no results generated
2025-12-07 13:36:14,328 - WARNING - Skipping BIOMD0000000198.xml - no results generated
2025-12-07 13:36:14,335 - WARNING - Skipping BIOMD0000000199.xml - no results generated
2025-12-07 13:36:14,349 - WARNING - Skipping BIOMD0000000200.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000196.txt
Evaluating 197/1075: BIOMD0000000197.xml
Evaluating 198/1075: BIOMD0000000198.xml
Evaluating 199/1075: BIOMD0000000199.xml
Evaluating 200/1075: BIOMD0000000200.xml
Evaluating 201/1075: BIOMD0000000201.xml

2025-12-07 13:36:18,797 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000201.txt
Evaluating 202/1075: BIOMD0000000202.xml

2025-12-07 13:36:21,119 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000202.txt
Evaluating 203/1075: BIOMD0000000203.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000203.txt
Evaluating 204/1075: BIOMD0000000204.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000204.txt
Evaluating 205/1075: BIOMD0000000205.xml

2025-12-07 13:38:14,674 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:38:14,749 - WARNING - Skipping BIOMD0000000206.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000205.txt
Evaluating 206/1075: BIOMD0000000206.xml
Evaluating 207/1075: BIOMD0000000207.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000207.txt
Evaluating 208/1075: BIOMD0000000208.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000208.txt
Evaluating 209/1075: BIOMD0000000209.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000209.txt
Evaluating 210/1075: BIOMD0000000210.xml

2025-12-07 13:38:28,561 - WARNING - Skipping BIOMD0000000211.xml - no results generated
2025-12-07 13:38:28,574 - WARNING - Skipping BIOMD0000000212.xml - no results generated
2025-12-07 13:38:28,586 - WARNING - Skipping BIOMD0000000213.xml - no results generated
2025-12-07 13:38:28,597 - WARNING - Skipping BIOMD0000000214.xml - no results generated
2025-12-07 13:38:28,605 - WARNING - Skipping BIOMD0000000215.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000210.txt
Evaluating 211/1075: BIOMD0000000211.xml
Evaluating 212/1075: BIOMD0000000212.xml
Evaluating 213/1075: BIOMD0000000213.xml
Evaluating 214/1075: BIOMD0000000214.xml
Evaluating 215/1075: BIOMD0000000215.xml
Evaluating 216/1075: BIOMD0000000216.xml

2025-12-07 13:38:30,991 - WARNING - Skipping BIOMD0000000217.xml - no results generated
2025-12-07 13:38:30,999 - WARNING - Skipping BIOMD0000000218.xml - no results generated
2025-12-07 13:38:31,008 - WARNING - Skipping BIOMD0000000219.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000216.txt
Evaluating 217/1075: BIOMD0000000217.xml
Evaluating 218/1075: BIOMD0000000218.xml
Evaluating 219/1075: BIOMD0000000219.xml
Evaluating 220/1075: BIOMD0000000220.xml

2025-12-07 13:38:42,907 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:38:43,002 - WARNING - Skipping BIOMD0000000221.xml - no results generated
2025-12-07 13:38:43,009 - WARNING - Skipping BIOMD0000000222.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000220.txt
Evaluating 221/1075: BIOMD0000000221.xml
Evaluating 222/1075: BIOMD0000000222.xml
Evaluating 223/1075: BIOMD0000000223.xml

2025-12-07 13:38:46,258 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:38:46,344 - WARNING - Skipping BIOMD0000000224.xml - no results generated
2025-12-07 13:38:46,348 - WARNING - Skipping BIOMD0000000225.xml - no results generated
2025-12-07 13:38:46,369 - WARNING - Skipping BIOMD0000000226.xml - no results generated
2025-12-07 13:38:46,420 - WARNING - Skipping BIOMD0000000227.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000223.txt
Evaluating 224/1075: BIOMD0000000224.xml
Evaluating 225/1075: BIOMD0000000225.xml
Evaluating 226/1075: BIOMD0000000226.xml
Evaluating 227/1075: BIOMD0000000227.xml
Evaluating 228/1075: BIOMD0000000228.xml

2025-12-07 13:38:50,701 - WARNING - Skipping BIOMD0000000229.xml - no results generated
2025-12-07 13:38:50,718 - WARNING - Skipping BIOMD0000000230.xml - no results generated
2025-12-07 13:38:50,722 - WARNING - Skipping BIOMD0000000231.xml - no results generated
2025-12-07 13:38:50,730 - WARNING - Skipping BIOMD0000000232.xml - no results generated
2025-12-07 13:38:50,733 - WARNING - Skipping BIOMD0000000233.xml - no results generated
2025-12-07 13:38:50,738 - WARNING - Skipping BIOMD0000000234.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000228.txt
Evaluating 229/1075: BIOMD0000000229.xml
Evaluating 230/1075: BIOMD0000000230.xml
Evaluating 231/1075: BIOMD0000000231.xml
Evaluating 232/1075: BIOMD0000000232.xml
Evaluating 233/1075: BIOMD0000000233.xml
Evaluating 234/1075: BIOMD0000000234.xml
Evaluating 235/1075: BIOMD0000000235.xml

2025-12-07 13:38:58,088 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:38:58,331 - WARNING - Skipping BIOMD0000000236.xml - no results generated
2025-12-07 13:38:58,344 - WARNING - Skipping BIOMD0000000237.xml - no results generated
2025-12-07 13:38:58,352 - WARNING - Skipping BIOMD0000000238.xml - no results generated
2025-12-07 13:38:58,388 - WARNING - Skipping BIOMD0000000239.xml - no results generated
2025-12-07 13:38:58,395 - WARNING - Skipping BIOMD0000000240.xml - no results generated
2025-12-07 13:38:58,399 - WARNING - Skipping BIOMD0000000241.xml - no results generated
2025-12-07 13:38:58,407 - WARNING - Skipping BIOMD0000000242.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000235.txt
Evaluating 236/1075: BIOMD0000000236.xml
Evaluating 237/1075: BIOMD0000000237.xml
Evaluating 238/1075: BIOMD0000000238.xml
Evaluating 239/1075: BIOMD0000000239.xml
Evaluating 240/1075: BIOMD0000000240.xml
Evaluating 241/1075: BIOMD0000000241.xml
Evaluating 242/1075: BIOMD0000000242.xml
Evaluating 243/1075: BIOMD0000000243.xml

2025-12-07 13:39:06,152 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:39:06,194 - WARNING - Skipping BIOMD0000000244.xml - no results generated
2025-12-07 13:39:06,204 - WARNING - Skipping BIOMD0000000245.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000243.txt
Evaluating 244/1075: BIOMD0000000244.xml
Evaluating 245/1075: BIOMD0000000245.xml
Evaluating 246/1075: BIOMD0000000246.xml

2025-12-07 13:39:12,469 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:39:12,635 - WARNING - Skipping BIOMD0000000247.xml - no results generated
2025-12-07 13:39:12,641 - WARNING - Skipping BIOMD0000000248.xml - no results generated
2025-12-07 13:39:12,648 - WARNING - Skipping BIOMD0000000249.xml - no results generated
2025-12-07 13:39:12,668 - WARNING - Skipping BIOMD0000000250.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000246.txt
Evaluating 247/1075: BIOMD0000000247.xml
Evaluating 248/1075: BIOMD0000000248.xml
Evaluating 249/1075: BIOMD0000000249.xml
Evaluating 250/1075: BIOMD0000000250.xml
Evaluating 251/1075: BIOMD0000000251.xml

2025-12-07 13:39:16,797 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000251.txt
Evaluating 252/1075: BIOMD0000000252.xml

2025-12-07 13:39:18,724 - WARNING - Skipping BIOMD0000000253.xml - no results generated
2025-12-07 13:39:18,727 - WARNING - Skipping BIOMD0000000254.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000252.txt
Evaluating 253/1075: BIOMD0000000253.xml
Evaluating 254/1075: BIOMD0000000254.xml
Evaluating 255/1075: BIOMD0000000255.xml

2025-12-07 13:39:38,583 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000255.txt
Evaluating 256/1075: BIOMD0000000256.xml

2025-12-07 13:39:49,545 - WARNING - Skipping BIOMD0000000257.xml - no results generated
2025-12-07 13:39:49,547 - WARNING - Skipping BIOMD0000000258.xml - no results generated
2025-12-07 13:39:49,564 - WARNING - Skipping BIOMD0000000259.xml - no results generated
2025-12-07 13:39:49,582 - WARNING - Skipping BIOMD0000000260.xml - no results generated
2025-12-07 13:39:49,601 - WARNING - Skipping BIOMD0000000261.xml - no results generated
2025-12-07 13:39:49,609 - WARNING - Skipping BIOMD0000000262.xml - no results generated
2025-12-07 13:39:49,616 - WARNING - Skipping BIOMD0000000263.xml - no results generated
2025-12-07 13:39:49,625 - WARNING - Skipping BIOMD0000000264.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000256.txt
Evaluating 257/1075: BIOMD0000000257.xml
Evaluating 258/1075: BIOMD0000000258.xml
Evaluating 259/1075: BIOMD0000000259.xml
Evaluating 260/1075: BIOMD0000000260.xml
Evaluating 261/1075: BIOMD0000000261.xml
Evaluating 262/1075: BIOMD0000000262.xml
Evaluating 263/1075: BIOMD0000000263.xml
Evaluating 264/1075: BIOMD0000000264.xml
Evaluating 265/1075: BIOMD0000000265.xml

2025-12-07 13:39:56,997 - WARNING - Skipping BIOMD0000000266.xml - no results generated
2025-12-07 13:39:57,001 - WARNING - Skipping BIOMD0000000267.xml - no results generated
2025-12-07 13:39:57,023 - WARNING - Skipping BIOMD0000000268.xml - no results generated
2025-12-07 13:39:57,034 - WARNING - Skipping BIOMD0000000269.xml - no results generated
2025-12-07 13:39:57,053 - WARNING - Skipping BIOMD0000000270.xml - no results generated
2025-12-07 13:39:57,058 - WARNING - Skipping BIOMD0000000271.xml - no results generated
2025-12-07 13:39:57,063 - WARNING - Skipping BIOMD0000000272.xml - no results generated
2025-12-07 13:39:57,081 - WARNING - Skipping BIOMD0000000273.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000265.txt
Evaluating 266/1075: BIOMD0000000266.xml
Evaluating 267/1075: BIOMD0000000267.xml
Evaluating 268/1075: BIOMD0000000268.xml
Evaluating 269/1075: BIOMD0000000269.xml
Evaluating 270/1075: BIOMD0000000270.xml
Evaluating 271/1075: BIOMD0000000271.xml
Evaluating 272/1075: BIOMD0000000272.xml
Evaluating 273/1075: BIOMD0000000273.xml
Evaluating 274/1075: BIOMD0000000274.xml

2025-12-07 13:39:58,598 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000274.txt
Evaluating 275/1075: BIOMD0000000275.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000275.txt
Evaluating 276/1075: BIOMD0000000276.xml

2025-12-07 13:40:02,089 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000276.txt
Evaluating 277/1075: BIOMD0000000277.xml

2025-12-07 13:40:04,145 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:40:04,163 - WARNING - Skipping BIOMD0000000278.xml - no results generated
2025-12-07 13:40:04,169 - WARNING - Skipping BIOMD0000000279.xml - no results generated
2025-12-07 13:40:04,173 - WARNING - Skipping BIOMD0000000280.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000277.txt
Evaluating 278/1075: BIOMD0000000278.xml
Evaluating 279/1075: BIOMD0000000279.xml
Evaluating 280/1075: BIOMD0000000280.xml
Evaluating 281/1075: BIOMD0000000281.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000281.txt
Evaluating 282/1075: BIOMD0000000282.xml

2025-12-07 13:40:06,872 - WARNING - Skipping BIOMD0000000283.xml - no results generated
2025-12-07 13:40:06,876 - WARNING - Skipping BIOMD0000000284.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000282.txt
Evaluating 283/1075: BIOMD0000000283.xml
Evaluating 284/1075: BIOMD0000000284.xml
Evaluating 285/1075: BIOMD0000000285.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000285.txt
Evaluating 286/1075: BIOMD0000000286.xml

2025-12-07 13:40:20,281 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000286.txt
Evaluating 287/1075: BIOMD0000000287.xml

2025-12-07 13:40:28,673 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000287.txt
Evaluating 288/1075: BIOMD0000000288.xml

2025-12-07 13:40:33,525 - WARNING - Skipping BIOMD0000000289.xml - no results generated
2025-12-07 13:40:33,529 - WARNING - Skipping BIOMD0000000290.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000288.txt
Evaluating 289/1075: BIOMD0000000289.xml
Evaluating 290/1075: BIOMD0000000290.xml
Evaluating 291/1075: BIOMD0000000291.xml

2025-12-07 13:40:37,382 - WARNING - Skipping BIOMD0000000292.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000291.txt
Evaluating 292/1075: BIOMD0000000292.xml
Evaluating 293/1075: BIOMD0000000293.xml

2025-12-07 13:41:15,879 - WARNING - Skipping BIOMD0000000294.xml - no results generated
2025-12-07 13:41:15,883 - WARNING - Skipping BIOMD0000000295.xml - no results generated
2025-12-07 13:41:15,888 - WARNING - Skipping BIOMD0000000296.xml - no results generated
2025-12-07 13:41:15,903 - WARNING - Skipping BIOMD0000000297.xml - no results generated
2025-12-07 13:41:15,908 - WARNING - Skipping BIOMD0000000298.xml - no results generated
2025-12-07 13:41:15,912 - WARNING - Skipping BIOMD0000000299.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000293.txt
Evaluating 294/1075: BIOMD0000000294.xml
Evaluating 295/1075: BIOMD0000000295.xml
Evaluating 296/1075: BIOMD0000000296.xml
Evaluating 297/1075: BIOMD0000000297.xml
Evaluating 298/1075: BIOMD0000000298.xml
Evaluating 299/1075: BIOMD0000000299.xml
Evaluating 300/1075: BIOMD0000000300.xml

2025-12-07 13:41:19,925 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:41:19,940 - WARNING - Skipping BIOMD0000000301.xml - no results generated
2025-12-07 13:41:19,944 - WARNING - Skipping BIOMD0000000302.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000300.txt
Evaluating 301/1075: BIOMD0000000301.xml
Evaluating 302/1075: BIOMD0000000302.xml
Evaluating 303/1075: BIOMD0000000303.xml

2025-12-07 13:41:31,117 - WARNING - Skipping BIOMD0000000304.xml - no results generated
2025-12-07 13:41:31,123 - WARNING - Skipping BIOMD0000000305.xml - no results generated
2025-12-07 13:41:31,128 - WARNING - Skipping BIOMD0000000306.xml - no results generated
2025-12-07 13:41:31,132 - WARNING - Skipping BIOMD0000000307.xml - no results generated
2025-12-07 13:41:31,137 - WARNING - Skipping BIOMD0000000308.xml - no results generated
2025-12-07 13:41:31,142 - WARNING - Skipping BIOMD0000000309.xml - no results generated
2025-12-07 13:41:31,147 - WARNING - Skipping BIOMD0000000310.xml - no results generated
2025-12-07 13:41:31,151 - WARNING - Skipping BIOMD0000000311.xml - no results generated
2025-12-07 13:41:31,155 - WARNING - Skipping BIOMD0000000312.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000303.txt
Evaluating 304/1075: BIOMD0000000304.xml
Evaluating 305/1075: BIOMD0000000305.xml
Evaluating 306/1075: BIOMD0000000306.xml
Evaluating 307/1075: BIOMD0000000307.xml
Evaluating 308/1075: BIOMD0000000308.xml
Evaluating 309/1075: BIOMD0000000309.xml
Evaluating 310/1075: BIOMD0000000310.xml
Evaluating 311/1075: BIOMD0000000311.xml
Evaluating 312/1075: BIOMD0000000312.xml
Evaluating 313/1075: BIOMD0000000313.xml

2025-12-07 13:41:39,839 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000313.txt
Evaluating 314/1075: BIOMD0000000314.xml

2025-12-07 13:41:45,979 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:41:45,997 - WARNING - Skipping BIOMD0000000315.xml - no results generated
2025-12-07 13:41:46,002 - WARNING - Skipping BIOMD0000000316.xml - no results generated
2025-12-07 13:41:46,007 - WARNING - Skipping BIOMD0000000317.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000314.txt
Evaluating 315/1075: BIOMD0000000315.xml
Evaluating 316/1075: BIOMD0000000316.xml
Evaluating 317/1075: BIOMD0000000317.xml
Evaluating 318/1075: BIOMD0000000318.xml

2025-12-07 13:41:49,171 - WARNING - Skipping BIOMD0000000319.xml - no results generated
2025-12-07 13:41:49,179 - WARNING - Skipping BIOMD0000000320.xml - no results generated
2025-12-07 13:41:49,184 - WARNING - Skipping BIOMD0000000321.xml - no results generated
2025-12-07 13:41:49,188 - WARNING - Skipping BIOMD0000000322.xml - no results generated
2025-12-07 13:41:49,193 - WARNING - Skipping BIOMD0000000323.xml - no results generated
2025-12-07 13:41:49,196 - WARNING - Skipping BIOMD0000000324.xml - no results generated
2025-12-07 13:41:49,202 - WARNING - Skipping BIOMD0000000325.xml - no results generated
2025-12-07 13:41:49,235 - WARNING - Skipping BIOMD0000000326.xml - no results generated
2025-12-07 13:41:49,242 - WARNING - Skipping BIOMD0000000327.xml - no results generated
2025-12-07 13:41:49,263 - WARNING - Skipping BIOMD0000000328.xml - no results generated
2025-12-07 13:41:49,267 - WARNING - Skipping BIOMD0000000329.xml - no results generated
2025-12-07 13:41:49,271 - WARNING - Skipping BIOMD0000000330.xml - no results generated
2025-12-07 13:41:49,275 - WARNING - Skipping BIOMD0000000331.xml - no results generated
2025-12-07 13:41:49,305 - WARNING - Skipping BIOMD0000000332.xml - no results generated
2025-12-07 13:41:49,324 - WARNING - Skipping BIOMD0000000333.xml - no results generated
2025-12-07 13:41:49,353 - WARNING - Skipping BIOMD0000000334.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000318.txt
Evaluating 319/1075: BIOMD0000000319.xml
Evaluating 320/1075: BIOMD0000000320.xml
Evaluating 321/1075: BIOMD0000000321.xml
Evaluating 322/1075: BIOMD0000000322.xml
Evaluating 323/1075: BIOMD0000000323.xml
Evaluating 324/1075: BIOMD0000000324.xml
Evaluating 325/1075: BIOMD0000000325.xml
Evaluating 326/1075: BIOMD0000000326.xml
Evaluating 327/1075: BIOMD0000000327.xml
Evaluating 328/1075: BIOMD0000000328.xml
Evaluating 329/1075: BIOMD0000000329.xml
Evaluating 330/1075: BIOMD0000000330.xml
Evaluating 331/1075: BIOMD0000000331.xml
Evaluating 332/1075: BIOMD0000000332.xml
Evaluating 333/1075: BIOMD0000000333.xml
Evaluating 334/1075: BIOMD0000000334.xml
Evaluating 335/1075: BIOMD0000000335.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000335.txt
Evaluating 336/1075: BIOMD0000000336.xml

2025-12-07 13:42:05,056 - WARNING - Skipping BIOMD0000000337.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000336.txt
Evaluating 337/1075: BIOMD0000000337.xml
Evaluating 338/1075: BIOMD0000000338.xml

2025-12-07 13:42:22,395 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000338.txt
Evaluating 339/1075: BIOMD0000000339.xml

2025-12-07 13:42:36,422 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000339.txt
Evaluating 340/1075: BIOMD0000000340.xml

2025-12-07 13:42:47,175 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000340.txt
Evaluating 341/1075: BIOMD0000000341.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000341.txt
Evaluating 342/1075: BIOMD0000000342.xml

2025-12-07 13:42:56,530 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000342.txt
Evaluating 343/1075: BIOMD0000000343.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000343.txt
Evaluating 344/1075: BIOMD0000000344.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000344.txt
Evaluating 345/1075: BIOMD0000000345.xml

2025-12-07 13:43:08,338 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:43:08,353 - WARNING - Skipping BIOMD0000000346.xml - no results generated
2025-12-07 13:43:08,371 - WARNING - Skipping BIOMD0000000347.xml - no results generated
2025-12-07 13:43:08,379 - WARNING - Skipping BIOMD0000000348.xml - no results generated
2025-12-07 13:43:08,388 - WARNING - Skipping BIOMD0000000349.xml - no results generated
2025-12-07 13:43:08,405 - WARNING - Skipping BIOMD0000000350.xml - no results generated
2025-12-07 13:43:08,411 - WARNING - Skipping BIOMD0000000351.xml - no results generated
2025-12-07 13:43:08,417 - WARNING - Skipping BIOMD0000000352.xml - no results generated
2025-12-07 13:43:08,448 - WARNING - Skipping BIOMD0000000353.xml - no results generated
2025-12-07 13:43:08,455 - WARNING - Skipping BIOMD0000000354.xml - no results generated
2025-12-07 13:43:08,464 - WARNING - Skipping BIOMD0000000355.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000345.txt
Evaluating 346/1075: BIOMD0000000346.xml
Evaluating 347/1075: BIOMD0000000347.xml
Evaluating 348/1075: BIOMD0000000348.xml
Evaluating 349/1075: BIOMD0000000349.xml
Evaluating 350/1075: BIOMD0000000350.xml
Evaluating 351/1075: BIOMD0000000351.xml
Evaluating 352/1075: BIOMD0000000352.xml
Evaluating 353/1075: BIOMD0000000353.xml
Evaluating 354/1075: BIOMD0000000354.xml
Evaluating 355/1075: BIOMD0000000355.xml
Evaluating 356/1075: BIOMD0000000356.xml

2025-12-07 13:43:16,990 - WARNING - Skipping BIOMD0000000357.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000356.txt
Evaluating 357/1075: BIOMD0000000357.xml
Evaluating 358/1075: BIOMD0000000358.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000358.txt
Evaluating 359/1075: BIOMD0000000359.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000359.txt
Evaluating 360/1075: BIOMD0000000360.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000360.txt
Evaluating 361/1075: BIOMD0000000361.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000361.txt
Evaluating 362/1075: BIOMD0000000362.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000362.txt
Evaluating 363/1075: BIOMD0000000363.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000363.txt
Evaluating 364/1075: BIOMD0000000364.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000364.txt
Evaluating 365/1075: BIOMD0000000365.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000365.txt
Evaluating 366/1075: BIOMD0000000366.xml

2025-12-07 13:43:53,945 - WARNING - Skipping BIOMD0000000367.xml - no results generated
2025-12-07 13:43:53,947 - WARNING - Skipping BIOMD0000000368.xml - no results generated
2025-12-07 13:43:53,949 - WARNING - Skipping BIOMD0000000369.xml - no results generated
2025-12-07 13:43:53,961 - WARNING - Skipping BIOMD0000000370.xml - no results generated
2025-12-07 13:43:53,964 - WARNING - Skipping BIOMD0000000371.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000366.txt
Evaluating 367/1075: BIOMD0000000367.xml
Evaluating 368/1075: BIOMD0000000368.xml
Evaluating 369/1075: BIOMD0000000369.xml
Evaluating 370/1075: BIOMD0000000370.xml
Evaluating 371/1075: BIOMD0000000371.xml
Evaluating 372/1075: BIOMD0000000372.xml

2025-12-07 13:43:55,929 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:43:55,952 - WARNING - Skipping BIOMD0000000373.xml - no results generated
2025-12-07 13:43:55,959 - WARNING - Skipping BIOMD0000000374.xml - no results generated
2025-12-07 13:43:55,966 - WARNING - Skipping BIOMD0000000375.xml - no results generated
2025-12-07 13:43:55,978 - WARNING - Skipping BIOMD0000000376.xml - no results generated
2025-12-07 13:43:55,982 - WARNING - Skipping BIOMD0000000377.xml - no results generated
2025-12-07 13:43:55,988 - WARNING - Skipping BIOMD0000000378.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000372.txt
Evaluating 373/1075: BIOMD0000000373.xml
Evaluating 374/1075: BIOMD0000000374.xml
Evaluating 375/1075: BIOMD0000000375.xml
Evaluating 376/1075: BIOMD0000000376.xml
Evaluating 377/1075: BIOMD0000000377.xml
Evaluating 378/1075: BIOMD0000000378.xml
Evaluating 379/1075: BIOMD0000000379.xml

2025-12-07 13:44:00,160 - WARNING - Skipping BIOMD0000000380.xml - no results generated
2025-12-07 13:44:00,164 - WARNING - Skipping BIOMD0000000381.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000379.txt
Evaluating 380/1075: BIOMD0000000380.xml
Evaluating 381/1075: BIOMD0000000381.xml
Evaluating 382/1075: BIOMD0000000382.xml

2025-12-07 13:44:01,667 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:44:01,681 - WARNING - Skipping BIOMD0000000383.xml - no results generated
2025-12-07 13:44:01,687 - WARNING - Skipping BIOMD0000000384.xml - no results generated
2025-12-07 13:44:01,706 - WARNING - Skipping BIOMD0000000385.xml - no results generated
2025-12-07 13:44:01,718 - WARNING - Skipping BIOMD0000000386.xml - no results generated
2025-12-07 13:44:01,728 - WARNING - Skipping BIOMD0000000387.xml - no results generated
2025-12-07 13:44:01,734 - WARNING - Skipping BIOMD0000000388.xml - no results generated
2025-12-07 13:44:01,742 - WARNING - Skipping BIOMD0000000389.xml - no results generated
2025-12-07 13:44:01,748 - WARNING - Skipping BIOMD0000000390.xml - no results generated
2025-12-07 13:44:01,759 - WARNING - Skipping BIOMD0000000391.xml - no results generated
2025-12-07 13:44:01,778 - WARNING - Skipping BIOMD0000000392.xml - no results generated
2025-12-07 13:44:01,801 - WARNING - Skipping BIOMD0000000393.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000382.txt
Evaluating 383/1075: BIOMD0000000383.xml
Evaluating 384/1075: BIOMD0000000384.xml
Evaluating 385/1075: BIOMD0000000385.xml
Evaluating 386/1075: BIOMD0000000386.xml
Evaluating 387/1075: BIOMD0000000387.xml
Evaluating 388/1075: BIOMD0000000388.xml
Evaluating 389/1075: BIOMD0000000389.xml
Evaluating 390/1075: BIOMD0000000390.xml
Evaluating 391/1075: BIOMD0000000391.xml
Evaluating 392/1075: BIOMD0000000392.xml
Evaluating 393/1075: BIOMD0000000393.xml
Evaluating 394/1075: BIOMD0000000394.xml

2025-12-07 13:44:08,686 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000394.txt
Evaluating 395/1075: BIOMD0000000395.xml

2025-12-07 13:44:11,582 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000395.txt
Evaluating 396/1075: BIOMD0000000396.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000396.txt
Evaluating 397/1075: BIOMD0000000397.xml

2025-12-07 13:44:23,523 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000397.txt
Evaluating 398/1075: BIOMD0000000398.xml

2025-12-07 13:44:28,544 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000398.txt
Evaluating 399/1075: BIOMD0000000399.xml

2025-12-07 13:44:58,175 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:44:59,039 - WARNING - Skipping BIOMD0000000400.xml - no results generated
2025-12-07 13:44:59,042 - WARNING - Skipping BIOMD0000000401.xml - no results generated
2025-12-07 13:44:59,045 - WARNING - Skipping BIOMD0000000402.xml - no results generated
2025-12-07 13:44:59,048 - WARNING - Skipping BIOMD0000000403.xml - no results generated
2025-12-07 13:44:59,069 - WARNING - Skipping BIOMD0000000404.xml - no results generated
2025-12-07 13:44:59,074 - WARNING - Skipping BIOMD0000000405.xml - no results generated
2025-12-07 13:44:59,092 - WARNING - Skipping BIOMD0000000406.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000399.txt
Evaluating 400/1075: BIOMD0000000400.xml
Evaluating 401/1075: BIOMD0000000401.xml
Evaluating 402/1075: BIOMD0000000402.xml
Evaluating 403/1075: BIOMD0000000403.xml
Evaluating 404/1075: BIOMD0000000404.xml
Evaluating 405/1075: BIOMD0000000405.xml
Evaluating 406/1075: BIOMD0000000406.xml
Evaluating 407/1075: BIOMD0000000407.xml

2025-12-07 13:45:14,819 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:45:15,010 - WARNING - Skipping BIOMD0000000408.xml - no results generated
2025-12-07 13:45:15,022 - WARNING - Skipping BIOMD0000000409.xml - no results generated
2025-12-07 13:45:15,055 - WARNING - Skipping BIOMD0000000410.xml - no results generated
2025-12-07 13:45:15,064 - WARNING - Skipping BIOMD0000000411.xml - no results generated
2025-12-07 13:45:15,125 - WARNING - Skipping BIOMD0000000412.xml - no results generated
2025-12-07 13:45:15,130 - WARNING - Skipping BIOMD0000000413.xml - no results generated
2025-12-07 13:45:15,132 - WARNING - Skipping BIOMD0000000414.xml - no results generated
2025-12-07 13:45:15,136 - WARNING - Skipping BIOMD0000000415.xml - no results generated
2025-12-07 13:45:15,148 - WARNING - Skipping BIOMD0000000416.xml - no results generated
2025-12-07 13:45:15,152 - WARNING - Skipping BIOMD0000000417.xml - no results generated
2025-12-07 13:45:15,155 - WARNING - Skipping BIOMD0000000418.xml - no results generated
2025-12-07 13:45:15,159 - WARNING - Skipping BIOMD0000000419.xml - no results generated
2025-12-07 13:45:15,162 - WARNING - Skipping BIOMD0000000420.xml - no results generated
2025-12-07 13:45:15,165 - WARNING - Skipping BIOMD0000000421.xml - no results generated
2025-12-07 13:45:15,178 - WARNING - Skipping BIOMD0000000422.xml - no results generated
2025-12-07 13:45:15,183 - WARNING - Skipping BIOMD0000000423.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000407.txt
Evaluating 408/1075: BIOMD0000000408.xml
Evaluating 409/1075: BIOMD0000000409.xml
Evaluating 410/1075: BIOMD0000000410.xml
Evaluating 411/1075: BIOMD0000000411.xml
Evaluating 412/1075: BIOMD0000000412.xml
Evaluating 413/1075: BIOMD0000000413.xml
Evaluating 414/1075: BIOMD0000000414.xml
Evaluating 415/1075: BIOMD0000000415.xml
Evaluating 416/1075: BIOMD0000000416.xml
Evaluating 417/1075: BIOMD0000000417.xml
Evaluating 418/1075: BIOMD0000000418.xml
Evaluating 419/1075: BIOMD0000000419.xml
Evaluating 420/1075: BIOMD0000000420.xml
Evaluating 421/1075: BIOMD0000000421.xml
Evaluating 422/1075: BIOMD0000000422.xml
Evaluating 423/1075: BIOMD0000000423.xml
Evaluating 424/1075: BIOMD0000000424.xml

2025-12-07 13:45:30,486 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:45:30,910 - WARNING - Skipping BIOMD0000000425.xml - no results generated
2025-12-07 13:45:30,943 - WARNING - Skipping BIOMD0000000426.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000424.txt
Evaluating 425/1075: BIOMD0000000425.xml
Evaluating 426/1075: BIOMD0000000426.xml
Evaluating 427/1075: BIOMD0000000427.xml

2025-12-07 13:45:40,791 - WARNING - Skipping BIOMD0000000428.xml - no results generated
2025-12-07 13:45:40,813 - WARNING - Skipping BIOMD0000000429.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000427.txt
Evaluating 428/1075: BIOMD0000000428.xml
Evaluating 429/1075: BIOMD0000000429.xml
Evaluating 430/1075: BIOMD0000000430.xml

2025-12-07 13:45:52,205 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000430.txt
Evaluating 431/1075: BIOMD0000000431.xml

2025-12-07 13:46:01,001 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000431.txt
Evaluating 432/1075: BIOMD0000000432.xml

2025-12-07 13:46:07,495 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000432.txt
Evaluating 433/1075: BIOMD0000000433.xml

2025-12-07 13:46:12,585 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000433.txt
Evaluating 434/1075: BIOMD0000000434.xml

2025-12-07 13:46:18,048 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:46:18,161 - WARNING - Skipping BIOMD0000000435.xml - no results generated
2025-12-07 13:46:18,174 - WARNING - Skipping BIOMD0000000436.xml - no results generated
2025-12-07 13:46:18,209 - WARNING - Skipping BIOMD0000000437.xml - no results generated
2025-12-07 13:46:18,214 - WARNING - Skipping BIOMD0000000438.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000434.txt
Evaluating 435/1075: BIOMD0000000435.xml
Evaluating 436/1075: BIOMD0000000436.xml
Evaluating 437/1075: BIOMD0000000437.xml
Evaluating 438/1075: BIOMD0000000438.xml
Evaluating 439/1075: BIOMD0000000439.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000439.txt
Evaluating 440/1075: BIOMD0000000440.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000440.txt
Evaluating 441/1075: BIOMD0000000441.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000441.txt
Evaluating 442/1075: BIOMD0000000442.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000442.txt
Evaluating 443/1075: BIOMD0000000443.xml

2025-12-07 13:46:44,728 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000443.txt
Evaluating 444/1075: BIOMD0000000444.xml

2025-12-07 13:46:52,729 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:46:52,789 - WARNING - Skipping BIOMD0000000445.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000444.txt
Evaluating 445/1075: BIOMD0000000445.xml
Evaluating 446/1075: BIOMD0000000446.xml

2025-12-07 13:46:55,894 - WARNING - Skipping BIOMD0000000447.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000446.txt
Evaluating 447/1075: BIOMD0000000447.xml
Evaluating 448/1075: BIOMD0000000448.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000448.txt
Evaluating 449/1075: BIOMD0000000449.xml

2025-12-07 13:47:13,603 - WARNING - Skipping BIOMD0000000450.xml - no results generated
2025-12-07 13:47:13,646 - WARNING - Skipping BIOMD0000000451.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000449.txt
Evaluating 450/1075: BIOMD0000000450.xml
Evaluating 451/1075: BIOMD0000000451.xml
Evaluating 452/1075: BIOMD0000000452.xml

2025-12-07 13:48:50,537 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000452.txt
Evaluating 453/1075: BIOMD0000000453.xml

2025-12-07 13:50:15,878 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:50:16,715 - WARNING - Skipping BIOMD0000000454.xml - no results generated
2025-12-07 13:50:16,720 - WARNING - Skipping BIOMD0000000455.xml - no results generated
2025-12-07 13:50:16,725 - WARNING - Skipping BIOMD0000000456.xml - no results generated
2025-12-07 13:50:16,841 - WARNING - Skipping BIOMD0000000457.xml - no results generated
2025-12-07 13:50:16,847 - WARNING - Skipping BIOMD0000000458.xml - no results generated
2025-12-07 13:50:16,851 - WARNING - Skipping BIOMD0000000459.xml - no results generated
2025-12-07 13:50:16,855 - WARNING - Skipping BIOMD0000000460.xml - no results generated
2025-12-07 13:50:16,860 - WARNING - Skipping BIOMD0000000461.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000453.txt
Evaluating 454/1075: BIOMD0000000454.xml
Evaluating 455/1075: BIOMD0000000455.xml
Evaluating 456/1075: BIOMD0000000456.xml
Evaluating 457/1075: BIOMD0000000457.xml
Evaluating 458/1075: BIOMD0000000458.xml
Evaluating 459/1075: BIOMD0000000459.xml
Evaluating 460/1075: BIOMD0000000460.xml
Evaluating 461/1075: BIOMD0000000461.xml
Evaluating 462/1075: BIOMD0000000462.xml

2025-12-07 13:50:18,239 - WARNING - Skipping BIOMD0000000463.xml - no results generated
2025-12-07 13:50:18,251 - WARNING - Skipping BIOMD0000000464.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000462.txt
Evaluating 463/1075: BIOMD0000000463.xml
Evaluating 464/1075: BIOMD0000000464.xml
Evaluating 465/1075: BIOMD0000000465.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000465.txt
Evaluating 466/1075: BIOMD0000000466.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000466.txt
Evaluating 467/1075: BIOMD0000000467.xml

2025-12-07 13:50:33,513 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000467.txt
Evaluating 468/1075: BIOMD0000000468.xml

2025-12-07 13:50:46,009 - WARNING - Skipping BIOMD0000000469.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000468.txt
Evaluating 469/1075: BIOMD0000000469.xml
Evaluating 470/1075: BIOMD0000000470.xml

2025-12-07 13:50:46,388 - WARNING - Skipping BIOMD0000000470.xml - no results generated
2025-12-07 13:50:46,664 - WARNING - Skipping BIOMD0000000471.xml - no results generated
2025-12-07 13:50:46,958 - WARNING - Skipping BIOMD0000000472.xml - no results generated

Evaluating 471/1075: BIOMD0000000471.xml
Evaluating 472/1075: BIOMD0000000472.xml

2025-12-07 13:50:47,275 - WARNING - Skipping BIOMD0000000473.xml - no results generated

Evaluating 473/1075: BIOMD0000000473.xml
Evaluating 474/1075: BIOMD0000000474.xml

2025-12-07 13:50:50,106 - WARNING - Skipping BIOMD0000000475.xml - no results generated
2025-12-07 13:50:50,120 - WARNING - Skipping BIOMD0000000476.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000474.txt
Evaluating 475/1075: BIOMD0000000475.xml
Evaluating 476/1075: BIOMD0000000476.xml
Evaluating 477/1075: BIOMD0000000477.xml

2025-12-07 13:51:10,590 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:51:10,890 - WARNING - Skipping BIOMD0000000478.xml - no results generated
2025-12-07 13:51:10,906 - WARNING - Skipping BIOMD0000000479.xml - no results generated
2025-12-07 13:51:10,948 - WARNING - Skipping BIOMD0000000480.xml - no results generated
2025-12-07 13:51:10,974 - WARNING - Skipping BIOMD0000000481.xml - no results generated
2025-12-07 13:51:10,986 - WARNING - Skipping BIOMD0000000482.xml - no results generated
2025-12-07 13:51:10,991 - WARNING - Skipping BIOMD0000000483.xml - no results generated
2025-12-07 13:51:10,993 - WARNING - Skipping BIOMD0000000484.xml - no results generated
2025-12-07 13:51:10,996 - WARNING - Skipping BIOMD0000000485.xml - no results generated
2025-12-07 13:51:10,998 - WARNING - Skipping BIOMD0000000486.xml - no results generated
2025-12-07 13:51:11,001 - WARNING - Skipping BIOMD0000000487.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000477.txt
Evaluating 478/1075: BIOMD0000000478.xml
Evaluating 479/1075: BIOMD0000000479.xml
Evaluating 480/1075: BIOMD0000000480.xml
Evaluating 481/1075: BIOMD0000000481.xml
Evaluating 482/1075: BIOMD0000000482.xml
Evaluating 483/1075: BIOMD0000000483.xml
Evaluating 484/1075: BIOMD0000000484.xml
Evaluating 485/1075: BIOMD0000000485.xml
Evaluating 486/1075: BIOMD0000000486.xml
Evaluating 487/1075: BIOMD0000000487.xml
Evaluating 488/1075: BIOMD0000000488.xml

2025-12-07 13:51:29,485 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000488.txt
Evaluating 489/1075: BIOMD0000000489.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000489.txt
Evaluating 490/1075: BIOMD0000000490.xml

2025-12-07 13:51:34,921 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000490.txt
Evaluating 491/1075: BIOMD0000000491.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000491.txt
Evaluating 492/1075: BIOMD0000000492.xml

2025-12-07 13:51:41,447 - WARNING - Skipping BIOMD0000000493.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000492.txt
Evaluating 493/1075: BIOMD0000000493.xml
Evaluating 494/1075: BIOMD0000000494.xml

2025-12-07 13:51:52,609 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:51:52,690 - WARNING - Skipping BIOMD0000000495.xml - no results generated
2025-12-07 13:51:52,960 - WARNING - Skipping BIOMD0000000496.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000494.txt
Evaluating 495/1075: BIOMD0000000495.xml
Evaluating 496/1075: BIOMD0000000496.xml

2025-12-07 13:51:53,238 - WARNING - Skipping BIOMD0000000497.xml - no results generated

Evaluating 497/1075: BIOMD0000000497.xml
Evaluating 498/1075: BIOMD0000000498.xml

2025-12-07 13:52:00,007 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000498.txt
Evaluating 499/1075: BIOMD0000000499.xml

2025-12-07 13:52:07,813 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:52:07,833 - WARNING - Skipping BIOMD0000000500.xml - no results generated
2025-12-07 13:52:07,859 - WARNING - Skipping BIOMD0000000501.xml - no results generated
2025-12-07 13:52:07,872 - WARNING - Skipping BIOMD0000000502.xml - no results generated
2025-12-07 13:52:07,912 - WARNING - Skipping BIOMD0000000503.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000499.txt
Evaluating 500/1075: BIOMD0000000500.xml
Evaluating 501/1075: BIOMD0000000501.xml
Evaluating 502/1075: BIOMD0000000502.xml
Evaluating 503/1075: BIOMD0000000503.xml
Evaluating 504/1075: BIOMD0000000504.xml

2025-12-07 13:52:30,754 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:52:31,253 - WARNING - Skipping BIOMD0000000505.xml - no results generated
2025-12-07 13:52:31,322 - WARNING - Skipping BIOMD0000000506.xml - no results generated
2025-12-07 13:52:31,326 - WARNING - Skipping BIOMD0000000507.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000504.txt
Evaluating 505/1075: BIOMD0000000505.xml
Evaluating 506/1075: BIOMD0000000506.xml
Evaluating 507/1075: BIOMD0000000507.xml
Evaluating 508/1075: BIOMD0000000508.xml

2025-12-07 13:52:33,300 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000508.txt
Evaluating 509/1075: BIOMD0000000509.xml

2025-12-07 13:52:35,395 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:52:35,477 - WARNING - Skipping BIOMD0000000510.xml - no results generated
2025-12-07 13:52:35,496 - WARNING - Skipping BIOMD0000000511.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000509.txt
Evaluating 510/1075: BIOMD0000000510.xml
Evaluating 511/1075: BIOMD0000000511.xml
Evaluating 512/1075: BIOMD0000000512.xml

2025-12-07 13:52:38,022 - WARNING - Skipping BIOMD0000000513.xml - no results generated
2025-12-07 13:52:38,041 - WARNING - Skipping BIOMD0000000514.xml - no results generated
2025-12-07 13:52:38,063 - WARNING - Skipping BIOMD0000000515.xml - no results generated
2025-12-07 13:52:38,086 - WARNING - Skipping BIOMD0000000516.xml - no results generated
2025-12-07 13:52:38,092 - WARNING - Skipping BIOMD0000000517.xml - no results generated
2025-12-07 13:52:38,098 - WARNING - Skipping BIOMD0000000518.xml - no results generated
2025-12-07 13:52:38,103 - WARNING - Skipping BIOMD0000000519.xml - no results generated
2025-12-07 13:52:38,109 - WARNING - Skipping BIOMD0000000520.xml - no results generated
2025-12-07 13:52:38,112 - WARNING - Skipping BIOMD0000000521.xml - no results generated
2025-12-07 13:52:38,118 - WARNING - Skipping BIOMD0000000522.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000512.txt
Evaluating 513/1075: BIOMD0000000513.xml
Evaluating 514/1075: BIOMD0000000514.xml
Evaluating 515/1075: BIOMD0000000515.xml
Evaluating 516/1075: BIOMD0000000516.xml
Evaluating 517/1075: BIOMD0000000517.xml
Evaluating 518/1075: BIOMD0000000518.xml
Evaluating 519/1075: BIOMD0000000519.xml
Evaluating 520/1075: BIOMD0000000520.xml
Evaluating 521/1075: BIOMD0000000521.xml
Evaluating 522/1075: BIOMD0000000522.xml
Evaluating 523/1075: BIOMD0000000523.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000523.txt
Evaluating 524/1075: BIOMD0000000524.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000524.txt
Evaluating 525/1075: BIOMD0000000525.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000525.txt
Evaluating 526/1075: BIOMD0000000526.xml

2025-12-07 13:52:57,567 - WARNING - Skipping BIOMD0000000527.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000526.txt
Evaluating 527/1075: BIOMD0000000527.xml
Evaluating 528/1075: BIOMD0000000528.xml

2025-12-07 13:53:00,589 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000528.txt
Evaluating 529/1075: BIOMD0000000529.xml

2025-12-07 13:53:03,394 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:53:03,412 - WARNING - Skipping BIOMD0000000530.xml - no results generated
2025-12-07 13:53:03,416 - WARNING - Skipping BIOMD0000000531.xml - no results generated
2025-12-07 13:53:03,421 - WARNING - Skipping BIOMD0000000532.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000529.txt
Evaluating 530/1075: BIOMD0000000530.xml
Evaluating 531/1075: BIOMD0000000531.xml
Evaluating 532/1075: BIOMD0000000532.xml
Evaluating 533/1075: BIOMD0000000533.xml

2025-12-07 13:53:07,578 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000533.txt
Evaluating 534/1075: BIOMD0000000534.xml

2025-12-07 13:53:28,143 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000534.txt
Evaluating 535/1075: BIOMD0000000535.xml

2025-12-07 13:53:44,797 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000535.txt
Evaluating 536/1075: BIOMD0000000536.xml

2025-12-07 13:54:03,092 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000536.txt
Evaluating 537/1075: BIOMD0000000537.xml

2025-12-07 13:54:27,080 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:54:27,308 - WARNING - Skipping BIOMD0000000538.xml - no results generated
2025-12-07 13:54:27,314 - WARNING - Skipping BIOMD0000000539.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000537.txt
Evaluating 538/1075: BIOMD0000000538.xml
Evaluating 539/1075: BIOMD0000000539.xml
Evaluating 540/1075: BIOMD0000000540.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000540.txt
Evaluating 541/1075: BIOMD0000000541.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000541.txt
Evaluating 542/1075: BIOMD0000000542.xml

2025-12-07 13:54:48,930 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000542.txt
Evaluating 543/1075: BIOMD0000000543.xml

2025-12-07 13:55:30,298 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000543.txt
Evaluating 544/1075: BIOMD0000000544.xml

2025-12-07 13:56:12,487 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:56:13,459 - WARNING - Skipping BIOMD0000000545.xml - no results generated
2025-12-07 13:56:13,478 - WARNING - Skipping BIOMD0000000546.xml - no results generated
2025-12-07 13:56:13,494 - WARNING - Skipping BIOMD0000000547.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000544.txt
Evaluating 545/1075: BIOMD0000000545.xml
Evaluating 546/1075: BIOMD0000000546.xml
Evaluating 547/1075: BIOMD0000000547.xml
Evaluating 548/1075: BIOMD0000000548.xml

2025-12-07 13:56:15,210 - WARNING - Skipping BIOMD0000000549.xml - no results generated
2025-12-07 13:56:15,213 - WARNING - Skipping BIOMD0000000550.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000548.txt
Evaluating 549/1075: BIOMD0000000549.xml
Evaluating 550/1075: BIOMD0000000550.xml
Evaluating 551/1075: BIOMD0000000551.xml

2025-12-07 13:56:17,014 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000551.txt
Evaluating 552/1075: BIOMD0000000552.xml

2025-12-07 13:56:17,988 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000552.txt
Evaluating 553/1075: BIOMD0000000553.xml

2025-12-07 13:56:19,188 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:56:19,227 - WARNING - Skipping BIOMD0000000554.xml - no results generated
2025-12-07 13:56:19,230 - WARNING - Skipping BIOMD0000000555.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000553.txt
Evaluating 554/1075: BIOMD0000000554.xml
Evaluating 555/1075: BIOMD0000000555.xml
Evaluating 556/1075: BIOMD0000000556.xml

2025-12-07 13:56:22,253 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000556.txt
Evaluating 557/1075: BIOMD0000000557.xml

2025-12-07 13:56:31,439 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000557.txt
Evaluating 558/1075: BIOMD0000000558.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000558.txt
Evaluating 559/1075: BIOMD0000000559.xml

2025-12-07 13:57:03,459 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000559.txt
Evaluating 560/1075: BIOMD0000000560.xml

2025-12-07 13:57:22,572 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:57:22,940 - WARNING - Skipping BIOMD0000000561.xml - no results generated
2025-12-07 13:57:22,946 - WARNING - Skipping BIOMD0000000562.xml - no results generated
2025-12-07 13:57:22,954 - WARNING - Skipping BIOMD0000000563.xml - no results generated
2025-12-07 13:57:22,978 - WARNING - Skipping BIOMD0000000564.xml - no results generated
2025-12-07 13:57:22,997 - WARNING - Skipping BIOMD0000000565.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000560.txt
Evaluating 561/1075: BIOMD0000000561.xml
Evaluating 562/1075: BIOMD0000000562.xml
Evaluating 563/1075: BIOMD0000000563.xml
Evaluating 564/1075: BIOMD0000000564.xml
Evaluating 565/1075: BIOMD0000000565.xml
Evaluating 566/1075: BIOMD0000000566.xml

2025-12-07 13:57:24,737 - WARNING - Skipping BIOMD0000000567.xml - no results generated
2025-12-07 13:57:24,768 - WARNING - Skipping BIOMD0000000568.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000566.txt
Evaluating 567/1075: BIOMD0000000567.xml
Evaluating 568/1075: BIOMD0000000568.xml
Evaluating 569/1075: BIOMD0000000569.xml

2025-12-07 13:57:26,433 - WARNING - Skipping BIOMD0000000570.xml - no results generated
2025-12-07 13:57:26,463 - WARNING - Skipping BIOMD0000000571.xml - no results generated
2025-12-07 13:57:26,483 - WARNING - Skipping BIOMD0000000572.xml - no results generated
2025-12-07 13:57:26,487 - WARNING - Skipping BIOMD0000000573.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000569.txt
Evaluating 570/1075: BIOMD0000000570.xml
Evaluating 571/1075: BIOMD0000000571.xml
Evaluating 572/1075: BIOMD0000000572.xml
Evaluating 573/1075: BIOMD0000000573.xml
Evaluating 574/1075: BIOMD0000000574.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000574.txt
Evaluating 575/1075: BIOMD0000000575.xml

2025-12-07 13:58:07,746 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:58:07,826 - WARNING - Species 's28': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 13:58:07,827 - WARNING - Species 'Ligand2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000575.txt
Evaluating 576/1075: BIOMD0000000576.xml

2025-12-07 13:58:21,210 - WARNING - Skipping BIOMD0000000576.xml - no results generated
2025-12-07 13:58:21,277 - WARNING - Skipping BIOMD0000000577.xml - no results generated
2025-12-07 13:58:21,299 - WARNING - Skipping BIOMD0000000578.xml - no results generated

Evaluating 577/1075: BIOMD0000000577.xml
Evaluating 578/1075: BIOMD0000000578.xml
Evaluating 579/1075: BIOMD0000000579.xml

2025-12-07 13:58:43,296 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000579.txt
Evaluating 580/1075: BIOMD0000000580.xml

2025-12-07 13:58:57,817 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000580.txt
Evaluating 581/1075: BIOMD0000000581.xml

2025-12-07 13:59:06,010 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000581.txt
Evaluating 582/1075: BIOMD0000000582.xml

2025-12-07 13:59:11,308 - WARNING - Skipping BIOMD0000000583.xml - no results generated
2025-12-07 13:59:11,313 - WARNING - Skipping BIOMD0000000584.xml - no results generated
2025-12-07 13:59:11,319 - WARNING - Skipping BIOMD0000000585.xml - no results generated
2025-12-07 13:59:11,331 - WARNING - Skipping BIOMD0000000586.xml - no results generated
2025-12-07 13:59:11,341 - WARNING - Skipping BIOMD0000000587.xml - no results generated
2025-12-07 13:59:11,381 - WARNING - Skipping BIOMD0000000588.xml - no results generated
2025-12-07 13:59:11,393 - WARNING - Species 'GSH': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 13:59:11,393 - WARNING - Species 'H2O2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 13:59:11,394 - WARNING - Skipping BIOMD0000000589.xml - no results generated
2025-12-07 13:59:11,405 - WARNING - Skipping BIOMD0000000590.xml - no results generated
2025-12-07 13:59:11,410 - WARNING - Skipping BIOMD0000000591.xml - no results generated
2025-12-07 13:59:11,414 - WARNING - Skipping BIOMD0000000592.xml - no results generated
2025-12-07 13:59:11,421 - WARNING - Skipping BIOMD0000000593.xml - no results generated
2025-12-07 13:59:11,457 - WARNING - Species 'Grb2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000582.txt
Evaluating 583/1075: BIOMD0000000583.xml
Evaluating 584/1075: BIOMD0000000584.xml
Evaluating 585/1075: BIOMD0000000585.xml
Evaluating 586/1075: BIOMD0000000586.xml
Evaluating 587/1075: BIOMD0000000587.xml
Evaluating 588/1075: BIOMD0000000588.xml
Evaluating 589/1075: BIOMD0000000589.xml
Evaluating 590/1075: BIOMD0000000590.xml
Evaluating 591/1075: BIOMD0000000591.xml
Evaluating 592/1075: BIOMD0000000592.xml
Evaluating 593/1075: BIOMD0000000593.xml
Evaluating 594/1075: BIOMD0000000594.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000594.txt
Evaluating 595/1075: BIOMD0000000595.xml

2025-12-07 13:59:21,158 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000595.txt
Evaluating 596/1075: BIOMD0000000596.xml

2025-12-07 13:59:24,694 - WARNING - Skipping BIOMD0000000597.xml - no results generated
2025-12-07 13:59:24,716 - WARNING - Skipping BIOMD0000000598.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000596.txt
Evaluating 597/1075: BIOMD0000000597.xml
Evaluating 598/1075: BIOMD0000000598.xml
Evaluating 599/1075: BIOMD0000000599.xml

2025-12-07 13:59:34,823 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000599.txt
Evaluating 600/1075: BIOMD0000000600.xml

2025-12-07 13:59:37,905 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:59:37,946 - WARNING - Skipping BIOMD0000000601.xml - no results generated
2025-12-07 13:59:37,992 - WARNING - Skipping BIOMD0000000602.xml - no results generated
2025-12-07 13:59:38,028 - WARNING - Skipping BIOMD0000000603.xml - no results generated
2025-12-07 13:59:38,063 - WARNING - Skipping BIOMD0000000604.xml - no results generated
2025-12-07 13:59:38,097 - WARNING - Skipping BIOMD0000000605.xml - no results generated
2025-12-07 13:59:38,131 - WARNING - Skipping BIOMD0000000606.xml - no results generated
2025-12-07 13:59:38,162 - WARNING - Skipping BIOMD0000000607.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000600.txt
Evaluating 601/1075: BIOMD0000000601.xml
Evaluating 602/1075: BIOMD0000000602.xml
Evaluating 603/1075: BIOMD0000000603.xml
Evaluating 604/1075: BIOMD0000000604.xml
Evaluating 605/1075: BIOMD0000000605.xml
Evaluating 606/1075: BIOMD0000000606.xml
Evaluating 607/1075: BIOMD0000000607.xml

2025-12-07 13:59:38,190 - WARNING - Skipping BIOMD0000000608.xml - no results generated

Evaluating 608/1075: BIOMD0000000608.xml
Evaluating 609/1075: BIOMD0000000609.xml

2025-12-07 13:59:40,132 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 13:59:40,194 - WARNING - Skipping BIOMD0000000610.xml - no results generated
2025-12-07 13:59:40,220 - WARNING - Skipping BIOMD0000000611.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000609.txt
Evaluating 610/1075: BIOMD0000000610.xml
Evaluating 611/1075: BIOMD0000000611.xml
Evaluating 612/1075: BIOMD0000000612.xml

2025-12-07 13:59:48,698 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000612.txt
Evaluating 613/1075: BIOMD0000000613.xml

2025-12-07 13:59:54,695 - WARNING - Species 'f': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000613.txt
Evaluating 614/1075: BIOMD0000000614.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000614.txt
Evaluating 615/1075: BIOMD0000000615.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000615.txt
Evaluating 616/1075: BIOMD0000000616.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000616.txt
Evaluating 617/1075: BIOMD0000000617.xml

2025-12-07 14:00:00,680 - WARNING - Skipping BIOMD0000000618.xml - no results generated
2025-12-07 14:00:00,689 - WARNING - Skipping BIOMD0000000619.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000617.txt
Evaluating 618/1075: BIOMD0000000618.xml
Evaluating 619/1075: BIOMD0000000619.xml
Evaluating 620/1075: BIOMD0000000620.xml

2025-12-07 14:00:03,657 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000620.txt
Evaluating 621/1075: BIOMD0000000621.xml

2025-12-07 14:00:07,369 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000621.txt
Evaluating 622/1075: BIOMD0000000622.xml

2025-12-07 14:00:13,440 - WARNING - Skipping BIOMD0000000623.xml - no results generated
2025-12-07 14:00:13,445 - WARNING - Skipping BIOMD0000000624.xml - no results generated
2025-12-07 14:00:13,467 - WARNING - Skipping BIOMD0000000625.xml - no results generated
2025-12-07 14:00:13,477 - WARNING - Skipping BIOMD0000000626.xml - no results generated
2025-12-07 14:00:13,539 - WARNING - Skipping BIOMD0000000627.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000622.txt
Evaluating 623/1075: BIOMD0000000623.xml
Evaluating 624/1075: BIOMD0000000624.xml
Evaluating 625/1075: BIOMD0000000625.xml
Evaluating 626/1075: BIOMD0000000626.xml
Evaluating 627/1075: BIOMD0000000627.xml
Evaluating 628/1075: BIOMD0000000628.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000628.txt
Evaluating 629/1075: BIOMD0000000629.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000629.txt
Evaluating 630/1075: BIOMD0000000630.xml

2025-12-07 14:00:32,496 - WARNING - Skipping BIOMD0000000631.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000630.txt
Evaluating 631/1075: BIOMD0000000631.xml
Evaluating 632/1075: BIOMD0000000632.xml

2025-12-07 14:00:36,101 - WARNING - Skipping BIOMD0000000633.xml - no results generated
2025-12-07 14:00:36,130 - WARNING - Species 'Mdm2_P_Ub2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:00:36,130 - WARNING - Species 'Mdm2_P_Ub3': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000632.txt
Evaluating 633/1075: BIOMD0000000633.xml
Evaluating 634/1075: BIOMD0000000634.xml

2025-12-07 14:00:49,651 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:00:49,731 - WARNING - Skipping BIOMD0000000635.xml - no results generated
2025-12-07 14:00:49,774 - WARNING - Species 'mw9710c658_a2a1_4f49_b494_af109853f251': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:00:49,776 - WARNING - Skipping BIOMD0000000636.xml - no results generated
2025-12-07 14:00:49,792 - WARNING - Skipping BIOMD0000000637.xml - no results generated
2025-12-07 14:00:49,818 - WARNING - Skipping BIOMD0000000638.xml - no results generated
2025-12-07 14:00:49,825 - WARNING - Skipping BIOMD0000000639.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000634.txt
Evaluating 635/1075: BIOMD0000000635.xml
Evaluating 636/1075: BIOMD0000000636.xml
Evaluating 637/1075: BIOMD0000000637.xml
Evaluating 638/1075: BIOMD0000000638.xml
Evaluating 639/1075: BIOMD0000000639.xml
Evaluating 640/1075: BIOMD0000000640.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000640.txt
Evaluating 641/1075: BIOMD0000000641.xml

2025-12-07 14:00:57,152 - WARNING - Skipping BIOMD0000000642.xml - no results generated
2025-12-07 14:00:57,159 - WARNING - Skipping BIOMD0000000643.xml - no results generated
2025-12-07 14:00:57,167 - WARNING - Skipping BIOMD0000000644.xml - no results generated
2025-12-07 14:00:57,176 - WARNING - Skipping BIOMD0000000645.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000641.txt
Evaluating 642/1075: BIOMD0000000642.xml
Evaluating 643/1075: BIOMD0000000643.xml
Evaluating 644/1075: BIOMD0000000644.xml
Evaluating 645/1075: BIOMD0000000645.xml
Evaluating 646/1075: BIOMD0000000646.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000646.txt
Evaluating 647/1075: BIOMD0000000647.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000647.txt
Evaluating 648/1075: BIOMD0000000648.xml

2025-12-07 14:01:19,233 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:01:19,272 - WARNING - Skipping BIOMD0000000650.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000648.txt
Evaluating 649/1075: BIOMD0000000650.xml
Evaluating 650/1075: BIOMD0000000651.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000651.txt
Evaluating 651/1075: BIOMD0000000652.xml

2025-12-07 14:01:43,732 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000652.txt
Evaluating 652/1075: BIOMD0000000653.xml

2025-12-07 14:01:56,986 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000653.txt
Evaluating 653/1075: BIOMD0000000654.xml

2025-12-07 14:02:14,548 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000654.txt
Evaluating 654/1075: BIOMD0000000655.xml

2025-12-07 14:02:29,809 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000655.txt
Evaluating 655/1075: BIOMD0000000656.xml

2025-12-07 14:02:47,788 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000656.txt
Evaluating 656/1075: BIOMD0000000657.xml

2025-12-07 14:02:49,649 - WARNING - Skipping BIOMD0000000658.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000657.txt
Evaluating 657/1075: BIOMD0000000658.xml
Evaluating 658/1075: BIOMD0000000659.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000659.txt
Evaluating 659/1075: BIOMD0000000660.xml

2025-12-07 14:02:57,690 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000660.txt
Evaluating 660/1075: BIOMD0000000661.xml

2025-12-07 14:02:59,653 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:02:59,680 - WARNING - Skipping BIOMD0000000662.xml - no results generated
2025-12-07 14:02:59,688 - WARNING - Skipping BIOMD0000000663.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000661.txt
Evaluating 661/1075: BIOMD0000000662.xml
Evaluating 662/1075: BIOMD0000000663.xml
Evaluating 663/1075: BIOMD0000000664.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000664.txt
Evaluating 664/1075: BIOMD0000000665.xml

2025-12-07 14:03:07,939 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000665.txt
Evaluating 665/1075: BIOMD0000000666.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000666.txt
Evaluating 666/1075: BIOMD0000000667.xml

2025-12-07 14:03:52,977 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:03:53,893 - WARNING - Species 'Inh_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:03:53,894 - WARNING - Species 'Inh_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:03:53,894 - WARNING - Species 'Sti_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:03:53,894 - WARNING - Species 'Sti_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:03:53,896 - WARNING - Skipping BIOMD0000000668.xml - no results generated
2025-12-07 14:03:53,915 - WARNING - Skipping BIOMD0000000669.xml - no results generated
2025-12-07 14:03:53,918 - WARNING - Skipping BIOMD0000000670.xml - no results generated
2025-12-07 14:03:53,923 - WARNING - Skipping BIOMD0000000671.xml - no results generated
2025-12-07 14:03:53,929 - WARNING - Skipping BIOMD0000000672.xml - no results generated
2025-12-07 14:03:53,939 - WARNING - Skipping BIOMD0000000673.xml - no results generated
2025-12-07 14:03:53,993 - WARNING - Skipping BIOMD0000000674.xml - no results generated
2025-12-07 14:03:54,018 - WARNING - Skipping BIOMD0000000675.xml - no results generated
2025-12-07 14:03:54,031 - WARNING - Skipping BIOMD0000000676.xml - no results generated
2025-12-07 14:03:54,035 - WARNING - Skipping BIOMD0000000677.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000667.txt
Evaluating 667/1075: BIOMD0000000668.xml
Evaluating 668/1075: BIOMD0000000669.xml
Evaluating 669/1075: BIOMD0000000670.xml
Evaluating 670/1075: BIOMD0000000671.xml
Evaluating 671/1075: BIOMD0000000672.xml
Evaluating 672/1075: BIOMD0000000673.xml
Evaluating 673/1075: BIOMD0000000674.xml
Evaluating 674/1075: BIOMD0000000675.xml
Evaluating 675/1075: BIOMD0000000676.xml
Evaluating 676/1075: BIOMD0000000677.xml
Evaluating 677/1075: BIOMD0000000678.xml

2025-12-07 14:03:56,299 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:03:56,300 - WARNING - Skipping BIOMD0000000679.xml - no results generated
2025-12-07 14:03:56,305 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:03:56,306 - WARNING - Skipping BIOMD0000000680.xml - no results generated
2025-12-07 14:03:56,312 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:03:56,312 - WARNING - Skipping BIOMD0000000681.xml - no results generated
2025-12-07 14:03:56,324 - WARNING - Skipping BIOMD0000000682.xml - no results generated
2025-12-07 14:03:56,333 - WARNING - Skipping BIOMD0000000683.xml - no results generated
2025-12-07 14:03:56,344 - WARNING - Skipping BIOMD0000000684.xml - no results generated
2025-12-07 14:03:56,350 - WARNING - Skipping BIOMD0000000685.xml - no results generated
2025-12-07 14:03:56,356 - WARNING - Skipping BIOMD0000000686.xml - no results generated
2025-12-07 14:03:56,371 - WARNING - Skipping BIOMD0000000687.xml - no results generated
2025-12-07 14:03:56,393 - WARNING - Skipping BIOMD0000000688.xml - no results generated
2025-12-07 14:03:56,403 - WARNING - Skipping BIOMD0000000689.xml - no results generated
2025-12-07 14:03:56,415 - WARNING - Skipping BIOMD0000000690.xml - no results generated
2025-12-07 14:03:56,430 - WARNING - Skipping BIOMD0000000691.xml - no results generated
2025-12-07 14:03:56,438 - WARNING - Skipping BIOMD0000000692.xml - no results generated
2025-12-07 14:03:56,448 - WARNING - Skipping BIOMD0000000693.xml - no results generated
2025-12-07 14:03:56,476 - WARNING - Skipping BIOMD0000000695.xml - no results generated
2025-12-07 14:03:56,492 - WARNING - Skipping BIOMD0000000696.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000678.txt
Evaluating 678/1075: BIOMD0000000679.xml
Evaluating 679/1075: BIOMD0000000680.xml
Evaluating 680/1075: BIOMD0000000681.xml
Evaluating 681/1075: BIOMD0000000682.xml
Evaluating 682/1075: BIOMD0000000683.xml
Evaluating 683/1075: BIOMD0000000684.xml
Evaluating 684/1075: BIOMD0000000685.xml
Evaluating 685/1075: BIOMD0000000686.xml
Evaluating 686/1075: BIOMD0000000687.xml
Evaluating 687/1075: BIOMD0000000688.xml
Evaluating 688/1075: BIOMD0000000689.xml
Evaluating 689/1075: BIOMD0000000690.xml
Evaluating 690/1075: BIOMD0000000691.xml
Evaluating 691/1075: BIOMD0000000692.xml
Evaluating 692/1075: BIOMD0000000693.xml
Evaluating 693/1075: BIOMD0000000695.xml
Evaluating 694/1075: BIOMD0000000696.xml
Evaluating 695/1075: BIOMD0000000697.xml

2025-12-07 14:03:56,514 - WARNING - Skipping BIOMD0000000697.xml - no results generated
2025-12-07 14:03:56,524 - WARNING - Skipping BIOMD0000000698.xml - no results generated
2025-12-07 14:03:56,556 - WARNING - Skipping BIOMD0000000699.xml - no results generated

Evaluating 696/1075: BIOMD0000000698.xml
Evaluating 697/1075: BIOMD0000000699.xml
Evaluating 698/1075: BIOMD0000000700.xml

2025-12-07 14:04:06,470 - WARNING - Skipping BIOMD0000000701.xml - no results generated
2025-12-07 14:04:06,500 - WARNING - Skipping BIOMD0000000702.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000700.txt
Evaluating 699/1075: BIOMD0000000701.xml
Evaluating 700/1075: BIOMD0000000702.xml
Evaluating 701/1075: BIOMD0000000703.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000703.txt
Evaluating 702/1075: BIOMD0000000704.xml

2025-12-07 14:04:17,355 - WARNING - Skipping BIOMD0000000705.xml - no results generated
2025-12-07 14:04:17,417 - WARNING - Skipping BIOMD0000000706.xml - no results generated
2025-12-07 14:04:17,424 - WARNING - Skipping BIOMD0000000707.xml - no results generated
2025-12-07 14:04:17,433 - WARNING - Skipping BIOMD0000000708.xml - no results generated
2025-12-07 14:04:17,440 - WARNING - Skipping BIOMD0000000709.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000704.txt
Evaluating 703/1075: BIOMD0000000705.xml
Evaluating 704/1075: BIOMD0000000706.xml
Evaluating 705/1075: BIOMD0000000707.xml
Evaluating 706/1075: BIOMD0000000708.xml
Evaluating 707/1075: BIOMD0000000709.xml
Evaluating 708/1075: BIOMD0000000710.xml

2025-12-07 14:04:18,834 - WARNING - Skipping BIOMD0000000711.xml - no results generated
2025-12-07 14:04:18,839 - WARNING - Skipping BIOMD0000000712.xml - no results generated
2025-12-07 14:04:18,846 - WARNING - Skipping BIOMD0000000713.xml - no results generated
2025-12-07 14:04:18,852 - WARNING - Skipping BIOMD0000000714.xml - no results generated
2025-12-07 14:04:18,859 - WARNING - Skipping BIOMD0000000715.xml - no results generated
2025-12-07 14:04:18,868 - WARNING - Skipping BIOMD0000000716.xml - no results generated
2025-12-07 14:04:18,878 - WARNING - Skipping BIOMD0000000717.xml - no results generated
2025-12-07 14:04:18,899 - WARNING - Skipping BIOMD0000000718.xml - no results generated
2025-12-07 14:04:18,909 - WARNING - Skipping BIOMD0000000719.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000710.txt
Evaluating 709/1075: BIOMD0000000711.xml
Evaluating 710/1075: BIOMD0000000712.xml
Evaluating 711/1075: BIOMD0000000713.xml
Evaluating 712/1075: BIOMD0000000714.xml
Evaluating 713/1075: BIOMD0000000715.xml
Evaluating 714/1075: BIOMD0000000716.xml
Evaluating 715/1075: BIOMD0000000717.xml
Evaluating 716/1075: BIOMD0000000718.xml
Evaluating 717/1075: BIOMD0000000719.xml
Evaluating 718/1075: BIOMD0000000720.xml

2025-12-07 14:04:22,252 - WARNING - Skipping BIOMD0000000721.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000720.txt
Evaluating 719/1075: BIOMD0000000721.xml
Evaluating 720/1075: BIOMD0000000722.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000722.txt
Evaluating 721/1075: BIOMD0000000723.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000723.txt
Evaluating 722/1075: BIOMD0000000724.xml

2025-12-07 14:04:45,619 - WARNING - Skipping BIOMD0000000725.xml - no results generated
2025-12-07 14:04:45,629 - WARNING - Skipping BIOMD0000000726.xml - no results generated
2025-12-07 14:04:45,668 - WARNING - Skipping BIOMD0000000727.xml - no results generated
2025-12-07 14:04:45,677 - WARNING - Skipping BIOMD0000000728.xml - no results generated
2025-12-07 14:04:45,685 - WARNING - Skipping BIOMD0000000729.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000724.txt
Evaluating 723/1075: BIOMD0000000725.xml
Evaluating 724/1075: BIOMD0000000726.xml
Evaluating 725/1075: BIOMD0000000727.xml
Evaluating 726/1075: BIOMD0000000728.xml
Evaluating 727/1075: BIOMD0000000729.xml
Evaluating 728/1075: BIOMD0000000730.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000730.txt
Evaluating 729/1075: BIOMD0000000731.xml

2025-12-07 14:04:58,595 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000731.txt
Evaluating 730/1075: BIOMD0000000732.xml

2025-12-07 14:05:00,014 - WARNING - Skipping BIOMD0000000733.xml - no results generated
2025-12-07 14:05:00,040 - WARNING - Skipping BIOMD0000000734.xml - no results generated
2025-12-07 14:05:00,067 - WARNING - Skipping BIOMD0000000735.xml - no results generated
2025-12-07 14:05:00,084 - WARNING - Skipping BIOMD0000000736.xml - no results generated
2025-12-07 14:05:00,100 - WARNING - Skipping BIOMD0000000737.xml - no results generated
2025-12-07 14:05:00,115 - WARNING - Skipping BIOMD0000000738.xml - no results generated
2025-12-07 14:05:00,130 - WARNING - Species 'Va_i_306': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:00,130 - WARNING - Species 'Va_1_306_Va_LC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:00,130 - WARNING - Species 'Va_307_506': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:00,131 - WARNING - Species 'Va_507_679_709': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:00,132 - WARNING - Skipping BIOMD0000000739.xml - no results generated
2025-12-07 14:05:00,146 - WARNING - Species 'Xa_TFPI': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:00,147 - WARNING - Species 'Xa_VIIa_TF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:00,148 - WARNING - Skipping BIOMD0000000740.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000732.txt
Evaluating 731/1075: BIOMD0000000733.xml
Evaluating 732/1075: BIOMD0000000734.xml
Evaluating 733/1075: BIOMD0000000735.xml
Evaluating 734/1075: BIOMD0000000736.xml
Evaluating 735/1075: BIOMD0000000737.xml
Evaluating 736/1075: BIOMD0000000738.xml
Evaluating 737/1075: BIOMD0000000739.xml
Evaluating 738/1075: BIOMD0000000740.xml
Evaluating 739/1075: BIOMD0000000741.xml

2025-12-07 14:05:01,723 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:05:01,757 - WARNING - Skipping BIOMD0000000742.xml - no results generated
2025-12-07 14:05:01,776 - WARNING - Skipping BIOMD0000000743.xml - no results generated
2025-12-07 14:05:01,794 - WARNING - Skipping BIOMD0000000744.xml - no results generated
2025-12-07 14:05:01,807 - WARNING - Skipping BIOMD0000000745.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000741.txt
Evaluating 740/1075: BIOMD0000000742.xml
Evaluating 741/1075: BIOMD0000000743.xml
Evaluating 742/1075: BIOMD0000000744.xml
Evaluating 743/1075: BIOMD0000000745.xml
Evaluating 744/1075: BIOMD0000000746.xml

2025-12-07 14:05:03,219 - WARNING - Skipping BIOMD0000000747.xml - no results generated
2025-12-07 14:05:03,230 - WARNING - Skipping BIOMD0000000748.xml - no results generated
2025-12-07 14:05:03,240 - WARNING - Skipping BIOMD0000000749.xml - no results generated
2025-12-07 14:05:03,262 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:03,263 - WARNING - Skipping BIOMD0000000750.xml - no results generated
2025-12-07 14:05:03,269 - WARNING - Skipping BIOMD0000000751.xml - no results generated
2025-12-07 14:05:03,275 - WARNING - Skipping BIOMD0000000752.xml - no results generated
2025-12-07 14:05:03,283 - WARNING - Skipping BIOMD0000000753.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000746.txt
Evaluating 745/1075: BIOMD0000000747.xml
Evaluating 746/1075: BIOMD0000000748.xml
Evaluating 747/1075: BIOMD0000000749.xml
Evaluating 748/1075: BIOMD0000000750.xml
Evaluating 749/1075: BIOMD0000000751.xml
Evaluating 750/1075: BIOMD0000000752.xml
Evaluating 751/1075: BIOMD0000000753.xml
Evaluating 752/1075: BIOMD0000000754.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000754.txt
Evaluating 753/1075: BIOMD0000000755.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000755.txt
Evaluating 754/1075: BIOMD0000000756.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000756.txt
Evaluating 755/1075: BIOMD0000000757.xml

2025-12-07 14:05:11,903 - WARNING - Skipping BIOMD0000000758.xml - no results generated
2025-12-07 14:05:11,918 - WARNING - Skipping BIOMD0000000759.xml - no results generated
2025-12-07 14:05:11,923 - WARNING - Skipping BIOMD0000000760.xml - no results generated
2025-12-07 14:05:11,936 - WARNING - Skipping BIOMD0000000761.xml - no results generated
2025-12-07 14:05:11,943 - WARNING - Skipping BIOMD0000000762.xml - no results generated
2025-12-07 14:05:11,950 - WARNING - Skipping BIOMD0000000763.xml - no results generated
2025-12-07 14:05:11,959 - WARNING - Skipping BIOMD0000000764.xml - no results generated
2025-12-07 14:05:11,967 - WARNING - Skipping BIOMD0000000765.xml - no results generated
2025-12-07 14:05:11,977 - WARNING - Skipping BIOMD0000000766.xml - no results generated
2025-12-07 14:05:11,983 - WARNING - Skipping BIOMD0000000767.xml - no results generated
2025-12-07 14:05:11,998 - WARNING - Skipping BIOMD0000000768.xml - no results generated
2025-12-07 14:05:12,019 - WARNING - Skipping BIOMD0000000769.xml - no results generated
2025-12-07 14:05:12,031 - WARNING - Skipping BIOMD0000000770.xml - no results generated
2025-12-07 14:05:12,036 - WARNING - Skipping BIOMD0000000771.xml - no results generated
2025-12-07 14:05:12,042 - WARNING - Skipping BIOMD0000000772.xml - no results generated
2025-12-07 14:05:12,051 - WARNING - Skipping BIOMD0000000773.xml - no results generated
2025-12-07 14:05:12,057 - WARNING - Skipping BIOMD0000000774.xml - no results generated
2025-12-07 14:05:12,068 - WARNING - Skipping BIOMD0000000775.xml - no results generated
2025-12-07 14:05:12,074 - WARNING - Skipping BIOMD0000000776.xml - no results generated
2025-12-07 14:05:12,079 - WARNING - Skipping BIOMD0000000777.xml - no results generated
2025-12-07 14:05:12,087 - WARNING - Skipping BIOMD0000000778.xml - no results generated
2025-12-07 14:05:12,101 - WARNING - Skipping BIOMD0000000779.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000757.txt
Evaluating 756/1075: BIOMD0000000758.xml
Evaluating 757/1075: BIOMD0000000759.xml
Evaluating 758/1075: BIOMD0000000760.xml
Evaluating 759/1075: BIOMD0000000761.xml
Evaluating 760/1075: BIOMD0000000762.xml
Evaluating 761/1075: BIOMD0000000763.xml
Evaluating 762/1075: BIOMD0000000764.xml
Evaluating 763/1075: BIOMD0000000765.xml
Evaluating 764/1075: BIOMD0000000766.xml
Evaluating 765/1075: BIOMD0000000767.xml
Evaluating 766/1075: BIOMD0000000768.xml
Evaluating 767/1075: BIOMD0000000769.xml
Evaluating 768/1075: BIOMD0000000770.xml
Evaluating 769/1075: BIOMD0000000771.xml
Evaluating 770/1075: BIOMD0000000772.xml
Evaluating 771/1075: BIOMD0000000773.xml
Evaluating 772/1075: BIOMD0000000774.xml
Evaluating 773/1075: BIOMD0000000775.xml
Evaluating 774/1075: BIOMD0000000776.xml
Evaluating 775/1075: BIOMD0000000777.xml
Evaluating 776/1075: BIOMD0000000778.xml
Evaluating 777/1075: BIOMD0000000779.xml
Evaluating 778/1075: BIOMD0000000780.xml

2025-12-07 14:05:12,109 - WARNING - Skipping BIOMD0000000780.xml - no results generated
2025-12-07 14:05:12,116 - WARNING - Skipping BIOMD0000000781.xml - no results generated
2025-12-07 14:05:12,121 - WARNING - Skipping BIOMD0000000782.xml - no results generated
2025-12-07 14:05:12,127 - WARNING - Skipping BIOMD0000000783.xml - no results generated
2025-12-07 14:05:12,133 - WARNING - Skipping BIOMD0000000784.xml - no results generated
2025-12-07 14:05:12,138 - WARNING - Skipping BIOMD0000000785.xml - no results generated
2025-12-07 14:05:12,212 - WARNING - Skipping BIOMD0000000786.xml - no results generated
2025-12-07 14:05:12,216 - WARNING - Skipping BIOMD0000000787.xml - no results generated
2025-12-07 14:05:12,228 - WARNING - Skipping BIOMD0000000788.xml - no results generated
2025-12-07 14:05:12,235 - WARNING - Skipping BIOMD0000000789.xml - no results generated
2025-12-07 14:05:12,245 - WARNING - Skipping BIOMD0000000790.xml - no results generated

Evaluating 779/1075: BIOMD0000000781.xml
Evaluating 780/1075: BIOMD0000000782.xml
Evaluating 781/1075: BIOMD0000000783.xml
Evaluating 782/1075: BIOMD0000000784.xml
Evaluating 783/1075: BIOMD0000000785.xml
Evaluating 784/1075: BIOMD0000000786.xml
Evaluating 785/1075: BIOMD0000000787.xml
Evaluating 786/1075: BIOMD0000000788.xml
Evaluating 787/1075: BIOMD0000000789.xml
Evaluating 788/1075: BIOMD0000000790.xml
Evaluating 789/1075: BIOMD0000000791.xml

2025-12-07 14:05:14,048 - WARNING - Skipping BIOMD0000000792.xml - no results generated
2025-12-07 14:05:14,058 - WARNING - Skipping BIOMD0000000793.xml - no results generated
2025-12-07 14:05:14,142 - WARNING - Skipping BIOMD0000000794.xml - no results generated
2025-12-07 14:05:14,148 - WARNING - Skipping BIOMD0000000795.xml - no results generated
2025-12-07 14:05:14,162 - WARNING - Skipping BIOMD0000000796.xml - no results generated
2025-12-07 14:05:14,171 - WARNING - Skipping BIOMD0000000797.xml - no results generated
2025-12-07 14:05:14,186 - WARNING - Skipping BIOMD0000000798.xml - no results generated
2025-12-07 14:05:14,190 - WARNING - Skipping BIOMD0000000799.xml - no results generated
2025-12-07 14:05:14,199 - WARNING - Skipping BIOMD0000000800.xml - no results generated
2025-12-07 14:05:14,211 - WARNING - Skipping BIOMD0000000801.xml - no results generated
2025-12-07 14:05:14,220 - WARNING - Skipping BIOMD0000000802.xml - no results generated
2025-12-07 14:05:14,226 - WARNING - Skipping BIOMD0000000803.xml - no results generated
2025-12-07 14:05:14,235 - WARNING - Skipping BIOMD0000000804.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000791.txt
Evaluating 790/1075: BIOMD0000000792.xml
Evaluating 791/1075: BIOMD0000000793.xml
Evaluating 792/1075: BIOMD0000000794.xml
Evaluating 793/1075: BIOMD0000000795.xml
Evaluating 794/1075: BIOMD0000000796.xml
Evaluating 795/1075: BIOMD0000000797.xml
Evaluating 796/1075: BIOMD0000000798.xml
Evaluating 797/1075: BIOMD0000000799.xml
Evaluating 798/1075: BIOMD0000000800.xml
Evaluating 799/1075: BIOMD0000000801.xml
Evaluating 800/1075: BIOMD0000000802.xml
Evaluating 801/1075: BIOMD0000000803.xml
Evaluating 802/1075: BIOMD0000000804.xml
Evaluating 803/1075: BIOMD0000000805.xml

2025-12-07 14:05:14,244 - WARNING - Skipping BIOMD0000000805.xml - no results generated
2025-12-07 14:05:14,263 - WARNING - Skipping BIOMD0000000806.xml - no results generated
2025-12-07 14:05:14,277 - WARNING - Skipping BIOMD0000000807.xml - no results generated
2025-12-07 14:05:14,289 - WARNING - Skipping BIOMD0000000808.xml - no results generated
2025-12-07 14:05:14,298 - WARNING - Skipping BIOMD0000000809.xml - no results generated
2025-12-07 14:05:14,331 - WARNING - Skipping BIOMD0000000810.xml - no results generated
2025-12-07 14:05:14,347 - WARNING - Skipping BIOMD0000000811.xml - no results generated
2025-12-07 14:05:14,354 - WARNING - Skipping BIOMD0000000812.xml - no results generated
2025-12-07 14:05:14,359 - WARNING - Skipping BIOMD0000000813.xml - no results generated
2025-12-07 14:05:14,369 - WARNING - Skipping BIOMD0000000814.xml - no results generated
2025-12-07 14:05:14,375 - WARNING - Skipping BIOMD0000000815.xml - no results generated
2025-12-07 14:05:14,389 - WARNING - Skipping BIOMD0000000816.xml - no results generated
2025-12-07 14:05:14,403 - WARNING - Skipping BIOMD0000000817.xml - no results generated

Evaluating 804/1075: BIOMD0000000806.xml
Evaluating 805/1075: BIOMD0000000807.xml
Evaluating 806/1075: BIOMD0000000808.xml
Evaluating 807/1075: BIOMD0000000809.xml
Evaluating 808/1075: BIOMD0000000810.xml
Evaluating 809/1075: BIOMD0000000811.xml
Evaluating 810/1075: BIOMD0000000812.xml
Evaluating 811/1075: BIOMD0000000813.xml
Evaluating 812/1075: BIOMD0000000814.xml
Evaluating 813/1075: BIOMD0000000815.xml
Evaluating 814/1075: BIOMD0000000816.xml
Evaluating 815/1075: BIOMD0000000817.xml
Evaluating 816/1075: BIOMD0000000818.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000818.txt
Evaluating 817/1075: BIOMD0000000819.xml

2025-12-07 14:05:24,811 - WARNING - Skipping BIOMD0000000820.xml - no results generated
2025-12-07 14:05:24,817 - WARNING - Skipping BIOMD0000000821.xml - no results generated
2025-12-07 14:05:24,827 - WARNING - Skipping BIOMD0000000822.xml - no results generated
2025-12-07 14:05:24,840 - WARNING - Skipping BIOMD0000000823.xml - no results generated
2025-12-07 14:05:24,844 - WARNING - Skipping BIOMD0000000824.xml - no results generated
2025-12-07 14:05:24,850 - WARNING - Skipping BIOMD0000000825.xml - no results generated
2025-12-07 14:05:24,871 - WARNING - Skipping BIOMD0000000826.xml - no results generated
2025-12-07 14:05:24,881 - WARNING - Skipping BIOMD0000000827.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000819.txt
Evaluating 818/1075: BIOMD0000000820.xml
Evaluating 819/1075: BIOMD0000000821.xml
Evaluating 820/1075: BIOMD0000000822.xml
Evaluating 821/1075: BIOMD0000000823.xml
Evaluating 822/1075: BIOMD0000000824.xml
Evaluating 823/1075: BIOMD0000000825.xml
Evaluating 824/1075: BIOMD0000000826.xml
Evaluating 825/1075: BIOMD0000000827.xml
Evaluating 826/1075: BIOMD0000000828.xml

2025-12-07 14:05:26,791 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000828.txt
Evaluating 827/1075: BIOMD0000000829.xml

2025-12-07 14:05:30,929 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:05:31,067 - WARNING - Skipping BIOMD0000000830.xml - no results generated
2025-12-07 14:05:31,072 - WARNING - Skipping BIOMD0000000831.xml - no results generated
2025-12-07 14:05:31,090 - WARNING - Species 'LATS1': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000829.txt
Evaluating 828/1075: BIOMD0000000830.xml
Evaluating 829/1075: BIOMD0000000831.xml
Evaluating 830/1075: BIOMD0000000832.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000832.txt
Evaluating 831/1075: BIOMD0000000833.xml

2025-12-07 14:05:45,837 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:05:46,200 - WARNING - Skipping BIOMD0000000834.xml - no results generated
2025-12-07 14:05:46,239 - WARNING - Skipping BIOMD0000000835.xml - no results generated
2025-12-07 14:05:46,242 - WARNING - Skipping BIOMD0000000836.xml - no results generated
2025-12-07 14:05:46,252 - WARNING - Skipping BIOMD0000000837.xml - no results generated
2025-12-07 14:05:46,257 - WARNING - Skipping BIOMD0000000838.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000833.txt
Evaluating 832/1075: BIOMD0000000834.xml
Evaluating 833/1075: BIOMD0000000835.xml
Evaluating 834/1075: BIOMD0000000836.xml
Evaluating 835/1075: BIOMD0000000837.xml
Evaluating 836/1075: BIOMD0000000838.xml
Evaluating 837/1075: BIOMD0000000839.xml

2025-12-07 14:05:48,436 - WARNING - Skipping BIOMD0000000840.xml - no results generated
2025-12-07 14:05:48,443 - WARNING - Skipping BIOMD0000000841.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000839.txt
Evaluating 838/1075: BIOMD0000000840.xml
Evaluating 839/1075: BIOMD0000000841.xml
Evaluating 840/1075: BIOMD0000000842.xml

2025-12-07 14:05:55,894 - WARNING - Skipping BIOMD0000000843.xml - no results generated
2025-12-07 14:05:55,909 - WARNING - Skipping BIOMD0000000844.xml - no results generated
2025-12-07 14:05:55,913 - WARNING - Skipping BIOMD0000000845.xml - no results generated
2025-12-07 14:05:55,919 - WARNING - Skipping BIOMD0000000846.xml - no results generated
2025-12-07 14:05:55,925 - WARNING - Skipping BIOMD0000000847.xml - no results generated
2025-12-07 14:05:55,939 - WARNING - Skipping BIOMD0000000848.xml - no results generated
2025-12-07 14:05:56,029 - WARNING - Skipping BIOMD0000000849.xml - no results generated
2025-12-07 14:05:56,033 - WARNING - Skipping BIOMD0000000850.xml - no results generated
2025-12-07 14:05:56,039 - WARNING - Skipping BIOMD0000000851.xml - no results generated
2025-12-07 14:05:56,050 - WARNING - Skipping BIOMD0000000852.xml - no results generated
2025-12-07 14:05:56,062 - WARNING - Species 'STAB': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:56,064 - WARNING - Skipping BIOMD0000000853.xml - no results generated
2025-12-07 14:05:56,070 - WARNING - Skipping BIOMD0000000854.xml - no results generated
2025-12-07 14:05:56,081 - WARNING - Skipping BIOMD0000000855.xml - no results generated
2025-12-07 14:05:56,101 - WARNING - Skipping BIOMD0000000856.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000842.txt
Evaluating 841/1075: BIOMD0000000843.xml
Evaluating 842/1075: BIOMD0000000844.xml
Evaluating 843/1075: BIOMD0000000845.xml
Evaluating 844/1075: BIOMD0000000846.xml
Evaluating 845/1075: BIOMD0000000847.xml
Evaluating 846/1075: BIOMD0000000848.xml
Evaluating 847/1075: BIOMD0000000849.xml
Evaluating 848/1075: BIOMD0000000850.xml
Evaluating 849/1075: BIOMD0000000851.xml
Evaluating 850/1075: BIOMD0000000852.xml
Evaluating 851/1075: BIOMD0000000853.xml
Evaluating 852/1075: BIOMD0000000854.xml
Evaluating 853/1075: BIOMD0000000855.xml
Evaluating 854/1075: BIOMD0000000856.xml

2025-12-07 14:05:56,116 - WARNING - Skipping BIOMD0000000857.xml - no results generated
2025-12-07 14:05:56,135 - WARNING - Skipping BIOMD0000000858.xml - no results generated
2025-12-07 14:05:56,154 - WARNING - Skipping BIOMD0000000859.xml - no results generated
2025-12-07 14:05:56,159 - WARNING - Species 'miR': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:56,160 - WARNING - Species 'TF1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:05:56,160 - WARNING - Skipping BIOMD0000000860.xml - no results generated
2025-12-07 14:05:56,182 - WARNING - Species 'p12EpoRpJAK2': Found bqmodel qualifier instead of bqbiol - incorrect usage

Evaluating 855/1075: BIOMD0000000857.xml
Evaluating 856/1075: BIOMD0000000858.xml
Evaluating 857/1075: BIOMD0000000859.xml
Evaluating 858/1075: BIOMD0000000860.xml
Evaluating 859/1075: BIOMD0000000861.xml

2025-12-07 14:05:59,642 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:05:59,709 - WARNING - Skipping BIOMD0000000862.xml - no results generated
2025-12-07 14:05:59,721 - WARNING - Skipping BIOMD0000000863.xml - no results generated
2025-12-07 14:05:59,725 - WARNING - Skipping BIOMD0000000864.xml - no results generated
2025-12-07 14:05:59,734 - WARNING - Skipping BIOMD0000000865.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000861.txt
Evaluating 860/1075: BIOMD0000000862.xml
Evaluating 861/1075: BIOMD0000000863.xml
Evaluating 862/1075: BIOMD0000000864.xml
Evaluating 863/1075: BIOMD0000000865.xml
Evaluating 864/1075: BIOMD0000000866.xml

2025-12-07 14:06:01,478 - WARNING - Skipping BIOMD0000000867.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000866.txt
Evaluating 865/1075: BIOMD0000000867.xml
Evaluating 866/1075: BIOMD0000000868.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000868.txt
Evaluating 867/1075: BIOMD0000000869.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000869.txt
Evaluating 868/1075: BIOMD0000000870.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000870.txt
Evaluating 869/1075: BIOMD0000000871.xml

2025-12-07 14:06:11,842 - WARNING - Species 's2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,843 - WARNING - Species 's4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,843 - WARNING - Species 's14': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,843 - WARNING - Species 's16': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,844 - WARNING - Species 's13': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,844 - WARNING - Species 's12': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,845 - WARNING - Skipping BIOMD0000000872.xml - no results generated
2025-12-07 14:06:11,864 - WARNING - Species 'mw5b252d78_9ab9_438c_8b81_2189b1f76357': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,865 - WARNING - Species 'mw869055b5_5d27_4f4a_a390_b3fa48d6780e': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,866 - WARNING - Species 'mw6f8ce639_1c28_444f_b6e6_30ff06ab0d6e': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,866 - WARNING - Species 'mwb9a40fab_a7c9_4984_805f_045fefc4ff32': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:11,867 - WARNING - Species 'mw4fc13b75_10cc_41fb_b9f8_1ce95fccae73': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000871.txt
Evaluating 870/1075: BIOMD0000000872.xml
Evaluating 871/1075: BIOMD0000000873.xml

2025-12-07 14:06:25,706 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000873.txt
Evaluating 872/1075: BIOMD0000000874.xml

2025-12-07 14:06:28,111 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:28,112 - WARNING - Skipping BIOMD0000000875.xml - no results generated
2025-12-07 14:06:28,123 - WARNING - Skipping BIOMD0000000876.xml - no results generated
2025-12-07 14:06:28,132 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:28,133 - WARNING - Skipping BIOMD0000000877.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000874.txt
Evaluating 873/1075: BIOMD0000000875.xml
Evaluating 874/1075: BIOMD0000000876.xml
Evaluating 875/1075: BIOMD0000000877.xml
Evaluating 876/1075: BIOMD0000000878.xml

2025-12-07 14:06:29,447 - WARNING - Skipping BIOMD0000000879.xml - no results generated
2025-12-07 14:06:29,455 - WARNING - Skipping BIOMD0000000880.xml - no results generated
2025-12-07 14:06:29,462 - WARNING - Skipping BIOMD0000000881.xml - no results generated
2025-12-07 14:06:29,467 - WARNING - Species 'Susceptible': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:29,467 - WARNING - Species 'Removal': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:29,468 - WARNING - Skipping BIOMD0000000882.xml - no results generated
2025-12-07 14:06:29,518 - WARNING - Species 'mTORC2Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:29,519 - WARNING - Species 'mTORC1Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:29,519 - WARNING - Species 'mTORC1Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:29,526 - WARNING - Species 'mTORC2Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000878.txt
Evaluating 877/1075: BIOMD0000000879.xml
Evaluating 878/1075: BIOMD0000000880.xml
Evaluating 879/1075: BIOMD0000000881.xml
Evaluating 880/1075: BIOMD0000000882.xml
Evaluating 881/1075: BIOMD0000000883.xml

2025-12-07 14:06:57,889 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:06:57,939 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,939 - WARNING - Species 'V': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,940 - WARNING - Skipping BIOMD0000000884.xml - no results generated
2025-12-07 14:06:57,945 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,945 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,946 - WARNING - Skipping BIOMD0000000885.xml - no results generated
2025-12-07 14:06:57,954 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,954 - WARNING - Species 'Th': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,955 - WARNING - Species 'B': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,955 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,956 - WARNING - Skipping BIOMD0000000886.xml - no results generated
2025-12-07 14:06:57,962 - WARNING - Skipping BIOMD0000000887.xml - no results generated
2025-12-07 14:06:57,976 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,977 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,977 - WARNING - Species 'D': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,977 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:57,978 - WARNING - Skipping BIOMD0000000888.xml - no results generated
2025-12-07 14:06:57,994 - WARNING - Skipping BIOMD0000000889.xml - no results generated
2025-12-07 14:06:58,000 - WARNING - Skipping BIOMD0000000890.xml - no results generated
2025-12-07 14:06:58,006 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,006 - WARNING - Species 'v': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,007 - WARNING - Species 'w': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,007 - WARNING - Skipping BIOMD0000000891.xml - no results generated
2025-12-07 14:06:58,013 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,014 - WARNING - Skipping BIOMD0000000892.xml - no results generated
2025-12-07 14:06:58,019 - WARNING - Skipping BIOMD0000000893.xml - no results generated
2025-12-07 14:06:58,025 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,025 - WARNING - Species 'y': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,025 - WARNING - Species 'z': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,026 - WARNING - Skipping BIOMD0000000894.xml - no results generated
2025-12-07 14:06:58,045 - WARNING - Skipping BIOMD0000000895.xml - no results generated
2025-12-07 14:06:58,058 - WARNING - Species 'HSF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,060 - WARNING - Skipping BIOMD0000000896.xml - no results generated
2025-12-07 14:06:58,065 - WARNING - Skipping BIOMD0000000897.xml - no results generated
2025-12-07 14:06:58,075 - WARNING - Skipping BIOMD0000000898.xml - no results generated
2025-12-07 14:06:58,125 - WARNING - Skipping BIOMD0000000899.xml - no results generated
2025-12-07 14:06:58,130 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,131 - WARNING - Skipping BIOMD0000000900.xml - no results generated
2025-12-07 14:06:58,135 - WARNING - Skipping BIOMD0000000901.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000883.txt
Evaluating 882/1075: BIOMD0000000884.xml
Evaluating 883/1075: BIOMD0000000885.xml
Evaluating 884/1075: BIOMD0000000886.xml
Evaluating 885/1075: BIOMD0000000887.xml
Evaluating 886/1075: BIOMD0000000888.xml
Evaluating 887/1075: BIOMD0000000889.xml
Evaluating 888/1075: BIOMD0000000890.xml
Evaluating 889/1075: BIOMD0000000891.xml
Evaluating 890/1075: BIOMD0000000892.xml
Evaluating 891/1075: BIOMD0000000893.xml
Evaluating 892/1075: BIOMD0000000894.xml
Evaluating 893/1075: BIOMD0000000895.xml
Evaluating 894/1075: BIOMD0000000896.xml
Evaluating 895/1075: BIOMD0000000897.xml
Evaluating 896/1075: BIOMD0000000898.xml
Evaluating 897/1075: BIOMD0000000899.xml
Evaluating 898/1075: BIOMD0000000900.xml
Evaluating 899/1075: BIOMD0000000901.xml
Evaluating 900/1075: BIOMD0000000902.xml

2025-12-07 14:06:58,140 - WARNING - Skipping BIOMD0000000902.xml - no results generated
2025-12-07 14:06:58,147 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,147 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,148 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,148 - WARNING - Skipping BIOMD0000000903.xml - no results generated
2025-12-07 14:06:58,154 - WARNING - Species 'Ti': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,155 - WARNING - Species 'Tm': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,155 - WARNING - Skipping BIOMD0000000904.xml - no results generated
2025-12-07 14:06:58,162 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,163 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,164 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,164 - WARNING - Skipping BIOMD0000000905.xml - no results generated
2025-12-07 14:06:58,169 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,169 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,170 - WARNING - Skipping BIOMD0000000906.xml - no results generated
2025-12-07 14:06:58,187 - WARNING - Skipping BIOMD0000000907.xml - no results generated
2025-12-07 14:06:58,197 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,197 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,198 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,198 - WARNING - Species 'R': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,198 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,198 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,199 - WARNING - Species 'S': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,199 - WARNING - Skipping BIOMD0000000908.xml - no results generated
2025-12-07 14:06:58,206 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,206 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,206 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,207 - WARNING - Skipping BIOMD0000000909.xml - no results generated
2025-12-07 14:06:58,212 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:06:58,213 - WARNING - Species 'I2': Found bqmodel qualifier instead of bqbiol - incorrect usage

Evaluating 901/1075: BIOMD0000000903.xml
Evaluating 902/1075: BIOMD0000000904.xml
Evaluating 903/1075: BIOMD0000000905.xml
Evaluating 904/1075: BIOMD0000000906.xml
Evaluating 905/1075: BIOMD0000000907.xml
Evaluating 906/1075: BIOMD0000000908.xml
Evaluating 907/1075: BIOMD0000000909.xml
Evaluating 908/1075: BIOMD0000000910.xml

2025-12-07 14:06:59,292 - WARNING - Skipping BIOMD0000000911.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000910.txt
Evaluating 909/1075: BIOMD0000000911.xml
Evaluating 910/1075: BIOMD0000000912.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000912.txt
Evaluating 911/1075: BIOMD0000000913.xml

2025-12-07 14:07:02,594 - WARNING - Species 'SVAC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:07:02,595 - WARNING - Skipping BIOMD0000000914.xml - no results generated
2025-12-07 14:07:02,610 - WARNING - Skipping BIOMD0000000915.xml - no results generated
2025-12-07 14:07:02,619 - WARNING - Skipping BIOMD0000000916.xml - no results generated
2025-12-07 14:07:02,630 - WARNING - Skipping BIOMD0000000917.xml - no results generated
2025-12-07 14:07:02,642 - WARNING - Skipping BIOMD0000000918.xml - no results generated
2025-12-07 14:07:02,648 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:07:02,649 - WARNING - Skipping BIOMD0000000919.xml - no results generated
2025-12-07 14:07:02,659 - WARNING - Skipping BIOMD0000000920.xml - no results generated
2025-12-07 14:07:02,668 - WARNING - Species 'G': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:07:02,669 - WARNING - Species 'M': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:07:02,669 - WARNING - Species 'C_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:07:02,669 - WARNING - Species 'T_beta': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:07:02,670 - WARNING - Species 'I_gamma': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:07:02,670 - WARNING - Skipping BIOMD0000000921.xml - no results generated
2025-12-07 14:07:02,675 - WARNING - Skipping BIOMD0000000922.xml - no results generated
2025-12-07 14:07:02,682 - WARNING - Skipping BIOMD0000000923.xml - no results generated
2025-12-07 14:07:02,693 - WARNING - Skipping BIOMD0000000924.xml - no results generated
2025-12-07 14:07:02,755 - WARNING - Skipping BIOMD0000000925.xml - no results generated
2025-12-07 14:07:02,777 - WARNING - Skipping BIOMD0000000926.xml - no results generated
2025-12-07 14:07:02,782 - WARNING - Skipping BIOMD0000000927.xml - no results generated
2025-12-07 14:07:02,795 - WARNING - Skipping BIOMD0000000928.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000913.txt
Evaluating 912/1075: BIOMD0000000914.xml
Evaluating 913/1075: BIOMD0000000915.xml
Evaluating 914/1075: BIOMD0000000916.xml
Evaluating 915/1075: BIOMD0000000917.xml
Evaluating 916/1075: BIOMD0000000918.xml
Evaluating 917/1075: BIOMD0000000919.xml
Evaluating 918/1075: BIOMD0000000920.xml
Evaluating 919/1075: BIOMD0000000921.xml
Evaluating 920/1075: BIOMD0000000922.xml
Evaluating 921/1075: BIOMD0000000923.xml
Evaluating 922/1075: BIOMD0000000924.xml
Evaluating 923/1075: BIOMD0000000925.xml
Evaluating 924/1075: BIOMD0000000926.xml
Evaluating 925/1075: BIOMD0000000927.xml
Evaluating 926/1075: BIOMD0000000928.xml

2025-12-07 14:07:02,818 - WARNING - Skipping BIOMD0000000929.xml - no results generated
2025-12-07 14:07:02,827 - WARNING - Skipping BIOMD0000000930.xml - no results generated
2025-12-07 14:07:02,833 - WARNING - Skipping BIOMD0000000931.xml - no results generated
2025-12-07 14:07:02,839 - WARNING - Skipping BIOMD0000000932.xml - no results generated
2025-12-07 14:07:02,845 - WARNING - Skipping BIOMD0000000933.xml - no results generated
2025-12-07 14:07:02,862 - WARNING - Skipping BIOMD0000000934.xml - no results generated
2025-12-07 14:07:02,867 - WARNING - Skipping BIOMD0000000935.xml - no results generated
2025-12-07 14:07:02,871 - WARNING - Skipping BIOMD0000000936.xml - no results generated
2025-12-07 14:07:02,877 - WARNING - Skipping BIOMD0000000937.xml - no results generated
2025-12-07 14:07:02,885 - WARNING - Skipping BIOMD0000000938.xml - no results generated

Evaluating 927/1075: BIOMD0000000929.xml
Evaluating 928/1075: BIOMD0000000930.xml
Evaluating 929/1075: BIOMD0000000931.xml
Evaluating 930/1075: BIOMD0000000932.xml
Evaluating 931/1075: BIOMD0000000933.xml
Evaluating 932/1075: BIOMD0000000934.xml
Evaluating 933/1075: BIOMD0000000935.xml
Evaluating 934/1075: BIOMD0000000936.xml
Evaluating 935/1075: BIOMD0000000937.xml
Evaluating 936/1075: BIOMD0000000938.xml
Evaluating 937/1075: BIOMD0000000939.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000939.txt
Evaluating 938/1075: BIOMD0000000940.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000940.txt
Evaluating 939/1075: BIOMD0000000941.xml

2025-12-07 14:07:34,448 - WARNING - Skipping BIOMD0000000942.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000941.txt
Evaluating 940/1075: BIOMD0000000942.xml
Evaluating 941/1075: BIOMD0000000943.xml

2025-12-07 14:07:53,654 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:07:53,745 - WARNING - Skipping BIOMD0000000944.xml - no results generated
2025-12-07 14:07:53,752 - WARNING - Skipping BIOMD0000000945.xml - no results generated
2025-12-07 14:07:53,760 - WARNING - Skipping BIOMD0000000946.xml - no results generated
2025-12-07 14:07:53,768 - WARNING - Skipping BIOMD0000000947.xml - no results generated
2025-12-07 14:07:53,773 - WARNING - Skipping BIOMD0000000948.xml - no results generated
2025-12-07 14:07:53,791 - WARNING - Skipping BIOMD0000000949.xml - no results generated
2025-12-07 14:07:53,800 - WARNING - Skipping BIOMD0000000950.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000943.txt
Evaluating 942/1075: BIOMD0000000944.xml
Evaluating 943/1075: BIOMD0000000945.xml
Evaluating 944/1075: BIOMD0000000946.xml
Evaluating 945/1075: BIOMD0000000947.xml
Evaluating 946/1075: BIOMD0000000948.xml
Evaluating 947/1075: BIOMD0000000949.xml
Evaluating 948/1075: BIOMD0000000950.xml
Evaluating 949/1075: BIOMD0000000951.xml

2025-12-07 14:08:02,700 - WARNING - Skipping BIOMD0000000952.xml - no results generated
2025-12-07 14:08:02,719 - WARNING - Skipping BIOMD0000000953.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000951.txt
Evaluating 950/1075: BIOMD0000000952.xml
Evaluating 951/1075: BIOMD0000000953.xml
Evaluating 952/1075: BIOMD0000000954.xml

2025-12-07 14:08:11,691 - WARNING - Skipping BIOMD0000000955.xml - no results generated
2025-12-07 14:08:11,698 - WARNING - Skipping BIOMD0000000956.xml - no results generated
2025-12-07 14:08:11,702 - WARNING - Skipping BIOMD0000000957.xml - no results generated
2025-12-07 14:08:11,712 - WARNING - Skipping BIOMD0000000958.xml - no results generated
2025-12-07 14:08:11,752 - WARNING - Species 'STAT1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,753 - WARNING - Species 'STAT1_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,753 - WARNING - Species 'STAT1_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,753 - WARNING - Species 'STAT2_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,754 - WARNING - Species 'STAT2_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,754 - WARNING - Species 'STAT2_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,754 - WARNING - Species 'STAT2_LC_4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,755 - WARNING - Species 'STAT2_LC_5': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,755 - WARNING - Species 'IRF9_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,755 - WARNING - Species 'IRF9_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,756 - WARNING - Species 'USP18_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,756 - WARNING - Species 'USP18_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:11,756 - WARNING - Species 'SOCS1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000954.txt
Evaluating 953/1075: BIOMD0000000955.xml
Evaluating 954/1075: BIOMD0000000956.xml
Evaluating 955/1075: BIOMD0000000957.xml
Evaluating 956/1075: BIOMD0000000958.xml
Evaluating 957/1075: BIOMD0000000959.xml

2025-12-07 14:08:24,491 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:08:24,605 - WARNING - Skipping BIOMD0000000960.xml - no results generated
2025-12-07 14:08:24,950 - WARNING - Skipping BIOMD0000000961.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000959.txt
Evaluating 958/1075: BIOMD0000000960.xml
Evaluating 959/1075: BIOMD0000000961.xml
Evaluating 960/1075: BIOMD0000000962.xml

2025-12-07 14:08:24,961 - WARNING - Skipping BIOMD0000000962.xml - no results generated
2025-12-07 14:08:24,965 - WARNING - Skipping BIOMD0000000963.xml - no results generated
2025-12-07 14:08:24,976 - WARNING - Skipping BIOMD0000000964.xml - no results generated
2025-12-07 14:08:25,008 - WARNING - Species 'I1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:25,010 - WARNING - Skipping BIOMD0000000965.xml - no results generated
2025-12-07 14:08:25,028 - WARNING - Species 'Py': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:25,029 - WARNING - Species 'Py1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:25,029 - WARNING - Species 'Dw': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:25,029 - WARNING - Species 'Qw1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:25,030 - WARNING - Species 'Qw2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:25,031 - WARNING - Skipping BIOMD0000000966.xml - no results generated
2025-12-07 14:08:25,047 - WARNING - Skipping BIOMD0000000967.xml - no results generated

Evaluating 961/1075: BIOMD0000000963.xml
Evaluating 962/1075: BIOMD0000000964.xml
Evaluating 963/1075: BIOMD0000000965.xml
Evaluating 964/1075: BIOMD0000000966.xml
Evaluating 965/1075: BIOMD0000000967.xml
Evaluating 966/1075: BIOMD0000000968.xml

2025-12-07 14:08:28,757 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:08:28,904 - WARNING - Skipping BIOMD0000000969.xml - no results generated
2025-12-07 14:08:28,909 - WARNING - Skipping BIOMD0000000970.xml - no results generated
2025-12-07 14:08:28,920 - WARNING - Skipping BIOMD0000000971.xml - no results generated
2025-12-07 14:08:28,934 - WARNING - Skipping BIOMD0000000972.xml - no results generated
2025-12-07 14:08:28,939 - WARNING - Skipping BIOMD0000000973.xml - no results generated
2025-12-07 14:08:28,945 - WARNING - Skipping BIOMD0000000974.xml - no results generated
2025-12-07 14:08:28,982 - WARNING - Species 'PCC_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:28,982 - WARNING - Species 'PCN_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:28,983 - WARNING - Species 'PCNP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 14:08:28,983 - WARNING - Species 'PCCP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000968.txt
Evaluating 967/1075: BIOMD0000000969.xml
Evaluating 968/1075: BIOMD0000000970.xml
Evaluating 969/1075: BIOMD0000000971.xml
Evaluating 970/1075: BIOMD0000000972.xml
Evaluating 971/1075: BIOMD0000000973.xml
Evaluating 972/1075: BIOMD0000000974.xml
Evaluating 973/1075: BIOMD0000000975.xml

2025-12-07 14:08:34,479 - WARNING - Skipping BIOMD0000000976.xml - no results generated
2025-12-07 14:08:34,490 - WARNING - Skipping BIOMD0000000977.xml - no results generated
2025-12-07 14:08:34,494 - WARNING - Skipping BIOMD0000000978.xml - no results generated
2025-12-07 14:08:34,500 - WARNING - Skipping BIOMD0000000979.xml - no results generated
2025-12-07 14:08:34,507 - WARNING - Skipping BIOMD0000000980.xml - no results generated
2025-12-07 14:08:34,520 - WARNING - Skipping BIOMD0000000981.xml - no results generated
2025-12-07 14:08:34,526 - WARNING - Skipping BIOMD0000000982.xml - no results generated
2025-12-07 14:08:34,539 - WARNING - Skipping BIOMD0000000983.xml - no results generated
2025-12-07 14:08:34,544 - WARNING - Skipping BIOMD0000000984.xml - no results generated
2025-12-07 14:08:34,554 - WARNING - Skipping BIOMD0000000985.xml - no results generated
2025-12-07 14:08:34,562 - WARNING - Skipping BIOMD0000000986.xml - no results generated
2025-12-07 14:08:34,571 - WARNING - Skipping BIOMD0000000987.xml - no results generated
2025-12-07 14:08:34,614 - WARNING - Skipping BIOMD0000000988.xml - no results generated
2025-12-07 14:08:34,653 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000975.txt
Evaluating 974/1075: BIOMD0000000976.xml
Evaluating 975/1075: BIOMD0000000977.xml
Evaluating 976/1075: BIOMD0000000978.xml
Evaluating 977/1075: BIOMD0000000979.xml
Evaluating 978/1075: BIOMD0000000980.xml
Evaluating 979/1075: BIOMD0000000981.xml
Evaluating 980/1075: BIOMD0000000982.xml
Evaluating 981/1075: BIOMD0000000983.xml
Evaluating 982/1075: BIOMD0000000984.xml
Evaluating 983/1075: BIOMD0000000985.xml
Evaluating 984/1075: BIOMD0000000986.xml
Evaluating 985/1075: BIOMD0000000987.xml
Evaluating 986/1075: BIOMD0000000988.xml
Evaluating 987/1075: BIOMD0000000989.xml

2025-12-07 14:08:45,689 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:08:45,831 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000989.txt
Evaluating 988/1075: BIOMD0000000990.xml

2025-12-07 14:08:55,928 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:08:56,046 - WARNING - Skipping BIOMD0000000991.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000990.txt
Evaluating 989/1075: BIOMD0000000991.xml
Evaluating 990/1075: BIOMD0000000994.xml

2025-12-07 14:09:06,825 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000994.txt
Evaluating 991/1075: BIOMD0000000995.xml

2025-12-07 14:09:18,972 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000995.txt
Evaluating 992/1075: BIOMD0000000996.xml

2025-12-07 14:09:29,344 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000996.txt
Evaluating 993/1075: BIOMD0000000997.xml

2025-12-07 14:09:40,441 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000997.txt
Evaluating 994/1075: BIOMD0000000998.xml

2025-12-07 14:09:50,422 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000998.txt
Evaluating 995/1075: BIOMD0000000999.xml

2025-12-07 14:10:02,027 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000000999.txt
Evaluating 996/1075: BIOMD0000001000.xml

2025-12-07 14:10:12,688 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001000.txt
Evaluating 997/1075: BIOMD0000001001.xml

2025-12-07 14:10:23,575 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001001.txt
Evaluating 998/1075: BIOMD0000001002.xml

2025-12-07 14:10:34,771 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001002.txt
Evaluating 999/1075: BIOMD0000001003.xml

2025-12-07 14:10:45,363 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:10:45,475 - WARNING - Skipping BIOMD0000001004.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001003.txt
Evaluating 1000/1075: BIOMD0000001004.xml
Evaluating 1001/1075: BIOMD0000001005.xml

2025-12-07 14:10:56,275 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001005.txt
Evaluating 1002/1075: BIOMD0000001006.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001006.txt
Evaluating 1003/1075: BIOMD0000001007.xml

2025-12-07 14:11:01,646 - WARNING - Skipping BIOMD0000001008.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001007.txt
Evaluating 1004/1075: BIOMD0000001008.xml
Evaluating 1005/1075: BIOMD0000001009.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001009.txt
Evaluating 1006/1075: BIOMD0000001010.xml

2025-12-07 14:11:05,816 - WARNING - Skipping BIOMD0000001011.xml - no results generated
2025-12-07 14:11:05,823 - WARNING - Skipping BIOMD0000001012.xml - no results generated
2025-12-07 14:11:05,829 - WARNING - Skipping BIOMD0000001013.xml - no results generated
2025-12-07 14:11:05,837 - WARNING - Skipping BIOMD0000001014.xml - no results generated
2025-12-07 14:11:05,847 - WARNING - Skipping BIOMD0000001015.xml - no results generated
2025-12-07 14:11:05,856 - WARNING - Skipping BIOMD0000001016.xml - no results generated
2025-12-07 14:11:05,868 - WARNING - Skipping BIOMD0000001017.xml - no results generated
2025-12-07 14:11:05,887 - WARNING - Skipping BIOMD0000001018.xml - no results generated
2025-12-07 14:11:05,893 - WARNING - Skipping BIOMD0000001019.xml - no results generated
2025-12-07 14:11:05,899 - WARNING - Skipping BIOMD0000001020.xml - no results generated
2025-12-07 14:11:05,909 - WARNING - Skipping BIOMD0000001021.xml - no results generated
2025-12-07 14:11:05,915 - WARNING - Skipping BIOMD0000001022.xml - no results generated
2025-12-07 14:11:05,922 - WARNING - Skipping BIOMD0000001023.xml - no results generated
2025-12-07 14:11:05,927 - WARNING - Skipping BIOMD0000001024.xml - no results generated
2025-12-07 14:11:05,933 - WARNING - Skipping BIOMD0000001025.xml - no results generated
2025-12-07 14:11:05,939 - WARNING - Skipping BIOMD0000001026.xml - no results generated
2025-12-07 14:11:05,974 - WARNING - Skipping BIOMD0000001027.xml - no results generated
2025-12-07 14:11:06,005 - WARNING - Skipping BIOMD0000001028.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001010.txt
Evaluating 1007/1075: BIOMD0000001011.xml
Evaluating 1008/1075: BIOMD0000001012.xml
Evaluating 1009/1075: BIOMD0000001013.xml
Evaluating 1010/1075: BIOMD0000001014.xml
Evaluating 1011/1075: BIOMD0000001015.xml
Evaluating 1012/1075: BIOMD0000001016.xml
Evaluating 1013/1075: BIOMD0000001017.xml
Evaluating 1014/1075: BIOMD0000001018.xml
Evaluating 1015/1075: BIOMD0000001019.xml
Evaluating 1016/1075: BIOMD0000001020.xml
Evaluating 1017/1075: BIOMD0000001021.xml
Evaluating 1018/1075: BIOMD0000001022.xml
Evaluating 1019/1075: BIOMD0000001023.xml
Evaluating 1020/1075: BIOMD0000001024.xml
Evaluating 1021/1075: BIOMD0000001025.xml
Evaluating 1022/1075: BIOMD0000001026.xml
Evaluating 1023/1075: BIOMD0000001027.xml
Evaluating 1024/1075: BIOMD0000001028.xml
Evaluating 1025/1075: BIOMD0000001029.xml

2025-12-07 14:11:06,035 - WARNING - Skipping BIOMD0000001029.xml - no results generated
2025-12-07 14:11:06,041 - WARNING - Skipping BIOMD0000001030.xml - no results generated
2025-12-07 14:11:06,047 - WARNING - Skipping BIOMD0000001031.xml - no results generated
2025-12-07 14:11:06,054 - WARNING - Skipping BIOMD0000001032.xml - no results generated
2025-12-07 14:11:06,065 - WARNING - Skipping BIOMD0000001033.xml - no results generated
2025-12-07 14:11:06,072 - WARNING - Skipping BIOMD0000001034.xml - no results generated
2025-12-07 14:11:06,080 - WARNING - Skipping BIOMD0000001035.xml - no results generated
2025-12-07 14:11:06,086 - WARNING - Skipping BIOMD0000001036.xml - no results generated
2025-12-07 14:11:06,091 - WARNING - Skipping BIOMD0000001037.xml - no results generated
2025-12-07 14:11:06,097 - WARNING - Skipping BIOMD0000001038.xml - no results generated
2025-12-07 14:11:06,126 - WARNING - Skipping BIOMD0000001039.xml - no results generated
2025-12-07 14:11:06,131 - WARNING - Skipping BIOMD0000001040.xml - no results generated
2025-12-07 14:11:06,137 - WARNING - Skipping BIOMD0000001041.xml - no results generated
2025-12-07 14:11:06,147 - WARNING - Skipping BIOMD0000001042.xml - no results generated
2025-12-07 14:11:06,154 - WARNING - Skipping BIOMD0000001043.xml - no results generated

Evaluating 1026/1075: BIOMD0000001030.xml
Evaluating 1027/1075: BIOMD0000001031.xml
Evaluating 1028/1075: BIOMD0000001032.xml
Evaluating 1029/1075: BIOMD0000001033.xml
Evaluating 1030/1075: BIOMD0000001034.xml
Evaluating 1031/1075: BIOMD0000001035.xml
Evaluating 1032/1075: BIOMD0000001036.xml
Evaluating 1033/1075: BIOMD0000001037.xml
Evaluating 1034/1075: BIOMD0000001038.xml
Evaluating 1035/1075: BIOMD0000001039.xml
Evaluating 1036/1075: BIOMD0000001040.xml
Evaluating 1037/1075: BIOMD0000001041.xml
Evaluating 1038/1075: BIOMD0000001042.xml
Evaluating 1039/1075: BIOMD0000001043.xml
Evaluating 1040/1075: BIOMD0000001044.xml

2025-12-07 14:11:15,285 - WARNING - Skipping BIOMD0000001045.xml - no results generated
2025-12-07 14:11:15,401 - WARNING - Skipping BIOMD0000001046.xml - no results generated
2025-12-07 14:11:15,410 - WARNING - Skipping BIOMD0000001047.xml - no results generated
2025-12-07 14:11:15,417 - WARNING - Skipping BIOMD0000001048.xml - no results generated
2025-12-07 14:11:15,428 - WARNING - Skipping BIOMD0000001052.xml - no results generated
2025-12-07 14:11:15,437 - WARNING - Skipping BIOMD0000001053.xml - no results generated
2025-12-07 14:11:15,446 - WARNING - Skipping BIOMD0000001054.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001044.txt
Evaluating 1041/1075: BIOMD0000001045.xml
Evaluating 1042/1075: BIOMD0000001046.xml
Evaluating 1043/1075: BIOMD0000001047.xml
Evaluating 1044/1075: BIOMD0000001048.xml
Evaluating 1045/1075: BIOMD0000001052.xml
Evaluating 1046/1075: BIOMD0000001053.xml
Evaluating 1047/1075: BIOMD0000001054.xml
Evaluating 1048/1075: BIOMD0000001055.xml

2025-12-07 14:11:22,057 - WARNING - Skipping BIOMD0000001056.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001055.txt
Evaluating 1049/1075: BIOMD0000001056.xml
Evaluating 1050/1075: BIOMD0000001057.xml

2025-12-07 14:11:23,522 - WARNING - Skipping BIOMD0000001058.xml - no results generated
2025-12-07 14:11:23,536 - WARNING - Skipping BIOMD0000001059.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001057.txt
Evaluating 1051/1075: BIOMD0000001058.xml
Evaluating 1052/1075: BIOMD0000001059.xml
Evaluating 1053/1075: BIOMD0000001060.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001060.txt
Evaluating 1054/1075: BIOMD0000001061.xml

2025-12-07 14:11:26,093 - WARNING - Skipping BIOMD0000001061.xml - no results generated
2025-12-07 14:11:28,528 - WARNING - Skipping BIOMD0000001062.xml - no results generated

Evaluating 1055/1075: BIOMD0000001062.xml
Evaluating 1056/1075: BIOMD0000001063.xml

2025-12-07 14:11:30,606 - WARNING - Skipping BIOMD0000001063.xml - no results generated
2025-12-07 14:11:30,745 - WARNING - Skipping BIOMD0000001064.xml - no results generated
2025-12-07 14:11:30,833 - WARNING - Skipping BIOMD0000001065.xml - no results generated
2025-12-07 14:11:30,844 - WARNING - Skipping BIOMD0000001072.xml - no results generated

Evaluating 1057/1075: BIOMD0000001064.xml
Evaluating 1058/1075: BIOMD0000001065.xml
Evaluating 1059/1075: BIOMD0000001072.xml
Evaluating 1060/1075: BIOMD0000001077.xml

2025-12-07 14:11:36,135 - WARNING - No valid database found for entity type 'chemical' in allowed databases: ['uniprot']
2025-12-07 14:11:36,154 - WARNING - Skipping BIOMD0000001078.xml - no results generated
2025-12-07 14:11:36,158 - WARNING - Skipping BIOMD0000001079.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001077.txt
Evaluating 1061/1075: BIOMD0000001078.xml
Evaluating 1062/1075: BIOMD0000001079.xml
Evaluating 1063/1075: BIOMD0000001080.xml

2025-12-07 14:11:37,960 - WARNING - Skipping BIOMD0000001090.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251207_1330/BIOMD0000001080.txt
Evaluating 1064/1075: BIOMD0000001090.xml
Evaluating 1065/1075: BIOMD0000001091.xml

2025-12-07 14:11:39,087 - WARNING - Skipping BIOMD0000001091.xml - no results generated
2025-12-07 14:11:39,692 - WARNING - Skipping BIOMD0000001092.xml - no results generated

Evaluating 1066/1075: BIOMD0000001092.xml
Evaluating 1067/1075: BIOMD0000001093.xml

2025-12-07 14:11:42,566 - WARNING - Skipping BIOMD0000001093.xml - no results generated
2025-12-07 14:11:43,113 - WARNING - Skipping BIOMD0000001094.xml - no results generated

Evaluating 1068/1075: BIOMD0000001094.xml
Evaluating 1069/1075: BIOMD0000001095.xml

2025-12-07 14:11:43,350 - WARNING - Skipping BIOMD0000001095.xml - no results generated
2025-12-07 14:11:43,695 - WARNING - Skipping BIOMD0000001096.xml - no results generated
2025-12-07 14:11:43,903 - WARNING - Skipping BIOMD0000001097.xml - no results generated

Evaluating 1070/1075: BIOMD0000001096.xml
Evaluating 1071/1075: BIOMD0000001097.xml

2025-12-07 14:11:44,044 - WARNING - Skipping BIOMD0000001098.xml - no results generated
2025-12-07 14:11:44,215 - WARNING - Skipping BIOMD0000001099.xml - no results generated
2025-12-07 14:11:44,223 - WARNING - Skipping BIOMD0000001102.xml - no results generated
2025-12-07 14:11:44,231 - WARNING - Skipping BIOMD0000001103.xml - no results generated

Evaluating 1072/1075: BIOMD0000001098.xml
Evaluating 1073/1075: BIOMD0000001099.xml
Evaluating 1074/1075: BIOMD0000001102.xml
Evaluating 1075/1075: BIOMD0000001103.xml

In [6]:
print_evaluation_results("autoType/biomd251106_uniprot_direct_llama-4_top3_autoType_complex_improved.csv", ref_results_csv=None, entity_types=['complex'])

Showing all results
Filtering results by entity types: ['complex']
Number of models assessed: 204
Number of models with predictions: 174
Number of annotations evaluated: 2117
Average accuracy (per model): 0.61
Ave. recall (formula): 0.46
Ave. precision (formula): 0.50
Ave. recall (exact): 0.46
Ave. precision (exact): 0.50
Average accuracy (per species): 0.57
Ave. recall (formula, per species): 0.40
Ave. precision (formula, per species): 0.45
Ave. recall (exact, per species): 0.40
Ave. precision (exact, per species): 0.45
Ave. total time (per model): 10.20
Ave. total time (per element, per model): 0.98
Ave. LLM time (per model): 10.00
Ave. LLM time (per element, per model): 0.96
Average number of predictions per species: 1.38

In [7]:
print_evaluation_results("autoType/biomd251106_uniprot_direct_llama-4_top3_autoType_complex_improved.csv", ref_results_csv=None, entity_types=['protein'])

Showing all results
Filtering results by entity types: ['protein']
Number of models assessed: 277
Number of models with predictions: 259
Number of annotations evaluated: 2628
Average accuracy (per model): 0.62
Ave. recall (formula): 0.60
Ave. precision (formula): 0.58
Ave. recall (exact): 0.60
Ave. precision (exact): 0.58
Average accuracy (per species): 0.59
Ave. recall (formula, per species): 0.57
Ave. precision (formula, per species): 0.55
Ave. recall (exact, per species): 0.57
Ave. precision (exact, per species): 0.55
Ave. total time (per model): 8.27
Ave. total time (per element, per model): 0.87
Ave. LLM time (per model): 8.11
Ave. LLM time (per element, per model): 0.85
Average number of predictions per species: 0.81

In [12]:
print_evaluation_results("autoType/biomd251106_uniprot_direct_llama-4_top3_autoType_complex_improved.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 272
Number of models with predictions: 235
Number of annotations evaluated: 2810
Average accuracy (per model): 0.52
Ave. recall (formula): 0.51
Ave. precision (formula): 0.48
Ave. recall (exact): 0.51
Ave. precision (exact): 0.48
Average accuracy (per species): 0.51
Ave. recall (formula, per species): 0.51
Ave. precision (formula, per species): 0.48
Ave. recall (exact, per species): 0.51
Ave. precision (exact, per species): 0.48
Ave. total time (per model): 8.15
Ave. total time (per element, per model): 0.79
Ave. LLM time (per model): 7.99
Ave. LLM time (per element, per model): 0.77
Average number of predictions per species: 0.72

In [13]:
print_evaluation_results("autoType/biomd251106_uniprot_direct_llama-4_top3_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 472
Number of models with predictions: 352
Number of annotations evaluated: 7825
Average accuracy (per model): 0.07
Ave. recall (formula): 0.00
Ave. precision (formula): 0.00
Ave. recall (exact): 0.07
Ave. precision (exact): 0.06
Average accuracy (per species): 0.03
Ave. recall (formula, per species): 0.00
Ave. precision (formula, per species): 0.00
Ave. recall (exact, per species): 0.03
Ave. precision (exact, per species): 0.02
Ave. total time (per model): 11.71
Ave. total time (per element, per model): 0.71
Ave. LLM time (per model): 11.51
Ave. LLM time (per element, per model): 0.69
Average number of predictions per species: 0.32

In [19]:
model_dir = '/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioDivine/'

# Check if model directory exists
if os.path.exists(model_dir):
    model_files = [f for f in os.listdir(model_dir) if f.endswith('.sbml')]
    print(f"✓ Model directory found: {model_dir}")
    print(f"  - Found {len(model_files)} SBML files")

✓ Model directory found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioDivine/
  - Found 190 SBML files

In [ ]:
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    top_k=3,
    entity_type='auto',
    database='uniprot',
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biodivine_uniprot_direct_llama-3_top5_9606_autoType.csv",
    start_at=1,
    tax_id = 9606
)

In [22]:
print_evaluation_results("autoType/biodivine_uniprot_direct_llama-3_top5_9606_autoType.csv", ref_results_csv=None)

Showing all results
Number of models assessed: 15
Number of models with predictions: 8
Number of annotations evaluated: 605
Average accuracy (per model): 0.00
Ave. recall (formula): 0.00
Ave. precision (formula): 0.00
Ave. recall (exact): 0.00
Ave. precision (exact): 0.00
Average accuracy (per species): 0.00
Ave. recall (formula, per species): 0.00
Ave. precision (formula, per species): 0.00
Ave. recall (exact, per species): 0.00
Ave. precision (exact, per species): 0.00
Ave. total time (per model): 14.54
Ave. total time (per element, per model): 0.36
Ave. LLM time (per model): 14.34
Ave. LLM time (per element, per model): 0.36
Average number of predictions per species: 0.08

## chebi + uniprot

In [ ]:
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database=['chebi', 'uniprot'],
    method="direct",
    top_k = 3,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv",
    start_at=1,
    tax_id = 9606
)

In [2]:
from utils.evaluation import recalculate_statistics
df = recalculate_statistics("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv", "autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType_recal.csv")

Reading results from: autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv
Recalculated statistics saved to: autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType_recal.csv
Processed 17510 rows

Summary statistics (recalculated):
  Average accuracy: 0.685
  Average recall (formula): 0.673
  Average precision (formula): 0.628
  Average recall (exact): 0.460
  Average precision (exact): 0.450

In [13]:
print_evaluation_results("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv", ref_results_csv=None, entity_types=['chemical'])

Showing all results
Filtering results by entity types: ['chemical']
Number of models assessed: 404
Number of models with predictions: 341
Number of annotations evaluated: 11613
Average accuracy (per model): 0.64
Ave. recall (formula): 0.64
Ave. precision (formula): 0.58
Ave. recall (exact): 0.55
Ave. precision (exact): 0.30
Average accuracy (per species): 0.86
Ave. recall (formula, per species): 0.86
Ave. precision (formula, per species): 0.80
Ave. recall (exact, per species): 0.53
Ave. precision (exact, per species): 0.53
Ave. total time (per model): 18.65
Ave. total time (per element, per model): 0.65
Ave. LLM time (per model): 17.26
Ave. LLM time (per element, per model): 0.60
Average number of predictions per species: 1.82

In [14]:
print_evaluation_results("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv", ref_results_csv=None, entity_types=['protein'])

Showing all results
Filtering results by entity types: ['protein']
Number of models assessed: 313
Number of models with predictions: 282
Number of annotations evaluated: 2714
Average accuracy (per model): 0.57
Ave. recall (formula): 0.00
Ave. precision (formula): 0.00
Ave. recall (exact): 0.55
Ave. precision (exact): 0.53
Average accuracy (per species): 0.59
Ave. recall (formula, per species): 0.00
Ave. precision (formula, per species): 0.00
Ave. recall (exact, per species): 0.57
Ave. precision (exact, per species): 0.54
Ave. total time (per model): 22.96
Ave. total time (per element, per model): 2.65
Ave. LLM time (per model): 21.37
Ave. LLM time (per element, per model): 2.46
Average number of predictions per species: 0.86

In [15]:
print_evaluation_results("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv", ref_results_csv=None, entity_types=['complex'])

Showing all results
Filtering results by entity types: ['complex']
Number of models assessed: 265
Number of models with predictions: 153
Number of annotations evaluated: 2855
Average accuracy (per model): 0.12
Ave. recall (formula): 0.13
Ave. precision (formula): 0.12
Ave. recall (exact): 0.10
Ave. precision (exact): 0.07
Average accuracy (per species): 0.14
Ave. recall (formula, per species): 0.14
Ave. precision (formula, per species): 0.15
Ave. recall (exact, per species): 0.10
Ave. precision (exact, per species): 0.09
Ave. total time (per model): 26.40
Ave. total time (per element, per model): 2.45
Ave. LLM time (per model): 24.54
Ave. LLM time (per element, per model): 2.28
Average number of predictions per species: 0.89

In [4]:
print_evaluation_results("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv", ref_results_csv=None)

Showing all results
Number of models assessed: 552
Number of models with predictions: 521
Number of annotations evaluated: 17510
Average accuracy (per model): 0.57
Ave. recall (formula): 0.38
Ave. precision (formula): 0.35
Ave. recall (exact): 0.51
Ave. precision (exact): 0.36
Average accuracy (per species): 0.69
Ave. recall (formula, per species): 0.59
Ave. precision (formula, per species): 0.55
Ave. recall (exact, per species): 0.46
Ave. precision (exact, per species): 0.45
Ave. total time (per model): 14.76
Ave. total time (per element, per model): 0.47
Ave. LLM time (per model): 13.68
Ave. LLM time (per element, per model): 0.43
Average number of predictions per species: 1.49

In [4]:
print_evaluation_results("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_autoType_updated.csv", ref_results_csv=None)

Showing all results
Number of models assessed: 683
Number of models with predictions: 635
Number of annotations evaluated: 23765
Average accuracy (per model): 0.30
Ave. recall (formula): 0.26
Ave. precision (formula): 0.24
Ave. recall (exact): 0.26
Ave. precision (exact): 0.15
Average accuracy (per species): 0.44
Ave. recall (formula, per species): 0.42
Ave. precision (formula, per species): 0.40
Ave. recall (exact, per species): 0.28
Ave. precision (exact, per species): 0.28
Ave. total time (per model): 15.61
Ave. total time (per element, per model): 0.45
Ave. LLM time (per model): 14.62
Ave. LLM time (per element, per model): 0.42
Average number of predictions per species: 1.20

In [11]:
print_evaluation_results("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_autoType.csv", ref_results_csv=None)

Showing all results
Number of models assessed: 683
Number of models with predictions: 617
Number of annotations evaluated: 23765
Average accuracy (per model): 0.28
Ave. recall (formula): 0.25
Ave. precision (formula): 0.23
Ave. recall (exact): 0.24
Ave. precision (exact): 0.14
Average accuracy (per species): 0.44
Ave. recall (formula, per species): 0.42
Ave. precision (formula, per species): 0.40
Ave. recall (exact, per species): 0.28
Ave. precision (exact, per species): 0.28
Ave. total time (per model): 17.26
Ave. total time (per element, per model): 0.50
Ave. LLM time (per model): 16.18
Ave. LLM time (per element, per model): 0.46
Average number of predictions per species: 1.10

# Type distribution
Can LLM accurately identify complex?

In [4]:
def evaluate_complex_detection(csv_path: str):
    """
    Evaluate precision and recall for detecting complexes.
    
    Ground truth:
        qualifier == 'hasPart'  → complex
    Prediction:
        detected_entity_type == 'complex'
    """
    df = pd.read_csv(csv_path)

    # Ground truth: True if this species is actually a complex
    gt = df['qualifier'].astype(str).str.contains('hasPart', case=False, na=False)

    # Prediction: True if model predicted complex
    pred = df['detected_entity_type'].astype(str).str.lower() == 'complex'

    # Calculate TP, FP, FN
    tp = ((pred == True) & (gt == True)).sum()
    fp = ((pred == True) & (gt == False)).sum()
    fn = ((pred == False) & (gt == True)).sum()
    tn = ((pred == False) & (gt == False)).sum()

    # Precision and Recall
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0.0

    print(f"Total species: {len(df)}, 'hasPart' species: {sum(gt)}, 'complex' predictions: {sum(pred)}")
    print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, Accuracy: {accuracy:.4f}")

evaluate_complex_detection("autoType/biomd251106_uniprot_direct_llama-4_top3_autoType_complex_improved.csv")

Total species: 5292, 'hasPart' species: 2068, 'complex' predictions: 2117
Precision: 0.8375, Recall: 0.8574, Accuracy: 0.8793

In [5]:
evaluate_complex_detection("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts_updated.csv")

Total species: 12486, 'hasPart' species: 1043, 'complex' predictions: 967
Precision: 0.7901, Recall: 0.7325, Accuracy: 0.9614

In [6]:
evaluate_complex_detection("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_9606_autoType.csv")

Total species: 17510, 'hasPart' species: 2843, 'complex' predictions: 2855
Precision: 0.8252, Recall: 0.8287, Accuracy: 0.9437

# Statistics

In [5]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts_updated.csv", ref_results_csv=None)

Showing all results
Number of models assessed: 342
Number of models with predictions: 331
Number of annotations evaluated: 12486
Average accuracy (per model): 0.76
Ave. recall (formula): 0.77
Ave. precision (formula): 0.58
Ave. recall (exact): 0.65
Ave. precision (exact): 0.23
Average accuracy (per species): 0.87
Ave. recall (formula, per species): 0.87
Ave. precision (formula, per species): 0.65
Ave. recall (exact, per species): 0.57
Ave. precision (exact, per species): 0.36
Ave. total time (per model): 18.66
Ave. total time (per element, per model): 0.51
Ave. LLM time (per model): 18.10
Ave. LLM time (per element, per model): 0.50
Average number of predictions per species: 2.76

In [6]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts_updated.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 312
Number of annotations evaluated: 11373
Average accuracy (per model): 0.86
Ave. recall (formula): 0.86
Ave. precision (formula): 0.65
Ave. recall (exact): 0.73
Ave. precision (exact): 0.26
Average accuracy (per species): 0.93
Ave. recall (formula, per species): 0.93
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.60
Ave. precision (exact, per species): 0.39
Ave. total time (per model): 19.55
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.97
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 2.77

In [7]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 308
Number of annotations evaluated: 11370
Average accuracy (per model): 0.85
Ave. recall (formula): 0.85
Ave. precision (formula): 0.64
Ave. recall (exact): 0.72
Ave. precision (exact): 0.25
Average accuracy (per species): 0.91
Ave. recall (formula, per species): 0.91
Ave. precision (formula, per species): 0.67
Ave. recall (exact, per species): 0.59
Ave. precision (exact, per species): 0.37
Ave. total time (per model): 19.25
Ave. total time (per element, per model): 0.54
Ave. LLM time (per model): 18.57
Ave. LLM time (per element, per model): 0.52
Average number of predictions per species: 2.79

In [9]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts_updated.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 313
Number of annotations evaluated: 11373
Average accuracy (per model): 0.89
Ave. recall (formula): 0.89
Ave. precision (formula): 0.23
Ave. recall (exact): 0.84
Ave. precision (exact): 0.09
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.95
Ave. precision (formula, per species): 0.26
Ave. recall (exact, per species): 0.68
Ave. precision (exact, per species): 0.15
Ave. total time (per model): 19.59
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.90
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 8.93

In [8]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 306
Number of annotations evaluated: 11370
Average accuracy (per model): 0.87
Ave. recall (formula): 0.87
Ave. precision (formula): 0.23
Ave. recall (exact): 0.82
Ave. precision (exact): 0.09
Average accuracy (per species): 0.93
Ave. recall (formula, per species): 0.93
Ave. precision (formula, per species): 0.25
Ave. recall (exact, per species): 0.67
Ave. precision (exact, per species): 0.14
Ave. total time (per model): 18.79
Ave. total time (per element, per model): 0.53
Ave. LLM time (per model): 18.12
Ave. LLM time (per element, per model): 0.51
Average number of predictions per species: 8.97

In [7]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'], entity_types=['chemical'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Filtering results by entity types: ['chemical']
Number of models assessed: 305
Number of models with predictions: 305
Number of annotations evaluated: 10850
Average accuracy (per model): 0.93
Ave. recall (formula): 0.93
Ave. precision (formula): 0.24
Ave. recall (exact): 0.88
Ave. precision (exact): 0.09
Average accuracy (per species): 0.96
Ave. recall (formula, per species): 0.96
Ave. precision (formula, per species): 0.26
Ave. recall (exact, per species): 0.69
Ave. precision (exact, per species): 0.15
Ave. total time (per model): 19.60
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.89
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 9.28

In [5]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'], entity_types=['chemical'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Filtering results by entity types: ['chemical']
Number of models assessed: 307
Number of models with predictions: 307
Number of annotations evaluated: 10814
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.69
Ave. recall (exact): 0.77
Ave. precision (exact): 0.27
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.60
Ave. precision (exact, per species): 0.38
Ave. total time (per model): 19.96
Ave. total time (per element, per model): 0.57
Ave. LLM time (per model): 19.26
Ave. LLM time (per element, per model): 0.55
Average number of predictions per species: 2.88

In [4]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 308
Number of annotations evaluated: 11370
Average accuracy (per model): 0.85
Ave. recall (formula): 0.85
Ave. precision (formula): 0.64
Ave. recall (exact): 0.72
Ave. precision (exact): 0.25
Average accuracy (per species): 0.91
Ave. recall (formula, per species): 0.91
Ave. precision (formula, per species): 0.67
Ave. recall (exact, per species): 0.59
Ave. precision (exact, per species): 0.37
Ave. total time (per model): 19.25
Ave. total time (per element, per model): 0.54
Ave. LLM time (per model): 18.57
Ave. LLM time (per element, per model): 0.52
Average number of predictions per species: 2.79

In [5]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'], entity_types=['chemical'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Filtering results by entity types: ['chemical']
Number of models assessed: 308
Number of models with predictions: 308
Number of annotations evaluated: 10815
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.68
Ave. recall (exact): 0.77
Ave. precision (exact): 0.27
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.61
Ave. precision (exact, per species): 0.38
Ave. total time (per model): 19.98
Ave. total time (per element, per model): 0.57
Ave. LLM time (per model): 19.28
Ave. LLM time (per element, per model): 0.55
Average number of predictions per species: 2.88

In [14]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 316
Number of models with predictions: 310
Number of annotations evaluated: 11154
Average accuracy (per model): 0.88
Ave. recall (formula): 0.88
Ave. precision (formula): 0.66
Ave. recall (exact): 0.75
Ave. precision (exact): 0.26
Average accuracy (per species): 0.94
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.61
Ave. precision (exact, per species): 0.38
Ave. total time (per model): 19.10
Ave. total time (per element, per model): 0.54
Ave. LLM time (per model): 18.40
Ave. LLM time (per element, per model): 0.52
Average number of predictions per species: 2.83

In [ ]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 315
Number of models with predictions: 309
Number of annotations evaluated: 11145
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.24
Ave. recall (exact): 0.85
Ave. precision (exact): 0.09
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.95
Ave. precision (formula, per species): 0.25
Ave. recall (exact, per species): 0.69
Ave. precision (exact, per species): 0.14
Ave. total time (per model): 19.39
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.64
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 9.20

In [4]:
print_evaluation_results("autoType/biomd251106_chebi_direct_llama-3_top10_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 306
Number of models with predictions: 301
Number of annotations evaluated: 10806
Average accuracy (per model): 0.85
Ave. recall (formula): 0.85
Ave. precision (formula): 0.73
Ave. recall (exact): 0.79
Ave. precision (exact): 0.36
Average accuracy (per species): 0.90
Ave. recall (formula, per species): 0.90
Ave. precision (formula, per species): 0.77
Ave. recall (exact, per species): 0.59
Ave. precision (exact, per species): 0.48
Ave. total time (per model): 25.95
Ave. total time (per element, per model): 0.73
Ave. LLM time (per model): 23.66
Ave. LLM time (per element, per model): 0.67
Average number of predictions per species: 2.77

In [6]:
print_evaluation_results("results/biomd251106_chebi_direct_llama-3_top10.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 316
Number of annotations evaluated: 11370
Average accuracy (per model): 0.87
Ave. recall (formula): 0.87
Ave. precision (formula): 0.76
Ave. recall (exact): 0.79
Ave. precision (exact): 0.36
Average accuracy (per species): 0.87
Ave. recall (formula, per species): 0.86
Ave. precision (formula, per species): 0.74
Ave. recall (exact, per species): 0.57
Ave. precision (exact, per species): 0.46
Ave. total time (per model): 25.23
Ave. total time (per element, per model): 0.71
Ave. LLM time (per model): 22.73
Ave. LLM time (per element, per model): 0.64
Average number of predictions per species: 2.67

In [7]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-3_top10_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 307
Number of models with predictions: 307
Number of annotations evaluated: 10826
Average accuracy (per model): 0.94
Ave. recall (formula): 0.94
Ave. precision (formula): 0.23
Ave. recall (exact): 0.88
Ave. precision (exact): 0.09
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.22
Ave. recall (exact, per species): 0.68
Ave. precision (exact, per species): 0.13
Ave. total time (per model): 24.71
Ave. total time (per element, per model): 0.70
Ave. LLM time (per model): 23.80
Ave. LLM time (per element, per model): 0.67
Average number of predictions per species: 9.94

In [8]:
print_evaluation_results("results/biomd251106_chebi_rag_llama-3_top10.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 320
Number of annotations evaluated: 11370
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.23
Ave. recall (exact): 0.85
Ave. precision (exact): 0.09
Average accuracy (per species): 0.91
Ave. recall (formula, per species): 0.91
Ave. precision (formula, per species): 0.22
Ave. recall (exact, per species): 0.65
Ave. precision (exact, per species): 0.12
Ave. total time (per model): 23.79
Ave. total time (per element, per model): 0.67
Ave. LLM time (per model): 22.84
Ave. LLM time (per element, per model): 0.64
Average number of predictions per species: 9.89

In [8]:
# find different model, species pairs
df1 = pd.read_csv('results/biomd251106_chebi_rag_llama-4_top3.csv')
df2 = pd.read_csv('autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated.csv')
# only consider is, isVersionOf
df1 = df1[df1['qualifier'].isin(['is', 'isVersionOf'])]
df2 = df2[df2['qualifier'].isin(['is', 'isVersionOf'])]

# find pairs in df1 but not in df2
df1['model_species_pair'] = df1['model'] + '_' + df1['species_id']
df2['model_species_pair'] = df2['model'] + '_' + df2['species_id']
df1[~df1['model_species_pair'].isin(df2['model_species_pair'])].to_csv('autoType/biomd251106_chebi_rag_llama-4_top3_auto_diff.csv', index=False)