# Automatic entity type detection

In [1]:
import os
import sys
import pandas as pd
import numpy as np
from pathlib import Path
import logging
import warnings
warnings.filterwarnings('ignore')

# Add the project root to the Python path
project_root = Path().absolute().parent
sys.path.insert(0, str(project_root))

# Import AAAIM functions
from core import annotate_model, curate_model
from core.database_search import force_clear_chromadb, get_species_recommendations_rag
from utils.evaluation import (
    evaluate_single_model,
    evaluate_models_in_folder,
    print_evaluation_results,
    compare_results,
    process_saved_llm_responses
)

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# LLM configuration
# llm_model = "Llama-4-Maverick-17B-128E-Instruct-FP8"
llm_model = "Llama-3.3-70B-Instruct"
# llm_model = "meta-llama/llama-3.3-70b-instruct:free"
# llm_model = "gpt-4.1-nano"

output_dir = "./autoType/"  # Output directory for results

In [2]:
test_model_file = "/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels/BIOMD0000000052.xml"
# test_model_file = "190_few_anno.xml"
# Check if test model exists
if os.path.exists(test_model_file):
    print(f"✓ Test model found: {test_model_file}")
else:
    print(f"✗ Test model not found: {test_model_file}")

✓ Test model found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels/BIOMD0000000052.xml

In [3]:
from core.model_info import format_prompt, find_species_with_annotations_and_qualifiers
# extract species that have chebi annotation
existing_annotations, qualifiers = find_species_with_annotations_and_qualifiers(test_model_file, 'chebi')
existing_annotations

{'Glu': ['17234'],
 'Fru': ['28757'],
 'Formic_acid': ['30751'],
 'Acetic_acid': ['15366'],
 'lys_R': ['32568']}

In [4]:
# get the prompt for this model
prompt = format_prompt(test_model_file, existing_annotations.keys(), 'chemical')
print(prompt)

Now annotate these:
Chemical to annotate: Glu, Fru, Formic_acid, Acetic_acid, lys_R
Model: "Brands2002 - Monosaccharide-casein systems"

// Reactions:
Glu => Fru
Fru => Glu
Glu => C5 + Formic_acid
Fru => C5 + Formic_acid
Fru => 2 Triose
Triose => Cn + Acetic_acid
lys_R + Glu => Amadori
Amadori => Acetic_acid + lys_R
lys_R + Fru => AMP

// Notes:
"Brands2002 - Monosaccharide-casein systems
A kinetic model of the Maillard reaction occurring in heated monosaccharide-casein system.
This model is described in the article:
Kinetic modeling of reactions in heated monosaccharide-casein systems.
Brands CM, van Boekel MA
Journal of Agricultural and Food Chemistry. 2002, 50(23):6725-6739
Abstract:
In the present study, a kinetic model of the Maillard reaction occurring in heated monosaccharide-casein systems was proposed. Its parameters, the reaction rate constants, were estimated via multiresponse modeling. The determinant criterion was used as the statistical fit criterion instead of the familiar least squares to avoid statistical problems. The kinetic model was extensively tested by varying the reaction conditions. Different sugars (glucose, fructose, galactose, and tagatose) were studied regarding their effect on the reaction kinetics. This study has shown the power of multiresponse modeling for the unraveling of complicated reaction routes as occur in the Maillard reaction. The iterative process of proposing a model, confronting it with experiments, and criticizing the model was passed through four times to arrive at a model that was largely consistent with all results obtained. A striking difference was found between aldose and ketose sugars as suggested by the modeling results: not the ketoses themselves but only their reaction products were found to be reactive in the Maillard reaction.
This model is hosted on
and identified
by:
MODEL8177704759
.
for published quantitative kinetic models
.
for more information."

Return up to 3 standardized names or common synonyms for each chemical, ranked by likelihood.
Use the below format, do not include any other text except the synonyms, and give short reasons for all chemicals after 'Reason:' by the end.

SpeciesA: "name1", "name2", …
SpeciesB: …
Reason: …

In [5]:
result_df = evaluate_single_model(
    model_file=test_model_file,
    llm_model=llm_model,
    method = 'direct',
    top_k = 5,
    entity_type='chemical',
    database='chebi',
    save_llm_results=False,
    output_dir=output_dir,
    verbose=True
)

2025-11-24 13:13:33,786 - INFO - Evaluating model: BIOMD0000000023.xml
2025-11-24 13:13:33,889 - INFO - Evaluating 13 entities in BIOMD0000000023.xml
2025-11-24 13:13:37,702 - INFO - HTTP Request: POST https://api.llama.com/compat/v1/chat/completions "HTTP/1.1 200 OK"

LLM response:
Fru: "fructose", "D-fructose", "beta-D-fructose"
Glc: "glucose", "D-glucose", "alpha-D-glucose"
HexP: "hexose phosphate", "fructose-6-phosphate", "glucose-6-phosphate"
Suc6P: "sucrose-6-phosphate", "sucrose phosphate", "6-phosphosucrose"
Suc: "sucrose", "alpha-D-glucopyranosyl beta-D-fructofuranoside", "beta-D-fructofuranosyl alpha-D-glucopyranoside"
Sucvac: "sucrose", "vacuolar sucrose", "sucrose in vacuole"
Glcex: "glucose", "extracellular glucose", "external glucose"
Fruex: "fructose", "extracellular fructose", "external fructose"
phos: "phosphate", "inorganic phosphate", "orthophosphate"
UDP: "uridine diphosphate", "uridine 5'-diphosphate", "UDP"
ADP: "adenosine diphosphate", "adenosine 5'-diphosphate", "ADP"
ATP: "adenosine triphosphate", "adenosine 5'-triphosphate", "ATP"
glycolysis: "glycolytic pathway", "glycolysis intermediate", "UNK"
Reason: The model appears to be a metabolic model of sucrose metabolism, with reactions involving glucose, fructose, and sucrose. The names are standardized based on common biochemical nomenclature. Glycolysis is a pathway rather than a specific chemical, so it is annotated as such. Sucvac is likely referring to sucrose in the vacuole, but without more context, it is difficult to provide a more specific name.
Synonyms dict: {'Fru': ['fructose', 'D-fructose', 'beta-D-fructose'], 'Glc': ['glucose', 'D-glucose', 'alpha-D-glucose'], 'HexP': ['hexose phosphate', 'fructose-6-phosphate', 'glucose-6-phosphate'], 'Suc6P': ['sucrose-6-phosphate', 'sucrose phosphate', '6-phosphosucrose'], 'Suc': ['sucrose', 'alpha-D-glucopyranosyl beta-D-fructofuranoside', 'beta-D-fructofuranosyl alpha-D-glucopyranoside'], 'Sucvac': ['sucrose', 'vacuolar sucrose', 'sucrose in vacuole'], 'Glcex': ['glucose', 'extracellular glucose', 'external glucose'], 'Fruex': ['fructose', 'extracellular fructose', 'external fructose'], 'phos': ['phosphate', 'inorganic phosphate', 'orthophosphate'], 'UDP': ['uridine diphosphate', "uridine 5'-diphosphate", 'UDP'], 'ADP': ['adenosine diphosphate', "adenosine 5'-diphosphate", 'ADP'], 'ATP': ['adenosine triphosphate', "adenosine 5'-triphosphate", 'ATP'], 'glycolysis': ['glycolytic pathway', 'glycolysis intermediate', 'UNK']}

In [6]:
result_df

,model,species_id,display_name,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,match_score,...,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier,detected_entity_type
0,BIOMD0000000023.xml,Fru,,"[fructose, D-fructose, beta-D-fructose]",Chunk 1: The model appears to be a metabolic m...,[15824],D-fructose,"[28645, 28757, 15824, 37721, 48095]","beta-D-fructofuranose, fructose, D-fructose, D...","[0.6666666666666666, 0.3333333333333333, 0.333...",...,1.00,0.20,1,5.373753,3.784719,1.589034,None,None,is,unknown
1,BIOMD0000000023.xml,Glc,,"[glucose, D-glucose, alpha-D-glucose]",,[17634],D-glucose,"[4167, 42758, 17234, 17634, 17925]","D-glucopyranose, aldehydo-D-glucose, glucose, ...","[0.6666666666666666, 0.6666666666666666, 0.333...",...,1.00,0.20,1,5.373753,3.784719,1.589034,None,None,is,unknown
2,BIOMD0000000023.xml,HexP,,"[hexose phosphate, fructose-6-phosphate, gluco...",,"[16218, 15946, 14314, 18066]","beta-D-glucose 1-phosphate, keto-D-fructose 6-...","[47878, 16084, 15946, 88003]","hexose phosphate, beta-D-fructofuranose 6-phos...","[0.3333333333333333, 0.3333333333333333, 0.333...",...,0.25,0.25,1,5.373753,3.784719,1.589034,None,None,"hasVersion, hasVersion, hasVersion, hasVersion",unknown
3,BIOMD0000000023.xml,Suc6P,,"[sucrose-6-phosphate, sucrose phosphate, 6-pho...",,[16308],sucrose 6(F)-phosphate,"[131603, 16308]","sucrose 6(G)-phosphate, sucrose 6(F)-phosphate","[0.6666666666666666, 0.6666666666666666]",...,1.00,0.50,1,5.373753,3.784719,1.589034,None,None,is,unknown
4,BIOMD0000000023.xml,Suc,,"[sucrose, alpha-D-glucopyranosyl beta-D-fructo...",,[17992],sucrose,[17992],sucrose,[0.6666666666666666],...,1.00,1.00,1,5.373753,3.784719,1.589034,None,None,is,unknown
5,BIOMD0000000023.xml,Sucvac,,"[sucrose, vacuolar sucrose, sucrose in vacuole]",,[17992],sucrose,[17992],sucrose,[0.3333333333333333],...,1.00,1.00,1,5.373753,3.784719,1.589034,None,None,is,unknown
6,BIOMD0000000023.xml,glycolysis,,"[glycolytic pathway, glycolysis intermediate, ...",,[28013],"beta-D-fructofuranose 1,6-bisphosphate",[],NA,[],...,0.00,0.00,0,5.373753,3.784719,1.589034,None,None,is,unknown
7,BIOMD0000000023.xml,phos,,"[phosphate, inorganic phosphate, orthophosphate]",,[18367],phosphate(3-),"[18367, 26020, 26078, 35780, 43474]","phosphate(3-), phosphate, phosphoric acid, pho...","[0.6666666666666666, 0.3333333333333333, 0.333...",...,1.00,0.20,1,5.373753,3.784719,1.589034,None,None,is,unknown
8,BIOMD0000000023.xml,UDP,,"[uridine diphosphate, uridine 5'-diphosphate, ...",,[17659],UDP,"[17659, 58223]","UDP, UDP(3-)","[1.0, 0.6666666666666666]",...,1.00,0.50,1,5.373753,3.784719,1.589034,None,None,is,unknown
9,BIOMD0000000023.xml,ADP,,"[adenosine diphosphate, adenosine 5'-diphospha...",,[16761],ADP,"[16761, 456216, 177051, 73342]","ADP, ADP(3-), Adenosine_Diphosphate, Ala-Asp-Pro","[0.6666666666666666, 0.6666666666666666, 0.333...",...,1.00,0.25,1,5.373753,3.784719,1.589034,None,None,is,unknown
10,BIOMD0000000023.xml,ATP,,"[adenosine triphosphate, adenosine 5'-triphosp...",,[15422],ATP,"[15422, 30616]","ATP, ATP(4-)","[1.0, 0.3333333333333333]",...,1.00,0.50,1,5.373753,3.784719,1.589034,None,None,is,unknown
11,BIOMD0000000023.xml,Glcex,,"[glucose, extracellular glucose, external gluc...",,[17634],D-glucose,"[4167, 42758, 17234]","D-glucopyranose, aldehydo-D-glucose, glucose","[0.3333333333333333, 0.3333333333333333, 0.333...",...,0.00,0.00,1,5.373753,3.784719,1.589034,None,None,is,unknown
12,BIOMD0000000023.xml,Fruex,,"[fructose, extracellular fructose, external fr...",,[15824],D-fructose,"[28645, 28757]","beta-D-fructofuranose, fructose","[0.3333333333333333, 0.3333333333333333]",...,0.00,0.00,1,5.373753,3.784719,1.589034,None,None,is,unknown

# Test on auto detection

In [5]:
import sys
import importlib
importlib.reload(sys.modules['core.model_info'])
importlib.reload(sys.modules['utils.evaluation'])
from core.model_info import format_prompt, find_species_with_annotations_and_qualifiers
from utils.evaluation import evaluate_single_model

In [6]:
prompt = format_prompt(test_model_file, existing_annotations.keys(), 'auto')
print(prompt)

Now annotate these species:
Species to annotate: Glu, Fru, Formic_acid, Acetic_acid, lys_R
Model: "Brands2002 - Monosaccharide-casein systems"

// Reactions:
Glu => Fru
Fru => Glu
Glu => C5 + Formic_acid
Fru => C5 + Formic_acid
Fru => 2 Triose
Triose => Cn + Acetic_acid
lys_R + Glu => Amadori
Amadori => Acetic_acid + lys_R
lys_R + Fru => AMP

// Notes:
"Brands2002 - Monosaccharide-casein systems
A kinetic model of the Maillard reaction occurring in heated monosaccharide-casein system.
This model is described in the article:
Kinetic modeling of reactions in heated monosaccharide-casein systems.
Brands CM, van Boekel MA
Journal of Agricultural and Food Chemistry. 2002, 50(23):6725-6739
Abstract:
In the present study, a kinetic model of the Maillard reaction occurring in heated monosaccharide-casein systems was proposed. Its parameters, the reaction rate constants, were estimated via multiresponse modeling. The determinant criterion was used as the statistical fit criterion instead of the familiar least squares to avoid statistical problems. The kinetic model was extensively tested by varying the reaction conditions. Different sugars (glucose, fructose, galactose, and tagatose) were studied regarding their effect on the reaction kinetics. This study has shown the power of multiresponse modeling for the unraveling of complicated reaction routes as occur in the Maillard reaction. The iterative process of proposing a model, confronting it with experiments, and criticizing the model was passed through four times to arrive at a model that was largely consistent with all results obtained. A striking difference was found between aldose and ketose sugars as suggested by the modeling results: not the ketoses themselves but only their reaction products were found to be reactive in the Maillard reaction.
This model is hosted on
and identified
by:
MODEL8177704759
.
for published quantitative kinetic models
.
for more information."

For each species, determine its entity type (chemical, gene, protein, complex, unknown).
Return up to 3 standardized names or common synonyms for each species, ranked by likelihood.
Specify the entity type in parentheses after each species ID.
Use the below format, do not include any other text except the synonyms, and give short reasons for all species after 'Reason:' by the end.

SpeciesA (entity_type): "name1", "name2", …
SpeciesB (entity_type): …
Reason: …

In [7]:
result_df = evaluate_single_model(
    model_file=test_model_file,
    llm_model=llm_model,
    method = 'direct',
    top_k = 3,
    entity_type='auto',
    database='chebi',
    save_llm_results=False,
    output_dir=output_dir,
    verbose=True
)

2025-11-26 23:06:29,914 - INFO - Evaluating model: BIOMD0000000052.xml
2025-11-26 23:06:29,981 - INFO - Evaluating 4 entities in BIOMD0000000052.xml
2025-11-26 23:06:32,136 - INFO - HTTP Request: POST https://api.llama.com/compat/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-26 23:06:32,150 - INFO - Detected entity types: {'chemical': 3, 'protein': 1}
2025-11-26 23:06:32,150 - INFO - Searching chebi for 3 chemical entities
2025-11-26 23:06:33,071 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-26 23:06:33,071 - WARNING - No valid database found for entity type 'protein' in ['chebi'] for 1 species

In [8]:
result_df

,model,species_id,display_name,detected_entity_type,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,...,precision_formula,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier
0,BIOMD0000000052.xml,Glu,,chemical,"[glucose, D-glucose, blood sugar]",Chunk 1: The model describes the Maillard reac...,[17234],glucose,"[4167, 42758, 17234]","D-glucopyranose, aldehydo-D-glucose, glucose",...,1.0,1.0,0.333,1,3.073333,2.15174,0.921593,None,None,is
1,BIOMD0000000052.xml,Formic_acid,,chemical,"[formic acid, methanoic acid, HCOOH]",,[30751],formic acid,[30751],formic acid,...,1.0,1.0,1.000,1,3.073333,2.15174,0.921593,None,None,is
2,BIOMD0000000052.xml,Acetic_acid,,chemical,"[acetic acid, ethanoic acid, CH3COOH]",,[15366],acetic acid,[15366],acetic acid,...,1.0,1.0,1.000,1,3.073333,2.15174,0.921593,None,None,is
3,BIOMD0000000052.xml,lys_R,,protein,"[lysine receptor, lysine, L-lysine]",,[32568],lysine residue,[],NA,...,0.0,0.0,0.000,0,3.073333,2.15174,0.921593,None,None,is

In [8]:
from core.llm_interface import SYSTEM_PROMPT, query_llm, parse_llm_response, get_system_prompt
llm_response = """
Ca_cyt (chemical): "calcium(2+)", "calcium ion", "Ca2+"
CaER (chemical): "calcium", "endoplasmic reticulum calcium", "Ca2+ in endoplasmic reticulum"
CaM (chemical): "calmodulin", "calcium-modulated protein", "CaM protein"
CaPr (complex): "calcium-protein complex", "protein-calcium complex", "calcium bound protein"

Reason: The model "Marhl2000_CaOscillations" suggests a focus on calcium oscillations
"""
chunk_synonyms_dict, chunk_entity_type_dict, chunk_reason = parse_llm_response(llm_response)

In [29]:
# Test with a single model using automatic entity type detection
recommendations_df, metrics = annotate_model(
    model_file=test_model_file,
    llm_model=llm_model,
    method="direct",
    top_k=3,
    entity_type="auto",
    database=["chebi", "uniprot"]
)

2025-11-17 14:57:08,492 - INFO - Starting annotation for model: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels/BIOMD0000000039.xml
2025-11-17 14:57:08,493 - INFO - Using LLM model: Llama-3.3-70B-Instruct
2025-11-17 14:57:08,493 - INFO - Using method: direct for database search
2025-11-17 14:57:08,494 - INFO - Entity type: auto, Database: ['chebi', 'uniprot']
2025-11-17 14:57:08,494 - INFO - >>>Step 1: Getting species from model...<<<
2025-11-17 14:57:08,500 - INFO - Found 5 species in model
2025-11-17 14:57:08,501 - WARNING - Entity type auto with database ['chebi', 'uniprot'] not yet supported
2025-11-17 14:57:08,501 - INFO - Annotate all 5 entities
2025-11-17 14:57:08,501 - INFO - >>>Step 2: Extracting model context...<<<
2025-11-17 14:57:08,526 - INFO - Extracted context for model: Marhl2000_CaOscillations
2025-11-17 14:57:08,526 - INFO - >>>Step 3: Querying LLM (Llama-3.3-70B-Instruct)...<<<
2025-11-17 14:57:08,546 - WARNING - Auto entity type detection not yet implemented
2025-11-17 14:57:08,547 - ERROR - Failed to format prompt

## uniprot

In [ ]:
test_model_file = "/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106/BIOMD0000000019.xml"
tax_id = 9606
# Check if test model exist
if os.path.exists(test_model_file):
    print(f"✓ Test model found: {test_model_file}")
else:
    print(f"✗ Test model not found: {test_model_file}")

✓ Test model found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106/BIOMD0000000019.xml

In [ ]:
# Running with given entity type
result_df = evaluate_single_model(
    model_file=test_model_file,
    tax_id=tax_id,
    llm_model=llm_model,
    entity_type='protein',
    database='uniprot',
    save_llm_results=False,
    output_dir=output_dir
)

2025-11-28 17:28:01,114 - INFO - Evaluating model: BIOMD0000000019.xml
2025-11-28 17:28:01,115 - INFO - Using organism-specific search for tax_id: 9606
2025-11-28 17:28:01,162 - INFO - Evaluating 17 entities in BIOMD0000000019.xml
2025-11-28 17:28:07,679 - INFO - HTTP Request: POST https://api.llama.com/compat/v1/chat/completions "HTTP/1.1 200 OK"

In [16]:
result_df

,model,species_id,display_name,detected_entity_type,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,...,precision_formula,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier
0,BIOMD0000000019.xml,x3,EGF-EGFR,protein,"[EGFR, ERBB1, HER1]",Chunk 1: The model appears to be an EGF MAPK s...,"[P01133, P00533]","EGF, EGFR",[P00533],EGFR,...,0,0.50,1.0,1,6.857546,6.358645,0.498901,9606,None,"hasVersion, hasVersion"
1,BIOMD0000000019.xml,x4,EGF-EGFR^2,protein,"[EGFR, ERBB1, HER1]",,"[P01133, P00533]","EGF, EGFR",[P00533],EGFR,...,0,0.50,1.0,1,6.857546,6.358645,0.498901,9606,None,"hasVersion, hasVersion"
2,BIOMD0000000019.xml,x5,EGF-EGFR*^2,protein,"[EGFR, ERBB1, HER1]",,"[P00533, P01133]","EGFR, EGF",[P00533],EGFR,...,0,0.50,1.0,1,6.857546,6.358645,0.498901,9606,None,"hasVersion, hasVersion"
3,BIOMD0000000019.xml,x6,EGFRi,protein,"[EGFR, ERBB1, HER1]",,[P00533],EGFR,[P00533],EGFR,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf
4,BIOMD0000000019.xml,x7,EGF-EGFR*^2-GAP-Grb2-Prot,protein,"[GRB2, GROWTH FACTOR RECEPTOR-BOUND PROTEIN 2,...",,"[P20936, P62993, P00533, P01133]","RASA1, GRB2, EGFR, EGF",[P62993],GRB2,...,0,0.25,1.0,1,6.857546,6.358645,0.498901,9606,None,"hasVersion, hasVersion, hasVersion, hasVersion"
5,BIOMD0000000019.xml,x8,EGF-EGFRi*^2,protein,"[EGFR, ERBB1, HER1]",,"[P00533, P01133]","EGFR, EGF",[P00533],EGFR,...,0,0.50,1.0,1,6.857546,6.358645,0.498901,9606,None,"hasVersion, hasVersion"
6,BIOMD0000000019.xml,x10,EGF-EGFRi,protein,"[EGFR, ERBB1, HER1]",,"[P01133, P00533]","EGF, EGFR",[P00533],EGFR,...,0,0.50,1.0,1,6.857546,6.358645,0.498901,9606,None,"hasVersion, hasVersion"
7,BIOMD0000000019.xml,x14,GAP,protein,"[GAP, GTPASE-ACTIVATING PROTEIN, RAS GTPASE-AC...",,[P20936],RASA1,[P20936],RASA1,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf
8,BIOMD0000000019.xml,x22,Grb2,protein,"[GRB2, GROWTH FACTOR RECEPTOR-BOUND PROTEIN 2,...",,[P62993],GRB2,[P62993],GRB2,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf
9,BIOMD0000000019.xml,x24,Sos,protein,"[SOS1, SON OF SEVENLESS, GROWTH FACTOR RECEPTO...",,[Q07889],SOS1,[Q07889],SOS1,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf
10,BIOMD0000000019.xml,x26,Ras-GDP,protein,"[HRAS, HARAS, GTPASE HRAS]",,[P01112],HRAS,[P01112],HRAS,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,hasPart
11,BIOMD0000000019.xml,x28,Ras-GTP,protein,"[HRAS, HARAS, GTPASE HRAS]",,[P01112],HRAS,[P01112],HRAS,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,hasPart
12,BIOMD0000000019.xml,x31,Shc,protein,"[SHC1, SRC HOMOLOGY 2 DOMAIN-CONTAINING TRANSF...",,[P98077],SHC2,[P29353],SHC1,...,0,0.00,0.0,0,6.857546,6.358645,0.498901,9606,None,isVersionOf
13,BIOMD0000000019.xml,x41,Raf,protein,"[RAF1, V-RAF-1 MURINE LEUKEMIA VIRAL ONCOGENE ...",,[P04049],RAF1,[P04049],RAF1,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf
14,BIOMD0000000019.xml,x47,MEK,protein,"[MAP2K1, MITOGEN-ACTIVATED PROTEIN KINASE KINA...",,[Q02750],MAP2K1,[Q02750],MAP2K1,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf
15,BIOMD0000000019.xml,x49,MEK-P,protein,"[MAP2K1, MITOGEN-ACTIVATED PROTEIN KINASE KINA...",,[Q02750],MAP2K1,[Q02750],MAP2K1,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf
16,BIOMD0000000019.xml,x55,ERK,protein,"[MAPK1, MITOGEN-ACTIVATED PROTEIN KINASE 1, ERK2]",,[P28482],MAPK1,[P28482],MAPK1,...,0,1.00,1.0,1,6.857546,6.358645,0.498901,9606,None,isVersionOf

In [17]:
# Running with auto entity type
result_df = evaluate_single_model(
    model_file=test_model_file,
    tax_id=tax_id,
    llm_model=llm_model,
    entity_type='auto',
    database='uniprot',
    save_llm_results=False,
    output_dir=output_dir
)

2025-11-28 17:28:46,121 - INFO - Evaluating model: BIOMD0000000019.xml
2025-11-28 17:28:46,122 - INFO - Using organism-specific search for tax_id: 9606
2025-11-28 17:28:46,160 - INFO - Evaluating 17 entities in BIOMD0000000019.xml
2025-11-28 17:28:52,267 - INFO - HTTP Request: POST https://api.llama.com/compat/v1/chat/completions "HTTP/1.1 200 OK"
2025-11-28 17:28:52,268 - INFO - Detected entity types: {'complex': 6, 'protein': 11}
2025-11-28 17:28:52,268 - INFO - Searching uniprot for 6 complex entities
2025-11-28 17:28:52,370 - INFO - Searching uniprot for 11 protein entities

In [18]:
result_df

,model,species_id,display_name,detected_entity_type,synonyms_LLM,reason,exist_annotation_id,exist_annotation_name,predictions,predictions_names,...,precision_formula,recall_exact,precision_exact,accuracy,total_time,llm_time,query_time,tax_id,tax_name,qualifier
0,BIOMD0000000019.xml,x3,EGF-EGFR,complex,"[EGF-EGFR, Epidermal Growth Factor Receptor co...",Chunk 1: The entity types were determined base...,"[P01133, P00533]","EGF, EGFR",[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,"hasVersion, hasVersion"
1,BIOMD0000000019.xml,x4,EGF-EGFR^2,complex,"[EGF-EGFR dimer, EGFR dimer, EGF-EGFR^2]",,"[P01133, P00533]","EGF, EGFR",[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,"hasVersion, hasVersion"
2,BIOMD0000000019.xml,x5,EGF-EGFR*^2,complex,"[EGF-EGFR^2-GAP, EGFR-GAP complex, GAP-EGFR co...",,"[P00533, P01133]","EGFR, EGF",[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,"hasVersion, hasVersion"
3,BIOMD0000000019.xml,x7,EGF-EGFR*^2-GAP-Grb2-Prot,complex,"[EGF-EGFR*^2-GAP-Grb2-Prot, EGFR-Grb2-GAP comp...",,"[P20936, P62993, P00533, P01133]","RASA1, GRB2, EGFR, EGF",[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,"hasVersion, hasVersion, hasVersion, hasVersion"
4,BIOMD0000000019.xml,x8,EGF-EGFRi*^2,complex,"[EGF-EGFRi*^2, Inactive EGFR dimer, EGFRi dimer]",,"[P00533, P01133]","EGFR, EGF",[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,"hasVersion, hasVersion"
5,BIOMD0000000019.xml,x10,EGF-EGFRi,complex,"[EGF-EGFRi, EGFRi, Inactive EGFR]",,"[P01133, P00533]","EGF, EGFR",[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,"hasVersion, hasVersion"
6,BIOMD0000000019.xml,x6,EGFRi,protein,"[EGFRi, Inactive EGFR, EGFR inhibitor]",,[P00533],EGFR,[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,isVersionOf
7,BIOMD0000000019.xml,x14,GAP,protein,"[GAP, GTPase-activating protein, RasGAP]",,[P20936],RASA1,"[P20936, Q15283]","RASA1, RASA2",...,0,1.0,0.5,1,6.216499,5.964367,0.252132,9606,None,isVersionOf
8,BIOMD0000000019.xml,x22,Grb2,protein,"[Grb2, Growth factor receptor-bound protein 2,...",,[P62993],GRB2,[P62993],GRB2,...,0,1.0,1.0,1,6.216499,5.964367,0.252132,9606,None,isVersionOf
9,BIOMD0000000019.xml,x24,Sos,protein,"[Sos, Son of sevenless, Guanine nucleotide exc...",,[Q07889],SOS1,[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,isVersionOf
10,BIOMD0000000019.xml,x26,Ras-GDP,protein,"[Ras-GDP, Ras protein, GDP-bound Ras]",,[P01112],HRAS,[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,hasPart
11,BIOMD0000000019.xml,x28,Ras-GTP,protein,"[Ras-GTP, GTP-bound Ras, Active Ras]",,[P01112],HRAS,[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,hasPart
12,BIOMD0000000019.xml,x31,Shc,protein,"[Shc, Src homology 2 domain-containing transfo...",,[P98077],SHC2,[P29353],SHC1,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,isVersionOf
13,BIOMD0000000019.xml,x41,Raf,protein,"[Raf, Raf kinase, Raf-1 protein kinase]",,[P04049],RAF1,"[P04049, Q9Y6X8]","RAF1, ZHX2",...,0,1.0,0.5,1,6.216499,5.964367,0.252132,9606,None,isVersionOf
14,BIOMD0000000019.xml,x47,MEK,protein,"[MEK, Mitogen-activated protein kinase kinase,...",,[Q02750],MAP2K1,[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,isVersionOf
15,BIOMD0000000019.xml,x49,MEK-P,protein,"[MEK-P, Phosphorylated MEK, pMEK]",,[Q02750],MAP2K1,[],NA,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,isVersionOf
16,BIOMD0000000019.xml,x55,ERK,protein,"[ERK, Extracellular signal-regulated kinase, M...",,[P28482],MAPK1,[P29323],EPHB2,...,0,0.0,0.0,0,6.216499,5.964367,0.252132,9606,None,isVersionOf

# Batch evaluation
## chebi

In [2]:
model_dir = "/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106"
# model_dir = "test_models"
# Check if model directory exists
if os.path.exists(model_dir):
    model_files = [f for f in os.listdir(model_dir) if f.endswith('.xml')]
    print(f"✓ Model directory found: {model_dir}")
    print(f"  - Found {len(model_files)} XML files")
    # print(f"  - Will test first {min(num_models_to_test, len(model_files))} models")

✓ Model directory found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106
  - Found 1075 XML files

In [ ]:
# Run batch evaluation on updated BioModels
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database='chebi',
    method="rag",
    top_k = 3,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv",
    start_at=1
)

In [8]:
# Run batch evaluation 
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database='chebi',
    method="rag",
    top_k = 10,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts_updated.csv",
    start_at=1
)

2025-12-06 14:20:19,157 - WARNING - Skipping BIOMD0000000001.xml - no results generated

LLM results will be saved to: ./autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420
Saved configuration to ./autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/config.txt
Evaluating 1/1075: BIOMD0000000001.xml
Evaluating 2/1075: BIOMD0000000002.xml

2025-12-06 14:20:21,227 - WARNING - Skipping BIOMD0000000003.xml - no results generated
2025-12-06 14:20:21,231 - WARNING - Skipping BIOMD0000000004.xml - no results generated
2025-12-06 14:20:21,237 - WARNING - Skipping BIOMD0000000005.xml - no results generated
2025-12-06 14:20:21,240 - WARNING - Skipping BIOMD0000000006.xml - no results generated
2025-12-06 14:20:21,251 - WARNING - Skipping BIOMD0000000007.xml - no results generated
2025-12-06 14:20:21,256 - WARNING - Skipping BIOMD0000000008.xml - no results generated
2025-12-06 14:20:21,268 - WARNING - Skipping BIOMD0000000009.xml - no results generated
2025-12-06 14:20:21,275 - WARNING - Skipping BIOMD0000000010.xml - no results generated
2025-12-06 14:20:21,290 - WARNING - Skipping BIOMD0000000011.xml - no results generated
2025-12-06 14:20:21,299 - WARNING - Skipping BIOMD0000000012.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000002.txt
Evaluating 3/1075: BIOMD0000000003.xml
Evaluating 4/1075: BIOMD0000000004.xml
Evaluating 5/1075: BIOMD0000000005.xml
Evaluating 6/1075: BIOMD0000000006.xml
Evaluating 7/1075: BIOMD0000000007.xml
Evaluating 8/1075: BIOMD0000000008.xml
Evaluating 9/1075: BIOMD0000000009.xml
Evaluating 10/1075: BIOMD0000000010.xml
Evaluating 11/1075: BIOMD0000000011.xml
Evaluating 12/1075: BIOMD0000000012.xml
Evaluating 13/1075: BIOMD0000000013.xml

2025-12-06 14:20:30,130 - WARNING - Skipping BIOMD0000000014.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000013.txt
Evaluating 14/1075: BIOMD0000000014.xml
Evaluating 15/1075: BIOMD0000000015.xml

2025-12-06 14:20:36,946 - WARNING - Skipping BIOMD0000000016.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000015.txt
Evaluating 16/1075: BIOMD0000000016.xml
Evaluating 17/1075: BIOMD0000000017.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000017.txt
Evaluating 18/1075: BIOMD0000000018.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000018.txt
Evaluating 19/1075: BIOMD0000000019.xml

2025-12-06 14:20:50,382 - WARNING - Skipping BIOMD0000000020.xml - no results generated
2025-12-06 14:20:50,392 - WARNING - Skipping BIOMD0000000021.xml - no results generated
2025-12-06 14:20:50,403 - WARNING - Skipping BIOMD0000000022.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000019.txt
Evaluating 20/1075: BIOMD0000000020.xml
Evaluating 21/1075: BIOMD0000000021.xml
Evaluating 22/1075: BIOMD0000000022.xml
Evaluating 23/1075: BIOMD0000000023.xml

2025-12-06 14:20:55,697 - WARNING - Skipping BIOMD0000000024.xml - no results generated
2025-12-06 14:20:55,701 - WARNING - Skipping BIOMD0000000025.xml - no results generated
2025-12-06 14:20:55,707 - WARNING - Skipping BIOMD0000000026.xml - no results generated
2025-12-06 14:20:55,711 - WARNING - Skipping BIOMD0000000027.xml - no results generated
2025-12-06 14:20:55,721 - WARNING - Skipping BIOMD0000000028.xml - no results generated
2025-12-06 14:20:55,728 - WARNING - Skipping BIOMD0000000029.xml - no results generated
2025-12-06 14:20:55,739 - WARNING - Skipping BIOMD0000000030.xml - no results generated
2025-12-06 14:20:55,743 - WARNING - Skipping BIOMD0000000031.xml - no results generated
2025-12-06 14:20:55,765 - WARNING - Skipping BIOMD0000000032.xml - no results generated
2025-12-06 14:20:55,780 - WARNING - Skipping BIOMD0000000033.xml - no results generated
2025-12-06 14:20:55,789 - WARNING - Skipping BIOMD0000000034.xml - no results generated
2025-12-06 14:20:55,796 - WARNING - Skipping BIOMD0000000035.xml - no results generated
2025-12-06 14:20:55,800 - WARNING - Skipping BIOMD0000000036.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000023.txt
Evaluating 24/1075: BIOMD0000000024.xml
Evaluating 25/1075: BIOMD0000000025.xml
Evaluating 26/1075: BIOMD0000000026.xml
Evaluating 27/1075: BIOMD0000000027.xml
Evaluating 28/1075: BIOMD0000000028.xml
Evaluating 29/1075: BIOMD0000000029.xml
Evaluating 30/1075: BIOMD0000000030.xml
Evaluating 31/1075: BIOMD0000000031.xml
Evaluating 32/1075: BIOMD0000000032.xml
Evaluating 33/1075: BIOMD0000000033.xml
Evaluating 34/1075: BIOMD0000000034.xml
Evaluating 35/1075: BIOMD0000000035.xml
Evaluating 36/1075: BIOMD0000000036.xml
Evaluating 37/1075: BIOMD0000000037.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000037.txt
Evaluating 38/1075: BIOMD0000000038.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000038.txt
Evaluating 39/1075: BIOMD0000000039.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000039.txt
Evaluating 40/1075: BIOMD0000000040.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000040.txt
Evaluating 41/1075: BIOMD0000000041.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000041.txt
Evaluating 42/1075: BIOMD0000000042.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000042.txt
Evaluating 43/1075: BIOMD0000000043.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000043.txt
Evaluating 44/1075: BIOMD0000000044.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000044.txt
Evaluating 45/1075: BIOMD0000000045.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000045.txt
Evaluating 46/1075: BIOMD0000000046.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000046.txt
Evaluating 47/1075: BIOMD0000000047.xml

2025-12-06 14:21:30,379 - WARNING - Skipping BIOMD0000000048.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000047.txt
Evaluating 48/1075: BIOMD0000000048.xml
Evaluating 49/1075: BIOMD0000000049.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000049.txt
Evaluating 50/1075: BIOMD0000000050.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000050.txt
Evaluating 51/1075: BIOMD0000000051.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000051.txt
Evaluating 52/1075: BIOMD0000000052.xml

2025-12-06 14:21:54,170 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000052.txt
Evaluating 53/1075: BIOMD0000000053.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000053.txt
Evaluating 54/1075: BIOMD0000000054.xml

2025-12-06 14:21:58,840 - WARNING - Skipping BIOMD0000000055.xml - no results generated
2025-12-06 14:21:58,871 - WARNING - Skipping BIOMD0000000056.xml - no results generated
2025-12-06 14:21:58,876 - WARNING - Skipping BIOMD0000000057.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000054.txt
Evaluating 55/1075: BIOMD0000000055.xml
Evaluating 56/1075: BIOMD0000000056.xml
Evaluating 57/1075: BIOMD0000000057.xml
Evaluating 58/1075: BIOMD0000000058.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000058.txt
Evaluating 59/1075: BIOMD0000000059.xml

2025-12-06 14:22:03,577 - WARNING - Skipping BIOMD0000000060.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000059.txt
Evaluating 60/1075: BIOMD0000000060.xml
Evaluating 61/1075: BIOMD0000000061.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000061.txt
Evaluating 62/1075: BIOMD0000000062.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000062.txt
Evaluating 63/1075: BIOMD0000000063.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000063.txt
Evaluating 64/1075: BIOMD0000000064.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000064.txt
Evaluating 65/1075: BIOMD0000000065.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000065.txt
Evaluating 66/1075: BIOMD0000000066.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000066.txt
Evaluating 67/1075: BIOMD0000000067.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000067.txt
Evaluating 68/1075: BIOMD0000000068.xml

2025-12-06 14:22:34,907 - WARNING - Skipping BIOMD0000000069.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000068.txt
Evaluating 69/1075: BIOMD0000000069.xml
Evaluating 70/1075: BIOMD0000000070.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000070.txt
Evaluating 71/1075: BIOMD0000000071.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000071.txt
Evaluating 72/1075: BIOMD0000000072.xml

2025-12-06 14:23:04,769 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:23:04,822 - WARNING - Skipping BIOMD0000000073.xml - no results generated
2025-12-06 14:23:04,839 - WARNING - Skipping BIOMD0000000074.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000072.txt
Evaluating 73/1075: BIOMD0000000073.xml
Evaluating 74/1075: BIOMD0000000074.xml
Evaluating 75/1075: BIOMD0000000075.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000075.txt
Evaluating 76/1075: BIOMD0000000076.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000076.txt
Evaluating 77/1075: BIOMD0000000077.xml

2025-12-06 14:23:12,506 - WARNING - Skipping BIOMD0000000078.xml - no results generated
2025-12-06 14:23:12,509 - WARNING - Skipping BIOMD0000000079.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000077.txt
Evaluating 78/1075: BIOMD0000000078.xml
Evaluating 79/1075: BIOMD0000000079.xml
Evaluating 80/1075: BIOMD0000000080.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000080.txt
Evaluating 81/1075: BIOMD0000000081.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000081.txt
Evaluating 82/1075: BIOMD0000000082.xml

2025-12-06 14:23:31,488 - WARNING - Skipping BIOMD0000000083.xml - no results generated
2025-12-06 14:23:31,493 - WARNING - Skipping BIOMD0000000084.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000082.txt
Evaluating 83/1075: BIOMD0000000083.xml
Evaluating 84/1075: BIOMD0000000084.xml
Evaluating 85/1075: BIOMD0000000085.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000085.txt
Evaluating 86/1075: BIOMD0000000086.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000086.txt
Evaluating 87/1075: BIOMD0000000087.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000087.txt
Evaluating 88/1075: BIOMD0000000088.xml

2025-12-06 14:24:23,830 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:24:24,449 - WARNING - Skipping BIOMD0000000089.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000088.txt
Evaluating 89/1075: BIOMD0000000089.xml
Evaluating 90/1075: BIOMD0000000090.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000090.txt
Evaluating 91/1075: BIOMD0000000091.xml

2025-12-06 14:24:32,568 - WARNING - Skipping BIOMD0000000092.xml - no results generated
2025-12-06 14:24:32,586 - WARNING - Skipping BIOMD0000000093.xml - no results generated
2025-12-06 14:24:32,605 - WARNING - Skipping BIOMD0000000094.xml - no results generated
2025-12-06 14:24:32,619 - WARNING - Skipping BIOMD0000000095.xml - no results generated
2025-12-06 14:24:32,635 - WARNING - Skipping BIOMD0000000096.xml - no results generated
2025-12-06 14:24:32,651 - WARNING - Skipping BIOMD0000000097.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000091.txt
Evaluating 92/1075: BIOMD0000000092.xml
Evaluating 93/1075: BIOMD0000000093.xml
Evaluating 94/1075: BIOMD0000000094.xml
Evaluating 95/1075: BIOMD0000000095.xml
Evaluating 96/1075: BIOMD0000000096.xml
Evaluating 97/1075: BIOMD0000000097.xml
Evaluating 98/1075: BIOMD0000000098.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000098.txt
Evaluating 99/1075: BIOMD0000000099.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000099.txt
Evaluating 100/1075: BIOMD0000000100.xml

2025-12-06 14:24:37,614 - WARNING - Skipping BIOMD0000000101.xml - no results generated
2025-12-06 14:24:37,623 - WARNING - Skipping BIOMD0000000102.xml - no results generated
2025-12-06 14:24:37,638 - WARNING - Skipping BIOMD0000000103.xml - no results generated
2025-12-06 14:24:37,642 - WARNING - Skipping BIOMD0000000104.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000100.txt
Evaluating 101/1075: BIOMD0000000101.xml
Evaluating 102/1075: BIOMD0000000102.xml
Evaluating 103/1075: BIOMD0000000103.xml
Evaluating 104/1075: BIOMD0000000104.xml
Evaluating 105/1075: BIOMD0000000105.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000105.txt
Evaluating 106/1075: BIOMD0000000106.xml

2025-12-06 14:24:44,136 - WARNING - Skipping BIOMD0000000107.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000106.txt
Evaluating 107/1075: BIOMD0000000107.xml
Evaluating 108/1075: BIOMD0000000108.xml

2025-12-06 14:24:46,852 - WARNING - Skipping BIOMD0000000109.xml - no results generated
2025-12-06 14:24:46,860 - WARNING - Skipping BIOMD0000000110.xml - no results generated
2025-12-06 14:24:46,869 - WARNING - Skipping BIOMD0000000111.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000108.txt
Evaluating 109/1075: BIOMD0000000109.xml
Evaluating 110/1075: BIOMD0000000110.xml
Evaluating 111/1075: BIOMD0000000111.xml
Evaluating 112/1075: BIOMD0000000112.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000112.txt
Evaluating 113/1075: BIOMD0000000113.xml

2025-12-06 14:24:49,175 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000113.txt
Evaluating 114/1075: BIOMD0000000114.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000114.txt
Evaluating 115/1075: BIOMD0000000115.xml

2025-12-06 14:24:51,551 - WARNING - Skipping BIOMD0000000116.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000115.txt
Evaluating 116/1075: BIOMD0000000116.xml
Evaluating 117/1075: BIOMD0000000117.xml

2025-12-06 14:24:52,876 - WARNING - Skipping BIOMD0000000118.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000117.txt
Evaluating 118/1075: BIOMD0000000118.xml
Evaluating 119/1075: BIOMD0000000119.xml

2025-12-06 14:24:54,081 - WARNING - Skipping BIOMD0000000120.xml - no results generated
2025-12-06 14:24:54,086 - WARNING - Skipping BIOMD0000000121.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000119.txt
Evaluating 120/1075: BIOMD0000000120.xml
Evaluating 121/1075: BIOMD0000000121.xml
Evaluating 122/1075: BIOMD0000000122.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000122.txt
Evaluating 123/1075: BIOMD0000000123.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000123.txt
Evaluating 124/1075: BIOMD0000000124.xml

2025-12-06 14:24:58,457 - WARNING - Skipping BIOMD0000000125.xml - no results generated
2025-12-06 14:24:58,464 - WARNING - Skipping BIOMD0000000126.xml - no results generated
2025-12-06 14:24:58,467 - WARNING - Skipping BIOMD0000000127.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000124.txt
Evaluating 125/1075: BIOMD0000000125.xml
Evaluating 126/1075: BIOMD0000000126.xml
Evaluating 127/1075: BIOMD0000000127.xml
Evaluating 128/1075: BIOMD0000000128.xml

2025-12-06 14:25:00,107 - WARNING - Skipping BIOMD0000000129.xml - no results generated
2025-12-06 14:25:00,110 - WARNING - Skipping BIOMD0000000130.xml - no results generated
2025-12-06 14:25:00,112 - WARNING - Skipping BIOMD0000000131.xml - no results generated
2025-12-06 14:25:00,114 - WARNING - Skipping BIOMD0000000132.xml - no results generated
2025-12-06 14:25:00,117 - WARNING - Skipping BIOMD0000000133.xml - no results generated
2025-12-06 14:25:00,119 - WARNING - Skipping BIOMD0000000134.xml - no results generated
2025-12-06 14:25:00,121 - WARNING - Skipping BIOMD0000000135.xml - no results generated
2025-12-06 14:25:00,124 - WARNING - Skipping BIOMD0000000136.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000128.txt
Evaluating 129/1075: BIOMD0000000129.xml
Evaluating 130/1075: BIOMD0000000130.xml
Evaluating 131/1075: BIOMD0000000131.xml
Evaluating 132/1075: BIOMD0000000132.xml
Evaluating 133/1075: BIOMD0000000133.xml
Evaluating 134/1075: BIOMD0000000134.xml
Evaluating 135/1075: BIOMD0000000135.xml
Evaluating 136/1075: BIOMD0000000136.xml
Evaluating 137/1075: BIOMD0000000137.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000137.txt
Evaluating 138/1075: BIOMD0000000138.xml

2025-12-06 14:25:03,621 - WARNING - Skipping BIOMD0000000139.xml - no results generated
2025-12-06 14:25:03,640 - WARNING - Skipping BIOMD0000000140.xml - no results generated
2025-12-06 14:25:03,643 - WARNING - Skipping BIOMD0000000141.xml - no results generated
2025-12-06 14:25:03,645 - WARNING - Skipping BIOMD0000000142.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000138.txt
Evaluating 139/1075: BIOMD0000000139.xml
Evaluating 140/1075: BIOMD0000000140.xml
Evaluating 141/1075: BIOMD0000000141.xml
Evaluating 142/1075: BIOMD0000000142.xml
Evaluating 143/1075: BIOMD0000000143.xml

2025-12-06 14:25:11,306 - WARNING - Skipping BIOMD0000000144.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000143.txt
Evaluating 144/1075: BIOMD0000000144.xml
Evaluating 145/1075: BIOMD0000000145.xml

2025-12-06 14:25:13,773 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000145.txt
Evaluating 146/1075: BIOMD0000000146.xml

2025-12-06 14:25:20,334 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:25:20,425 - WARNING - Skipping BIOMD0000000147.xml - no results generated
2025-12-06 14:25:20,429 - WARNING - Skipping BIOMD0000000148.xml - no results generated
2025-12-06 14:25:20,446 - WARNING - Skipping BIOMD0000000149.xml - no results generated
2025-12-06 14:25:20,450 - WARNING - Skipping BIOMD0000000150.xml - no results generated
2025-12-06 14:25:20,477 - WARNING - Skipping BIOMD0000000151.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000146.txt
Evaluating 147/1075: BIOMD0000000147.xml
Evaluating 148/1075: BIOMD0000000148.xml
Evaluating 149/1075: BIOMD0000000149.xml
Evaluating 150/1075: BIOMD0000000150.xml
Evaluating 151/1075: BIOMD0000000151.xml
Evaluating 152/1075: BIOMD0000000152.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000152.txt
Evaluating 153/1075: BIOMD0000000153.xml

2025-12-06 14:25:46,820 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:25:48,315 - WARNING - Skipping BIOMD0000000154.xml - no results generated
2025-12-06 14:25:48,319 - WARNING - Skipping BIOMD0000000155.xml - no results generated
2025-12-06 14:25:48,322 - WARNING - Skipping BIOMD0000000156.xml - no results generated
2025-12-06 14:25:48,325 - WARNING - Skipping BIOMD0000000157.xml - no results generated
2025-12-06 14:25:48,329 - WARNING - Skipping BIOMD0000000158.xml - no results generated
2025-12-06 14:25:48,333 - WARNING - Skipping BIOMD0000000159.xml - no results generated
2025-12-06 14:25:48,347 - WARNING - Skipping BIOMD0000000160.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000153.txt
Evaluating 154/1075: BIOMD0000000154.xml
Evaluating 155/1075: BIOMD0000000155.xml
Evaluating 156/1075: BIOMD0000000156.xml
Evaluating 157/1075: BIOMD0000000157.xml
Evaluating 158/1075: BIOMD0000000158.xml
Evaluating 159/1075: BIOMD0000000159.xml
Evaluating 160/1075: BIOMD0000000160.xml
Evaluating 161/1075: BIOMD0000000161.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000161.txt
Evaluating 162/1075: BIOMD0000000162.xml

2025-12-06 14:26:05,636 - WARNING - Skipping BIOMD0000000163.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000162.txt
Evaluating 163/1075: BIOMD0000000163.xml
Evaluating 164/1075: BIOMD0000000164.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000164.txt
Evaluating 165/1075: BIOMD0000000165.xml

2025-12-06 14:26:19,723 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000165.txt
Evaluating 166/1075: BIOMD0000000166.xml

2025-12-06 14:26:21,129 - WARNING - Skipping BIOMD0000000167.xml - no results generated
2025-12-06 14:26:21,135 - WARNING - Skipping BIOMD0000000168.xml - no results generated
2025-12-06 14:26:21,144 - WARNING - Skipping BIOMD0000000169.xml - no results generated
2025-12-06 14:26:21,151 - WARNING - Skipping BIOMD0000000170.xml - no results generated
2025-12-06 14:26:21,160 - WARNING - Skipping BIOMD0000000171.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000166.txt
Evaluating 167/1075: BIOMD0000000167.xml
Evaluating 168/1075: BIOMD0000000168.xml
Evaluating 169/1075: BIOMD0000000169.xml
Evaluating 170/1075: BIOMD0000000170.xml
Evaluating 171/1075: BIOMD0000000171.xml
Evaluating 172/1075: BIOMD0000000172.xml

2025-12-06 14:26:28,523 - WARNING - Skipping BIOMD0000000173.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000172.txt
Evaluating 173/1075: BIOMD0000000173.xml
Evaluating 174/1075: BIOMD0000000174.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000174.txt
Evaluating 175/1075: BIOMD0000000175.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000175.txt
Evaluating 176/1075: BIOMD0000000176.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000176.txt
Evaluating 177/1075: BIOMD0000000177.xml

2025-12-06 14:26:44,595 - WARNING - Skipping BIOMD0000000178.xml - no results generated
2025-12-06 14:26:44,601 - WARNING - Skipping BIOMD0000000179.xml - no results generated
2025-12-06 14:26:44,607 - WARNING - Skipping BIOMD0000000180.xml - no results generated
2025-12-06 14:26:44,614 - WARNING - Skipping BIOMD0000000181.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000177.txt
Evaluating 178/1075: BIOMD0000000178.xml
Evaluating 179/1075: BIOMD0000000179.xml
Evaluating 180/1075: BIOMD0000000180.xml
Evaluating 181/1075: BIOMD0000000181.xml
Evaluating 182/1075: BIOMD0000000182.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000182.txt
Evaluating 183/1075: BIOMD0000000183.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000183.txt
Evaluating 184/1075: BIOMD0000000184.xml

2025-12-06 14:27:31,163 - WARNING - Skipping BIOMD0000000185.xml - no results generated
2025-12-06 14:27:31,172 - WARNING - Skipping BIOMD0000000186.xml - no results generated
2025-12-06 14:27:31,180 - WARNING - Skipping BIOMD0000000187.xml - no results generated
2025-12-06 14:27:31,189 - WARNING - Skipping BIOMD0000000188.xml - no results generated
2025-12-06 14:27:31,198 - WARNING - Skipping BIOMD0000000189.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000184.txt
Evaluating 185/1075: BIOMD0000000185.xml
Evaluating 186/1075: BIOMD0000000186.xml
Evaluating 187/1075: BIOMD0000000187.xml
Evaluating 188/1075: BIOMD0000000188.xml
Evaluating 189/1075: BIOMD0000000189.xml
Evaluating 190/1075: BIOMD0000000190.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000190.txt
Evaluating 191/1075: BIOMD0000000191.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000191.txt
Evaluating 192/1075: BIOMD0000000192.xml

2025-12-06 14:27:39,613 - WARNING - Skipping BIOMD0000000193.xml - no results generated
2025-12-06 14:27:39,617 - WARNING - Skipping BIOMD0000000194.xml - no results generated
2025-12-06 14:27:39,628 - WARNING - Skipping BIOMD0000000195.xml - no results generated
2025-12-06 14:27:39,638 - WARNING - Skipping BIOMD0000000196.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000192.txt
Evaluating 193/1075: BIOMD0000000193.xml
Evaluating 194/1075: BIOMD0000000194.xml
Evaluating 195/1075: BIOMD0000000195.xml
Evaluating 196/1075: BIOMD0000000196.xml
Evaluating 197/1075: BIOMD0000000197.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000197.txt
Evaluating 198/1075: BIOMD0000000198.xml

2025-12-06 14:27:48,873 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000198.txt
Evaluating 199/1075: BIOMD0000000199.xml

2025-12-06 14:27:57,860 - WARNING - Skipping BIOMD0000000200.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000199.txt
Evaluating 200/1075: BIOMD0000000200.xml
Evaluating 201/1075: BIOMD0000000201.xml

2025-12-06 14:27:59,673 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000201.txt
Evaluating 202/1075: BIOMD0000000202.xml

2025-12-06 14:28:01,916 - WARNING - Skipping BIOMD0000000203.xml - no results generated
2025-12-06 14:28:01,922 - WARNING - Skipping BIOMD0000000204.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000202.txt
Evaluating 203/1075: BIOMD0000000203.xml
Evaluating 204/1075: BIOMD0000000204.xml
Evaluating 205/1075: BIOMD0000000205.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000205.txt
Evaluating 206/1075: BIOMD0000000206.xml

2025-12-06 14:28:28,854 - WARNING - Skipping BIOMD0000000207.xml - no results generated
2025-12-06 14:28:28,858 - WARNING - Skipping BIOMD0000000208.xml - no results generated
2025-12-06 14:28:28,867 - WARNING - Skipping BIOMD0000000209.xml - no results generated
2025-12-06 14:28:28,875 - WARNING - Skipping BIOMD0000000210.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000206.txt
Evaluating 207/1075: BIOMD0000000207.xml
Evaluating 208/1075: BIOMD0000000208.xml
Evaluating 209/1075: BIOMD0000000209.xml
Evaluating 210/1075: BIOMD0000000210.xml
Evaluating 211/1075: BIOMD0000000211.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000211.txt
Evaluating 212/1075: BIOMD0000000212.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000212.txt
Evaluating 213/1075: BIOMD0000000213.xml

2025-12-06 14:28:49,803 - WARNING - Skipping BIOMD0000000214.xml - no results generated
2025-12-06 14:28:49,809 - WARNING - Skipping BIOMD0000000215.xml - no results generated
2025-12-06 14:28:49,815 - WARNING - Skipping BIOMD0000000216.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000213.txt
Evaluating 214/1075: BIOMD0000000214.xml
Evaluating 215/1075: BIOMD0000000215.xml
Evaluating 216/1075: BIOMD0000000216.xml
Evaluating 217/1075: BIOMD0000000217.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000217.txt
Evaluating 218/1075: BIOMD0000000218.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000218.txt
Evaluating 219/1075: BIOMD0000000219.xml

2025-12-06 14:29:01,380 - WARNING - Skipping BIOMD0000000220.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000219.txt
Evaluating 220/1075: BIOMD0000000220.xml
Evaluating 221/1075: BIOMD0000000221.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000221.txt
Evaluating 222/1075: BIOMD0000000222.xml

2025-12-06 14:29:08,102 - WARNING - Skipping BIOMD0000000223.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000222.txt
Evaluating 223/1075: BIOMD0000000223.xml
Evaluating 224/1075: BIOMD0000000224.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000224.txt
Evaluating 225/1075: BIOMD0000000225.xml

2025-12-06 14:29:13,362 - WARNING - Skipping BIOMD0000000226.xml - no results generated
2025-12-06 14:29:13,413 - WARNING - Skipping BIOMD0000000227.xml - no results generated
2025-12-06 14:29:13,424 - WARNING - Skipping BIOMD0000000228.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000225.txt
Evaluating 226/1075: BIOMD0000000226.xml
Evaluating 227/1075: BIOMD0000000227.xml
Evaluating 228/1075: BIOMD0000000228.xml
Evaluating 229/1075: BIOMD0000000229.xml

2025-12-06 14:29:15,655 - WARNING - Skipping BIOMD0000000230.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000229.txt
Evaluating 230/1075: BIOMD0000000230.xml
Evaluating 231/1075: BIOMD0000000231.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000231.txt
Evaluating 232/1075: BIOMD0000000232.xml

2025-12-06 14:29:21,003 - WARNING - Skipping BIOMD0000000233.xml - no results generated
2025-12-06 14:29:21,007 - WARNING - Skipping BIOMD0000000234.xml - no results generated
2025-12-06 14:29:21,263 - WARNING - Skipping BIOMD0000000235.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000232.txt
Evaluating 233/1075: BIOMD0000000233.xml
Evaluating 234/1075: BIOMD0000000234.xml
Evaluating 235/1075: BIOMD0000000235.xml
Evaluating 236/1075: BIOMD0000000236.xml

2025-12-06 14:29:25,099 - WARNING - Skipping BIOMD0000000237.xml - no results generated
2025-12-06 14:29:25,103 - WARNING - Skipping BIOMD0000000238.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000236.txt
Evaluating 237/1075: BIOMD0000000237.xml
Evaluating 238/1075: BIOMD0000000238.xml
Evaluating 239/1075: BIOMD0000000239.xml

2025-12-06 14:29:39,844 - WARNING - Skipping BIOMD0000000240.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000239.txt
Evaluating 240/1075: BIOMD0000000240.xml
Evaluating 241/1075: BIOMD0000000241.xml

2025-12-06 14:29:42,787 - WARNING - Skipping BIOMD0000000242.xml - no results generated
2025-12-06 14:29:42,796 - WARNING - Skipping BIOMD0000000243.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000241.txt
Evaluating 242/1075: BIOMD0000000242.xml
Evaluating 243/1075: BIOMD0000000243.xml
Evaluating 244/1075: BIOMD0000000244.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000244.txt
Evaluating 245/1075: BIOMD0000000245.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000245.txt
Evaluating 246/1075: BIOMD0000000246.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000246.txt
Evaluating 247/1075: BIOMD0000000247.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000247.txt
Evaluating 248/1075: BIOMD0000000248.xml

2025-12-06 14:30:09,493 - WARNING - Skipping BIOMD0000000249.xml - no results generated
2025-12-06 14:30:09,513 - WARNING - Skipping BIOMD0000000250.xml - no results generated
2025-12-06 14:30:09,520 - WARNING - Skipping BIOMD0000000251.xml - no results generated
2025-12-06 14:30:09,523 - WARNING - Skipping BIOMD0000000252.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000248.txt
Evaluating 249/1075: BIOMD0000000249.xml
Evaluating 250/1075: BIOMD0000000250.xml
Evaluating 251/1075: BIOMD0000000251.xml
Evaluating 252/1075: BIOMD0000000252.xml
Evaluating 253/1075: BIOMD0000000253.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000253.txt
Evaluating 254/1075: BIOMD0000000254.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000254.txt
Evaluating 255/1075: BIOMD0000000255.xml

2025-12-06 14:30:22,034 - WARNING - Skipping BIOMD0000000256.xml - no results generated
2025-12-06 14:30:22,037 - WARNING - Skipping BIOMD0000000257.xml - no results generated
2025-12-06 14:30:22,041 - WARNING - Skipping BIOMD0000000258.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000255.txt
Evaluating 256/1075: BIOMD0000000256.xml
Evaluating 257/1075: BIOMD0000000257.xml
Evaluating 258/1075: BIOMD0000000258.xml
Evaluating 259/1075: BIOMD0000000259.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000259.txt
Evaluating 260/1075: BIOMD0000000260.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000260.txt
Evaluating 261/1075: BIOMD0000000261.xml

2025-12-06 14:30:49,074 - WARNING - Skipping BIOMD0000000262.xml - no results generated
2025-12-06 14:30:49,081 - WARNING - Skipping BIOMD0000000263.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000261.txt
Evaluating 262/1075: BIOMD0000000262.xml
Evaluating 263/1075: BIOMD0000000263.xml
Evaluating 264/1075: BIOMD0000000264.xml

2025-12-06 14:30:52,193 - WARNING - Skipping BIOMD0000000265.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000264.txt
Evaluating 265/1075: BIOMD0000000265.xml
Evaluating 266/1075: BIOMD0000000266.xml

2025-12-06 14:30:54,846 - WARNING - Skipping BIOMD0000000267.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000266.txt
Evaluating 267/1075: BIOMD0000000267.xml
Evaluating 268/1075: BIOMD0000000268.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000268.txt
Evaluating 269/1075: BIOMD0000000269.xml

2025-12-06 14:31:06,726 - WARNING - Skipping BIOMD0000000270.xml - no results generated
2025-12-06 14:31:06,731 - WARNING - Skipping BIOMD0000000271.xml - no results generated
2025-12-06 14:31:06,736 - WARNING - Skipping BIOMD0000000272.xml - no results generated
2025-12-06 14:31:06,753 - WARNING - Skipping BIOMD0000000273.xml - no results generated
2025-12-06 14:31:06,757 - WARNING - Skipping BIOMD0000000274.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000269.txt
Evaluating 270/1075: BIOMD0000000270.xml
Evaluating 271/1075: BIOMD0000000271.xml
Evaluating 272/1075: BIOMD0000000272.xml
Evaluating 273/1075: BIOMD0000000273.xml
Evaluating 274/1075: BIOMD0000000274.xml
Evaluating 275/1075: BIOMD0000000275.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000275.txt
Evaluating 276/1075: BIOMD0000000276.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000276.txt
Evaluating 277/1075: BIOMD0000000277.xml

2025-12-06 14:31:10,861 - WARNING - Skipping BIOMD0000000278.xml - no results generated
2025-12-06 14:31:10,864 - WARNING - Skipping BIOMD0000000279.xml - no results generated
2025-12-06 14:31:10,867 - WARNING - Skipping BIOMD0000000280.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000277.txt
Evaluating 278/1075: BIOMD0000000278.xml
Evaluating 279/1075: BIOMD0000000279.xml
Evaluating 280/1075: BIOMD0000000280.xml
Evaluating 281/1075: BIOMD0000000281.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000281.txt
Evaluating 282/1075: BIOMD0000000282.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000282.txt
Evaluating 283/1075: BIOMD0000000283.xml

2025-12-06 14:31:26,910 - WARNING - Skipping BIOMD0000000284.xml - no results generated
2025-12-06 14:31:26,925 - WARNING - Skipping BIOMD0000000285.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000283.txt
Evaluating 284/1075: BIOMD0000000284.xml
Evaluating 285/1075: BIOMD0000000285.xml
Evaluating 286/1075: BIOMD0000000286.xml

2025-12-06 14:31:28,616 - WARNING - Skipping BIOMD0000000287.xml - no results generated
2025-12-06 14:31:28,625 - WARNING - Skipping BIOMD0000000288.xml - no results generated
2025-12-06 14:31:28,629 - WARNING - Skipping BIOMD0000000289.xml - no results generated
2025-12-06 14:31:28,633 - WARNING - Skipping BIOMD0000000290.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000286.txt
Evaluating 287/1075: BIOMD0000000287.xml
Evaluating 288/1075: BIOMD0000000288.xml
Evaluating 289/1075: BIOMD0000000289.xml
Evaluating 290/1075: BIOMD0000000290.xml
Evaluating 291/1075: BIOMD0000000291.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000291.txt
Evaluating 292/1075: BIOMD0000000292.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000292.txt
Evaluating 293/1075: BIOMD0000000293.xml

2025-12-06 14:31:37,403 - WARNING - Skipping BIOMD0000000294.xml - no results generated
2025-12-06 14:31:37,407 - WARNING - Skipping BIOMD0000000295.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000293.txt
Evaluating 294/1075: BIOMD0000000294.xml
Evaluating 295/1075: BIOMD0000000295.xml
Evaluating 296/1075: BIOMD0000000296.xml

2025-12-06 14:31:39,381 - WARNING - Skipping BIOMD0000000297.xml - no results generated
2025-12-06 14:31:39,386 - WARNING - Skipping BIOMD0000000298.xml - no results generated
2025-12-06 14:31:39,389 - WARNING - Skipping BIOMD0000000299.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000296.txt
Evaluating 297/1075: BIOMD0000000297.xml
Evaluating 298/1075: BIOMD0000000298.xml
Evaluating 299/1075: BIOMD0000000299.xml
Evaluating 300/1075: BIOMD0000000300.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000300.txt
Evaluating 301/1075: BIOMD0000000301.xml

2025-12-06 14:31:41,771 - WARNING - Skipping BIOMD0000000302.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000301.txt
Evaluating 302/1075: BIOMD0000000302.xml
Evaluating 303/1075: BIOMD0000000303.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000303.txt
Evaluating 304/1075: BIOMD0000000304.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000304.txt
Evaluating 305/1075: BIOMD0000000305.xml

2025-12-06 14:31:59,455 - WARNING - Skipping BIOMD0000000306.xml - no results generated
2025-12-06 14:31:59,459 - WARNING - Skipping BIOMD0000000307.xml - no results generated
2025-12-06 14:31:59,464 - WARNING - Skipping BIOMD0000000308.xml - no results generated
2025-12-06 14:31:59,468 - WARNING - Skipping BIOMD0000000309.xml - no results generated
2025-12-06 14:31:59,473 - WARNING - Skipping BIOMD0000000310.xml - no results generated
2025-12-06 14:31:59,476 - WARNING - Skipping BIOMD0000000311.xml - no results generated
2025-12-06 14:31:59,481 - WARNING - Skipping BIOMD0000000312.xml - no results generated
2025-12-06 14:31:59,489 - WARNING - Skipping BIOMD0000000313.xml - no results generated
2025-12-06 14:31:59,497 - WARNING - Skipping BIOMD0000000314.xml - no results generated
2025-12-06 14:31:59,511 - WARNING - Skipping BIOMD0000000315.xml - no results generated
2025-12-06 14:31:59,516 - WARNING - Skipping BIOMD0000000316.xml - no results generated
2025-12-06 14:31:59,521 - WARNING - Skipping BIOMD0000000317.xml - no results generated
2025-12-06 14:31:59,532 - WARNING - Skipping BIOMD0000000318.xml - no results generated
2025-12-06 14:31:59,537 - WARNING - Skipping BIOMD0000000319.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000305.txt
Evaluating 306/1075: BIOMD0000000306.xml
Evaluating 307/1075: BIOMD0000000307.xml
Evaluating 308/1075: BIOMD0000000308.xml
Evaluating 309/1075: BIOMD0000000309.xml
Evaluating 310/1075: BIOMD0000000310.xml
Evaluating 311/1075: BIOMD0000000311.xml
Evaluating 312/1075: BIOMD0000000312.xml
Evaluating 313/1075: BIOMD0000000313.xml
Evaluating 314/1075: BIOMD0000000314.xml
Evaluating 315/1075: BIOMD0000000315.xml
Evaluating 316/1075: BIOMD0000000316.xml
Evaluating 317/1075: BIOMD0000000317.xml
Evaluating 318/1075: BIOMD0000000318.xml
Evaluating 319/1075: BIOMD0000000319.xml
Evaluating 320/1075: BIOMD0000000320.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000320.txt
Evaluating 321/1075: BIOMD0000000321.xml

2025-12-06 14:32:03,762 - WARNING - Skipping BIOMD0000000322.xml - no results generated
2025-12-06 14:32:03,767 - WARNING - Skipping BIOMD0000000323.xml - no results generated
2025-12-06 14:32:03,771 - WARNING - Skipping BIOMD0000000324.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000321.txt
Evaluating 322/1075: BIOMD0000000322.xml
Evaluating 323/1075: BIOMD0000000323.xml
Evaluating 324/1075: BIOMD0000000324.xml
Evaluating 325/1075: BIOMD0000000325.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000325.txt
Evaluating 326/1075: BIOMD0000000326.xml

2025-12-06 14:32:20,808 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000326.txt
Evaluating 327/1075: BIOMD0000000327.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000327.txt
Evaluating 328/1075: BIOMD0000000328.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000328.txt
Evaluating 329/1075: BIOMD0000000329.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000329.txt
Evaluating 330/1075: BIOMD0000000330.xml

2025-12-06 14:32:30,536 - WARNING - Skipping BIOMD0000000331.xml - no results generated
2025-12-06 14:32:30,563 - WARNING - Skipping BIOMD0000000332.xml - no results generated
2025-12-06 14:32:30,582 - WARNING - Skipping BIOMD0000000333.xml - no results generated
2025-12-06 14:32:30,610 - WARNING - Skipping BIOMD0000000334.xml - no results generated
2025-12-06 14:32:30,620 - WARNING - Skipping BIOMD0000000335.xml - no results generated
2025-12-06 14:32:30,628 - WARNING - Skipping BIOMD0000000336.xml - no results generated
2025-12-06 14:32:30,631 - WARNING - Skipping BIOMD0000000337.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000330.txt
Evaluating 331/1075: BIOMD0000000331.xml
Evaluating 332/1075: BIOMD0000000332.xml
Evaluating 333/1075: BIOMD0000000333.xml
Evaluating 334/1075: BIOMD0000000334.xml
Evaluating 335/1075: BIOMD0000000335.xml
Evaluating 336/1075: BIOMD0000000336.xml
Evaluating 337/1075: BIOMD0000000337.xml
Evaluating 338/1075: BIOMD0000000338.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000338.txt
Evaluating 339/1075: BIOMD0000000339.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000339.txt
Evaluating 340/1075: BIOMD0000000340.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000340.txt
Evaluating 341/1075: BIOMD0000000341.xml

2025-12-06 14:32:50,352 - WARNING - Skipping BIOMD0000000342.xml - no results generated
2025-12-06 14:32:50,356 - WARNING - Skipping BIOMD0000000343.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000341.txt
Evaluating 342/1075: BIOMD0000000342.xml
Evaluating 343/1075: BIOMD0000000343.xml
Evaluating 344/1075: BIOMD0000000344.xml

2025-12-06 14:32:51,633 - WARNING - Skipping BIOMD0000000345.xml - no results generated
2025-12-06 14:32:51,635 - WARNING - Skipping BIOMD0000000346.xml - no results generated
2025-12-06 14:32:51,649 - WARNING - Skipping BIOMD0000000347.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000344.txt
Evaluating 345/1075: BIOMD0000000345.xml
Evaluating 346/1075: BIOMD0000000346.xml
Evaluating 347/1075: BIOMD0000000347.xml
Evaluating 348/1075: BIOMD0000000348.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000348.txt
Evaluating 349/1075: BIOMD0000000349.xml

2025-12-06 14:32:58,387 - WARNING - Skipping BIOMD0000000350.xml - no results generated
2025-12-06 14:32:58,393 - WARNING - Skipping BIOMD0000000351.xml - no results generated
2025-12-06 14:32:58,400 - WARNING - Skipping BIOMD0000000352.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000349.txt
Evaluating 350/1075: BIOMD0000000350.xml
Evaluating 351/1075: BIOMD0000000351.xml
Evaluating 352/1075: BIOMD0000000352.xml
Evaluating 353/1075: BIOMD0000000353.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000353.txt
Evaluating 354/1075: BIOMD0000000354.xml

2025-12-06 14:33:05,514 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000354.txt
Evaluating 355/1075: BIOMD0000000355.xml

2025-12-06 14:33:10,046 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:33:10,077 - WARNING - Skipping BIOMD0000000356.xml - no results generated
2025-12-06 14:33:10,082 - WARNING - Skipping BIOMD0000000357.xml - no results generated
2025-12-06 14:33:10,087 - WARNING - Skipping BIOMD0000000358.xml - no results generated
2025-12-06 14:33:10,091 - WARNING - Skipping BIOMD0000000359.xml - no results generated
2025-12-06 14:33:10,096 - WARNING - Skipping BIOMD0000000360.xml - no results generated
2025-12-06 14:33:10,100 - WARNING - Skipping BIOMD0000000361.xml - no results generated
2025-12-06 14:33:10,112 - WARNING - Skipping BIOMD0000000362.xml - no results generated
2025-12-06 14:33:10,115 - WARNING - Skipping BIOMD0000000363.xml - no results generated
2025-12-06 14:33:10,120 - WARNING - Skipping BIOMD0000000364.xml - no results generated
2025-12-06 14:33:10,129 - WARNING - Skipping BIOMD0000000365.xml - no results generated
2025-12-06 14:33:10,133 - WARNING - Skipping BIOMD0000000366.xml - no results generated
2025-12-06 14:33:10,136 - WARNING - Skipping BIOMD0000000367.xml - no results generated
2025-12-06 14:33:10,138 - WARNING - Skipping BIOMD0000000368.xml - no results generated
2025-12-06 14:33:10,140 - WARNING - Skipping BIOMD0000000369.xml - no results generated
2025-12-06 14:33:10,152 - WARNING - Skipping BIOMD0000000370.xml - no results generated
2025-12-06 14:33:10,155 - WARNING - Skipping BIOMD0000000371.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000355.txt
Evaluating 356/1075: BIOMD0000000356.xml
Evaluating 357/1075: BIOMD0000000357.xml
Evaluating 358/1075: BIOMD0000000358.xml
Evaluating 359/1075: BIOMD0000000359.xml
Evaluating 360/1075: BIOMD0000000360.xml
Evaluating 361/1075: BIOMD0000000361.xml
Evaluating 362/1075: BIOMD0000000362.xml
Evaluating 363/1075: BIOMD0000000363.xml
Evaluating 364/1075: BIOMD0000000364.xml
Evaluating 365/1075: BIOMD0000000365.xml
Evaluating 366/1075: BIOMD0000000366.xml
Evaluating 367/1075: BIOMD0000000367.xml
Evaluating 368/1075: BIOMD0000000368.xml
Evaluating 369/1075: BIOMD0000000369.xml
Evaluating 370/1075: BIOMD0000000370.xml
Evaluating 371/1075: BIOMD0000000371.xml
Evaluating 372/1075: BIOMD0000000372.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000372.txt
Evaluating 373/1075: BIOMD0000000373.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000373.txt
Evaluating 374/1075: BIOMD0000000374.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000374.txt
Evaluating 375/1075: BIOMD0000000375.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000375.txt
Evaluating 376/1075: BIOMD0000000376.xml

2025-12-06 14:33:20,439 - WARNING - Skipping BIOMD0000000377.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000376.txt
Evaluating 377/1075: BIOMD0000000377.xml
Evaluating 378/1075: BIOMD0000000378.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000378.txt
Evaluating 379/1075: BIOMD0000000379.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000379.txt
Evaluating 380/1075: BIOMD0000000380.xml

2025-12-06 14:33:29,133 - WARNING - Skipping BIOMD0000000381.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000380.txt
Evaluating 381/1075: BIOMD0000000381.xml
Evaluating 382/1075: BIOMD0000000382.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000382.txt
Evaluating 383/1075: BIOMD0000000383.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000383.txt
Evaluating 384/1075: BIOMD0000000384.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000384.txt
Evaluating 385/1075: BIOMD0000000385.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000385.txt
Evaluating 386/1075: BIOMD0000000386.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000386.txt
Evaluating 387/1075: BIOMD0000000387.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000387.txt
Evaluating 388/1075: BIOMD0000000388.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000388.txt
Evaluating 389/1075: BIOMD0000000389.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000389.txt
Evaluating 390/1075: BIOMD0000000390.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000390.txt
Evaluating 391/1075: BIOMD0000000391.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000391.txt
Evaluating 392/1075: BIOMD0000000392.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000392.txt
Evaluating 393/1075: BIOMD0000000393.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000393.txt
Evaluating 394/1075: BIOMD0000000394.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000394.txt
Evaluating 395/1075: BIOMD0000000395.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000395.txt
Evaluating 396/1075: BIOMD0000000396.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000396.txt
Evaluating 397/1075: BIOMD0000000397.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000397.txt
Evaluating 398/1075: BIOMD0000000398.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000398.txt
Evaluating 399/1075: BIOMD0000000399.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000399.txt
Evaluating 400/1075: BIOMD0000000400.xml

2025-12-06 14:34:50,696 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:34:50,951 - WARNING - Skipping BIOMD0000000401.xml - no results generated
2025-12-06 14:34:50,954 - WARNING - Skipping BIOMD0000000402.xml - no results generated
2025-12-06 14:34:50,958 - WARNING - Skipping BIOMD0000000403.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000400.txt
Evaluating 401/1075: BIOMD0000000401.xml
Evaluating 402/1075: BIOMD0000000402.xml
Evaluating 403/1075: BIOMD0000000403.xml
Evaluating 404/1075: BIOMD0000000404.xml

2025-12-06 14:34:56,342 - WARNING - Skipping BIOMD0000000405.xml - no results generated
2025-12-06 14:34:56,358 - WARNING - Skipping BIOMD0000000406.xml - no results generated
2025-12-06 14:34:56,379 - WARNING - Skipping BIOMD0000000407.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000404.txt
Evaluating 405/1075: BIOMD0000000405.xml
Evaluating 406/1075: BIOMD0000000406.xml
Evaluating 407/1075: BIOMD0000000407.xml
Evaluating 408/1075: BIOMD0000000408.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000408.txt
Evaluating 409/1075: BIOMD0000000409.xml

2025-12-06 14:35:00,025 - WARNING - Skipping BIOMD0000000410.xml - no results generated
2025-12-06 14:35:00,036 - WARNING - Skipping BIOMD0000000411.xml - no results generated
2025-12-06 14:35:00,101 - WARNING - Skipping BIOMD0000000412.xml - no results generated
2025-12-06 14:35:00,105 - WARNING - Skipping BIOMD0000000413.xml - no results generated
2025-12-06 14:35:00,108 - WARNING - Skipping BIOMD0000000414.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000409.txt
Evaluating 410/1075: BIOMD0000000410.xml
Evaluating 411/1075: BIOMD0000000411.xml
Evaluating 412/1075: BIOMD0000000412.xml
Evaluating 413/1075: BIOMD0000000413.xml
Evaluating 414/1075: BIOMD0000000414.xml
Evaluating 415/1075: BIOMD0000000415.xml

2025-12-06 14:35:01,844 - WARNING - Skipping BIOMD0000000416.xml - no results generated
2025-12-06 14:35:01,847 - WARNING - Skipping BIOMD0000000417.xml - no results generated
2025-12-06 14:35:01,850 - WARNING - Skipping BIOMD0000000418.xml - no results generated
2025-12-06 14:35:01,853 - WARNING - Skipping BIOMD0000000419.xml - no results generated
2025-12-06 14:35:01,856 - WARNING - Skipping BIOMD0000000420.xml - no results generated
2025-12-06 14:35:01,859 - WARNING - Skipping BIOMD0000000421.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000415.txt
Evaluating 416/1075: BIOMD0000000416.xml
Evaluating 417/1075: BIOMD0000000417.xml
Evaluating 418/1075: BIOMD0000000418.xml
Evaluating 419/1075: BIOMD0000000419.xml
Evaluating 420/1075: BIOMD0000000420.xml
Evaluating 421/1075: BIOMD0000000421.xml
Evaluating 422/1075: BIOMD0000000422.xml

2025-12-06 14:35:12,813 - WARNING - Skipping BIOMD0000000423.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000422.txt
Evaluating 423/1075: BIOMD0000000423.xml
Evaluating 424/1075: BIOMD0000000424.xml

2025-12-06 14:35:17,758 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:35:17,964 - WARNING - Skipping BIOMD0000000425.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000424.txt
Evaluating 425/1075: BIOMD0000000425.xml
Evaluating 426/1075: BIOMD0000000426.xml

2025-12-06 14:35:27,860 - WARNING - Skipping BIOMD0000000427.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000426.txt
Evaluating 427/1075: BIOMD0000000427.xml
Evaluating 428/1075: BIOMD0000000428.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000428.txt
Evaluating 429/1075: BIOMD0000000429.xml

2025-12-06 14:35:37,149 - WARNING - Skipping BIOMD0000000430.xml - no results generated
2025-12-06 14:35:37,165 - WARNING - Skipping BIOMD0000000431.xml - no results generated
2025-12-06 14:35:37,178 - WARNING - Skipping BIOMD0000000432.xml - no results generated
2025-12-06 14:35:37,193 - WARNING - Skipping BIOMD0000000433.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000429.txt
Evaluating 430/1075: BIOMD0000000430.xml
Evaluating 431/1075: BIOMD0000000431.xml
Evaluating 432/1075: BIOMD0000000432.xml
Evaluating 433/1075: BIOMD0000000433.xml
Evaluating 434/1075: BIOMD0000000434.xml

2025-12-06 14:35:41,156 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 14:35:41,181 - WARNING - Skipping BIOMD0000000435.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000434.txt
Evaluating 435/1075: BIOMD0000000435.xml
Evaluating 436/1075: BIOMD0000000436.xml

2025-12-06 14:35:44,282 - WARNING - Skipping BIOMD0000000437.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000436.txt
Evaluating 437/1075: BIOMD0000000437.xml
Evaluating 438/1075: BIOMD0000000438.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000438.txt
Evaluating 439/1075: BIOMD0000000439.xml

2025-12-06 14:35:53,921 - WARNING - Skipping BIOMD0000000440.xml - no results generated
2025-12-06 14:35:53,932 - WARNING - Skipping BIOMD0000000441.xml - no results generated
2025-12-06 14:35:53,942 - WARNING - Skipping BIOMD0000000442.xml - no results generated
2025-12-06 14:35:53,961 - WARNING - Skipping BIOMD0000000443.xml - no results generated
2025-12-06 14:35:53,980 - WARNING - Skipping BIOMD0000000444.xml - no results generated
2025-12-06 14:35:54,025 - WARNING - Skipping BIOMD0000000445.xml - no results generated
2025-12-06 14:35:54,039 - WARNING - Skipping BIOMD0000000446.xml - no results generated
2025-12-06 14:35:54,053 - WARNING - Skipping BIOMD0000000447.xml - no results generated
2025-12-06 14:35:54,068 - WARNING - Skipping BIOMD0000000448.xml - no results generated
2025-12-06 14:35:54,082 - WARNING - Skipping BIOMD0000000449.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000439.txt
Evaluating 440/1075: BIOMD0000000440.xml
Evaluating 441/1075: BIOMD0000000441.xml
Evaluating 442/1075: BIOMD0000000442.xml
Evaluating 443/1075: BIOMD0000000443.xml
Evaluating 444/1075: BIOMD0000000444.xml
Evaluating 445/1075: BIOMD0000000445.xml
Evaluating 446/1075: BIOMD0000000446.xml
Evaluating 447/1075: BIOMD0000000447.xml
Evaluating 448/1075: BIOMD0000000448.xml
Evaluating 449/1075: BIOMD0000000449.xml
Evaluating 450/1075: BIOMD0000000450.xml

2025-12-06 14:36:08,399 - WARNING - Skipping BIOMD0000000451.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000450.txt
Evaluating 451/1075: BIOMD0000000451.xml
Evaluating 452/1075: BIOMD0000000452.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000452.txt
Evaluating 453/1075: BIOMD0000000453.xml

2025-12-06 14:36:28,590 - WARNING - Skipping BIOMD0000000454.xml - no results generated
2025-12-06 14:36:28,595 - WARNING - Skipping BIOMD0000000455.xml - no results generated
2025-12-06 14:36:28,600 - WARNING - Skipping BIOMD0000000456.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000453.txt
Evaluating 454/1075: BIOMD0000000454.xml
Evaluating 455/1075: BIOMD0000000455.xml
Evaluating 456/1075: BIOMD0000000456.xml
Evaluating 457/1075: BIOMD0000000457.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000457.txt
Evaluating 458/1075: BIOMD0000000458.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000458.txt
Evaluating 459/1075: BIOMD0000000459.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000459.txt
Evaluating 460/1075: BIOMD0000000460.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000460.txt
Evaluating 461/1075: BIOMD0000000461.xml

2025-12-06 14:38:45,070 - WARNING - Skipping BIOMD0000000462.xml - no results generated
2025-12-06 14:38:45,098 - WARNING - Skipping BIOMD0000000463.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000461.txt
Evaluating 462/1075: BIOMD0000000462.xml
Evaluating 463/1075: BIOMD0000000463.xml
Evaluating 464/1075: BIOMD0000000464.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000464.txt
Evaluating 465/1075: BIOMD0000000465.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000465.txt
Evaluating 466/1075: BIOMD0000000466.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000466.txt
Evaluating 467/1075: BIOMD0000000467.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000467.txt
Evaluating 468/1075: BIOMD0000000468.xml

2025-12-06 14:39:08,590 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000468.txt
Evaluating 469/1075: BIOMD0000000469.xml

2025-12-06 14:42:56,101 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000469.txt
Evaluating 470/1075: BIOMD0000000470.xml

2025-12-06 14:46:25,414 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000470.txt
Evaluating 471/1075: BIOMD0000000471.xml

2025-12-06 14:49:15,712 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000471.txt
Evaluating 472/1075: BIOMD0000000472.xml

2025-12-06 14:52:05,083 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000472.txt
Evaluating 473/1075: BIOMD0000000473.xml

2025-12-06 14:55:29,439 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000473.txt
Evaluating 474/1075: BIOMD0000000474.xml

2025-12-06 14:55:48,605 - WARNING - Skipping BIOMD0000000475.xml - no results generated
2025-12-06 14:55:48,619 - WARNING - Skipping BIOMD0000000476.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000474.txt
Evaluating 475/1075: BIOMD0000000475.xml
Evaluating 476/1075: BIOMD0000000476.xml
Evaluating 477/1075: BIOMD0000000477.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000477.txt
Evaluating 478/1075: BIOMD0000000478.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000478.txt
Evaluating 479/1075: BIOMD0000000479.xml

2025-12-06 14:56:21,604 - WARNING - Skipping BIOMD0000000480.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000479.txt
Evaluating 480/1075: BIOMD0000000480.xml
Evaluating 481/1075: BIOMD0000000481.xml

2025-12-06 14:56:23,774 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000481.txt
Evaluating 482/1075: BIOMD0000000482.xml

2025-12-06 14:56:26,789 - WARNING - Skipping BIOMD0000000483.xml - no results generated
2025-12-06 14:56:26,792 - WARNING - Skipping BIOMD0000000484.xml - no results generated
2025-12-06 14:56:26,795 - WARNING - Skipping BIOMD0000000485.xml - no results generated
2025-12-06 14:56:26,797 - WARNING - Skipping BIOMD0000000486.xml - no results generated
2025-12-06 14:56:26,800 - WARNING - Skipping BIOMD0000000487.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000482.txt
Evaluating 483/1075: BIOMD0000000483.xml
Evaluating 484/1075: BIOMD0000000484.xml
Evaluating 485/1075: BIOMD0000000485.xml
Evaluating 486/1075: BIOMD0000000486.xml
Evaluating 487/1075: BIOMD0000000487.xml
Evaluating 488/1075: BIOMD0000000488.xml

2025-12-06 14:56:29,006 - WARNING - Skipping BIOMD0000000489.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000488.txt
Evaluating 489/1075: BIOMD0000000489.xml
Evaluating 490/1075: BIOMD0000000490.xml

2025-12-06 14:56:33,282 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000490.txt
Evaluating 491/1075: BIOMD0000000491.xml

2025-12-06 14:56:36,887 - WARNING - Skipping BIOMD0000000492.xml - no results generated
2025-12-06 14:56:36,891 - WARNING - Skipping BIOMD0000000493.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000491.txt
Evaluating 492/1075: BIOMD0000000492.xml
Evaluating 493/1075: BIOMD0000000493.xml
Evaluating 494/1075: BIOMD0000000494.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000494.txt
Evaluating 495/1075: BIOMD0000000495.xml

2025-12-06 14:56:45,553 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000495.txt
Evaluating 496/1075: BIOMD0000000496.xml

2025-12-06 14:59:07,890 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000496.txt
Evaluating 497/1075: BIOMD0000000497.xml

2025-12-06 15:01:40,602 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000497.txt
Evaluating 498/1075: BIOMD0000000498.xml

2025-12-06 15:01:46,522 - WARNING - Skipping BIOMD0000000499.xml - no results generated
2025-12-06 15:01:46,533 - WARNING - Skipping BIOMD0000000500.xml - no results generated
2025-12-06 15:01:46,572 - WARNING - Skipping BIOMD0000000501.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000498.txt
Evaluating 499/1075: BIOMD0000000499.xml
Evaluating 500/1075: BIOMD0000000500.xml
Evaluating 501/1075: BIOMD0000000501.xml
Evaluating 502/1075: BIOMD0000000502.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000502.txt
Evaluating 503/1075: BIOMD0000000503.xml

2025-12-06 15:02:02,076 - WARNING - Skipping BIOMD0000000504.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000503.txt
Evaluating 504/1075: BIOMD0000000504.xml
Evaluating 505/1075: BIOMD0000000505.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000505.txt
Evaluating 506/1075: BIOMD0000000506.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000506.txt
Evaluating 507/1075: BIOMD0000000507.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000507.txt
Evaluating 508/1075: BIOMD0000000508.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000508.txt
Evaluating 509/1075: BIOMD0000000509.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000509.txt
Evaluating 510/1075: BIOMD0000000510.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000510.txt
Evaluating 511/1075: BIOMD0000000511.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000511.txt
Evaluating 512/1075: BIOMD0000000512.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000512.txt
Evaluating 513/1075: BIOMD0000000513.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000513.txt
Evaluating 514/1075: BIOMD0000000514.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000514.txt
Evaluating 515/1075: BIOMD0000000515.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000515.txt
Evaluating 516/1075: BIOMD0000000516.xml

2025-12-06 15:03:49,985 - WARNING - Skipping BIOMD0000000517.xml - no results generated
2025-12-06 15:03:49,992 - WARNING - Skipping BIOMD0000000518.xml - no results generated
2025-12-06 15:03:49,997 - WARNING - Skipping BIOMD0000000519.xml - no results generated
2025-12-06 15:03:50,001 - WARNING - Skipping BIOMD0000000520.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000516.txt
Evaluating 517/1075: BIOMD0000000517.xml
Evaluating 518/1075: BIOMD0000000518.xml
Evaluating 519/1075: BIOMD0000000519.xml
Evaluating 520/1075: BIOMD0000000520.xml
Evaluating 521/1075: BIOMD0000000521.xml

2025-12-06 15:03:52,601 - WARNING - Skipping BIOMD0000000522.xml - no results generated
2025-12-06 15:03:52,608 - WARNING - Skipping BIOMD0000000523.xml - no results generated
2025-12-06 15:03:52,616 - WARNING - Skipping BIOMD0000000524.xml - no results generated
2025-12-06 15:03:52,624 - WARNING - Skipping BIOMD0000000525.xml - no results generated
2025-12-06 15:03:52,633 - WARNING - Skipping BIOMD0000000526.xml - no results generated
2025-12-06 15:03:52,636 - WARNING - Skipping BIOMD0000000527.xml - no results generated
2025-12-06 15:03:52,643 - WARNING - Skipping BIOMD0000000528.xml - no results generated
2025-12-06 15:03:52,650 - WARNING - Skipping BIOMD0000000529.xml - no results generated
2025-12-06 15:03:52,659 - WARNING - Skipping BIOMD0000000530.xml - no results generated
2025-12-06 15:03:52,661 - WARNING - Skipping BIOMD0000000531.xml - no results generated
2025-12-06 15:03:52,666 - WARNING - Skipping BIOMD0000000532.xml - no results generated
2025-12-06 15:03:52,670 - WARNING - Skipping BIOMD0000000533.xml - no results generated
2025-12-06 15:03:52,701 - WARNING - Skipping BIOMD0000000534.xml - no results generated
2025-12-06 15:03:52,727 - WARNING - Skipping BIOMD0000000535.xml - no results generated
2025-12-06 15:03:52,755 - WARNING - Skipping BIOMD0000000536.xml - no results generated
2025-12-06 15:03:52,784 - WARNING - Skipping BIOMD0000000537.xml - no results generated
2025-12-06 15:03:52,788 - WARNING - Skipping BIOMD0000000538.xml - no results generated
2025-12-06 15:03:52,794 - WARNING - Skipping BIOMD0000000539.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000521.txt
Evaluating 522/1075: BIOMD0000000522.xml
Evaluating 523/1075: BIOMD0000000523.xml
Evaluating 524/1075: BIOMD0000000524.xml
Evaluating 525/1075: BIOMD0000000525.xml
Evaluating 526/1075: BIOMD0000000526.xml
Evaluating 527/1075: BIOMD0000000527.xml
Evaluating 528/1075: BIOMD0000000528.xml
Evaluating 529/1075: BIOMD0000000529.xml
Evaluating 530/1075: BIOMD0000000530.xml
Evaluating 531/1075: BIOMD0000000531.xml
Evaluating 532/1075: BIOMD0000000532.xml
Evaluating 533/1075: BIOMD0000000533.xml
Evaluating 534/1075: BIOMD0000000534.xml
Evaluating 535/1075: BIOMD0000000535.xml
Evaluating 536/1075: BIOMD0000000536.xml
Evaluating 537/1075: BIOMD0000000537.xml
Evaluating 538/1075: BIOMD0000000538.xml
Evaluating 539/1075: BIOMD0000000539.xml
Evaluating 540/1075: BIOMD0000000540.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000540.txt
Evaluating 541/1075: BIOMD0000000541.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000541.txt
Evaluating 542/1075: BIOMD0000000542.xml

2025-12-06 15:04:01,090 - WARNING - Skipping BIOMD0000000543.xml - no results generated
2025-12-06 15:04:01,155 - WARNING - Skipping BIOMD0000000544.xml - no results generated
2025-12-06 15:04:01,162 - WARNING - Skipping BIOMD0000000545.xml - no results generated
2025-12-06 15:04:01,184 - WARNING - Skipping BIOMD0000000546.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000542.txt
Evaluating 543/1075: BIOMD0000000543.xml
Evaluating 544/1075: BIOMD0000000544.xml
Evaluating 545/1075: BIOMD0000000545.xml
Evaluating 546/1075: BIOMD0000000546.xml
Evaluating 547/1075: BIOMD0000000547.xml

2025-12-06 15:04:07,333 - WARNING - Skipping BIOMD0000000548.xml - no results generated
2025-12-06 15:04:07,337 - WARNING - Skipping BIOMD0000000549.xml - no results generated
2025-12-06 15:04:07,340 - WARNING - Skipping BIOMD0000000550.xml - no results generated
2025-12-06 15:04:07,345 - WARNING - Skipping BIOMD0000000551.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000547.txt
Evaluating 548/1075: BIOMD0000000548.xml
Evaluating 549/1075: BIOMD0000000549.xml
Evaluating 550/1075: BIOMD0000000550.xml
Evaluating 551/1075: BIOMD0000000551.xml
Evaluating 552/1075: BIOMD0000000552.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000552.txt
Evaluating 553/1075: BIOMD0000000553.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000553.txt
Evaluating 554/1075: BIOMD0000000554.xml

2025-12-06 15:04:21,574 - WARNING - Skipping BIOMD0000000555.xml - no results generated
2025-12-06 15:04:21,582 - WARNING - Skipping BIOMD0000000556.xml - no results generated
2025-12-06 15:04:21,593 - WARNING - Skipping BIOMD0000000557.xml - no results generated
2025-12-06 15:04:21,599 - WARNING - Skipping BIOMD0000000558.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000554.txt
Evaluating 555/1075: BIOMD0000000555.xml
Evaluating 556/1075: BIOMD0000000556.xml
Evaluating 557/1075: BIOMD0000000557.xml
Evaluating 558/1075: BIOMD0000000558.xml
Evaluating 559/1075: BIOMD0000000559.xml

2025-12-06 15:04:38,899 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 15:04:39,008 - WARNING - Skipping BIOMD0000000560.xml - no results generated
2025-12-06 15:04:39,011 - WARNING - Skipping BIOMD0000000561.xml - no results generated
2025-12-06 15:04:39,019 - WARNING - Skipping BIOMD0000000562.xml - no results generated
2025-12-06 15:04:39,027 - WARNING - Skipping BIOMD0000000563.xml - no results generated
2025-12-06 15:04:39,052 - WARNING - Skipping BIOMD0000000564.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000559.txt
Evaluating 560/1075: BIOMD0000000560.xml
Evaluating 561/1075: BIOMD0000000561.xml
Evaluating 562/1075: BIOMD0000000562.xml
Evaluating 563/1075: BIOMD0000000563.xml
Evaluating 564/1075: BIOMD0000000564.xml
Evaluating 565/1075: BIOMD0000000565.xml

2025-12-06 15:04:46,040 - WARNING - Skipping BIOMD0000000566.xml - no results generated
2025-12-06 15:04:46,043 - WARNING - Skipping BIOMD0000000567.xml - no results generated
2025-12-06 15:04:46,072 - WARNING - Skipping BIOMD0000000568.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000565.txt
Evaluating 566/1075: BIOMD0000000566.xml
Evaluating 567/1075: BIOMD0000000567.xml
Evaluating 568/1075: BIOMD0000000568.xml
Evaluating 569/1075: BIOMD0000000569.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000569.txt
Evaluating 570/1075: BIOMD0000000570.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000570.txt
Evaluating 571/1075: BIOMD0000000571.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000571.txt
Evaluating 572/1075: BIOMD0000000572.xml

2025-12-06 15:05:14,498 - WARNING - Skipping BIOMD0000000573.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000572.txt
Evaluating 573/1075: BIOMD0000000573.xml
Evaluating 574/1075: BIOMD0000000574.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000574.txt
Evaluating 575/1075: BIOMD0000000575.xml

2025-12-06 15:05:35,920 - WARNING - Species 's28': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:05:35,920 - WARNING - Species 'Ligand2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000575.txt
Evaluating 576/1075: BIOMD0000000576.xml

2025-12-06 15:05:44,999 - WARNING - Skipping BIOMD0000000577.xml - no results generated
2025-12-06 15:05:45,020 - WARNING - Skipping BIOMD0000000578.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000576.txt
Evaluating 577/1075: BIOMD0000000577.xml
Evaluating 578/1075: BIOMD0000000578.xml
Evaluating 579/1075: BIOMD0000000579.xml

2025-12-06 15:06:52,393 - WARNING - Skipping BIOMD0000000580.xml - no results generated
2025-12-06 15:06:52,407 - WARNING - Skipping BIOMD0000000581.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000579.txt
Evaluating 580/1075: BIOMD0000000580.xml
Evaluating 581/1075: BIOMD0000000581.xml
Evaluating 582/1075: BIOMD0000000582.xml

2025-12-06 15:06:53,306 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 15:06:53,367 - WARNING - Skipping BIOMD0000000583.xml - no results generated
2025-12-06 15:06:53,373 - WARNING - Skipping BIOMD0000000584.xml - no results generated
2025-12-06 15:06:53,380 - WARNING - Skipping BIOMD0000000585.xml - no results generated
2025-12-06 15:06:53,392 - WARNING - Skipping BIOMD0000000586.xml - no results generated
2025-12-06 15:06:53,402 - WARNING - Skipping BIOMD0000000587.xml - no results generated
2025-12-06 15:06:53,436 - WARNING - Skipping BIOMD0000000588.xml - no results generated
2025-12-06 15:06:53,451 - WARNING - Species 'GSH': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:06:53,451 - WARNING - Species 'H2O2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000582.txt
Evaluating 583/1075: BIOMD0000000583.xml
Evaluating 584/1075: BIOMD0000000584.xml
Evaluating 585/1075: BIOMD0000000585.xml
Evaluating 586/1075: BIOMD0000000586.xml
Evaluating 587/1075: BIOMD0000000587.xml
Evaluating 588/1075: BIOMD0000000588.xml
Evaluating 589/1075: BIOMD0000000589.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000589.txt
Evaluating 590/1075: BIOMD0000000590.xml

2025-12-06 15:07:01,197 - WARNING - Skipping BIOMD0000000591.xml - no results generated
2025-12-06 15:07:01,201 - WARNING - Skipping BIOMD0000000592.xml - no results generated
2025-12-06 15:07:01,208 - WARNING - Skipping BIOMD0000000593.xml - no results generated
2025-12-06 15:07:01,239 - WARNING - Species 'Grb2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:07:01,240 - WARNING - Skipping BIOMD0000000594.xml - no results generated
2025-12-06 15:07:01,562 - WARNING - Skipping BIOMD0000000595.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000590.txt
Evaluating 591/1075: BIOMD0000000591.xml
Evaluating 592/1075: BIOMD0000000592.xml
Evaluating 593/1075: BIOMD0000000593.xml
Evaluating 594/1075: BIOMD0000000594.xml
Evaluating 595/1075: BIOMD0000000595.xml

2025-12-06 15:07:01,690 - WARNING - Skipping BIOMD0000000596.xml - no results generated
2025-12-06 15:07:01,713 - WARNING - Skipping BIOMD0000000597.xml - no results generated
2025-12-06 15:07:01,735 - WARNING - Skipping BIOMD0000000598.xml - no results generated
2025-12-06 15:07:01,761 - WARNING - Skipping BIOMD0000000599.xml - no results generated
2025-12-06 15:07:01,793 - WARNING - Skipping BIOMD0000000600.xml - no results generated

Evaluating 596/1075: BIOMD0000000596.xml
Evaluating 597/1075: BIOMD0000000597.xml
Evaluating 598/1075: BIOMD0000000598.xml
Evaluating 599/1075: BIOMD0000000599.xml
Evaluating 600/1075: BIOMD0000000600.xml
Evaluating 601/1075: BIOMD0000000601.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000601.txt
Evaluating 602/1075: BIOMD0000000602.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000602.txt
Evaluating 603/1075: BIOMD0000000603.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000603.txt
Evaluating 604/1075: BIOMD0000000604.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000604.txt
Evaluating 605/1075: BIOMD0000000605.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000605.txt
Evaluating 606/1075: BIOMD0000000606.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000606.txt
Evaluating 607/1075: BIOMD0000000607.xml

2025-12-06 15:07:45,053 - WARNING - Skipping BIOMD0000000608.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000607.txt
Evaluating 608/1075: BIOMD0000000608.xml
Evaluating 609/1075: BIOMD0000000609.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000609.txt
Evaluating 610/1075: BIOMD0000000610.xml

2025-12-06 15:07:50,967 - WARNING - Skipping BIOMD0000000611.xml - no results generated
2025-12-06 15:07:50,988 - WARNING - Skipping BIOMD0000000612.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000610.txt
Evaluating 611/1075: BIOMD0000000611.xml
Evaluating 612/1075: BIOMD0000000612.xml
Evaluating 613/1075: BIOMD0000000613.xml

2025-12-06 15:07:54,784 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 15:07:54,889 - WARNING - Species 'f': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:07:54,889 - WARNING - Skipping BIOMD0000000614.xml - no results generated
2025-12-06 15:07:54,896 - WARNING - Skipping BIOMD0000000615.xml - no results generated
2025-12-06 15:07:54,902 - WARNING - Skipping BIOMD0000000616.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000613.txt
Evaluating 614/1075: BIOMD0000000614.xml
Evaluating 615/1075: BIOMD0000000615.xml
Evaluating 616/1075: BIOMD0000000616.xml
Evaluating 617/1075: BIOMD0000000617.xml

2025-12-06 15:07:57,297 - WARNING - Skipping BIOMD0000000618.xml - no results generated
2025-12-06 15:07:57,306 - WARNING - Skipping BIOMD0000000619.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000617.txt
Evaluating 618/1075: BIOMD0000000618.xml
Evaluating 619/1075: BIOMD0000000619.xml
Evaluating 620/1075: BIOMD0000000620.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000620.txt
Evaluating 621/1075: BIOMD0000000621.xml

2025-12-06 15:08:00,014 - WARNING - Skipping BIOMD0000000622.xml - no results generated
2025-12-06 15:08:00,038 - WARNING - Skipping BIOMD0000000623.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000621.txt
Evaluating 622/1075: BIOMD0000000622.xml
Evaluating 623/1075: BIOMD0000000623.xml
Evaluating 624/1075: BIOMD0000000624.xml

2025-12-06 15:08:04,735 - WARNING - Skipping BIOMD0000000625.xml - no results generated
2025-12-06 15:08:04,744 - WARNING - Skipping BIOMD0000000626.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000624.txt
Evaluating 625/1075: BIOMD0000000625.xml
Evaluating 626/1075: BIOMD0000000626.xml
Evaluating 627/1075: BIOMD0000000627.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000627.txt
Evaluating 628/1075: BIOMD0000000628.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000628.txt
Evaluating 629/1075: BIOMD0000000629.xml

2025-12-06 15:08:49,128 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 15:08:49,144 - WARNING - Skipping BIOMD0000000630.xml - no results generated
2025-12-06 15:08:49,157 - WARNING - Skipping BIOMD0000000631.xml - no results generated
2025-12-06 15:08:49,176 - WARNING - Skipping BIOMD0000000632.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000629.txt
Evaluating 630/1075: BIOMD0000000630.xml
Evaluating 631/1075: BIOMD0000000631.xml
Evaluating 632/1075: BIOMD0000000632.xml
Evaluating 633/1075: BIOMD0000000633.xml

2025-12-06 15:08:52,614 - WARNING - Species 'Mdm2_P_Ub2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:08:52,614 - WARNING - Species 'Mdm2_P_Ub3': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000633.txt
Evaluating 634/1075: BIOMD0000000634.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000634.txt
Evaluating 635/1075: BIOMD0000000635.xml

2025-12-06 15:09:48,209 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 15:09:50,295 - WARNING - Species 'mw9710c658_a2a1_4f49_b494_af109853f251': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000635.txt
Evaluating 636/1075: BIOMD0000000636.xml

2025-12-06 15:10:20,478 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000636.txt
Evaluating 637/1075: BIOMD0000000637.xml

2025-12-06 15:10:26,255 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000637.txt
Evaluating 638/1075: BIOMD0000000638.xml

2025-12-06 15:10:31,416 - WARNING - Skipping BIOMD0000000639.xml - no results generated
2025-12-06 15:10:31,430 - WARNING - Skipping BIOMD0000000640.xml - no results generated
2025-12-06 15:10:31,436 - WARNING - Skipping BIOMD0000000641.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000638.txt
Evaluating 639/1075: BIOMD0000000639.xml
Evaluating 640/1075: BIOMD0000000640.xml
Evaluating 641/1075: BIOMD0000000641.xml
Evaluating 642/1075: BIOMD0000000642.xml

2025-12-06 15:10:33,035 - WARNING - Skipping BIOMD0000000643.xml - no results generated
2025-12-06 15:10:33,043 - WARNING - Skipping BIOMD0000000644.xml - no results generated
2025-12-06 15:10:33,051 - WARNING - Skipping BIOMD0000000645.xml - no results generated
2025-12-06 15:10:33,068 - WARNING - Skipping BIOMD0000000646.xml - no results generated
2025-12-06 15:10:33,076 - WARNING - Skipping BIOMD0000000647.xml - no results generated
2025-12-06 15:10:33,113 - WARNING - Skipping BIOMD0000000648.xml - no results generated
2025-12-06 15:10:33,117 - WARNING - Skipping BIOMD0000000650.xml - no results generated
2025-12-06 15:10:33,132 - WARNING - Skipping BIOMD0000000651.xml - no results generated
2025-12-06 15:10:33,169 - WARNING - Skipping BIOMD0000000652.xml - no results generated
2025-12-06 15:10:33,204 - WARNING - Skipping BIOMD0000000653.xml - no results generated
2025-12-06 15:10:33,240 - WARNING - Skipping BIOMD0000000654.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000642.txt
Evaluating 643/1075: BIOMD0000000643.xml
Evaluating 644/1075: BIOMD0000000644.xml
Evaluating 645/1075: BIOMD0000000645.xml
Evaluating 646/1075: BIOMD0000000646.xml
Evaluating 647/1075: BIOMD0000000647.xml
Evaluating 648/1075: BIOMD0000000648.xml
Evaluating 649/1075: BIOMD0000000650.xml
Evaluating 650/1075: BIOMD0000000651.xml
Evaluating 651/1075: BIOMD0000000652.xml
Evaluating 652/1075: BIOMD0000000653.xml
Evaluating 653/1075: BIOMD0000000654.xml

2025-12-06 15:10:33,277 - WARNING - Skipping BIOMD0000000655.xml - no results generated
2025-12-06 15:10:33,312 - WARNING - Skipping BIOMD0000000656.xml - no results generated
2025-12-06 15:10:33,319 - WARNING - Skipping BIOMD0000000657.xml - no results generated

Evaluating 654/1075: BIOMD0000000655.xml
Evaluating 655/1075: BIOMD0000000656.xml
Evaluating 656/1075: BIOMD0000000657.xml
Evaluating 657/1075: BIOMD0000000658.xml

2025-12-06 15:10:35,582 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000658.txt
Evaluating 658/1075: BIOMD0000000659.xml

2025-12-06 15:10:36,798 - WARNING - Skipping BIOMD0000000660.xml - no results generated
2025-12-06 15:10:36,812 - WARNING - Skipping BIOMD0000000661.xml - no results generated
2025-12-06 15:10:36,821 - WARNING - Skipping BIOMD0000000662.xml - no results generated
2025-12-06 15:10:36,830 - WARNING - Skipping BIOMD0000000663.xml - no results generated
2025-12-06 15:10:36,843 - WARNING - Skipping BIOMD0000000664.xml - no results generated
2025-12-06 15:10:36,855 - WARNING - Skipping BIOMD0000000665.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000659.txt
Evaluating 659/1075: BIOMD0000000660.xml
Evaluating 660/1075: BIOMD0000000661.xml
Evaluating 661/1075: BIOMD0000000662.xml
Evaluating 662/1075: BIOMD0000000663.xml
Evaluating 663/1075: BIOMD0000000664.xml
Evaluating 664/1075: BIOMD0000000665.xml
Evaluating 665/1075: BIOMD0000000666.xml

2025-12-06 15:10:38,366 - WARNING - Skipping BIOMD0000000667.xml - no results generated
2025-12-06 15:10:38,380 - WARNING - Species 'Inh_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:10:38,381 - WARNING - Species 'Inh_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:10:38,381 - WARNING - Species 'Sti_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:10:38,382 - WARNING - Species 'Sti_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:10:38,383 - WARNING - Skipping BIOMD0000000668.xml - no results generated
2025-12-06 15:10:38,401 - WARNING - Skipping BIOMD0000000669.xml - no results generated
2025-12-06 15:10:38,405 - WARNING - Skipping BIOMD0000000670.xml - no results generated
2025-12-06 15:10:38,409 - WARNING - Skipping BIOMD0000000671.xml - no results generated
2025-12-06 15:10:38,415 - WARNING - Skipping BIOMD0000000672.xml - no results generated
2025-12-06 15:10:38,425 - WARNING - Skipping BIOMD0000000673.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000666.txt
Evaluating 666/1075: BIOMD0000000667.xml
Evaluating 667/1075: BIOMD0000000668.xml
Evaluating 668/1075: BIOMD0000000669.xml
Evaluating 669/1075: BIOMD0000000670.xml
Evaluating 670/1075: BIOMD0000000671.xml
Evaluating 671/1075: BIOMD0000000672.xml
Evaluating 672/1075: BIOMD0000000673.xml
Evaluating 673/1075: BIOMD0000000674.xml

2025-12-06 15:10:54,090 - WARNING - Skipping BIOMD0000000675.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000674.txt
Evaluating 674/1075: BIOMD0000000675.xml
Evaluating 675/1075: BIOMD0000000676.xml

2025-12-06 15:11:01,500 - WARNING - Skipping BIOMD0000000677.xml - no results generated
2025-12-06 15:11:01,505 - WARNING - Skipping BIOMD0000000678.xml - no results generated
2025-12-06 15:11:01,512 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:11:01,513 - WARNING - Skipping BIOMD0000000679.xml - no results generated
2025-12-06 15:11:01,519 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:11:01,519 - WARNING - Skipping BIOMD0000000680.xml - no results generated
2025-12-06 15:11:01,525 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:11:01,526 - WARNING - Skipping BIOMD0000000681.xml - no results generated
2025-12-06 15:11:01,535 - WARNING - Skipping BIOMD0000000682.xml - no results generated
2025-12-06 15:11:01,544 - WARNING - Skipping BIOMD0000000683.xml - no results generated
2025-12-06 15:11:01,553 - WARNING - Skipping BIOMD0000000684.xml - no results generated
2025-12-06 15:11:01,558 - WARNING - Skipping BIOMD0000000685.xml - no results generated
2025-12-06 15:11:01,566 - WARNING - Skipping BIOMD0000000686.xml - no results generated
2025-12-06 15:11:01,585 - WARNING - Skipping BIOMD0000000687.xml - no results generated
2025-12-06 15:11:01,603 - WARNING - Skipping BIOMD0000000688.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000676.txt
Evaluating 676/1075: BIOMD0000000677.xml
Evaluating 677/1075: BIOMD0000000678.xml
Evaluating 678/1075: BIOMD0000000679.xml
Evaluating 679/1075: BIOMD0000000680.xml
Evaluating 680/1075: BIOMD0000000681.xml
Evaluating 681/1075: BIOMD0000000682.xml
Evaluating 682/1075: BIOMD0000000683.xml
Evaluating 683/1075: BIOMD0000000684.xml
Evaluating 684/1075: BIOMD0000000685.xml
Evaluating 685/1075: BIOMD0000000686.xml
Evaluating 686/1075: BIOMD0000000687.xml
Evaluating 687/1075: BIOMD0000000688.xml
Evaluating 688/1075: BIOMD0000000689.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000689.txt
Evaluating 689/1075: BIOMD0000000690.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000690.txt
Evaluating 690/1075: BIOMD0000000691.xml

2025-12-06 15:11:13,831 - WARNING - Skipping BIOMD0000000692.xml - no results generated
2025-12-06 15:11:13,843 - WARNING - Skipping BIOMD0000000693.xml - no results generated
2025-12-06 15:11:13,875 - WARNING - Skipping BIOMD0000000695.xml - no results generated
2025-12-06 15:11:13,893 - WARNING - Skipping BIOMD0000000696.xml - no results generated
2025-12-06 15:11:13,916 - WARNING - Skipping BIOMD0000000697.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000691.txt
Evaluating 691/1075: BIOMD0000000692.xml
Evaluating 692/1075: BIOMD0000000693.xml
Evaluating 693/1075: BIOMD0000000695.xml
Evaluating 694/1075: BIOMD0000000696.xml
Evaluating 695/1075: BIOMD0000000697.xml
Evaluating 696/1075: BIOMD0000000698.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000698.txt
Evaluating 697/1075: BIOMD0000000699.xml

2025-12-06 15:11:35,313 - WARNING - Skipping BIOMD0000000700.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000699.txt
Evaluating 698/1075: BIOMD0000000700.xml
Evaluating 699/1075: BIOMD0000000701.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000701.txt
Evaluating 700/1075: BIOMD0000000702.xml

2025-12-06 15:12:15,063 - WARNING - Skipping BIOMD0000000703.xml - no results generated
2025-12-06 15:12:15,083 - WARNING - Skipping BIOMD0000000704.xml - no results generated
2025-12-06 15:12:15,121 - WARNING - Skipping BIOMD0000000705.xml - no results generated
2025-12-06 15:12:15,189 - WARNING - Skipping BIOMD0000000706.xml - no results generated
2025-12-06 15:12:15,196 - WARNING - Skipping BIOMD0000000707.xml - no results generated
2025-12-06 15:12:15,204 - WARNING - Skipping BIOMD0000000708.xml - no results generated
2025-12-06 15:12:15,211 - WARNING - Skipping BIOMD0000000709.xml - no results generated
2025-12-06 15:12:15,222 - WARNING - Skipping BIOMD0000000710.xml - no results generated
2025-12-06 15:12:15,237 - WARNING - Skipping BIOMD0000000711.xml - no results generated
2025-12-06 15:12:15,242 - WARNING - Skipping BIOMD0000000712.xml - no results generated
2025-12-06 15:12:15,249 - WARNING - Skipping BIOMD0000000713.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000702.txt
Evaluating 701/1075: BIOMD0000000703.xml
Evaluating 702/1075: BIOMD0000000704.xml
Evaluating 703/1075: BIOMD0000000705.xml
Evaluating 704/1075: BIOMD0000000706.xml
Evaluating 705/1075: BIOMD0000000707.xml
Evaluating 706/1075: BIOMD0000000708.xml
Evaluating 707/1075: BIOMD0000000709.xml
Evaluating 708/1075: BIOMD0000000710.xml
Evaluating 709/1075: BIOMD0000000711.xml
Evaluating 710/1075: BIOMD0000000712.xml
Evaluating 711/1075: BIOMD0000000713.xml
Evaluating 712/1075: BIOMD0000000714.xml

2025-12-06 15:12:15,256 - WARNING - Skipping BIOMD0000000714.xml - no results generated
2025-12-06 15:12:15,262 - WARNING - Skipping BIOMD0000000715.xml - no results generated
2025-12-06 15:12:15,272 - WARNING - Skipping BIOMD0000000716.xml - no results generated
2025-12-06 15:12:15,281 - WARNING - Skipping BIOMD0000000717.xml - no results generated
2025-12-06 15:12:15,305 - WARNING - Skipping BIOMD0000000718.xml - no results generated
2025-12-06 15:12:15,316 - WARNING - Skipping BIOMD0000000719.xml - no results generated
2025-12-06 15:12:15,326 - WARNING - Skipping BIOMD0000000720.xml - no results generated
2025-12-06 15:12:15,334 - WARNING - Skipping BIOMD0000000721.xml - no results generated
2025-12-06 15:12:15,341 - WARNING - Skipping BIOMD0000000722.xml - no results generated
2025-12-06 15:12:15,377 - WARNING - Skipping BIOMD0000000723.xml - no results generated
2025-12-06 15:12:15,404 - WARNING - Skipping BIOMD0000000724.xml - no results generated
2025-12-06 15:12:15,432 - WARNING - Skipping BIOMD0000000725.xml - no results generated
2025-12-06 15:12:15,444 - WARNING - Skipping BIOMD0000000726.xml - no results generated

Evaluating 713/1075: BIOMD0000000715.xml
Evaluating 714/1075: BIOMD0000000716.xml
Evaluating 715/1075: BIOMD0000000717.xml
Evaluating 716/1075: BIOMD0000000718.xml
Evaluating 717/1075: BIOMD0000000719.xml
Evaluating 718/1075: BIOMD0000000720.xml
Evaluating 719/1075: BIOMD0000000721.xml
Evaluating 720/1075: BIOMD0000000722.xml
Evaluating 721/1075: BIOMD0000000723.xml
Evaluating 722/1075: BIOMD0000000724.xml
Evaluating 723/1075: BIOMD0000000725.xml
Evaluating 724/1075: BIOMD0000000726.xml
Evaluating 725/1075: BIOMD0000000727.xml

2025-12-06 15:12:15,483 - WARNING - Skipping BIOMD0000000727.xml - no results generated
2025-12-06 15:12:15,489 - WARNING - Skipping BIOMD0000000728.xml - no results generated
2025-12-06 15:12:15,496 - WARNING - Skipping BIOMD0000000729.xml - no results generated
2025-12-06 15:12:15,566 - WARNING - Skipping BIOMD0000000730.xml - no results generated
2025-12-06 15:12:15,585 - WARNING - Skipping BIOMD0000000731.xml - no results generated
2025-12-06 15:12:15,591 - WARNING - Skipping BIOMD0000000732.xml - no results generated
2025-12-06 15:12:15,597 - WARNING - Skipping BIOMD0000000733.xml - no results generated

Evaluating 726/1075: BIOMD0000000728.xml
Evaluating 727/1075: BIOMD0000000729.xml
Evaluating 728/1075: BIOMD0000000730.xml
Evaluating 729/1075: BIOMD0000000731.xml
Evaluating 730/1075: BIOMD0000000732.xml
Evaluating 731/1075: BIOMD0000000733.xml
Evaluating 732/1075: BIOMD0000000734.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000734.txt
Evaluating 733/1075: BIOMD0000000735.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000735.txt
Evaluating 734/1075: BIOMD0000000736.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000736.txt
Evaluating 735/1075: BIOMD0000000737.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000737.txt
Evaluating 736/1075: BIOMD0000000738.xml

2025-12-06 15:12:46,508 - WARNING - Species 'Va_i_306': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:12:46,508 - WARNING - Species 'Va_1_306_Va_LC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:12:46,509 - WARNING - Species 'Va_307_506': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:12:46,509 - WARNING - Species 'Va_507_679_709': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:12:46,510 - WARNING - Skipping BIOMD0000000739.xml - no results generated
2025-12-06 15:12:46,523 - WARNING - Species 'Xa_TFPI': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:12:46,524 - WARNING - Species 'Xa_VIIa_TF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:12:46,525 - WARNING - Skipping BIOMD0000000740.xml - no results generated
2025-12-06 15:12:46,543 - WARNING - Skipping BIOMD0000000741.xml - no results generated
2025-12-06 15:12:46,551 - WARNING - Skipping BIOMD0000000742.xml - no results generated
2025-12-06 15:12:46,578 - WARNING - Skipping BIOMD0000000743.xml - no results generated
2025-12-06 15:12:46,594 - WARNING - Skipping BIOMD0000000744.xml - no results generated
2025-12-06 15:12:46,607 - WARNING - Skipping BIOMD0000000745.xml - no results generated
2025-12-06 15:12:46,619 - WARNING - Skipping BIOMD0000000746.xml - no results generated
2025-12-06 15:12:46,639 - WARNING - Skipping BIOMD0000000747.xml - no results generated
2025-12-06 15:12:46,650 - WARNING - Skipping BIOMD0000000748.xml - no results generated
2025-12-06 15:12:46,659 - WARNING - Skipping BIOMD0000000749.xml - no results generated
2025-12-06 15:12:46,680 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000738.txt
Evaluating 737/1075: BIOMD0000000739.xml
Evaluating 738/1075: BIOMD0000000740.xml
Evaluating 739/1075: BIOMD0000000741.xml
Evaluating 740/1075: BIOMD0000000742.xml
Evaluating 741/1075: BIOMD0000000743.xml
Evaluating 742/1075: BIOMD0000000744.xml
Evaluating 743/1075: BIOMD0000000745.xml
Evaluating 744/1075: BIOMD0000000746.xml
Evaluating 745/1075: BIOMD0000000747.xml
Evaluating 746/1075: BIOMD0000000748.xml
Evaluating 747/1075: BIOMD0000000749.xml
Evaluating 748/1075: BIOMD0000000750.xml

2025-12-06 15:12:48,716 - WARNING - Skipping BIOMD0000000751.xml - no results generated
2025-12-06 15:12:48,724 - WARNING - Skipping BIOMD0000000752.xml - no results generated
2025-12-06 15:12:48,732 - WARNING - Skipping BIOMD0000000753.xml - no results generated
2025-12-06 15:12:48,745 - WARNING - Skipping BIOMD0000000754.xml - no results generated
2025-12-06 15:12:48,753 - WARNING - Skipping BIOMD0000000755.xml - no results generated
2025-12-06 15:12:48,765 - WARNING - Skipping BIOMD0000000756.xml - no results generated
2025-12-06 15:12:48,784 - WARNING - Skipping BIOMD0000000757.xml - no results generated
2025-12-06 15:12:48,789 - WARNING - Skipping BIOMD0000000758.xml - no results generated
2025-12-06 15:12:48,805 - WARNING - Skipping BIOMD0000000759.xml - no results generated
2025-12-06 15:12:48,812 - WARNING - Skipping BIOMD0000000760.xml - no results generated
2025-12-06 15:12:48,822 - WARNING - Skipping BIOMD0000000761.xml - no results generated
2025-12-06 15:12:48,829 - WARNING - Skipping BIOMD0000000762.xml - no results generated
2025-12-06 15:12:48,836 - WARNING - Skipping BIOMD0000000763.xml - no results generated
2025-12-06 15:12:48,846 - WARNING - Skipping BIOMD0000000764.xml - no results generated
2025-12-06 15:12:48,854 - WARNING - Skipping BIOMD0000000765.xml - no results generated
2025-12-06 15:12:48,865 - WARNING - Skipping BIOMD0000000766.xml - no results generated
2025-12-06 15:12:48,872 - WARNING - Skipping BIOMD0000000767.xml - no results generated
2025-12-06 15:12:48,884 - WARNING - Skipping BIOMD0000000768.xml - no results generated
2025-12-06 15:12:48,901 - WARNING - Skipping BIOMD0000000769.xml - no results generated
2025-12-06 15:12:48,911 - WARNING - Skipping BIOMD0000000770.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000750.txt
Evaluating 749/1075: BIOMD0000000751.xml
Evaluating 750/1075: BIOMD0000000752.xml
Evaluating 751/1075: BIOMD0000000753.xml
Evaluating 752/1075: BIOMD0000000754.xml
Evaluating 753/1075: BIOMD0000000755.xml
Evaluating 754/1075: BIOMD0000000756.xml
Evaluating 755/1075: BIOMD0000000757.xml
Evaluating 756/1075: BIOMD0000000758.xml
Evaluating 757/1075: BIOMD0000000759.xml
Evaluating 758/1075: BIOMD0000000760.xml
Evaluating 759/1075: BIOMD0000000761.xml
Evaluating 760/1075: BIOMD0000000762.xml
Evaluating 761/1075: BIOMD0000000763.xml
Evaluating 762/1075: BIOMD0000000764.xml
Evaluating 763/1075: BIOMD0000000765.xml
Evaluating 764/1075: BIOMD0000000766.xml
Evaluating 765/1075: BIOMD0000000767.xml
Evaluating 766/1075: BIOMD0000000768.xml
Evaluating 767/1075: BIOMD0000000769.xml
Evaluating 768/1075: BIOMD0000000770.xml
Evaluating 769/1075: BIOMD0000000771.xml

2025-12-06 15:12:48,917 - WARNING - Skipping BIOMD0000000771.xml - no results generated
2025-12-06 15:12:48,923 - WARNING - Skipping BIOMD0000000772.xml - no results generated
2025-12-06 15:12:48,932 - WARNING - Skipping BIOMD0000000773.xml - no results generated
2025-12-06 15:12:48,939 - WARNING - Skipping BIOMD0000000774.xml - no results generated
2025-12-06 15:12:48,949 - WARNING - Skipping BIOMD0000000775.xml - no results generated
2025-12-06 15:12:48,955 - WARNING - Skipping BIOMD0000000776.xml - no results generated
2025-12-06 15:12:48,960 - WARNING - Skipping BIOMD0000000777.xml - no results generated
2025-12-06 15:12:48,969 - WARNING - Skipping BIOMD0000000778.xml - no results generated

Evaluating 770/1075: BIOMD0000000772.xml
Evaluating 771/1075: BIOMD0000000773.xml
Evaluating 772/1075: BIOMD0000000774.xml
Evaluating 773/1075: BIOMD0000000775.xml
Evaluating 774/1075: BIOMD0000000776.xml
Evaluating 775/1075: BIOMD0000000777.xml
Evaluating 776/1075: BIOMD0000000778.xml
Evaluating 777/1075: BIOMD0000000779.xml

2025-12-06 15:12:50,270 - WARNING - Skipping BIOMD0000000780.xml - no results generated
2025-12-06 15:12:50,276 - WARNING - Skipping BIOMD0000000781.xml - no results generated
2025-12-06 15:12:50,282 - WARNING - Skipping BIOMD0000000782.xml - no results generated
2025-12-06 15:12:50,287 - WARNING - Skipping BIOMD0000000783.xml - no results generated
2025-12-06 15:12:50,294 - WARNING - Skipping BIOMD0000000784.xml - no results generated
2025-12-06 15:12:50,299 - WARNING - Skipping BIOMD0000000785.xml - no results generated
2025-12-06 15:12:50,377 - WARNING - Skipping BIOMD0000000786.xml - no results generated
2025-12-06 15:12:50,382 - WARNING - Skipping BIOMD0000000787.xml - no results generated
2025-12-06 15:12:50,394 - WARNING - Skipping BIOMD0000000788.xml - no results generated
2025-12-06 15:12:50,401 - WARNING - Skipping BIOMD0000000789.xml - no results generated
2025-12-06 15:12:50,411 - WARNING - Skipping BIOMD0000000790.xml - no results generated
2025-12-06 15:12:50,421 - WARNING - Skipping BIOMD0000000791.xml - no results generated
2025-12-06 15:12:50,429 - WARNING - Skipping BIOMD0000000792.xml - no results generated
2025-12-06 15:12:50,435 - WARNING - Skipping BIOMD0000000793.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000779.txt
Evaluating 778/1075: BIOMD0000000780.xml
Evaluating 779/1075: BIOMD0000000781.xml
Evaluating 780/1075: BIOMD0000000782.xml
Evaluating 781/1075: BIOMD0000000783.xml
Evaluating 782/1075: BIOMD0000000784.xml
Evaluating 783/1075: BIOMD0000000785.xml
Evaluating 784/1075: BIOMD0000000786.xml
Evaluating 785/1075: BIOMD0000000787.xml
Evaluating 786/1075: BIOMD0000000788.xml
Evaluating 787/1075: BIOMD0000000789.xml
Evaluating 788/1075: BIOMD0000000790.xml
Evaluating 789/1075: BIOMD0000000791.xml
Evaluating 790/1075: BIOMD0000000792.xml
Evaluating 791/1075: BIOMD0000000793.xml
Evaluating 792/1075: BIOMD0000000794.xml

2025-12-06 15:12:50,509 - WARNING - Skipping BIOMD0000000794.xml - no results generated
2025-12-06 15:12:50,516 - WARNING - Skipping BIOMD0000000795.xml - no results generated
2025-12-06 15:12:50,529 - WARNING - Skipping BIOMD0000000796.xml - no results generated
2025-12-06 15:12:50,538 - WARNING - Skipping BIOMD0000000797.xml - no results generated
2025-12-06 15:12:50,546 - WARNING - Skipping BIOMD0000000798.xml - no results generated
2025-12-06 15:12:50,550 - WARNING - Skipping BIOMD0000000799.xml - no results generated
2025-12-06 15:12:50,556 - WARNING - Skipping BIOMD0000000800.xml - no results generated

Evaluating 793/1075: BIOMD0000000795.xml
Evaluating 794/1075: BIOMD0000000796.xml
Evaluating 795/1075: BIOMD0000000797.xml
Evaluating 796/1075: BIOMD0000000798.xml
Evaluating 797/1075: BIOMD0000000799.xml
Evaluating 798/1075: BIOMD0000000800.xml
Evaluating 799/1075: BIOMD0000000801.xml

2025-12-06 15:12:53,351 - WARNING - Skipping BIOMD0000000802.xml - no results generated
2025-12-06 15:12:53,357 - WARNING - Skipping BIOMD0000000803.xml - no results generated
2025-12-06 15:12:53,368 - WARNING - Skipping BIOMD0000000804.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000801.txt
Evaluating 800/1075: BIOMD0000000802.xml
Evaluating 801/1075: BIOMD0000000803.xml
Evaluating 802/1075: BIOMD0000000804.xml
Evaluating 803/1075: BIOMD0000000805.xml

2025-12-06 15:12:55,433 - WARNING - Skipping BIOMD0000000806.xml - no results generated
2025-12-06 15:12:55,446 - WARNING - Skipping BIOMD0000000807.xml - no results generated
2025-12-06 15:12:55,457 - WARNING - Skipping BIOMD0000000808.xml - no results generated
2025-12-06 15:12:55,467 - WARNING - Skipping BIOMD0000000809.xml - no results generated
2025-12-06 15:12:55,498 - WARNING - Skipping BIOMD0000000810.xml - no results generated
2025-12-06 15:12:55,513 - WARNING - Skipping BIOMD0000000811.xml - no results generated
2025-12-06 15:12:55,520 - WARNING - Skipping BIOMD0000000812.xml - no results generated
2025-12-06 15:12:55,526 - WARNING - Skipping BIOMD0000000813.xml - no results generated
2025-12-06 15:12:55,535 - WARNING - Skipping BIOMD0000000814.xml - no results generated
2025-12-06 15:12:55,541 - WARNING - Skipping BIOMD0000000815.xml - no results generated
2025-12-06 15:12:55,555 - WARNING - Skipping BIOMD0000000816.xml - no results generated
2025-12-06 15:12:55,567 - WARNING - Skipping BIOMD0000000817.xml - no results generated
2025-12-06 15:12:55,577 - WARNING - Skipping BIOMD0000000818.xml - no results generated
2025-12-06 15:12:55,597 - WARNING - Skipping BIOMD0000000819.xml - no results generated
2025-12-06 15:12:55,604 - WARNING - Skipping BIOMD0000000820.xml - no results generated
2025-12-06 15:12:55,610 - WARNING - Skipping BIOMD0000000821.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000805.txt
Evaluating 804/1075: BIOMD0000000806.xml
Evaluating 805/1075: BIOMD0000000807.xml
Evaluating 806/1075: BIOMD0000000808.xml
Evaluating 807/1075: BIOMD0000000809.xml
Evaluating 808/1075: BIOMD0000000810.xml
Evaluating 809/1075: BIOMD0000000811.xml
Evaluating 810/1075: BIOMD0000000812.xml
Evaluating 811/1075: BIOMD0000000813.xml
Evaluating 812/1075: BIOMD0000000814.xml
Evaluating 813/1075: BIOMD0000000815.xml
Evaluating 814/1075: BIOMD0000000816.xml
Evaluating 815/1075: BIOMD0000000817.xml
Evaluating 816/1075: BIOMD0000000818.xml
Evaluating 817/1075: BIOMD0000000819.xml
Evaluating 818/1075: BIOMD0000000820.xml
Evaluating 819/1075: BIOMD0000000821.xml
Evaluating 820/1075: BIOMD0000000822.xml

2025-12-06 15:12:58,844 - WARNING - Skipping BIOMD0000000823.xml - no results generated
2025-12-06 15:12:58,847 - WARNING - Skipping BIOMD0000000824.xml - no results generated
2025-12-06 15:12:58,853 - WARNING - Skipping BIOMD0000000825.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000822.txt
Evaluating 821/1075: BIOMD0000000823.xml
Evaluating 822/1075: BIOMD0000000824.xml
Evaluating 823/1075: BIOMD0000000825.xml
Evaluating 824/1075: BIOMD0000000826.xml

2025-12-06 15:13:00,518 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000826.txt
Evaluating 825/1075: BIOMD0000000827.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000827.txt
Evaluating 826/1075: BIOMD0000000828.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000828.txt
Evaluating 827/1075: BIOMD0000000829.xml

2025-12-06 15:13:04,992 - WARNING - Skipping BIOMD0000000830.xml - no results generated
2025-12-06 15:13:04,999 - WARNING - Skipping BIOMD0000000831.xml - no results generated
2025-12-06 15:13:05,018 - WARNING - Species 'LATS1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:05,020 - WARNING - Skipping BIOMD0000000832.xml - no results generated
2025-12-06 15:13:05,069 - WARNING - Skipping BIOMD0000000833.xml - no results generated
2025-12-06 15:13:05,110 - WARNING - Skipping BIOMD0000000834.xml - no results generated
2025-12-06 15:13:05,150 - WARNING - Skipping BIOMD0000000835.xml - no results generated
2025-12-06 15:13:05,153 - WARNING - Skipping BIOMD0000000836.xml - no results generated
2025-12-06 15:13:05,164 - WARNING - Skipping BIOMD0000000837.xml - no results generated
2025-12-06 15:13:05,170 - WARNING - Skipping BIOMD0000000838.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000829.txt
Evaluating 828/1075: BIOMD0000000830.xml
Evaluating 829/1075: BIOMD0000000831.xml
Evaluating 830/1075: BIOMD0000000832.xml
Evaluating 831/1075: BIOMD0000000833.xml
Evaluating 832/1075: BIOMD0000000834.xml
Evaluating 833/1075: BIOMD0000000835.xml
Evaluating 834/1075: BIOMD0000000836.xml
Evaluating 835/1075: BIOMD0000000837.xml
Evaluating 836/1075: BIOMD0000000838.xml
Evaluating 837/1075: BIOMD0000000839.xml

2025-12-06 15:13:05,181 - WARNING - Skipping BIOMD0000000839.xml - no results generated
2025-12-06 15:13:05,189 - WARNING - Skipping BIOMD0000000840.xml - no results generated
2025-12-06 15:13:05,195 - WARNING - Skipping BIOMD0000000841.xml - no results generated

Evaluating 838/1075: BIOMD0000000840.xml
Evaluating 839/1075: BIOMD0000000841.xml
Evaluating 840/1075: BIOMD0000000842.xml

2025-12-06 15:13:07,715 - WARNING - Skipping BIOMD0000000843.xml - no results generated
2025-12-06 15:13:07,730 - WARNING - Skipping BIOMD0000000844.xml - no results generated
2025-12-06 15:13:07,735 - WARNING - Skipping BIOMD0000000845.xml - no results generated
2025-12-06 15:13:07,741 - WARNING - Skipping BIOMD0000000846.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000842.txt
Evaluating 841/1075: BIOMD0000000843.xml
Evaluating 842/1075: BIOMD0000000844.xml
Evaluating 843/1075: BIOMD0000000845.xml
Evaluating 844/1075: BIOMD0000000846.xml
Evaluating 845/1075: BIOMD0000000847.xml

2025-12-06 15:13:10,663 - WARNING - Skipping BIOMD0000000848.xml - no results generated
2025-12-06 15:13:10,750 - WARNING - Skipping BIOMD0000000849.xml - no results generated
2025-12-06 15:13:10,755 - WARNING - Skipping BIOMD0000000850.xml - no results generated
2025-12-06 15:13:10,760 - WARNING - Skipping BIOMD0000000851.xml - no results generated
2025-12-06 15:13:10,772 - WARNING - Skipping BIOMD0000000852.xml - no results generated
2025-12-06 15:13:10,783 - WARNING - Species 'STAB': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:10,784 - WARNING - Skipping BIOMD0000000853.xml - no results generated
2025-12-06 15:13:10,791 - WARNING - Skipping BIOMD0000000854.xml - no results generated
2025-12-06 15:13:10,802 - WARNING - Skipping BIOMD0000000855.xml - no results generated
2025-12-06 15:13:10,823 - WARNING - Skipping BIOMD0000000856.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000847.txt
Evaluating 846/1075: BIOMD0000000848.xml
Evaluating 847/1075: BIOMD0000000849.xml
Evaluating 848/1075: BIOMD0000000850.xml
Evaluating 849/1075: BIOMD0000000851.xml
Evaluating 850/1075: BIOMD0000000852.xml
Evaluating 851/1075: BIOMD0000000853.xml
Evaluating 852/1075: BIOMD0000000854.xml
Evaluating 853/1075: BIOMD0000000855.xml
Evaluating 854/1075: BIOMD0000000856.xml
Evaluating 855/1075: BIOMD0000000857.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000857.txt
Evaluating 856/1075: BIOMD0000000858.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000858.txt
Evaluating 857/1075: BIOMD0000000859.xml

2025-12-06 15:13:17,756 - WARNING - Species 'miR': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,756 - WARNING - Species 'TF1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,757 - WARNING - Skipping BIOMD0000000860.xml - no results generated
2025-12-06 15:13:17,779 - WARNING - Species 'p12EpoRpJAK2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,781 - WARNING - Skipping BIOMD0000000861.xml - no results generated
2025-12-06 15:13:17,788 - WARNING - Skipping BIOMD0000000862.xml - no results generated
2025-12-06 15:13:17,804 - WARNING - Skipping BIOMD0000000863.xml - no results generated
2025-12-06 15:13:17,809 - WARNING - Skipping BIOMD0000000864.xml - no results generated
2025-12-06 15:13:17,819 - WARNING - Skipping BIOMD0000000865.xml - no results generated
2025-12-06 15:13:17,824 - WARNING - Skipping BIOMD0000000866.xml - no results generated
2025-12-06 15:13:17,842 - WARNING - Skipping BIOMD0000000867.xml - no results generated
2025-12-06 15:13:17,848 - WARNING - Skipping BIOMD0000000868.xml - no results generated
2025-12-06 15:13:17,853 - WARNING - Skipping BIOMD0000000869.xml - no results generated
2025-12-06 15:13:17,860 - WARNING - Skipping BIOMD0000000870.xml - no results generated
2025-12-06 15:13:17,868 - WARNING - Skipping BIOMD0000000871.xml - no results generated
2025-12-06 15:13:17,932 - WARNING - Species 's2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,933 - WARNING - Species 's4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,934 - WARNING - Species 's14': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,934 - WARNING - Species 's16': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,934 - WARNING - Species 's13': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,935 - WARNING - Species 's12': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,936 - WARNING - Skipping BIOMD0000000872.xml - no results generated
2025-12-06 15:13:17,955 - WARNING - Species 'mw5b252d78_9ab9_438c_8b81_2189b1f76357': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,956 - WARNING - Species 'mw869055b5_5d27_4f4a_a390_b3fa48d6780e': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000859.txt
Evaluating 858/1075: BIOMD0000000860.xml
Evaluating 859/1075: BIOMD0000000861.xml
Evaluating 860/1075: BIOMD0000000862.xml
Evaluating 861/1075: BIOMD0000000863.xml
Evaluating 862/1075: BIOMD0000000864.xml
Evaluating 863/1075: BIOMD0000000865.xml
Evaluating 864/1075: BIOMD0000000866.xml
Evaluating 865/1075: BIOMD0000000867.xml
Evaluating 866/1075: BIOMD0000000868.xml
Evaluating 867/1075: BIOMD0000000869.xml
Evaluating 868/1075: BIOMD0000000870.xml
Evaluating 869/1075: BIOMD0000000871.xml
Evaluating 870/1075: BIOMD0000000872.xml
Evaluating 871/1075: BIOMD0000000873.xml

2025-12-06 15:13:17,957 - WARNING - Species 'mw6f8ce639_1c28_444f_b6e6_30ff06ab0d6e': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,957 - WARNING - Species 'mwb9a40fab_a7c9_4984_805f_045fefc4ff32': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,958 - WARNING - Species 'mw4fc13b75_10cc_41fb_b9f8_1ce95fccae73': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,959 - WARNING - Skipping BIOMD0000000873.xml - no results generated
2025-12-06 15:13:17,965 - WARNING - Skipping BIOMD0000000874.xml - no results generated
2025-12-06 15:13:17,971 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,971 - WARNING - Skipping BIOMD0000000875.xml - no results generated
2025-12-06 15:13:17,979 - WARNING - Skipping BIOMD0000000876.xml - no results generated
2025-12-06 15:13:17,985 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:17,986 - WARNING - Skipping BIOMD0000000877.xml - no results generated
2025-12-06 15:13:17,992 - WARNING - Skipping BIOMD0000000878.xml - no results generated

Evaluating 872/1075: BIOMD0000000874.xml
Evaluating 873/1075: BIOMD0000000875.xml
Evaluating 874/1075: BIOMD0000000876.xml
Evaluating 875/1075: BIOMD0000000877.xml
Evaluating 876/1075: BIOMD0000000878.xml
Evaluating 877/1075: BIOMD0000000879.xml

2025-12-06 15:13:18,992 - WARNING - Skipping BIOMD0000000880.xml - no results generated
2025-12-06 15:13:19,002 - WARNING - Skipping BIOMD0000000881.xml - no results generated
2025-12-06 15:13:19,008 - WARNING - Species 'Susceptible': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:19,009 - WARNING - Species 'Removal': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:19,009 - WARNING - Skipping BIOMD0000000882.xml - no results generated
2025-12-06 15:13:19,062 - WARNING - Species 'mTORC2Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:19,063 - WARNING - Species 'mTORC1Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:19,063 - WARNING - Species 'mTORC1Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:19,070 - WARNING - Species 'mTORC2Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000879.txt
Evaluating 878/1075: BIOMD0000000880.xml
Evaluating 879/1075: BIOMD0000000881.xml
Evaluating 880/1075: BIOMD0000000882.xml
Evaluating 881/1075: BIOMD0000000883.xml

2025-12-06 15:13:21,561 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,561 - WARNING - Species 'V': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,562 - WARNING - Skipping BIOMD0000000884.xml - no results generated
2025-12-06 15:13:21,568 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,568 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,568 - WARNING - Skipping BIOMD0000000885.xml - no results generated
2025-12-06 15:13:21,576 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,576 - WARNING - Species 'Th': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,576 - WARNING - Species 'B': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,577 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,577 - WARNING - Skipping BIOMD0000000886.xml - no results generated
2025-12-06 15:13:21,585 - WARNING - Skipping BIOMD0000000887.xml - no results generated
2025-12-06 15:13:21,594 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,595 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,595 - WARNING - Species 'D': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,595 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:21,596 - WARNING - Skipping BIOMD0000000888.xml - no results generated
2025-12-06 15:13:21,612 - WARNING - Skipping BIOMD0000000889.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000883.txt
Evaluating 882/1075: BIOMD0000000884.xml
Evaluating 883/1075: BIOMD0000000885.xml
Evaluating 884/1075: BIOMD0000000886.xml
Evaluating 885/1075: BIOMD0000000887.xml
Evaluating 886/1075: BIOMD0000000888.xml
Evaluating 887/1075: BIOMD0000000889.xml
Evaluating 888/1075: BIOMD0000000890.xml

2025-12-06 15:13:22,495 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,496 - WARNING - Species 'v': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,496 - WARNING - Species 'w': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,497 - WARNING - Skipping BIOMD0000000891.xml - no results generated
2025-12-06 15:13:22,508 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,509 - WARNING - Skipping BIOMD0000000892.xml - no results generated
2025-12-06 15:13:22,516 - WARNING - Skipping BIOMD0000000893.xml - no results generated
2025-12-06 15:13:22,524 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,524 - WARNING - Species 'y': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,524 - WARNING - Species 'z': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,525 - WARNING - Skipping BIOMD0000000894.xml - no results generated
2025-12-06 15:13:22,543 - WARNING - Skipping BIOMD0000000895.xml - no results generated
2025-12-06 15:13:22,555 - WARNING - Species 'HSF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,556 - WARNING - Skipping BIOMD0000000896.xml - no results generated
2025-12-06 15:13:22,561 - WARNING - Skipping BIOMD0000000897.xml - no results generated
2025-12-06 15:13:22,569 - WARNING - Skipping BIOMD0000000898.xml - no results generated
2025-12-06 15:13:22,621 - WARNING - Skipping BIOMD0000000899.xml - no results generated
2025-12-06 15:13:22,627 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,627 - WARNING - Skipping BIOMD0000000900.xml - no results generated
2025-12-06 15:13:22,632 - WARNING - Skipping BIOMD0000000901.xml - no results generated
2025-12-06 15:13:22,638 - WARNING - Skipping BIOMD0000000902.xml - no results generated
2025-12-06 15:13:22,645 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,645 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,646 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,646 - WARNING - Skipping BIOMD0000000903.xml - no results generated
2025-12-06 15:13:22,653 - WARNING - Species 'Ti': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,653 - WARNING - Species 'Tm': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,654 - WARNING - Skipping BIOMD0000000904.xml - no results generated
2025-12-06 15:13:22,661 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,661 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,662 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,663 - WARNING - Skipping BIOMD0000000905.xml - no results generated
2025-12-06 15:13:22,667 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,668 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,668 - WARNING - Skipping BIOMD0000000906.xml - no results generated
2025-12-06 15:13:22,685 - WARNING - Skipping BIOMD0000000907.xml - no results generated
2025-12-06 15:13:22,695 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000890.txt
Evaluating 889/1075: BIOMD0000000891.xml
Evaluating 890/1075: BIOMD0000000892.xml
Evaluating 891/1075: BIOMD0000000893.xml
Evaluating 892/1075: BIOMD0000000894.xml
Evaluating 893/1075: BIOMD0000000895.xml
Evaluating 894/1075: BIOMD0000000896.xml
Evaluating 895/1075: BIOMD0000000897.xml
Evaluating 896/1075: BIOMD0000000898.xml
Evaluating 897/1075: BIOMD0000000899.xml
Evaluating 898/1075: BIOMD0000000900.xml
Evaluating 899/1075: BIOMD0000000901.xml
Evaluating 900/1075: BIOMD0000000902.xml
Evaluating 901/1075: BIOMD0000000903.xml
Evaluating 902/1075: BIOMD0000000904.xml
Evaluating 903/1075: BIOMD0000000905.xml
Evaluating 904/1075: BIOMD0000000906.xml
Evaluating 905/1075: BIOMD0000000907.xml
Evaluating 906/1075: BIOMD0000000908.xml

2025-12-06 15:13:22,696 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,696 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,696 - WARNING - Species 'R': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,697 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,697 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,697 - WARNING - Species 'S': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,698 - WARNING - Skipping BIOMD0000000908.xml - no results generated
2025-12-06 15:13:22,704 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,704 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,705 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,705 - WARNING - Skipping BIOMD0000000909.xml - no results generated
2025-12-06 15:13:22,710 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,714 - WARNING - Species 'I2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,714 - WARNING - Skipping BIOMD0000000910.xml - no results generated
2025-12-06 15:13:22,720 - WARNING - Skipping BIOMD0000000911.xml - no results generated
2025-12-06 15:13:22,726 - WARNING - Skipping BIOMD0000000912.xml - no results generated
2025-12-06 15:13:22,736 - WARNING - Skipping BIOMD0000000913.xml - no results generated
2025-12-06 15:13:22,742 - WARNING - Species 'SVAC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,743 - WARNING - Skipping BIOMD0000000914.xml - no results generated
2025-12-06 15:13:22,754 - WARNING - Skipping BIOMD0000000915.xml - no results generated
2025-12-06 15:13:22,760 - WARNING - Skipping BIOMD0000000916.xml - no results generated
2025-12-06 15:13:22,770 - WARNING - Skipping BIOMD0000000917.xml - no results generated
2025-12-06 15:13:22,782 - WARNING - Skipping BIOMD0000000918.xml - no results generated
2025-12-06 15:13:22,787 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,788 - WARNING - Skipping BIOMD0000000919.xml - no results generated
2025-12-06 15:13:22,796 - WARNING - Skipping BIOMD0000000920.xml - no results generated
2025-12-06 15:13:22,807 - WARNING - Species 'G': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,808 - WARNING - Species 'M': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,808 - WARNING - Species 'C_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,808 - WARNING - Species 'T_beta': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,808 - WARNING - Species 'I_gamma': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:22,809 - WARNING - Skipping BIOMD0000000921.xml - no results generated
2025-12-06 15:13:22,814 - WARNING - Skipping BIOMD0000000922.xml - no results generated
2025-12-06 15:13:22,821 - WARNING - Skipping BIOMD0000000923.xml - no results generated
2025-12-06 15:13:22,833 - WARNING - Skipping BIOMD0000000924.xml - no results generated

Evaluating 907/1075: BIOMD0000000909.xml
Evaluating 908/1075: BIOMD0000000910.xml
Evaluating 909/1075: BIOMD0000000911.xml
Evaluating 910/1075: BIOMD0000000912.xml
Evaluating 911/1075: BIOMD0000000913.xml
Evaluating 912/1075: BIOMD0000000914.xml
Evaluating 913/1075: BIOMD0000000915.xml
Evaluating 914/1075: BIOMD0000000916.xml
Evaluating 915/1075: BIOMD0000000917.xml
Evaluating 916/1075: BIOMD0000000918.xml
Evaluating 917/1075: BIOMD0000000919.xml
Evaluating 918/1075: BIOMD0000000920.xml
Evaluating 919/1075: BIOMD0000000921.xml
Evaluating 920/1075: BIOMD0000000922.xml
Evaluating 921/1075: BIOMD0000000923.xml
Evaluating 922/1075: BIOMD0000000924.xml
Evaluating 923/1075: BIOMD0000000925.xml

2025-12-06 15:13:22,946 - WARNING - Skipping BIOMD0000000925.xml - no results generated
2025-12-06 15:13:22,970 - WARNING - Skipping BIOMD0000000926.xml - no results generated

Evaluating 924/1075: BIOMD0000000926.xml
Evaluating 925/1075: BIOMD0000000927.xml

2025-12-06 15:13:24,237 - WARNING - Skipping BIOMD0000000928.xml - no results generated
2025-12-06 15:13:24,263 - WARNING - Skipping BIOMD0000000929.xml - no results generated
2025-12-06 15:13:24,275 - WARNING - Skipping BIOMD0000000930.xml - no results generated
2025-12-06 15:13:24,283 - WARNING - Skipping BIOMD0000000931.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000927.txt
Evaluating 926/1075: BIOMD0000000928.xml
Evaluating 927/1075: BIOMD0000000929.xml
Evaluating 928/1075: BIOMD0000000930.xml
Evaluating 929/1075: BIOMD0000000931.xml
Evaluating 930/1075: BIOMD0000000932.xml

2025-12-06 15:13:26,221 - WARNING - Skipping BIOMD0000000933.xml - no results generated
2025-12-06 15:13:26,234 - WARNING - Skipping BIOMD0000000934.xml - no results generated
2025-12-06 15:13:26,239 - WARNING - Skipping BIOMD0000000935.xml - no results generated
2025-12-06 15:13:26,242 - WARNING - Skipping BIOMD0000000936.xml - no results generated
2025-12-06 15:13:26,248 - WARNING - Skipping BIOMD0000000937.xml - no results generated
2025-12-06 15:13:26,258 - WARNING - Skipping BIOMD0000000938.xml - no results generated
2025-12-06 15:13:26,327 - WARNING - Skipping BIOMD0000000939.xml - no results generated
2025-12-06 15:13:26,356 - WARNING - Skipping BIOMD0000000940.xml - no results generated
2025-12-06 15:13:26,368 - WARNING - Skipping BIOMD0000000941.xml - no results generated
2025-12-06 15:13:26,380 - WARNING - Skipping BIOMD0000000942.xml - no results generated
2025-12-06 15:13:26,425 - WARNING - Skipping BIOMD0000000943.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000932.txt
Evaluating 931/1075: BIOMD0000000933.xml
Evaluating 932/1075: BIOMD0000000934.xml
Evaluating 933/1075: BIOMD0000000935.xml
Evaluating 934/1075: BIOMD0000000936.xml
Evaluating 935/1075: BIOMD0000000937.xml
Evaluating 936/1075: BIOMD0000000938.xml
Evaluating 937/1075: BIOMD0000000939.xml
Evaluating 938/1075: BIOMD0000000940.xml
Evaluating 939/1075: BIOMD0000000941.xml
Evaluating 940/1075: BIOMD0000000942.xml
Evaluating 941/1075: BIOMD0000000943.xml

2025-12-06 15:13:26,431 - WARNING - Skipping BIOMD0000000944.xml - no results generated
2025-12-06 15:13:26,439 - WARNING - Skipping BIOMD0000000945.xml - no results generated
2025-12-06 15:13:26,450 - WARNING - Skipping BIOMD0000000946.xml - no results generated

Evaluating 942/1075: BIOMD0000000944.xml
Evaluating 943/1075: BIOMD0000000945.xml
Evaluating 944/1075: BIOMD0000000946.xml
Evaluating 945/1075: BIOMD0000000947.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000947.txt
Evaluating 946/1075: BIOMD0000000948.xml

2025-12-06 15:13:35,237 - WARNING - Skipping BIOMD0000000949.xml - no results generated
2025-12-06 15:13:35,247 - WARNING - Skipping BIOMD0000000950.xml - no results generated
2025-12-06 15:13:35,273 - WARNING - Skipping BIOMD0000000951.xml - no results generated
2025-12-06 15:13:35,288 - WARNING - Skipping BIOMD0000000952.xml - no results generated
2025-12-06 15:13:35,311 - WARNING - Skipping BIOMD0000000953.xml - no results generated
2025-12-06 15:13:35,345 - WARNING - Skipping BIOMD0000000954.xml - no results generated
2025-12-06 15:13:35,359 - WARNING - Skipping BIOMD0000000955.xml - no results generated
2025-12-06 15:13:35,368 - WARNING - Skipping BIOMD0000000956.xml - no results generated
2025-12-06 15:13:35,372 - WARNING - Skipping BIOMD0000000957.xml - no results generated
2025-12-06 15:13:35,384 - WARNING - Skipping BIOMD0000000958.xml - no results generated
2025-12-06 15:13:35,423 - WARNING - Species 'STAT1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,423 - WARNING - Species 'STAT1_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,424 - WARNING - Species 'STAT1_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,424 - WARNING - Species 'STAT2_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,424 - WARNING - Species 'STAT2_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,425 - WARNING - Species 'STAT2_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,425 - WARNING - Species 'STAT2_LC_4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,425 - WARNING - Species 'STAT2_LC_5': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,426 - WARNING - Species 'IRF9_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,426 - WARNING - Species 'IRF9_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,426 - WARNING - Species 'USP18_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,427 - WARNING - Species 'USP18_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,427 - WARNING - Species 'SOCS1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:35,429 - WARNING - Skipping BIOMD0000000959.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000948.txt
Evaluating 947/1075: BIOMD0000000949.xml
Evaluating 948/1075: BIOMD0000000950.xml
Evaluating 949/1075: BIOMD0000000951.xml
Evaluating 950/1075: BIOMD0000000952.xml
Evaluating 951/1075: BIOMD0000000953.xml
Evaluating 952/1075: BIOMD0000000954.xml
Evaluating 953/1075: BIOMD0000000955.xml
Evaluating 954/1075: BIOMD0000000956.xml
Evaluating 955/1075: BIOMD0000000957.xml
Evaluating 956/1075: BIOMD0000000958.xml
Evaluating 957/1075: BIOMD0000000959.xml
Evaluating 958/1075: BIOMD0000000960.xml

2025-12-06 15:13:35,454 - WARNING - Skipping BIOMD0000000960.xml - no results generated

Evaluating 959/1075: BIOMD0000000961.xml

2025-12-06 15:13:48,515 - WARNING - Skipping BIOMD0000000962.xml - no results generated
2025-12-06 15:13:48,520 - WARNING - Skipping BIOMD0000000963.xml - no results generated
2025-12-06 15:13:48,531 - WARNING - Skipping BIOMD0000000964.xml - no results generated
2025-12-06 15:13:48,563 - WARNING - Species 'I1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:48,565 - WARNING - Skipping BIOMD0000000965.xml - no results generated
2025-12-06 15:13:48,583 - WARNING - Species 'Py': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:48,584 - WARNING - Species 'Py1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:48,585 - WARNING - Species 'Dw': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:48,585 - WARNING - Species 'Qw1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:48,585 - WARNING - Species 'Qw2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000961.txt
Evaluating 960/1075: BIOMD0000000962.xml
Evaluating 961/1075: BIOMD0000000963.xml
Evaluating 962/1075: BIOMD0000000964.xml
Evaluating 963/1075: BIOMD0000000965.xml
Evaluating 964/1075: BIOMD0000000966.xml

2025-12-06 15:13:50,443 - WARNING - Skipping BIOMD0000000967.xml - no results generated
2025-12-06 15:13:50,456 - WARNING - Skipping BIOMD0000000968.xml - no results generated
2025-12-06 15:13:50,482 - WARNING - Skipping BIOMD0000000969.xml - no results generated
2025-12-06 15:13:50,489 - WARNING - Skipping BIOMD0000000970.xml - no results generated
2025-12-06 15:13:50,503 - WARNING - Skipping BIOMD0000000971.xml - no results generated
2025-12-06 15:13:50,514 - WARNING - Skipping BIOMD0000000972.xml - no results generated
2025-12-06 15:13:50,521 - WARNING - Skipping BIOMD0000000973.xml - no results generated
2025-12-06 15:13:50,527 - WARNING - Skipping BIOMD0000000974.xml - no results generated
2025-12-06 15:13:50,564 - WARNING - Species 'PCC_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:50,565 - WARNING - Species 'PCN_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:50,565 - WARNING - Species 'PCNP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:50,565 - WARNING - Species 'PCCP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:50,567 - WARNING - Skipping BIOMD0000000975.xml - no results generated
2025-12-06 15:13:50,574 - WARNING - Skipping BIOMD0000000976.xml - no results generated
2025-12-06 15:13:50,585 - WARNING - Skipping BIOMD0000000977.xml - no results generated
2025-12-06 15:13:50,591 - WARNING - Skipping BIOMD0000000978.xml - no results generated
2025-12-06 15:13:50,598 - WARNING - Skipping BIOMD0000000979.xml - no results generated
2025-12-06 15:13:50,605 - WARNING - Skipping BIOMD0000000980.xml - no results generated
2025-12-06 15:13:50,618 - WARNING - Skipping BIOMD0000000981.xml - no results generated
2025-12-06 15:13:50,623 - WARNING - Skipping BIOMD0000000982.xml - no results generated
2025-12-06 15:13:50,634 - WARNING - Skipping BIOMD0000000983.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000966.txt
Evaluating 965/1075: BIOMD0000000967.xml
Evaluating 966/1075: BIOMD0000000968.xml
Evaluating 967/1075: BIOMD0000000969.xml
Evaluating 968/1075: BIOMD0000000970.xml
Evaluating 969/1075: BIOMD0000000971.xml
Evaluating 970/1075: BIOMD0000000972.xml
Evaluating 971/1075: BIOMD0000000973.xml
Evaluating 972/1075: BIOMD0000000974.xml
Evaluating 973/1075: BIOMD0000000975.xml
Evaluating 974/1075: BIOMD0000000976.xml
Evaluating 975/1075: BIOMD0000000977.xml
Evaluating 976/1075: BIOMD0000000978.xml
Evaluating 977/1075: BIOMD0000000979.xml
Evaluating 978/1075: BIOMD0000000980.xml
Evaluating 979/1075: BIOMD0000000981.xml
Evaluating 980/1075: BIOMD0000000982.xml
Evaluating 981/1075: BIOMD0000000983.xml
Evaluating 982/1075: BIOMD0000000984.xml

2025-12-06 15:13:50,639 - WARNING - Skipping BIOMD0000000984.xml - no results generated
2025-12-06 15:13:50,649 - WARNING - Skipping BIOMD0000000985.xml - no results generated

Evaluating 983/1075: BIOMD0000000985.xml
Evaluating 984/1075: BIOMD0000000986.xml

2025-12-06 15:13:53,374 - WARNING - Skipping BIOMD0000000987.xml - no results generated
2025-12-06 15:13:53,416 - WARNING - Skipping BIOMD0000000988.xml - no results generated
2025-12-06 15:13:53,457 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:53,459 - WARNING - Skipping BIOMD0000000989.xml - no results generated
2025-12-06 15:13:53,500 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-06 15:13:53,503 - WARNING - Skipping BIOMD0000000990.xml - no results generated
2025-12-06 15:13:53,514 - WARNING - Skipping BIOMD0000000991.xml - no results generated
2025-12-06 15:13:53,552 - WARNING - Skipping BIOMD0000000994.xml - no results generated
2025-12-06 15:13:53,588 - WARNING - Skipping BIOMD0000000995.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000000986.txt
Evaluating 985/1075: BIOMD0000000987.xml
Evaluating 986/1075: BIOMD0000000988.xml
Evaluating 987/1075: BIOMD0000000989.xml
Evaluating 988/1075: BIOMD0000000990.xml
Evaluating 989/1075: BIOMD0000000991.xml
Evaluating 990/1075: BIOMD0000000994.xml
Evaluating 991/1075: BIOMD0000000995.xml

2025-12-06 15:13:53,628 - WARNING - Skipping BIOMD0000000996.xml - no results generated
2025-12-06 15:13:53,665 - WARNING - Skipping BIOMD0000000997.xml - no results generated
2025-12-06 15:13:53,703 - WARNING - Skipping BIOMD0000000998.xml - no results generated
2025-12-06 15:13:53,738 - WARNING - Skipping BIOMD0000000999.xml - no results generated
2025-12-06 15:13:53,774 - WARNING - Skipping BIOMD0000001000.xml - no results generated
2025-12-06 15:13:53,809 - WARNING - Skipping BIOMD0000001001.xml - no results generated

Evaluating 992/1075: BIOMD0000000996.xml
Evaluating 993/1075: BIOMD0000000997.xml
Evaluating 994/1075: BIOMD0000000998.xml
Evaluating 995/1075: BIOMD0000000999.xml
Evaluating 996/1075: BIOMD0000001000.xml
Evaluating 997/1075: BIOMD0000001001.xml
Evaluating 998/1075: BIOMD0000001002.xml

2025-12-06 15:13:53,847 - WARNING - Skipping BIOMD0000001002.xml - no results generated
2025-12-06 15:13:53,883 - WARNING - Skipping BIOMD0000001003.xml - no results generated
2025-12-06 15:13:53,896 - WARNING - Skipping BIOMD0000001004.xml - no results generated

Evaluating 999/1075: BIOMD0000001003.xml
Evaluating 1000/1075: BIOMD0000001004.xml
Evaluating 1001/1075: BIOMD0000001005.xml

2025-12-06 15:13:56,460 - WARNING - Skipping BIOMD0000001006.xml - no results generated
2025-12-06 15:13:56,469 - WARNING - Skipping BIOMD0000001007.xml - no results generated
2025-12-06 15:13:56,474 - WARNING - Skipping BIOMD0000001008.xml - no results generated
2025-12-06 15:13:56,484 - WARNING - Skipping BIOMD0000001009.xml - no results generated
2025-12-06 15:13:56,492 - WARNING - Skipping BIOMD0000001010.xml - no results generated
2025-12-06 15:13:56,498 - WARNING - Skipping BIOMD0000001011.xml - no results generated
2025-12-06 15:13:56,507 - WARNING - Skipping BIOMD0000001012.xml - no results generated
2025-12-06 15:13:56,513 - WARNING - Skipping BIOMD0000001013.xml - no results generated
2025-12-06 15:13:56,522 - WARNING - Skipping BIOMD0000001014.xml - no results generated
2025-12-06 15:13:56,533 - WARNING - Skipping BIOMD0000001015.xml - no results generated
2025-12-06 15:13:56,542 - WARNING - Skipping BIOMD0000001016.xml - no results generated
2025-12-06 15:13:56,556 - WARNING - Skipping BIOMD0000001017.xml - no results generated
2025-12-06 15:13:56,576 - WARNING - Skipping BIOMD0000001018.xml - no results generated
2025-12-06 15:13:56,583 - WARNING - Skipping BIOMD0000001019.xml - no results generated
2025-12-06 15:13:56,588 - WARNING - Skipping BIOMD0000001020.xml - no results generated
2025-12-06 15:13:56,597 - WARNING - Skipping BIOMD0000001021.xml - no results generated
2025-12-06 15:13:56,604 - WARNING - Skipping BIOMD0000001022.xml - no results generated
2025-12-06 15:13:56,613 - WARNING - Skipping BIOMD0000001023.xml - no results generated
2025-12-06 15:13:56,619 - WARNING - Skipping BIOMD0000001024.xml - no results generated
2025-12-06 15:13:56,625 - WARNING - Skipping BIOMD0000001025.xml - no results generated
2025-12-06 15:13:56,630 - WARNING - Skipping BIOMD0000001026.xml - no results generated
2025-12-06 15:13:56,657 - WARNING - Skipping BIOMD0000001027.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001005.txt
Evaluating 1002/1075: BIOMD0000001006.xml
Evaluating 1003/1075: BIOMD0000001007.xml
Evaluating 1004/1075: BIOMD0000001008.xml
Evaluating 1005/1075: BIOMD0000001009.xml
Evaluating 1006/1075: BIOMD0000001010.xml
Evaluating 1007/1075: BIOMD0000001011.xml
Evaluating 1008/1075: BIOMD0000001012.xml
Evaluating 1009/1075: BIOMD0000001013.xml
Evaluating 1010/1075: BIOMD0000001014.xml
Evaluating 1011/1075: BIOMD0000001015.xml
Evaluating 1012/1075: BIOMD0000001016.xml
Evaluating 1013/1075: BIOMD0000001017.xml
Evaluating 1014/1075: BIOMD0000001018.xml
Evaluating 1015/1075: BIOMD0000001019.xml
Evaluating 1016/1075: BIOMD0000001020.xml
Evaluating 1017/1075: BIOMD0000001021.xml
Evaluating 1018/1075: BIOMD0000001022.xml
Evaluating 1019/1075: BIOMD0000001023.xml
Evaluating 1020/1075: BIOMD0000001024.xml
Evaluating 1021/1075: BIOMD0000001025.xml
Evaluating 1022/1075: BIOMD0000001026.xml
Evaluating 1023/1075: BIOMD0000001027.xml

2025-12-06 15:13:56,687 - WARNING - Skipping BIOMD0000001028.xml - no results generated
2025-12-06 15:13:56,718 - WARNING - Skipping BIOMD0000001029.xml - no results generated
2025-12-06 15:13:56,724 - WARNING - Skipping BIOMD0000001030.xml - no results generated
2025-12-06 15:13:56,730 - WARNING - Skipping BIOMD0000001031.xml - no results generated
2025-12-06 15:13:56,738 - WARNING - Skipping BIOMD0000001032.xml - no results generated
2025-12-06 15:13:56,755 - WARNING - Skipping BIOMD0000001033.xml - no results generated
2025-12-06 15:13:56,763 - WARNING - Skipping BIOMD0000001034.xml - no results generated
2025-12-06 15:13:56,771 - WARNING - Skipping BIOMD0000001035.xml - no results generated
2025-12-06 15:13:56,777 - WARNING - Skipping BIOMD0000001036.xml - no results generated
2025-12-06 15:13:56,781 - WARNING - Skipping BIOMD0000001037.xml - no results generated
2025-12-06 15:13:56,786 - WARNING - Skipping BIOMD0000001038.xml - no results generated
2025-12-06 15:13:56,818 - WARNING - Skipping BIOMD0000001039.xml - no results generated
2025-12-06 15:13:56,824 - WARNING - Skipping BIOMD0000001040.xml - no results generated
2025-12-06 15:13:56,830 - WARNING - Skipping BIOMD0000001041.xml - no results generated
2025-12-06 15:13:56,840 - WARNING - Skipping BIOMD0000001042.xml - no results generated
2025-12-06 15:13:56,847 - WARNING - Skipping BIOMD0000001043.xml - no results generated
2025-12-06 15:13:56,929 - WARNING - Skipping BIOMD0000001044.xml - no results generated

Evaluating 1024/1075: BIOMD0000001028.xml
Evaluating 1025/1075: BIOMD0000001029.xml
Evaluating 1026/1075: BIOMD0000001030.xml
Evaluating 1027/1075: BIOMD0000001031.xml
Evaluating 1028/1075: BIOMD0000001032.xml
Evaluating 1029/1075: BIOMD0000001033.xml
Evaluating 1030/1075: BIOMD0000001034.xml
Evaluating 1031/1075: BIOMD0000001035.xml
Evaluating 1032/1075: BIOMD0000001036.xml
Evaluating 1033/1075: BIOMD0000001037.xml
Evaluating 1034/1075: BIOMD0000001038.xml
Evaluating 1035/1075: BIOMD0000001039.xml
Evaluating 1036/1075: BIOMD0000001040.xml
Evaluating 1037/1075: BIOMD0000001041.xml
Evaluating 1038/1075: BIOMD0000001042.xml
Evaluating 1039/1075: BIOMD0000001043.xml
Evaluating 1040/1075: BIOMD0000001044.xml

2025-12-06 15:13:56,934 - WARNING - Skipping BIOMD0000001045.xml - no results generated

Evaluating 1041/1075: BIOMD0000001045.xml
Evaluating 1042/1075: BIOMD0000001046.xml

2025-12-06 15:16:34,766 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 15:16:38,389 - WARNING - Skipping BIOMD0000001047.xml - no results generated
2025-12-06 15:16:38,395 - WARNING - Skipping BIOMD0000001048.xml - no results generated
2025-12-06 15:16:38,404 - WARNING - Skipping BIOMD0000001052.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001046.txt
Evaluating 1043/1075: BIOMD0000001047.xml
Evaluating 1044/1075: BIOMD0000001048.xml
Evaluating 1045/1075: BIOMD0000001052.xml
Evaluating 1046/1075: BIOMD0000001053.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001053.txt
Evaluating 1047/1075: BIOMD0000001054.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001054.txt
Evaluating 1048/1075: BIOMD0000001055.xml

2025-12-06 15:16:44,934 - WARNING - Skipping BIOMD0000001056.xml - no results generated
2025-12-06 15:16:44,940 - WARNING - Skipping BIOMD0000001057.xml - no results generated
2025-12-06 15:16:44,959 - WARNING - Skipping BIOMD0000001058.xml - no results generated
2025-12-06 15:16:44,974 - WARNING - Skipping BIOMD0000001059.xml - no results generated
2025-12-06 15:16:44,982 - WARNING - Skipping BIOMD0000001060.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001055.txt
Evaluating 1049/1075: BIOMD0000001056.xml
Evaluating 1050/1075: BIOMD0000001057.xml
Evaluating 1051/1075: BIOMD0000001058.xml
Evaluating 1052/1075: BIOMD0000001059.xml
Evaluating 1053/1075: BIOMD0000001060.xml
Evaluating 1054/1075: BIOMD0000001061.xml

2025-12-06 15:24:20,890 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001061.txt
Evaluating 1055/1075: BIOMD0000001062.xml

2025-12-06 15:44:29,513 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001062.txt
Evaluating 1056/1075: BIOMD0000001063.xml

2025-12-06 16:18:55,863 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-12-06 16:18:58,150 - WARNING - Skipping BIOMD0000001064.xml - no results generated
2025-12-06 16:18:58,248 - WARNING - Skipping BIOMD0000001065.xml - no results generated
2025-12-06 16:18:58,259 - WARNING - Skipping BIOMD0000001072.xml - no results generated
2025-12-06 16:18:58,276 - WARNING - Skipping BIOMD0000001077.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001063.txt
Evaluating 1057/1075: BIOMD0000001064.xml
Evaluating 1058/1075: BIOMD0000001065.xml
Evaluating 1059/1075: BIOMD0000001072.xml
Evaluating 1060/1075: BIOMD0000001077.xml

2025-12-06 16:18:58,281 - WARNING - Skipping BIOMD0000001078.xml - no results generated
2025-12-06 16:18:58,285 - WARNING - Skipping BIOMD0000001079.xml - no results generated
2025-12-06 16:18:58,290 - WARNING - Skipping BIOMD0000001080.xml - no results generated
2025-12-06 16:18:58,566 - WARNING - Skipping BIOMD0000001090.xml - no results generated

Evaluating 1061/1075: BIOMD0000001078.xml
Evaluating 1062/1075: BIOMD0000001079.xml
Evaluating 1063/1075: BIOMD0000001080.xml
Evaluating 1064/1075: BIOMD0000001090.xml
Evaluating 1065/1075: BIOMD0000001091.xml

2025-12-06 16:18:59,786 - WARNING - Skipping BIOMD0000001091.xml - no results generated

Evaluating 1066/1075: BIOMD0000001092.xml

2025-12-06 16:22:36,265 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001092.txt
Evaluating 1067/1075: BIOMD0000001093.xml

2025-12-06 16:35:42,216 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_1420/BIOMD0000001093.txt
Evaluating 1068/1075: BIOMD0000001094.xml

2025-12-06 16:35:44,828 - WARNING - Skipping BIOMD0000001094.xml - no results generated
2025-12-06 16:35:45,078 - WARNING - Skipping BIOMD0000001095.xml - no results generated
2025-12-06 16:35:45,440 - WARNING - Skipping BIOMD0000001096.xml - no results generated

Evaluating 1069/1075: BIOMD0000001095.xml
Evaluating 1070/1075: BIOMD0000001096.xml

2025-12-06 16:35:45,655 - WARNING - Skipping BIOMD0000001097.xml - no results generated
2025-12-06 16:35:45,816 - WARNING - Skipping BIOMD0000001098.xml - no results generated

Evaluating 1071/1075: BIOMD0000001097.xml
Evaluating 1072/1075: BIOMD0000001098.xml
Evaluating 1073/1075: BIOMD0000001099.xml

2025-12-06 16:35:45,993 - WARNING - Skipping BIOMD0000001099.xml - no results generated
2025-12-06 16:35:46,003 - WARNING - Skipping BIOMD0000001102.xml - no results generated
2025-12-06 16:35:46,011 - WARNING - Skipping BIOMD0000001103.xml - no results generated

Evaluating 1074/1075: BIOMD0000001102.xml
Evaluating 1075/1075: BIOMD0000001103.xml

In [3]:
# Run batch evaluation on updated BioModels
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model=llm_model,
    entity_type='auto',
    database='chebi',
    method="rag",
    top_k = 10,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi_rag_llama-3_top10_autoType.csv",
    start_at=1
)

2025-11-20 12:19:05,166 - WARNING - Skipping BIOMD0000000001.xml - no results generated

LLM results will be saved to: ./autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219
Evaluating 1/1075: BIOMD0000000001.xml
Evaluating 2/1075: BIOMD0000000002.xml

2025-11-20 12:19:10,592 - WARNING - Skipping BIOMD0000000003.xml - no results generated
2025-11-20 12:19:10,598 - WARNING - Skipping BIOMD0000000004.xml - no results generated
2025-11-20 12:19:10,604 - WARNING - Skipping BIOMD0000000005.xml - no results generated
2025-11-20 12:19:10,608 - WARNING - Skipping BIOMD0000000006.xml - no results generated
2025-11-20 12:19:10,649 - WARNING - Skipping BIOMD0000000007.xml - no results generated
2025-11-20 12:19:10,666 - WARNING - Skipping BIOMD0000000008.xml - no results generated
2025-11-20 12:19:10,738 - WARNING - Skipping BIOMD0000000009.xml - no results generated
2025-11-20 12:19:10,757 - WARNING - Skipping BIOMD0000000010.xml - no results generated
2025-11-20 12:19:10,775 - WARNING - Skipping BIOMD0000000011.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000002.txt
LLM response:
L (chemical): "acetylcholine", "ACh", "achetylcholine"
Reason: The species L is identified as "ACh" in the display names, which is a common abbreviation for acetylcholine, a neurotransmitter. The model is also described as an "EPSP ACh species" and discusses nicotinic acetylcholine receptors, further supporting the identification of L as acetylcholine.
Synonyms dict: {'L': ['acetylcholine', 'ACh', 'achetylcholine']}
Evaluating 3/1075: BIOMD0000000003.xml
Evaluating 4/1075: BIOMD0000000004.xml
Evaluating 5/1075: BIOMD0000000005.xml
Evaluating 6/1075: BIOMD0000000006.xml
Evaluating 7/1075: BIOMD0000000007.xml
Evaluating 8/1075: BIOMD0000000008.xml
Evaluating 9/1075: BIOMD0000000009.xml
Evaluating 10/1075: BIOMD0000000010.xml
Evaluating 11/1075: BIOMD0000000011.xml
Evaluating 12/1075: BIOMD0000000012.xml

2025-11-20 12:19:10,785 - WARNING - Skipping BIOMD0000000012.xml - no results generated

Evaluating 13/1075: BIOMD0000000013.xml

2025-11-20 12:19:17,920 - WARNING - Skipping BIOMD0000000014.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000013.txt
LLM response:
x_CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
ATP_ch (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
x_NADPH_ch (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced nicotinamide adenine dinucleotide phosphate"
GAP_ch (chemical): "glyceraldehyde-3-phosphate", "GAP", "3-phosphoglyceraldehyde"
Pi_ch (chemical): "inorganic phosphate", "phosphate", "orthophosphate"
DHAP_ch (chemical): "dihydroxyacetone phosphate", "DHAP", "3-hydroxy-2-oxopropyl phosphate"
FBP_ch (chemical): "fructose-1,6-bisphosphate", "FBP", "fructose 1,6-diphosphate"
F6P_ch (chemical): "fructose-6-phosphate", "F6P", "fructose 6-phosphate"
E4P_ch (chemical): "erythrose-4-phosphate", "E4P", "4-phosphoerythrose"
X5P_ch (chemical): "xylulose-5-phosphate", "X5P", "5-phosphoxylulose"
SBP_ch (chemical): "sedoheptulose-1,7-bisphosphate", "SBP", "sedoheptulose 1,7-diphosphate"
S7P_ch (chemical): "sedoheptulose-7-phosphate", "S7P", "7-phosphosedoheptulose"
R5P_ch (chemical): "ribose-5-phosphate", "R5P", "5-phosphoribose"
Ru5P_ch (chemical): "ribulose-5-phosphate", "Ru5P", "5-phosphoribulose"
x_Pi_cyt (chemical): "inorganic phosphate", "phosphate", "orthophosphate"
x_GAP_cyt (chemical): "glyceraldehyde-3-phosphate", "GAP", "3-phosphoglyceraldehyde"
G6P_ch (chemical): "glucose-6-phosphate", "G6P", "glucose 6-phosphate"
x_NADP_ch (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP", "oxidized nicotinamide adenine dinucleotide phosphate"
ADP_ch (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
x_DHAP_cyt (chemical): "dihydroxyacetone phosphate", "DHAP", "3-hydroxy-2-oxopropyl phosphate"
x_Proton_ch (chemical): "hydrogen ion", "proton", "H+"
G1P_ch (chemical): "glucose-1-phosphate", "G1P", "glucose 1-phosphate"
Reason: The entity types and standardized names were determined based on the context of the Calvin cycle model and common biochemical nomenclature. The species IDs with "_ch" or "_cyt" suffixes were assumed to represent chemical species in the chloroplast or cytosol, respectively. The names were ranked by likelihood based on their common usage in biochemical literature.
Synonyms dict: {'x_CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'ATP_ch': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'x_NADPH_ch': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced nicotinamide adenine dinucleotide phosphate'], 'GAP_ch': ['glyceraldehyde-3-phosphate', 'GAP', '3-phosphoglyceraldehyde'], 'Pi_ch': ['inorganic phosphate', 'phosphate', 'orthophosphate'], 'DHAP_ch': ['dihydroxyacetone phosphate', 'DHAP', '3-hydroxy-2-oxopropyl phosphate'], 'FBP_ch': ['fructose-1,6-bisphosphate', 'FBP', 'fructose 1,6-diphosphate'], 'F6P_ch': ['fructose-6-phosphate', 'F6P', 'fructose 6-phosphate'], 'E4P_ch': ['erythrose-4-phosphate', 'E4P', '4-phosphoerythrose'], 'X5P_ch': ['xylulose-5-phosphate', 'X5P', '5-phosphoxylulose'], 'SBP_ch': ['sedoheptulose-1,7-bisphosphate', 'SBP', 'sedoheptulose 1,7-diphosphate'], 'S7P_ch': ['sedoheptulose-7-phosphate', 'S7P', '7-phosphosedoheptulose'], 'R5P_ch': ['ribose-5-phosphate', 'R5P', '5-phosphoribose'], 'Ru5P_ch': ['ribulose-5-phosphate', 'Ru5P', '5-phosphoribulose'], 'x_Pi_cyt': ['inorganic phosphate', 'phosphate', 'orthophosphate'], 'x_GAP_cyt': ['glyceraldehyde-3-phosphate', 'GAP', '3-phosphoglyceraldehyde'], 'G6P_ch': ['glucose-6-phosphate', 'G6P', 'glucose 6-phosphate'], 'x_NADP_ch': ['nicotinamide adenine dinucleotide phosphate', 'NADP', 'oxidized nicotinamide adenine dinucleotide phosphate'], 'ADP_ch': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'x_DHAP_cyt': ['dihydroxyacetone phosphate', 'DHAP', '3-hydroxy-2-oxopropyl phosphate'], 'x_Proton_ch': ['hydrogen ion', 'proton', 'H+'], 'G1P_ch': ['glucose-1-phosphate', 'G1P', 'glucose 1-phosphate']}
Evaluating 14/1075: BIOMD0000000014.xml
Evaluating 15/1075: BIOMD0000000015.xml

2025-11-20 12:19:23,483 - WARNING - Skipping BIOMD0000000016.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000015.txt
LLM response:
PRPP (chemical): "phosphoribosyl pyrophosphate", "phosphoribosyl diphosphate", "PRPP"
IMP (chemical): "inosine monophosphate", "inosine 5'-monophosphate", "IMP"
SAMP (chemical): "adenylosuccinate", "adenylosuccinic acid", "S-adenosylsuccinate"
ATP (chemical): "adenosine triphosphate", "adenosine 5'-triphosphate", "ATP"
SAM (chemical): "s-adenosylmethionine", "s-adenosyl-l-methionine", "SAMe"
XMP (chemical): "xanthosine monophosphate", "xanthosine 5'-monophosphate", "XMP"
GTP (chemical): "guanosine triphosphate", "guanosine 5'-triphosphate", "GTP"
dATP (chemical): "deoxyadenosine triphosphate", "deoxyadenosine 5'-triphosphate", "dATP"
dGTP (chemical): "deoxyguanosine triphosphate", "deoxyguanosine 5'-triphosphate", "dGTP"
HX (chemical): "hypoxanthine", "6-hypoxanthine", "HX"
Xa (chemical): "xanthine", "6-xanthine", "Xa"
Gua (chemical): "guanine", "2-amino-6-hydroxypurine", "Gua"
UA (chemical): "uric acid", "2,6,8-trihydroxypurine", "UA"
R5P (chemical): "ribose-5-phosphate", "d-ribose 5-phosphate", "R5P"
Pi (chemical): "phosphate", "inorganic phosphate", "Pi"
Ade (chemical): "adenine", "6-aminopurine", "Ade"
DNA_ (unknown): "DNA", "deoxyribonucleic acid", "DNA molecule"
RNA (unknown): "RNA", "ribonucleic acid", "RNA molecule"

Reason: All species with display names corresponding to known biochemical compounds were classified as chemicals. DNA_ and RNA were classified as unknown because they represent complex biomolecules rather than specific chemical compounds. The synonyms provided are based on common names and abbreviations used in biochemistry.
Synonyms dict: {'PRPP': ['phosphoribosyl pyrophosphate', 'phosphoribosyl diphosphate', 'PRPP'], 'IMP': ['inosine monophosphate', "inosine 5'-monophosphate", 'IMP'], 'SAMP': ['adenylosuccinate', 'adenylosuccinic acid', 'S-adenosylsuccinate'], 'ATP': ['adenosine triphosphate', "adenosine 5'-triphosphate", 'ATP'], 'SAM': ['s-adenosylmethionine', 's-adenosyl-l-methionine', 'SAMe'], 'XMP': ['xanthosine monophosphate', "xanthosine 5'-monophosphate", 'XMP'], 'GTP': ['guanosine triphosphate', "guanosine 5'-triphosphate", 'GTP'], 'dATP': ['deoxyadenosine triphosphate', "deoxyadenosine 5'-triphosphate", 'dATP'], 'dGTP': ['deoxyguanosine triphosphate', "deoxyguanosine 5'-triphosphate", 'dGTP'], 'HX': ['hypoxanthine', '6-hypoxanthine', 'HX'], 'Xa': ['xanthine', '6-xanthine', 'Xa'], 'Gua': ['guanine', '2-amino-6-hydroxypurine', 'Gua'], 'UA': ['uric acid', '2,6,8-trihydroxypurine', 'UA'], 'R5P': ['ribose-5-phosphate', 'd-ribose 5-phosphate', 'R5P'], 'Pi': ['phosphate', 'inorganic phosphate', 'Pi'], 'Ade': ['adenine', '6-aminopurine', 'Ade'], 'DNA_': ['DNA', 'deoxyribonucleic acid', 'DNA molecule'], 'RNA': ['RNA', 'ribonucleic acid', 'RNA molecule']}
Evaluating 16/1075: BIOMD0000000016.xml
Evaluating 17/1075: BIOMD0000000017.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000017.txt
LLM response:
ADP (chemical): "adenosine diphosphate", "ADP molecule", "adenosine 5'-diphosphate"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "diphosphopyridine nucleotide"
ATP (chemical): "adenosine triphosphate", "ATP molecule", "adenosine 5'-triphosphate"
NADH (chemical): "nicotinamide adenine dinucleotide + hydrogen", "NADH molecule", "reduced diphosphopyridine nucleotide"
pyruvate (chemical): "pyruvic acid", "2-oxopropanoic acid", "pyruvate ion"
lactate (chemical): "lactic acid", "2-hydroxypropanoic acid", "lactate ion"
CoA (chemical): "coenzyme A", "CoA molecule", "coenzyme A (non-acetylated)"
AcCoA (chemical): "acetyl-CoA", "acetyl coenzyme A", "acetyl-CoA molecule"
AcP (chemical): "acetyl phosphate", "acetylphosphate", "acetic phosphate"
Ac (chemical): "acetic acid", "ethanoic acid", "acetate ion"
AcO (chemical): "acetaldehyde", "ethanal", "acetaldehyde molecule"
EtOH (chemical): "ethanol", "ethyl alcohol", "ethanol molecule"
AcLac (chemical): "acetolactate", "2-hydroxy-2-methyl-3-oxobutanoic acid", "acetolactic acid"
AcetoinIn (chemical): "acetoin", "3-hydroxybutanone", "acetoin (internal)"
AcetoinOut (chemical): "acetoin", "3-hydroxybutanone", "acetoin (external)"
Butanediol (chemical): "2,3-butanediol", "butane-2,3-diol", "2,3-butanediol molecule"
O2 (chemical): "oxygen", "dioxygen", "oxygen molecule"
PO4 (chemical): "phosphate", "inorganic phosphate", "phosphate ion"

Reason: The species were identified as chemicals based on their involvement in metabolic reactions, such as the pyruvate branch, and their roles as substrates, products, or cofactors. The standardized names and synonyms were chosen based on common usage in biochemistry and the context of the model. The reactions and notes provided in the model helped to clarify the identities of the species, such as AcCoA being acetyl-CoA and AcLac being acetolactate.
Synonyms dict: {'ADP': ['adenosine diphosphate', 'ADP molecule', "adenosine 5'-diphosphate"], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'diphosphopyridine nucleotide'], 'ATP': ['adenosine triphosphate', 'ATP molecule', "adenosine 5'-triphosphate"], 'NADH': ['nicotinamide adenine dinucleotide + hydrogen', 'NADH molecule', 'reduced diphosphopyridine nucleotide'], 'pyruvate': ['pyruvic acid', '2-oxopropanoic acid', 'pyruvate ion'], 'lactate': ['lactic acid', '2-hydroxypropanoic acid', 'lactate ion'], 'CoA': ['coenzyme A', 'CoA molecule', 'coenzyme A (non-acetylated)'], 'AcCoA': ['acetyl-CoA', 'acetyl coenzyme A', 'acetyl-CoA molecule'], 'AcP': ['acetyl phosphate', 'acetylphosphate', 'acetic phosphate'], 'Ac': ['acetic acid', 'ethanoic acid', 'acetate ion'], 'AcO': ['acetaldehyde', 'ethanal', 'acetaldehyde molecule'], 'EtOH': ['ethanol', 'ethyl alcohol', 'ethanol molecule'], 'AcLac': ['acetolactate', '2-hydroxy-2-methyl-3-oxobutanoic acid', 'acetolactic acid'], 'AcetoinIn': ['acetoin', '3-hydroxybutanone', 'acetoin (internal)'], 'AcetoinOut': ['acetoin', '3-hydroxybutanone', 'acetoin (external)'], 'Butanediol': ['2,3-butanediol', 'butane-2,3-diol', '2,3-butanediol molecule'], 'O2': ['oxygen', 'dioxygen', 'oxygen molecule'], 'PO4': ['phosphate', 'inorganic phosphate', 'phosphate ion']}
Evaluating 18/1075: BIOMD0000000018.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000018.txt
LLM response:
FH2f (chemical): "dihydrofolate", "7,8-dihydrofolate", "DHF"
FH2b (chemical): "dihydrofolate bound", "bound dihydrofolate", "DHF bound"
FH4 (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
CH2FH4 (chemical): "5,10-methylene-tetrahydrofolate", "5,10-CH2-THF", "methylene-THF"
CH3FH4 (chemical): "5-methyl-tetrahydrofolate", "5-CH3-THF", "methyl-THF"
CHOFH4 (chemical): "10-formyl-tetrahydrofolate", "10-formyl-THF", "formyl-THF"
FFH2 (chemical): "10-formyl-dihydrofolate", "10-formyl-DHF", "formyl-DHF"
HCHO (chemical): "formaldehyde", "methanal", "HCHO"
AICAR (chemical): "5-amino-4-imidazolecarboxamide ribonucleotide", "AICAR", "ZMP"
dUMP (chemical): "deoxyuridine monophosphate", "dUMP", "deoxyuridylate"
serine (chemical): "L-serine", "serine", "L-ser"
formate (chemical): "formic acid", "formate", "HCOOH"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
glutamine (chemical): "L-glutamine", "glutamine", "L-gln"
glycine (chemical): "glycine", "Gly", "aminoacetic acid"
NADP (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP+", "NADP"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate reduced", "NADPH", "NADP reduced"
homocysteine (chemical): "homocysteine", "Hcy", "homocysteine thiolactone"
Reason: The species are identified based on their display names and roles in the folate cycle. Most species are chemicals, including folate derivatives, amino acids, and nucleotides. The entity types are determined by the context of the reactions and the display names. For example, FH2f and FH4 are identified as chemicals based on their display names and roles in the folate cycle. AICAR and dUMP are also identified as chemicals, as they are nucleotides involved in the purine and pyrimidine synthesis pathways. The amino acids serine, glutamine, glycine, and homocysteine are also identified as chemicals. NADP and NADPH are identified as chemicals, as they are electron carriers involved in various biochemical reactions.
Synonyms dict: {'FH2f': ['dihydrofolate', '7,8-dihydrofolate', 'DHF'], 'FH2b': ['dihydrofolate bound', 'bound dihydrofolate', 'DHF bound'], 'FH4': ['tetrahydrofolate', 'THF', 'tetrahydrofolic acid'], 'CH2FH4': ['5,10-methylene-tetrahydrofolate', '5,10-CH2-THF', 'methylene-THF'], 'CH3FH4': ['5-methyl-tetrahydrofolate', '5-CH3-THF', 'methyl-THF'], 'CHOFH4': ['10-formyl-tetrahydrofolate', '10-formyl-THF', 'formyl-THF'], 'FFH2': ['10-formyl-dihydrofolate', '10-formyl-DHF', 'formyl-DHF'], 'HCHO': ['formaldehyde', 'methanal', 'HCHO'], 'AICAR': ['5-amino-4-imidazolecarboxamide ribonucleotide', 'AICAR', 'ZMP'], 'dUMP': ['deoxyuridine monophosphate', 'dUMP', 'deoxyuridylate'], 'serine': ['L-serine', 'serine', 'L-ser'], 'formate': ['formic acid', 'formate', 'HCOOH'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'glutamine': ['L-glutamine', 'glutamine', 'L-gln'], 'glycine': ['glycine', 'Gly', 'aminoacetic acid'], 'NADP': ['nicotinamide adenine dinucleotide phosphate', 'NADP+', 'NADP'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate reduced', 'NADPH', 'NADP reduced'], 'homocysteine': ['homocysteine', 'Hcy', 'homocysteine thiolactone']}
Evaluating 19/1075: BIOMD0000000019.xml

2025-11-20 12:19:37,460 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:19:37,460 - WARNING - Skipping BIOMD0000000019.xml - no results generated
2025-11-20 12:19:37,466 - WARNING - Skipping BIOMD0000000020.xml - no results generated
2025-11-20 12:19:37,476 - WARNING - Skipping BIOMD0000000021.xml - no results generated
2025-11-20 12:19:37,489 - WARNING - Skipping BIOMD0000000022.xml - no results generated

Evaluating 20/1075: BIOMD0000000020.xml
Evaluating 21/1075: BIOMD0000000021.xml
Evaluating 22/1075: BIOMD0000000022.xml
Evaluating 23/1075: BIOMD0000000023.xml

2025-11-20 12:19:41,387 - WARNING - Skipping BIOMD0000000024.xml - no results generated
2025-11-20 12:19:41,390 - WARNING - Skipping BIOMD0000000025.xml - no results generated
2025-11-20 12:19:41,398 - WARNING - Skipping BIOMD0000000026.xml - no results generated
2025-11-20 12:19:41,402 - WARNING - Skipping BIOMD0000000027.xml - no results generated
2025-11-20 12:19:41,411 - WARNING - Skipping BIOMD0000000028.xml - no results generated
2025-11-20 12:19:41,417 - WARNING - Skipping BIOMD0000000029.xml - no results generated
2025-11-20 12:19:41,426 - WARNING - Skipping BIOMD0000000030.xml - no results generated
2025-11-20 12:19:41,430 - WARNING - Skipping BIOMD0000000031.xml - no results generated
2025-11-20 12:19:41,449 - WARNING - Skipping BIOMD0000000032.xml - no results generated
2025-11-20 12:19:41,463 - WARNING - Skipping BIOMD0000000033.xml - no results generated
2025-11-20 12:19:41,472 - WARNING - Skipping BIOMD0000000034.xml - no results generated
2025-11-20 12:19:41,480 - WARNING - Skipping BIOMD0000000035.xml - no results generated
2025-11-20 12:19:41,485 - WARNING - Skipping BIOMD0000000036.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000023.txt
LLM response:
Fru (chemical): "fructose", "D-fructose", "fruit sugar"
Glc (chemical): "glucose", "D-glucose", "blood sugar"
HexP (chemical): "hexose phosphate", "fructose-6-phosphate", "glucose-6-phosphate"
Suc6P (chemical): "sucrose-6-phosphate", "sucrose phosphate", "SP"
Suc (chemical): "sucrose", "table sugar", "saccharose"
Sucvac (unknown): "UNK", "sucrose vacuole",
Glcex (chemical): "extracellular glucose", "external glucose", "glucose_ex"
Fruex (chemical): "extracellular fructose", "external fructose", "fructose_ex"
glycolysis (unknown): "UNK", "glycolytic pathway",
phos (chemical): "inorganic phosphate", "phosphate", "Pi"
UDP (chemical): "uridine diphosphate", "UDP", "uridine 5'-diphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
Reason: The model appears to be a metabolic model of sucrose metabolism, involving glycolysis and phosphate reactions. Most species are identified as chemicals based on their roles in the reactions and common biochemical knowledge. Sucvac is unknown as it seems to represent a compartment or process rather than a specific chemical. Glycolysis is also unknown as it is a pathway rather than a specific molecule. Glcex and Fruex are identified as chemicals, representing extracellular glucose and fructose, respectively. Phos is identified as inorganic phosphate, a common chemical in biochemical reactions. UDP, ADP, and ATP are identified as nucleotides, which are chemicals involved in energy transfer reactions.
Synonyms dict: {'Fru': ['fructose', 'D-fructose', 'fruit sugar'], 'Glc': ['glucose', 'D-glucose', 'blood sugar'], 'HexP': ['hexose phosphate', 'fructose-6-phosphate', 'glucose-6-phosphate'], 'Suc6P': ['sucrose-6-phosphate', 'sucrose phosphate', 'SP'], 'Suc': ['sucrose', 'table sugar', 'saccharose'], 'Sucvac': ['UNK', 'sucrose vacuole'], 'Glcex': ['extracellular glucose', 'external glucose', 'glucose_ex'], 'Fruex': ['extracellular fructose', 'external fructose', 'fructose_ex'], 'glycolysis': ['UNK', 'glycolytic pathway'], 'phos': ['inorganic phosphate', 'phosphate', 'Pi'], 'UDP': ['uridine diphosphate', 'UDP', "uridine 5'-diphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"]}
Evaluating 24/1075: BIOMD0000000024.xml
Evaluating 25/1075: BIOMD0000000025.xml
Evaluating 26/1075: BIOMD0000000026.xml
Evaluating 27/1075: BIOMD0000000027.xml
Evaluating 28/1075: BIOMD0000000028.xml
Evaluating 29/1075: BIOMD0000000029.xml
Evaluating 30/1075: BIOMD0000000030.xml
Evaluating 31/1075: BIOMD0000000031.xml
Evaluating 32/1075: BIOMD0000000032.xml
Evaluating 33/1075: BIOMD0000000033.xml
Evaluating 34/1075: BIOMD0000000034.xml
Evaluating 35/1075: BIOMD0000000035.xml
Evaluating 36/1075: BIOMD0000000036.xml
Evaluating 37/1075: BIOMD0000000037.xml

2025-11-20 12:19:42,963 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000037.txt
LLM response:
Pfr (protein): "phytochrome far-red light absorbing form", "Pfr phytochrome", "phytochrome Pfr"
Pr (protein): "phytochrome red light absorbing form", "Pr phytochrome", "phytochrome Pr"
Gluc (chemical): "glucose", "D-glucose", "blood sugar"
Reason: Pfr and Pr are likely proteins because they are involved in a regulatory hierarchy between genes and have reactions that suggest a conformational change or activation/deactivation, which is consistent with phytochrome proteins. Gluc is likely a chemical because it is involved in a reaction with other species (Ya and Yi) and is a common chemical name (glucose).
Synonyms dict: {'Pfr': ['phytochrome far-red light absorbing form', 'Pfr phytochrome', 'phytochrome Pfr'], 'Pr': ['phytochrome red light absorbing form', 'Pr phytochrome', 'phytochrome Pr'], 'Gluc': ['glucose', 'D-glucose', 'blood sugar']}
Evaluating 38/1075: BIOMD0000000038.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000038.txt
LLM response:
PyrPI (chemical): "pyruvate phosphate", "phosphopyruvate", "Pyr-PI"
EIICBPGlc (chemical): "glucose-EIICB complex", "glucose-EIICB phosphate", "Glc-EIICB-P"
PEP (chemical): "phosphoenolpyruvate", "PEP", "2-phosphoenolpyruvate"
Pyr (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
GlcP (chemical): "glucose phosphate", "glucose-6-phosphate", "G6P"
Glc (chemical): "glucose", "D-glucose", "dextrose"
EI (unknown): "UNK"
EIP (unknown): "UNK"
EIICB (unknown): "UNK"
EIICBP (unknown): "UNK"
Reason: The species are annotated based on their involvement in the phosphotransferase system, a mechanism for glucose transport in bacteria. PyrPI, EIICBPGlc, PEP, Pyr, GlcP, and Glc are likely chemicals due to their roles as substrates or products in the reactions. EI, EIP, EIICB, and EIICBP are annotated as unknown due to lack of information about their specific roles or structures, but they are likely proteins or protein complexes involved in the phosphotransferase system.
Synonyms dict: {'PyrPI': ['pyruvate phosphate', 'phosphopyruvate', 'Pyr-PI'], 'EIICBPGlc': ['glucose-EIICB complex', 'glucose-EIICB phosphate', 'Glc-EIICB-P'], 'PEP': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvate'], 'Pyr': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'GlcP': ['glucose phosphate', 'glucose-6-phosphate', 'G6P'], 'Glc': ['glucose', 'D-glucose', 'dextrose'], 'EI': ['UNK'], 'EIP': ['UNK'], 'EIICB': ['UNK'], 'EIICBP': ['UNK']}
Evaluating 39/1075: BIOMD0000000039.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000039.txt
LLM response:
Ca_cyt (chemical): "calcium ion", "Ca2+", "calcium"
CaER (chemical): "endoplasmic reticulum calcium", "ER calcium", "calcium in endoplasmic reticulum"
CaM (chemical): "calmodulin", "calcium-calmodulin", "CaM protein"
CaPr (complex): "calcium-protein complex", "calcium bound protein", "protein-calcium complex"

Reason: The model "Marhl2000_CaOscillations" suggests a focus on calcium oscillations, implying that Ca_cyt, CaER, and CaM are related to calcium. Ca_cyt is likely calcium ion, CaER is calcium in the endoplasmic reticulum, and CaM is calmodulin, a calcium-binding protein. CaPr is a complex of calcium and a protein, as indicated by the reaction where it dissociates into Pr (protein) and Ca_cyt (calcium ion).
Synonyms dict: {'Ca_cyt': ['calcium ion', 'Ca2+', 'calcium'], 'CaER': ['endoplasmic reticulum calcium', 'ER calcium', 'calcium in endoplasmic reticulum'], 'CaM': ['calmodulin', 'calcium-calmodulin', 'CaM protein'], 'CaPr': ['calcium-protein complex', 'calcium bound protein', 'protein-calcium complex']}
Evaluating 40/1075: BIOMD0000000040.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000040.txt
LLM response:
Br (chemical): "bromide", "bromide ion", "Br-"
BrO3 (chemical): "bromate", "bromate ion", "BrO3-"
Reason: Both Br and BrO3 are identified as chemical species based on their display names and roles in the Belousov-Zhabotinsky reaction, a well-known chemical oscillation reaction. Br is bromide, a common chemical ion, and BrO3 is bromate, also a chemical ion, as indicated by their display names "Br-" and "BrO3-" respectively.
Synonyms dict: {'Br': ['bromide', 'bromide ion', 'Br-'], 'BrO3': ['bromate', 'bromate ion', 'BrO3-']}
Evaluating 41/1075: BIOMD0000000041.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000041.txt
LLM response:
ADPi (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
ATPi (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
Cri (chemical): "creatine", "creatinine", "methylguanidine"
PCri (chemical): "phosphocreatine", "creatine phosphate", "phosphocreatine ion"
PCr (chemical): "phosphocreatine", "creatine phosphate", "phosphocreatine ion"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
Cr (chemical): "creatine", "creatinine", "methylguanidine"
Pi (chemical): "inorganic phosphate", "phosphate ion", "orthophosphate"
P (chemical): "inorganic phosphate", "phosphate ion", "orthophosphate"

Reason: The species can be identified based on their roles in the creatine kinase reaction and energy metabolism in muscle cells. ADPi, ATPi, ADP, and ATP are forms of adenosine diphosphate and triphosphate, which are essential energy transfer molecules. Cri, PCri, PCr, and Cr are related to creatine and phosphocreatine, which play a crucial role in the phosphocreatine shuttle. Pi and P are inorganic phosphate ions, which are involved in various biochemical reactions. The 'i' suffix in some species names likely indicates their intracellular or ionic forms.
Synonyms dict: {'ADPi': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'ATPi': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'Cri': ['creatine', 'creatinine', 'methylguanidine'], 'PCri': ['phosphocreatine', 'creatine phosphate', 'phosphocreatine ion'], 'PCr': ['phosphocreatine', 'creatine phosphate', 'phosphocreatine ion'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'Cr': ['creatine', 'creatinine', 'methylguanidine'], 'Pi': ['inorganic phosphate', 'phosphate ion', 'orthophosphate'], 'P': ['inorganic phosphate', 'phosphate ion', 'orthophosphate']}
Evaluating 42/1075: BIOMD0000000042.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000042.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "adenosine 5'-triphosphate", "ATP"
ADP (chemical): "adenosine diphosphate", "adenosine 5'-diphosphate", "ADP"
AMP (chemical): "adenosine monophosphate", "adenosine 5'-monophosphate", "AMP"
GLC (chemical): "glucose", "D-glucose", "dextrose"
FBP (chemical): "fructose-1,6-bisphosphate", "fructose 1,6-bisphosphate", "FBP"
GAP (chemical): "glyceraldehyde 3-phosphate", "glyceraldehyde-3-phosphate", "G3P"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "nicotinamide adenine dinucleotide (oxidized form)"
NADH (chemical): "nicotinamide adenine dinucleotide (reduced form)", "NADH", "nicotinamide adenine dinucleotide + hydrogen"
DPG (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "1,3-DPG"
PEP (chemical): "phosphoenolpyruvate", "phosphoenolpyruvic acid", "PEP"
PYR (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
ACA (chemical): "acetaldehyde", "ethanal", "acetic aldehyde"
EtOH (chemical): "ethanol", "ethyl alcohol", "alcohol"
Reason: All species are annotated as chemicals because they are all metabolites involved in the glycolytic pathway, which is a series of chemical reactions. The standardized names and synonyms are based on common biochemical nomenclature. No genes or proteins are mentioned in the model, and all reactions involve chemical transformations, confirming the chemical entity type for each species.
Synonyms dict: {'ATP': ['adenosine triphosphate', "adenosine 5'-triphosphate", 'ATP'], 'ADP': ['adenosine diphosphate', "adenosine 5'-diphosphate", 'ADP'], 'AMP': ['adenosine monophosphate', "adenosine 5'-monophosphate", 'AMP'], 'GLC': ['glucose', 'D-glucose', 'dextrose'], 'FBP': ['fructose-1,6-bisphosphate', 'fructose 1,6-bisphosphate', 'FBP'], 'GAP': ['glyceraldehyde 3-phosphate', 'glyceraldehyde-3-phosphate', 'G3P'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'nicotinamide adenine dinucleotide (oxidized form)'], 'NADH': ['nicotinamide adenine dinucleotide (reduced form)', 'NADH', 'nicotinamide adenine dinucleotide + hydrogen'], 'DPG': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', '1,3-DPG'], 'PEP': ['phosphoenolpyruvate', 'phosphoenolpyruvic acid', 'PEP'], 'PYR': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'ACA': ['acetaldehyde', 'ethanal', 'acetic aldehyde'], 'EtOH': ['ethanol', 'ethyl alcohol', 'alcohol']}
Evaluating 43/1075: BIOMD0000000043.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000043.txt
LLM response:
EC (chemical): "calcium", "Ca2+", "calcium ion"
Z (chemical): "calcium", "Ca2+", "calcium ion"
Y (chemical): "calcium", "Ca2+", "calcium ion"
Reason: All species are likely to be calcium or calcium-related ions because the model is described as a "Calcium Oscillation" model, and the article discusses intracellular calcium oscillations, suggesting that the species are involved in the calcium signaling pathway. The reactions also suggest a cyclic relationship between the species, which is consistent with the oscillatory behavior of calcium ions in cellular signaling.
Synonyms dict: {'EC': ['calcium', 'Ca2+', 'calcium ion'], 'Z': ['calcium', 'Ca2+', 'calcium ion'], 'Y': ['calcium', 'Ca2+', 'calcium ion']}
Evaluating 44/1075: BIOMD0000000044.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000044.txt
LLM response:
EC (chemical): "extracellular calcium", "calcium ion", "Ca(2+)"
Z (chemical): "cytosolic calcium", "intracellular calcium", "Ca2+"
A (unknown): "UNK", "agonist", "stimulus"
Y (chemical): "inositol 1,4,5-trisphosphate", "IP3", "inositol trisphosphate"
Reason: EC and Z are likely to be related to calcium ions, given the model's focus on calcium oscillations. Y is probably inositol 1,4,5-trisphosphate (IP3) due to its mention in the model notes as a key component in the calcium release process. A is unknown, but may represent an agonist or stimulus, as it is not clearly defined in the provided information.
Synonyms dict: {'EC': ['extracellular calcium', 'calcium ion', 'Ca(2+)'], 'Z': ['cytosolic calcium', 'intracellular calcium', 'Ca2+'], 'A': ['UNK', 'agonist', 'stimulus'], 'Y': ['inositol 1,4,5-trisphosphate', 'IP3', 'inositol trisphosphate']}
Evaluating 45/1075: BIOMD0000000045.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000045.txt
LLM response:
EC (chemical): "calcium", "Ca2+", "calcium ion"
Z (chemical): "inositol 1,4,5-trisphosphate", "IP3", "inositol trisphosphate"
Y (chemical): "calcium", "Ca2+", "calcium ion"
X (chemical): "calcium", "Ca2+", "calcium ion"
Reason: The model is about calcium oscillations and the reactions involve calcium release and uptake, suggesting that EC, Z, Y, and X are related to calcium or signaling molecules involved in this process. Z is likely inositol 1,4,5-trisphosphate (IP3) due to its mention in the model notes as a key molecule in the signaling pathway. EC, Y, and X are likely calcium or calcium-related species due to the context of the model, but without more specific information, they are annotated as calcium.
Synonyms dict: {'EC': ['calcium', 'Ca2+', 'calcium ion'], 'Z': ['inositol 1,4,5-trisphosphate', 'IP3', 'inositol trisphosphate'], 'Y': ['calcium', 'Ca2+', 'calcium ion'], 'X': ['calcium', 'Ca2+', 'calcium ion']}
Evaluating 46/1075: BIOMD0000000046.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000046.txt
LLM response:
NADH (chemical): "nicotinamide adenine dinucleotide", "NADH", "reduced nicotinamide adenine dinucleotide"
O2 (chemical): "oxygen", "dioxygen", "molecular oxygen"
H2O2 (chemical): "hydrogen peroxide", "peroxide", "H2O2"
ArH (chemical): "arachidonic acid radical", "arachidonate", "eicosatetraenoic acid"
Ar (chemical): "arachidonic acid", "eicosatetraenoic acid", "all-cis-5,8,11,14-eicosatetraenoic acid"
NADrad (chemical): "nicotinamide adenine dinucleotide radical", "NAD radical", "NAD."
super (chemical): "superoxide", "superoxide anion", "dioxygen radical"
NAD2 (chemical): "nicotinamide adenine dinucleotide dimer", "NAD dimer", "NAD2"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "oxidized nicotinamide adenine dinucleotide"
O2g (chemical): "oxygen gas", "gaseous oxygen", "atmospheric oxygen"
NADHres (chemical): "reduced nicotinamide adenine dinucleotide reserve", "NADH reservoir", "NADH pool"
coI (unknown): "UNK"
coII (unknown): "UNK"
coIII (unknown): "UNK"
per2 (unknown): "UNK"
per3 (unknown): "UNK"

Reason: The model "Olsen2003_peroxidase" suggests a biochemical reaction network involving peroxidase activity. NADH, O2, H2O2, ArH, Ar, NADrad, super, NAD2, NAD, O2g, and NADHres are identified as chemicals based on their roles in the reactions and standard biochemical nomenclature. coI, coII, coIII, per2, and per3 are marked as unknown due to lack of information about their chemical structures or functions, although they seem to represent different states or forms of enzymes or intermediates in the peroxidase reaction.
Synonyms dict: {'NADH': ['nicotinamide adenine dinucleotide', 'NADH', 'reduced nicotinamide adenine dinucleotide'], 'O2': ['oxygen', 'dioxygen', 'molecular oxygen'], 'H2O2': ['hydrogen peroxide', 'peroxide', 'H2O2'], 'ArH': ['arachidonic acid radical', 'arachidonate', 'eicosatetraenoic acid'], 'Ar': ['arachidonic acid', 'eicosatetraenoic acid', 'all-cis-5,8,11,14-eicosatetraenoic acid'], 'NADrad': ['nicotinamide adenine dinucleotide radical', 'NAD radical', 'NAD.'], 'super': ['superoxide', 'superoxide anion', 'dioxygen radical'], 'NAD2': ['nicotinamide adenine dinucleotide dimer', 'NAD dimer', 'NAD2'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'oxidized nicotinamide adenine dinucleotide'], 'O2g': ['oxygen gas', 'gaseous oxygen', 'atmospheric oxygen'], 'NADHres': ['reduced nicotinamide adenine dinucleotide reserve', 'NADH reservoir', 'NADH pool'], 'coI': ['UNK'], 'coII': ['UNK'], 'coIII': ['UNK'], 'per2': ['UNK'], 'per3': ['UNK']}
Evaluating 47/1075: BIOMD0000000047.xml

2025-11-20 12:20:08,067 - WARNING - Skipping BIOMD0000000048.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000047.txt
LLM response:
CaER (chemical): "calcium endoplasmic reticulum", "endoplasmic reticulum calcium", "Ca2+ ER"
Ca_Cyt (chemical): "cytosolic calcium", "calcium cytosol", "Ca2+ cyt"
Reason: The model is related to calcium oscillations, and the reactions suggest the exchange of calcium between the endoplasmic reticulum (ER) and the cytosol, indicating that CaER and Ca_Cyt are likely to represent calcium ions in these cellular compartments.
Synonyms dict: {'CaER': ['calcium endoplasmic reticulum', 'endoplasmic reticulum calcium', 'Ca2+ ER'], 'Ca_Cyt': ['cytosolic calcium', 'calcium cytosol', 'Ca2+ cyt']}
Evaluating 48/1075: BIOMD0000000048.xml
Evaluating 49/1075: BIOMD0000000049.xml

2025-11-20 12:20:12,152 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000049.txt
LLM response:
Rap1_GDP (protein): "Rap1 GTP-binding protein", "Rap1A", "KREV-1"
Ras_GDP (protein): "Ras protein", "Ras GTPase", "HRAS"
B_Raf_Rap1_GTP (complex): "B-Raf-Rap1 complex", "BRAF-RAP1", "B-Raf-Rap1 GTP-bound complex"
B_Raf_Rap1_GTP_MEK (complex): "B-Raf-Rap1-MEK complex", "BRAF-RAP1-MEK", "B-Raf-Rap1-MEK signaling complex"
B_Raf_Rap1_GTP_pMEK (complex): "B-Raf-Rap1-pMEK complex", "BRAF-RAP1-pMEK", "B-Raf-Rap1-phospho-MEK complex"
B_Raf_Rap1_GTP_MEK_ERK (complex): "B-Raf-Rap1-MEK-ERK complex", "BRAF-RAP1-MEK-ERK", "B-Raf-Rap1-MEK-ERK signaling complex"
B_Raf_Rap1_GTP_pMEK_ERK (complex): "B-Raf-Rap1-pMEK-ERK complex", "BRAF-RAP1-pMEK-ERK", "B-Raf-Rap1-phospho-MEK-ERK complex"
Reason: The species are annotated based on their names and the context of the MAPK signaling pathway. Rap1_GDP and Ras_GDP are proteins, while B_Raf_Rap1_GTP and its related species are complexes formed by the interaction of B-Raf, Rap1, and other proteins. The entity types are determined by the presence of protein names (e.g., Rap1, Ras, B-Raf) and the context of the reactions, which involve protein-protein interactions and signaling cascades. The synonyms are chosen based on common names and abbreviations used in the field of molecular biology and signaling pathways.
Synonyms dict: {'Rap1_GDP': ['Rap1 GTP-binding protein', 'Rap1A', 'KREV-1'], 'Ras_GDP': ['Ras protein', 'Ras GTPase', 'HRAS'], 'B_Raf_Rap1_GTP': ['B-Raf-Rap1 complex', 'BRAF-RAP1', 'B-Raf-Rap1 GTP-bound complex'], 'B_Raf_Rap1_GTP_MEK': ['B-Raf-Rap1-MEK complex', 'BRAF-RAP1-MEK', 'B-Raf-Rap1-MEK signaling complex'], 'B_Raf_Rap1_GTP_pMEK': ['B-Raf-Rap1-pMEK complex', 'BRAF-RAP1-pMEK', 'B-Raf-Rap1-phospho-MEK complex'], 'B_Raf_Rap1_GTP_MEK_ERK': ['B-Raf-Rap1-MEK-ERK complex', 'BRAF-RAP1-MEK-ERK', 'B-Raf-Rap1-MEK-ERK signaling complex'], 'B_Raf_Rap1_GTP_pMEK_ERK': ['B-Raf-Rap1-pMEK-ERK complex', 'BRAF-RAP1-pMEK-ERK', 'B-Raf-Rap1-phospho-MEK-ERK complex']}
Evaluating 50/1075: BIOMD0000000050.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000050.txt
LLM response:
Gly (chemical): "glycine", "aminoacetic acid", "aminoethanoic acid"
FA (chemical): "formic acid", "methanoic acid", "hydrogen carboxylic acid"
AA (chemical): "acetic acid", "ethanoic acid", "methanecarboxylic acid"
Glu (chemical): "glucose", "D-glucose", "dextrose"
MG (chemical): "methylglyoxal", "pyruvaldehyde", "2-oxopropanal"
Reason: The species can be identified based on the context of the Amadori degradation model and the chemical reactions provided. Gly is likely glycine, an amino acid. FA and AA are likely formic acid and acetic acid, respectively, which are common products of carbohydrate degradation. Glu is likely glucose, a simple sugar. MG is likely methylglyoxal, a compound known to be formed during the degradation of carbohydrates.
Synonyms dict: {'Gly': ['glycine', 'aminoacetic acid', 'aminoethanoic acid'], 'FA': ['formic acid', 'methanoic acid', 'hydrogen carboxylic acid'], 'AA': ['acetic acid', 'ethanoic acid', 'methanecarboxylic acid'], 'Glu': ['glucose', 'D-glucose', 'dextrose'], 'MG': ['methylglyoxal', 'pyruvaldehyde', '2-oxopropanal']}
Evaluating 51/1075: BIOMD0000000051.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000051.txt
LLM response:
cpep (chemical): "Phosphoenolpyruvate", "PEP", "Phosphoenol pyruvate"
cglcex (chemical): "Glucose", "D-Glucose", "Extracellular Glucose"
cg6p (chemical): "Glucose-6-phosphate", "G6P", "D-Glucose 6-phosphate"
cpyr (chemical): "Pyruvate", "Pyruvic acid", "2-Oxopropanoic acid"
cf6p (chemical): "Fructose-6-phosphate", "F6P", "D-Fructose 6-phosphate"
cg1p (chemical): "Glucose-1-phosphate", "G1P", "D-Glucose 1-phosphate"
cpg (chemical): "6-Phosphogluconate", "6-PG", "D-Gluconate 6-phosphate"
cfdp (chemical): "Fructose-1,6-bisphosphate", "F1,6BP", "D-Fructose 1,6-bisphosphate"
csed7p (chemical): "Sedoheptulose-7-phosphate", "S7P", "D-Sedoheptulose 7-phosphate"
cgap (chemical): "Glyceraldehyde-3-phosphate", "G3P", "D-Glyceraldehyde 3-phosphate"
ce4p (chemical): "Erythrose-4-phosphate", "E4P", "D-Erythrose 4-phosphate"
cxyl5p (chemical): "Xylulose-5-phosphate", "X5P", "D-Xylulose 5-phosphate"
crib5p (chemical): "Ribose-5-phosphate", "R5P", "D-Ribose 5-phosphate"
cdhap (chemical): "Dihydroxyacetonephosphate", "DHAP", "D-Glyceraldehyde 3-phosphate"
cpgp (chemical): "1,3-Bisphosphoglycerate", "1,3BPG", "D-Glycerate 1,3-bisphosphate"
cpg3 (chemical): "3-Phosphoglycerate", "3PG", "D-Glycerate 3-phosphate"
cpg2 (chemical): "2-Phosphoglycerate", "2PG", "D-Glycerate 2-phosphate"
cribu5p (chemical): "Ribulose-5-phosphate", "Ru5P", "D-Ribulose 5-phosphate"
Reason: All species are assigned as chemicals because they are all metabolites involved in the carbon metabolism pathway, and their display names match known biochemical compounds. The standardized names and synonyms provided are based on common names used in biochemistry.
Synonyms dict: {'cpep': ['Phosphoenolpyruvate', 'PEP', 'Phosphoenol pyruvate'], 'cglcex': ['Glucose', 'D-Glucose', 'Extracellular Glucose'], 'cg6p': ['Glucose-6-phosphate', 'G6P', 'D-Glucose 6-phosphate'], 'cpyr': ['Pyruvate', 'Pyruvic acid', '2-Oxopropanoic acid'], 'cf6p': ['Fructose-6-phosphate', 'F6P', 'D-Fructose 6-phosphate'], 'cg1p': ['Glucose-1-phosphate', 'G1P', 'D-Glucose 1-phosphate'], 'cpg': ['6-Phosphogluconate', '6-PG', 'D-Gluconate 6-phosphate'], 'cfdp': ['Fructose-1,6-bisphosphate', 'F1,6BP', 'D-Fructose 1,6-bisphosphate'], 'csed7p': ['Sedoheptulose-7-phosphate', 'S7P', 'D-Sedoheptulose 7-phosphate'], 'cgap': ['Glyceraldehyde-3-phosphate', 'G3P', 'D-Glyceraldehyde 3-phosphate'], 'ce4p': ['Erythrose-4-phosphate', 'E4P', 'D-Erythrose 4-phosphate'], 'cxyl5p': ['Xylulose-5-phosphate', 'X5P', 'D-Xylulose 5-phosphate'], 'crib5p': ['Ribose-5-phosphate', 'R5P', 'D-Ribose 5-phosphate'], 'cdhap': ['Dihydroxyacetonephosphate', 'DHAP', 'D-Glyceraldehyde 3-phosphate'], 'cpgp': ['1,3-Bisphosphoglycerate', '1,3BPG', 'D-Glycerate 1,3-bisphosphate'], 'cpg3': ['3-Phosphoglycerate', '3PG', 'D-Glycerate 3-phosphate'], 'cpg2': ['2-Phosphoglycerate', '2PG', 'D-Glycerate 2-phosphate'], 'cribu5p': ['Ribulose-5-phosphate', 'Ru5P', 'D-Ribulose 5-phosphate']}
Evaluating 52/1075: BIOMD0000000052.xml

2025-11-20 12:20:22,124 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000052.txt
LLM response:
Glu (chemical): "glucose", "D-glucose", "blood sugar"
Formic_acid (chemical): "formic acid", "methanoic acid", "HCOOH"
Acetic_acid (chemical): "acetic acid", "ethanoic acid", "CH3COOH"
lys_R (protein): "lysine", "L-lysine", "protein lysine"

Reason: The model is a kinetic model of the Maillard reaction, which involves the reaction of amino acids (like lysine) with reducing sugars (like glucose). Glu is likely glucose, a common sugar, and Formic_acid and Acetic_acid are both organic acids that can be produced in the Maillard reaction. lys_R is likely a protein or amino acid, given its reaction with Glu to form Amadori, a known product of the Maillard reaction between amino acids and sugars.
Synonyms dict: {'Glu': ['glucose', 'D-glucose', 'blood sugar'], 'Formic_acid': ['formic acid', 'methanoic acid', 'HCOOH'], 'Acetic_acid': ['acetic acid', 'ethanoic acid', 'CH3COOH'], 'lys_R': ['lysine', 'L-lysine', 'protein lysine']}
Evaluating 53/1075: BIOMD0000000053.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000053.txt
LLM response:
Glucose (chemical): "glucose", "D-glucose", "blood sugar"
Lysine (chemical): "lysine", "L-lysine", "amino acid"
Glyoxal (chemical): "glyoxal", "ethanedial", "oxalaldehyde"
Reason: The species are all annotated as chemicals because they are involved in a series of chemical reactions, including the formation of Schiff bases and the production of CML, which is a known advanced glycosylation end-product. Glucose is a simple sugar, Lysine is an amino acid, and Glyoxal is a small organic compound, all of which are commonly involved in biochemical reactions.
Synonyms dict: {'Glucose': ['glucose', 'D-glucose', 'blood sugar'], 'Lysine': ['lysine', 'L-lysine', 'amino acid'], 'Glyoxal': ['glyoxal', 'ethanedial', 'oxalaldehyde']}
Evaluating 54/1075: BIOMD0000000054.xml

2025-11-20 12:20:24,684 - WARNING - Skipping BIOMD0000000055.xml - no results generated
2025-11-20 12:20:24,718 - WARNING - Skipping BIOMD0000000056.xml - no results generated
2025-11-20 12:20:24,723 - WARNING - Skipping BIOMD0000000057.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000054.txt
LLM response:
I (chemical): "ions", "inorganic ions", "metal ions"
E (chemical): "energy pool", "ATP", "adenosine triphosphate"
A (chemical): "adenylate pool", "adenylates", "AMP"

Reason: I is likely a chemical as it represents ions, E is also a chemical representing the energy pool which could be related to ATP, and A is a chemical representing the adenylate pool which includes adenylates such as AMP.
Synonyms dict: {'I': ['ions', 'inorganic ions', 'metal ions'], 'E': ['energy pool', 'ATP', 'adenosine triphosphate'], 'A': ['adenylate pool', 'adenylates', 'AMP']}
Evaluating 55/1075: BIOMD0000000055.xml
Evaluating 56/1075: BIOMD0000000056.xml
Evaluating 57/1075: BIOMD0000000057.xml
Evaluating 58/1075: BIOMD0000000058.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000058.txt
LLM response:
c1 (chemical): "Calcium ion", "Ca2+", "Calcium(2+)"
c2 (chemical): "Calcium ion", "Ca2+", "Calcium(2+)"
Reason: Both c1 and c2 are identified as "Calcium ion" in the display names, and their participation in reactions without any indication of being genes, proteins, or complexes suggests they are chemical species, specifically calcium ions. The synonyms provided are common names and symbols for calcium ions.
Synonyms dict: {'c1': ['Calcium ion', 'Ca2+', 'Calcium(2+)'], 'c2': ['Calcium ion', 'Ca2+', 'Calcium(2+)']}
Evaluating 59/1075: BIOMD0000000059.xml

2025-11-20 12:20:27,943 - WARNING - Skipping BIOMD0000000060.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000059.txt
LLM response:
Ca_cyt (chemical): "Calcium ion", "Ca2+", "Calcium"
Ca_er (chemical): "Calcium ion", "Ca2+", "Calcium"
IP3_cyt (chemical): "Inositol trisphosphate", "IP3", "D-myo-inositol 1,4,5-trisphosphate"
Na_cyt (chemical): "Sodium ion", "Na+", "Sodium"
ATP_cyt (chemical): "Adenosine triphosphate", "ATP", "Adenosine 5'-triphosphate"
ADP_cyt (chemical): "Adenosine diphosphate", "ADP", "Adenosine 5'-diphosphate"
Reason: All species have display names that directly indicate they are chemicals, and their participation in reactions also suggests they are chemicals, with calcium and sodium being ions, IP3 being a signaling molecule, and ATP and ADP being energy transfer molecules.
Synonyms dict: {'Ca_cyt': ['Calcium ion', 'Ca2+', 'Calcium'], 'Ca_er': ['Calcium ion', 'Ca2+', 'Calcium'], 'IP3_cyt': ['Inositol trisphosphate', 'IP3', 'D-myo-inositol 1,4,5-trisphosphate'], 'Na_cyt': ['Sodium ion', 'Na+', 'Sodium'], 'ATP_cyt': ['Adenosine triphosphate', 'ATP', "Adenosine 5'-triphosphate"], 'ADP_cyt': ['Adenosine diphosphate', 'ADP', "Adenosine 5'-diphosphate"]}
Evaluating 60/1075: BIOMD0000000060.xml
Evaluating 61/1075: BIOMD0000000061.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000061.txt
LLM response:
GlcX (chemical): "extracellular glucose", "glucose", "D-glucose"
Glc (chemical): "cytosolic glucose", "glucose", "D-glucose"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
G6P (chemical): "glucose-6-phosphate", "D-glucose-6-phosphate", "G6P"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
FBP (chemical): "fructose 1,6-bisphosphate", "fructose-1,6-bisphosphate", "F1,6BP"
GAP (chemical): "glyceraldehyde 3-phosphate", "D-glyceraldehyde 3-phosphate", "G3P"
DHAP (chemical): "dihydroxyacetone phosphate", "DHAP", "dihydroxyacetonephosphate"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "nicotinamide adenine dinucleotide oxidized form"
BPG (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "BPG"
NADH (chemical): "nicotinamide adenine dinucleotide reduced form", "NADH", "nicotinamide adenine dinucleotide reduced"
PEP (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
Pyr (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
ACA (chemical): "acetaldehyde", "ethanal", "acetaldehyde"
EtOH (chemical): "ethanol", "ethyl alcohol", "alcohol"
EtOHX (chemical): "extracellular ethanol", "ethanol", "ethyl alcohol"
Glyc (chemical): "glycerol", "glycerin", "1,2,3-propanetriol"
GlycX (chemical): "extracellular glycerol", "glycerol", "glycerin"
ACAX (chemical): "extracellular acetaldehyde", "acetaldehyde", "ethanal"
CNX (chemical): "cyanide", "hydrogen cyanide", "CN-"
CNX0 (chemical): "mixed flow cyanide", "cyanide", "hydrogen cyanide"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
CNX0 (chemical): "mixed flow cyanide", "cyanide", "hydrogen cyanide"
GlcX0 (chemical): "mixed flow glucose", "glucose", "D-glucose"
Reason: The model is a glycolysis model, which is a metabolic pathway that converts glucose into pyruvate. All species are metabolites or cofactors involved in this pathway, and their entity types are therefore chemical. The standardized names and synonyms are based on common names used in biochemistry. The species with "X" or "0" suffixes are likely to represent extracellular or mixed flow species, and their names and synonyms reflect this.
Synonyms dict: {'GlcX': ['extracellular glucose', 'glucose', 'D-glucose'], 'Glc': ['cytosolic glucose', 'glucose', 'D-glucose'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'G6P': ['glucose-6-phosphate', 'D-glucose-6-phosphate', 'G6P'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'FBP': ['fructose 1,6-bisphosphate', 'fructose-1,6-bisphosphate', 'F1,6BP'], 'GAP': ['glyceraldehyde 3-phosphate', 'D-glyceraldehyde 3-phosphate', 'G3P'], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP', 'dihydroxyacetonephosphate'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'nicotinamide adenine dinucleotide oxidized form'], 'BPG': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', 'BPG'], 'NADH': ['nicotinamide adenine dinucleotide reduced form', 'NADH', 'nicotinamide adenine dinucleotide reduced'], 'PEP': ['phosphoenolpyruvate', 'PEP', 'phosphoenolpyruvic acid'], 'Pyr': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'ACA': ['acetaldehyde', 'ethanal', 'acetaldehyde'], 'EtOH': ['ethanol', 'ethyl alcohol', 'alcohol'], 'EtOHX': ['extracellular ethanol', 'ethanol', 'ethyl alcohol'], 'Glyc': ['glycerol', 'glycerin', '1,2,3-propanetriol'], 'GlycX': ['extracellular glycerol', 'glycerol', 'glycerin'], 'ACAX': ['extracellular acetaldehyde', 'acetaldehyde', 'ethanal'], 'CNX': ['cyanide', 'hydrogen cyanide', 'CN-'], 'CNX0': ['mixed flow cyanide', 'cyanide', 'hydrogen cyanide'], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'GlcX0': ['mixed flow glucose', 'glucose', 'D-glucose']}
Evaluating 62/1075: BIOMD0000000062.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000062.txt
LLM response:
Ts (chemical): "tryptophan", "L-tryptophan", "trp"
Tt (chemical): "total tryptophan", "tryptophan total", "tryptophan concentration"
Reason: Ts and Tt are both related to tryptophan, a chemical compound, in the context of the tryptophan operon model. Ts is "Synthesized tryptophan" and Tt is "Total tryptophan", indicating they represent different aspects of tryptophan, but both are chemical in nature.
Synonyms dict: {'Ts': ['tryptophan', 'L-tryptophan', 'trp'], 'Tt': ['total tryptophan', 'tryptophan total', 'tryptophan concentration']}
Evaluating 63/1075: BIOMD0000000063.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000063.txt
LLM response:
Glci (chemical): "Glucose", "D-Glucose", "Blood sugar"
ATP (chemical): "Adenosine triphosphate", "Adenosine 5'-triphosphate", "ATPase"
G6P (chemical): "Glucose-6-phosphate", "D-Glucose 6-phosphate", "G6Pase"
FDP (chemical): "Fructose-1,6-bisphosphate", "Fructose 1,6-diphosphate", "FBP"
PEP (chemical): "Phosphoenolpyruvate", "Phosphoenolpyruvic acid", "PEP carboxykinase"
Gly (chemical): "Glycerol", "Glycerin", "Propan-1,2,3-triol"
EtOH (chemical): "Ethanol", "Ethyl alcohol", "Alcohol"
Carbo (complex): "Glycogen", "Trehalose", "Polysaccharide"
Reason: The species are identified based on their display names and the context of the fermentation pathway kinetics model. Glci, ATP, G6P, FDP, PEP, Gly, and EtOH are all chemical species involved in the metabolic pathway. Carbo is considered a complex because it represents a combination of glycogen and trehalose, which are both polysaccharides. The standardized names and synonyms provided are based on common biochemical nomenclature and are ranked by likelihood based on their relevance to the model and the display names provided.
Synonyms dict: {'Glci': ['Glucose', 'D-Glucose', 'Blood sugar'], 'ATP': ['Adenosine triphosphate', "Adenosine 5'-triphosphate", 'ATPase'], 'G6P': ['Glucose-6-phosphate', 'D-Glucose 6-phosphate', 'G6Pase'], 'FDP': ['Fructose-1,6-bisphosphate', 'Fructose 1,6-diphosphate', 'FBP'], 'PEP': ['Phosphoenolpyruvate', 'Phosphoenolpyruvic acid', 'PEP carboxykinase'], 'Gly': ['Glycerol', 'Glycerin', 'Propan-1,2,3-triol'], 'EtOH': ['Ethanol', 'Ethyl alcohol', 'Alcohol'], 'Carbo': ['Glycogen', 'Trehalose', 'Polysaccharide']}
Evaluating 64/1075: BIOMD0000000064.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000064.txt
LLM response:
GLCi (chemical): "Glucose", "D-Glucose", "Blood sugar"
G6P (chemical): "Glucose-6-phosphate", "D-Glucose-6-phosphate", "G6P"
F6P (chemical): "Fructose-6-phosphate", "D-Fructose-6-phosphate", "F6P"
F16P (chemical): "Fructose-1,6-bisphosphate", "D-Fructose-1,6-bisphosphate", "F1,6BP"
TRIO (chemical): "Triose phosphate", "Glyceraldehyde-3-phosphate", "Dihydroxyacetone phosphate"
BPG (chemical): "1,3-Bisphosphoglycerate", "1,3-Bisphosphoglyceric acid", "Bisphosphoglycerate"
P3G (chemical): "3-Phosphoglycerate", "3-Phosphoglyceric acid", "PG"
P2G (chemical): "2-Phosphoglycerate", "2-Phosphoglyceric acid", "2-PG"
PEP (chemical): "Phosphoenolpyruvate", "Phosphoenolpyruvic acid", "PEP"
PYR (chemical): "Pyruvate", "Pyruvic acid", "2-Oxopropanoic acid"
ACE (chemical): "Acetaldehyde", "Ethanal", "Acetic aldehyde"
P (chemical): "Phosphate", "Inorganic phosphate", "High energy phosphate"
NAD (chemical): "Nicotinamide adenine dinucleotide", "NAD+", "Diphosphopyridine nucleotide"
NADH (chemical): "Nicotinamide adenine dinucleotide reduced", "NADH", "Reduced diphosphopyridine nucleotide"
Trh (chemical): "Trehalose", "Mycose", "Trehalose sugar"
CO2 (chemical): "Carbon dioxide", "CO2", "Carbonic acid"
SUCC (chemical): "Succinate", "Succinic acid", "Butanedioic acid"
GLCo (chemical): "Glucose", "D-Glucose", "Extracellular glucose"
ETOH (chemical): "Ethanol", "Ethyl alcohol", "Alcohol"
GLY (chemical): "Glycerol", "Glycerin", "Propanetriol"
ATP (chemical): "Adenosine triphosphate", "ATP", "Adenosine 5'-triphosphate"
ADP (chemical): "Adenosine diphosphate", "ADP", "Adenosine 5'-diphosphate"
AMP (chemical): "Adenosine monophosphate", "AMP", "Adenosine 5'-monophosphate"
SUM_P (chemical): "Sum of adenine nucleotides", "Total adenine nucleotides", "AXP"
F26BP (chemical): "Fructose-2,6-bisphosphate", "D-Fructose-2,6-bisphosphate", "F2,6BP"
Reason: The species are annotated based on their display names and roles in the glycolysis model. Most species are identified as chemicals, including metabolites, cofactors, and energy carriers. The model does not include genes or proteins as species, so none are annotated as such. The entity types are determined based on the biochemical context and the display names provided in the model.
Synonyms dict: {'GLCi': ['Glucose', 'D-Glucose', 'Blood sugar'], 'G6P': ['Glucose-6-phosphate', 'D-Glucose-6-phosphate', 'G6P'], 'F6P': ['Fructose-6-phosphate', 'D-Fructose-6-phosphate', 'F6P'], 'F16P': ['Fructose-1,6-bisphosphate', 'D-Fructose-1,6-bisphosphate', 'F1,6BP'], 'TRIO': ['Triose phosphate', 'Glyceraldehyde-3-phosphate', 'Dihydroxyacetone phosphate'], 'BPG': ['1,3-Bisphosphoglycerate', '1,3-Bisphosphoglyceric acid', 'Bisphosphoglycerate'], 'P3G': ['3-Phosphoglycerate', '3-Phosphoglyceric acid', 'PG'], 'P2G': ['2-Phosphoglycerate', '2-Phosphoglyceric acid', '2-PG'], 'PEP': ['Phosphoenolpyruvate', 'Phosphoenolpyruvic acid', 'PEP'], 'PYR': ['Pyruvate', 'Pyruvic acid', '2-Oxopropanoic acid'], 'ACE': ['Acetaldehyde', 'Ethanal', 'Acetic aldehyde'], 'P': ['Phosphate', 'Inorganic phosphate', 'High energy phosphate'], 'NAD': ['Nicotinamide adenine dinucleotide', 'NAD+', 'Diphosphopyridine nucleotide'], 'NADH': ['Nicotinamide adenine dinucleotide reduced', 'NADH', 'Reduced diphosphopyridine nucleotide'], 'Trh': ['Trehalose', 'Mycose', 'Trehalose sugar'], 'CO2': ['Carbon dioxide', 'CO2', 'Carbonic acid'], 'SUCC': ['Succinate', 'Succinic acid', 'Butanedioic acid'], 'GLCo': ['Glucose', 'D-Glucose', 'Extracellular glucose'], 'ETOH': ['Ethanol', 'Ethyl alcohol', 'Alcohol'], 'GLY': ['Glycerol', 'Glycerin', 'Propanetriol'], 'ATP': ['Adenosine triphosphate', 'ATP', "Adenosine 5'-triphosphate"], 'ADP': ['Adenosine diphosphate', 'ADP', "Adenosine 5'-diphosphate"], 'AMP': ['Adenosine monophosphate', 'AMP', "Adenosine 5'-monophosphate"], 'SUM_P': ['Sum of adenine nucleotides', 'Total adenine nucleotides', 'AXP'], 'F26BP': ['Fructose-2,6-bisphosphate', 'D-Fructose-2,6-bisphosphate', 'F2,6BP']}
Evaluating 65/1075: BIOMD0000000065.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000065.txt
LLM response:
A (chemical): "allolactose", "1,6-anhydro-beta-D-galactopyranose", "4-O-β-D-Galactopyranosyl-D-Glucose"
L (chemical): "lactose", "lactose_internal", "β-D-Galactopyranosyl-(1→4)-D-Glucose"
L_e (chemical): "external lactose", "lactose_external", "D-Lactose"

Reason: The species A is identified as a chemical because it is a metabolite involved in the lac operon, specifically allolactose, which is a lactose metabolite. L and L_e are also chemicals, as they represent internal and external lactose, respectively, which are carbohydrates involved in the lac operon regulation. The names provided are standardized and common synonyms for these species, with the most likely names listed first.
Synonyms dict: {'A': ['allolactose', '1,6-anhydro-beta-D-galactopyranose', '4-O-β-D-Galactopyranosyl-D-Glucose'], 'L': ['lactose', 'lactose_internal', 'β-D-Galactopyranosyl-(1→4)-D-Glucose'], 'L_e': ['external lactose', 'lactose_external', 'D-Lactose']}
Evaluating 66/1075: BIOMD0000000066.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000066.txt
LLM response:
aspp (chemical): "Aspartyl phosphate", "L-aspartyl phosphate", "Aspartate phosphate"
asa (chemical): "Aspartate beta-semialdehyde", "Aspartic beta-semialdehyde", "Aspartate-β-semialdehyde"
hs (chemical): "Homoserine", "L-Homoserine", "Homoserine amino acid"
hsp (chemical): "O-Phospho-homoserine", "L-Homoserine phosphate", "Phosphohomoserine"
phos (chemical): "Phosphate", "Inorganic phosphate", "Orthophosphate"
thr (chemical): "Threonine", "L-Threonine", "Threonine amino acid"
asp (chemical): "Aspartate", "L-Aspartate", "Aspartic acid"
nadp (chemical): "NADP+", "Nicotinamide adenine dinucleotide phosphate", "NADP oxidized form"
nadph (chemical): "NADPH", "Nicotinamide adenine dinucleotide phosphate reduced form", "NADP reduced form"
adp (chemical): "ADP", "Adenosine diphosphate", "Adenosine 5'-diphosphate"
atp (chemical): "ATP", "Adenosine triphosphate", "Adenosine 5'-triphosphate"
Reason: All species are identified as chemicals because they are all involved in biochemical reactions and are known metabolites or cofactors in the threonine synthesis pathway. The standardized names and synonyms are based on common usage in biochemistry and the provided display names in the model.
Synonyms dict: {'aspp': ['Aspartyl phosphate', 'L-aspartyl phosphate', 'Aspartate phosphate'], 'asa': ['Aspartate beta-semialdehyde', 'Aspartic beta-semialdehyde', 'Aspartate-β-semialdehyde'], 'hs': ['Homoserine', 'L-Homoserine', 'Homoserine amino acid'], 'hsp': ['O-Phospho-homoserine', 'L-Homoserine phosphate', 'Phosphohomoserine'], 'phos': ['Phosphate', 'Inorganic phosphate', 'Orthophosphate'], 'thr': ['Threonine', 'L-Threonine', 'Threonine amino acid'], 'asp': ['Aspartate', 'L-Aspartate', 'Aspartic acid'], 'nadp': ['NADP+', 'Nicotinamide adenine dinucleotide phosphate', 'NADP oxidized form'], 'nadph': ['NADPH', 'Nicotinamide adenine dinucleotide phosphate reduced form', 'NADP reduced form'], 'adp': ['ADP', 'Adenosine diphosphate', "Adenosine 5'-diphosphate"], 'atp': ['ATP', 'Adenosine triphosphate', "Adenosine 5'-triphosphate"]}
Evaluating 67/1075: BIOMD0000000067.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000067.txt
LLM response:
AcCoA (chemical): "acetyl-CoA", "acetyl coenzyme A", "CoA-acetyl"
AcP (chemical): "acetyl phosphate", "acetylphosphate", "AcP"
OAc (chemical): "acetate", "acetic acid", "acetate ion"
HOAc (chemical): "protonated acetate", "acetic acid", "ethanoic acid"
HOAc_E (chemical): "exported acetate", "extracellular acetate", "acetate export"

Reason: The species can be identified as chemicals based on their display names and roles in the metabolic oscillator model. AcCoA is a key molecule in metabolism, AcP is an intermediate in the conversion of AcCoA to acetate, OAc is the acetate ion, HOAc is the protonated form of acetate, and HOAc_E represents the exported or extracellular form of acetate. The names provided are standardized or common synonyms for each species, ranked by likelihood based on their usage in biochemical literature.
Synonyms dict: {'AcCoA': ['acetyl-CoA', 'acetyl coenzyme A', 'CoA-acetyl'], 'AcP': ['acetyl phosphate', 'acetylphosphate', 'AcP'], 'OAc': ['acetate', 'acetic acid', 'acetate ion'], 'HOAc': ['protonated acetate', 'acetic acid', 'ethanoic acid'], 'HOAc_E': ['exported acetate', 'extracellular acetate', 'acetate export']}
Evaluating 68/1075: BIOMD0000000068.xml

2025-11-20 12:20:57,851 - WARNING - Skipping BIOMD0000000069.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000068.txt
LLM response:
Phser (chemical): "Phosphohomoserine", "O-Phosphohomoserine", "L-Phosphohomoserine"
Thr (chemical): "Threonine", "L-Threonine", "2-Amino-3-hydroxybutyric acid"
Cystathionine (chemical): "Cystathionine", "L-Cystathionine", "3-(2-Amino-2-carboxyethylthio)propanoic acid"
Hser (chemical): "Homoserine", "L-Homoserine", "2-Amino-4-hydroxybutyric acid"
Phi (chemical): "Inorganic phosphate", "Phosphate ion", "Orthophosphate"
Cys (chemical): "Cysteine", "L-Cysteine", "3-Mercaptopropanoic acid"
AdoMet (chemical): "S-Adenosylmethionine", "AdoMet", "S-Adenosyl-L-methionine"

Reason: The model "Curien2003_MetThr_synthesis" describes the metabolic branch-point between the methionine and threonine biosynthesis pathways, and all the species are involved in this biochemical process as reactants or products, indicating they are chemicals. The display names and reactions provided in the model also support this classification.
Synonyms dict: {'Phser': ['Phosphohomoserine', 'O-Phosphohomoserine', 'L-Phosphohomoserine'], 'Thr': ['Threonine', 'L-Threonine', '2-Amino-3-hydroxybutyric acid'], 'Cystathionine': ['Cystathionine', 'L-Cystathionine', '3-(2-Amino-2-carboxyethylthio)propanoic acid'], 'Hser': ['Homoserine', 'L-Homoserine', '2-Amino-4-hydroxybutyric acid'], 'Phi': ['Inorganic phosphate', 'Phosphate ion', 'Orthophosphate'], 'Cys': ['Cysteine', 'L-Cysteine', '3-Mercaptopropanoic acid'], 'AdoMet': ['S-Adenosylmethionine', 'AdoMet', 'S-Adenosyl-L-methionine']}
Evaluating 69/1075: BIOMD0000000069.xml
Evaluating 70/1075: BIOMD0000000070.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000070.txt
LLM response:
Glcin (chemical): "Glucose", "D-Glucose", "Blood glucose"
MgATP (chemical): "Magnesium ATP", "MgATP", "Adenosine triphosphate"
Glc6P (chemical): "Glucose 6-phosphate", "D-Glucose 6-phosphate", "G6P"
MgADP (chemical): "Magnesium ADP", "MgADP", "Adenosine diphosphate"
Fru6P (chemical): "Fructose 6-phosphate", "D-Fructose 6-phosphate", "F6P"
Fru16P2 (chemical): "Fructose 1,6-bisphosphate", "D-Fructose 1,6-bisphosphate", "F1,6BP"
GraP (chemical): "Glyceraldehyde 3-phosphate", "D-Glyceraldehyde 3-phosphate", "G3P"
DHAP (chemical): "Dihydroxyacetone phosphate", "DHA", "DHAP"
NAD (chemical): "Nicotinamide adenine dinucleotide", "NAD+", "DPN"
Gri13P2 (chemical): "1,3-Bisphosphoglycerate", "1,3-Bisphosphoglyceric acid", "1,3BPG"
NADH (chemical): "Nicotinamide adenine dinucleotide reduced", "NADH", "DPNH"
Gri3P (chemical): "3-Phosphoglycerate", "3-Phosphoglyceric acid", "3PG"
Gri23P2f (chemical): "2,3-Bisphosphoglycerate", "2,3-Bisphosphoglyceric acid", "2,3BPG"
Gri2P (chemical): "2-Phosphoglycerate", "2-Phosphoglyceric acid", "2PG"
PEP (chemical): "Phosphoenolpyruvate", "PEP", "Phosphoenolpyruvic acid"
Pyr (chemical): "Pyruvate", "Pyruvic acid", "Pyr"
Lac (chemical): "Lactate", "Lactic acid", "Lac"
NADPHf (chemical): "Nicotinamide adenine dinucleotide phosphate reduced", "NADPH", "TPNH"
NADPf (chemical): "Nicotinamide adenine dinucleotide phosphate", "NADP+", "TPN"
AMPf (chemical): "Adenosine monophosphate", "AMP", "Adenylate"
ADPf (chemical): "Adenosine diphosphate", "ADP", "Adenosine pyrophosphate"
GlcA6P (chemical): "Glucuronic acid 6-phosphate", "Glucuronate 6-phosphate", "G6P"
Rul5P (chemical): "Ribulose 5-phosphate", "Ribulose-5-phosphate", "Ru5P"
GSSG (chemical): "Glutathione disulfide", "Oxidized glutathione", "GSSG"
GSH (chemical): "Glutathione reduced", "Reduced glutathione", "GSH"
Xul5P (chemical): "Xylulose 5-phosphate", "Xylulose-5-phosphate", "Xu5P"
Rib5P (chemical): "Ribose 5-phosphate", "Ribose-5-phosphate", "R5P"
Sed7P (chemical): "Sedoheptulose 7-phosphate", "Sedoheptulose-7-phosphate", "S7P"
E4P (chemical): "Erythrose 4-phosphate", "Erythrose-4-phosphate", "E4P"
MgAMP (chemical): "Magnesium adenosine monophosphate", "MgAMP", "Magnesium adenylate"
PRPP (chemical): "5-Phosphoribosyl-1-pyrophosphate", "PRPP", "Phosphoribosyl pyrophosphate"
Mgf (chemical): "Magnesium ion", "Mg2+", "Magnesium"
ATPf (chemical): "Adenosine triphosphate", "ATP", "Adenosine 5'-triphosphate"
Lacex (chemical): "External lactate", "Lactate external", "Lacex"
Pyrex (chemical): "External pyruvate", "Pyruvate external", "Pyrex"
Glcout (chemical): "External glucose", "Glucose external", "Glcout"
P1NADP (complex): "Protein 1 bound NADP", "NADP bound protein 1", "P1-NADP"
P1NADPH (complex): "Protein 1 bound NADPH", "NADPH bound protein 1", "P1-NADPH"
P2NADP (complex): "Protein 2 bound NADP", "NADP bound protein 2", "P2-NADP"
P2NADPH (complex): "Protein 2 bound NADPH", "NADPH bound protein 2", "P2-NADPH"
P1f (protein): "Protein 1", "P1", "Protein1"
P2f (protein): "Protein 2", "P2", "Protein2"
MgGri23P2 (chemical): "Magnesium 2,3-bisphosphoglycerate", "Mg 2,3BPG", "MgGri23P2"

Reason: Most of the species are identified as chemicals based on their names and roles in the model, which appears to be a metabolic network. The species with "Mg" prefixes are likely magnesium complexes of the corresponding chemicals. The species with "P1" and "P2" prefixes are likely proteins, and those with "NADP" and "NADPH" are likely protein-NADP and protein-NADPH complexes, respectively. The external species (Lacex, Pyrex, Glcout) are likely chemicals as well, representing external pools of lactate, pyruvate, and glucose.
Synonyms dict: {'Glcin': ['Glucose', 'D-Glucose', 'Blood glucose'], 'MgATP': ['Magnesium ATP', 'MgATP', 'Adenosine triphosphate'], 'Glc6P': ['Glucose 6-phosphate', 'D-Glucose 6-phosphate', 'G6P'], 'MgADP': ['Magnesium ADP', 'MgADP', 'Adenosine diphosphate'], 'Fru6P': ['Fructose 6-phosphate', 'D-Fructose 6-phosphate', 'F6P'], 'Fru16P2': ['Fructose 1,6-bisphosphate', 'D-Fructose 1,6-bisphosphate', 'F1,6BP'], 'GraP': ['Glyceraldehyde 3-phosphate', 'D-Glyceraldehyde 3-phosphate', 'G3P'], 'DHAP': ['Dihydroxyacetone phosphate', 'DHA', 'DHAP'], 'NAD': ['Nicotinamide adenine dinucleotide', 'NAD+', 'DPN'], 'Gri13P2': ['1,3-Bisphosphoglycerate', '1,3-Bisphosphoglyceric acid', '1,3BPG'], 'NADH': ['Nicotinamide adenine dinucleotide reduced', 'NADH', 'DPNH'], 'Gri3P': ['3-Phosphoglycerate', '3-Phosphoglyceric acid', '3PG'], 'Gri23P2f': ['2,3-Bisphosphoglycerate', '2,3-Bisphosphoglyceric acid', '2,3BPG'], 'Gri2P': ['2-Phosphoglycerate', '2-Phosphoglyceric acid', '2PG'], 'PEP': ['Phosphoenolpyruvate', 'PEP', 'Phosphoenolpyruvic acid'], 'Pyr': ['Pyruvate', 'Pyruvic acid', 'Pyr'], 'Lac': ['Lactate', 'Lactic acid', 'Lac'], 'NADPHf': ['Nicotinamide adenine dinucleotide phosphate reduced', 'NADPH', 'TPNH'], 'NADPf': ['Nicotinamide adenine dinucleotide phosphate', 'NADP+', 'TPN'], 'AMPf': ['Adenosine monophosphate', 'AMP', 'Adenylate'], 'ADPf': ['Adenosine diphosphate', 'ADP', 'Adenosine pyrophosphate'], 'GlcA6P': ['Glucuronic acid 6-phosphate', 'Glucuronate 6-phosphate', 'G6P'], 'Rul5P': ['Ribulose 5-phosphate', 'Ribulose-5-phosphate', 'Ru5P'], 'GSSG': ['Glutathione disulfide', 'Oxidized glutathione', 'GSSG'], 'GSH': ['Glutathione reduced', 'Reduced glutathione', 'GSH'], 'Xul5P': ['Xylulose 5-phosphate', 'Xylulose-5-phosphate', 'Xu5P'], 'Rib5P': ['Ribose 5-phosphate', 'Ribose-5-phosphate', 'R5P'], 'Sed7P': ['Sedoheptulose 7-phosphate', 'Sedoheptulose-7-phosphate', 'S7P'], 'E4P': ['Erythrose 4-phosphate', 'Erythrose-4-phosphate', 'E4P'], 'MgAMP': ['Magnesium adenosine monophosphate', 'MgAMP', 'Magnesium adenylate'], 'PRPP': ['5-Phosphoribosyl-1-pyrophosphate', 'PRPP', 'Phosphoribosyl pyrophosphate'], 'Mgf': ['Magnesium ion', 'Mg2+', 'Magnesium'], 'ATPf': ['Adenosine triphosphate', 'ATP', "Adenosine 5'-triphosphate"], 'Lacex': ['External lactate', 'Lactate external', 'Lacex'], 'Pyrex': ['External pyruvate', 'Pyruvate external', 'Pyrex'], 'Glcout': ['External glucose', 'Glucose external', 'Glcout'], 'P1NADP': ['Protein 1 bound NADP', 'NADP bound protein 1', 'P1-NADP'], 'P1NADPH': ['Protein 1 bound NADPH', 'NADPH bound protein 1', 'P1-NADPH'], 'P2NADP': ['Protein 2 bound NADP', 'NADP bound protein 2', 'P2-NADP'], 'P2NADPH': ['Protein 2 bound NADPH', 'NADPH bound protein 2', 'P2-NADPH'], 'P1f': ['Protein 1', 'P1', 'Protein1'], 'P2f': ['Protein 2', 'P2', 'Protein2'], 'MgGri23P2': ['Magnesium 2,3-bisphosphoglycerate', 'Mg 2,3BPG', 'MgGri23P2']}
Evaluating 71/1075: BIOMD0000000071.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000071.txt
LLM response:
GlcI (chemical): "Glucose", "D-Glucose", "Blood sugar"
Glc6P (chemical): "Glucose 6-phosphate", "D-Glucose 6-phosphate", "G6P"
Fru6P (chemical): "Fructose 6-phosphate", "D-Fructose 6-phosphate", "F6P"
Fru16BP (chemical): "Fructose 1,6-bisphosphate", "D-Fructose 1,6-bisphosphate", "F1,6BP"
DHAP (chemical): "Dihydroxyacetone phosphate", "Dihydroxyacetone-3-phosphate", "DHAP"
GAP (chemical): "Glyceraldehyde 3-phosphate", "D-Glyceraldehyde 3-phosphate", "G3P"
NAD (chemical): "Nicotinamide adenine dinucleotide", "NAD+", "Dinucleotide"
BPGA13 (chemical): "1,3-Bisphosphoglycerate", "1,3-Bisphosphoglyceric acid", "1,3BPG"
NADH (chemical): "Nicotinamide adenine dinucleotide reduced", "NADH", "Reduced NAD"
Pyr (chemical): "Pyruvate", "Pyruvic acid", "2-Oxopropanoic acid"
Nb (chemical): "3-Phosphoglycerate", "3-Phosphoglyceric acid", "3PG"
PyrE (chemical): "Pyruvate external", "External Pyruvate", "Pyruvate extracellular"
Gly (chemical): "Glycerol", "Glycerin", "Propan-1,2,3-triol"
GlcE (chemical): "Glucose external", "External Glucose", "Glucose extracellular"
Gly3P (chemical): "Glycerol 3-phosphate", "D-Glycerol 3-phosphate", "G3P"
ATPc (chemical): "ATP cytosolic", "Cytosolic ATP", "Adenosine triphosphate cytosol"
ADPc (chemical): "ADP cytosolic", "Cytosolic ADP", "Adenosine diphosphate cytosol"
ATPg (chemical): "ATP glycosomal", "Glycosomal ATP", "Adenosine triphosphate glycosome"
ADPg (chemical): "ADP glycosomal", "Glycosomal ADP", "Adenosine diphosphate glycosome"
DHAPg (chemical): "DHAP glycosomal", "Glycosomal DHAP", "Dihydroxyacetone phosphate glycosome"
DHAPc (chemical): "DHAP cytosolic", "Cytosolic DHAP", "Dihydroxyacetone phosphate cytosol"
Gly3Pc (chemical): "Gly3P cytosolic", "Cytosolic Gly3P", "Glycerol 3-phosphate cytosol"
Gly3Pg (chemical): "Gly3P glycosomal", "Glycosomal Gly3P", "Glycerol 3-phosphate glycosome"
PGAg (chemical): "3-PGA glycosomal", "Glycosomal 3-PGA", "3-Phosphoglycerate glycosome"
PEPc (chemical): "PEP cytosolic", "Cytosolic PEP", "Phosphoenolpyruvate cytosol"

Reason: The model is a glycolysis model, and all species are metabolites or cofactors involved in glycolysis, therefore they are all chemicals. The names are standardized based on common biochemical nomenclature.
Synonyms dict: {'GlcI': ['Glucose', 'D-Glucose', 'Blood sugar'], 'Glc6P': ['Glucose 6-phosphate', 'D-Glucose 6-phosphate', 'G6P'], 'Fru6P': ['Fructose 6-phosphate', 'D-Fructose 6-phosphate', 'F6P'], 'Fru16BP': ['Fructose 1,6-bisphosphate', 'D-Fructose 1,6-bisphosphate', 'F1,6BP'], 'DHAP': ['Dihydroxyacetone phosphate', 'Dihydroxyacetone-3-phosphate', 'DHAP'], 'GAP': ['Glyceraldehyde 3-phosphate', 'D-Glyceraldehyde 3-phosphate', 'G3P'], 'NAD': ['Nicotinamide adenine dinucleotide', 'NAD+', 'Dinucleotide'], 'BPGA13': ['1,3-Bisphosphoglycerate', '1,3-Bisphosphoglyceric acid', '1,3BPG'], 'NADH': ['Nicotinamide adenine dinucleotide reduced', 'NADH', 'Reduced NAD'], 'Pyr': ['Pyruvate', 'Pyruvic acid', '2-Oxopropanoic acid'], 'Nb': ['3-Phosphoglycerate', '3-Phosphoglyceric acid', '3PG'], 'PyrE': ['Pyruvate external', 'External Pyruvate', 'Pyruvate extracellular'], 'Gly': ['Glycerol', 'Glycerin', 'Propan-1,2,3-triol'], 'GlcE': ['Glucose external', 'External Glucose', 'Glucose extracellular'], 'Gly3P': ['Glycerol 3-phosphate', 'D-Glycerol 3-phosphate', 'G3P'], 'ATPc': ['ATP cytosolic', 'Cytosolic ATP', 'Adenosine triphosphate cytosol'], 'ADPc': ['ADP cytosolic', 'Cytosolic ADP', 'Adenosine diphosphate cytosol'], 'ATPg': ['ATP glycosomal', 'Glycosomal ATP', 'Adenosine triphosphate glycosome'], 'ADPg': ['ADP glycosomal', 'Glycosomal ADP', 'Adenosine diphosphate glycosome'], 'DHAPg': ['DHAP glycosomal', 'Glycosomal DHAP', 'Dihydroxyacetone phosphate glycosome'], 'DHAPc': ['DHAP cytosolic', 'Cytosolic DHAP', 'Dihydroxyacetone phosphate cytosol'], 'Gly3Pc': ['Gly3P cytosolic', 'Cytosolic Gly3P', 'Glycerol 3-phosphate cytosol'], 'Gly3Pg': ['Gly3P glycosomal', 'Glycosomal Gly3P', 'Glycerol 3-phosphate glycosome'], 'PGAg': ['3-PGA glycosomal', 'Glycosomal 3-PGA', '3-Phosphoglycerate glycosome'], 'PEPc': ['PEP cytosolic', 'Cytosolic PEP', 'Phosphoenolpyruvate cytosol']}
Evaluating 72/1075: BIOMD0000000072.xml

2025-11-20 12:21:20,053 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:21:20,054 - WARNING - Skipping BIOMD0000000072.xml - no results generated
2025-11-20 12:21:20,078 - WARNING - Skipping BIOMD0000000073.xml - no results generated
2025-11-20 12:21:20,097 - WARNING - Skipping BIOMD0000000074.xml - no results generated

Evaluating 73/1075: BIOMD0000000073.xml
Evaluating 74/1075: BIOMD0000000074.xml
Evaluating 75/1075: BIOMD0000000075.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000075.txt
LLM response:
PIP2_PHGFP_PM (complex): "PIP2 PH domain GFP complex", "Phosphatidylinositol 4,5-bisphosphate PH domain GFP complex", "PIP2 PH-GFP complex"
IP3_PHGFP_Cyt (complex): "IP3 PH domain GFP complex", "Inositol 1,4,5-trisphosphate PH domain GFP complex", "IP3 PH-GFP complex"
PIP2_PM (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PIP2", "Phosphoinositide"
DAG_PM (chemical): "Diacylglycerol", "DAG", "1,2-Diacylglycerol"
IP3X_Cytosol (chemical): "Inositol 1,4,5-trisphosphate", "IP3", "InsP3"
IP3_Cyt (chemical): "Inositol 1,4,5-trisphosphate", "IP3", "InsP3"

Reason: The species PIP2_PHGFP_PM and IP3_PHGFP_Cyt are classified as complexes because they involve the binding of PIP2 or IP3 to the PH domain of GFP, a protein. PIP2_PM and DAG_PM are classified as chemicals because they are phospholipids and a lipid, respectively. IP3X_Cytosol and IP3_Cyt are also classified as chemicals because they are inositol phosphates. The standardized names and synonyms are based on common names used in the field of biochemistry and cell biology, and are ranked by likelihood based on their frequency of use in the scientific literature.
Synonyms dict: {'PIP2_PHGFP_PM': ['PIP2 PH domain GFP complex', 'Phosphatidylinositol 4,5-bisphosphate PH domain GFP complex', 'PIP2 PH-GFP complex'], 'IP3_PHGFP_Cyt': ['IP3 PH domain GFP complex', 'Inositol 1,4,5-trisphosphate PH domain GFP complex', 'IP3 PH-GFP complex'], 'PIP2_PM': ['Phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'Phosphoinositide'], 'DAG_PM': ['Diacylglycerol', 'DAG', '1,2-Diacylglycerol'], 'IP3X_Cytosol': ['Inositol 1,4,5-trisphosphate', 'IP3', 'InsP3'], 'IP3_Cyt': ['Inositol 1,4,5-trisphosphate', 'IP3', 'InsP3']}
Evaluating 76/1075: BIOMD0000000076.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000076.txt
LLM response:
G3P (chemical): "Glycerol 3-phosphate", "L-Glycerol 3-phosphate", "G3P"
Gly (chemical): "Glycerol", "Glycerin", "Propan-1,2,3-triol"
DHAP (chemical): "Dihydroxyacetone phosphate", "DHAP", "Glycerone phosphate"

Reason: The model is a biochemical model of glycerol synthesis, and all species have display names that match common biochemical compounds. G3P is a known intermediate in glycerol synthesis, Gly is the final product, and DHAP is a precursor to G3P. The display names and reaction equations provide sufficient information to determine that all species are chemicals.
Synonyms dict: {'G3P': ['Glycerol 3-phosphate', 'L-Glycerol 3-phosphate', 'G3P'], 'Gly': ['Glycerol', 'Glycerin', 'Propan-1,2,3-triol'], 'DHAP': ['Dihydroxyacetone phosphate', 'DHAP', 'Glycerone phosphate']}
Evaluating 77/1075: BIOMD0000000077.xml

2025-11-20 12:21:26,684 - WARNING - Skipping BIOMD0000000078.xml - no results generated
2025-11-20 12:21:26,688 - WARNING - Skipping BIOMD0000000079.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000077.txt
LLM response:
IP3 (chemical): "inositol trisphosphate", "inositol 1,4,5-trisphosphate", "IP3"
Reason: IP3 is known to be a chemical involved in cellular signaling, specifically as a second messenger in the phosphoinositide signaling pathway, which is consistent with its role in the model of GnRH-induced LH secretion. The display name "IP3" is a common abbreviation for inositol trisphosphate, and the reactions in the model suggest it is being produced and consumed, which is typical of a chemical species.
Synonyms dict: {'IP3': ['inositol trisphosphate', 'inositol 1,4,5-trisphosphate', 'IP3']}
Evaluating 78/1075: BIOMD0000000078.xml
Evaluating 79/1075: BIOMD0000000079.xml
Evaluating 80/1075: BIOMD0000000080.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000080.txt
LLM response:
DRG_GDP (complex): "DRG-GDP complex", "GDP-bound DRG", "DRG-GDP"
G_GDP (complex): "G-GDP complex", "GDP-bound G", "G-GDP"
GDP (chemical): "guanosine diphosphate", "GDP", "guanosine 5'-diphosphate"
DRG_GTP (complex): "DRG-GTP complex", "GTP-bound DRG", "DRG-GTP"
GTP (chemical): "guanosine triphosphate", "GTP", "guanosine 5'-triphosphate"
G_GTP (complex): "G-GTP complex", "GTP-bound G", "G-GTP"
Reason: The species are annotated based on their display names and reaction equations. DRG_GDP, G_GDP, DRG_GTP, and G_GTP are complexes because they appear to be bound forms of GDP or GTP with other molecules (DRG or G). GDP and GTP are chemicals because they are nucleotides. The standardized names and synonyms are chosen based on common biochemical nomenclature and the context of the model, which appears to be related to G-protein signaling.
Synonyms dict: {'DRG_GDP': ['DRG-GDP complex', 'GDP-bound DRG', 'DRG-GDP'], 'G_GDP': ['G-GDP complex', 'GDP-bound G', 'G-GDP'], 'GDP': ['guanosine diphosphate', 'GDP', "guanosine 5'-diphosphate"], 'DRG_GTP': ['DRG-GTP complex', 'GTP-bound DRG', 'DRG-GTP'], 'GTP': ['guanosine triphosphate', 'GTP', "guanosine 5'-triphosphate"], 'G_GTP': ['G-GTP complex', 'GTP-bound G', 'G-GTP']}
Evaluating 81/1075: BIOMD0000000081.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000081.txt
LLM response:
PIP2_M (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PtdIns(4,5)P2", "Phosphatidylinositol bisphosphate"
GGDPbS_M (chemical): "GDP-bound state", "Guanosine diphosphate", "GDP"
Mg2_C (chemical): "Magnesium ion", "Mg2+", "Magnesium(2+)"
ATP_C (chemical): "Adenosine triphosphate", "ATP", "Adenosine 5'-triphosphate"
oxoM_EX (unknown): "UNK"
GDPbS_C (chemical): "GDP-bound state", "Guanosine diphosphate", "GDP"
GGTPMg_M (chemical): "GTP-bound state with magnesium", "Guanosine triphosphate", "GTP"
GDP_C (chemical): "Guanosine diphosphate", "GDP", "Guanosine 5'-diphosphate"
GTP_C (chemical): "Guanosine triphosphate", "GTP", "Guanosine 5'-triphosphate"
GGDPAlF4Mg_M (chemical): "GDP-bound state with aluminum fluoride and magnesium", "Guanosine diphosphate", "GDP"
ip3_C (chemical): "Inositol trisphosphate", "IP3", "D-myo-Inositol 1,4,5-trisphosphate"
AlF4_C (chemical): "Aluminum fluoride", "AlF4", "Aluminum tetrafluoride"
GGTP_M (chemical): "GTP-bound state", "Guanosine triphosphate", "GTP"
PI_M (chemical): "Phosphatidylinositol", "PtdIns", "Phosphatidylinositol"
PIP_M (chemical): "Phosphatidylinositol 4-phosphate", "PtdIns(4)P", "Phosphatidylinositol phosphate"
PIP2xKCNQ_M (complex): "Phosphatidylinositol 4,5-bisphosphate with KCNQ channel", "PtdIns(4,5)P2-KCNQ", "KCNQ-PIP2 complex"
GGTPgSMg_M (chemical): "GTP-bound state with guanosine and magnesium", "Guanosine triphosphate", "GTP"
GGDPAlF4_M (chemical): "GDP-bound state with aluminum fluoride", "Guanosine diphosphate", "GDP"
GGTPgS_M (chemical): "GTP-bound state with guanosine", "Guanosine triphosphate", "GTP"
GGDP_M (chemical): "GDP-bound state", "Guanosine diphosphate", "GDP"

Reason: Most species are identified as chemicals based on their names and roles in the model, which appears to be a biochemical pathway involving phosphatidylinositol signaling and G-protein regulation. PIP2xKCNQ_M is identified as a complex because it involves the interaction between phosphatidylinositol 4,5-bisphosphate and the KCNQ channel. oxoM_EX is unknown due to lack of information about its structure or function.
Synonyms dict: {'PIP2_M': ['Phosphatidylinositol 4,5-bisphosphate', 'PtdIns(4,5)P2', 'Phosphatidylinositol bisphosphate'], 'GGDPbS_M': ['GDP-bound state', 'Guanosine diphosphate', 'GDP'], 'Mg2_C': ['Magnesium ion', 'Mg2+', 'Magnesium(2+)'], 'ATP_C': ['Adenosine triphosphate', 'ATP', "Adenosine 5'-triphosphate"], 'oxoM_EX': ['UNK'], 'GDPbS_C': ['GDP-bound state', 'Guanosine diphosphate', 'GDP'], 'GGTPMg_M': ['GTP-bound state with magnesium', 'Guanosine triphosphate', 'GTP'], 'GDP_C': ['Guanosine diphosphate', 'GDP', "Guanosine 5'-diphosphate"], 'GTP_C': ['Guanosine triphosphate', 'GTP', "Guanosine 5'-triphosphate"], 'GGDPAlF4Mg_M': ['GDP-bound state with aluminum fluoride and magnesium', 'Guanosine diphosphate', 'GDP'], 'ip3_C': ['Inositol trisphosphate', 'IP3', 'D-myo-Inositol 1,4,5-trisphosphate'], 'AlF4_C': ['Aluminum fluoride', 'AlF4', 'Aluminum tetrafluoride'], 'GGTP_M': ['GTP-bound state', 'Guanosine triphosphate', 'GTP'], 'PI_M': ['Phosphatidylinositol', 'PtdIns', 'Phosphatidylinositol'], 'PIP_M': ['Phosphatidylinositol 4-phosphate', 'PtdIns(4)P', 'Phosphatidylinositol phosphate'], 'PIP2xKCNQ_M': ['Phosphatidylinositol 4,5-bisphosphate with KCNQ channel', 'PtdIns(4,5)P2-KCNQ', 'KCNQ-PIP2 complex'], 'GGTPgSMg_M': ['GTP-bound state with guanosine and magnesium', 'Guanosine triphosphate', 'GTP'], 'GGDPAlF4_M': ['GDP-bound state with aluminum fluoride', 'Guanosine diphosphate', 'GDP'], 'GGTPgS_M': ['GTP-bound state with guanosine', 'Guanosine triphosphate', 'GTP'], 'GGDP_M': ['GDP-bound state', 'Guanosine diphosphate', 'GDP']}
Evaluating 82/1075: BIOMD0000000082.xml

2025-11-20 12:21:38,650 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:21:38,684 - WARNING - Skipping BIOMD0000000083.xml - no results generated
2025-11-20 12:21:38,689 - WARNING - Skipping BIOMD0000000084.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000082.txt
LLM response:
DRG_GDP (complex): "DRG-GDP complex", "Dopamine receptor-GDP complex", "Alpha2-adrenergic receptor-GDP complex"
GDP (chemical): "Guanosine diphosphate", "GDP", "Guanosine 5'-diphosphate"
DRG_GTP (complex): "DRG-GTP complex", "Dopamine receptor-GTP complex", "Alpha2-adrenergic receptor-GTP complex"
GTP (chemical): "Guanosine triphosphate", "GTP", "Guanosine 5'-triphosphate"
G_GDP (protein): "GDP-bound G protein", "Gi protein", "Inhibitory G protein"
G_GTP (protein): "GTP-bound G protein", "Active G protein", "GTP-bound Gi protein"
DRG (protein): "Dopamine receptor", "Alpha2-adrenergic receptor", "ADRA2A"
Reason: The species are annotated based on their display names and reaction equations. DRG_GDP and DRG_GTP are complexes because they are formed by the interaction of DRG (Dopamine receptor) with GDP or GTP. GDP and GTP are chemicals because they are nucleotides. G_GDP and G_GTP are proteins because they represent the GDP-bound and GTP-bound states of the G protein, respectively. DRG is a protein because it is a receptor.
Synonyms dict: {'DRG_GDP': ['DRG-GDP complex', 'Dopamine receptor-GDP complex', 'Alpha2-adrenergic receptor-GDP complex'], 'GDP': ['Guanosine diphosphate', 'GDP', "Guanosine 5'-diphosphate"], 'DRG_GTP': ['DRG-GTP complex', 'Dopamine receptor-GTP complex', 'Alpha2-adrenergic receptor-GTP complex'], 'GTP': ['Guanosine triphosphate', 'GTP', "Guanosine 5'-triphosphate"], 'G_GDP': ['GDP-bound G protein', 'Gi protein', 'Inhibitory G protein'], 'G_GTP': ['GTP-bound G protein', 'Active G protein', 'GTP-bound Gi protein'], 'DRG': ['Dopamine receptor', 'Alpha2-adrenergic receptor', 'ADRA2A']}
Evaluating 83/1075: BIOMD0000000083.xml
Evaluating 84/1075: BIOMD0000000084.xml
Evaluating 85/1075: BIOMD0000000085.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000085.txt
LLM response:
species_3 (chemical): "GTP", "guanosine triphosphate", "GTP molecule"
species_5 (complex): "GTP-bound G-protein", "G-protein-GTP", "G*GTP"
species_6 (complex): "GDP-bound G-protein", "G-protein-GDP", "G*GDP"
species_7 (chemical): "inorganic phosphate", "phosphate ion", "Pi"
species_8 (chemical): "GDP", "guanosine diphosphate", "GDP molecule"
species_10 (complex): "RGTP", "R-GTP", "RG*GTP"
species_11 (complex): "GAT", "G*AT", "G-protein-AT"
species_12 (complex): "GAD", "G*AD", "G-protein-ADP"
species_13 (complex): "RGD", "R-GDP", "RG*GDP"
species_15 (complex): "RGAT", "R-GAT", "RG*AT"
species_16 (complex): "RGAD", "R-GAD", "RG*ADP"
Reason: The model "Maurya2005_GTPaseCycle_reducedOrder" is a GTPase cycle model, which involves G-proteins, GTP, and GDP. The species are annotated based on their display names and reaction equations. For example, species_3 is likely "GTP" because it reacts with species_1 (G-protein) to form species_5 (GTP-bound G-protein). Similarly, species_7 is "inorganic phosphate" (Pi) because it is released in several reactions. The complexes are annotated based on their components, such as species_10 being "RGTP" (R-GTP) and species_13 being "RGD" (R-GDP).
Synonyms dict: {'species_3': ['GTP', 'guanosine triphosphate', 'GTP molecule'], 'species_5': ['GTP-bound G-protein', 'G-protein-GTP', 'G*GTP'], 'species_6': ['GDP-bound G-protein', 'G-protein-GDP', 'G*GDP'], 'species_7': ['inorganic phosphate', 'phosphate ion', 'Pi'], 'species_8': ['GDP', 'guanosine diphosphate', 'GDP molecule'], 'species_10': ['RGTP', 'R-GTP', 'RG*GTP'], 'species_11': ['GAT', 'G*AT', 'G-protein-AT'], 'species_12': ['GAD', 'G*AD', 'G-protein-ADP'], 'species_13': ['RGD', 'R-GDP', 'RG*GDP'], 'species_15': ['RGAT', 'R-GAT', 'RG*AT'], 'species_16': ['RGAD', 'R-GAD', 'RG*ADP']}
Evaluating 86/1075: BIOMD0000000086.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000086.txt
LLM response:
species_3 (chemical): "GTP", "guanosine triphosphate", "GTP molecule"
species_5 (complex): "GTP-bound G-protein", "G-protein-GTP complex", "G*GTP"
species_6 (complex): "GDP-bound G-protein", "G-protein-GDP complex", "G*GDP"
species_7 (chemical): "inorganic phosphate", "phosphate ion", "Pi"
species_8 (chemical): "GDP", "guanosine diphosphate", "GDP molecule"
species_10 (complex): "RGTP", "R-GTP complex", "activator-GTP complex"
species_11 (complex): "GAT", "G-protein-AT complex", "G-protein-ATP complex"
species_12 (complex): "GAD", "G-protein-ADP complex", "G-protein-ADP complex"
species_13 (complex): "RGD", "R-GDP complex", "activator-GDP complex"
species_15 (complex): "RGAT", "R-GAT complex", "activator-GAT complex"
species_16 (complex): "RGAD", "R-GAD complex", "activator-GAD complex"
Reason: The model is a GTPase cycle, where species_3 is GTP, species_7 is inorganic phosphate, and species_8 is GDP. The other species are complexes of G-proteins with GTP, GDP, or other molecules, based on the reaction equations and display names. For example, species_5 is a complex of G-protein and GTP, and species_10 is a complex of activator and GTP. The entity types are determined based on the composition and function of each species in the GTPase cycle.
Synonyms dict: {'species_3': ['GTP', 'guanosine triphosphate', 'GTP molecule'], 'species_5': ['GTP-bound G-protein', 'G-protein-GTP complex', 'G*GTP'], 'species_6': ['GDP-bound G-protein', 'G-protein-GDP complex', 'G*GDP'], 'species_7': ['inorganic phosphate', 'phosphate ion', 'Pi'], 'species_8': ['GDP', 'guanosine diphosphate', 'GDP molecule'], 'species_10': ['RGTP', 'R-GTP complex', 'activator-GTP complex'], 'species_11': ['GAT', 'G-protein-AT complex', 'G-protein-ATP complex'], 'species_12': ['GAD', 'G-protein-ADP complex', 'G-protein-ADP complex'], 'species_13': ['RGD', 'R-GDP complex', 'activator-GDP complex'], 'species_15': ['RGAT', 'R-GAT complex', 'activator-GAT complex'], 'species_16': ['RGAD', 'R-GAD complex', 'activator-GAD complex']}
Evaluating 87/1075: BIOMD0000000087.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000087.txt
LLM response:
RPAssDNA (complex): "RPA-ssDNA complex", "Replication Protein A/ssDNA complex", "RPA/ssDNA"
RPAssDNA1 (complex): "RPA-ssDNA intermediate", "RPA/ssDNA complex intermediate", "Replication Protein A/ssDNA intermediate"
RPAssDNA2 (complex): "RPA-ssDNA intermediate 2", "RPA/ssDNA complex intermediate 2", "Replication Protein A/ssDNA intermediate 2"
Mec1RPAssDNA (complex): "Mec1/RPA-ssDNA complex", "Mec1/Replication Protein A/ssDNA complex", "Mec1/RPA/ssDNA"
ATP (chemical): "adenosine triphosphate", "ATP molecule", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP molecule", "adenosine 5'-diphosphate"
Reason: RPAssDNA and its variants are complexes because they involve the binding of RPA (Replication Protein A) to ssDNA (single-stranded DNA). Mec1RPAssDNA is also a complex as it involves the binding of Mec1 to the RPA-ssDNA complex. ATP and ADP are chemicals as they are nucleotide molecules involved in energy transfer reactions.
Synonyms dict: {'RPAssDNA': ['RPA-ssDNA complex', 'Replication Protein A/ssDNA complex', 'RPA/ssDNA'], 'RPAssDNA1': ['RPA-ssDNA intermediate', 'RPA/ssDNA complex intermediate', 'Replication Protein A/ssDNA intermediate'], 'RPAssDNA2': ['RPA-ssDNA intermediate 2', 'RPA/ssDNA complex intermediate 2', 'Replication Protein A/ssDNA intermediate 2'], 'Mec1RPAssDNA': ['Mec1/RPA-ssDNA complex', 'Mec1/Replication Protein A/ssDNA complex', 'Mec1/RPA/ssDNA'], 'ATP': ['adenosine triphosphate', 'ATP molecule', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP molecule', "adenosine 5'-diphosphate"]}
Evaluating 88/1075: BIOMD0000000088.xml

2025-11-20 12:22:24,548 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:22:25,503 - WARNING - Skipping BIOMD0000000089.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000088.txt
LLM response:
s165 (chemical): "Inositol", "myo-Inositol", "D-myo-Inositol"
s267 (chemical): "Calcium ion", "Ca2+", "Calcium"
s172 (chemical): "Calcium ion", "Ca2+", "Calcium"
s173 (complex): "IP3R-3IP3", "Inositol trisphosphate receptor-IP3 complex", "IP3-IP3R complex"
s187 (protein): "Gq alpha subunit", "Gq alpha", "G alpha q"
s214 (protein): "Rho-GTP", "RhoA-GTP", "Rho GTPase"
s231 (protein): "Rho-GDP", "RhoA-GDP", "Rho GTPase"
s252 (protein): "Rho-kinase", "ROCK", "Rho-associated protein kinase"
s267 (chemical): "Calcium ion", "Ca2+", "Calcium"
s276 (protein): "Calmodulin", "CaM", "Calcium-modulated protein"
s277 (complex): "Ca2+-Calmodulin", "Calcium-Calmodulin complex", "CaM-Ca2+ complex"
s278 (complex): "2Ca2+-Calmodulin", "2 Calcium-Calmodulin complex", "CaM-2Ca2+ complex"
s279 (complex): "3Ca2+-Calmodulin", "3 Calcium-Calmodulin complex", "CaM-3Ca2+ complex"
s280 (complex): "4Ca2+-Calmodulin", "4 Calcium-Calmodulin complex", "CaM-4Ca2+ complex"
s289 (protein): "Myosin light chain kinase", "MLCK", "Myosin kinase"
s292 (complex): "MLCK-Ca2+-Calmodulin", "Myosin light chain kinase-Ca2+-Calmodulin complex", "MLCK-CaM-Ca2+ complex"
s293 (complex): "MLCK-2Ca2+-Calmodulin", "Myosin light chain kinase-2Ca2+-Calmodulin complex", "MLCK-2CaM-Ca2+ complex"
s294 (complex): "MLCK-3Ca2+-Calmodulin", "Myosin light chain kinase-3Ca2+-Calmodulin complex", "MLCK-3CaM-Ca2+ complex"
s295 (complex): "MLCK-4Ca2+-Calmodulin", "Myosin light chain kinase-4Ca2+-Calmodulin complex", "MLCK-4CaM-Ca2+ complex"
s309 (protein): "Protein kinase C", "PKC", "PKC enzyme"
s311 (complex): "PKC-DAG", "Protein kinase C-DAG complex", "PKC-Diacylglycerol complex"
s358 (protein): "Myosin light chain", "MLC", "Myosin regulatory light chain"
s359 (protein): "Phosphorylated myosin light chain", "pMLC", "Monophosphorylated MLC"
s360 (protein): "Phosphorylated myosin light chain", "ppMLC", "Diphosphorylated MLC"
s430 (chemical): "Calcium ion", "Ca2+", "Calcium"
s435 (protein): "G12 alpha subunit", "G12 alpha", "G alpha 12"
s436 (protein): "p115RhoGEF-GTP", "p115 Rho guanine nucleotide exchange factor-GTP", "p115RhoGEF-GTP complex"
s439 (protein): "Gq alpha subunit-GTP", "Gq alpha-GTP", "G alpha q-GTP"
s441 (protein): "Gq alpha beta gamma subunit", "Gq alpha beta gamma", "G alpha q beta gamma"
s443 (complex): "PLC beta-Gq alpha-GTP", "Phospholipase C beta-Gq alpha-GTP complex", "PLC beta-G alpha q-GTP complex"
s446 (complex): "Calcium pump-Ca2+", "Calcium pump-Calcium complex", "Ca2+ pump-Ca2+ complex"
s449 (complex): "Rho-kinase-MLC", "Rho-associated protein kinase-Myosin light chain complex", "ROCK-MLC complex"
s456 (complex): "Rho-kinase-MLC", "Rho-associated protein kinase-Myosin light chain complex", "ROCK-MLC complex"
s506 (complex): "MLCK-4Ca2+-Calmodulin-MLC", "Myosin light chain kinase-4Ca2+-Calmodulin-Myosin light chain complex", "MLCK-4CaM-Ca2+-MLC complex"
s512 (complex): "MLCK-3Ca2+-Calmodulin-MLC", "Myosin light chain kinase-3Ca2+-Calmodulin-Myosin light chain complex", "MLCK-3CaM-Ca2+-MLC complex"
s513 (complex): "MLCK-4Ca2+-Calmodulin-MLC", "Myosin light chain kinase-4Ca2+-Calmodulin-Myosin light chain complex", "MLCK-4CaM-Ca2+-MLC complex"
s520 (complex): "MLCK-3Ca2+-Calmodulin-MLC", "Myosin light chain kinase-3Ca2+-Calmodulin-Myosin light chain complex", "MLCK-3CaM-Ca2+-MLC complex"
s526 (complex): "MLCK-2Ca2+-Calmodulin-MLC", "Myosin light chain kinase-2Ca2+-Calmodulin-Myosin light chain complex", "MLCK-2CaM-Ca2+-MLC complex"
s539 (complex): "MLCK-2Ca2+-Calmodulin-MLC", "Myosin light chain kinase-2Ca2+-Calmodulin-Myosin light chain complex", "MLCK-2CaM-Ca2+-MLC complex"
s546 (complex): "MLCK-Ca2+-Calmodulin-MLC", "Myosin light chain kinase-Ca2+-Calmodulin-Myosin light chain complex", "MLCK-CaM-Ca2+-MLC complex"
s551 (complex): "MLCK-Ca2+-Calmodulin-MLC", "Myosin light chain kinase-Ca2+-Calmodulin-Myosin light chain complex", "MLCK-CaM-Ca2+-MLC complex"
s556 (chemical): "Calcium ion", "Ca2+", "Calcium"
s557 (chemical): "Calcium ion", "Ca2+", "Calcium"
s564 (complex): "PLC beta-Gq alpha-GTP-Ca2+-PIP2", "Phospholipase C beta-Gq alpha-GTP-Calcium-PIP2 complex", "PLC beta-G alpha q-GTP-Ca2+-PIP2 complex"
s565 (complex): "PKC-Ca2+-DAG", "Protein kinase C-Calcium-DAG complex", "PKC-Ca2+-Diacylglycerol complex"
s566 (complex): "PKC-Ca2+", "Protein kinase C-Calcium complex", "PKC-Ca2+ complex"
s567 (complex): "PLC beta-Gq alpha-GTP-Ca2+-PIP2", "Phospholipase C beta-Gq alpha-GTP-Calcium-PIP2 complex", "PLC beta-G alpha q-GTP-Ca2+-PIP2 complex"
s568 (complex): "PLC beta-Ca2+-PIP2", "Phospholipase C beta-Calcium-PIP2 complex", "PLC beta-Ca2+-PIP2 complex"
s569 (complex): "PLC beta-Ca2+", "Phospholipase C beta-Calcium complex", "PLC beta-Ca2+ complex"
s48 (chemical): "GTP", "Guanosine triphosphate", "Guanosine 5'-triphosphate"
s50 (chemical): "GDP", "Guanosine diphosphate", "Guanosine 5'-diphosphate"
s151 (chemical): "PIP2", "Phosphatidylinositol 4,5-bisphosphate", "Phosphatidylinositol(4,5)P2"
s152 (chemical): "IP3", "Inositol trisphosphate", "D-myo-Inositol 1,4,5-trisphosphate"
s153 (chemical): "DAG", "Diacylglycerol", "1,2-Diacylglycerol"
s164 (chemical): "Phosphatidic acid", "PA", "1,2-Phosphatidic acid"
s165 (chemical): "Inositol", "myo-Inositol", "D-myo-Inositol"
s171 (protein): "IP3 receptor", "IP3R", "Inositol trisphosphate receptor"
s172 (chemical): "Calcium ion", "Ca2+", "Calcium"
s173 (complex): "IP3R-3IP3", "Inositol trisphosphate receptor-IP3 complex", "IP3-IP3R complex"
s187 (protein): "Gq alpha subunit", "Gq alpha", "G alpha q"
s214 (protein): "Rho-GTP", "RhoA-GTP", "Rho GTPase"
s231 (protein): "Rho-GDP", "RhoA-GDP", "Rho GTPase"
s252 (protein): "Rho-kinase", "ROCK", "Rho-associated protein kinase"
s267 (chemical): "Calcium ion", "Ca2+", "Calcium"
s276 (protein): "Calmodulin", "CaM", "Calcium-modulated protein"
s277 (complex): "Ca2+-Calmodulin", "Calcium-Calmodulin complex", "CaM-Ca2+ complex"
s278 (complex): "2Ca2+-Calmodulin", "2 Calcium-Calmodulin complex", "CaM-2Ca2+ complex"
s279 (complex): "3Ca2+-Calmodulin", "3 Calcium-Calmodulin complex", "CaM-3Ca2+ complex"
s280 (complex): "4Ca2+-Calmodulin", "4 Calcium-Calmodulin complex", "CaM-4Ca2+ complex"
s289 (protein): "Myosin light chain kinase", "MLCK", "Myosin kinase"
s292 (complex): "MLCK-Ca2+-Calmodulin", "Myosin light chain kinase-Ca2+-Calmodulin complex", "MLCK-CaM-Ca2+ complex"
s293 (complex): "MLCK-2Ca2+-Calmodulin", "Myosin light chain kinase-2Ca2+-Calmodulin complex", "MLCK-2CaM-Ca2+ complex"
s294 (complex): "MLCK-3Ca2+-Calmodulin", "Myosin light chain kinase-3Ca2+-Calmodulin complex", "MLCK-3CaM-Ca2+ complex"
s295 (complex): "MLCK-4Ca2+-Calmodulin", "Myosin light chain kinase-4Ca2+-Calmodulin complex", "MLCK-4CaM-Ca2+ complex"
s309 (protein): "Protein kinase C", "PKC", "PKC enzyme"
s311 (complex): "PKC-DAG", "Protein kinase C-DAG complex", "PKC-Diacylglycerol complex"
s358 (protein): "Myosin light chain", "MLC", "Myosin regulatory light chain"
s359 (protein): "Phosphorylated myosin light chain", "pMLC", "Monophosphorylated MLC"
s360 (protein): "Phosphorylated myosin light chain", "ppMLC", "Diphosphorylated MLC"
s430 (chemical): "Calcium ion", "Ca2+", "Calcium"
s435 (protein): "G12 alpha subunit", "G12 alpha", "G alpha 12"
s436 (protein): "p115RhoGEF-GTP", "p115 Rho guanine nucleotide exchange factor-GTP", "p115RhoGEF-GTP complex"
s439 (protein): "Gq alpha subunit-GTP", "Gq alpha-GTP", "G alpha q-GTP"
s441 (protein): "Gq alpha beta gamma subunit", "Gq alpha beta gamma", "G alpha q beta gamma"
s443 (complex): "PLC beta-Gq alpha-GTP", "Phospholipase C beta-Gq alpha-GTP complex", "PLC beta-G alpha q-GTP complex"
s446 (complex): "Calcium pump-Ca2+", "Calcium pump-Calcium complex", "Ca2+ pump-Ca2+ complex"
s449 (complex): "Rho-kinase-MLC", "Rho-associated protein kinase-Myosin light chain complex", "ROCK-MLC complex"
s456 (complex): "Rho-kinase-MLC", "Rho-associated protein kinase-Myosin light chain complex", "ROCK-MLC complex"
s506 (complex): "MLCK-4Ca2+-Calmodulin-MLC", "Myosin light chain kinase-4Ca2+-Calmodulin-Myosin light chain complex", "MLCK-4CaM-Ca2+-MLC complex"
s512 (complex): "MLCK-3Ca2+-Calmodulin-MLC", "Myosin light chain kinase-3Ca2+-Calmodulin-Myosin light chain complex", "MLCK-3CaM-Ca2+-MLC complex"
s513 (complex): "MLCK-4Ca2+-Calmodulin-MLC", "Myosin light chain kinase-4Ca2+-Calmodulin-Myosin light chain complex", "MLCK-4CaM-Ca2+-MLC complex"
s520 (complex): "MLCK-3Ca2+-Calmodulin-MLC", "Myosin light chain kinase-3Ca2+-Calmodulin-Myosin light chain complex", "MLCK-3CaM-Ca2+-MLC complex"
s526 (complex): "MLCK-2Ca2+-Calmodulin-MLC", "Myosin light chain kinase-2Ca2+-Calmodulin-Myosin light chain complex", "MLCK-2CaM-Ca2+-MLC complex"
s539 (complex): "MLCK-2Ca2+-Calmodulin-MLC", "Myosin light chain kinase-2Ca2+-Calmodulin-Myosin light chain complex", "MLCK-2CaM-Ca2+-MLC complex"
s546 (complex): "MLCK-Ca2+-Calmodulin-MLC", "Myosin light chain kinase-Ca2+-Calmodulin-Myosin light chain complex", "MLCK-CaM-Ca2+-MLC complex"
s551 (complex): "MLCK-Ca2+-Calmodulin-MLC", "Myosin light chain kinase-Ca2+-Calmodulin-Myosin light chain complex", "MLCK-CaM-Ca2+-MLC complex"
s556 (chemical): "Calcium ion", "Ca2+", "Calcium"
s557 (chemical): "Calcium ion", "Ca2+", "Calcium"
s564 (complex): "PLC beta-Gq alpha-GTP-Ca2+-PIP2", "Phospholipase C beta-Gq alpha-GTP-Calcium-PIP2 complex", "PLC beta-G alpha q-GTP-Ca2+-PIP2 complex"
s565 (complex): "PKC-Ca2+-DAG", "Protein kinase C-Calcium-DAG complex", "PKC-Ca2+-Diacylglycerol complex"
s566 (complex): "PKC-Ca2+", "Protein kinase C-Calcium complex", "PKC-Ca2+ complex"
s567 (complex): "PLC beta-Gq alpha-GTP-Ca2+-PIP2", "Phospholipase C beta-Gq alpha-GTP-Calcium-PIP2 complex", "PLC beta-G alpha q-GTP-Ca2+-PIP2 complex"
s568 (complex): "PLC beta-Ca2+-PIP2", "Phospholipase C beta-Calcium-PIP2 complex", "PLC beta-Ca2+-PIP2 complex"
s569 (complex): "PLC beta-Ca2+", "Phospholipase C beta-Calcium complex", "PLC beta-Ca2+ complex"
s48 (chemical): "GTP", "Guanosine triphosphate", "Guanosine 5'-triphosphate"
s50 (chemical): "GDP", "Guanosine diphosphate", "Guanosine 5'-diphosphate"
s151 (chemical): "PIP2", "Phosphatidylinositol 4,5-bisphosphate", "Phosphatidylinositol(4,5)P2"
s152 (chemical): "IP3", "Inositol trisphosphate", "D-myo-Inositol 1,4,5-trisphosphate"
s153 (chemical): "DAG", "Diacylglycerol", "1,2-Diacylglycerol"
s164 (chemical): "Phosphatidic acid", "PA", "1,2-Phosphatidic acid"
s165 (chemical): "Inositol", "myo-Inositol", "D-myo-Inositol"
s171 (protein): "IP3 receptor", "IP3R", "Inositol trisphosphate receptor"
s172 (chemical): "Calcium ion", "Ca2+", "Calcium"
s173 (complex): "IP3R-3IP3", "Inositol trisphosphate receptor-IP3 complex", "IP3-IP3R complex"
s187 (protein): "Gq alpha subunit", "Gq alpha", "G alpha q"
s214 (protein): "Rho-GTP", "RhoA-GTP", "Rho GTPase"
s231 (protein): "Rho-GDP", "RhoA-GDP", "Rho GTPase"
s252 (protein): "Rho-kinase", "ROCK", "Rho-associated protein kinase"
s267 (
Synonyms dict: {'s165': ['Inositol', 'myo-Inositol', 'D-myo-Inositol'], 's267': ['Calcium ion', 'Ca2+', 'Calcium'], 's172': ['Calcium ion', 'Ca2+', 'Calcium'], 's173': ['IP3R-3IP3', 'Inositol trisphosphate receptor-IP3 complex', 'IP3-IP3R complex'], 's187': ['Gq alpha subunit', 'Gq alpha', 'G alpha q'], 's214': ['Rho-GTP', 'RhoA-GTP', 'Rho GTPase'], 's231': ['Rho-GDP', 'RhoA-GDP', 'Rho GTPase'], 's252': ['Rho-kinase', 'ROCK', 'Rho-associated protein kinase'], 's276': ['Calmodulin', 'CaM', 'Calcium-modulated protein'], 's277': ['Ca2+-Calmodulin', 'Calcium-Calmodulin complex', 'CaM-Ca2+ complex'], 's278': ['2Ca2+-Calmodulin', '2 Calcium-Calmodulin complex', 'CaM-2Ca2+ complex'], 's279': ['3Ca2+-Calmodulin', '3 Calcium-Calmodulin complex', 'CaM-3Ca2+ complex'], 's280': ['4Ca2+-Calmodulin', '4 Calcium-Calmodulin complex', 'CaM-4Ca2+ complex'], 's289': ['Myosin light chain kinase', 'MLCK', 'Myosin kinase'], 's292': ['MLCK-Ca2+-Calmodulin', 'Myosin light chain kinase-Ca2+-Calmodulin complex', 'MLCK-CaM-Ca2+ complex'], 's293': ['MLCK-2Ca2+-Calmodulin', 'Myosin light chain kinase-2Ca2+-Calmodulin complex', 'MLCK-2CaM-Ca2+ complex'], 's294': ['MLCK-3Ca2+-Calmodulin', 'Myosin light chain kinase-3Ca2+-Calmodulin complex', 'MLCK-3CaM-Ca2+ complex'], 's295': ['MLCK-4Ca2+-Calmodulin', 'Myosin light chain kinase-4Ca2+-Calmodulin complex', 'MLCK-4CaM-Ca2+ complex'], 's309': ['Protein kinase C', 'PKC', 'PKC enzyme'], 's311': ['PKC-DAG', 'Protein kinase C-DAG complex', 'PKC-Diacylglycerol complex'], 's358': ['Myosin light chain', 'MLC', 'Myosin regulatory light chain'], 's359': ['Phosphorylated myosin light chain', 'pMLC', 'Monophosphorylated MLC'], 's360': ['Phosphorylated myosin light chain', 'ppMLC', 'Diphosphorylated MLC'], 's430': ['Calcium ion', 'Ca2+', 'Calcium'], 's435': ['G12 alpha subunit', 'G12 alpha', 'G alpha 12'], 's436': ['p115RhoGEF-GTP', 'p115 Rho guanine nucleotide exchange factor-GTP', 'p115RhoGEF-GTP complex'], 's439': ['Gq alpha subunit-GTP', 'Gq alpha-GTP', 'G alpha q-GTP'], 's441': ['Gq alpha beta gamma subunit', 'Gq alpha beta gamma', 'G alpha q beta gamma'], 's443': ['PLC beta-Gq alpha-GTP', 'Phospholipase C beta-Gq alpha-GTP complex', 'PLC beta-G alpha q-GTP complex'], 's446': ['Calcium pump-Ca2+', 'Calcium pump-Calcium complex', 'Ca2+ pump-Ca2+ complex'], 's449': ['Rho-kinase-MLC', 'Rho-associated protein kinase-Myosin light chain complex', 'ROCK-MLC complex'], 's456': ['Rho-kinase-MLC', 'Rho-associated protein kinase-Myosin light chain complex', 'ROCK-MLC complex'], 's506': ['MLCK-4Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-4Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-4CaM-Ca2+-MLC complex'], 's512': ['MLCK-3Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-3Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-3CaM-Ca2+-MLC complex'], 's513': ['MLCK-4Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-4Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-4CaM-Ca2+-MLC complex'], 's520': ['MLCK-3Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-3Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-3CaM-Ca2+-MLC complex'], 's526': ['MLCK-2Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-2Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-2CaM-Ca2+-MLC complex'], 's539': ['MLCK-2Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-2Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-2CaM-Ca2+-MLC complex'], 's546': ['MLCK-Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-CaM-Ca2+-MLC complex'], 's551': ['MLCK-Ca2+-Calmodulin-MLC', 'Myosin light chain kinase-Ca2+-Calmodulin-Myosin light chain complex', 'MLCK-CaM-Ca2+-MLC complex'], 's556': ['Calcium ion', 'Ca2+', 'Calcium'], 's557': ['Calcium ion', 'Ca2+', 'Calcium'], 's564': ['PLC beta-Gq alpha-GTP-Ca2+-PIP2', 'Phospholipase C beta-Gq alpha-GTP-Calcium-PIP2 complex', 'PLC beta-G alpha q-GTP-Ca2+-PIP2 complex'], 's565': ['PKC-Ca2+-DAG', 'Protein kinase C-Calcium-DAG complex', 'PKC-Ca2+-Diacylglycerol complex'], 's566': ['PKC-Ca2+', 'Protein kinase C-Calcium complex', 'PKC-Ca2+ complex'], 's567': ['PLC beta-Gq alpha-GTP-Ca2+-PIP2', 'Phospholipase C beta-Gq alpha-GTP-Calcium-PIP2 complex', 'PLC beta-G alpha q-GTP-Ca2+-PIP2 complex'], 's568': ['PLC beta-Ca2+-PIP2', 'Phospholipase C beta-Calcium-PIP2 complex', 'PLC beta-Ca2+-PIP2 complex'], 's569': ['PLC beta-Ca2+', 'Phospholipase C beta-Calcium complex', 'PLC beta-Ca2+ complex'], 's48': ['GTP', 'Guanosine triphosphate', "Guanosine 5'-triphosphate"], 's50': ['GDP', 'Guanosine diphosphate', "Guanosine 5'-diphosphate"], 's151': ['PIP2', 'Phosphatidylinositol 4,5-bisphosphate', 'Phosphatidylinositol(4,5)P2'], 's152': ['IP3', 'Inositol trisphosphate', 'D-myo-Inositol 1,4,5-trisphosphate'], 's153': ['DAG', 'Diacylglycerol', '1,2-Diacylglycerol'], 's164': ['Phosphatidic acid', 'PA', '1,2-Phosphatidic acid'], 's171': ['IP3 receptor', 'IP3R', 'Inositol trisphosphate receptor']}
Evaluating 89/1075: BIOMD0000000089.xml
Evaluating 90/1075: BIOMD0000000090.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000090.txt
LLM response:
sul_ex (chemical): "sulfate", "sulfuric acid", "SO4"
eth_ex (chemical): "ethanol", "EtOH", "alcohol"
oxy_ex (chemical): "oxygen", "O2", "dioxygen"
oxy (chemical): "oxygen", "O2", "dioxygen"
H2O (chemical): "water", "H2O", "dihydrogen monoxide"
A3c (chemical): "ATP", "adenosine triphosphate", "ATP cytosolic"
aps (chemical): "APS", "adenosine 5'-phosphosulfate", "5'-adenylyl sulfate"
PPi (chemical): "pyrophosphate", "diphosphate", "P2O7"
pap (chemical): "PAPS", "3'-phosphoadenosine 5'-phosphosulfate", "phosphoadenosine phosphosulfate"
sul (chemical): "sulfate", "sulfuric acid", "SO4"
eth (chemical): "ethanol", "EtOH", "alcohol"
A2c (chemical): "ADP", "adenosine diphosphate", "ADP cytosolic"
hyd (chemical): "hydrogen sulfide", "H2S", "sulfane"
cys (chemical): "cysteine", "CYS", "L-cysteine"
N2 (chemical): "NADH", "nicotinamide adenine dinucleotide", "NADH reduced"
N1 (chemical): "NAD", "nicotinamide adenine dinucleotide", "NAD oxidized"
aco (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
oah (chemical): "o-acetylhomoserine", "OAH", "o-acetyl-L-homoserine"
A2m (chemical): "ADP mitochondrial", "ADP mit", "mitochondrial ADP"
A3m (chemical): "ATP mitochondrial", "ATP mit", "mitochondrial ATP"
Ho (unknown): "UNK", "unknown", "undefined"
Hm (unknown): "UNK", "unknown", "undefined"
C1 (unknown): "UNK", "unknown", "undefined"
C2 (unknown): "UNK", "unknown", "undefined"
S1 (unknown): "UNK", "unknown", "undefined"
S2 (unknown): "UNK", "unknown", "undefined"

Reason: Most species can be identified as chemicals based on their display names and roles in the model reactions. For example, sul_ex, eth_ex, oxy_ex, and oxy are likely chemicals due to their involvement in transport reactions. A3c, aps, PPi, pap, sul, eth, A2c, hyd, cys, N2, N1, aco, and oah can be identified as chemicals based on their display names and standard biochemical nomenclature. Ho, Hm, C1, C2, S1, and S2 are marked as unknown due to lack of information about their display names or roles in the model.
Synonyms dict: {'sul_ex': ['sulfate', 'sulfuric acid', 'SO4'], 'eth_ex': ['ethanol', 'EtOH', 'alcohol'], 'oxy_ex': ['oxygen', 'O2', 'dioxygen'], 'oxy': ['oxygen', 'O2', 'dioxygen'], 'H2O': ['water', 'H2O', 'dihydrogen monoxide'], 'A3c': ['ATP', 'adenosine triphosphate', 'ATP cytosolic'], 'aps': ['APS', "adenosine 5'-phosphosulfate", "5'-adenylyl sulfate"], 'PPi': ['pyrophosphate', 'diphosphate', 'P2O7'], 'pap': ['PAPS', "3'-phosphoadenosine 5'-phosphosulfate", 'phosphoadenosine phosphosulfate'], 'sul': ['sulfate', 'sulfuric acid', 'SO4'], 'eth': ['ethanol', 'EtOH', 'alcohol'], 'A2c': ['ADP', 'adenosine diphosphate', 'ADP cytosolic'], 'hyd': ['hydrogen sulfide', 'H2S', 'sulfane'], 'cys': ['cysteine', 'CYS', 'L-cysteine'], 'N2': ['NADH', 'nicotinamide adenine dinucleotide', 'NADH reduced'], 'N1': ['NAD', 'nicotinamide adenine dinucleotide', 'NAD oxidized'], 'aco': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'oah': ['o-acetylhomoserine', 'OAH', 'o-acetyl-L-homoserine'], 'A2m': ['ADP mitochondrial', 'ADP mit', 'mitochondrial ADP'], 'A3m': ['ATP mitochondrial', 'ATP mit', 'mitochondrial ATP'], 'Ho': ['UNK', 'unknown', 'undefined'], 'Hm': ['UNK', 'unknown', 'undefined'], 'C1': ['UNK', 'unknown', 'undefined'], 'C2': ['UNK', 'unknown', 'undefined'], 'S1': ['UNK', 'unknown', 'undefined'], 'S2': ['UNK', 'unknown', 'undefined']}
Evaluating 91/1075: BIOMD0000000091.xml

2025-11-20 12:22:34,533 - WARNING - Skipping BIOMD0000000092.xml - no results generated
2025-11-20 12:22:34,550 - WARNING - Skipping BIOMD0000000093.xml - no results generated
2025-11-20 12:22:34,568 - WARNING - Skipping BIOMD0000000094.xml - no results generated
2025-11-20 12:22:34,585 - WARNING - Skipping BIOMD0000000095.xml - no results generated
2025-11-20 12:22:34,601 - WARNING - Skipping BIOMD0000000096.xml - no results generated
2025-11-20 12:22:34,618 - WARNING - Skipping BIOMD0000000097.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000091.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Reason: Both ATP and ADP are well-known chemical compounds that play crucial roles in energy transfer within cells, which is consistent with their involvement in the reactions described in the model, such as ATP being consumed and ADP being produced in various processes, indicating their chemical nature.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"]}
Evaluating 92/1075: BIOMD0000000092.xml
Evaluating 93/1075: BIOMD0000000093.xml
Evaluating 94/1075: BIOMD0000000094.xml
Evaluating 95/1075: BIOMD0000000095.xml
Evaluating 96/1075: BIOMD0000000096.xml
Evaluating 97/1075: BIOMD0000000097.xml
Evaluating 98/1075: BIOMD0000000098.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000098.txt
LLM response:
Z (chemical): "calcium", "Ca2+", "calcium ion"
Y (chemical): "calcium", "Ca2+", "intracellular calcium"
Reason: The model is named "Goldbeter1990_CalciumSpike_CICR" which suggests it is related to calcium signaling, and the reactions imply that Z and Y are interchangeable forms of calcium, likely representing cytosolic and intracellular calcium.
Synonyms dict: {'Z': ['calcium', 'Ca2+', 'calcium ion'], 'Y': ['calcium', 'Ca2+', 'intracellular calcium']}
Evaluating 99/1075: BIOMD0000000099.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000099.txt
LLM response:
species_0 (chemical): "cAMP", "cyclic adenosine monophosphate", "cyclic AMP"
species_1 (chemical): "cAMP", "cyclic adenosine monophosphate", "cyclic AMP"
Reason: Both species_0 and species_1 are annotated as "Ex_cAMP" and "In_cAMP" respectively, indicating they represent extracellular and intracellular cyclic adenosine monophosphate (cAMP), a chemical messenger.
Synonyms dict: {'species_0': ['cAMP', 'cyclic adenosine monophosphate', 'cyclic AMP'], 'species_1': ['cAMP', 'cyclic adenosine monophosphate', 'cyclic AMP']}
Evaluating 100/1075: BIOMD0000000100.xml

2025-11-20 12:22:39,252 - WARNING - Skipping BIOMD0000000101.xml - no results generated
2025-11-20 12:22:39,262 - WARNING - Skipping BIOMD0000000102.xml - no results generated
2025-11-20 12:22:39,275 - WARNING - Skipping BIOMD0000000103.xml - no results generated
2025-11-20 12:22:39,279 - WARNING - Skipping BIOMD0000000104.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000100.txt
LLM response:
EC (chemical): "calcium ion", "Ca2+", "extracellular calcium"
Z (chemical): "cytosolic calcium", "calcium ion", "Ca2+"
A (chemical): "inositol trisphosphate", "IP3", "myo-inositol 1,4,5-trisphosphate"
Y (chemical): "intravesicular calcium", "calcium ion", "Ca2+"
Reason: All species (EC, Z, A, Y) are related to calcium or signaling molecules, which are typically chemicals. EC, Z, and Y are all forms of calcium, while A is a well-known signaling molecule involved in calcium release. The display names and reactions support these annotations, with calcium moving between extracellular, cytosolic, and intravesicular compartments, and IP3 playing a role in this process.
Synonyms dict: {'EC': ['calcium ion', 'Ca2+', 'extracellular calcium'], 'Z': ['cytosolic calcium', 'calcium ion', 'Ca2+'], 'A': ['inositol trisphosphate', 'IP3', 'myo-inositol 1,4,5-trisphosphate'], 'Y': ['intravesicular calcium', 'calcium ion', 'Ca2+']}
Evaluating 101/1075: BIOMD0000000101.xml
Evaluating 102/1075: BIOMD0000000102.xml
Evaluating 103/1075: BIOMD0000000103.xml
Evaluating 104/1075: BIOMD0000000104.xml
Evaluating 105/1075: BIOMD0000000105.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000105.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "adenosine 5'-triphosphate", "ATP"
ADP (chemical): "adenosine diphosphate", "adenosine 5'-diphosphate", "ADP"
AMP (chemical): "adenosine monophosphate", "adenosine 5'-monophosphate", "AMP"
Reason: ATP, ADP, and AMP are all well-known chemical compounds that play important roles in energy transfer within cells, and their involvement in the ubiquitin-proteasome system reactions as described in the model further supports their classification as chemicals.
Synonyms dict: {'ATP': ['adenosine triphosphate', "adenosine 5'-triphosphate", 'ATP'], 'ADP': ['adenosine diphosphate', "adenosine 5'-diphosphate", 'ADP'], 'AMP': ['adenosine monophosphate', "adenosine 5'-monophosphate", 'AMP']}
Evaluating 106/1075: BIOMD0000000106.xml

2025-11-20 12:22:46,991 - WARNING - Skipping BIOMD0000000107.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000106.txt
LLM response:
x1 (chemical): "Arachidonic acid", "Eicosatetraenoic acid", "AA"
x2 (chemical): "15-Hydroperoxyeicosatetraenoic acid", "15-HPETE", "15-HPETA"
x3 (chemical): "15-Hydroxyeicosatetraenoic acid", "15-HETE", "15-Hydroxy-5,8,11,13-eicosatetraenoic acid"
x4 (chemical): "12-Hydroperoxyeicosatetraenoic acid", "12-HPETE", "12-HPETA"
x5 (chemical): "12-Hydroxyeicosatetraenoic acid", "12-HETE", "12-Hydroxy-5,8,10,14-eicosatetraenoic acid"
x6 (chemical): "Prostaglandin H2", "PGH2", "Prostaglandin H sub 2"
x7 (chemical): "Prostaglandin E2", "PGE2", "Dinoprostone"
x8 (chemical): "Thromboxane A2", "TXA2", "Thromboxane A sub 2"
x9 (chemical): "Thromboxane B2", "TXB2", "Thromboxane B sub 2"
x10 (chemical): "5-Hydroperoxyeicosatetraenoic acid", "5-HPETE", "5-HPETA"
x11 (chemical): "5-Hydroxyeicosatetraenoic acid", "5-HETE", "5-Hydroxy-6,8,11,14-eicosatetraenoic acid"
x12 (chemical): "Leukotriene A4", "LTA4", "Leukotriene A sub 4"
x13 (chemical): "Leukotriene B4", "LTB4", "Leukotriene B sub 4"
x14 (chemical): "20-Hydroxy-leukotriene B4", "20-OH-LTB4", "omega-Hydroxy-leukotriene B4"
Reason: The model "Yang2007_ArachidonicAcid" describes the arachidonic acid metabolic network. All species are chemical compounds, which are metabolites or intermediates in the arachidonic acid pathway, including eicosanoids like prostaglandins, thromboxanes, and leukotrienes. The display names and reaction equations provided in the model support the identification of these species as chemicals.
Synonyms dict: {'x1': ['Arachidonic acid', 'Eicosatetraenoic acid', 'AA'], 'x2': ['15-Hydroperoxyeicosatetraenoic acid', '15-HPETE', '15-HPETA'], 'x3': ['15-Hydroxyeicosatetraenoic acid', '15-HETE', '15-Hydroxy-5,8,11,13-eicosatetraenoic acid'], 'x4': ['12-Hydroperoxyeicosatetraenoic acid', '12-HPETE', '12-HPETA'], 'x5': ['12-Hydroxyeicosatetraenoic acid', '12-HETE', '12-Hydroxy-5,8,10,14-eicosatetraenoic acid'], 'x6': ['Prostaglandin H2', 'PGH2', 'Prostaglandin H sub 2'], 'x7': ['Prostaglandin E2', 'PGE2', 'Dinoprostone'], 'x8': ['Thromboxane A2', 'TXA2', 'Thromboxane A sub 2'], 'x9': ['Thromboxane B2', 'TXB2', 'Thromboxane B sub 2'], 'x10': ['5-Hydroperoxyeicosatetraenoic acid', '5-HPETE', '5-HPETA'], 'x11': ['5-Hydroxyeicosatetraenoic acid', '5-HETE', '5-Hydroxy-6,8,11,14-eicosatetraenoic acid'], 'x12': ['Leukotriene A4', 'LTA4', 'Leukotriene A sub 4'], 'x13': ['Leukotriene B4', 'LTB4', 'Leukotriene B sub 4'], 'x14': ['20-Hydroxy-leukotriene B4', '20-OH-LTB4', 'omega-Hydroxy-leukotriene B4']}
Evaluating 107/1075: BIOMD0000000107.xml
Evaluating 108/1075: BIOMD0000000108.xml

2025-11-20 12:22:48,930 - WARNING - Skipping BIOMD0000000109.xml - no results generated
2025-11-20 12:22:48,940 - WARNING - Skipping BIOMD0000000110.xml - no results generated
2025-11-20 12:22:48,950 - WARNING - Skipping BIOMD0000000111.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000108.txt
LLM response:
species_0000001 (chemical): "superoxide", "oxygen radical", "O2*"
species_0000006 (chemical): "hydrogen peroxide", "H2O2", "dihydrogen dioxide"
species_0000008 (chemical): "hydroxyl radical", "hydroxy radical", "HO*"
species_0000009 (chemical): "lipid hydroperoxide", "LOOH", "lipid peroxide"
Reason: The species can be identified based on their display names and roles in the reactions. species_0000001 is superoxide, a reactive oxygen species, and species_0000006 is hydrogen peroxide, also a reactive oxygen species. species_0000008 is the hydroxyl radical, a highly reactive species. species_0000009 is lipid hydroperoxide, a product of lipid oxidation. All of these species are chemicals involved in oxidative stress and lipid peroxidation reactions.
Synonyms dict: {'species_0000001': ['superoxide', 'oxygen radical', 'O2*'], 'species_0000006': ['hydrogen peroxide', 'H2O2', 'dihydrogen dioxide'], 'species_0000008': ['hydroxyl radical', 'hydroxy radical', 'HO*'], 'species_0000009': ['lipid hydroperoxide', 'LOOH', 'lipid peroxide']}
Evaluating 109/1075: BIOMD0000000109.xml
Evaluating 110/1075: BIOMD0000000110.xml
Evaluating 111/1075: BIOMD0000000111.xml
Evaluating 112/1075: BIOMD0000000112.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000112.txt
LLM response:
Pi (chemical): "inorganic phosphate", "phosphate", "Pi"
R_smad_P_nuc (protein): "R-Smad-P", "phosphorylated R-Smad", "Smad protein"
R_smad_nuc (protein): "R-Smad", "unphosphorylated R-Smad", "Smad nuclear protein"
Reason: Pi is likely inorganic phosphate, a common chemical species in biological reactions. R_smad_P_nuc and R_smad_nuc are proteins involved in the Smad signaling pathway, with R_smad_P_nuc being the phosphorylated form and R_smad_nuc being the unphosphorylated form.
Synonyms dict: {'Pi': ['inorganic phosphate', 'phosphate', 'Pi'], 'R_smad_P_nuc': ['R-Smad-P', 'phosphorylated R-Smad', 'Smad protein'], 'R_smad_nuc': ['R-Smad', 'unphosphorylated R-Smad', 'Smad nuclear protein']}
Evaluating 113/1075: BIOMD0000000113.xml

2025-11-20 12:22:51,579 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:22:51,579 - WARNING - Skipping BIOMD0000000113.xml - no results generated

Evaluating 114/1075: BIOMD0000000114.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000114.txt
LLM response:
x (chemical): "calcium in endoplasmic reticulum", "Ca2+ in ER", "endoplasmic reticulum calcium"
y (chemical): "cytosolic calcium", "calcium in cytosol", "Ca2+ in cytosol"
Reason: The model "Somogyi1990_CaOscillations" is about calcium oscillations in liver cells, and the display names "Ca_Cyt" and "Ca_ER" suggest that x and y represent calcium in different cellular locations, specifically the endoplasmic reticulum (ER) and cytosol, respectively.
Synonyms dict: {'x': ['calcium in endoplasmic reticulum', 'Ca2+ in ER', 'endoplasmic reticulum calcium'], 'y': ['cytosolic calcium', 'calcium in cytosol', 'Ca2+ in cytosol']}
Evaluating 115/1075: BIOMD0000000115.xml

2025-11-20 12:22:54,571 - WARNING - Skipping BIOMD0000000116.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000115.txt
LLM response:
x (chemical): "calcium in endoplasmic reticulum", "Ca2+ in ER", "endoplasmic reticulum calcium"
y (chemical): "cytosolic calcium", "calcium in cytosol", "Ca2+ in cytosol"
Reason: The model is about calcium oscillations in liver cells, and the display names "Ca_Cyt" and "Ca_ER" suggest that x and y represent calcium ions in the endoplasmic reticulum and cytosol, respectively. The reactions also indicate the movement of calcium ions between these two compartments.
Synonyms dict: {'x': ['calcium in endoplasmic reticulum', 'Ca2+ in ER', 'endoplasmic reticulum calcium'], 'y': ['cytosolic calcium', 'calcium in cytosol', 'Ca2+ in cytosol']}
Evaluating 116/1075: BIOMD0000000116.xml
Evaluating 117/1075: BIOMD0000000117.xml

2025-11-20 12:22:55,597 - WARNING - Skipping BIOMD0000000118.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000117.txt
LLM response:
z (chemical): "calcium", "Ca2+", "calcium ion"
y (chemical): "calcium", "Ca2+", "intracellular calcium"
Reason: Both z and y are related to calcium in the model, with z representing calcium in the cytosol and y representing calcium in the InsP3-insensitive pool, indicating they are the same chemical entity but in different cellular locations.
Synonyms dict: {'z': ['calcium', 'Ca2+', 'calcium ion'], 'y': ['calcium', 'Ca2+', 'intracellular calcium']}
Evaluating 118/1075: BIOMD0000000118.xml
Evaluating 119/1075: BIOMD0000000119.xml

2025-11-20 12:22:56,761 - WARNING - Skipping BIOMD0000000120.xml - no results generated
2025-11-20 12:22:56,766 - WARNING - Skipping BIOMD0000000121.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000119.txt
LLM response:
Ca (chemical): "calcium ion", "calcium(2+)", "Ca2+"
Reason: The species Ca is likely calcium, an essential chemical element and ion important in biological processes, particularly in neuronal signaling and muscle contraction, which is consistent with the context of the model describing somatic bursting in CA1 pyramidal cells.
Synonyms dict: {'Ca': ['calcium ion', 'calcium(2+)', 'Ca2+']}
Evaluating 120/1075: BIOMD0000000120.xml
Evaluating 121/1075: BIOMD0000000121.xml
Evaluating 122/1075: BIOMD0000000122.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000122.txt
LLM response:
Ca_Nuc (chemical): "calcium ion", "Ca2+", "calcium(2+)"
Ca_Cyt (chemical): "calcium ion", "Ca2+", "calcium(2+)"
Reason: Both Ca_Nuc and Ca_Cyt are identified as "Calcium in Nucleus" and "Calcium in Cytosol" respectively in the display names, indicating they represent the same chemical entity, calcium, in different cellular locations.
Synonyms dict: {'Ca_Nuc': ['calcium ion', 'Ca2+', 'calcium(2+)'], 'Ca_Cyt': ['calcium ion', 'Ca2+', 'calcium(2+)']}
Evaluating 123/1075: BIOMD0000000123.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000123.txt
LLM response:
Ca_Nuc (chemical): "calcium ion", "Ca2+", "calcium"
Ca_Cyt (chemical): "calcium ion", "Ca2+", "calcium"
Reason: Both Ca_Nuc and Ca_Cyt are referred to as "Calcium" in the display names, indicating they represent the same chemical entity, calcium ions, in different cellular locations (nucleus and cytosol).
Synonyms dict: {'Ca_Nuc': ['calcium ion', 'Ca2+', 'calcium'], 'Ca_Cyt': ['calcium ion', 'Ca2+', 'calcium']}
Evaluating 124/1075: BIOMD0000000124.xml

2025-11-20 12:23:00,527 - WARNING - Skipping BIOMD0000000125.xml - no results generated
2025-11-20 12:23:00,534 - WARNING - Skipping BIOMD0000000126.xml - no results generated
2025-11-20 12:23:00,537 - WARNING - Skipping BIOMD0000000127.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000124.txt
LLM response:
c (chemical): "calcium ion", "Ca2+", "free calcium"
cer (chemical): "endoplasmic reticulum calcium", "ER calcium", "calcium ion (ER)"
Reason: Both c and cer are related to calcium concentrations, with c referring to cytosolic free calcium and cer referring to calcium concentration in the endoplasmic reticulum, indicating they are chemical species involved in the model of potassium channel activity.
Synonyms dict: {'c': ['calcium ion', 'Ca2+', 'free calcium'], 'cer': ['endoplasmic reticulum calcium', 'ER calcium', 'calcium ion (ER)']}
Evaluating 125/1075: BIOMD0000000125.xml
Evaluating 126/1075: BIOMD0000000126.xml
Evaluating 127/1075: BIOMD0000000127.xml
Evaluating 128/1075: BIOMD0000000128.xml

2025-11-20 12:23:02,094 - WARNING - Skipping BIOMD0000000129.xml - no results generated
2025-11-20 12:23:02,096 - WARNING - Skipping BIOMD0000000130.xml - no results generated
2025-11-20 12:23:02,098 - WARNING - Skipping BIOMD0000000131.xml - no results generated
2025-11-20 12:23:02,100 - WARNING - Skipping BIOMD0000000132.xml - no results generated
2025-11-20 12:23:02,102 - WARNING - Skipping BIOMD0000000133.xml - no results generated
2025-11-20 12:23:02,105 - WARNING - Skipping BIOMD0000000134.xml - no results generated
2025-11-20 12:23:02,107 - WARNING - Skipping BIOMD0000000135.xml - no results generated
2025-11-20 12:23:02,110 - WARNING - Skipping BIOMD0000000136.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000128.txt
LLM response:
c (chemical): "calcium ion", "Ca2+", "cytosolic calcium"
cer (chemical): "calcium ion", "Ca2+", "endoplasmic reticulum calcium"
cAMP (chemical): "cyclic adenosine monophosphate", "cAMP", "cyclic AMP"

Reason: c and cer are annotated as chemical because they represent calcium concentrations in different cellular locations, and calcium is a chemical element. cAMP is also annotated as chemical because it is a well-known cyclic nucleotide that acts as a second messenger in cellular signaling pathways. The display names and the context of the model, which involves cellular signaling and calcium concentrations, support these annotations.
Synonyms dict: {'c': ['calcium ion', 'Ca2+', 'cytosolic calcium'], 'cer': ['calcium ion', 'Ca2+', 'endoplasmic reticulum calcium'], 'cAMP': ['cyclic adenosine monophosphate', 'cAMP', 'cyclic AMP']}
Evaluating 129/1075: BIOMD0000000129.xml
Evaluating 130/1075: BIOMD0000000130.xml
Evaluating 131/1075: BIOMD0000000131.xml
Evaluating 132/1075: BIOMD0000000132.xml
Evaluating 133/1075: BIOMD0000000133.xml
Evaluating 134/1075: BIOMD0000000134.xml
Evaluating 135/1075: BIOMD0000000135.xml
Evaluating 136/1075: BIOMD0000000136.xml
Evaluating 137/1075: BIOMD0000000137.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000137.txt
LLM response:
x13 (chemical): "Phosphatidylinositol 3,4,5-trisphosphate", "PIP3", "PI(3,4,5)P3"
x14 (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PIP2", "PI(4,5)P2"
x15 (chemical): "Phosphatidylinositol 3,4-bisphosphate", "PIP2(3,4)", "PI(3,4)P2"
Reason: The display names and the model context suggest that these species are phosphoinositides, which are a class of chemical signaling molecules involved in insulin signaling pathways. The reactions also indicate conversions between these phosphoinositides, consistent with known biochemical processes.
Synonyms dict: {'x13': ['Phosphatidylinositol 3,4,5-trisphosphate', 'PIP3', 'PI(3,4,5)P3'], 'x14': ['Phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'PI(4,5)P2'], 'x15': ['Phosphatidylinositol 3,4-bisphosphate', 'PIP2(3,4)', 'PI(3,4)P2']}
Evaluating 138/1075: BIOMD0000000138.xml

2025-11-20 12:23:04,831 - WARNING - Skipping BIOMD0000000139.xml - no results generated
2025-11-20 12:23:04,851 - WARNING - Skipping BIOMD0000000140.xml - no results generated
2025-11-20 12:23:04,855 - WARNING - Skipping BIOMD0000000141.xml - no results generated
2025-11-20 12:23:04,858 - WARNING - Skipping BIOMD0000000142.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000138.txt
LLM response:
c (chemical): "calcium", "calcium ion", "Ca2+"
Reason: The species "c" is annotated as "calcium concentration", indicating it represents the amount of calcium present, which is a chemical entity. Calcium is a common chemical symbol and name, and "calcium ion" and "Ca2+" are standard synonyms.
Synonyms dict: {'c': ['calcium', 'calcium ion', 'Ca2+']}
Evaluating 139/1075: BIOMD0000000139.xml
Evaluating 140/1075: BIOMD0000000140.xml
Evaluating 141/1075: BIOMD0000000141.xml
Evaluating 142/1075: BIOMD0000000142.xml
Evaluating 143/1075: BIOMD0000000143.xml

2025-11-20 12:23:10,240 - WARNING - Skipping BIOMD0000000144.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000143.txt
LLM response:
H2O2_p (chemical): "hydrogen peroxide", "H2O2", "peroxide"
MLTH_p (chemical): "melatonin", "N-acetyl-5-methoxytryptamine", "5-methoxytryptamine"
MLT_p (chemical): "melatonin free radical", "N-acetyl-5-methoxytryptamine radical", "5-methoxytryptamine radical"
O2minus_p (chemical): "superoxide", "super oxide anion", "O2-"
H_p (chemical): "hydrogen ion", "proton", "H+"
O2_p (chemical): "oxygen", "dioxygen", "O2"
NADPH_c (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
O2_c (chemical): "oxygen", "dioxygen", "O2"
NADPplus_c (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP+", "oxidized NADP"
H2O2_c (chemical): "hydrogen peroxide", "H2O2", "peroxide"
NADP_c (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP", "NADP+"
O2minus_c (chemical): "superoxide", "super oxide anion", "O2-"
H_c (chemical): "hydrogen ion", "proton", "H+"
MLT_c (chemical): "melatonin free radical", "N-acetyl-5-methoxytryptamine radical", "5-methoxytryptamine radical"
NADP2_c (chemical): "nicotinamide adenine dinucleotide phosphate dimer", "NADP dimer", "NADP2"
Reason: All species are assigned as chemicals because they are involved in biochemical reactions and are not genes or proteins. The suffixes _p and _c likely indicate different compartments (e.g., peroxisome and cytosol), but do not affect the entity type. The names are standardized based on common biochemical nomenclature.
Synonyms dict: {'H2O2_p': ['hydrogen peroxide', 'H2O2', 'peroxide'], 'MLTH_p': ['melatonin', 'N-acetyl-5-methoxytryptamine', '5-methoxytryptamine'], 'MLT_p': ['melatonin free radical', 'N-acetyl-5-methoxytryptamine radical', '5-methoxytryptamine radical'], 'O2minus_p': ['superoxide', 'super oxide anion', 'O2-'], 'H_p': ['hydrogen ion', 'proton', 'H+'], 'O2_p': ['oxygen', 'dioxygen', 'O2'], 'NADPH_c': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'O2_c': ['oxygen', 'dioxygen', 'O2'], 'NADPplus_c': ['nicotinamide adenine dinucleotide phosphate', 'NADP+', 'oxidized NADP'], 'H2O2_c': ['hydrogen peroxide', 'H2O2', 'peroxide'], 'NADP_c': ['nicotinamide adenine dinucleotide phosphate', 'NADP', 'NADP+'], 'O2minus_c': ['superoxide', 'super oxide anion', 'O2-'], 'H_c': ['hydrogen ion', 'proton', 'H+'], 'MLT_c': ['melatonin free radical', 'N-acetyl-5-methoxytryptamine radical', '5-methoxytryptamine radical'], 'NADP2_c': ['nicotinamide adenine dinucleotide phosphate dimer', 'NADP dimer', 'NADP2']}
Evaluating 144/1075: BIOMD0000000144.xml
Evaluating 145/1075: BIOMD0000000145.xml

2025-11-20 12:23:12,525 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000145.txt
LLM response:
Galpha_GTP (protein): "Galpha subunit", "G protein alpha subunit", "Gα"
IP3 (chemical): "Inositol trisphosphate", "Myo-inositol 1,4,5-trisphosphate", "IP3"
Ca_ER (chemical): "Calcium ion", "Ca2+", "Calcium(2+)"
Ca_Cyt (chemical): "Calcium ion", "Ca2+", "Calcium(2+)"
DG (chemical): "Diacylglycerol", "DAG", "1,2-Diacylglycerol"

Reason: Galpha_GTP is a protein because it is a subunit of a G protein, which is a type of protein complex. IP3, Ca_ER, Ca_Cyt, and DG are chemicals because they are small molecules involved in cellular signaling pathways. IP3 is a second messenger molecule, Ca_ER and Ca_Cyt represent calcium ions in different cellular compartments, and DG is a lipid molecule involved in signaling. The model context and display names support these annotations.
Synonyms dict: {'Galpha_GTP': ['Galpha subunit', 'G protein alpha subunit', 'Gα'], 'IP3': ['Inositol trisphosphate', 'Myo-inositol 1,4,5-trisphosphate', 'IP3'], 'Ca_ER': ['Calcium ion', 'Ca2+', 'Calcium(2+)'], 'Ca_Cyt': ['Calcium ion', 'Ca2+', 'Calcium(2+)'], 'DG': ['Diacylglycerol', 'DAG', '1,2-Diacylglycerol']}
Evaluating 146/1075: BIOMD0000000146.xml

2025-11-20 12:23:16,592 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:23:16,664 - WARNING - Skipping BIOMD0000000147.xml - no results generated
2025-11-20 12:23:16,668 - WARNING - Skipping BIOMD0000000148.xml - no results generated
2025-11-20 12:23:16,681 - WARNING - Skipping BIOMD0000000149.xml - no results generated
2025-11-20 12:23:16,684 - WARNING - Skipping BIOMD0000000150.xml - no results generated
2025-11-20 12:23:16,708 - WARNING - Skipping BIOMD0000000151.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000146.txt
LLM response:
AktPIP3 (complex): "Akt-PIP3 complex", "Akt1-PIP3 complex", "Protein Kinase B-PIP3 complex"
AktPIPP (complex): "Akt-PIP2 complex", "Akt1-PIP2 complex", "Protein Kinase B-PIP2 complex"
ERKP (protein): "phosphorylated ERK", "p44/42 MAPK", "extracellular signal-regulated kinase"
ERKPP (protein): "dual phosphorylated ERK", "ppERK", "phospho-ERK"
MEKP (protein): "phosphorylated MEK", "pMEK", "mitogen-activated protein kinase kinase"
MEKPP (unknown): "UNK"
PIP3 (chemical): "phosphatidylinositol 3,4,5-trisphosphate", "PI(3,4,5)P3", "PtdIns(3,4,5)P3"
RasGDP (protein): "Ras-GDP", "Ras protein", "GTPase KRas"
RasGTP (protein): "Ras-GTP", "active Ras", "GTP-bound Ras"

Reason: The model appears to be a MAPK signaling pathway model, where Akt, ERK, and MEK are proteins that undergo phosphorylation, and PIP3 is a phospholipid secondary messenger. RasGDP and RasGTP represent the inactive and active forms of the Ras protein, respectively. The "P" suffix in species names likely indicates phosphorylation, and the presence of "PIP3" in complex names suggests a binding interaction between the protein and the phospholipid. MEKPP is unknown due to lack of information about its specific form or function.
Synonyms dict: {'AktPIP3': ['Akt-PIP3 complex', 'Akt1-PIP3 complex', 'Protein Kinase B-PIP3 complex'], 'AktPIPP': ['Akt-PIP2 complex', 'Akt1-PIP2 complex', 'Protein Kinase B-PIP2 complex'], 'ERKP': ['phosphorylated ERK', 'p44/42 MAPK', 'extracellular signal-regulated kinase'], 'ERKPP': ['dual phosphorylated ERK', 'ppERK', 'phospho-ERK'], 'MEKP': ['phosphorylated MEK', 'pMEK', 'mitogen-activated protein kinase kinase'], 'MEKPP': ['UNK'], 'PIP3': ['phosphatidylinositol 3,4,5-trisphosphate', 'PI(3,4,5)P3', 'PtdIns(3,4,5)P3'], 'RasGDP': ['Ras-GDP', 'Ras protein', 'GTPase KRas'], 'RasGTP': ['Ras-GTP', 'active Ras', 'GTP-bound Ras']}
Evaluating 147/1075: BIOMD0000000147.xml
Evaluating 148/1075: BIOMD0000000148.xml
Evaluating 149/1075: BIOMD0000000149.xml
Evaluating 150/1075: BIOMD0000000150.xml
Evaluating 151/1075: BIOMD0000000151.xml
Evaluating 152/1075: BIOMD0000000152.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000152.txt
LLM response:
Ca (chemical): "calcium", "calcium ion", "Ca2+"
PP2BinactiveCa2 (complex): "PP2B inactive calcium complex", "protein phosphatase 2B inactive calcium complex", "Ca2+-PP2B inactive complex"
cAMP (chemical): "cyclic adenosine monophosphate", "cAMP", "cyclic AMP"
cAMP_R2C2 (complex): "cAMP-R2C2 complex", "cAMP-receptor complex", "cyclic AMP-receptor complex"
cAMP2_R2C2 (complex): "cAMP2-R2C2 complex", "di-cAMP-receptor complex", "cyclic AMP dimer-receptor complex"
cAMP3_R2C2 (complex): "cAMP3-R2C2 complex", "tri-cAMP-receptor complex", "cyclic AMP trimer-receptor complex"
cAMP4_R2C2 (complex): "cAMP4-R2C2 complex", "tetra-cAMP-receptor complex", "cyclic AMP tetramer-receptor complex"
cAMP4_R2C (complex): "cAMP4-R2C complex", "tetra-cAMP-receptor subcomplex", "cyclic AMP tetramer-receptor subcomplex"
cAMP4_R2 (complex): "cAMP4-R2 complex", "tetra-cAMP-receptor subunit complex", "cyclic AMP tetramer-receptor subunit complex"
cAMP_PDE (complex): "cAMP-phosphodiesterase complex", "cAMP-PDE complex", "cyclic AMP-phosphodiesterase complex"
cAMP_PDEP (complex): "cAMP-phosphodiesterase phosphatase complex", "cAMP-PDEP complex", "cyclic AMP-phosphodiesterase phosphatase complex"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
Reason: The species were annotated based on their display names and reaction equations. Ca is a chemical as it represents calcium ions. PP2BinactiveCa2 is a complex as it represents a protein phosphatase 2B inactive complex bound to calcium ions. cAMP and AMP are chemicals as they represent cyclic adenosine monophosphate and adenosine monophosphate, respectively. The cAMP_R2C2, cAMP2_R2C2, cAMP3_R2C2, and cAMP4_R2C2 species are complexes as they represent cAMP-receptor complexes with varying numbers of cAMP molecules bound. The cAMP4_R2C and cAMP4_R2 species are also complexes as they represent subcomplexes of the cAMP-receptor complex. The cAMP_PDE and cAMP_PDEP species are complexes as they represent cAMP bound to phosphodiesterase and phosphodiesterase phosphatase, respectively.
Synonyms dict: {'Ca': ['calcium', 'calcium ion', 'Ca2+'], 'PP2BinactiveCa2': ['PP2B inactive calcium complex', 'protein phosphatase 2B inactive calcium complex', 'Ca2+-PP2B inactive complex'], 'cAMP': ['cyclic adenosine monophosphate', 'cAMP', 'cyclic AMP'], 'cAMP_R2C2': ['cAMP-R2C2 complex', 'cAMP-receptor complex', 'cyclic AMP-receptor complex'], 'cAMP2_R2C2': ['cAMP2-R2C2 complex', 'di-cAMP-receptor complex', 'cyclic AMP dimer-receptor complex'], 'cAMP3_R2C2': ['cAMP3-R2C2 complex', 'tri-cAMP-receptor complex', 'cyclic AMP trimer-receptor complex'], 'cAMP4_R2C2': ['cAMP4-R2C2 complex', 'tetra-cAMP-receptor complex', 'cyclic AMP tetramer-receptor complex'], 'cAMP4_R2C': ['cAMP4-R2C complex', 'tetra-cAMP-receptor subcomplex', 'cyclic AMP tetramer-receptor subcomplex'], 'cAMP4_R2': ['cAMP4-R2 complex', 'tetra-cAMP-receptor subunit complex', 'cyclic AMP tetramer-receptor subunit complex'], 'cAMP_PDE': ['cAMP-phosphodiesterase complex', 'cAMP-PDE complex', 'cyclic AMP-phosphodiesterase complex'], 'cAMP_PDEP': ['cAMP-phosphodiesterase phosphatase complex', 'cAMP-PDEP complex', 'cyclic AMP-phosphodiesterase phosphatase complex'], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"]}
Evaluating 153/1075: BIOMD0000000153.xml

2025-11-20 12:23:33,960 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:23:34,766 - WARNING - Skipping BIOMD0000000154.xml - no results generated
2025-11-20 12:23:34,768 - WARNING - Skipping BIOMD0000000155.xml - no results generated
2025-11-20 12:23:34,771 - WARNING - Skipping BIOMD0000000156.xml - no results generated
2025-11-20 12:23:34,775 - WARNING - Skipping BIOMD0000000157.xml - no results generated
2025-11-20 12:23:34,779 - WARNING - Skipping BIOMD0000000158.xml - no results generated
2025-11-20 12:23:34,782 - WARNING - Skipping BIOMD0000000159.xml - no results generated
2025-11-20 12:23:34,796 - WARNING - Skipping BIOMD0000000160.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000153.txt
LLM response:
PP2B (protein): "protein phosphatase 2B", "calcineurin", "PP2B"
D34_PP2B (complex): "D34-PP2B complex", "PP2B-D34 complex", "protein phosphatase 2B-D34 complex"
D34_75_PP2B (complex): "D34:75-PP2B complex", "PP2B-D34:75 complex", "protein phosphatase 2B-D34:75 complex"
D34_137_PP2B (complex): "D34:137-PP2B complex", "PP2B-D34:137 complex", "protein phosphatase 2B-D34:137 complex"
D34_75_137_PP2B (complex): "D34:75:137-PP2B complex", "PP2B-D34:75:137 complex", "protein phosphatase 2B-D34:75:137 complex"
Ca (chemical): "calcium", "calcium ion", "Ca2+"
PP2BinactiveCa2 (protein): "inactive protein phosphatase 2B", "calcineurin-Ca2+", "PP2B-Ca2+"
cAMP (chemical): "cyclic adenosine monophosphate", "cAMP", "cyclic AMP"
cAMP_R2C2 (complex): "cAMP-R2C2 complex", "R2C2-cAMP complex", "cAMP-bound R2C2"
cAMP2_R2C2 (complex): "cAMP2-R2C2 complex", "R2C2-cAMP2 complex", "cAMP2-bound R2C2"
cAMP3_R2C2 (complex): "cAMP3-R2C2 complex", "R2C2-cAMP3 complex", "cAMP3-bound R2C2"
cAMP4_R2C2 (complex): "cAMP4-R2C2 complex", "R2C2-cAMP4 complex", "cAMP4-bound R2C2"
cAMP4_R2C (complex): "cAMP4-R2C complex", "R2C-cAMP4 complex", "cAMP4-bound R2C"
cAMP4_R2 (complex): "cAMP4-R2 complex", "R2-cAMP4 complex", "cAMP4-bound R2"
cAMP_PDE (complex): "cAMP-PDE complex", "PDE-cAMP complex", "cAMP-bound PDE"
cAMP_PDEP (complex): "cAMP-PDEP complex", "PDEP-cAMP complex", "cAMP-bound PDEP"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine phosphate"
D34_75_PP2ACa (complex): "D34:75-PP2ACa complex", "PP2ACa-D34:75 complex", "protein phosphatase 2ACa-D34:75 complex"
D34_75_137_PP2ACa (complex): "D34:75:137-PP2ACa complex", "PP2ACa-D34:75:137 complex", "protein phosphatase 2ACa-D34:75:137 complex"
D75_PP2ACa (complex): "D75-PP2ACa complex", "PP2ACa-D75 complex", "protein phosphatase 2ACa-D75 complex"
D75_137_PP2ACa (complex): "D75:137-PP2ACa complex", "PP2ACa-D75:137 complex", "protein phosphatase 2ACa-D75:137 complex"
D34_75_PP2APCa (complex): "D34:75-PP2APCa complex", "PP2APCa-D34:75 complex", "protein phosphatase 2APCa-D34:75 complex"
D34_75_137_PP2APCa (complex): "D34:75:137-PP2APCa complex", "PP2APCa-D34:75:137 complex", "protein phosphatase 2APCa-D34:75:137 complex"
D75_PP2APCa (complex): "D75-PP2APCa complex", "PP2APCa-D75 complex", "protein phosphatase 2APCa-D75 complex"
D75_137_PP2APCa (complex): "D75:137-PP2APCa complex", "PP2APCa-D75:137 complex", "protein phosphatase 2APCa-D75:137 complex"
PP2ACa (protein): "protein phosphatase 2A-Ca", "PP2A-Ca", "calcineurin"
PP2APCa (protein): "protein phosphatase 2A-PCa", "PP2A-PCa", "protein phosphatase 2APCa"
PP2ACa_PKA (complex): "PP2ACa-PKA complex", "PKA-PP2ACa complex", "protein kinase A-PP2ACa complex"
Reason: Most species are complexes of proteins and other molecules, with some being chemical species like Ca and cAMP. PP2B, PP2ACa, and PP2APCa are likely protein phosphatases, while PKA is a protein kinase. The D34, D75, and D137 species are unknown, but based on their interactions, they may be proteins or protein complexes. The R2C2 species is likely a protein or protein complex that binds to cAMP. The PDE and PDEP species are likely enzymes that degrade cAMP.
Synonyms dict: {'PP2B': ['protein phosphatase 2B', 'calcineurin', 'PP2B'], 'D34_PP2B': ['D34-PP2B complex', 'PP2B-D34 complex', 'protein phosphatase 2B-D34 complex'], 'D34_75_PP2B': ['D34:75-PP2B complex', 'PP2B-D34:75 complex', 'protein phosphatase 2B-D34:75 complex'], 'D34_137_PP2B': ['D34:137-PP2B complex', 'PP2B-D34:137 complex', 'protein phosphatase 2B-D34:137 complex'], 'D34_75_137_PP2B': ['D34:75:137-PP2B complex', 'PP2B-D34:75:137 complex', 'protein phosphatase 2B-D34:75:137 complex'], 'Ca': ['calcium', 'calcium ion', 'Ca2+'], 'PP2BinactiveCa2': ['inactive protein phosphatase 2B', 'calcineurin-Ca2+', 'PP2B-Ca2+'], 'cAMP': ['cyclic adenosine monophosphate', 'cAMP', 'cyclic AMP'], 'cAMP_R2C2': ['cAMP-R2C2 complex', 'R2C2-cAMP complex', 'cAMP-bound R2C2'], 'cAMP2_R2C2': ['cAMP2-R2C2 complex', 'R2C2-cAMP2 complex', 'cAMP2-bound R2C2'], 'cAMP3_R2C2': ['cAMP3-R2C2 complex', 'R2C2-cAMP3 complex', 'cAMP3-bound R2C2'], 'cAMP4_R2C2': ['cAMP4-R2C2 complex', 'R2C2-cAMP4 complex', 'cAMP4-bound R2C2'], 'cAMP4_R2C': ['cAMP4-R2C complex', 'R2C-cAMP4 complex', 'cAMP4-bound R2C'], 'cAMP4_R2': ['cAMP4-R2 complex', 'R2-cAMP4 complex', 'cAMP4-bound R2'], 'cAMP_PDE': ['cAMP-PDE complex', 'PDE-cAMP complex', 'cAMP-bound PDE'], 'cAMP_PDEP': ['cAMP-PDEP complex', 'PDEP-cAMP complex', 'cAMP-bound PDEP'], 'AMP': ['adenosine monophosphate', 'AMP', 'adenosine phosphate'], 'D34_75_PP2ACa': ['D34:75-PP2ACa complex', 'PP2ACa-D34:75 complex', 'protein phosphatase 2ACa-D34:75 complex'], 'D34_75_137_PP2ACa': ['D34:75:137-PP2ACa complex', 'PP2ACa-D34:75:137 complex', 'protein phosphatase 2ACa-D34:75:137 complex'], 'D75_PP2ACa': ['D75-PP2ACa complex', 'PP2ACa-D75 complex', 'protein phosphatase 2ACa-D75 complex'], 'D75_137_PP2ACa': ['D75:137-PP2ACa complex', 'PP2ACa-D75:137 complex', 'protein phosphatase 2ACa-D75:137 complex'], 'D34_75_PP2APCa': ['D34:75-PP2APCa complex', 'PP2APCa-D34:75 complex', 'protein phosphatase 2APCa-D34:75 complex'], 'D34_75_137_PP2APCa': ['D34:75:137-PP2APCa complex', 'PP2APCa-D34:75:137 complex', 'protein phosphatase 2APCa-D34:75:137 complex'], 'D75_PP2APCa': ['D75-PP2APCa complex', 'PP2APCa-D75 complex', 'protein phosphatase 2APCa-D75 complex'], 'D75_137_PP2APCa': ['D75:137-PP2APCa complex', 'PP2APCa-D75:137 complex', 'protein phosphatase 2APCa-D75:137 complex'], 'PP2ACa': ['protein phosphatase 2A-Ca', 'PP2A-Ca', 'calcineurin'], 'PP2APCa': ['protein phosphatase 2A-PCa', 'PP2A-PCa', 'protein phosphatase 2APCa'], 'PP2ACa_PKA': ['PP2ACa-PKA complex', 'PKA-PP2ACa complex', 'protein kinase A-PP2ACa complex']}
Evaluating 154/1075: BIOMD0000000154.xml
Evaluating 155/1075: BIOMD0000000155.xml
Evaluating 156/1075: BIOMD0000000156.xml
Evaluating 157/1075: BIOMD0000000157.xml
Evaluating 158/1075: BIOMD0000000158.xml
Evaluating 159/1075: BIOMD0000000159.xml
Evaluating 160/1075: BIOMD0000000160.xml
Evaluating 161/1075: BIOMD0000000161.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000161.txt
LLM response:
PIP_PM (chemical): "phosphatidylinositol 4-phosphate", "PIP", "phosphatidylinositol phosphate"
PI_PM (chemical): "phosphatidylinositol", "PI", "phosphatidyl inositol"
CaCAPRI_PM_PM (complex): "Ca-CAPRI complex", "calcium CAPRI complex", "Ca2+-CAPRI"
PIP2_PM (chemical): "phosphatidylinositol 4,5-bisphosphate", "PIP2", "phosphatidylinositol bisphosphate"
Ca (chemical): "calcium", "Ca2+", "calcium ion"
RinhCa (complex): "Rinh-Ca complex", "Rinh calcium complex", "Rinh-Ca2+"
IP3 (chemical): "inositol trisphosphate", "IP3", "inositol 1,4,5-trisphosphate"
Ca_RasGRP_GM_GM (complex): "Ca-RasGRP complex", "calcium RasGRP complex", "Ca2+-RasGRP"
DAG_GM_GM (chemical): "diacylglycerol", "DAG", "diglyceride"
CaCAPRI_cyt (complex): "Ca-CAPRI complex", "calcium CAPRI complex", "Ca2+-CAPRI"
DAG_PM (chemical): "diacylglycerol", "DAG", "diglyceride"
Ca_PLCe_cyt (complex): "Ca-PLCe complex", "calcium PLCe complex", "Ca2+-PLCe"
Ras_CaPLCe_GM (complex): "Ras-CaPLCe complex", "Ras calcium PLCe complex", "Ras-Ca2+-PLCe"
PIP2_GM_GM (chemical): "phosphatidylinositol 4,5-bisphosphate", "PIP2", "phosphatidylinositol bisphosphate"
Ca_ER (chemical): "calcium", "Ca2+", "calcium ion"
CaRasGRP1_cyt (complex): "Ca-RasGRP1 complex", "calcium RasGRP1 complex", "Ca2+-RasGRP1"
Reason: Most species are annotated based on their names and the context of the model, which appears to be related to Ras activation and cell signaling. PIP_PM, PI_PM, PIP2_PM, and PIP2_GM_GM are likely phosphatidylinositol phosphates, which are chemical species. Ca is likely calcium, a chemical species. CaCAPRI_PM_PM, RinhCa, Ca_RasGRP_GM_GM, CaCAPRI_cyt, Ca_PLCe_cyt, Ras_CaPLCe_GM, and CaRasGRP1_cyt are likely complexes, as they appear to be combinations of different species. DAG_GM_GM and DAG_PM are likely diacylglycerol, a chemical species. IP3 is likely inositol trisphosphate, a chemical species. Ca_ER is likely calcium, a chemical species, in the endoplasmic reticulum.
Synonyms dict: {'PIP_PM': ['phosphatidylinositol 4-phosphate', 'PIP', 'phosphatidylinositol phosphate'], 'PI_PM': ['phosphatidylinositol', 'PI', 'phosphatidyl inositol'], 'CaCAPRI_PM_PM': ['Ca-CAPRI complex', 'calcium CAPRI complex', 'Ca2+-CAPRI'], 'PIP2_PM': ['phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'phosphatidylinositol bisphosphate'], 'Ca': ['calcium', 'Ca2+', 'calcium ion'], 'RinhCa': ['Rinh-Ca complex', 'Rinh calcium complex', 'Rinh-Ca2+'], 'IP3': ['inositol trisphosphate', 'IP3', 'inositol 1,4,5-trisphosphate'], 'Ca_RasGRP_GM_GM': ['Ca-RasGRP complex', 'calcium RasGRP complex', 'Ca2+-RasGRP'], 'DAG_GM_GM': ['diacylglycerol', 'DAG', 'diglyceride'], 'CaCAPRI_cyt': ['Ca-CAPRI complex', 'calcium CAPRI complex', 'Ca2+-CAPRI'], 'DAG_PM': ['diacylglycerol', 'DAG', 'diglyceride'], 'Ca_PLCe_cyt': ['Ca-PLCe complex', 'calcium PLCe complex', 'Ca2+-PLCe'], 'Ras_CaPLCe_GM': ['Ras-CaPLCe complex', 'Ras calcium PLCe complex', 'Ras-Ca2+-PLCe'], 'PIP2_GM_GM': ['phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'phosphatidylinositol bisphosphate'], 'Ca_ER': ['calcium', 'Ca2+', 'calcium ion'], 'CaRasGRP1_cyt': ['Ca-RasGRP1 complex', 'calcium RasGRP1 complex', 'Ca2+-RasGRP1']}
Evaluating 162/1075: BIOMD0000000162.xml

2025-11-20 12:23:46,214 - WARNING - Skipping BIOMD0000000163.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000162.txt
LLM response:
PABCa_D_Cytosol (complex): "Calcium-bound phosphatase A", "Phosphatase A-Ca complex"
Ca_D_ER (chemical): "Calcium ion", "Ca2+"
PABMg_D_Cytosol (complex): "Magnesium-bound phosphatase A", "Phosphatase A-Mg complex"
PABCa_Cytosol (complex): "Calcium-bound phosphatase A", "Phosphatase A-Ca complex"
Mg_Cytosol (chemical): "Magnesium ion", "Mg2+"
Ca_ER (chemical): "Calcium ion", "Ca2+"
Ca_D_Cytosol (chemical): "Calcium ion", "Ca2+"
PABMg_Cytosol (complex): "Magnesium-bound phosphatase A", "Phosphatase A-Mg complex"
IP3_Cytosol (chemical): "Inositol trisphosphate", "IP3"
Ca_Extracellular (chemical): "Calcium ion", "Ca2+"
IP3_D_Cytosol (chemical): "Inositol trisphosphate", "IP3"
Mg_D_Cytosol (chemical): "Magnesium ion", "Mg2+"
Ca_Cytosol (chemical): "Calcium ion", "Ca2+"
Ca_D_Extracellular (chemical): "Calcium ion", "Ca2+"
Reason: The species are annotated based on their names and the context of the "Hernjak2005_Calcium_Signaling" model. Species containing "Ca" are likely Calcium ions, while those with "Mg" are Magnesium ions. "IP3" is a common abbreviation for Inositol trisphosphate. "PABCa" and "PABMg" are likely complexes of phosphatase A with Calcium or Magnesium, respectively. The "_D_" and "_Cytosol" suffixes indicate the location and possibly the state of the species, but do not affect the overall entity type. The model's focus on Calcium signaling also supports the annotation of Calcium-related species as chemicals.
Synonyms dict: {'PABCa_D_Cytosol': ['Calcium-bound phosphatase A', 'Phosphatase A-Ca complex'], 'Ca_D_ER': ['Calcium ion', 'Ca2+'], 'PABMg_D_Cytosol': ['Magnesium-bound phosphatase A', 'Phosphatase A-Mg complex'], 'PABCa_Cytosol': ['Calcium-bound phosphatase A', 'Phosphatase A-Ca complex'], 'Mg_Cytosol': ['Magnesium ion', 'Mg2+'], 'Ca_ER': ['Calcium ion', 'Ca2+'], 'Ca_D_Cytosol': ['Calcium ion', 'Ca2+'], 'PABMg_Cytosol': ['Magnesium-bound phosphatase A', 'Phosphatase A-Mg complex'], 'IP3_Cytosol': ['Inositol trisphosphate', 'IP3'], 'Ca_Extracellular': ['Calcium ion', 'Ca2+'], 'IP3_D_Cytosol': ['Inositol trisphosphate', 'IP3'], 'Mg_D_Cytosol': ['Magnesium ion', 'Mg2+'], 'Ca_Cytosol': ['Calcium ion', 'Ca2+'], 'Ca_D_Extracellular': ['Calcium ion', 'Ca2+']}
Evaluating 163/1075: BIOMD0000000163.xml
Evaluating 164/1075: BIOMD0000000164.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000164.txt
LLM response:
Carrier_RanGTP_Cytosol (complex): "RanGTP-Carrier complex", "GTP-bound Ran-Carrier complex", "Ran-Carrier-GTP complex"
RanBP1_Carrier_RanGTP_Cytosol (complex): "RanBP1-RanGTP-Carrier complex", "RanBP1-GTP-bound Ran-Carrier complex", "RanBP1-Ran-Carrier-GTP complex"
RanGDP_Nucleus (chemical): "RanGDP", "GDP-bound Ran", "Ran guanosine diphosphate"
RanGTP_Nucleus (chemical): "RanGTP", "GTP-bound Ran", "Ran guanosine triphosphate"
NTF2_RanGDP_Nucleus (complex): "NTF2-RanGDP complex", "RanGDP-NTF2 complex", "Nuclear transport factor 2-RanGDP complex"
RanGDP_Cytosol (chemical): "RanGDP", "GDP-bound Ran", "Ran guanosine diphosphate"
Carrier_RanGTP_Nucleus (complex): "RanGTP-Carrier complex", "GTP-bound Ran-Carrier complex", "Ran-Carrier-GTP complex"
NTF2_RanGDP_Cytosol (complex): "NTF2-RanGDP complex", "RanGDP-NTF2 complex", "Nuclear transport factor 2-RanGDP complex"
FRanGTP_Cytosol (chemical): "RanGTP", "GTP-bound Ran", "Ran guanosine triphosphate"
FCarrier_RanGTP_Cytosol (complex): "RanGTP-Carrier complex", "GTP-bound Ran-Carrier complex", "Ran-Carrier-GTP complex"
FRanGDP_Cytosol (chemical): "RanGDP", "GDP-bound Ran", "Ran guanosine diphosphate"
FNTF2_RanGDP_Cytosol (complex): "NTF2-RanGDP complex", "RanGDP-NTF2 complex", "Nuclear transport factor 2-RanGDP complex"
FRanBP1_Carrier_RanGTP_Cytosol (complex): "RanBP1-RanGTP-Carrier complex", "RanBP1-GTP-bound Ran-Carrier complex", "RanBP1-Ran-Carrier-GTP complex"
FCarrier_RanGTP_Nucleus (complex): "RanGTP-Carrier complex", "GTP-bound Ran-Carrier complex", "Ran-Carrier-GTP complex"
FRanGDP_Nucleus (chemical): "RanGDP", "GDP-bound Ran", "Ran guanosine diphosphate"
FNTF2_RanGDP_Nucleus (complex): "NTF2-RanGDP complex", "RanGDP-NTF2 complex", "Nuclear transport factor 2-RanGDP complex"
FRanGTP_Nucleus (chemical): "RanGTP", "GTP-bound Ran", "Ran guanosine triphosphate"
RanGTP_Cytosol (chemical): "RanGTP", "GTP-bound Ran", "Ran guanosine triphosphate"
Reason: The species were annotated based on their names and the reactions they participate in. Species with "Ran" in their name are likely to be related to the Ras-related nuclear protein, which is a small GTPase. Species with "GTP" or "GDP" in their name are likely to be the GTP-bound or GDP-bound forms of Ran. Species with "Carrier" in their name are likely to be complexes between Ran and a carrier protein. Species with "NTF2" in their name are likely to be complexes between RanGDP and the nuclear transport factor 2. Species with "RanBP1" in their name are likely to be complexes between RanGTP and the Ran-binding protein 1. The "F" prefix in some species names may indicate a modified or fluorescently labeled form of the species.
Synonyms dict: {'Carrier_RanGTP_Cytosol': ['RanGTP-Carrier complex', 'GTP-bound Ran-Carrier complex', 'Ran-Carrier-GTP complex'], 'RanBP1_Carrier_RanGTP_Cytosol': ['RanBP1-RanGTP-Carrier complex', 'RanBP1-GTP-bound Ran-Carrier complex', 'RanBP1-Ran-Carrier-GTP complex'], 'RanGDP_Nucleus': ['RanGDP', 'GDP-bound Ran', 'Ran guanosine diphosphate'], 'RanGTP_Nucleus': ['RanGTP', 'GTP-bound Ran', 'Ran guanosine triphosphate'], 'NTF2_RanGDP_Nucleus': ['NTF2-RanGDP complex', 'RanGDP-NTF2 complex', 'Nuclear transport factor 2-RanGDP complex'], 'RanGDP_Cytosol': ['RanGDP', 'GDP-bound Ran', 'Ran guanosine diphosphate'], 'Carrier_RanGTP_Nucleus': ['RanGTP-Carrier complex', 'GTP-bound Ran-Carrier complex', 'Ran-Carrier-GTP complex'], 'NTF2_RanGDP_Cytosol': ['NTF2-RanGDP complex', 'RanGDP-NTF2 complex', 'Nuclear transport factor 2-RanGDP complex'], 'FRanGTP_Cytosol': ['RanGTP', 'GTP-bound Ran', 'Ran guanosine triphosphate'], 'FCarrier_RanGTP_Cytosol': ['RanGTP-Carrier complex', 'GTP-bound Ran-Carrier complex', 'Ran-Carrier-GTP complex'], 'FRanGDP_Cytosol': ['RanGDP', 'GDP-bound Ran', 'Ran guanosine diphosphate'], 'FNTF2_RanGDP_Cytosol': ['NTF2-RanGDP complex', 'RanGDP-NTF2 complex', 'Nuclear transport factor 2-RanGDP complex'], 'FRanBP1_Carrier_RanGTP_Cytosol': ['RanBP1-RanGTP-Carrier complex', 'RanBP1-GTP-bound Ran-Carrier complex', 'RanBP1-Ran-Carrier-GTP complex'], 'FCarrier_RanGTP_Nucleus': ['RanGTP-Carrier complex', 'GTP-bound Ran-Carrier complex', 'Ran-Carrier-GTP complex'], 'FRanGDP_Nucleus': ['RanGDP', 'GDP-bound Ran', 'Ran guanosine diphosphate'], 'FNTF2_RanGDP_Nucleus': ['NTF2-RanGDP complex', 'RanGDP-NTF2 complex', 'Nuclear transport factor 2-RanGDP complex'], 'FRanGTP_Nucleus': ['RanGTP', 'GTP-bound Ran', 'Ran guanosine triphosphate'], 'RanGTP_Cytosol': ['RanGTP', 'GTP-bound Ran', 'Ran guanosine triphosphate']}
Evaluating 165/1075: BIOMD0000000165.xml

2025-11-20 12:23:57,964 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000165.txt
LLM response:
Gsa_gdp_cell (protein): "G protein subunit alpha", "Gα subunit", "Gsa"
Gsa_gtp_cell (protein): "G protein subunit alpha GTP", "Gα-GTP", "Gsa-GTP"
ATP_cell (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
cAMP_cell (chemical): "cyclic adenosine monophosphate", "cAMP", "cyclic AMP"
DMNB_cAMP_cell (chemical): "N6,2'-O-dibutyryl cyclic adenosine monophosphate", "db-cAMP", "dibutyryl cAMP"

Reason: The species can be annotated based on their display names and the reactions they participate in. Gsa_gdp_cell and Gsa_gtp_cell are protein subunits, specifically the alpha subunit of the G protein, in its GDP- and GTP-bound states, respectively. ATP_cell is a chemical, the energy currency of the cell. cAMP_cell is also a chemical, a key second messenger in cellular signaling. DMNB_cAMP_cell is a chemical, a synthetic analog of cAMP. The reactions and display names support these annotations, with Gsa_gdp_cell and Gsa_gtp_cell participating in G protein signaling, ATP_cell being converted to cAMP_cell, and DMNB_cAMP_cell acting as a cAMP analog.
Synonyms dict: {'Gsa_gdp_cell': ['G protein subunit alpha', 'Gα subunit', 'Gsa'], 'Gsa_gtp_cell': ['G protein subunit alpha GTP', 'Gα-GTP', 'Gsa-GTP'], 'ATP_cell': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'cAMP_cell': ['cyclic adenosine monophosphate', 'cAMP', 'cyclic AMP'], 'DMNB_cAMP_cell': ["N6,2'-O-dibutyryl cyclic adenosine monophosphate", 'db-cAMP', 'dibutyryl cAMP']}
Evaluating 166/1075: BIOMD0000000166.xml

2025-11-20 12:23:59,518 - WARNING - Skipping BIOMD0000000167.xml - no results generated
2025-11-20 12:23:59,525 - WARNING - Skipping BIOMD0000000168.xml - no results generated
2025-11-20 12:23:59,536 - WARNING - Skipping BIOMD0000000169.xml - no results generated
2025-11-20 12:23:59,544 - WARNING - Skipping BIOMD0000000170.xml - no results generated
2025-11-20 12:23:59,554 - WARNING - Skipping BIOMD0000000171.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000166.txt
LLM response:
Y (chemical): "calcium ion", "Ca2+", "calcium store"
Z (chemical): "calcium ion", "Ca2+", "cytoplasmic calcium"
Reason: Both Y and Z are related to calcium, and given the context of the model "Zhu2007_TF_modulated_by_Calcium" and the display names, it is clear that they represent different locations of calcium ions within the cell, with Y being calcium stored in a specific compartment and Z being calcium in the cytoplasm. The entity type for both is chemical because they refer to the calcium ion, which is a chemical entity.
Synonyms dict: {'Y': ['calcium ion', 'Ca2+', 'calcium store'], 'Z': ['calcium ion', 'Ca2+', 'cytoplasmic calcium']}
Evaluating 167/1075: BIOMD0000000167.xml
Evaluating 168/1075: BIOMD0000000168.xml
Evaluating 169/1075: BIOMD0000000169.xml
Evaluating 170/1075: BIOMD0000000170.xml
Evaluating 171/1075: BIOMD0000000171.xml
Evaluating 172/1075: BIOMD0000000172.xml

2025-11-20 12:24:06,823 - WARNING - Skipping BIOMD0000000173.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000172.txt
LLM response:
GLCo (chemical): "glucose", "D-glucose", "blood sugar"
GLCi (chemical): "intracellular glucose", "glucose(int)", "D-glucose"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
G6P (chemical): "glucose-6-phosphate", "D-glucose-6-phosphate", "G6P"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
F6P (chemical): "fructose-6-phosphate", "D-fructose-6-phosphate", "F6P"
F16bP (chemical): "fructose-1,6-bisphosphate", "D-fructose-1,6-bisphosphate", "F1,6BP"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
F26bP (chemical): "fructose-2,6-bisphosphate", "D-fructose-2,6-bisphosphate", "F2,6BP"
DHAP (chemical): "dihydroxyacetone phosphate", "DHAP", "glycerone phosphate"
GAP (chemical): "glyceraldehyde-3-phosphate", "D-glyceraldehyde-3-phosphate", "G3P"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD", "NAD+"
BPG (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "BPG"
NADH (chemical): "nicotinamide adenine dinucleotide reduced", "NADH", "NADH2"
P3G (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "3PG"
P2G (chemical): "2-phosphoglycerate", "2-phosphoglyceric acid", "2PG"
PEP (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
PYR (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
AcAld (chemical): "acetaldehyde", "ethanal", "CH3CHO"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
EtOH (chemical): "ethanol", "ethyl alcohol", "CH3CH2OH"
Glycerol (chemical): "glycerol", "glycerin", "1,2,3-propanetriol"
Trehalose (chemical): "trehalose", "mycose", "α,α-trehalose"
Succinate (chemical): "succinate", "succinic acid", "butanedioic acid"
Reason: All the species are identified as chemicals because they are all metabolites or molecules involved in the glycolytic pathway. The standardized names and synonyms are based on common biochemical nomenclature and the display names provided in the model. The entity type for each species is determined based on its role in the glycolytic pathway and its chemical structure.
Synonyms dict: {'GLCo': ['glucose', 'D-glucose', 'blood sugar'], 'GLCi': ['intracellular glucose', 'glucose(int)', 'D-glucose'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'G6P': ['glucose-6-phosphate', 'D-glucose-6-phosphate', 'G6P'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'F6P': ['fructose-6-phosphate', 'D-fructose-6-phosphate', 'F6P'], 'F16bP': ['fructose-1,6-bisphosphate', 'D-fructose-1,6-bisphosphate', 'F1,6BP'], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'F26bP': ['fructose-2,6-bisphosphate', 'D-fructose-2,6-bisphosphate', 'F2,6BP'], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP', 'glycerone phosphate'], 'GAP': ['glyceraldehyde-3-phosphate', 'D-glyceraldehyde-3-phosphate', 'G3P'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD', 'NAD+'], 'BPG': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', 'BPG'], 'NADH': ['nicotinamide adenine dinucleotide reduced', 'NADH', 'NADH2'], 'P3G': ['3-phosphoglycerate', '3-phosphoglyceric acid', '3PG'], 'P2G': ['2-phosphoglycerate', '2-phosphoglyceric acid', '2PG'], 'PEP': ['phosphoenolpyruvate', 'PEP', 'phosphoenolpyruvic acid'], 'PYR': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'AcAld': ['acetaldehyde', 'ethanal', 'CH3CHO'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'EtOH': ['ethanol', 'ethyl alcohol', 'CH3CH2OH'], 'Glycerol': ['glycerol', 'glycerin', '1,2,3-propanetriol'], 'Trehalose': ['trehalose', 'mycose', 'α,α-trehalose'], 'Succinate': ['succinate', 'succinic acid', 'butanedioic acid']}
Evaluating 173/1075: BIOMD0000000173.xml
Evaluating 174/1075: BIOMD0000000174.xml

2025-11-20 12:24:09,137 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:24:09,138 - WARNING - Skipping BIOMD0000000174.xml - no results generated

Evaluating 175/1075: BIOMD0000000175.xml

2025-11-20 12:24:10,672 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000175.txt
LLM response:
P3 (chemical): "Phosphatidylinositol 3,4,5-trisphosphate", "PIP3", "PIP3 lipid"
RsD (protein): "Ras GDP-bound", "Ras-GDP", "GDP-bound Ras"
RsT (protein): "Ras GTP-bound", "Ras-GTP", "GTP-bound Ras"
Reason: P3 is a chemical as it refers to a specific phospholipid, Phosphatidylinositol 3,4,5-trisphosphate. RsD and RsT are proteins as they refer to different states of the Ras protein, with RsD being the GDP-bound state and RsT being the GTP-bound state.
Synonyms dict: {'P3': ['Phosphatidylinositol 3,4,5-trisphosphate', 'PIP3', 'PIP3 lipid'], 'RsD': ['Ras GDP-bound', 'Ras-GDP', 'GDP-bound Ras'], 'RsT': ['Ras GTP-bound', 'Ras-GTP', 'GTP-bound Ras']}
Evaluating 176/1075: BIOMD0000000176.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000176.txt
LLM response:
GLCi (chemical): "glucose", "D-glucose", "blood sugar"
ATP (chemical): "adenosine triphosphate", "ATPase", "adenosine 5'-triphosphate"
G6P (chemical): "glucose-6-phosphate", "D-glucose-6-phosphate", "G6Pase"
ADP (chemical): "adenosine diphosphate", "ADPase", "adenosine 5'-diphosphate"
F6P (chemical): "fructose-6-phosphate", "D-fructose-6-phosphate", "F6Pase"
F16bP (chemical): "fructose-1,6-bisphosphate", "D-fructose-1,6-bisphosphate", "F1,6BP"
F26bP (chemical): "fructose-2,6-bisphosphate", "D-fructose-2,6-bisphosphate", "F2,6BP"
AMP (chemical): "adenosine monophosphate", "AMPase", "adenosine 5'-monophosphate"
DHAP (chemical): "dihydroxyacetone phosphate", "D-glyceraldehyde-3-phosphate", "DHAPase"
GAP (chemical): "glyceraldehyde-3-phosphate", "D-glyceraldehyde-3-phosphate", "GAPase"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "nicotinamide adenine dinucleotide oxidized form"
BPG (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "BPGase"
NADH (chemical): "nicotinamide adenine dinucleotide reduced form", "NADH", "nicotinamide adenine dinucleotide reduced"
P3G (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "P3Gase"
P2G (chemical): "2-phosphoglycerate", "2-phosphoglyceric acid", "P2Gase"
PEP (chemical): "phosphoenolpyruvate", "PEPase", "phosphoenolpyruvic acid"
PYR (chemical): "pyruvate", "pyruvic acid", "PYRase"
AcAld (chemical): "acetaldehyde", "ethanal", "AcAldase"
GLCo (chemical): "glucose external", "extracellular glucose", "blood glucose"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
EtOH (chemical): "ethanol", "ethyl alcohol", "EtOHase"
Glycerol (chemical): "glycerin", "glycerine", "glycerol"
Trehalose (chemical): "mycose", "trehalose", "alpha-D-glucopyranosyl alpha-D-glucopyranoside"
Succinate (chemical): "succinic acid", "butanedioic acid", "succinate"
Reason: All the species are assigned as chemicals because they are all involved in the glycolytic pathway, which is a series of chemical reactions that convert glucose into pyruvate. The standardized names and synonyms are based on common biochemical nomenclature and are ranked by likelihood based on their frequency of use in the scientific literature. The external species GLCo and CO2 are also assigned as chemicals, as they are involved in the transport and exchange of molecules across the cell membrane. The species EtOH and Glycerol are also assigned as chemicals, as they are involved in the fermentation pathway, which is closely related to glycolysis. The species Trehalose is assigned as a chemical, as it is a disaccharide composed of two glucose molecules and is involved in the cellular response to stress. The species Succinate is assigned as a chemical, as it is a key intermediate in the citric acid cycle, which is closely related to glycolysis.
Synonyms dict: {'GLCi': ['glucose', 'D-glucose', 'blood sugar'], 'ATP': ['adenosine triphosphate', 'ATPase', "adenosine 5'-triphosphate"], 'G6P': ['glucose-6-phosphate', 'D-glucose-6-phosphate', 'G6Pase'], 'ADP': ['adenosine diphosphate', 'ADPase', "adenosine 5'-diphosphate"], 'F6P': ['fructose-6-phosphate', 'D-fructose-6-phosphate', 'F6Pase'], 'F16bP': ['fructose-1,6-bisphosphate', 'D-fructose-1,6-bisphosphate', 'F1,6BP'], 'F26bP': ['fructose-2,6-bisphosphate', 'D-fructose-2,6-bisphosphate', 'F2,6BP'], 'AMP': ['adenosine monophosphate', 'AMPase', "adenosine 5'-monophosphate"], 'DHAP': ['dihydroxyacetone phosphate', 'D-glyceraldehyde-3-phosphate', 'DHAPase'], 'GAP': ['glyceraldehyde-3-phosphate', 'D-glyceraldehyde-3-phosphate', 'GAPase'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'nicotinamide adenine dinucleotide oxidized form'], 'BPG': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', 'BPGase'], 'NADH': ['nicotinamide adenine dinucleotide reduced form', 'NADH', 'nicotinamide adenine dinucleotide reduced'], 'P3G': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'P3Gase'], 'P2G': ['2-phosphoglycerate', '2-phosphoglyceric acid', 'P2Gase'], 'PEP': ['phosphoenolpyruvate', 'PEPase', 'phosphoenolpyruvic acid'], 'PYR': ['pyruvate', 'pyruvic acid', 'PYRase'], 'AcAld': ['acetaldehyde', 'ethanal', 'AcAldase'], 'GLCo': ['glucose external', 'extracellular glucose', 'blood glucose'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'EtOH': ['ethanol', 'ethyl alcohol', 'EtOHase'], 'Glycerol': ['glycerin', 'glycerine', 'glycerol'], 'Trehalose': ['mycose', 'trehalose', 'alpha-D-glucopyranosyl alpha-D-glucopyranoside'], 'Succinate': ['succinic acid', 'butanedioic acid', 'succinate']}
Evaluating 177/1075: BIOMD0000000177.xml

2025-11-20 12:24:27,739 - WARNING - Skipping BIOMD0000000178.xml - no results generated
2025-11-20 12:24:27,745 - WARNING - Skipping BIOMD0000000179.xml - no results generated
2025-11-20 12:24:27,752 - WARNING - Skipping BIOMD0000000180.xml - no results generated
2025-11-20 12:24:27,760 - WARNING - Skipping BIOMD0000000181.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000177.txt
LLM response:
GLCi (chemical): "glucose", "D-glucose", "blood sugar"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
G6P (chemical): "glucose-6-phosphate", "G6P", "D-glucose-6-phosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
F6P (chemical): "fructose-6-phosphate", "F6P", "D-fructose-6-phosphate"
F16bP (chemical): "fructose-1,6-bisphosphate", "F1,6BP", "D-fructose-1,6-bisphosphate"
F26bP (chemical): "fructose-2,6-bisphosphate", "F2,6BP", "D-fructose-2,6-bisphosphate"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
DHAP (chemical): "dihydroxyacetone phosphate", "DHAP", "D-glyceraldehyde-3-phosphate"
GAP (chemical): "glyceraldehyde-3-phosphate", "G3P", "D-glyceraldehyde-3-phosphate"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "NAD"
BPG (chemical): "1,3-bisphosphoglycerate", "1,3-BPG", "1,3-bisphosphoglyceric acid"
NADH (chemical): "nicotinamide adenine dinucleotide + hydrogen", "NADH", "reduced NAD"
P3G (chemical): "3-phosphoglycerate", "3PG", "3-phosphoglyceric acid"
P2G (chemical): "2-phosphoglycerate", "2PG", "2-phosphoglyceric acid"
PEP (chemical): "phosphoenolpyruvate", "PEP", "2-phosphoenolpyruvate"
PYR (chemical): "pyruvate", "PYR", "2-oxopropanoic acid"
PYRmito (chemical): "mitochondrial pyruvate", "PYRmito", "pyruvate (mitochondrial)"
AcAld (chemical): "acetaldehyde", "AcAld", "ethanal"
GLCo (chemical): "glucose (extracellular)", "GLCo", "extracellular glucose"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
EtOH (chemical): "ethanol", "EtOH", "ethyl alcohol"
Glycerol (chemical): "glycerol", "Glycerol", "1,2,3-propanetriol"
Trehalose (chemical): "trehalose", "Trehalose", "mycose"
Succinate (chemical): "succinate", "Succinate", "butanedioic acid"
CO2mito (chemical): "mitochondrial carbon dioxide", "CO2mito", "carbon dioxide (mitochondrial)"
Reason: All species are identified as chemicals based on their involvement in the glycolytic pathway and other metabolic reactions. The names provided are standardized and commonly used in biochemistry. The mitochondrial species (PYRmito, CO2mito) are distinguished from their cytosolic counterparts.
Synonyms dict: {'GLCi': ['glucose', 'D-glucose', 'blood sugar'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'G6P': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'F6P': ['fructose-6-phosphate', 'F6P', 'D-fructose-6-phosphate'], 'F16bP': ['fructose-1,6-bisphosphate', 'F1,6BP', 'D-fructose-1,6-bisphosphate'], 'F26bP': ['fructose-2,6-bisphosphate', 'F2,6BP', 'D-fructose-2,6-bisphosphate'], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP', 'D-glyceraldehyde-3-phosphate'], 'GAP': ['glyceraldehyde-3-phosphate', 'G3P', 'D-glyceraldehyde-3-phosphate'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'NAD'], 'BPG': ['1,3-bisphosphoglycerate', '1,3-BPG', '1,3-bisphosphoglyceric acid'], 'NADH': ['nicotinamide adenine dinucleotide + hydrogen', 'NADH', 'reduced NAD'], 'P3G': ['3-phosphoglycerate', '3PG', '3-phosphoglyceric acid'], 'P2G': ['2-phosphoglycerate', '2PG', '2-phosphoglyceric acid'], 'PEP': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvate'], 'PYR': ['pyruvate', 'PYR', '2-oxopropanoic acid'], 'PYRmito': ['mitochondrial pyruvate', 'PYRmito', 'pyruvate (mitochondrial)'], 'AcAld': ['acetaldehyde', 'AcAld', 'ethanal'], 'GLCo': ['glucose (extracellular)', 'GLCo', 'extracellular glucose'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'EtOH': ['ethanol', 'EtOH', 'ethyl alcohol'], 'Glycerol': ['glycerol', 'Glycerol', '1,2,3-propanetriol'], 'Trehalose': ['trehalose', 'Trehalose', 'mycose'], 'Succinate': ['succinate', 'Succinate', 'butanedioic acid'], 'CO2mito': ['mitochondrial carbon dioxide', 'CO2mito', 'carbon dioxide (mitochondrial)']}
Evaluating 178/1075: BIOMD0000000178.xml
Evaluating 179/1075: BIOMD0000000179.xml
Evaluating 180/1075: BIOMD0000000180.xml
Evaluating 181/1075: BIOMD0000000181.xml
Evaluating 182/1075: BIOMD0000000182.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000182.txt
LLM response:
G_GDP_cyto (chemical): "GDP", "guanosine diphosphate", "Guanosine 5'-diphosphate"
ATP_cyto (chemical): "ATP", "adenosine triphosphate", "Adenosine 5'-triphosphate"
AMP_cyto (chemical): "AMP", "adenosine monophosphate", "Adenosine 5'-monophosphate"
cAMP_cyto (chemical): "cAMP", "cyclic adenosine monophosphate", "3',5'-cyclic AMP"

Reason: The species are all related to nucleotides, which are chemical molecules. G_GDP_cyto is likely a G-protein bound to GDP, but the "G_GDP" part refers to the chemical state. ATP_cyto, AMP_cyto, and cAMP_cyto are all well-known chemical molecules involved in cellular signaling, particularly in the context of the cAMP/PKA signaling pathway mentioned in the model notes.
Synonyms dict: {'G_GDP_cyto': ['GDP', 'guanosine diphosphate', "Guanosine 5'-diphosphate"], 'ATP_cyto': ['ATP', 'adenosine triphosphate', "Adenosine 5'-triphosphate"], 'AMP_cyto': ['AMP', 'adenosine monophosphate', "Adenosine 5'-monophosphate"], 'cAMP_cyto': ['cAMP', 'cyclic adenosine monophosphate', "3',5'-cyclic AMP"]}
Evaluating 183/1075: BIOMD0000000183.xml

2025-11-20 12:25:00,489 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000183.txt
LLM response:
species_56 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_57 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_58 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_59 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_60 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_61 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_62 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_63 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_64 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_65 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
species_66 (protein): "calmodulin PP2B complex", "CaM-PP2B complex", "calmodulin-PP2B"
Reason: All species from 56 to 66 are complexes of calmodulin with PP2B, as indicated by their display names (e.g., "camR_ca2_AB_PP2B") and reaction equations, which show them interacting with PP2B (species_50). The model describes an allosteric model for calmodulin activation and its interaction with PP2B, suggesting that these species represent different states or conformations of the calmodulin-PP2B complex.
Synonyms dict: {'species_1': ['calcium', 'Ca2+', 'calcium ion'], 'species_2': ['calmodulin', 'CaM', 'cam'], 'species_3': ['calmodulin', 'CaM', 'cam'], 'species_4': ['calmodulin', 'CaM', 'cam'], 'species_5': ['calmodulin', 'CaM', 'cam'], 'species_6': ['calmodulin', 'CaM', 'cam'], 'species_7': ['calmodulin', 'CaM', 'cam'], 'species_8': ['calmodulin', 'CaM', 'cam'], 'species_9': ['calmodulin', 'CaM', 'cam'], 'species_10': ['calmodulin', 'CaM', 'cam'], 'species_11': ['calmodulin', 'CaM', 'cam'], 'species_12': ['calmodulin', 'CaM', 'cam'], 'species_13': ['calmodulin', 'CaM', 'cam'], 'species_14': ['calmodulin', 'CaM', 'cam'], 'species_15': ['calmodulin', 'CaM', 'cam'], 'species_16': ['calmodulin', 'CaM', 'cam'], 'species_17': ['UNK'], 'species_18': ['calmodulin', 'CaM', 'cam'], 'species_19': ['calmodulin', 'CaM', 'cam'], 'species_20': ['calmodulin', 'CaM', 'cam'], 'species_21': ['calmodulin', 'CaM', 'cam'], 'species_22': ['calmodulin', 'CaM', 'cam'], 'species_23': ['calmodulin', 'CaM', 'cam'], 'species_24': ['calmodulin', 'CaM', 'cam'], 'species_25': ['calmodulin', 'CaM', 'cam'], 'species_26': ['calmodulin', 'CaM', 'cam'], 'species_27': ['calmodulin', 'CaM', 'cam'], 'species_28': ['calmodulin', 'CaM', 'cam'], 'species_29': ['calmodulin', 'CaM', 'cam'], 'species_30': ['calmodulin', 'CaM', 'cam'], 'species_31': ['calmodulin', 'CaM', 'cam'], 'species_32': ['calmodulin', 'CaM', 'cam'], 'species_33': ['CaMKII', 'calcium/calmodulin-dependent protein kinase II', 'CaM kinase II'], 'species_34': ['CaMKII', 'calcium/calmodulin-dependent protein kinase II', 'CaM kinase II'], 'species_35': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_36': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_37': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_38': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_39': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_40': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_41': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_42': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_43': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_44': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_45': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_46': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_47': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_48': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_49': ['CaMKII-calmodulin complex', 'CaM-CaMKII complex', 'CaMKII-CaM complex'], 'species_50': ['PP2B', 'protein phosphatase 2B', 'calcineurin'], 'species_51': ['PP2B-calmodulin complex', 'CaM-PP2B complex', 'PP2B-CaM complex'], 'species_52': ['PP2B-calmodulin complex', 'CaM-PP2B complex', 'PP2B-CaM complex'], 'species_53': ['PP2B-calmodulin complex', 'CaM-PP2B complex', 'PP2B-CaM complex'], 'species_54': ['PP2B-calmodulin complex', 'CaM-PP2B complex', 'PP2B-CaM complex'], 'species_55': ['PP2B-calmodulin complex', 'CaM-PP2B complex', 'PP2B-CaM complex'], 'species_56': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_57': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_58': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_59': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_60': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_61': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_62': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_63': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_64': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_65': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B'], 'species_66': ['calmodulin PP2B complex', 'CaM-PP2B complex', 'calmodulin-PP2B']}
Evaluating 184/1075: BIOMD0000000184.xml

2025-11-20 12:25:02,269 - WARNING - Skipping BIOMD0000000185.xml - no results generated
2025-11-20 12:25:02,277 - WARNING - Skipping BIOMD0000000186.xml - no results generated
2025-11-20 12:25:02,286 - WARNING - Skipping BIOMD0000000187.xml - no results generated
2025-11-20 12:25:02,295 - WARNING - Skipping BIOMD0000000188.xml - no results generated
2025-11-20 12:25:02,303 - WARNING - Skipping BIOMD0000000189.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000184.txt
LLM response:
X (chemical): "Calcium", "Ca2+", "Cytoplasmic Calcium"
Y (chemical): "Calcium in ER", "Endoplasmic Reticulum Calcium", "ER Calcium"
Z (chemical): "IP3", "Inositol Trisphosphate", "D-myo-Inositol 1,4,5-trisphosphate"
Reason: X, Y, and Z are all related to calcium signaling, with X being cytoplasmic calcium, Y being calcium stored in the endoplasmic reticulum, and Z being inositol trisphosphate, a molecule involved in releasing calcium from the ER. All three are chemicals involved in cellular signaling.
Synonyms dict: {'X': ['Calcium', 'Ca2+', 'Cytoplasmic Calcium'], 'Y': ['Calcium in ER', 'Endoplasmic Reticulum Calcium', 'ER Calcium'], 'Z': ['IP3', 'Inositol Trisphosphate', 'D-myo-Inositol 1,4,5-trisphosphate']}
Evaluating 185/1075: BIOMD0000000185.xml
Evaluating 186/1075: BIOMD0000000186.xml
Evaluating 187/1075: BIOMD0000000187.xml
Evaluating 188/1075: BIOMD0000000188.xml
Evaluating 189/1075: BIOMD0000000189.xml
Evaluating 190/1075: BIOMD0000000190.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000190.txt
LLM response:
SAM (chemical): "S-adenosyl-L-methionine", "S-adenosylmethionine", "AdoMet"
A (chemical): "S-adenosylmethioninamine", "decarboxylated S-adenosylmethionine", "dcAdoMet"
P (chemical): "Putrescine", "1,4-diaminobutane", "put"
S (chemical): "Spermine", "N,N'-bis(3-aminopropyl)tetramethylenediamine", "spm"
D (chemical): "Spermidine", "N-(3-aminopropyl)tetramethylenediamine", "spd"
aD (chemical): "N1-Acetylspermidine", "N-acetylspermidine", "AcSpd"
aS (chemical): "N1-Acetylspermine", "N-acetylspermine", "AcSpm"
Met (chemical): "Methionine", "L-methionine", "Met"
ORN (chemical): "L-Ornithine", "L-ornithine", "Orn"
AcCoA (chemical): "Acetyl-CoA", "Acetyl coenzyme A", "AcCoA"
CoA (chemical): "CoA", "Coenzyme A", "CoASH"
Reason: The species are all identified as chemicals because they are all metabolites involved in the polyamine metabolism pathway. The names provided are standardized names or common synonyms for each species, and are ranked by likelihood based on their frequency of use in the literature. The reactions and display names provided in the model also support the identification of these species as chemicals.
Synonyms dict: {'SAM': ['S-adenosyl-L-methionine', 'S-adenosylmethionine', 'AdoMet'], 'A': ['S-adenosylmethioninamine', 'decarboxylated S-adenosylmethionine', 'dcAdoMet'], 'P': ['Putrescine', '1,4-diaminobutane', 'put'], 'S': ['Spermine', "N,N'-bis(3-aminopropyl)tetramethylenediamine", 'spm'], 'D': ['Spermidine', 'N-(3-aminopropyl)tetramethylenediamine', 'spd'], 'aD': ['N1-Acetylspermidine', 'N-acetylspermidine', 'AcSpd'], 'aS': ['N1-Acetylspermine', 'N-acetylspermine', 'AcSpm'], 'Met': ['Methionine', 'L-methionine', 'Met'], 'ORN': ['L-Ornithine', 'L-ornithine', 'Orn'], 'AcCoA': ['Acetyl-CoA', 'Acetyl coenzyme A', 'AcCoA'], 'CoA': ['CoA', 'Coenzyme A', 'CoASH']}
Evaluating 191/1075: BIOMD0000000191.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000191.txt
LLM response:
ARGex (chemical): "Arginine", "L-Arginine", "Arg"
ORN (chemical): "Ornithine", "L-Ornithine", "Orn"
ARGin (chemical): "Arginine", "L-Arginine", "Arg"
Reason: All three species are related to arginine catabolism, and their display names suggest they are different forms or locations of arginine and ornithine, which are amino acids and thus chemicals. ARGex and ARGin are likely referring to extracellular and intracellular arginine, respectively.
Synonyms dict: {'ARGex': ['Arginine', 'L-Arginine', 'Arg'], 'ORN': ['Ornithine', 'L-Ornithine', 'Orn'], 'ARGin': ['Arginine', 'L-Arginine', 'Arg']}
Evaluating 192/1075: BIOMD0000000192.xml

2025-11-20 12:25:10,218 - WARNING - Skipping BIOMD0000000193.xml - no results generated
2025-11-20 12:25:10,221 - WARNING - Skipping BIOMD0000000194.xml - no results generated
2025-11-20 12:25:10,231 - WARNING - Skipping BIOMD0000000195.xml - no results generated
2025-11-20 12:25:10,240 - WARNING - Skipping BIOMD0000000196.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000192.txt
LLM response:
RCC1_RanGDP (complex): "RCC1-RanGDP complex", "RanGDP-RCC1 complex", "RCC1 bound to RanGDP"
GDP (chemical): "guanosine diphosphate", "GDP", "guanosine 5'-diphosphate"
RCC1_RanGTP (complex): "RCC1-RanGTP complex", "RanGTP-RCC1 complex", "RCC1 bound to RanGTP"
GTP (chemical): "guanosine triphosphate", "GTP", "guanosine 5'-triphosphate"

Reason: RCC1_RanGDP and RCC1_RanGTP are classified as complexes because they represent RCC1 bound to either GDP or GTP, indicating a protein-ligand interaction. GDP and GTP are classified as chemicals because they are nucleotides involved in the regulation of the Ran GTPase cycle.
Synonyms dict: {'RCC1_RanGDP': ['RCC1-RanGDP complex', 'RanGDP-RCC1 complex', 'RCC1 bound to RanGDP'], 'GDP': ['guanosine diphosphate', 'GDP', "guanosine 5'-diphosphate"], 'RCC1_RanGTP': ['RCC1-RanGTP complex', 'RanGTP-RCC1 complex', 'RCC1 bound to RanGTP'], 'GTP': ['guanosine triphosphate', 'GTP', "guanosine 5'-triphosphate"]}
Evaluating 193/1075: BIOMD0000000193.xml
Evaluating 194/1075: BIOMD0000000194.xml
Evaluating 195/1075: BIOMD0000000195.xml
Evaluating 196/1075: BIOMD0000000196.xml
Evaluating 197/1075: BIOMD0000000197.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000197.txt
LLM response:
x1 (chemical): "BSP", "Bisphenol A", "4,4'-dihydroxy-2,2-diphenylpropane"
x2 (chemical): "bound BSP", "BSP basolateral bound", "Bisphenol A bound"
x3 (chemical): "intracellular free BSP", "free BSP intracellular", "Bisphenol A free"
x4 (chemical): "bound intracellular BSP", "BSP intracellular bound", "Bisphenol A intracellular bound"
x5 (chemical): "apical BSP", "BSP apical", "Bisphenol A apical"
BSP_tot (chemical): "total BSP", "BSP total", "Bisphenol A total"
BSP_cell (chemical): "intracellular BSP total", "BSP cell", "Bisphenol A intracellular"
Reason: All species are annotated as chemicals because they are related to BSP (Bisphenol A), a chemical compound, and are involved in reactions that describe its transport and binding in different cellular compartments. The names provided are based on the display names and the context of the model, with the most likely standardized names and synonyms for each species.
Synonyms dict: {'x1': ['BSP', 'Bisphenol A', "4,4'-dihydroxy-2,2-diphenylpropane"], 'x2': ['bound BSP', 'BSP basolateral bound', 'Bisphenol A bound'], 'x3': ['intracellular free BSP', 'free BSP intracellular', 'Bisphenol A free'], 'x4': ['bound intracellular BSP', 'BSP intracellular bound', 'Bisphenol A intracellular bound'], 'x5': ['apical BSP', 'BSP apical', 'Bisphenol A apical'], 'BSP_tot': ['total BSP', 'BSP total', 'Bisphenol A total'], 'BSP_cell': ['intracellular BSP total', 'BSP cell', 'Bisphenol A intracellular']}
Evaluating 198/1075: BIOMD0000000198.xml

2025-11-20 12:25:18,498 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000198.txt
LLM response:
NO (chemical): "nitric oxide", "nitrogen monoxide", "NO"
NO_sGCfast (complex): "nitric oxide-soluble guanylate cyclase complex", "NO-sGC fast complex", "nitrosyl-sGC fast"
NO_sGCfast_6coord (complex): "6-coordinate nitrosyl-sGC fast complex", "nitric oxide-sGC fast 6-coordinate complex", "NO-sGC fast 6-coordinate"
NO_sGCfast_5coord (complex): "5-coordinate nitrosyl-sGC fast complex", "nitric oxide-sGC fast 5-coordinate complex", "NO-sGC fast 5-coordinate"
NO_sGCslow (complex): "nitric oxide-soluble guanylate cyclase slow complex", "NO-sGC slow complex", "nitrosyl-sGC slow"
NO_sGCslow_6coord (complex): "6-coordinate nitrosyl-sGC slow complex", "nitric oxide-sGC slow 6-coordinate complex", "NO-sGC slow 6-coordinate"
NO_sGCslow_6coord_NO_int (complex): "6-coordinate nitrosyl-sGC slow complex with NO interaction", "nitric oxide-sGC slow 6-coordinate complex with NO", "NO-sGC slow 6-coordinate NO-bound"
NO_sGCslow_5coord (complex): "5-coordinate nitrosyl-sGC slow complex", "nitric oxide-sGC slow 5-coordinate complex", "NO-sGC slow 5-coordinate"
NO_sGC_5coord_tot (complex): "total 5-coordinate nitrosyl-sGC complex", "total nitric oxide-sGC 5-coordinate complex", "total NO-sGC 5-coordinate"
sGC_inact_tot (protein): "total inactive soluble guanylate cyclase", "total inactive sGC", "inactive sGC total"
sGCfast (protein): "soluble guanylate cyclase fast", "sGC fast", "fast soluble guanylate cyclase"
sGCslow (protein): "soluble guanylate cyclase slow", "sGC slow", "slow soluble guanylate cyclase"

Reason: The species are identified based on the context of the model, which describes the activation of soluble guanylate cyclase by nitric oxide. NO is a chemical species, while the other species are complexes formed between NO and soluble guanylate cyclase (sGC) in different states (fast or slow, 6-coordinate or 5-coordinate). sGCfast and sGCslow are protein species, representing the fast and slow forms of soluble guanylate cyclase. The entity types are determined based on the descriptions in the model and the standard names or common synonyms are provided for each species.
Synonyms dict: {'NO': ['nitric oxide', 'nitrogen monoxide', 'NO'], 'NO_sGCfast': ['nitric oxide-soluble guanylate cyclase complex', 'NO-sGC fast complex', 'nitrosyl-sGC fast'], 'NO_sGCfast_6coord': ['6-coordinate nitrosyl-sGC fast complex', 'nitric oxide-sGC fast 6-coordinate complex', 'NO-sGC fast 6-coordinate'], 'NO_sGCfast_5coord': ['5-coordinate nitrosyl-sGC fast complex', 'nitric oxide-sGC fast 5-coordinate complex', 'NO-sGC fast 5-coordinate'], 'NO_sGCslow': ['nitric oxide-soluble guanylate cyclase slow complex', 'NO-sGC slow complex', 'nitrosyl-sGC slow'], 'NO_sGCslow_6coord': ['6-coordinate nitrosyl-sGC slow complex', 'nitric oxide-sGC slow 6-coordinate complex', 'NO-sGC slow 6-coordinate'], 'NO_sGCslow_6coord_NO_int': ['6-coordinate nitrosyl-sGC slow complex with NO interaction', 'nitric oxide-sGC slow 6-coordinate complex with NO', 'NO-sGC slow 6-coordinate NO-bound'], 'NO_sGCslow_5coord': ['5-coordinate nitrosyl-sGC slow complex', 'nitric oxide-sGC slow 5-coordinate complex', 'NO-sGC slow 5-coordinate'], 'NO_sGC_5coord_tot': ['total 5-coordinate nitrosyl-sGC complex', 'total nitric oxide-sGC 5-coordinate complex', 'total NO-sGC 5-coordinate'], 'sGC_inact_tot': ['total inactive soluble guanylate cyclase', 'total inactive sGC', 'inactive sGC total'], 'sGCfast': ['soluble guanylate cyclase fast', 'sGC fast', 'fast soluble guanylate cyclase'], 'sGCslow': ['soluble guanylate cyclase slow', 'sGC slow', 'slow soluble guanylate cyclase']}
Evaluating 199/1075: BIOMD0000000199.xml

2025-11-20 12:25:23,279 - WARNING - Skipping BIOMD0000000200.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000199.txt
LLM response:
FeIII (chemical): "ferric ion", "iron(3+)", "Fe3+"
FeII (chemical): "ferrous ion", "iron(2+)", "Fe2+"
FeII_O2 (chemical): "oxyferrous", "iron(2+) oxygen", "Fe2+-O2"
FeIII_star (chemical): "ferric ion star", "iron(3+) radical", "Fe3+*"
FeII_star (chemical): "ferrous ion star", "iron(2+) radical", "Fe2+*"
FeII_star_O2 (chemical): "oxyferrous star", "iron(2+) oxygen radical", "Fe2+-O2*"
FeIII_NO (chemical): "ferric ion nitrosyl", "iron(3+) nitric oxide", "Fe3+-NO"
FeII_NO (chemical): "ferrous ion nitrosyl", "iron(2+) nitric oxide", "Fe2+-NO"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP reduced", "NADPH oxidase substrate"
O2 (chemical): "oxygen", "dioxygen", "O2 molecule"
citrulline (chemical): "L-citrulline", "cit", "2-amino-5-ureidovaleric acid"
NO3 (chemical): "nitrate", "nitrate ion", "NO3-"
NO (chemical): "nitric oxide", "nitrogen monoxide", "NO radical"
NADPplus (chemical): "nicotinamide adenine dinucleotide phosphate oxidized", "NADP+", "NADP oxidized"
FeIII_t (chemical): "ferric ion terminal", "iron(3+) terminal", "Fe3+ term"
Reason: The species are annotated based on their display names and reaction equations. The "_star" and "_NO" suffixes indicate radical or nitrosyl species, respectively. The "O2" suffix indicates an oxygen-bound species. NADPH and NADPplus are electron carriers, while citrulline is an amino acid. NO3 and NO are inorganic nitrogen compounds. FeIII, FeII, and their derivatives are iron ions in different oxidation states.
Synonyms dict: {'FeIII': ['ferric ion', 'iron(3+)', 'Fe3+'], 'FeII': ['ferrous ion', 'iron(2+)', 'Fe2+'], 'FeII_O2': ['oxyferrous', 'iron(2+) oxygen', 'Fe2+-O2'], 'FeIII_star': ['ferric ion star', 'iron(3+) radical', 'Fe3+*'], 'FeII_star': ['ferrous ion star', 'iron(2+) radical', 'Fe2+*'], 'FeII_star_O2': ['oxyferrous star', 'iron(2+) oxygen radical', 'Fe2+-O2*'], 'FeIII_NO': ['ferric ion nitrosyl', 'iron(3+) nitric oxide', 'Fe3+-NO'], 'FeII_NO': ['ferrous ion nitrosyl', 'iron(2+) nitric oxide', 'Fe2+-NO'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADP reduced', 'NADPH oxidase substrate'], 'O2': ['oxygen', 'dioxygen', 'O2 molecule'], 'citrulline': ['L-citrulline', 'cit', '2-amino-5-ureidovaleric acid'], 'NO3': ['nitrate', 'nitrate ion', 'NO3-'], 'NO': ['nitric oxide', 'nitrogen monoxide', 'NO radical'], 'NADPplus': ['nicotinamide adenine dinucleotide phosphate oxidized', 'NADP+', 'NADP oxidized'], 'FeIII_t': ['ferric ion terminal', 'iron(3+) terminal', 'Fe3+ term']}
Evaluating 200/1075: BIOMD0000000200.xml
Evaluating 201/1075: BIOMD0000000201.xml

2025-11-20 12:25:24,567 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:25:24,569 - WARNING - Skipping BIOMD0000000201.xml - no results generated

Evaluating 202/1075: BIOMD0000000202.xml

2025-11-20 12:25:26,663 - WARNING - Skipping BIOMD0000000203.xml - no results generated
2025-11-20 12:25:26,668 - WARNING - Skipping BIOMD0000000204.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000202.txt
LLM response:
Ca_Cyt (chemical): "calcium ion", "Ca2+", "calcium"
IP3_Cyt (chemical): "inositol trisphosphate", "IP3", "myo-inositol 1,4,5-trisphosphate"
Ca_ER (chemical): "calcium ion", "Ca2+", "endoplasmic reticulum calcium"
Reason: The species are annotated based on their names and the context of the model "ChenXF2008_CICR", which likely refers to a calcium-induced calcium release model. Ca_Cyt and Ca_ER are likely calcium ions in different cellular compartments (cytosol and endoplasmic reticulum, respectively), and IP3_Cyt is likely inositol trisphosphate, a chemical involved in calcium signaling.
Synonyms dict: {'Ca_Cyt': ['calcium ion', 'Ca2+', 'calcium'], 'IP3_Cyt': ['inositol trisphosphate', 'IP3', 'myo-inositol 1,4,5-trisphosphate'], 'Ca_ER': ['calcium ion', 'Ca2+', 'endoplasmic reticulum calcium']}
Evaluating 203/1075: BIOMD0000000203.xml
Evaluating 204/1075: BIOMD0000000204.xml
Evaluating 205/1075: BIOMD0000000205.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000205.txt
LLM response:
species_17 (chemical): "Ras GDP", "Ras guanosine diphosphate", "Ras-GDP"
species_18 (complex): "EGF-pEGFR-2-pShc-Grb2-SOS-RasGDP", "EGF receptor complex", "EGFR-SOS complex"
species_19 (chemical): "Ras GTP", "Ras guanosine triphosphate", "Ras-GTP"
species_22 (complex): "EGF-pEGFR-2-Grb2-SOS-RasGDP", "EGF receptor complex", "EGFR-SOS complex"
species_24 (complex): "Raf-RasGTP", "Raf kinase complex", "Ras-Raf complex"
species_55 (chemical): "PIP2", "Phosphatidylinositol 4,5-bisphosphate", "PtdIns(4,5)P2"
species_56 (complex): "pPI3K-PIP2", "Phosphatidylinositol 3-kinase complex", "PI3K-PIP2 complex"
species_57 (chemical): "PIP3", "Phosphatidylinositol 3,4,5-trisphosphate", "PtdIns(3,4,5)P3"
species_59 (complex): "Akt-PIP3", "Protein kinase B complex", "Akt-PIP3 complex"
species_61 (complex): "Akt-PIP3-PDK1", "Protein kinase B complex", "Akt-PDK1 complex"
species_62 (complex): "pAkt-PIP3", "Phosphorylated protein kinase B complex", "pAkt-PIP3 complex"
species_65 (complex): "pAkt-PIP3-Takt", "Phosphorylated protein kinase B complex", "pAkt-Takt complex"
species_66 (complex): "pRaf-pAkt-PIP3", "Phosphorylated Raf kinase complex", "pRaf-pAkt complex"
species_72 (complex): "pPTEN-PIP3", "Phosphatase and tensin homolog complex", "PTEN-PIP3 complex"
species_74 (complex): "PIP3-RacGEF", "Phosphatidylinositol 3,4,5-trisphosphate complex", "PIP3-RacGEF complex"
species_75 (chemical): "RacGDP", "Ras-related C3 botulinum toxin substrate 1 GDP", "Rac-GDP"
species_76 (complex): "PIP3-RacGEF-RacGDP", "Phosphatidylinositol 3,4,5-trisphosphate complex", "PIP3-RacGEF-RacGDP complex"
species_77 (chemical): "RacGTP", "Ras-related C3 botulinum toxin substrate 1 GTP", "Rac-GTP"
species_79 (complex): "RhoGDI-RacGDP", "Rho GDP-dissociation inhibitor complex", "RhoGDI-RacGDP complex"
species_81 (complex): "RacGTP-RacGAP", "Ras-related C3 botulinum toxin substrate 1 complex", "RacGTP-RacGAP complex"
species_86 (chemical): "RhoGTP", "Ras homolog gene family member GTP", "Rho-GTP"
species_88 (complex): "EGF-pEGFR-2-RasGAP-RasGTP", "EGF receptor complex", "EGFR-RasGAP complex"
species_148 (complex): "EGF-pEGFR-2-pShc-Grb2-MEKK1abcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_149 (complex): "EGF-pEGFR-2-pShc-Grb2-MEKK1abMEKcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_150 (complex): "EGF-pEGFR-2-pShc-Grb2-MEKK1abpMEKcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_151 (complex): "EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_152 (complex): "EGF-pEGFR-2-Grb2-MEKK1abcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_153 (complex): "EGF-pEGFR-2-Grb2-MEKK1abMEKcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_154 (complex): "EGF-pEGFR-2-Grb2-MEKK1abpMEKcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_155 (complex): "EGF-pEGFR-2-Grb2-MEKK1abppMEKcdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_156 (complex): "EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcERKdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_157 (complex): "EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcpERKdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_158 (complex): "EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcppERKdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_159 (complex): "EGF-pEGFR-2-Grb2-MEKK1abppMEKcERKdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_160 (complex): "EGF-pEGFR-2-Grb2-MEKK1abppMEKcpERKdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"
species_161 (complex): "EGF-pEGFR-2-Grb2-MEKK1abppMEKcppERKdefRasGTP", "EGF receptor complex", "EGFR-MEKK1 complex"

Reason: The model is based on the EGF receptor endocytosis pathway, which involves various protein-protein interactions and signaling cascades. The species are classified based on their roles in the pathway, with chemicals being small molecules like GDP, GTP, PIP2, and PIP3, and complexes being protein complexes involved in signaling. The entity types are determined by the names and reactions in the model, with proteins and complexes being the most common types. The standardized names and synonyms are based on common names used in the literature and databases.
Synonyms dict: {'species_17': ['Ras GDP', 'Ras guanosine diphosphate', 'Ras-GDP'], 'species_18': ['EGF-pEGFR-2-pShc-Grb2-SOS-RasGDP', 'EGF receptor complex', 'EGFR-SOS complex'], 'species_19': ['Ras GTP', 'Ras guanosine triphosphate', 'Ras-GTP'], 'species_22': ['EGF-pEGFR-2-Grb2-SOS-RasGDP', 'EGF receptor complex', 'EGFR-SOS complex'], 'species_24': ['Raf-RasGTP', 'Raf kinase complex', 'Ras-Raf complex'], 'species_55': ['PIP2', 'Phosphatidylinositol 4,5-bisphosphate', 'PtdIns(4,5)P2'], 'species_56': ['pPI3K-PIP2', 'Phosphatidylinositol 3-kinase complex', 'PI3K-PIP2 complex'], 'species_57': ['PIP3', 'Phosphatidylinositol 3,4,5-trisphosphate', 'PtdIns(3,4,5)P3'], 'species_59': ['Akt-PIP3', 'Protein kinase B complex', 'Akt-PIP3 complex'], 'species_61': ['Akt-PIP3-PDK1', 'Protein kinase B complex', 'Akt-PDK1 complex'], 'species_62': ['pAkt-PIP3', 'Phosphorylated protein kinase B complex', 'pAkt-PIP3 complex'], 'species_65': ['pAkt-PIP3-Takt', 'Phosphorylated protein kinase B complex', 'pAkt-Takt complex'], 'species_66': ['pRaf-pAkt-PIP3', 'Phosphorylated Raf kinase complex', 'pRaf-pAkt complex'], 'species_72': ['pPTEN-PIP3', 'Phosphatase and tensin homolog complex', 'PTEN-PIP3 complex'], 'species_74': ['PIP3-RacGEF', 'Phosphatidylinositol 3,4,5-trisphosphate complex', 'PIP3-RacGEF complex'], 'species_75': ['RacGDP', 'Ras-related C3 botulinum toxin substrate 1 GDP', 'Rac-GDP'], 'species_76': ['PIP3-RacGEF-RacGDP', 'Phosphatidylinositol 3,4,5-trisphosphate complex', 'PIP3-RacGEF-RacGDP complex'], 'species_77': ['RacGTP', 'Ras-related C3 botulinum toxin substrate 1 GTP', 'Rac-GTP'], 'species_79': ['RhoGDI-RacGDP', 'Rho GDP-dissociation inhibitor complex', 'RhoGDI-RacGDP complex'], 'species_81': ['RacGTP-RacGAP', 'Ras-related C3 botulinum toxin substrate 1 complex', 'RacGTP-RacGAP complex'], 'species_86': ['RhoGTP', 'Ras homolog gene family member GTP', 'Rho-GTP'], 'species_88': ['EGF-pEGFR-2-RasGAP-RasGTP', 'EGF receptor complex', 'EGFR-RasGAP complex'], 'species_148': ['EGF-pEGFR-2-pShc-Grb2-MEKK1abcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_149': ['EGF-pEGFR-2-pShc-Grb2-MEKK1abMEKcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_150': ['EGF-pEGFR-2-pShc-Grb2-MEKK1abpMEKcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_151': ['EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_152': ['EGF-pEGFR-2-Grb2-MEKK1abcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_153': ['EGF-pEGFR-2-Grb2-MEKK1abMEKcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_154': ['EGF-pEGFR-2-Grb2-MEKK1abpMEKcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_155': ['EGF-pEGFR-2-Grb2-MEKK1abppMEKcdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_156': ['EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcERKdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_157': ['EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcpERKdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_158': ['EGF-pEGFR-2-pShc-Grb2-MEKK1abppMEKcppERKdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_159': ['EGF-pEGFR-2-Grb2-MEKK1abppMEKcERKdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_160': ['EGF-pEGFR-2-Grb2-MEKK1abppMEKcpERKdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex'], 'species_161': ['EGF-pEGFR-2-Grb2-MEKK1abppMEKcppERKdefRasGTP', 'EGF receptor complex', 'EGFR-MEKK1 complex']}
Evaluating 206/1075: BIOMD0000000206.xml

2025-11-20 12:25:45,261 - WARNING - Skipping BIOMD0000000207.xml - no results generated
2025-11-20 12:25:45,265 - WARNING - Skipping BIOMD0000000208.xml - no results generated
2025-11-20 12:25:45,273 - WARNING - Skipping BIOMD0000000209.xml - no results generated
2025-11-20 12:25:45,280 - WARNING - Skipping BIOMD0000000210.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000206.txt
LLM response:
s1 (chemical): "Glucose", "D-Glucose", "Blood sugar"
at (chemical): "ATP", "Adenosine triphosphate", "Adenine nucleotide"
s2 (chemical): "Fructose-1,6-bisphosphate", "F16P", "Fructose 1,6-diphosphate"
s3 (chemical): "Glyceraldehyde-3-phosphate", "Triosephosphate", "3-Phosphoglyceraldehyde"
na (chemical): "NAD", "Nicotinamide adenine dinucleotide", "NAD+"
s4 (chemical): "3-Phosphoglycerate", "3-PG", "Glycerate 3-phosphate"
s5 (chemical): "Pyruvate", "Pyruvic acid", "2-Oxopropanoic acid"
s6 (chemical): "Acetaldehyde", "Ethanal", "Acetic aldehyde"
s6o (chemical): "Extracellular acetaldehyde", "External acetaldehyde", "Acetaldehyde (extracellular)"
Reason: The model is based on glycolytic oscillations, which is a process involving the breakdown of glucose to pyruvate, producing ATP and NADH in the process. The species are all intermediates or products of this process, and their display names match known chemical compounds involved in glycolysis. s6o is considered a chemical as it is a form of acetaldehyde, but specified as extracellular.
Synonyms dict: {'s1': ['Glucose', 'D-Glucose', 'Blood sugar'], 'at': ['ATP', 'Adenosine triphosphate', 'Adenine nucleotide'], 's2': ['Fructose-1,6-bisphosphate', 'F16P', 'Fructose 1,6-diphosphate'], 's3': ['Glyceraldehyde-3-phosphate', 'Triosephosphate', '3-Phosphoglyceraldehyde'], 'na': ['NAD', 'Nicotinamide adenine dinucleotide', 'NAD+'], 's4': ['3-Phosphoglycerate', '3-PG', 'Glycerate 3-phosphate'], 's5': ['Pyruvate', 'Pyruvic acid', '2-Oxopropanoic acid'], 's6': ['Acetaldehyde', 'Ethanal', 'Acetic aldehyde'], 's6o': ['Extracellular acetaldehyde', 'External acetaldehyde', 'Acetaldehyde (extracellular)']}
Evaluating 207/1075: BIOMD0000000207.xml
Evaluating 208/1075: BIOMD0000000208.xml
Evaluating 209/1075: BIOMD0000000209.xml
Evaluating 210/1075: BIOMD0000000210.xml
Evaluating 211/1075: BIOMD0000000211.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000211.txt
LLM response:
species_1 (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
species_2 (chemical): "ADP", "adenosine diphosphate", "5'-adenylic acid"
species_3 (chemical): "ATP", "adenosine triphosphate", "5'-adenylyl imidodiphosphate"
species_4 (chemical): "phosphoenolpyruvate", "PEP", "2-phosphoenolpyruvate"
species_5 (chemical): "2-phosphoglycerate", "2-PG", "2-phosphoglyceric acid"
species_6 (chemical): "AMP", "adenosine monophosphate", "5'-adenylic acid"
species_7 (chemical): "3-phosphoglycerate", "3-PG", "3-phosphoglyceric acid"
species_8 (chemical): "dihydroxyacetonephosphate", "DHAP", "1,3-dihydroxyacetone phosphate"
species_9 (chemical): "glycerol-3-phosphate", "G3P", "sn-glycerol 3-phosphate"
species_10 (chemical): "glucose", "D-glucose", "blood sugar"
species_11 (chemical): "ATP", "adenosine triphosphate", "5'-adenylyl imidodiphosphate"
species_12 (chemical): "ADP", "adenosine diphosphate", "5'-adenylic acid"
species_13 (chemical): "AMP", "adenosine monophosphate", "5'-adenylic acid"
species_14 (chemical): "glucose-6-phosphate", "G6P", "D-glucose 6-phosphate"
species_15 (chemical): "fructose-6-phosphate", "F6P", "D-fructose 6-phosphate"
species_16 (chemical): "fructose-1,6-bisphosphate", "F1,6BP", "D-fructose 1,6-bisphosphate"
species_17 (chemical): "dihydroxyacetonephosphate", "DHAP", "1,3-dihydroxyacetone phosphate"
species_18 (chemical): "glyceraldehyde-3-phosphate", "G3P", "D-glyceraldehyde 3-phosphate"
species_19 (chemical): "NAD", "nicotinamide adenine dinucleotide", "NAD+"
species_20 (chemical): "NADH", "nicotinamide adenine dinucleotide reduced", "NADH"
species_21 (chemical): "1,3-bisphosphoglycerate", "1,3BPG", "1,3-bisphosphoglyceric acid"
species_22 (chemical): "glycerol-3-phosphate", "G3P", "sn-glycerol 3-phosphate"
species_23 (chemical): "3-phosphoglycerate", "3-PG", "3-phosphoglyceric acid"
species_24 (chemical): "glycerol", "1,2,3-propanetriol", "glycerin"
species_25 (chemical): "glucose", "D-glucose", "blood sugar"
species_26 (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
species_27 (chemical): "glycerol", "1,2,3-propanetriol", "glycerin"
Reason: The entity types were determined based on the display names and the context of the glycolysis model. Most species are chemicals, such as metabolites (e.g., glucose, pyruvate) and cofactors (e.g., ATP, NAD). The model does not include genes or proteins as species, but rather focuses on the metabolic reactions and their corresponding chemical species. The standardized names and synonyms were chosen based on common usage in biochemistry and the likelihood of being correct.
Synonyms dict: {'species_1': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'species_2': ['ADP', 'adenosine diphosphate', "5'-adenylic acid"], 'species_3': ['ATP', 'adenosine triphosphate', "5'-adenylyl imidodiphosphate"], 'species_4': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvate'], 'species_5': ['2-phosphoglycerate', '2-PG', '2-phosphoglyceric acid'], 'species_6': ['AMP', 'adenosine monophosphate', "5'-adenylic acid"], 'species_7': ['3-phosphoglycerate', '3-PG', '3-phosphoglyceric acid'], 'species_8': ['dihydroxyacetonephosphate', 'DHAP', '1,3-dihydroxyacetone phosphate'], 'species_9': ['glycerol-3-phosphate', 'G3P', 'sn-glycerol 3-phosphate'], 'species_10': ['glucose', 'D-glucose', 'blood sugar'], 'species_11': ['ATP', 'adenosine triphosphate', "5'-adenylyl imidodiphosphate"], 'species_12': ['ADP', 'adenosine diphosphate', "5'-adenylic acid"], 'species_13': ['AMP', 'adenosine monophosphate', "5'-adenylic acid"], 'species_14': ['glucose-6-phosphate', 'G6P', 'D-glucose 6-phosphate'], 'species_15': ['fructose-6-phosphate', 'F6P', 'D-fructose 6-phosphate'], 'species_16': ['fructose-1,6-bisphosphate', 'F1,6BP', 'D-fructose 1,6-bisphosphate'], 'species_17': ['dihydroxyacetonephosphate', 'DHAP', '1,3-dihydroxyacetone phosphate'], 'species_18': ['glyceraldehyde-3-phosphate', 'G3P', 'D-glyceraldehyde 3-phosphate'], 'species_19': ['NAD', 'nicotinamide adenine dinucleotide', 'NAD+'], 'species_20': ['NADH', 'nicotinamide adenine dinucleotide reduced', 'NADH'], 'species_21': ['1,3-bisphosphoglycerate', '1,3BPG', '1,3-bisphosphoglyceric acid'], 'species_22': ['glycerol-3-phosphate', 'G3P', 'sn-glycerol 3-phosphate'], 'species_23': ['3-phosphoglycerate', '3-PG', '3-phosphoglyceric acid'], 'species_24': ['glycerol', '1,2,3-propanetriol', 'glycerin'], 'species_25': ['glucose', 'D-glucose', 'blood sugar'], 'species_26': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'species_27': ['glycerol', '1,2,3-propanetriol', 'glycerin']}
Evaluating 212/1075: BIOMD0000000212.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000212.txt
LLM response:
Asp (chemical): "aspartate", "aspartic acid", "L-aspartate"
Lys (chemical): "lysine", "L-lysine", "α-linolenic acid"
AdoMet (chemical): "S-adenosylmethionine", "SAMe", "AdoMet"
AspP (chemical): "aspartyl phosphate", "aspartate phosphate", "L-aspartyl phosphate"
Thr (chemical): "threonine", "L-threonine", "α-amino-β-hydroxyvaleric acid"
ASA (chemical): "aspartate semialdehyde", "β-aspartyl semialdehyde", "3-aminopropanal"
Hser (chemical): "homoserine", "L-homoserine", "α-amino-γ-hydroxybutyric acid"
PHser (chemical): "phosphohomoserine", "O-phosphohomoserine", "L-phosphohomoserine"
Phosphate (chemical): "inorganic phosphate", "orthophosphate", "phosphoric acid"
Cys (chemical): "cysteine", "L-cysteine", "α-amino-β-mercaptopropionic acid"
Cysta (chemical): "cystathionine", "L-cystathionine", "S-β-amino-β-carboxyethylhomocysteine"
Ile (chemical): "isoleucine", "L-isoleucine", "α-amino-β-methylvaleric acid"
Val (chemical): "valine", "L-valine", "α-amino-isovaleric acid"
ThrTRNA (complex): "threonine tRNA", "tRNA-Thr", "Thr-tRNA"
IleTRNA (complex): "isoleucine tRNA", "tRNA-Ile", "Ile-tRNA"
Sacc (chemical): "saccharopine", "L-saccharopine", "α-amino-ε-N-(glutar-2-yl)caproic acid"
Gly (chemical): "glycine", "L-glycine", "aminoacetic acid"
Reason: The species in the model are mostly amino acids and their derivatives, which are chemical entities. The tRNA species (e.g. ThrTRNA, IleTRNA) are complexes of RNA and amino acids, and are classified as such. The model does not include any genes or proteins as species, so none are classified as such. The names and synonyms provided are based on common biochemical nomenclature and are ranked by likelihood based on their frequency of use in the literature.
Synonyms dict: {'Asp': ['aspartate', 'aspartic acid', 'L-aspartate'], 'Lys': ['lysine', 'L-lysine', 'α-linolenic acid'], 'AdoMet': ['S-adenosylmethionine', 'SAMe', 'AdoMet'], 'AspP': ['aspartyl phosphate', 'aspartate phosphate', 'L-aspartyl phosphate'], 'Thr': ['threonine', 'L-threonine', 'α-amino-β-hydroxyvaleric acid'], 'ASA': ['aspartate semialdehyde', 'β-aspartyl semialdehyde', '3-aminopropanal'], 'Hser': ['homoserine', 'L-homoserine', 'α-amino-γ-hydroxybutyric acid'], 'PHser': ['phosphohomoserine', 'O-phosphohomoserine', 'L-phosphohomoserine'], 'Phosphate': ['inorganic phosphate', 'orthophosphate', 'phosphoric acid'], 'Cys': ['cysteine', 'L-cysteine', 'α-amino-β-mercaptopropionic acid'], 'Cysta': ['cystathionine', 'L-cystathionine', 'S-β-amino-β-carboxyethylhomocysteine'], 'Ile': ['isoleucine', 'L-isoleucine', 'α-amino-β-methylvaleric acid'], 'Val': ['valine', 'L-valine', 'α-amino-isovaleric acid'], 'ThrTRNA': ['threonine tRNA', 'tRNA-Thr', 'Thr-tRNA'], 'IleTRNA': ['isoleucine tRNA', 'tRNA-Ile', 'Ile-tRNA'], 'Sacc': ['saccharopine', 'L-saccharopine', 'α-amino-ε-N-(glutar-2-yl)caproic acid'], 'Gly': ['glycine', 'L-glycine', 'aminoacetic acid']}
Evaluating 213/1075: BIOMD0000000213.xml

2025-11-20 12:26:05,810 - WARNING - Skipping BIOMD0000000214.xml - no results generated
2025-11-20 12:26:05,816 - WARNING - Skipping BIOMD0000000215.xml - no results generated
2025-11-20 12:26:05,821 - WARNING - Skipping BIOMD0000000216.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000213.txt
LLM response:
_5mTHF (chemical): "5-methyltetrahydrofolate", "5-methyl-THF", "L-methylfolate"
THF (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
DHF (chemical): "dihydrofolate", "DHF", "7,8-dihydrofolate"
_5_10_CH2THF (chemical): "5,10-methylenetetrahydrofolate", "5,10-CH2-THF", "Methylenetetrahydrofolate"
_5_10_CHTHF (chemical): "5,10-methenyltetrahydrofolate", "5,10-CH-THF", "Methenyltetrahydrofolate"
_10fTHF (chemical): "10-formyltetrahydrofolate", "10-formyl-THF", "Formyltetrahydrofolate"
Ser (chemical): "serine", "L-serine", "Ser"
Gly (chemical): "glycine", "L-glycine", "Gly"
dUMP (chemical): "deoxyuridine monophosphate", "dUMP", "deoxyuridylate"
GAR (chemical): "glycinamide ribonucleotide", "GAR", "5'-phosphoribosylglycinamide"
AICAR (chemical): "5-amino-4-imidazolecarboxamide ribonucleotide", "AICAR", "ZMP"
HCOOH (chemical): "formic acid", "HCOOH", "methanoic acid"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
Hcy (chemical): "homocysteine", "L-homocysteine", "Hcy"

Reason: The species are identified as chemicals based on their involvement in the folate cycle, a biochemical pathway. The names provided are standardized and commonly used in the field of biochemistry. The reactions and notes from the model provide context for the species' roles in the pathway, allowing for accurate identification of their entity types and synonyms.
Synonyms dict: {'_5mTHF': ['5-methyltetrahydrofolate', '5-methyl-THF', 'L-methylfolate'], 'THF': ['tetrahydrofolate', 'THF', 'tetrahydrofolic acid'], 'DHF': ['dihydrofolate', 'DHF', '7,8-dihydrofolate'], '_5_10_CH2THF': ['5,10-methylenetetrahydrofolate', '5,10-CH2-THF', 'Methylenetetrahydrofolate'], '_5_10_CHTHF': ['5,10-methenyltetrahydrofolate', '5,10-CH-THF', 'Methenyltetrahydrofolate'], '_10fTHF': ['10-formyltetrahydrofolate', '10-formyl-THF', 'Formyltetrahydrofolate'], 'Ser': ['serine', 'L-serine', 'Ser'], 'Gly': ['glycine', 'L-glycine', 'Gly'], 'dUMP': ['deoxyuridine monophosphate', 'dUMP', 'deoxyuridylate'], 'GAR': ['glycinamide ribonucleotide', 'GAR', "5'-phosphoribosylglycinamide"], 'AICAR': ['5-amino-4-imidazolecarboxamide ribonucleotide', 'AICAR', 'ZMP'], 'HCOOH': ['formic acid', 'HCOOH', 'methanoic acid'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'Hcy': ['homocysteine', 'L-homocysteine', 'Hcy']}
Evaluating 214/1075: BIOMD0000000214.xml
Evaluating 215/1075: BIOMD0000000215.xml
Evaluating 216/1075: BIOMD0000000216.xml
Evaluating 217/1075: BIOMD0000000217.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000217.txt
LLM response:
UTP (chemical): "uridine triphosphate", "UTP", "uridine 5'-triphosphate"
PPi (chemical): "pyrophosphate", "diphosphate", "inorganic pyrophosphate"
GLN (chemical): "glutamine", "L-glutamine", "Gln"
UMP (chemical): "uridine monophosphate", "UMP", "uridine 5'-monophosphate"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
NH4 (chemical): "ammonium", "ammonium ion", "NH4+"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced nicotinamide adenine dinucleotide phosphate"
GLU (chemical): "glutamate", "L-glutamate", "Glu"
NADP (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP", "nicotinamide adenine dinucleotide phosphate (oxidized)"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
P_i (chemical): "inorganic phosphate", "phosphate", "Pi"

Reason: All species are identified as chemicals because they are all molecules involved in the metabolic pathways described in the model, specifically the ammonium assimilation pathway in Escherichia coli. The names provided are standardized or common synonyms for each species, based on their chemical structures and functions. No genes or proteins are listed as species in this model, which is focused on metabolic reactions and chemical transformations.
Synonyms dict: {'UTP': ['uridine triphosphate', 'UTP', "uridine 5'-triphosphate"], 'PPi': ['pyrophosphate', 'diphosphate', 'inorganic pyrophosphate'], 'GLN': ['glutamine', 'L-glutamine', 'Gln'], 'UMP': ['uridine monophosphate', 'UMP', "uridine 5'-monophosphate"], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'NH4': ['ammonium', 'ammonium ion', 'NH4+'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced nicotinamide adenine dinucleotide phosphate'], 'GLU': ['glutamate', 'L-glutamate', 'Glu'], 'NADP': ['nicotinamide adenine dinucleotide phosphate', 'NADP', 'nicotinamide adenine dinucleotide phosphate (oxidized)'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'P_i': ['inorganic phosphate', 'phosphate', 'Pi']}
Evaluating 218/1075: BIOMD0000000218.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000218.txt
LLM response:
aca (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
oaa (chemical): "oxaloacetate", "oxaloacetic acid", "OAA"
coa (chemical): "coenzyme A", "CoA", "Coenzyme A"
cit (chemical): "citrate", "citric acid", "CIT"
icit (chemical): "isocitrate", "isocitric acid", "ICIT"
akg (chemical): "alpha-ketoglutarate", "2-oxoglutarate", "AKG"
ssa (chemical): "succinyl-CoA", "succinyl coenzyme A", "SSA"
suc (chemical): "succinate", "succinic acid", "SUC"
sca (chemical): "succinyl-CoA", "succinyl coenzyme A", "SCA"
fa (chemical): "fumarate", "fumaric acid", "FUM"
mal (chemical): "malate", "malic acid", "MAL"
gly (chemical): "glyoxylate", "glyoxylic acid", "GLYOX"
biosyn (unknown): "UNK", "biosynthesis", "unknown"

Reason: The species are all part of the tricarboxylic acid (TCA) cycle and glyoxylate bypass, which are well-studied biochemical pathways. The names are standardized based on common usage in biochemistry. aca, oaa, coa, cit, icit, akg, ssa, suc, sca, fa, mal, and gly are all chemical species, as they are metabolites in the TCA cycle and glyoxylate bypass. biosyn is unknown, as it appears to be a placeholder for a biosynthetic process rather than a specific chemical species.
Synonyms dict: {'aca': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'oaa': ['oxaloacetate', 'oxaloacetic acid', 'OAA'], 'coa': ['coenzyme A', 'CoA', 'Coenzyme A'], 'cit': ['citrate', 'citric acid', 'CIT'], 'icit': ['isocitrate', 'isocitric acid', 'ICIT'], 'akg': ['alpha-ketoglutarate', '2-oxoglutarate', 'AKG'], 'ssa': ['succinyl-CoA', 'succinyl coenzyme A', 'SSA'], 'suc': ['succinate', 'succinic acid', 'SUC'], 'sca': ['succinyl-CoA', 'succinyl coenzyme A', 'SCA'], 'fa': ['fumarate', 'fumaric acid', 'FUM'], 'mal': ['malate', 'malic acid', 'MAL'], 'gly': ['glyoxylate', 'glyoxylic acid', 'GLYOX'], 'biosyn': ['UNK', 'biosynthesis', 'unknown']}
Evaluating 219/1075: BIOMD0000000219.xml

2025-11-20 12:26:17,948 - WARNING - Skipping BIOMD0000000220.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000219.txt
LLM response:
aca (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
oaa (chemical): "oxaloacetate", "oxaloacetic acid", "OAA"
coa (chemical): "coenzyme A", "CoA", "CoASH"
cit (chemical): "citrate", "citric acid", "CIT"
icit (chemical): "isocitrate", "isocitric acid", "ICT"
akg (chemical): "alpha-ketoglutarate", "2-oxoglutarate", "AKG"
ssa (chemical): "succinyl-CoA", "succinyl coenzyme A", "SCoA"
suc (chemical): "succinate", "succinic acid", "SUC"
sca (chemical): "succinyl-CoA", "succinyl coenzyme A", "SCoA"
fa (chemical): "fumarate", "fumaric acid", "FUM"
mal (chemical): "malate", "malic acid", "MAL"
gly (chemical): "glyoxylate", "glyoxylic acid", "GLX"
biosyn (unknown): "UNK"

Reason: The species are all part of the tricarboxylic acid (TCA) cycle and glyoxylate bypass, which are metabolic pathways. Based on the reaction equations and the context of the model, all species except "biosyn" can be identified as chemicals, which are metabolites or intermediates in the pathways. "biosyn" is unknown because it is not a standard metabolite or intermediate in the TCA cycle or glyoxylate bypass, and its meaning is not clear from the context. The standardized names and synonyms are based on common names used in biochemistry and metabolic pathway databases.
Synonyms dict: {'aca': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'oaa': ['oxaloacetate', 'oxaloacetic acid', 'OAA'], 'coa': ['coenzyme A', 'CoA', 'CoASH'], 'cit': ['citrate', 'citric acid', 'CIT'], 'icit': ['isocitrate', 'isocitric acid', 'ICT'], 'akg': ['alpha-ketoglutarate', '2-oxoglutarate', 'AKG'], 'ssa': ['succinyl-CoA', 'succinyl coenzyme A', 'SCoA'], 'suc': ['succinate', 'succinic acid', 'SUC'], 'sca': ['succinyl-CoA', 'succinyl coenzyme A', 'SCoA'], 'fa': ['fumarate', 'fumaric acid', 'FUM'], 'mal': ['malate', 'malic acid', 'MAL'], 'gly': ['glyoxylate', 'glyoxylic acid', 'GLX'], 'biosyn': ['UNK']}
Evaluating 220/1075: BIOMD0000000220.xml
Evaluating 221/1075: BIOMD0000000221.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000221.txt
LLM response:
aca (chemical): "acetyl-CoA", "acetyl coenzyme A", "CoA-acetyl"
oaa (chemical): "oxaloacetate", "oxaloacetic acid", "oxalacetate"
coa (chemical): "coenzyme A", "CoA", "coenzyme A (unspecified)"
cit (chemical): "citrate", "citric acid", "citrate(4−)"
icit (chemical): "isocitrate", "isocitric acid", "DL-isocitrate"
akg (chemical): "alpha-ketoglutarate", "2-oxoglutarate", "α-ketoglutaric acid"
sca (chemical): "succinyl-CoA", "succinyl coenzyme A", "succinyl-CoA (unspecified)"
suc (chemical): "succinate", "succinic acid", "butanedioic acid"
fa (chemical): "fumarate", "fumaric acid", "trans-butenedioic acid"
mal (chemical): "malate", "malic acid", "hydroxybutanedioic acid"
gly (chemical): "glyoxylate", "glyoxylic acid", "oxoacetic acid"
Reason: The species are all part of the tricarboxylic acid (TCA) cycle and glyoxylate bypass, which are well-studied biochemical pathways. The names and synonyms provided are based on common names and abbreviations used in biochemistry. The entity types are all chemicals because they are metabolites or intermediates in the pathways, rather than genes, proteins, or complexes.
Synonyms dict: {'aca': ['acetyl-CoA', 'acetyl coenzyme A', 'CoA-acetyl'], 'oaa': ['oxaloacetate', 'oxaloacetic acid', 'oxalacetate'], 'coa': ['coenzyme A', 'CoA', 'coenzyme A (unspecified)'], 'cit': ['citrate', 'citric acid', 'citrate(4−)'], 'icit': ['isocitrate', 'isocitric acid', 'DL-isocitrate'], 'akg': ['alpha-ketoglutarate', '2-oxoglutarate', 'α-ketoglutaric acid'], 'sca': ['succinyl-CoA', 'succinyl coenzyme A', 'succinyl-CoA (unspecified)'], 'suc': ['succinate', 'succinic acid', 'butanedioic acid'], 'fa': ['fumarate', 'fumaric acid', 'trans-butenedioic acid'], 'mal': ['malate', 'malic acid', 'hydroxybutanedioic acid'], 'gly': ['glyoxylate', 'glyoxylic acid', 'oxoacetic acid']}
Evaluating 222/1075: BIOMD0000000222.xml

2025-11-20 12:26:25,945 - WARNING - Skipping BIOMD0000000223.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000222.txt
LLM response:
aca (chemical): "acetyl-CoA", "acetyl coenzyme A", "CoA-acetyl"
oaa (chemical): "oxaloacetate", "oxaloacetic acid", "oxalacetate"
coa (chemical): "coenzyme A", "CoA", "coenzyme A (unspecified)"
cit (chemical): "citrate", "citric acid", "citrate ion"
icit (chemical): "isocitrate", "isocitric acid", "D-isocitrate"
akg (chemical): "alpha-ketoglutarate", "2-oxoglutarate", "alpha-ketoglutaric acid"
sca (chemical): "succinyl-CoA", "succinyl coenzyme A", "succinyl-CoA (unspecified)"
suc (chemical): "succinate", "succinic acid", "butanedioate"
fa (chemical): "fumarate", "fumaric acid", "trans-butenedioic acid"
mal (chemical): "malate", "malic acid", "hydroxybutanedioic acid"
gly (chemical): "glyoxylate", "glyoxylic acid", "hydroxyacetic acid"
biosyn (unknown): "UNK",
Reason: The species can be identified based on their roles in the tricarboxylic acid cycle (TCA cycle) and glyoxylate bypass, which are well-known biochemical pathways. The reaction equations and the model context suggest that all species except "biosyn" are metabolites or intermediates in these pathways, which are typically chemicals. "biosyn" is unknown because it is not a standard metabolite or intermediate in the TCA cycle or glyoxylate bypass, and its reaction equation does not provide enough information to determine its entity type.
Synonyms dict: {'aca': ['acetyl-CoA', 'acetyl coenzyme A', 'CoA-acetyl'], 'oaa': ['oxaloacetate', 'oxaloacetic acid', 'oxalacetate'], 'coa': ['coenzyme A', 'CoA', 'coenzyme A (unspecified)'], 'cit': ['citrate', 'citric acid', 'citrate ion'], 'icit': ['isocitrate', 'isocitric acid', 'D-isocitrate'], 'akg': ['alpha-ketoglutarate', '2-oxoglutarate', 'alpha-ketoglutaric acid'], 'sca': ['succinyl-CoA', 'succinyl coenzyme A', 'succinyl-CoA (unspecified)'], 'suc': ['succinate', 'succinic acid', 'butanedioate'], 'fa': ['fumarate', 'fumaric acid', 'trans-butenedioic acid'], 'mal': ['malate', 'malic acid', 'hydroxybutanedioic acid'], 'gly': ['glyoxylate', 'glyoxylic acid', 'hydroxyacetic acid'], 'biosyn': ['UNK']}
Evaluating 223/1075: BIOMD0000000223.xml
Evaluating 224/1075: BIOMD0000000224.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000224.txt
LLM response:
CaI (chemical): "calcium ion", "Ca2+", "calcium
IP3 (chemical): "inositol trisphosphate", "D-myo-inositol 1,4,5-trisphosphate", "IP3"
CaS (chemical): "calcium", "calcium store", "endoplasmic reticulum calcium"

Reason: CaI is likely a chemical because it represents an ion, and its reaction with CaS suggests a calcium flux. IP3 is also a chemical, as it is a well-known second messenger involved in calcium signaling. CaS is likely a chemical or more specifically, a calcium store, representing the endoplasmic reticulum's calcium content, which is often modeled as a single entity in cellular signaling pathways.
Synonyms dict: {'CaI': ['calcium ion', 'Ca2+', '"calcium'], 'IP3': ['inositol trisphosphate', 'D-myo-inositol 1,4,5-trisphosphate', 'IP3'], 'CaS': ['calcium', 'calcium store', 'endoplasmic reticulum calcium']}
Evaluating 225/1075: BIOMD0000000225.xml

2025-11-20 12:26:30,372 - WARNING - Skipping BIOMD0000000226.xml - no results generated
2025-11-20 12:26:30,417 - WARNING - Skipping BIOMD0000000227.xml - no results generated
2025-11-20 12:26:30,427 - WARNING - Skipping BIOMD0000000228.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000225.txt
LLM response:
GLC (chemical): "glucose", "D-glucose", "blood sugar"
G6P_F6P (chemical): "glucose-6-phosphate", "fructose-6-phosphate", "G6P"
F6P (chemical): "fructose-6-phosphate", "fructose 6-phosphate", "F6P"
FBP (chemical): "fructose-1,6-bisphosphate", "fructose 1,6-bisphosphate", "FBPase substrate"
G3P (chemical): "glyceraldehyde-3-phosphate", "3-phosphoglyceraldehyde", "G3P"
Reason: The species are all part of the glycolytic pathway, which is a metabolic pathway that converts glucose into pyruvate, releasing energy. The model described is focused on the upper part of glycolysis in the pancreatic beta-cell, and all species are intermediates in this pathway, therefore they are all chemicals. The names provided are standardized names or common synonyms for each species, ranked by likelihood based on their common usage in biochemical literature.
Synonyms dict: {'GLC': ['glucose', 'D-glucose', 'blood sugar'], 'G6P_F6P': ['glucose-6-phosphate', 'fructose-6-phosphate', 'G6P'], 'F6P': ['fructose-6-phosphate', 'fructose 6-phosphate', 'F6P'], 'FBP': ['fructose-1,6-bisphosphate', 'fructose 1,6-bisphosphate', 'FBPase substrate'], 'G3P': ['glyceraldehyde-3-phosphate', '3-phosphoglyceraldehyde', 'G3P']}
Evaluating 226/1075: BIOMD0000000226.xml
Evaluating 227/1075: BIOMD0000000227.xml
Evaluating 228/1075: BIOMD0000000228.xml
Evaluating 229/1075: BIOMD0000000229.xml

2025-11-20 12:26:31,971 - WARNING - Skipping BIOMD0000000230.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000229.txt
LLM response:
incAMP (chemical): "cAMP", "cyclic adenosine monophosphate", "cyclic AMP"
excAMP (chemical): "cAMP", "cyclic adenosine monophosphate", "cyclic AMP"
Reason: Both incAMP and excAMP are likely referring to cyclic adenosine monophosphate (cAMP), a chemical messenger in cellular biology, given the context of the model "Ma2002_cAMP_oscillations" and the notes referencing oscillatory models and biochemical networks. The prefixes "inc" and "exc" may indicate different compartments or states of cAMP, but the underlying entity is the same chemical.
Synonyms dict: {'incAMP': ['cAMP', 'cyclic adenosine monophosphate', 'cyclic AMP'], 'excAMP': ['cAMP', 'cyclic adenosine monophosphate', 'cyclic AMP']}
Evaluating 230/1075: BIOMD0000000230.xml
Evaluating 231/1075: BIOMD0000000231.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000231.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
NADH (chemical): "nicotinamide adenine dinucleotide + hydrogen", "NADH", "reduced nicotinamide adenine dinucleotide"
Reason: All species are identified as chemicals because they are involved in a metabolic pathway and are known biochemical compounds, with ATP, AMP, and ADP being adenine nucleotides and NADH being a redox cofactor.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'NADH': ['nicotinamide adenine dinucleotide + hydrogen', 'NADH', 'reduced nicotinamide adenine dinucleotide']}
Evaluating 232/1075: BIOMD0000000232.xml

2025-11-20 12:26:39,354 - WARNING - Skipping BIOMD0000000233.xml - no results generated
2025-11-20 12:26:39,357 - WARNING - Skipping BIOMD0000000234.xml - no results generated
2025-11-20 12:26:39,608 - WARNING - Skipping BIOMD0000000235.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000232.txt
LLM response:
ADP (chemical): "adenosine diphosphate", "ADP molecule", "diphosphoadenosine"
ATP (chemical): "adenosine triphosphate", "ATP molecule", "triphosphoadenosine"
H (chemical): "hydrogen ion", "proton", "H+"
He (chemical): "hydrogen ion", "proton", "H+"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "diphosphopyridine nucleotide"
NADH (chemical): "nicotinamide adenine dinucleotide reduced", "NADH molecule", "reduced diphosphopyridine nucleotide"
AcCoA (chemical): "acetyl coenzyme A", "acetyl-CoA molecule", "coenzyme A acetyl"
KG (chemical): "alpha-ketoglutarate", "2-oxoglutarate", "ketoglutaric acid"
Cit (chemical): "citric acid", "citrate molecule", "citrate(4−)"
OAA (chemical): "oxaloacetic acid", "oxaloacetate molecule", "oxaloacetate(2−)"
O2 (chemical): "oxygen molecule", "dioxygen", "molecular oxygen"
iP (chemical): "inorganic phosphate", "phosphate ion", "orthophosphate"
Pyr (chemical): "pyruvic acid", "pyruvate molecule", "2-oxopropanoic acid"
H2O (chemical): "water molecule", "dihydrogen monoxide", "oxidane"
Reason: All species are assigned as chemicals because they are all participating in metabolic reactions, and their display names match known biochemical compounds. H and He are both assigned as hydrogen ions (protons) due to their display names and roles in the reactions. NAD and NADH are assigned as chemicals due to their central role in redox reactions. AcCoA, KG, Cit, OAA, Pyr, and iP are all intermediates or substrates in the TCA cycle or related reactions, and are thus classified as chemicals. O2 and H2O are classified as chemicals due to their roles in oxidation and hydration reactions, respectively. ATP and ADP are classified as chemicals due to their roles in energy transfer reactions.
Synonyms dict: {'ADP': ['adenosine diphosphate', 'ADP molecule', 'diphosphoadenosine'], 'ATP': ['adenosine triphosphate', 'ATP molecule', 'triphosphoadenosine'], 'H': ['hydrogen ion', 'proton', 'H+'], 'He': ['hydrogen ion', 'proton', 'H+'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'diphosphopyridine nucleotide'], 'NADH': ['nicotinamide adenine dinucleotide reduced', 'NADH molecule', 'reduced diphosphopyridine nucleotide'], 'AcCoA': ['acetyl coenzyme A', 'acetyl-CoA molecule', 'coenzyme A acetyl'], 'KG': ['alpha-ketoglutarate', '2-oxoglutarate', 'ketoglutaric acid'], 'Cit': ['citric acid', 'citrate molecule', 'citrate(4−)'], 'OAA': ['oxaloacetic acid', 'oxaloacetate molecule', 'oxaloacetate(2−)'], 'O2': ['oxygen molecule', 'dioxygen', 'molecular oxygen'], 'iP': ['inorganic phosphate', 'phosphate ion', 'orthophosphate'], 'Pyr': ['pyruvic acid', 'pyruvate molecule', '2-oxopropanoic acid'], 'H2O': ['water molecule', 'dihydrogen monoxide', 'oxidane']}
Evaluating 233/1075: BIOMD0000000233.xml
Evaluating 234/1075: BIOMD0000000234.xml
Evaluating 235/1075: BIOMD0000000235.xml
Evaluating 236/1075: BIOMD0000000236.xml

2025-11-20 12:26:42,652 - WARNING - Skipping BIOMD0000000237.xml - no results generated
2025-11-20 12:26:42,660 - WARNING - Skipping BIOMD0000000238.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000236.txt
LLM response:
GLC (chemical): "glucose", "intracellular glucose", "d-glucose"
G6P_F6P (chemical): "glucose-6-phosphate", "fructose-6-phosphate", "G6P"
F6P (chemical): "fructose-6-phosphate", "fructose 6-phosphate", "F6P"
FBP (chemical): "fructose-1,6-bisphosphate", "fructose 1,6-bisphosphate", "FBP"
G3P (chemical): "glyceraldehyde-3-phosphate", "glyceraldehyde 3-phosphate", "G3P"
DHAP (chemical): "dihydroxyacetone phosphate", "dihydroxyacetonephosphate", "DHAP"
DHAP_G3P (chemical): "DHAP-G3P pool", "glyceraldehyde-3-phosphate and dihydroxyacetone phosphate", "triose phosphate pool"
Reason: The model is a glycolytic pathway, which is a metabolic pathway that converts glucose into pyruvate, releasing energy and forming ATP and NADH in the process. All species are intermediates in this pathway and are therefore chemicals. The display names and the context of the model provide clear evidence for the identification of these species as chemicals, and the provided synonyms are standard names for these chemicals in the context of biochemistry.
Synonyms dict: {'GLC': ['glucose', 'intracellular glucose', 'd-glucose'], 'G6P_F6P': ['glucose-6-phosphate', 'fructose-6-phosphate', 'G6P'], 'F6P': ['fructose-6-phosphate', 'fructose 6-phosphate', 'F6P'], 'FBP': ['fructose-1,6-bisphosphate', 'fructose 1,6-bisphosphate', 'FBP'], 'G3P': ['glyceraldehyde-3-phosphate', 'glyceraldehyde 3-phosphate', 'G3P'], 'DHAP': ['dihydroxyacetone phosphate', 'dihydroxyacetonephosphate', 'DHAP'], 'DHAP_G3P': ['DHAP-G3P pool', 'glyceraldehyde-3-phosphate and dihydroxyacetone phosphate', 'triose phosphate pool']}
Evaluating 237/1075: BIOMD0000000237.xml
Evaluating 238/1075: BIOMD0000000238.xml
Evaluating 239/1075: BIOMD0000000239.xml

2025-11-20 12:26:59,075 - WARNING - Skipping BIOMD0000000240.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000239.txt
LLM response:
QH2 (chemical): "ubiquinol", "reduced ubiquinone", "coenzyme QH2"
Reason: QH2 is identified as "ubiquinol" in the display names, which is a reduced form of ubiquinone, a chemical compound involved in the electron transport chain. The reactions also suggest its role as a chemical intermediate in the model.
Synonyms dict: {'GLC': ['glucose', 'D-glucose', 'blood sugar'], 'F6P': ['fructose-6-phosphate', 'fructose 6-phosphate', 'F6P'], 'FBP': ['fructose-1,6-bisphosphate', 'fructose 1,6-bisphosphate', 'FBP'], 'GAP': ['glyceraldehyde 3-phosphate', 'G3P', 'glyceraldehyde-3-phosphate'], 'DPG': ['1,3-bisphosphoglycerate', '1,3-BPG', '1,3-diphosphoglycerate'], 'PEP': ['phosphoenolpyruvate', 'PEP', 'enolpyruvate'], 'PYR_cyt': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'AMP': ['adenosine monophosphate', 'AMP', 'adénylate'], 'LAC': ['lactate', 'lactic acid', '2-hydroxypropanoic acid'], 'G3P': ['glycerol-3-phosphate', 'glycerophosphate', 'L-3-glycerophosphate'], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP', '3-hydroxy-2-oxopropanal phosphate'], 'OXA_cyt': ['oxaloacetate', 'oxaloacetic acid', '2-oxobutanedioic acid'], 'Asp_cyt': ['aspartate', 'aspartic acid', '2-aminosuccinic acid'], 'Glu_cyt': ['glutamate', 'glutamic acid', '2-aminopentanedioic acid'], 'OG_cyt': ['2-oxoglutarate', 'alpha-ketoglutarate', '2-oxopentanedioic acid'], 'Mal_cyt': ['malate', 'malic acid', '2-hydroxybutanedioic acid'], 'Acetyl_CoA_cyt': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'CoA_cyt': ['coenzyme A', 'CoA', 'CoASH'], 'IsoCitcyt': ['isocitrate', 'isocitric acid', '1,2,3-tricarboxypropane'], 'Cit_cyt': ['citrate', 'citric acid', '2-hydroxy-1,2,3-propanetricarboxylic acid'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'NAD plus'], 'NADH_cyt': ['NADH', 'nicotinamide adenine dinucleotide reduced', 'NADH'], 'NADP_cyt': ['NADP+', 'nicotinamide adenine dinucleotide phosphate', 'NADP'], 'NADPH_cyt': ['NADPH', 'nicotinamide adenine dinucleotide phosphate reduced', 'NADPH'], 'Pyr': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'CoA': ['coenzyme A', 'CoA', 'CoASH'], 'Acetyl_CoA': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'Pi': ['inorganic phosphate', 'phosphate', 'Pi'], 'Fum': ['fumarate', 'fumaric acid', '2-butenedioic acid'], 'SCoA': ['succinyl-CoA', 'succinyl coenzyme A', 'succinyl-CoA'], 'Suc': ['succinate', 'succinic acid', 'butanedioic acid'], 'GTP': ['guanosine triphosphate', 'GTP', "guanosine-5'-triphosphate"], 'GDP': ['guanosine diphosphate', 'GDP', "guanosine-5'-diphosphate"], 'Ala': ['alanine', '2-aminopropanoic acid', 'alpha-alanine'], 'Asp': ['aspartate', 'aspartic acid', '2-aminosuccinic acid'], 'Glu': ['glutamate', 'glutamic acid', '2-aminopentanedioic acid'], 'H2O': ['water', 'H2O', 'dihydrogen monoxide'], 'FADH2': ['flavin adenine dinucleotide reduced', 'FADH2', 'FADH'], 'FAD': ['flavin adenine dinucleotide', 'FAD', 'FAD oxidized'], 'OG': ['2-oxoglutarate', 'alpha-ketoglutarate', '2-oxopentanedioic acid'], 'Mal': ['malate', 'malic acid', '2-hydroxybutanedioic acid'], 'OXA': ['oxaloacetate', 'oxaloacetic acid', '2-oxobutanedioic acid'], 'Cit': ['citrate', 'citric acid', '2-hydroxy-1,2,3-propanetricarboxylic acid'], 'IsoCit': ['isocitrate', 'isocitric acid', '1,2,3-tricarboxypropane'], 'NADP_p': ['NADP+', 'nicotinamide adenine dinucleotide phosphate', 'NADP'], 'NADPH': ['NADPH', 'nicotinamide adenine dinucleotide phosphate reduced', 'NADPH'], 'NAD_p': ['NAD+', 'nicotinamide adenine dinucleotide', 'NAD plus'], 'NADH': ['NADH', 'nicotinamide adenine dinucleotide reduced', 'NADH'], 'Q': ['ubiquinone', 'coenzyme Q', 'CoQ'], 'QH2': ['ubiquinol', 'reduced ubiquinone', 'coenzyme QH2']}
Evaluating 240/1075: BIOMD0000000240.xml
Evaluating 241/1075: BIOMD0000000241.xml

2025-11-20 12:27:00,987 - WARNING - Skipping BIOMD0000000242.xml - no results generated
2025-11-20 12:27:00,996 - WARNING - Skipping BIOMD0000000243.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000241.txt
LLM response:
X_gut (chemical): "caffeine", "caffeine in gut", "gut caffeine"
C_p (chemical): "plasma caffeine", "caffeine in plasma", "caffeine"
C_per (chemical): "peripheral caffeine", "caffeine in peripheral compartment", "peripheral caffeine concentration"
C_e (chemical): "effect compartment caffeine", "caffeine in effect compartment", "effect site caffeine"
C_t (chemical): "tolerance compartment caffeine", "caffeine in tolerance compartment", "tolerance site caffeine"

Reason: All species are related to caffeine and its distribution in the body, with X_gut representing caffeine in the gut, C_p in the plasma, C_per in the peripheral compartment, C_e in the effect compartment, and C_t in the tolerance compartment, indicating that they are all chemical entities related to caffeine pharmacokinetics and pharmacodynamics.
Synonyms dict: {'X_gut': ['caffeine', 'caffeine in gut', 'gut caffeine'], 'C_p': ['plasma caffeine', 'caffeine in plasma', 'caffeine'], 'C_per': ['peripheral caffeine', 'caffeine in peripheral compartment', 'peripheral caffeine concentration'], 'C_e': ['effect compartment caffeine', 'caffeine in effect compartment', 'effect site caffeine'], 'C_t': ['tolerance compartment caffeine', 'caffeine in tolerance compartment', 'tolerance site caffeine']}
Evaluating 242/1075: BIOMD0000000242.xml
Evaluating 243/1075: BIOMD0000000243.xml
Evaluating 244/1075: BIOMD0000000244.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000244.txt
LLM response:
ACT (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
AKG (chemical): "alpha-ketoglutarate", "2-oxoglutarate", "α-ketoglutaric acid"
ACoA (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
cAMP (chemical): "cyclic adenosine monophosphate", "cyclic AMP", "cAMP"
FBP (chemical): "fructose-1,6-bisphosphate", "fructose 1,6-bisphosphate", "FBP"
G6P (chemical): "glucose-6-phosphate", "glucose 6-phosphate", "G6P"
GLX (chemical): "glutamate", "L-glutamate", "glutamic acid"
ICT (chemical): "isocitrate", "isocitric acid", "three-Ds-isocitrate"
MAL (chemical): "malate", "L-malate", "malic acid"
OAA (chemical): "oxaloacetate", "oxaloacetic acid", "OAA"
PEP (chemical): "phosphoenolpyruvate", "phosphoenolpyruvic acid", "PEP"
PG3 (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PG3"
PYR (chemical): "pyruvate", "pyruvic acid", "PYR"
CraFBP (complex): "cAMP receptor protein-fructose-1,6-bisphosphate complex", "CRP-FBP complex", "cAMP-CRP-FBP"
CrpcAMP (complex): "cAMP-CRP complex", "cAMP receptor protein-cAMP complex", "CRP-cAMP"
PdhRPYR (complex): "pyruvate dehydrogenase complex-pyruvate complex", "PDH-PYR complex", "pyruvate dehydrogenase-PYR"
GLC (chemical): "glucose", "D-glucose", "blood sugar"
EIIA (protein): "enzyme II A", "EIIA protein", "phosphotransferase system enzyme II A"
PdhR (protein): "pyruvate dehydrogenase regulator", "PDH regulator", "pyruvate dehydrogenase complex regulator"
Cra (protein): "cAMP receptor protein", "CRP protein", "cAMP receptor"
Crp (protein): "cAMP receptor protein", "CRP protein", "cAMP receptor"
EIIA_P (protein): "phosphorylated enzyme II A", "EIIA-P protein", "phosphotransferase system enzyme II A-P"

Reason: The entity types are determined based on the context of the model and the names of the species. Most species are identified as chemicals, which are metabolites involved in the metabolic pathways. Some species are identified as complexes, which are protein-metabolite complexes. A few species are identified as proteins, which are enzymes or regulators involved in the metabolic pathways. The standardized names and synonyms are provided based on common names used in biochemistry and molecular biology. The reasons for each species are based on the model description, the reaction equations, and the notes provided.
Synonyms dict: {'ACT': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'AKG': ['alpha-ketoglutarate', '2-oxoglutarate', 'α-ketoglutaric acid'], 'ACoA': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'cAMP': ['cyclic adenosine monophosphate', 'cyclic AMP', 'cAMP'], 'FBP': ['fructose-1,6-bisphosphate', 'fructose 1,6-bisphosphate', 'FBP'], 'G6P': ['glucose-6-phosphate', 'glucose 6-phosphate', 'G6P'], 'GLX': ['glutamate', 'L-glutamate', 'glutamic acid'], 'ICT': ['isocitrate', 'isocitric acid', 'three-Ds-isocitrate'], 'MAL': ['malate', 'L-malate', 'malic acid'], 'OAA': ['oxaloacetate', 'oxaloacetic acid', 'OAA'], 'PEP': ['phosphoenolpyruvate', 'phosphoenolpyruvic acid', 'PEP'], 'PG3': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PG3'], 'PYR': ['pyruvate', 'pyruvic acid', 'PYR'], 'CraFBP': ['cAMP receptor protein-fructose-1,6-bisphosphate complex', 'CRP-FBP complex', 'cAMP-CRP-FBP'], 'CrpcAMP': ['cAMP-CRP complex', 'cAMP receptor protein-cAMP complex', 'CRP-cAMP'], 'PdhRPYR': ['pyruvate dehydrogenase complex-pyruvate complex', 'PDH-PYR complex', 'pyruvate dehydrogenase-PYR'], 'GLC': ['glucose', 'D-glucose', 'blood sugar'], 'EIIA': ['enzyme II A', 'EIIA protein', 'phosphotransferase system enzyme II A'], 'PdhR': ['pyruvate dehydrogenase regulator', 'PDH regulator', 'pyruvate dehydrogenase complex regulator'], 'Cra': ['cAMP receptor protein', 'CRP protein', 'cAMP receptor'], 'Crp': ['cAMP receptor protein', 'CRP protein', 'cAMP receptor'], 'EIIA_P': ['phosphorylated enzyme II A', 'EIIA-P protein', 'phosphotransferase system enzyme II A-P']}
Evaluating 245/1075: BIOMD0000000245.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000245.txt
LLM response:
s_glu (chemical): "Glucose", "D-Glucose", "Blood sugar"
s_pyr (chemical): "Pyruvate", "Pyruvic acid", "2-Oxopropanoic acid"
s_acetald (chemical): "Acetaldehyde", "Ethanal", "Acetic aldehyde"
s_EtOH (chemical): "Ethanol", "Ethyl alcohol", "Alcohol"
CO2 (chemical): "Carbon dioxide", "CO2", "Carbonic acid"
Red (chemical): "NADH", "Nicotinamide adenine dinucleotide", "Reduced nicotinamide adenine dinucleotide"
S_f (chemical): "Glucose", "D-Glucose", "Blood sugar"
s_acetate (chemical): "Acetate", "Acetic acid", "Ethanoic acid"
x (unknown): "UNK"
Reason: The species can be identified as chemicals based on their display names and roles in the reactions, which are typical of metabolic pathways. s_glu, s_pyr, s_acetald, s_EtOH, CO2, and Red are all common metabolites in cellular metabolism. S_f is likely another name for glucose, given its display name and role in the reaction. s_acetate is also a common metabolite. x is unknown because its display name "BM" is unclear, and it does not have a clear role in the reactions.
Synonyms dict: {'s_glu': ['Glucose', 'D-Glucose', 'Blood sugar'], 's_pyr': ['Pyruvate', 'Pyruvic acid', '2-Oxopropanoic acid'], 's_acetald': ['Acetaldehyde', 'Ethanal', 'Acetic aldehyde'], 's_EtOH': ['Ethanol', 'Ethyl alcohol', 'Alcohol'], 'CO2': ['Carbon dioxide', 'CO2', 'Carbonic acid'], 'Red': ['NADH', 'Nicotinamide adenine dinucleotide', 'Reduced nicotinamide adenine dinucleotide'], 'S_f': ['Glucose', 'D-Glucose', 'Blood sugar'], 's_acetate': ['Acetate', 'Acetic acid', 'Ethanoic acid'], 'x': ['UNK']}
Evaluating 246/1075: BIOMD0000000246.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000246.txt
LLM response:
Ca_in (chemical): "calcium ion", "Ca2+", "calcium"
Ca_store (chemical): "calcium ion", "Ca2+", "calcium"
Ca_ex (chemical): "calcium ion", "Ca2+", "calcium"
Cl_ex (chemical): "chloride ion", "Cl-", "chloride"
Cl_o (chemical): "chloride ion", "Cl-", "chloride"
GABA (chemical): "gamma-aminobutyric acid", "GABA neurotransmitter", "4-aminobutanoic acid"
GABA_o (chemical): "gamma-aminobutyric acid", "GABA neurotransmitter", "4-aminobutanoic acid"
K_in (chemical): "potassium ion", "K+", "potassium"
K_ex (chemical): "potassium ion", "K+", "potassium"
Reason: All species are ions or neurotransmitters involved in the electrophysiology of pacemaker neurons, as described in the model notes. Calcium (Ca) is a key player in the model, with Ca_in and Ca_store representing different states of calcium ions. Chloride (Cl) and potassium (K) ions are also essential for neuronal function. GABA is a neurotransmitter that plays a critical role in the model. The "_in", "_ex", and "_o" suffixes likely indicate different locations or states of the ions, but do not change their underlying entity type.
Synonyms dict: {'Ca_in': ['calcium ion', 'Ca2+', 'calcium'], 'Ca_store': ['calcium ion', 'Ca2+', 'calcium'], 'Ca_ex': ['calcium ion', 'Ca2+', 'calcium'], 'Cl_ex': ['chloride ion', 'Cl-', 'chloride'], 'Cl_o': ['chloride ion', 'Cl-', 'chloride'], 'GABA': ['gamma-aminobutyric acid', 'GABA neurotransmitter', '4-aminobutanoic acid'], 'GABA_o': ['gamma-aminobutyric acid', 'GABA neurotransmitter', '4-aminobutanoic acid'], 'K_in': ['potassium ion', 'K+', 'potassium'], 'K_ex': ['potassium ion', 'K+', 'potassium']}
Evaluating 247/1075: BIOMD0000000247.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000247.txt
LLM response:
P (chemical): "high energy phosphate", "phosphate group", "inorganic phosphate"
G6P (chemical): "glucose 6-phosphate", "D-glucose 6-phosphate", "G6P"
F6P (chemical): "fructose 6-phosphate", "D-fructose 6-phosphate", "F6P"
F16P (chemical): "fructose-1,6-bisphosphate", "D-fructose-1,6-bisphosphate", "F1,6BP"
NADH (chemical): "nicotinamide adenine dinucleotide + hydrogen", "NADH", "reduced NAD"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "oxidized NAD"
BPG (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "BPG"
P3G (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "3PG"
P2G (chemical): "2-phosphoglycerate", "2-phosphoglyceric acid", "2PG"
PEP (chemical): "phosphoenolpyruvate", "phosphoenolpyruvic acid", "PEP"
PYR (chemical): "pyruvate", "pyruvic acid", "PYR"
ACE (chemical): "acetaldehyde", "ethanal", "ACE"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
ETOH (chemical): "ethanol", "ethyl alcohol", "ETOH"
SUCC (chemical): "succinate", "succinic acid", "SUCC"
GA3P (chemical): "glyceraldehyde 3-phosphate", "D-glyceraldehyde 3-phosphate", "G3P"
DHAP (chemical): "dihydroxyacetone phosphate", "DHAP", "DHA"
GLY (chemical): "glycerol", "glycerin", "GLY"
D6PGluconoLactone (chemical): "6-phosphogluconolactone", "6-phosphoglucono-1,5-lactone", "6PGL"
D6PGluconate (chemical): "6-phosphogluconate", "6-phosphogluconic acid", "6PG"
NADP (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP+", "oxidized NADP"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate + hydrogen", "NADPH", "reduced NADP"
Ribulose5P (chemical): "ribulose 5-phosphate", "D-ribulose 5-phosphate", "Ru5P"
Ribose5P (chemical): "ribose 5-phosphate", "D-ribose 5-phosphate", "R5P"
Xyl5P (chemical): "xylulose 5-phosphate", "D-xylulose 5-phosphate", "Xu5P"
Seduhept7P (chemical): "sedoheptulose 7-phosphate", "D-sedoheptulose 7-phosphate", "S7P"
Erythrose4P (chemical): "erythrose 4-phosphate", "D-erythrose 4-phosphate", "E4P"
GLCo (chemical): "glucose", "D-glucose", "extracellular glucose"
GLCi (chemical): "glucose", "D-glucose", "cytosolic glucose"
F26BP (chemical): "fructose-2,6-bisphosphate", "D-fructose-2,6-bisphosphate", "F2,6BP"
X (unknown): "UNK", "unknown", "undefined"
Reason: The species were identified based on their display names and the context of the model, which appears to be a metabolic pathway model. The entity types were determined based on the species' roles in the model and their chemical structures. The standardized names and synonyms were chosen based on common usage in biochemistry and metabolism. The unknown species "X" was assigned as such due to the lack of information about its identity or role in the model.
Synonyms dict: {'P': ['high energy phosphate', 'phosphate group', 'inorganic phosphate'], 'G6P': ['glucose 6-phosphate', 'D-glucose 6-phosphate', 'G6P'], 'F6P': ['fructose 6-phosphate', 'D-fructose 6-phosphate', 'F6P'], 'F16P': ['fructose-1,6-bisphosphate', 'D-fructose-1,6-bisphosphate', 'F1,6BP'], 'NADH': ['nicotinamide adenine dinucleotide + hydrogen', 'NADH', 'reduced NAD'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'oxidized NAD'], 'BPG': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', 'BPG'], 'P3G': ['3-phosphoglycerate', '3-phosphoglyceric acid', '3PG'], 'P2G': ['2-phosphoglycerate', '2-phosphoglyceric acid', '2PG'], 'PEP': ['phosphoenolpyruvate', 'phosphoenolpyruvic acid', 'PEP'], 'PYR': ['pyruvate', 'pyruvic acid', 'PYR'], 'ACE': ['acetaldehyde', 'ethanal', 'ACE'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'ETOH': ['ethanol', 'ethyl alcohol', 'ETOH'], 'SUCC': ['succinate', 'succinic acid', 'SUCC'], 'GA3P': ['glyceraldehyde 3-phosphate', 'D-glyceraldehyde 3-phosphate', 'G3P'], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP', 'DHA'], 'GLY': ['glycerol', 'glycerin', 'GLY'], 'D6PGluconoLactone': ['6-phosphogluconolactone', '6-phosphoglucono-1,5-lactone', '6PGL'], 'D6PGluconate': ['6-phosphogluconate', '6-phosphogluconic acid', '6PG'], 'NADP': ['nicotinamide adenine dinucleotide phosphate', 'NADP+', 'oxidized NADP'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate + hydrogen', 'NADPH', 'reduced NADP'], 'Ribulose5P': ['ribulose 5-phosphate', 'D-ribulose 5-phosphate', 'Ru5P'], 'Ribose5P': ['ribose 5-phosphate', 'D-ribose 5-phosphate', 'R5P'], 'Xyl5P': ['xylulose 5-phosphate', 'D-xylulose 5-phosphate', 'Xu5P'], 'Seduhept7P': ['sedoheptulose 7-phosphate', 'D-sedoheptulose 7-phosphate', 'S7P'], 'Erythrose4P': ['erythrose 4-phosphate', 'D-erythrose 4-phosphate', 'E4P'], 'GLCo': ['glucose', 'D-glucose', 'extracellular glucose'], 'GLCi': ['glucose', 'D-glucose', 'cytosolic glucose'], 'F26BP': ['fructose-2,6-bisphosphate', 'D-fructose-2,6-bisphosphate', 'F2,6BP'], 'X': ['UNK', 'unknown', 'undefined']}
Evaluating 248/1075: BIOMD0000000248.xml

2025-11-20 12:27:29,012 - WARNING - Skipping BIOMD0000000249.xml - no results generated
2025-11-20 12:27:29,031 - WARNING - Skipping BIOMD0000000250.xml - no results generated
2025-11-20 12:27:29,037 - WARNING - Skipping BIOMD0000000251.xml - no results generated
2025-11-20 12:27:29,040 - WARNING - Skipping BIOMD0000000252.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000248.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
PCr (chemical): "phosphocreatine", "phosphocreatine kinase", "PCr"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Cr (chemical): "creatine", "creatine monohydrate", "methylguanidine"
Pi (chemical): "inorganic phosphate", "phosphate", "orthophosphate"
CTcap (unknown): "oxygen concentration in blood capillary", "blood capillary oxygen", "UNK"
CTtis (unknown): "oxygen concentration in tissue", "tissue oxygen", "UNK"
CFcap (unknown): "free oxygen concentration in blood capillary", "blood capillary free oxygen", "UNK"
CFtis (unknown): "free oxygen concentration in tissue", "tissue free oxygen", "UNK"
Reason: The species ATP, PCr, ADP, Cr, and Pi are all well-known biochemical molecules and are classified as chemicals. CTcap, CTtis, CFcap, and CFtis are not specific biochemical molecules, but rather represent oxygen concentrations in different compartments, so they are classified as unknown. The names provided for these unknown species are based on the descriptions in the model notes.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'PCr': ['phosphocreatine', 'phosphocreatine kinase', 'PCr'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'Cr': ['creatine', 'creatine monohydrate', 'methylguanidine'], 'Pi': ['inorganic phosphate', 'phosphate', 'orthophosphate'], 'CTcap': ['oxygen concentration in blood capillary', 'blood capillary oxygen', 'UNK'], 'CTtis': ['oxygen concentration in tissue', 'tissue oxygen', 'UNK'], 'CFcap': ['free oxygen concentration in blood capillary', 'blood capillary free oxygen', 'UNK'], 'CFtis': ['free oxygen concentration in tissue', 'tissue free oxygen', 'UNK']}
Evaluating 249/1075: BIOMD0000000249.xml
Evaluating 250/1075: BIOMD0000000250.xml
Evaluating 251/1075: BIOMD0000000251.xml
Evaluating 252/1075: BIOMD0000000252.xml
Evaluating 253/1075: BIOMD0000000253.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000253.txt
LLM response:
HMP (chemical): "hexose monophosphate", "hexose phosphate", "fructose-6-phosphate"
Fru16P2 (chemical): "fructose 1,6-bisphosphate", "fructose-1,6-diphosphate", "F1,6BP"
ATP (chemical): "adenosine triphosphate", "ATP molecule", "adenosine 5'-triphosphate"
Glc (chemical): "glucose", "D-glucose", "blood sugar"
Tre6P (chemical): "trehalose 6-phosphate", "trehalose-6-phosphate", "T6P"
ADP (chemical): "adenosine diphosphate", "ADP molecule", "adenosine 5'-diphosphate"
Reason: All species are identified as chemicals because they are metabolites involved in the glycolytic pathway, with display names and reactions that indicate their roles as substrates, products, or intermediates in enzymatic reactions. The standardized names and synonyms are based on common biochemical nomenclature and the display names provided in the model.
Synonyms dict: {'HMP': ['hexose monophosphate', 'hexose phosphate', 'fructose-6-phosphate'], 'Fru16P2': ['fructose 1,6-bisphosphate', 'fructose-1,6-diphosphate', 'F1,6BP'], 'ATP': ['adenosine triphosphate', 'ATP molecule', "adenosine 5'-triphosphate"], 'Glc': ['glucose', 'D-glucose', 'blood sugar'], 'Tre6P': ['trehalose 6-phosphate', 'trehalose-6-phosphate', 'T6P'], 'ADP': ['adenosine diphosphate', 'ADP molecule', "adenosine 5'-diphosphate"]}
Evaluating 254/1075: BIOMD0000000254.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000254.txt
LLM response:
G1 (chemical): "Glucose", "D-Glucose", "Blood sugar"
T1 (chemical): "Adenosine triphosphate", "ATP", "Adenosine 5'-triphosphate"
G2 (chemical): "Glucose", "D-Glucose", "Blood sugar"
T2 (chemical): "Adenosine triphosphate", "ATP", "Adenosine 5'-triphosphate"
Reason: The model "Bier2000_GlycolyticOscillation" is a glycolytic oscillation model, which involves the breakdown of glucose to produce energy. G1 and G2 are likely glucose molecules, while T1 and T2 are likely ATP molecules, which are energy-rich molecules that play a central role in energy transfer within cells. The display names "Glucose_1" and "Glucose_2" for G1 and G2, and "ATP_1" and "ATP_2" for T1 and T2, support this annotation.
Synonyms dict: {'G1': ['Glucose', 'D-Glucose', 'Blood sugar'], 'T1': ['Adenosine triphosphate', 'ATP', "Adenosine 5'-triphosphate"], 'G2': ['Glucose', 'D-Glucose', 'Blood sugar'], 'T2': ['Adenosine triphosphate', 'ATP', "Adenosine 5'-triphosphate"]}
Evaluating 255/1075: BIOMD0000000255.xml

2025-11-20 12:27:40,032 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:27:40,476 - WARNING - Skipping BIOMD0000000256.xml - no results generated
2025-11-20 12:27:40,479 - WARNING - Skipping BIOMD0000000257.xml - no results generated
2025-11-20 12:27:40,482 - WARNING - Skipping BIOMD0000000258.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000255.txt
LLM response:
c2 (protein): "ErbB1", "EGFR", "Epidermal growth factor receptor"
c3 (complex): "EGF:ErbB1:ATP", "ErbB1:EGF:ATP", "EGFR:EGF:ATP"
c500 (complex): "EGF:ErbB1:ATP::EGF:ErbB1:Inh", "ErbB1:EGF:ATP:Inh", "EGFR:EGF:ATP:Inh"
c4 (complex): "2(EGF:ErbB1:ATP)", "ErbB1:EGF:ATP dimer", "EGFR:EGF:ATP dimer"
c10 (complex): "EGF:ErbB1:ATP", "ErbB1:EGF:ATP", "EGFR:EGF:ATP"
c11 (complex): "2(EGF:ErbB1:ATP)", "ErbB1:EGF:ATP dimer", "EGFR:EGF:ATP dimer"
c106 (chemical): "PIP3", "Phosphatidylinositol 3,4,5-trisphosphate", "PtdIns(3,4,5)P3"
c285 (chemical): "Inh", "Inhibitor", "Tyrosine kinase inhibitor"
c462 (complex): "PIP3:Shp", "Phosphatidylinositol 3,4,5-trisphosphate:SH2 domain-containing phosphatase", "PtdIns(3,4,5)P3:SH2 domain-containing phosphatase"
Reason: The entity types are determined based on the names and reactions in the model. c2, c3, c4, c10, and c11 are complexes of proteins (ErbB1 and EGF) and ATP, while c106 is a chemical (PIP3) and c285 is an inhibitor (Inh). c462 is a complex of PIP3 and Shp (a protein). c500 is a complex of EGF, ErbB1, ATP, and Inh. The standardized names are based on common synonyms and abbreviations used in the field of molecular biology.
Synonyms dict: {'c2': ['ErbB1', 'EGFR', 'Epidermal growth factor receptor'], 'c3': ['EGF:ErbB1:ATP', 'ErbB1:EGF:ATP', 'EGFR:EGF:ATP'], 'c500': ['EGF:ErbB1:ATP::EGF:ErbB1:Inh', 'ErbB1:EGF:ATP:Inh', 'EGFR:EGF:ATP:Inh'], 'c4': ['2(EGF:ErbB1:ATP)', 'ErbB1:EGF:ATP dimer', 'EGFR:EGF:ATP dimer'], 'c10': ['EGF:ErbB1:ATP', 'ErbB1:EGF:ATP', 'EGFR:EGF:ATP'], 'c11': ['2(EGF:ErbB1:ATP)', 'ErbB1:EGF:ATP dimer', 'EGFR:EGF:ATP dimer'], 'c106': ['PIP3', 'Phosphatidylinositol 3,4,5-trisphosphate', 'PtdIns(3,4,5)P3'], 'c285': ['Inh', 'Inhibitor', 'Tyrosine kinase inhibitor'], 'c462': ['PIP3:Shp', 'Phosphatidylinositol 3,4,5-trisphosphate:SH2 domain-containing phosphatase', 'PtdIns(3,4,5)P3:SH2 domain-containing phosphatase']}
Evaluating 256/1075: BIOMD0000000256.xml
Evaluating 257/1075: BIOMD0000000257.xml
Evaluating 258/1075: BIOMD0000000258.xml
Evaluating 259/1075: BIOMD0000000259.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000259.txt
LLM response:
s1 (chemical): "iron", "ferric ion", "Fe3+"
s2 (chemical): "iron in bone marrow", "ferric ion in bone marrow", "bone marrow iron"
s3 (chemical): "iron in red blood cells", "ferric ion in RBC", "RBC iron"
s4 (chemical): "iron in spleen", "ferric ion in spleen", "spleen iron"
s5 (chemical): "iron in liver", "ferric ion in liver", "liver iron"
s6 (chemical): "iron in muscle", "ferric ion in muscle", "muscle iron"
s7 (chemical): "iron in duodenum", "ferric ion in duodenum", "duodenum iron"
s8 (chemical): "iron in integument", "ferric ion in integument", "integument iron"
s9 (chemical): "iron in intestine", "ferric ion in intestine", "intestinal iron"
s10 (chemical): "iron ions outside", "extracellular iron", "plasma iron"
s11 (chemical): "iron in heart", "ferric ion in heart", "heart iron"
s12 (chemical): "iron in lungs", "ferric ion in lungs", "lung iron"
s13 (chemical): "iron in kidneys", "ferric ion in kidneys", "kidney iron"
s14 (chemical): "iron in testes", "ferric ion in testes", "testicular iron"
s15 (chemical): "iron in stomach", "ferric ion in stomach", "stomach iron"
s16 (chemical): "iron in fat", "ferric ion in fat", "fat iron"
s17 (chemical): "iron in brain", "ferric ion in brain", "brain iron"
Reason: All species are annotated as chemicals because they represent different pools of iron in various tissues and organs, and the model describes the dynamics of iron metabolism. The standardized names and synonyms provided are based on the display names and the context of the model, which suggests that all species are related to iron ions or ferric ions in different locations.
Synonyms dict: {'s1': ['iron', 'ferric ion', 'Fe3+'], 's2': ['iron in bone marrow', 'ferric ion in bone marrow', 'bone marrow iron'], 's3': ['iron in red blood cells', 'ferric ion in RBC', 'RBC iron'], 's4': ['iron in spleen', 'ferric ion in spleen', 'spleen iron'], 's5': ['iron in liver', 'ferric ion in liver', 'liver iron'], 's6': ['iron in muscle', 'ferric ion in muscle', 'muscle iron'], 's7': ['iron in duodenum', 'ferric ion in duodenum', 'duodenum iron'], 's8': ['iron in integument', 'ferric ion in integument', 'integument iron'], 's9': ['iron in intestine', 'ferric ion in intestine', 'intestinal iron'], 's10': ['iron ions outside', 'extracellular iron', 'plasma iron'], 's11': ['iron in heart', 'ferric ion in heart', 'heart iron'], 's12': ['iron in lungs', 'ferric ion in lungs', 'lung iron'], 's13': ['iron in kidneys', 'ferric ion in kidneys', 'kidney iron'], 's14': ['iron in testes', 'ferric ion in testes', 'testicular iron'], 's15': ['iron in stomach', 'ferric ion in stomach', 'stomach iron'], 's16': ['iron in fat', 'ferric ion in fat', 'fat iron'], 's17': ['iron in brain', 'ferric ion in brain', 'brain iron']}
Evaluating 260/1075: BIOMD0000000260.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000260.txt
LLM response:
s1 (chemical): "iron", "ferric ion", "Fe3+"
s2 (chemical): "iron in bone marrow", "ferric ion in bone marrow", "bone marrow iron"
s3 (chemical): "iron in red blood cells", "ferric ion in red blood cells", "RBC iron"
s4 (chemical): "iron in spleen", "ferric ion in spleen", "spleen iron"
s5 (chemical): "iron in liver", "ferric ion in liver", "liver iron"
s6 (chemical): "iron in muscle", "ferric ion in muscle", "muscle iron"
s7 (chemical): "iron in duodenum", "ferric ion in duodenum", "duodenum iron"
s8 (chemical): "iron in integument", "ferric ion in integument", "integument iron"
s9 (chemical): "iron in intestine", "ferric ion in intestine", "intestinal iron"
s10 (chemical): "iron ions outside", "extracellular iron", "free iron"
s11 (chemical): "iron in heart", "ferric ion in heart", "heart iron"
s12 (chemical): "iron in lungs", "ferric ion in lungs", "lung iron"
s13 (chemical): "iron in kidneys", "ferric ion in kidneys", "kidney iron"
s14 (chemical): "iron in testes", "ferric ion in testes", "testicular iron"
s15 (chemical): "iron in stomach", "ferric ion in stomach", "stomach iron"
s16 (chemical): "iron in fat", "ferric ion in fat", "fat iron"
s17 (chemical): "iron in brain", "ferric ion in brain", "brain iron"
Reason: All species are identified as chemicals because they are all related to iron ions or iron in different tissues and organs. The model is focused on iron metabolism, and the reactions describe the movement of iron between different compartments, indicating that the species represent iron in various forms and locations. The names provided are based on the display names and the context of the model, with the most likely standardized names or common synonyms listed first.
Synonyms dict: {'s1': ['iron', 'ferric ion', 'Fe3+'], 's2': ['iron in bone marrow', 'ferric ion in bone marrow', 'bone marrow iron'], 's3': ['iron in red blood cells', 'ferric ion in red blood cells', 'RBC iron'], 's4': ['iron in spleen', 'ferric ion in spleen', 'spleen iron'], 's5': ['iron in liver', 'ferric ion in liver', 'liver iron'], 's6': ['iron in muscle', 'ferric ion in muscle', 'muscle iron'], 's7': ['iron in duodenum', 'ferric ion in duodenum', 'duodenum iron'], 's8': ['iron in integument', 'ferric ion in integument', 'integument iron'], 's9': ['iron in intestine', 'ferric ion in intestine', 'intestinal iron'], 's10': ['iron ions outside', 'extracellular iron', 'free iron'], 's11': ['iron in heart', 'ferric ion in heart', 'heart iron'], 's12': ['iron in lungs', 'ferric ion in lungs', 'lung iron'], 's13': ['iron in kidneys', 'ferric ion in kidneys', 'kidney iron'], 's14': ['iron in testes', 'ferric ion in testes', 'testicular iron'], 's15': ['iron in stomach', 'ferric ion in stomach', 'stomach iron'], 's16': ['iron in fat', 'ferric ion in fat', 'fat iron'], 's17': ['iron in brain', 'ferric ion in brain', 'brain iron']}
Evaluating 261/1075: BIOMD0000000261.xml

2025-11-20 12:27:54,849 - WARNING - Skipping BIOMD0000000262.xml - no results generated
2025-11-20 12:27:54,855 - WARNING - Skipping BIOMD0000000263.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000261.txt
LLM response:
s1 (chemical): "iron", "ferric ion", "Fe3+"
s2 (chemical): "iron in bone marrow", "ferric ion in bone marrow", "Fe3+ in bone marrow"
s3 (chemical): "iron in red blood cells", "ferric ion in RBC", "Fe3+ in erythrocytes"
s4 (chemical): "iron in spleen", "ferric ion in spleen", "Fe3+ in spleen"
s5 (chemical): "iron in liver", "ferric ion in liver", "Fe3+ in liver"
s6 (chemical): "iron in muscle", "ferric ion in muscle", "Fe3+ in muscle"
s7 (chemical): "iron in duodenum", "ferric ion in duodenum", "Fe3+ in duodenum"
s8 (chemical): "iron in integument", "ferric ion in integument", "Fe3+ in skin"
s9 (chemical): "iron in intestine", "ferric ion in intestine", "Fe3+ in intestine"
s10 (chemical): "iron ions outside", "ferric ion outside", "Fe3+ outside"
s11 (chemical): "iron in heart", "ferric ion in heart", "Fe3+ in heart"
s12 (chemical): "iron in lungs", "ferric ion in lungs", "Fe3+ in lungs"
s13 (chemical): "iron in kidneys", "ferric ion in kidneys", "Fe3+ in kidneys"
s14 (chemical): "iron in testes", "ferric ion in testes", "Fe3+ in testes"
s15 (chemical): "iron in stomach", "ferric ion in stomach", "Fe3+ in stomach"
s16 (chemical): "iron in fat", "ferric ion in fat", "Fe3+ in adipose tissue"
s17 (chemical): "iron in brain", "ferric ion in brain", "Fe3+ in brain"
Reason: All species are assigned as chemicals because they represent iron ions or iron in different tissues and organs, and there is no indication of genes, proteins, or complexes in the model description. The standardized names and synonyms are based on the display names provided in the model, with "iron" and "ferric ion" being common names for the chemical element, and "Fe3+" being its symbol.
Synonyms dict: {'s1': ['iron', 'ferric ion', 'Fe3+'], 's2': ['iron in bone marrow', 'ferric ion in bone marrow', 'Fe3+ in bone marrow'], 's3': ['iron in red blood cells', 'ferric ion in RBC', 'Fe3+ in erythrocytes'], 's4': ['iron in spleen', 'ferric ion in spleen', 'Fe3+ in spleen'], 's5': ['iron in liver', 'ferric ion in liver', 'Fe3+ in liver'], 's6': ['iron in muscle', 'ferric ion in muscle', 'Fe3+ in muscle'], 's7': ['iron in duodenum', 'ferric ion in duodenum', 'Fe3+ in duodenum'], 's8': ['iron in integument', 'ferric ion in integument', 'Fe3+ in skin'], 's9': ['iron in intestine', 'ferric ion in intestine', 'Fe3+ in intestine'], 's10': ['iron ions outside', 'ferric ion outside', 'Fe3+ outside'], 's11': ['iron in heart', 'ferric ion in heart', 'Fe3+ in heart'], 's12': ['iron in lungs', 'ferric ion in lungs', 'Fe3+ in lungs'], 's13': ['iron in kidneys', 'ferric ion in kidneys', 'Fe3+ in kidneys'], 's14': ['iron in testes', 'ferric ion in testes', 'Fe3+ in testes'], 's15': ['iron in stomach', 'ferric ion in stomach', 'Fe3+ in stomach'], 's16': ['iron in fat', 'ferric ion in fat', 'Fe3+ in adipose tissue'], 's17': ['iron in brain', 'ferric ion in brain', 'Fe3+ in brain']}
Evaluating 262/1075: BIOMD0000000262.xml
Evaluating 263/1075: BIOMD0000000263.xml
Evaluating 264/1075: BIOMD0000000264.xml

2025-11-20 12:27:56,875 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:27:56,958 - WARNING - Skipping BIOMD0000000265.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000264.txt
LLM response:
EGFR_i (protein): "epidermal growth factor receptor", "EGFR", "ERBB1"
EGF_EGFR_i (complex): "EGF-EGFR complex", "epidermal growth factor receptor complex", "EGFR-EGF complex"
Reason: EGFR_i is a protein because it is referred to as a receptor and has a specific inhibitor, indicating it is a target for a drug. EGF_EGFR_i is a complex because it is formed by the interaction of EGF and EGFR, as shown in the reaction $EGF + EGFR_i -> EGF_EGFR_i$. The names provided are standardized based on common terminology in cell biology and signal transduction.
Synonyms dict: {'EGFR_i': ['epidermal growth factor receptor', 'EGFR', 'ERBB1'], 'EGF_EGFR_i': ['EGF-EGFR complex', 'epidermal growth factor receptor complex', 'EGFR-EGF complex']}
Evaluating 265/1075: BIOMD0000000265.xml
Evaluating 266/1075: BIOMD0000000266.xml

2025-11-20 12:27:59,365 - WARNING - Skipping BIOMD0000000267.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000266.txt
LLM response:
X0 (chemical): "glucose", "D-glucose", "blood sugar"
X1 (chemical): "glucose", "D-glucose", "blood sugar"
X2 (chemical): "glucose-6-phosphate", "G6P", "D-glucose-6-phosphate"
X3 (chemical): "glucose-1-phosphate", "G1P", "D-glucose-1-phosphate"
X4 (chemical): "uridine diphosphate glucose", "UDPG", "UDP-glucose"
X6 (chemical): "trehalose-6-phosphate", "T6P", "D-trehalose-6-phosphate"
X7 (chemical): "trehalose", "mycose", "D-trehalose"
Reason: All species can be identified as chemicals based on their display names and the context of the trehalose cycle model. The names provided are standardized and common synonyms for each species, ranked by likelihood based on their usage in biochemical literature. The model's description and the display names allow for the unambiguous identification of the entity types and names for all species.
Synonyms dict: {'X0': ['glucose', 'D-glucose', 'blood sugar'], 'X1': ['glucose', 'D-glucose', 'blood sugar'], 'X2': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'X3': ['glucose-1-phosphate', 'G1P', 'D-glucose-1-phosphate'], 'X4': ['uridine diphosphate glucose', 'UDPG', 'UDP-glucose'], 'X6': ['trehalose-6-phosphate', 'T6P', 'D-trehalose-6-phosphate'], 'X7': ['trehalose', 'mycose', 'D-trehalose']}
Evaluating 267/1075: BIOMD0000000267.xml
Evaluating 268/1075: BIOMD0000000268.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000268.txt
LLM response:
b_met (chemical): "methionine", "L-methionine", "L-Met"
b_ser (chemical): "serine", "L-serine", "L-Ser"
GAR (chemical): "glycinamide ribonucleotide", "5'-phosphoribosylglycinamide", "GAR"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP+", "NADPH"
BET (chemical): "betaine", "trimethylglycine", "Bet"
DUMP (chemical): "deoxyuridine monophosphate", "dUMP", "deoxyuridine 5'-monophosphate"
Fol (chemical): "folate", "folic acid", "vitamin B9"
H2O2 (chemical): "hydrogen peroxide", "H2O2", "peroxide"
CO (chemical): "carbon dioxide", "CO2", "carbon dioxide gas"
HCHO (chemical): "formaldehyde", "methanal", "HCHO"
c_thf (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
m_thf (chemical): "methyltetrahydrofolate", "mTHF", "5-methyl-THF"
c_5mf (chemical): "5-methyltetrahydrofolate", "5-Me-THF", "5-methyl-THF"
c_2cf (chemical): "5,10-methylenetetrahydrofolate", "5,10-Me-THF", "5,10-methylene-THF"
c_10f (chemical): "10-formyltetrahydrofolate", "10-CHO-THF", "10-formyl-THF"
c_dhf (chemical): "dihydrofolate", "DHF", "7,8-dihydrofolate"
m_2cf (chemical): "5,10-methylenetetrahydrofolate", "5,10-Me-THF", "5,10-methylene-THF"
m_10f (chemical): "10-formyltetrahydrofolate", "10-CHO-THF", "10-formyl-THF"
b_gly (chemical): "glycine", "L-glycine", "L-Gly"
b_glu (chemical): "glutamate", "L-glutamate", "L-Glu"
b_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
b_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
b_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
aic (chemical): "5-amino-4-imidazolecarboxamide", "AICAR", "5-amino-4-imidazolecarboxamide ribonucleotide"
c_glu (chemical): "glutamate", "L-glutamate", "L-Glu"
c_gly (chemical): "glycine", "L-glycine", "L-Gly"
c_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
c_coo (chemical): "formate", "formic acid", "HCOOH"
m_ser (chemical): "serine", "L-serine", "L-Ser"
m_gly (chemical): "glycine", "L-glycine", "L-Gly"
m_coo (chemical): "formate", "formic acid", "HCOOH"
src (chemical): "sarcosine", "N-methylglycine", "Sarc"
dmg (chemical): "dimethylglycine", "DMG", "N,N-dimethylglycine"
glc (chemical): "glutamylcysteine", "γ-glutamylcysteine", "Glu-Cys"
c_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
c_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
hcy (chemical): "homocysteine", "L-homocysteine", "L-Hcy"
c_ser (chemical): "serine", "L-serine", "L-Ser"
sah (chemical): "S-adenosylhomocysteine", "SAH", "S-adenosyl-L-homocysteine"
sam (chemical): "S-adenosylmethionine", "SAM", "S-adenosyl-L-methionine"
met (chemical): "methionine", "L-methionine", "L-Met"
Reason: All species are identified as chemicals based on their display names and roles in the Reed2008_Glutathione_Metabolism model. The model describes the metabolism of glutathione and related compounds, and all species are involved in chemical reactions. The display names and synonyms provided for each species are based on common names and abbreviations used in biochemistry and metabolism.
Synonyms dict: {'b_met': ['methionine', 'L-methionine', 'L-Met'], 'b_ser': ['serine', 'L-serine', 'L-Ser'], 'GAR': ['glycinamide ribonucleotide', "5'-phosphoribosylglycinamide", 'GAR'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADP+', 'NADPH'], 'BET': ['betaine', 'trimethylglycine', 'Bet'], 'DUMP': ['deoxyuridine monophosphate', 'dUMP', "deoxyuridine 5'-monophosphate"], 'Fol': ['folate', 'folic acid', 'vitamin B9'], 'H2O2': ['hydrogen peroxide', 'H2O2', 'peroxide'], 'CO': ['carbon dioxide', 'CO2', 'carbon dioxide gas'], 'HCHO': ['formaldehyde', 'methanal', 'HCHO'], 'c_thf': ['tetrahydrofolate', 'THF', 'tetrahydrofolic acid'], 'm_thf': ['methyltetrahydrofolate', 'mTHF', '5-methyl-THF'], 'c_5mf': ['5-methyltetrahydrofolate', '5-Me-THF', '5-methyl-THF'], 'c_2cf': ['5,10-methylenetetrahydrofolate', '5,10-Me-THF', '5,10-methylene-THF'], 'c_10f': ['10-formyltetrahydrofolate', '10-CHO-THF', '10-formyl-THF'], 'c_dhf': ['dihydrofolate', 'DHF', '7,8-dihydrofolate'], 'm_2cf': ['5,10-methylenetetrahydrofolate', '5,10-Me-THF', '5,10-methylene-THF'], 'm_10f': ['10-formyltetrahydrofolate', '10-CHO-THF', '10-formyl-THF'], 'b_gly': ['glycine', 'L-glycine', 'L-Gly'], 'b_glu': ['glutamate', 'L-glutamate', 'L-Glu'], 'b_cys': ['cysteine', 'L-cysteine', 'L-Cys'], 'b_gsg': ['glutathione disulfide', 'GSSG', 'oxidized glutathione'], 'b_gsh': ['glutathione', 'GSH', 'reduced glutathione'], 'aic': ['5-amino-4-imidazolecarboxamide', 'AICAR', '5-amino-4-imidazolecarboxamide ribonucleotide'], 'c_glu': ['glutamate', 'L-glutamate', 'L-Glu'], 'c_gly': ['glycine', 'L-glycine', 'L-Gly'], 'c_cys': ['cysteine', 'L-cysteine', 'L-Cys'], 'c_coo': ['formate', 'formic acid', 'HCOOH'], 'm_ser': ['serine', 'L-serine', 'L-Ser'], 'm_gly': ['glycine', 'L-glycine', 'L-Gly'], 'm_coo': ['formate', 'formic acid', 'HCOOH'], 'src': ['sarcosine', 'N-methylglycine', 'Sarc'], 'dmg': ['dimethylglycine', 'DMG', 'N,N-dimethylglycine'], 'glc': ['glutamylcysteine', 'γ-glutamylcysteine', 'Glu-Cys'], 'c_gsh': ['glutathione', 'GSH', 'reduced glutathione'], 'c_gsg': ['glutathione disulfide', 'GSSG', 'oxidized glutathione'], 'hcy': ['homocysteine', 'L-homocysteine', 'L-Hcy'], 'c_ser': ['serine', 'L-serine', 'L-Ser'], 'sah': ['S-adenosylhomocysteine', 'SAH', 'S-adenosyl-L-homocysteine'], 'sam': ['S-adenosylmethionine', 'SAM', 'S-adenosyl-L-methionine'], 'met': ['methionine', 'L-methionine', 'L-Met']}
Evaluating 269/1075: BIOMD0000000269.xml

2025-11-20 12:28:13,835 - WARNING - Skipping BIOMD0000000270.xml - no results generated
2025-11-20 12:28:13,840 - WARNING - Skipping BIOMD0000000271.xml - no results generated
2025-11-20 12:28:13,844 - WARNING - Skipping BIOMD0000000272.xml - no results generated
2025-11-20 12:28:13,860 - WARNING - Skipping BIOMD0000000273.xml - no results generated
2025-11-20 12:28:13,863 - WARNING - Skipping BIOMD0000000274.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000269.txt
LLM response:
ET (chemical): "ethylene", "ethene", "C2H4"
IAA (chemical): "indole-3-acetic acid", "indoleacetic acid", "auxin"
ACC (chemical): "1-aminocyclopropane-1-carboxylic acid", "1-aminocyclopropanecarboxylic acid", "ACC"
Reason: ET, IAA, and ACC are all known plant hormones or hormone precursors, with ET being ethylene, IAA being a form of auxin, and ACC being a precursor to ethylene. The model and notes describe hormonal crosstalk in Arabidopsis, supporting the classification of these species as chemicals.
Synonyms dict: {'ET': ['ethylene', 'ethene', 'C2H4'], 'IAA': ['indole-3-acetic acid', 'indoleacetic acid', 'auxin'], 'ACC': ['1-aminocyclopropane-1-carboxylic acid', '1-aminocyclopropanecarboxylic acid', 'ACC']}
Evaluating 270/1075: BIOMD0000000270.xml
Evaluating 271/1075: BIOMD0000000271.xml
Evaluating 272/1075: BIOMD0000000272.xml
Evaluating 273/1075: BIOMD0000000273.xml
Evaluating 274/1075: BIOMD0000000274.xml
Evaluating 275/1075: BIOMD0000000275.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000275.txt
LLM response:
RA (chemical): "retinoic acid", "vitamin A acid", "all-trans retinoic acid"
Reason: RA is identified as retinoic acid in the model notes and reactions, which is a chemical involved in signaling pathways, particularly in development and cell growth. The synonyms provided are common names for retinoic acid, with "all-trans retinoic acid" being a more specific form.
Synonyms dict: {'RA': ['retinoic acid', 'vitamin A acid', 'all-trans retinoic acid']}
Evaluating 276/1075: BIOMD0000000276.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000276.txt
LLM response:
Ca (chemical): "calcium", "ionized calcium", "Ca(2+)"
Reason: The model is about calcium homeostasis and the species Ca is referred to as "Ca_in_Plasma" and "plasma ionized calcium (Ca(2+))" in the notes, indicating that it is a chemical entity, specifically an ion.
Synonyms dict: {'Ca': ['calcium', 'ionized calcium', 'Ca(2+)']}
Evaluating 277/1075: BIOMD0000000277.xml

2025-11-20 12:28:17,855 - WARNING - Skipping BIOMD0000000278.xml - no results generated
2025-11-20 12:28:17,859 - WARNING - Skipping BIOMD0000000279.xml - no results generated
2025-11-20 12:28:17,862 - WARNING - Skipping BIOMD0000000280.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000277.txt
LLM response:
Ca (chemical): "calcium", "ionized calcium", "Ca(2+)"
Reason: The species Ca is identified as a chemical because it refers to calcium, a chemical element, and is described in the context of plasma ionized calcium concentration in the human body, which is a key aspect of calcium homeostasis. The model and notes provide further evidence of Ca being a chemical, as it is involved in the calcium-PTH axis and its concentration is crucial for maintaining normal physiology and metabolism.
Synonyms dict: {'Ca': ['calcium', 'ionized calcium', 'Ca(2+)']}
Evaluating 278/1075: BIOMD0000000278.xml
Evaluating 279/1075: BIOMD0000000279.xml
Evaluating 280/1075: BIOMD0000000280.xml
Evaluating 281/1075: BIOMD0000000281.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000281.txt
LLM response:
GLU (chemical): "glucose", "D-glucose", "blood sugar"
ENG (complex): "hexokinase-glucose complex", "glucose-hexokinase intermediate", "HK-Glu"
TP1 (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
GLP (chemical): "glucose 6-phosphate", "G6P", "D-glucose 6-phosphate"
ETG (complex): "phosphofructokinase intermediate", "PFK intermediate", "fructose-1,6-bisphosphate"
GPP (chemical): "hexose diphosphate", "fructose 1,6-bisphosphate", "F1,6BP"
GAP (chemical): "glyceraldehyde 3-phosphate", "G3P", "3-phosphoglyceraldehyde"
DHA (chemical): "dihydroxyacetone phosphate", "DHAP", "3-hydroxy-2-oxopropionaldehyde phosphate"
DPN (chemical): "diphosphopyridine nucleotide", "NAD+", "nicotinamide adenine dinucleotide"
DPH (chemical): "reduced diphosphopyridine nucleotide", "NADH", "nicotinamide adenine dinucleotide reduced"
PID (chemical): "inorganic phosphate", "Pi", "orthophosphate"
DGA (chemical): "1,3-diphosphoglycerate", "1,3-DPG", "1,3-bisphosphoglycerate"
PGA (chemical): "3-phosphoglycerate", "3-PGA", "3-phosphoglyceric acid"
PYR (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
LAC (chemical): "lactate", "lactic acid", "2-hydroxypropanoic acid"
DIN (chemical): "intramitochondrial diphosphopyridine nucleotide", "mitochondrial NAD+", "mNAD+"
DIH (chemical): "intramitochondrial reduced diphosphopyridine nucleotide", "mitochondrial NADH", "mNADH"
OXY (chemical): "oxygen", "O2", "molecular oxygen"
TP2 (chemical): "adenosine triphosphate in mitochondria", "mitochondrial ATP", "mATP"
PPP (complex): "enzyme intermediate concerned in ATP utilization", "ATP-utilizing enzyme complex", "E-ATP"
AGP (chemical): "alpha-glycerophosphate", "alpha-GP", "L-alpha-glycerophosphate"
MOD (complex): "glyceraldehyde 3-phosphate dehydrogenase-DPN complex", "GAPDH-NAD+ complex", "G3PDH-DPN"
MOB (complex): "acyl enzyme intermediate of glyceraldehyde 3-phosphate dehydrogenase", "GAPDH-acyl intermediate", "G3PDH-acyl"

Reason: The entity types are determined based on the display names and the reactions in the model. Chemical species are identified as molecules or ions, while complexes are identified as enzyme-substrate or enzyme-cofactor intermediates. The standardized names and synonyms are chosen based on common biochemical nomenclature and the context of the model. The Chance 1960 model is a well-known model of glycolysis and respiration, and the species names are consistent with the biochemical pathways described in the model.
Synonyms dict: {'GLU': ['glucose', 'D-glucose', 'blood sugar'], 'ENG': ['hexokinase-glucose complex', 'glucose-hexokinase intermediate', 'HK-Glu'], 'TP1': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'GLP': ['glucose 6-phosphate', 'G6P', 'D-glucose 6-phosphate'], 'ETG': ['phosphofructokinase intermediate', 'PFK intermediate', 'fructose-1,6-bisphosphate'], 'GPP': ['hexose diphosphate', 'fructose 1,6-bisphosphate', 'F1,6BP'], 'GAP': ['glyceraldehyde 3-phosphate', 'G3P', '3-phosphoglyceraldehyde'], 'DHA': ['dihydroxyacetone phosphate', 'DHAP', '3-hydroxy-2-oxopropionaldehyde phosphate'], 'DPN': ['diphosphopyridine nucleotide', 'NAD+', 'nicotinamide adenine dinucleotide'], 'DPH': ['reduced diphosphopyridine nucleotide', 'NADH', 'nicotinamide adenine dinucleotide reduced'], 'PID': ['inorganic phosphate', 'Pi', 'orthophosphate'], 'DGA': ['1,3-diphosphoglycerate', '1,3-DPG', '1,3-bisphosphoglycerate'], 'PGA': ['3-phosphoglycerate', '3-PGA', '3-phosphoglyceric acid'], 'PYR': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'LAC': ['lactate', 'lactic acid', '2-hydroxypropanoic acid'], 'DIN': ['intramitochondrial diphosphopyridine nucleotide', 'mitochondrial NAD+', 'mNAD+'], 'DIH': ['intramitochondrial reduced diphosphopyridine nucleotide', 'mitochondrial NADH', 'mNADH'], 'OXY': ['oxygen', 'O2', 'molecular oxygen'], 'TP2': ['adenosine triphosphate in mitochondria', 'mitochondrial ATP', 'mATP'], 'PPP': ['enzyme intermediate concerned in ATP utilization', 'ATP-utilizing enzyme complex', 'E-ATP'], 'AGP': ['alpha-glycerophosphate', 'alpha-GP', 'L-alpha-glycerophosphate'], 'MOD': ['glyceraldehyde 3-phosphate dehydrogenase-DPN complex', 'GAPDH-NAD+ complex', 'G3PDH-DPN'], 'MOB': ['acyl enzyme intermediate of glyceraldehyde 3-phosphate dehydrogenase', 'GAPDH-acyl intermediate', 'G3PDH-acyl']}
Evaluating 282/1075: BIOMD0000000282.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000282.txt
LLM response:
x (chemical): "hydrogen peroxide", "H2O2", "hydrogen peroxide molecule"
p (complex): "enzyme-substrate complex ES", "catalase-hydrogen peroxide complex", "ES complex"
p1 (chemical): "water", "H2O", "product 1"
p2 (chemical): "oxygen", "O2", "product 2"
a (chemical): "electron donor AH2", "AH2", "donor molecule"

Reason: The species x is identified as hydrogen peroxide, a chemical, based on its display name "substrate S (hydrogen peroxide)". p is a complex, specifically the enzyme-substrate complex between catalase and hydrogen peroxide. p1 and p2 are likely chemicals, with p1 being water and p2 being oxygen, based on the typical products of the catalase reaction. a is also a chemical, identified as an electron donor, but its exact identity is not specified, so it is referred to as "electron donor AH2" or "AH2".
Synonyms dict: {'x': ['hydrogen peroxide', 'H2O2', 'hydrogen peroxide molecule'], 'p': ['enzyme-substrate complex ES', 'catalase-hydrogen peroxide complex', 'ES complex'], 'p1': ['water', 'H2O', 'product 1'], 'p2': ['oxygen', 'O2', 'product 2'], 'a': ['electron donor AH2', 'AH2', 'donor molecule']}
Evaluating 283/1075: BIOMD0000000283.xml

2025-11-20 12:28:31,658 - WARNING - Skipping BIOMD0000000284.xml - no results generated
2025-11-20 12:28:31,671 - WARNING - Skipping BIOMD0000000285.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000283.txt
LLM response:
X (chemical): "hydrogen peroxide", "H2O2", "peroxide"
P (complex): "peroxidase-H2O2 Complex I", "Peroxidase-H2O2", "enzyme-substrate compound"
Q (chemical): "water", "H2O", "hydroxide"

Reason: Based on the model description and the reactions provided, X is likely hydrogen peroxide, a common substrate for peroxidase enzymes. P is identified as the enzyme-substrate compound, specifically peroxidase-H2O2 Complex I, which is a complex formed between the peroxidase enzyme and hydrogen peroxide. Q is likely water, a common product of enzymatic reactions involving peroxidases, although its display name does not provide direct information, the context of the reaction and the involvement of hydrogen peroxide suggest water as a plausible product.
Synonyms dict: {'X': ['hydrogen peroxide', 'H2O2', 'peroxide'], 'P': ['peroxidase-H2O2 Complex I', 'Peroxidase-H2O2', 'enzyme-substrate compound'], 'Q': ['water', 'H2O', 'hydroxide']}
Evaluating 284/1075: BIOMD0000000284.xml
Evaluating 285/1075: BIOMD0000000285.xml
Evaluating 286/1075: BIOMD0000000286.xml

2025-11-20 12:28:33,295 - WARNING - Skipping BIOMD0000000287.xml - no results generated
2025-11-20 12:28:33,303 - WARNING - Skipping BIOMD0000000288.xml - no results generated
2025-11-20 12:28:33,308 - WARNING - Skipping BIOMD0000000289.xml - no results generated
2025-11-20 12:28:33,312 - WARNING - Skipping BIOMD0000000290.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000286.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
Reason: ATP, ADP, and AMP are all nucleotides that play important roles in energy transfer within cells, and their names are widely recognized and standardized in biochemistry. The model's context, involving cellular processes and energy-related reactions, further supports their classification as chemicals.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"]}
Evaluating 287/1075: BIOMD0000000287.xml
Evaluating 288/1075: BIOMD0000000288.xml
Evaluating 289/1075: BIOMD0000000289.xml
Evaluating 290/1075: BIOMD0000000290.xml
Evaluating 291/1075: BIOMD0000000291.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000291.txt
LLM response:
x2 (chemical): "bilirubin", "bilirubin complex", "BC"
x3 (complex): "albumin-bilirubin complex", "AlCn", "albumin-C complex"
x6 (chemical): "binding site", "carbon pyropolymer site", "B"
x7 (chemical): "albumin", "Al", "human serum albumin"
B0 (unknown): "UNK", "unknown species", "unidentified molecule"
C0 (unknown): "UNK", "unknown species", "unidentified molecule"
Reason: x2 is likely a chemical as it is referred to as "BC" which could be bilirubin or a bilirubin complex. x3 is a complex as it is referred to as "AlCn" which could be an albumin-bilirubin complex. x6 is a chemical as it is involved in binding reactions and could represent a binding site on the carbon pyropolymer. x7 is a chemical as it is referred to as "Al" which could be albumin. B0 and C0 are unknown as there is not enough information to determine their entity types.
Synonyms dict: {'x2': ['bilirubin', 'bilirubin complex', 'BC'], 'x3': ['albumin-bilirubin complex', 'AlCn', 'albumin-C complex'], 'x6': ['binding site', 'carbon pyropolymer site', 'B'], 'x7': ['albumin', 'Al', 'human serum albumin'], 'B0': ['UNK', 'unknown species', 'unidentified molecule'], 'C0': ['UNK', 'unknown species', 'unidentified molecule']}
Evaluating 292/1075: BIOMD0000000292.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000292.txt
LLM response:
NADPH (chemical): "NADPH", "Nicotinamide adenine dinucleotide phosphate", "Reduced NADP"
ADP (chemical): "ADP", "Adenosine diphosphate", "Adenine dinucleotide"
ATP (chemical): "ATP", "Adenosine triphosphate", "Adenine triphosphate"
X (unknown): "UNK"
Y (unknown): "UNK"
NADP (chemical): "NADP", "Nicotinamide adenine dinucleotide phosphate", "NADP+"

Reason: NADPH, ADP, ATP, and NADP are all well-known chemicals involved in cellular metabolism, particularly in energy transfer and photosynthesis. X and Y are unknown because they lack display names or descriptions that could be used to identify them, and their roles in the reactions are not clearly defined in the provided context.
Synonyms dict: {'NADPH': ['NADPH', 'Nicotinamide adenine dinucleotide phosphate', 'Reduced NADP'], 'ADP': ['ADP', 'Adenosine diphosphate', 'Adenine dinucleotide'], 'ATP': ['ATP', 'Adenosine triphosphate', 'Adenine triphosphate'], 'X': ['UNK'], 'Y': ['UNK'], 'NADP': ['NADP', 'Nicotinamide adenine dinucleotide phosphate', 'NADP+']}
Evaluating 293/1075: BIOMD0000000293.xml

2025-11-20 12:28:40,206 - WARNING - Skipping BIOMD0000000294.xml - no results generated
2025-11-20 12:28:40,210 - WARNING - Skipping BIOMD0000000295.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000293.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
Reason: ATP, ADP, and AMP are all well-known chemical compounds that play crucial roles in energy transfer within cells, which is consistent with their involvement in the reactions listed in the model, particularly in the context of protein aggregation and proteasome activity. Their standardized names and common synonyms are widely recognized in biochemistry.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"]}
Evaluating 294/1075: BIOMD0000000294.xml
Evaluating 295/1075: BIOMD0000000295.xml
Evaluating 296/1075: BIOMD0000000296.xml

2025-11-20 12:28:41,914 - WARNING - Skipping BIOMD0000000297.xml - no results generated
2025-11-20 12:28:41,919 - WARNING - Skipping BIOMD0000000298.xml - no results generated
2025-11-20 12:28:41,922 - WARNING - Skipping BIOMD0000000299.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000296.txt
LLM response:
IPTG (chemical): "isopropyl β-D-1-thiogalactopyranoside", "IPTG", "isopropylthiogalactoside"
A1 (chemical): "N-acylhomoserine lactone", "AHL", "autoinducer"
A2 (chemical): "N-acylhomoserine lactone", "AHL", "autoinducer"
Reason: IPTG is a known chemical inducer, and A1 and A2 are likely autoinducer molecules such as N-acylhomoserine lactones (AHLs) based on the context of the article and the model, which describes a synthetic Escherichia coli predator-prey ecosystem involving cell-cell communication through AHLs.
Synonyms dict: {'IPTG': ['isopropyl β-D-1-thiogalactopyranoside', 'IPTG', 'isopropylthiogalactoside'], 'A1': ['N-acylhomoserine lactone', 'AHL', 'autoinducer'], 'A2': ['N-acylhomoserine lactone', 'AHL', 'autoinducer']}
Evaluating 297/1075: BIOMD0000000297.xml
Evaluating 298/1075: BIOMD0000000298.xml
Evaluating 299/1075: BIOMD0000000299.xml
Evaluating 300/1075: BIOMD0000000300.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000300.txt
LLM response:
species_11 (chemical): "oxygen", "O2", "molecular oxygen"
Reason: The display name for species_11 is "O2", which is a common symbol for oxygen, a chemical element. The model is related to hypoxia and oxygen-dependent processes, further supporting the identification of species_11 as oxygen.
Synonyms dict: {'species_11': ['oxygen', 'O2', 'molecular oxygen']}
Evaluating 301/1075: BIOMD0000000301.xml

2025-11-20 12:28:44,318 - WARNING - Skipping BIOMD0000000302.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000301.txt
LLM response:
ara (chemical): "arabinose", "L-arabinose", "alpha-L-arabinose"
Reason: The species "ara" is likely referring to the sugar arabinose, which is a common chemical used in biological systems, particularly in the context of E. coli as mentioned in the model notes. The standardized names provided are common synonyms for arabinose.
Synonyms dict: {'ara': ['arabinose', 'L-arabinose', 'alpha-L-arabinose']}
Evaluating 302/1075: BIOMD0000000302.xml
Evaluating 303/1075: BIOMD0000000303.xml

2025-11-20 12:28:53,452 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000303.txt
LLM response:
PC (protein): "properdin", "factor P", "proproperdin"
PC_CRP (complex): "properdin-CRP complex", "PC/CRP complex", "properdin-C-reactive protein complex"
PC_CRP_C1 (complex): "properdin-CRP-C1 complex", "PC/CRP/C1 complex", "properdin-C-reactive protein-C1 complex"
GlcNac (chemical): "N-acetylglucosamine", "GlcNAc", "2-acetamido-glucose"
GlcNac_LF (complex): "GlcNac/L-ficolin complex", "N-acetylglucosamine-L-ficolin complex", "GlcNAc/LF complex"
GlcNac_LF_MASP (complex): "GlcNac/LF/MASP complex", "N-acetylglucosamine-L-ficolin-MASP complex", "GlcNAc/LF/MASP complex"
PC_CRP_LF (complex): "PC/CRP/LF complex", "properdin-CRP-L-ficolin complex", "PC/CRP/LF complex"
PC_CRP_LF_MASP (complex): "PC/CRP/LF/MASP complex", "properdin-CRP-L-ficolin-MASP complex", "PC/CRP/LF/MASP complex"
GlcNac_LF_CRP (complex): "GlcNac/LF/CRP complex", "N-acetylglucosamine-L-ficolin-CRP complex", "GlcNAc/LF/CRP complex"
GlcNac_LF_CRP_C1 (complex): "GlcNac/LF/CRP/C1 complex", "N-acetylglucosamine-L-ficolin-CRP-C1 complex", "GlcNAc/LF/CRP/C1 complex"
C4BP_PC_CRP (complex): "C4BP/PC/CRP complex", "C4b-binding protein-properdin-CRP complex", "C4BP/PC/CRP complex"
C4BP_GlcNac_LF_CRP (complex): "C4BP/GlcNac/LF/CRP complex", "C4b-binding protein-GlcNac-L-ficolin-CRP complex", "C4BP/GlcNAc/LF/CRP complex"
PC_CRP_LF_C1 (complex): "PC/CRP/LF/C1 complex", "properdin-CRP-L-ficolin-C1 complex", "PC/CRP/LF/C1 complex"
C4BP_PC_CRP_LF (complex): "C4BP/PC/CRP/LF complex", "C4b-binding protein-properdin-CRP-L-ficolin complex", "C4BP/PC/CRP/LF complex"
GlcNac_LF_CRP_MASP (complex): "GlcNac/LF/CRP/MASP complex", "N-acetylglucosamine-L-ficolin-CRP-MASP complex", "GlcNAc/LF/CRP/MASP complex"
PC_CRP_LF_C1_MASP (complex): "PC/CRP/LF/C1/MASP complex", "properdin-CRP-L-ficolin-C1-MASP complex", "PC/CRP/LF/C1/MASP complex"
GlcNac_LF_C1_MASP (complex): "GlcNac/LF/C1/MASP complex", "N-acetylglucosamine-L-ficolin-C1-MASP complex", "GlcNAc/LF/C1/MASP complex"
GlcNac_HF (chemical): "GlcNac/HF", "N-acetylglucosamine/H-ficolin", "GlcNAc/HF"
GlcNac_HF_MASP (complex): "GlcNac/HF/MASP complex", "N-acetylglucosamine-H-ficolin-MASP complex", "GlcNAc/HF/MASP complex"
Reason: The species were identified based on their names and the context of the Complement System model. Properdin (PC) and C-reactive protein (CRP) are proteins, while N-acetylglucosamine (GlcNac) is a chemical. L-ficolin (LF) and H-ficolin (HF) are proteins that bind to GlcNac, forming complexes. MASP (mannan-binding lectin-associated serine protease) is a protein that interacts with these complexes. C4BP (C4b-binding protein) is a protein that regulates the complement system. The complexes formed between these proteins and chemicals were identified based on their names and the reactions in the model.
Synonyms dict: {'PC': ['properdin', 'factor P', 'proproperdin'], 'PC_CRP': ['properdin-CRP complex', 'PC/CRP complex', 'properdin-C-reactive protein complex'], 'PC_CRP_C1': ['properdin-CRP-C1 complex', 'PC/CRP/C1 complex', 'properdin-C-reactive protein-C1 complex'], 'GlcNac': ['N-acetylglucosamine', 'GlcNAc', '2-acetamido-glucose'], 'GlcNac_LF': ['GlcNac/L-ficolin complex', 'N-acetylglucosamine-L-ficolin complex', 'GlcNAc/LF complex'], 'GlcNac_LF_MASP': ['GlcNac/LF/MASP complex', 'N-acetylglucosamine-L-ficolin-MASP complex', 'GlcNAc/LF/MASP complex'], 'PC_CRP_LF': ['PC/CRP/LF complex', 'properdin-CRP-L-ficolin complex', 'PC/CRP/LF complex'], 'PC_CRP_LF_MASP': ['PC/CRP/LF/MASP complex', 'properdin-CRP-L-ficolin-MASP complex', 'PC/CRP/LF/MASP complex'], 'GlcNac_LF_CRP': ['GlcNac/LF/CRP complex', 'N-acetylglucosamine-L-ficolin-CRP complex', 'GlcNAc/LF/CRP complex'], 'GlcNac_LF_CRP_C1': ['GlcNac/LF/CRP/C1 complex', 'N-acetylglucosamine-L-ficolin-CRP-C1 complex', 'GlcNAc/LF/CRP/C1 complex'], 'C4BP_PC_CRP': ['C4BP/PC/CRP complex', 'C4b-binding protein-properdin-CRP complex', 'C4BP/PC/CRP complex'], 'C4BP_GlcNac_LF_CRP': ['C4BP/GlcNac/LF/CRP complex', 'C4b-binding protein-GlcNac-L-ficolin-CRP complex', 'C4BP/GlcNAc/LF/CRP complex'], 'PC_CRP_LF_C1': ['PC/CRP/LF/C1 complex', 'properdin-CRP-L-ficolin-C1 complex', 'PC/CRP/LF/C1 complex'], 'C4BP_PC_CRP_LF': ['C4BP/PC/CRP/LF complex', 'C4b-binding protein-properdin-CRP-L-ficolin complex', 'C4BP/PC/CRP/LF complex'], 'GlcNac_LF_CRP_MASP': ['GlcNac/LF/CRP/MASP complex', 'N-acetylglucosamine-L-ficolin-CRP-MASP complex', 'GlcNAc/LF/CRP/MASP complex'], 'PC_CRP_LF_C1_MASP': ['PC/CRP/LF/C1/MASP complex', 'properdin-CRP-L-ficolin-C1-MASP complex', 'PC/CRP/LF/C1/MASP complex'], 'GlcNac_LF_C1_MASP': ['GlcNac/LF/C1/MASP complex', 'N-acetylglucosamine-L-ficolin-C1-MASP complex', 'GlcNAc/LF/C1/MASP complex'], 'GlcNac_HF': ['GlcNac/HF', 'N-acetylglucosamine/H-ficolin', 'GlcNAc/HF'], 'GlcNac_HF_MASP': ['GlcNac/HF/MASP complex', 'N-acetylglucosamine-H-ficolin-MASP complex', 'GlcNAc/HF/MASP complex']}
Evaluating 304/1075: BIOMD0000000304.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000304.txt
LLM response:
h1 (unknown): "h1", "gating variable", "ion channel parameter"
x1 (unknown): "x1", "gating variable", "ion channel parameter"
n1 (unknown): "n1", "gating variable", "ion channel parameter"
c (chemical): "calcium ion", "Ca2+", "calcium

Reason: The species h1, x1, and n1 are likely gating variables or parameters related to ion channels in the nerve cell model, but their exact nature is unclear, so they are classified as unknown. The species c is likely representing the concentration of calcium ions, which is a common chemical species in cellular models, particularly in the context of nerve cell signaling and bursting behavior.
Synonyms dict: {'h1': ['h1', 'gating variable', 'ion channel parameter'], 'x1': ['x1', 'gating variable', 'ion channel parameter'], 'n1': ['n1', 'gating variable', 'ion channel parameter'], 'c': ['calcium ion', 'Ca2+', '"calcium']}
Evaluating 305/1075: BIOMD0000000305.xml

2025-11-20 12:28:57,691 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:28:57,703 - WARNING - Skipping BIOMD0000000306.xml - no results generated
2025-11-20 12:28:57,707 - WARNING - Skipping BIOMD0000000307.xml - no results generated
2025-11-20 12:28:57,711 - WARNING - Skipping BIOMD0000000308.xml - no results generated
2025-11-20 12:28:57,715 - WARNING - Skipping BIOMD0000000309.xml - no results generated
2025-11-20 12:28:57,720 - WARNING - Skipping BIOMD0000000310.xml - no results generated
2025-11-20 12:28:57,723 - WARNING - Skipping BIOMD0000000311.xml - no results generated
2025-11-20 12:28:57,726 - WARNING - Skipping BIOMD0000000312.xml - no results generated
2025-11-20 12:28:57,733 - WARNING - Skipping BIOMD0000000313.xml - no results generated
2025-11-20 12:28:57,739 - WARNING - Skipping BIOMD0000000314.xml - no results generated
2025-11-20 12:28:57,749 - WARNING - Skipping BIOMD0000000315.xml - no results generated
2025-11-20 12:28:57,753 - WARNING - Skipping BIOMD0000000316.xml - no results generated
2025-11-20 12:28:57,757 - WARNING - Skipping BIOMD0000000317.xml - no results generated
2025-11-20 12:28:57,765 - WARNING - Skipping BIOMD0000000318.xml - no results generated
2025-11-20 12:28:57,768 - WARNING - Skipping BIOMD0000000319.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000305.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
S1 (protein): "myosin V", "myosin-V", "myosin 5"
Pi_ (chemical): "inorganic phosphate", "phosphate", "Pi"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Reason: The species ATP and ADP are clearly chemicals as they are involved in energy transfer reactions. Pi_ is also a chemical, commonly referred to as inorganic phosphate. S1 is a protein, specifically a state of myosin V, as indicated by the model notes and reactions.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'S1': ['myosin V', 'myosin-V', 'myosin 5'], 'Pi_': ['inorganic phosphate', 'phosphate', 'Pi'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"]}
Evaluating 306/1075: BIOMD0000000306.xml
Evaluating 307/1075: BIOMD0000000307.xml
Evaluating 308/1075: BIOMD0000000308.xml
Evaluating 309/1075: BIOMD0000000309.xml
Evaluating 310/1075: BIOMD0000000310.xml
Evaluating 311/1075: BIOMD0000000311.xml
Evaluating 312/1075: BIOMD0000000312.xml
Evaluating 313/1075: BIOMD0000000313.xml
Evaluating 314/1075: BIOMD0000000314.xml
Evaluating 315/1075: BIOMD0000000315.xml
Evaluating 316/1075: BIOMD0000000316.xml
Evaluating 317/1075: BIOMD0000000317.xml
Evaluating 318/1075: BIOMD0000000318.xml
Evaluating 319/1075: BIOMD0000000319.xml
Evaluating 320/1075: BIOMD0000000320.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000320.txt
LLM response:
A_dopa (chemical): "L-dopa", "levodopa", "3,4-dihydroxyphenylalanine"
C_dopa (chemical): "3-O-methyldopa", "3-OMD", "3-methoxytyrosine"
Reason: A_dopa is identified as L-dopa, a chemical compound, based on the model description and notes. C_dopa is identified as 3-O-methyldopa, a metabolite of L-dopa, based on the reaction and notes. Both are classified as chemicals due to their role in the pharmacokinetic model.
Synonyms dict: {'A_dopa': ['L-dopa', 'levodopa', '3,4-dihydroxyphenylalanine'], 'C_dopa': ['3-O-methyldopa', '3-OMD', '3-methoxytyrosine']}
Evaluating 321/1075: BIOMD0000000321.xml

2025-11-20 12:29:01,356 - WARNING - Skipping BIOMD0000000322.xml - no results generated
2025-11-20 12:29:01,360 - WARNING - Skipping BIOMD0000000323.xml - no results generated
2025-11-20 12:29:01,363 - WARNING - Skipping BIOMD0000000324.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000321.txt
LLM response:
A_dopa (chemical): "L-dopa", "levodopa", "3,4-dihydroxyphenylalanine"
C_dopa (chemical): "3-OMD", "3-O-methyldopa", "3-methoxytyrosine"
Reason: A_dopa is identified as L-dopa, a chemical compound, based on the model description and notes. C_dopa is identified as 3-OMD, a metabolite of L-dopa, which is also a chemical compound. The notes and reactions in the model support these identifications, with A_dopa being administered and converted into C_dopa through various reactions.
Synonyms dict: {'A_dopa': ['L-dopa', 'levodopa', '3,4-dihydroxyphenylalanine'], 'C_dopa': ['3-OMD', '3-O-methyldopa', '3-methoxytyrosine']}
Evaluating 322/1075: BIOMD0000000322.xml
Evaluating 323/1075: BIOMD0000000323.xml
Evaluating 324/1075: BIOMD0000000324.xml
Evaluating 325/1075: BIOMD0000000325.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000325.txt
LLM response:
L (chemical): "ligand", "signaling ligand", "synthetic ligand"
C (complex): "ligand-receptor complex", "receptor-ligand complex", "L-R complex"
X (complex): "ligand-receptor complex bound to inactive transcription factor", "L-R-I complex", "transcription factor-ligand-receptor complex"
Reason: L is a chemical as it is referred to as a "ligand" in the model notes, C is a complex as it is formed by the binding of L and R, and X is also a complex as it is formed by the binding of C and I, an inactive transcription factor. The names provided are based on the descriptions in the model notes and the reactions in which each species is involved.
Synonyms dict: {'L': ['ligand', 'signaling ligand', 'synthetic ligand'], 'C': ['ligand-receptor complex', 'receptor-ligand complex', 'L-R complex'], 'X': ['ligand-receptor complex bound to inactive transcription factor', 'L-R-I complex', 'transcription factor-ligand-receptor complex']}
Evaluating 326/1075: BIOMD0000000326.xml

2025-11-20 12:29:10,903 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000326.txt
LLM response:
Ca2_buff (chemical): "calcium ion", "Ca2+", "calcium buffer"
Ca2_free (chemical): "calcium ion", "Ca2+", "free calcium"
G_GTP (protein): "G-protein", "GTP-bound G-protein", "heterotrimeric G-protein"
Ga_GTP (protein): "G-alpha subunit", "GTP-bound G-alpha", "Gα"
Ga_GDP (protein): "G-alpha subunit", "GDP-bound G-alpha", "Gα-GDP"
Ga_GTP_PDE_a_Ga_GTP (complex): "PDE-Gα complex", "Gα-PDE complex", "photoreceptor complex"
Ga_GTP_a_PDE_a_Ga_GTP (complex): "PDE-Gα complex", "Gα-PDE complex", "photoreceptor complex"
Ops_G_GTP (complex): "rhodopsin-GTP complex", "Rho-GTP complex", "opsin-GTP complex"
PDE_Ga_GTP (complex): "PDE-Gα complex", "Gα-PDE complex", "photoreceptor complex"
PDE_a_Ga_GTP (complex): "PDE-Gα complex", "Gα-PDE complex", "photoreceptor complex"
R0_G_GTP (protein): "R0 protein", "R0-GTP complex", "rod outer segment protein"
R1_G_GTP (protein): "R1 protein", "R1-GTP complex", "rod outer segment protein"
R2_G_GTP (protein): "R2 protein", "R2-GTP complex", "rod outer segment protein"
R3_G_GTP (protein): "R3 protein", "R3-GTP complex", "rod outer segment protein"
R4_G_GTP (protein): "R4 protein", "R4-GTP complex", "rod outer segment protein"
R5_G_GTP (protein): "R5 protein", "R5-GTP complex", "rod outer segment protein"
R6_G_GTP (protein): "R6 protein", "R6-GTP complex", "rod outer segment protein"
RGS_Ga_GTP_a_PDE_a_Ga_GTP (complex): "RGS-PDE-Gα complex", "Gα-PDE-RGS complex", "photoreceptor complex"
RGS_PDE_a_Ga_GTP (complex): "RGS-PDE complex", "PDE-RGS complex", "photoreceptor complex"
Rec_wCa2_RK (protein): "recoverin", "Ca2+-recoverin complex", "RK-recoverin complex"
cGMP (chemical): "cyclic GMP", "guanosine 3',5'-cyclic monophosphate", "cGMP signaling molecule"

Reason: The species were identified based on their names and the context of the phototransduction model. G-proteins, PDE, and RGS are known proteins involved in phototransduction, while Ca2+ and cGMP are chemical signaling molecules. The complexes were identified based on their component proteins and the reactions they participate in. The R0-R6 proteins are likely components of the rod outer segment, but their specific functions and names are not well-defined in the model. Recoverin is a known protein that binds to Ca2+ and RK.
Synonyms dict: {'Ca2_buff': ['calcium ion', 'Ca2+', 'calcium buffer'], 'Ca2_free': ['calcium ion', 'Ca2+', 'free calcium'], 'G_GTP': ['G-protein', 'GTP-bound G-protein', 'heterotrimeric G-protein'], 'Ga_GTP': ['G-alpha subunit', 'GTP-bound G-alpha', 'Gα'], 'Ga_GDP': ['G-alpha subunit', 'GDP-bound G-alpha', 'Gα-GDP'], 'Ga_GTP_PDE_a_Ga_GTP': ['PDE-Gα complex', 'Gα-PDE complex', 'photoreceptor complex'], 'Ga_GTP_a_PDE_a_Ga_GTP': ['PDE-Gα complex', 'Gα-PDE complex', 'photoreceptor complex'], 'Ops_G_GTP': ['rhodopsin-GTP complex', 'Rho-GTP complex', 'opsin-GTP complex'], 'PDE_Ga_GTP': ['PDE-Gα complex', 'Gα-PDE complex', 'photoreceptor complex'], 'PDE_a_Ga_GTP': ['PDE-Gα complex', 'Gα-PDE complex', 'photoreceptor complex'], 'R0_G_GTP': ['R0 protein', 'R0-GTP complex', 'rod outer segment protein'], 'R1_G_GTP': ['R1 protein', 'R1-GTP complex', 'rod outer segment protein'], 'R2_G_GTP': ['R2 protein', 'R2-GTP complex', 'rod outer segment protein'], 'R3_G_GTP': ['R3 protein', 'R3-GTP complex', 'rod outer segment protein'], 'R4_G_GTP': ['R4 protein', 'R4-GTP complex', 'rod outer segment protein'], 'R5_G_GTP': ['R5 protein', 'R5-GTP complex', 'rod outer segment protein'], 'R6_G_GTP': ['R6 protein', 'R6-GTP complex', 'rod outer segment protein'], 'RGS_Ga_GTP_a_PDE_a_Ga_GTP': ['RGS-PDE-Gα complex', 'Gα-PDE-RGS complex', 'photoreceptor complex'], 'RGS_PDE_a_Ga_GTP': ['RGS-PDE complex', 'PDE-RGS complex', 'photoreceptor complex'], 'Rec_wCa2_RK': ['recoverin', 'Ca2+-recoverin complex', 'RK-recoverin complex'], 'cGMP': ['cyclic GMP', "guanosine 3',5'-cyclic monophosphate", 'cGMP signaling molecule']}
Evaluating 327/1075: BIOMD0000000327.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000327.txt
LLM response:
bb (chemical): "bicarbonate", "hydrogen carbonate", "HCO3-"
cb (chemical): "chloride", "chloride ion", "Cl-"
nb (chemical): "sodium", "sodium ion", "Na+"
bi (chemical): "bicarbonate", "hydrogen carbonate", "HCO3-"
ci (chemical): "chloride", "chloride ion", "Cl-"
ni (chemical): "sodium", "sodium ion", "Na+"
bl (chemical): "bicarbonate", "hydrogen carbonate", "HCO3-"
cl (chemical): "chloride", "chloride ion", "Cl-"
Reason: All species have display names that correspond to common chemical ions, and the model is a mathematical representation of pancreatic duct cell secretion, which involves the transport of these ions. The reactions and notes also support the identification of these species as chemical ions, with no evidence of genes, proteins, or complexes being involved. The standardized names and synonyms provided are based on common chemical nomenclature and the display names given in the model.
Synonyms dict: {'bb': ['bicarbonate', 'hydrogen carbonate', 'HCO3-'], 'cb': ['chloride', 'chloride ion', 'Cl-'], 'nb': ['sodium', 'sodium ion', 'Na+'], 'bi': ['bicarbonate', 'hydrogen carbonate', 'HCO3-'], 'ci': ['chloride', 'chloride ion', 'Cl-'], 'ni': ['sodium', 'sodium ion', 'Na+'], 'bl': ['bicarbonate', 'hydrogen carbonate', 'HCO3-'], 'cl': ['chloride', 'chloride ion', 'Cl-']}
Evaluating 328/1075: BIOMD0000000328.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000328.txt
LLM response:
AS_m (chemical): "atorvastatin", "Lipitor", "atorvastatin calcium"
ASoOH_m (chemical): "o-hydroxyatorvastatin", "atorvastatin o-hydroxide", "o-hydroxy atorvastatin"
ASpOH_m (chemical): "p-hydroxyatorvastatin", "atorvastatin p-hydroxide", "p-hydroxy atorvastatin"
AS_c (chemical): "atorvastatin", "Lipitor", "atorvastatin calcium"
ASpOH_c (chemical): "p-hydroxyatorvastatin", "atorvastatin p-hydroxide", "p-hydroxy atorvastatin"
ASoOH_c (chemical): "o-hydroxyatorvastatin", "atorvastatin o-hydroxide", "o-hydroxy atorvastatin"
ASpOH_b (chemical): "p-hydroxyatorvastatin", "atorvastatin p-hydroxide", "p-hydroxy atorvastatin"
ASoOH_b (chemical): "o-hydroxyatorvastatin", "atorvastatin o-hydroxide", "o-hydroxy atorvastatin"
AS_b (chemical): "atorvastatin", "Lipitor", "atorvastatin calcium"
Reason: The species are all related to atorvastatin, a chemical compound, and its metabolites. The suffixes _m, _c, and _b likely indicate different compartments or locations (e.g., microsomal, cytosolic, and blood), but do not change the entity type. The prefixes AS, ASoOH, and ASpOH indicate the specific metabolite or form of atorvastatin.
Synonyms dict: {'AS_m': ['atorvastatin', 'Lipitor', 'atorvastatin calcium'], 'ASoOH_m': ['o-hydroxyatorvastatin', 'atorvastatin o-hydroxide', 'o-hydroxy atorvastatin'], 'ASpOH_m': ['p-hydroxyatorvastatin', 'atorvastatin p-hydroxide', 'p-hydroxy atorvastatin'], 'AS_c': ['atorvastatin', 'Lipitor', 'atorvastatin calcium'], 'ASpOH_c': ['p-hydroxyatorvastatin', 'atorvastatin p-hydroxide', 'p-hydroxy atorvastatin'], 'ASoOH_c': ['o-hydroxyatorvastatin', 'atorvastatin o-hydroxide', 'o-hydroxy atorvastatin'], 'ASpOH_b': ['p-hydroxyatorvastatin', 'atorvastatin p-hydroxide', 'p-hydroxy atorvastatin'], 'ASoOH_b': ['o-hydroxyatorvastatin', 'atorvastatin o-hydroxide', 'o-hydroxy atorvastatin'], 'AS_b': ['atorvastatin', 'Lipitor', 'atorvastatin calcium']}
Evaluating 329/1075: BIOMD0000000329.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000329.txt
LLM response:
c (chemical): "Calcium", "Ca2+", "Calcium ion"
Reason: The display name "Calcium" and the context of the model "Kummer2000 - Oscillations in Calcium Signalling" indicate that species c is a chemical entity, specifically the calcium ion, which is a common signaling molecule in biological systems.
Synonyms dict: {'c': ['Calcium', 'Ca2+', 'Calcium ion']}
Evaluating 330/1075: BIOMD0000000330.xml

2025-11-20 12:29:20,528 - WARNING - Skipping BIOMD0000000331.xml - no results generated
2025-11-20 12:29:20,557 - WARNING - Skipping BIOMD0000000332.xml - no results generated
2025-11-20 12:29:20,575 - WARNING - Skipping BIOMD0000000333.xml - no results generated
2025-11-20 12:29:20,600 - WARNING - Skipping BIOMD0000000334.xml - no results generated
2025-11-20 12:29:20,611 - WARNING - Skipping BIOMD0000000335.xml - no results generated
2025-11-20 12:29:20,619 - WARNING - Skipping BIOMD0000000336.xml - no results generated
2025-11-20 12:29:20,622 - WARNING - Skipping BIOMD0000000337.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000330.txt
LLM response:
Ca_cyt (chemical): "Calcium ion", "Ca2+", "Calcium"
Ca_ER (chemical): "Calcium ion", "Ca2+", "Endoplasmic reticulum calcium"
Ca_mit (chemical): "Calcium ion", "Ca2+", "Mitochondrial calcium"
Reason: All three species are related to calcium, and based on their names and the model context, they appear to represent different locations or compartments of calcium ions within the cell, such as the cytosol (Ca_cyt), endoplasmic reticulum (Ca_ER), and mitochondria (Ca_mit), indicating they are all chemicals, specifically calcium ions in different cellular locations.
Synonyms dict: {'Ca_cyt': ['Calcium ion', 'Ca2+', 'Calcium'], 'Ca_ER': ['Calcium ion', 'Ca2+', 'Endoplasmic reticulum calcium'], 'Ca_mit': ['Calcium ion', 'Ca2+', 'Mitochondrial calcium']}
Evaluating 331/1075: BIOMD0000000331.xml
Evaluating 332/1075: BIOMD0000000332.xml
Evaluating 333/1075: BIOMD0000000333.xml
Evaluating 334/1075: BIOMD0000000334.xml
Evaluating 335/1075: BIOMD0000000335.xml
Evaluating 336/1075: BIOMD0000000336.xml
Evaluating 337/1075: BIOMD0000000337.xml
Evaluating 338/1075: BIOMD0000000338.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000338.txt
LLM response:
ATIII_Heparin (complex): "antithrombin III-heparin complex", "ATIII-heparin", "antithrombin-heparin"
Xa_ATIII_Heparin (complex): "factor Xa-antithrombin III-heparin complex", "Xa-ATIII-heparin", "factor Xa-ATIII-heparin"
C_warf (chemical): "warfarin", "coumarin", "3-(alpha-acetonylbenzyl)-4-hydroxycoumarin"
IIa_ATIII_Heparin (complex): "factor IIa-antithrombin III-heparin complex", "thrombin-ATIII-heparin", "factor IIa-ATIII-heparin"
A_warf (chemical): "warfarin", "acacen", "4-hydroxycoumarin"
IXa_ATIII_Heparin (complex): "factor IXa-antithrombin III-heparin complex", "factor IXa-ATIII-heparin", "Christmas factor-ATIII-heparin"
Reason: The species are annotated based on their display names and the context of the blood coagulation model. ATIII_Heparin and its complexes with various factors (Xa, IIa, IXa) are classified as complexes because they involve the binding of antithrombin III with heparin and other coagulation factors. C_warf and A_warf are classified as chemicals because they are related to warfarin, an anticoagulant medication. The standardized names and synonyms provided are based on common names and abbreviations used in the field of coagulation and pharmacology.
Synonyms dict: {'ATIII_Heparin': ['antithrombin III-heparin complex', 'ATIII-heparin', 'antithrombin-heparin'], 'Xa_ATIII_Heparin': ['factor Xa-antithrombin III-heparin complex', 'Xa-ATIII-heparin', 'factor Xa-ATIII-heparin'], 'C_warf': ['warfarin', 'coumarin', '3-(alpha-acetonylbenzyl)-4-hydroxycoumarin'], 'IIa_ATIII_Heparin': ['factor IIa-antithrombin III-heparin complex', 'thrombin-ATIII-heparin', 'factor IIa-ATIII-heparin'], 'A_warf': ['warfarin', 'acacen', '4-hydroxycoumarin'], 'IXa_ATIII_Heparin': ['factor IXa-antithrombin III-heparin complex', 'factor IXa-ATIII-heparin', 'Christmas factor-ATIII-heparin']}
Evaluating 339/1075: BIOMD0000000339.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000339.txt
LLM response:
ATIII_Heparin (complex): "antithrombin III-heparin complex", "ATIII-heparin", "antithrombin-heparin"
Xa_ATIII_Heparin (complex): "factor Xa-antithrombin III-heparin complex", "Xa-ATIII-heparin", "factor Xa-ATIII-heparin"
C_warf (unknown): "C_warf", "warfarin target", "coagulation factor"
IIa_ATIII_Heparin (complex): "factor IIa-antithrombin III-heparin complex", "thrombin-ATIII-heparin", "factor IIa-ATIII-heparin"
A_warf (unknown): "A_warf", "warfarin target", "coagulation factor"
IXa_ATIII_Heparin (complex): "factor IXa-antithrombin III-heparin complex", "factor IXa-ATIII-heparin", "factor IXa-ATIII-heparin complex"
Reason: The species are annotated based on the model's context, which is a blood coagulation model. ATIII_Heparin, Xa_ATIII_Heparin, IIa_ATIII_Heparin, and IXa_ATIII_Heparin are complexes because they involve the binding of antithrombin III (a protein) with heparin (a chemical) and other coagulation factors. C_warf and A_warf are unknown because their display names do not provide enough information to determine their entity types, but based on the model's context, they might be related to warfarin, a chemical used as an anticoagulant.
Synonyms dict: {'ATIII_Heparin': ['antithrombin III-heparin complex', 'ATIII-heparin', 'antithrombin-heparin'], 'Xa_ATIII_Heparin': ['factor Xa-antithrombin III-heparin complex', 'Xa-ATIII-heparin', 'factor Xa-ATIII-heparin'], 'C_warf': ['C_warf', 'warfarin target', 'coagulation factor'], 'IIa_ATIII_Heparin': ['factor IIa-antithrombin III-heparin complex', 'thrombin-ATIII-heparin', 'factor IIa-ATIII-heparin'], 'A_warf': ['A_warf', 'warfarin target', 'coagulation factor'], 'IXa_ATIII_Heparin': ['factor IXa-antithrombin III-heparin complex', 'factor IXa-ATIII-heparin', 'factor IXa-ATIII-heparin complex']}
Evaluating 340/1075: BIOMD0000000340.xml

2025-11-20 12:29:32,331 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000340.txt
LLM response:
ATIII_Heparin (protein): "Antithrombin III", "Antithrombin", "ATIII"
Xa_ATIII_Heparin (complex): "Xa-Antithrombin III-Heparin complex", "Factor Xa-Antithrombin III-Heparin", "Xa-ATIII-Heparin"
C_warf (chemical): "Warfarin", "Coumadin", "Jantoven"
IIa_ATIII_Heparin (complex): "Thrombin-Antithrombin III-Heparin complex", "IIa-Antithrombin III-Heparin", "Thrombin-ATIII-Heparin"
IXa_ATIII_Heparin (complex): "Factor IXa-Antithrombin III-Heparin complex", "IXa-Antithrombin III-Heparin", "Factor IXa-ATIII-Heparin"
A_warf (unknown): "UNK"
Xa (protein): "Factor Xa", "Stuart-Prower factor", "Coagulation factor Xa"
IIa (protein): "Thrombin", "Coagulation factor IIa", "Fibrinogenase"
IXa (protein): "Factor IXa", "Coagulation factor IXa", "Christmas factor"
Reason: The model is a blood coagulation model, and the species are mostly coagulation factors or complexes involved in the coagulation cascade. ATIII_Heparin is a protein because Antithrombin III is a protein that binds to heparin. Xa_ATIII_Heparin, IIa_ATIII_Heparin, and IXa_ATIII_Heparin are complexes because they are formed by the binding of coagulation factors to Antithrombin III and heparin. C_warf is a chemical because warfarin is a small molecule anticoagulant. A_warf is unknown because there is not enough information to determine its entity type. Xa, IIa, and IXa are proteins because they are coagulation factors.
Synonyms dict: {'ATIII_Heparin': ['Antithrombin III', 'Antithrombin', 'ATIII'], 'Xa_ATIII_Heparin': ['Xa-Antithrombin III-Heparin complex', 'Factor Xa-Antithrombin III-Heparin', 'Xa-ATIII-Heparin'], 'C_warf': ['Warfarin', 'Coumadin', 'Jantoven'], 'IIa_ATIII_Heparin': ['Thrombin-Antithrombin III-Heparin complex', 'IIa-Antithrombin III-Heparin', 'Thrombin-ATIII-Heparin'], 'IXa_ATIII_Heparin': ['Factor IXa-Antithrombin III-Heparin complex', 'IXa-Antithrombin III-Heparin', 'Factor IXa-ATIII-Heparin'], 'A_warf': ['UNK'], 'Xa': ['Factor Xa', 'Stuart-Prower factor', 'Coagulation factor Xa'], 'IIa': ['Thrombin', 'Coagulation factor IIa', 'Fibrinogenase'], 'IXa': ['Factor IXa', 'Coagulation factor IXa', 'Christmas factor']}
Evaluating 341/1075: BIOMD0000000341.xml

2025-11-20 12:29:34,224 - WARNING - Skipping BIOMD0000000342.xml - no results generated
2025-11-20 12:29:34,229 - WARNING - Skipping BIOMD0000000343.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000341.txt
LLM response:
G (chemical): "glucose", "D-glucose", "blood glucose"
B (unknown): "beta-cell mass", "cell mass", "mass"
I (protein): "insulin", "human insulin", "insulin hormone"
Reason: G is a chemical as it refers to glucose, a simple sugar and a common energy source for cells. B is unknown because it represents beta-cell mass, which is a measure of the number of beta cells in the pancreas, rather than a specific chemical, gene, or protein. I is a protein as insulin is a hormone produced by the pancreas that regulates blood sugar levels.
Synonyms dict: {'G': ['glucose', 'D-glucose', 'blood glucose'], 'B': ['beta-cell mass', 'cell mass', 'mass'], 'I': ['insulin', 'human insulin', 'insulin hormone']}
Evaluating 342/1075: BIOMD0000000342.xml
Evaluating 343/1075: BIOMD0000000343.xml
Evaluating 344/1075: BIOMD0000000344.xml

2025-11-20 12:29:35,647 - WARNING - Skipping BIOMD0000000345.xml - no results generated
2025-11-20 12:29:35,649 - WARNING - Skipping BIOMD0000000346.xml - no results generated
2025-11-20 12:29:35,661 - WARNING - Skipping BIOMD0000000347.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000344.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "adenosine 5'-triphosphate", "ATP"
ADP (chemical): "adenosine diphosphate", "adenosine 5'-diphosphate", "ADP"
Reason: Both ATP and ADP are well-known chemical compounds that play crucial roles in energy transfer within cells, which is consistent with their involvement in the reactions listed in the model, particularly in the context of protein homeostasis and the activity of chaperones like Hsp70 and Hsp90.
Synonyms dict: {'ATP': ['adenosine triphosphate', "adenosine 5'-triphosphate", 'ATP'], 'ADP': ['adenosine diphosphate', "adenosine 5'-diphosphate", 'ADP']}
Evaluating 345/1075: BIOMD0000000345.xml
Evaluating 346/1075: BIOMD0000000346.xml
Evaluating 347/1075: BIOMD0000000347.xml
Evaluating 348/1075: BIOMD0000000348.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000348.txt
LLM response:
G3P (chemical): "glyceraldehyde 3-phosphate", "G3P", "3-phosphoglyceraldehyde"
PYR (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
NADHm (chemical): "NADH", "nicotinamide adenine dinucleotide", "reduced nicotinamide adenine dinucleotide"
NADHc (chemical): "NADH", "nicotinamide adenine dinucleotide", "reduced nicotinamide adenine dinucleotide"
Cam (chemical): "calcium", "Ca2+", "calcium ion"

Reason: The species are identified based on their display names and the context of the model, which is a mathematical model of beta-cell sensitivity to glucose. G3P, PYR, ATP, NADHm, and NADHc are all chemical species involved in glucose metabolism, while Cam is likely a representation of calcium ions, which play a role in cellular signaling and metabolism. The standardized names and synonyms provided are based on common usage in biochemistry and the likelihood of each species being represented by a particular name. NADHm and NADHc are likely representing NADH in different cellular compartments (mitochondrial and cytosolic, respectively), but are both classified as the same chemical species.
Synonyms dict: {'G3P': ['glyceraldehyde 3-phosphate', 'G3P', '3-phosphoglyceraldehyde'], 'PYR': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'NADHm': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced nicotinamide adenine dinucleotide'], 'NADHc': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced nicotinamide adenine dinucleotide'], 'Cam': ['calcium', 'Ca2+', 'calcium ion']}
Evaluating 349/1075: BIOMD0000000349.xml

2025-11-20 12:29:42,588 - WARNING - Skipping BIOMD0000000350.xml - no results generated
2025-11-20 12:29:42,593 - WARNING - Skipping BIOMD0000000351.xml - no results generated
2025-11-20 12:29:42,598 - WARNING - Skipping BIOMD0000000352.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000349.txt
LLM response:
G3P (chemical): "glyceraldehyde-3-phosphate", "G3P", "3-phosphoglyceraldehyde"
PYR (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
NADHm (chemical): "NADH", "nicotinamide adenine dinucleotide", "reduced nicotinamide adenine dinucleotide"
NADHc (chemical): "NADH", "nicotinamide adenine dinucleotide", "reduced nicotinamide adenine dinucleotide"
Cam (chemical): "calcium", "Ca2+", "calcium ion"

Reason: The species are identified based on their display names and the context of the model, which is a mathematical model of beta-cell sensitivity to glucose. G3P, PYR, ATP, NADHm, and NADHc are all chemicals involved in cellular metabolism, with G3P being an intermediate in glycolysis, PYR being the end product of glycolysis, ATP being the primary energy currency of the cell, and NADH being a coenzyme involved in redox reactions. Cam is likely calcium, which plays a crucial role in cellular signaling and metabolism. The suffixes 'm' and 'c' in NADHm and NADHc likely indicate mitochondrial and cytoplasmic compartments, respectively, but do not change the fundamental identity of the species as NADH.
Synonyms dict: {'G3P': ['glyceraldehyde-3-phosphate', 'G3P', '3-phosphoglyceraldehyde'], 'PYR': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'NADHm': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced nicotinamide adenine dinucleotide'], 'NADHc': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced nicotinamide adenine dinucleotide'], 'Cam': ['calcium', 'Ca2+', 'calcium ion']}
Evaluating 350/1075: BIOMD0000000350.xml
Evaluating 351/1075: BIOMD0000000351.xml
Evaluating 352/1075: BIOMD0000000352.xml
Evaluating 353/1075: BIOMD0000000353.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000353.txt
LLM response:
cpd_C00080_CY (chemical): "Hydrogen ion", "Proton", "H+"
cpd_C00208_CY (chemical): "Maltose", "Malt sugar", "D-Maltose"
cpd_C00208_CS (chemical): "Maltose", "Malt sugar", "D-Maltose"
cpd_C01835_CS (chemical): "Maltotriose", "Maltotriose sugar", "3-α-D-Glucosylmaltose"
cpd_G00343_CS (chemical): "Maltopentaose", "Maltopentaose sugar", "5-α-D-Glucosylmaltose"
cpd_C00031_CS (chemical): "D-Glucose", "Glucose", "Dextrose"
cpd_C00031_CY (chemical): "D-Glucose", "Glucose", "Dextrose"
cpd_C00002tot_CY (chemical): "ATP", "Adenosine triphosphate", "Adenosine 5'-triphosphate"
cpd_C00008tot_CY (chemical): "ADP", "Adenosine diphosphate", "Adenosine 5'-diphosphate"
cpd_C00009tot_CY (chemical): "Orthophosphate", "Phosphate", "Inorganic phosphate"
cpd_C00051_CY (chemical): "Glutathione", "Reduced glutathione", "GSH"
cpd_C00660tot_CY (chemical): "D-Glucose-1,6-bisphosphate", "Glucose-1,6-bisphosphate", "G16BP"
cpd_C03339tot_CY (chemical): "2,3-Bisphosphoglycerate", "2,3-BPG", "2,3-Diphosphoglycerate"
cpd_C00103tot_CY (chemical): "G1P", "Glucose-1-phosphate", "D-Glucose-1-phosphate"
cpd_C00092tot_CY (chemical): "G6P", "Glucose-6-phosphate", "D-Glucose-6-phosphate"
Reason: The entity types are determined based on the display names and the context of the model, which is a kinetic model of chloroplastic starch degradation. The species are identified as chemicals based on their display names, which are common names for metabolites and biochemical compounds. The standardized names and synonyms are provided based on common usage in biochemistry and the likelihood of each name being correct.
Synonyms dict: {'cpd_C00080_CY': ['Hydrogen ion', 'Proton', 'H+'], 'cpd_C00208_CY': ['Maltose', 'Malt sugar', 'D-Maltose'], 'cpd_C00208_CS': ['Maltose', 'Malt sugar', 'D-Maltose'], 'cpd_C01835_CS': ['Maltotriose', 'Maltotriose sugar', '3-α-D-Glucosylmaltose'], 'cpd_G00343_CS': ['Maltopentaose', 'Maltopentaose sugar', '5-α-D-Glucosylmaltose'], 'cpd_C00031_CS': ['D-Glucose', 'Glucose', 'Dextrose'], 'cpd_C00031_CY': ['D-Glucose', 'Glucose', 'Dextrose'], 'cpd_C00002tot_CY': ['ATP', 'Adenosine triphosphate', "Adenosine 5'-triphosphate"], 'cpd_C00008tot_CY': ['ADP', 'Adenosine diphosphate', "Adenosine 5'-diphosphate"], 'cpd_C00009tot_CY': ['Orthophosphate', 'Phosphate', 'Inorganic phosphate'], 'cpd_C00051_CY': ['Glutathione', 'Reduced glutathione', 'GSH'], 'cpd_C00660tot_CY': ['D-Glucose-1,6-bisphosphate', 'Glucose-1,6-bisphosphate', 'G16BP'], 'cpd_C03339tot_CY': ['2,3-Bisphosphoglycerate', '2,3-BPG', '2,3-Diphosphoglycerate'], 'cpd_C00103tot_CY': ['G1P', 'Glucose-1-phosphate', 'D-Glucose-1-phosphate'], 'cpd_C00092tot_CY': ['G6P', 'Glucose-6-phosphate', 'D-Glucose-6-phosphate']}
Evaluating 354/1075: BIOMD0000000354.xml

2025-11-20 12:29:50,606 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000354.txt
LLM response:
CaI (chemical): "calcium ion", "Ca2+", "calcium(2+)"
IP3 (chemical): "inositol trisphosphate", "D-myo-inositol 1,4,5-trisphosphate", "IP3"
CaO (unknown): "UNK"
CaS (chemical): "calcium ion", "Ca2+", "calcium(2+)"
CaM (protein): "calmodulin", "calcium-modulated protein", "CaM"

Reason: CaI and CaS are likely calcium ions due to their involvement in calcium signaling and the model's focus on calcium levels. IP3 is a well-known chemical involved in signaling pathways. CaM is a protein that binds to calcium ions and plays a role in signaling. CaO is unknown due to the lack of information about its reactants or products in the model.
Synonyms dict: {'CaI': ['calcium ion', 'Ca2+', 'calcium(2+)'], 'IP3': ['inositol trisphosphate', 'D-myo-inositol 1,4,5-trisphosphate', 'IP3'], 'CaO': ['UNK'], 'CaS': ['calcium ion', 'Ca2+', 'calcium(2+)'], 'CaM': ['calmodulin', 'calcium-modulated protein', 'CaM']}
Evaluating 355/1075: BIOMD0000000355.xml

2025-11-20 12:29:53,939 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:29:53,970 - WARNING - Skipping BIOMD0000000356.xml - no results generated
2025-11-20 12:29:53,975 - WARNING - Skipping BIOMD0000000357.xml - no results generated
2025-11-20 12:29:53,979 - WARNING - Skipping BIOMD0000000358.xml - no results generated
2025-11-20 12:29:53,983 - WARNING - Skipping BIOMD0000000359.xml - no results generated
2025-11-20 12:29:53,988 - WARNING - Skipping BIOMD0000000360.xml - no results generated
2025-11-20 12:29:53,991 - WARNING - Skipping BIOMD0000000361.xml - no results generated
2025-11-20 12:29:54,002 - WARNING - Skipping BIOMD0000000362.xml - no results generated
2025-11-20 12:29:54,004 - WARNING - Skipping BIOMD0000000363.xml - no results generated
2025-11-20 12:29:54,010 - WARNING - Skipping BIOMD0000000364.xml - no results generated
2025-11-20 12:29:54,017 - WARNING - Skipping BIOMD0000000365.xml - no results generated
2025-11-20 12:29:54,021 - WARNING - Skipping BIOMD0000000366.xml - no results generated
2025-11-20 12:29:54,022 - WARNING - Skipping BIOMD0000000367.xml - no results generated
2025-11-20 12:29:54,024 - WARNING - Skipping BIOMD0000000368.xml - no results generated
2025-11-20 12:29:54,026 - WARNING - Skipping BIOMD0000000369.xml - no results generated
2025-11-20 12:29:54,036 - WARNING - Skipping BIOMD0000000370.xml - no results generated
2025-11-20 12:29:54,039 - WARNING - Skipping BIOMD0000000371.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000355.txt
LLM response:
CaI (chemical): "calcium ion", "Ca2+", "calcium"
IP3 (chemical): "inositol trisphosphate", "IP3", "myo-inositol 1,4,5-trisphosphate"
mwd6b792d8_c983_42c1_b3bc_2494d6a3363e (chemical): "calcium oxide", "CaO", "calcium monoxide"
mw013a7c64_a9ec_483c_b3b8_ed658337ee95 (protein): "calmodulin", "CaM", "calcium-modulated protein"
CaS (chemical): "calcium", "calcium ion", "Ca2+"

Reason: The model is related to calcium signaling, and the display names suggest the species are related to calcium. CaI and CaS are likely calcium ions in different locations or states. IP3 is a known second messenger in calcium signaling. The long identifier mwd6b792d8_c983_42c1_b3bc_2494d6a3363e is assigned the display name "CaO", which is likely an abbreviation for calcium oxide, but in the context of the model, it may represent a calcium-related species. mw013a7c64_a9ec_483c_b3b8_ed658337ee95 is assigned the display name "CaM", which is a common abbreviation for calmodulin, a calcium-binding protein.
Synonyms dict: {'CaI': ['calcium ion', 'Ca2+', 'calcium'], 'IP3': ['inositol trisphosphate', 'IP3', 'myo-inositol 1,4,5-trisphosphate'], 'mwd6b792d8_c983_42c1_b3bc_2494d6a3363e': ['calcium oxide', 'CaO', 'calcium monoxide'], 'mw013a7c64_a9ec_483c_b3b8_ed658337ee95': ['calmodulin', 'CaM', 'calcium-modulated protein'], 'CaS': ['calcium', 'calcium ion', 'Ca2+']}
Evaluating 356/1075: BIOMD0000000356.xml
Evaluating 357/1075: BIOMD0000000357.xml
Evaluating 358/1075: BIOMD0000000358.xml
Evaluating 359/1075: BIOMD0000000359.xml
Evaluating 360/1075: BIOMD0000000360.xml
Evaluating 361/1075: BIOMD0000000361.xml
Evaluating 362/1075: BIOMD0000000362.xml
Evaluating 363/1075: BIOMD0000000363.xml
Evaluating 364/1075: BIOMD0000000364.xml
Evaluating 365/1075: BIOMD0000000365.xml
Evaluating 366/1075: BIOMD0000000366.xml
Evaluating 367/1075: BIOMD0000000367.xml
Evaluating 368/1075: BIOMD0000000368.xml
Evaluating 369/1075: BIOMD0000000369.xml
Evaluating 370/1075: BIOMD0000000370.xml
Evaluating 371/1075: BIOMD0000000371.xml
Evaluating 372/1075: BIOMD0000000372.xml

2025-11-20 12:29:55,214 - WARNING - Skipping BIOMD0000000372.xml - no results generated

Evaluating 373/1075: BIOMD0000000373.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000373.txt
LLM response:
c (chemical): "calcium", "Ca2+", "calcium ion"
cer (chemical): "ceramide", "N-acylsphingosine", "sphingosine"
g6p (chemical): "glucose-6-phosphate", "G6P", "D-glucose-6-phosphate"
fbp (chemical): "fructose-1,6-bisphosphate", "FBP", "D-fructose-1,6-bisphosphate"
adp (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Reason: The species are identified based on their display names and the context of the model, which is a pancreatic beta-cell model involving glycolysis and calcium dynamics. The display names for g6p, fbp, and adp match common biochemical abbreviations, while cer is likely ceramide, a type of sphingolipid, and c is likely calcium, given its involvement in cellular signaling and the model's focus on calcium and glycolysis.
Synonyms dict: {'c': ['calcium', 'Ca2+', 'calcium ion'], 'cer': ['ceramide', 'N-acylsphingosine', 'sphingosine'], 'g6p': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'fbp': ['fructose-1,6-bisphosphate', 'FBP', 'D-fructose-1,6-bisphosphate'], 'adp': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"]}
Evaluating 374/1075: BIOMD0000000374.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000374.txt
LLM response:
Ca_er_Ca_equations (unknown): "UNK"
Ca_i (chemical): "calcium ion", "Ca2+", "calcium

Reason: Ca_er_Ca_equations is unknown because it appears to be an equation or a variable related to calcium regulation in the endoplasmic reticulum, rather than a specific chemical or biological entity. Ca_i is a chemical because it represents the concentration of calcium ions inside the cell, which is a common variable in cellular models, particularly in the context of pancreatic beta-cell function and calcium signaling.
Synonyms dict: {'Ca_er_Ca_equations': ['UNK'], 'Ca_i': ['calcium ion', 'Ca2+', '"calcium']}
Evaluating 375/1075: BIOMD0000000375.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000375.txt
LLM response:
Ca_er_Ca_equations (unknown): "UNK"
Ca_i (chemical): "calcium ion", "Ca2+", "calcium

Reason: Ca_er_Ca_equations is unknown because it seems to represent a set of equations or a process related to calcium handling in the endoplasmic reticulum, rather than a specific chemical or biological entity. Ca_i is identified as a chemical because it represents the concentration of calcium ions inside the cell, which is a key aspect of the model focusing on calcium release-activated current in pancreatic beta-cells.
Synonyms dict: {'Ca_er_Ca_equations': ['UNK'], 'Ca_i': ['calcium ion', 'Ca2+', '"calcium']}
Evaluating 376/1075: BIOMD0000000376.xml

2025-11-20 12:30:04,298 - WARNING - Skipping BIOMD0000000377.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000376.txt
LLM response:
G6P (chemical): "glucose-6-phosphate", "G6P", "D-glucose-6-phosphate"
FBP (chemical): "fructose-1,6-bisphosphate", "FBP", "D-fructose-1,6-bisphosphate"
NADHm (chemical): "NADH", "nicotinamide adenine dinucleotide", "reduced nicotinamide adenine dinucleotide"
Cam (chemical): "calcium", "Ca2+", "calcium ion"
ADPm (chemical): "ADP", "adenosine diphosphate", "adenosine 5'-diphosphate"
adp (chemical): "ADP", "adenosine diphosphate", "adenosine 5'-diphosphate"
c (chemical): "calcium", "Ca2+", "calcium ion"
Caer (chemical): "calcium", "Ca2+", "calcium ion"
Reason: The species are identified based on their display names and the context of the model, which is related to glycolysis and mitochondrial respiration in pancreatic islets. G6P and FBP are intermediates in glycolysis, NADHm is a reduced electron carrier, Cam and Caer are calcium ions in different compartments, ADPm and adp are adenine nucleotides, and c is also a calcium ion. The standardized names and synonyms are based on common biochemical nomenclature.
Synonyms dict: {'G6P': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'FBP': ['fructose-1,6-bisphosphate', 'FBP', 'D-fructose-1,6-bisphosphate'], 'NADHm': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced nicotinamide adenine dinucleotide'], 'Cam': ['calcium', 'Ca2+', 'calcium ion'], 'ADPm': ['ADP', 'adenosine diphosphate', "adenosine 5'-diphosphate"], 'adp': ['ADP', 'adenosine diphosphate', "adenosine 5'-diphosphate"], 'c': ['calcium', 'Ca2+', 'calcium ion'], 'Caer': ['calcium', 'Ca2+', 'calcium ion']}
Evaluating 377/1075: BIOMD0000000377.xml
Evaluating 378/1075: BIOMD0000000378.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000378.txt
LLM response:
Ca_i_cytosolic_calcium (chemical): "calcium ion", "Ca2+", "cytosolic calcium"
Ca_lum (chemical): "luminal calcium", "calcium ion", "endoplasmic reticulum calcium"
Reason: Both species are related to calcium concentrations in different cellular compartments, with Ca_i_cytosolic_calcium referring to calcium in the cytosol and Ca_lum referring to calcium in the luminal space, likely of the endoplasmic reticulum, as indicated by the model context and the reaction equations describing their dynamics.
Synonyms dict: {'Ca_i_cytosolic_calcium': ['calcium ion', 'Ca2+', 'cytosolic calcium'], 'Ca_lum': ['luminal calcium', 'calcium ion', 'endoplasmic reticulum calcium']}
Evaluating 379/1075: BIOMD0000000379.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000379.txt
LLM response:
G_p (chemical): "glucose plasma", "blood glucose", "plasma glucose"
G_t (chemical): "glucose tissue", "tissue glucose", "interstitial glucose"
Q_sto1 (unknown): "Q_sto1", "meal glucose", "gut glucose"
Q_gut (unknown): "Q_gut", "gut glucose", "ingested glucose"
Q_sto2 (unknown): "Q_sto2", "stomach glucose", "ingested glucose pool"

Reason: G_p and G_t are likely related to glucose in different compartments, with G_p being glucose in the plasma and G_t being glucose in the tissue, based on the context of the glucose-insulin system model. Q_sto1, Q_gut, and Q_sto2 are unknown because they lack clear display names or descriptions, but based on the reaction equations and the model context, they appear to be related to glucose in different stages of meal absorption and digestion.
Synonyms dict: {'G_p': ['glucose plasma', 'blood glucose', 'plasma glucose'], 'G_t': ['glucose tissue', 'tissue glucose', 'interstitial glucose'], 'Q_sto1': ['Q_sto1', 'meal glucose', 'gut glucose'], 'Q_gut': ['Q_gut', 'gut glucose', 'ingested glucose'], 'Q_sto2': ['Q_sto2', 'stomach glucose', 'ingested glucose pool']}
Evaluating 380/1075: BIOMD0000000380.xml

2025-11-20 12:30:12,148 - WARNING - Skipping BIOMD0000000381.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000380.txt
LLM response:
glc (chemical): "glucose", "D-glucose", "blood sugar"
g1p (chemical): "glucose 1-phosphate", "alpha-D-glucose 1-phosphate", "G1P"
g6p (chemical): "glucose 6-phosphate", "D-glucose 6-phosphate", "G6P"
trh (chemical): "trehalose", "mycose", "trehalose dihydrate"
t6p (chemical): "trehalose 6-phosphate", "alpha,alpha-trehalose 6-phosphate", "T6P"
udg (chemical): "UDP-glucose", "uridine diphosphate glucose", "UDPG"
adp (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
atp (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ppi (chemical): "diphosphate", "pyrophosphate", "PPi"
f6p (chemical): "fructose 6-phosphate", "D-fructose 6-phosphate", "F6P"
h (chemical): "hydrogen ion", "proton", "H+"
pho (chemical): "phosphate", "inorganic phosphate", "Pi"
udp (chemical): "uridine diphosphate", "UDP", "uridine 5'-diphosphate"
utp (chemical): "uridine triphosphate", "UTP", "uridine 5'-triphosphate"
h2o (chemical): "water", "H2O", "dihydrogen monoxide"
glx (chemical): "glucose", "D-glucose", "blood sugar"
Reason: All species are annotated as chemicals because they are all metabolites involved in the trehalose biosynthesis pathway, and their display names and reactions suggest they are small molecules. The standardized names and synonyms are based on common biochemical nomenclature and the display names provided in the model. glx is likely a duplicate of glc, representing the same chemical species.
Synonyms dict: {'glc': ['glucose', 'D-glucose', 'blood sugar'], 'g1p': ['glucose 1-phosphate', 'alpha-D-glucose 1-phosphate', 'G1P'], 'g6p': ['glucose 6-phosphate', 'D-glucose 6-phosphate', 'G6P'], 'trh': ['trehalose', 'mycose', 'trehalose dihydrate'], 't6p': ['trehalose 6-phosphate', 'alpha,alpha-trehalose 6-phosphate', 'T6P'], 'udg': ['UDP-glucose', 'uridine diphosphate glucose', 'UDPG'], 'adp': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'atp': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ppi': ['diphosphate', 'pyrophosphate', 'PPi'], 'f6p': ['fructose 6-phosphate', 'D-fructose 6-phosphate', 'F6P'], 'h': ['hydrogen ion', 'proton', 'H+'], 'pho': ['phosphate', 'inorganic phosphate', 'Pi'], 'udp': ['uridine diphosphate', 'UDP', "uridine 5'-diphosphate"], 'utp': ['uridine triphosphate', 'UTP', "uridine 5'-triphosphate"], 'h2o': ['water', 'H2O', 'dihydrogen monoxide'], 'glx': ['glucose', 'D-glucose', 'blood sugar']}
Evaluating 381/1075: BIOMD0000000381.xml
Evaluating 382/1075: BIOMD0000000382.xml

2025-11-20 12:30:13,843 - WARNING - Skipping BIOMD0000000382.xml - no results generated

Evaluating 383/1075: BIOMD0000000383.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000383.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose 1,5-biphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
O2 (chemical): "oxygen", "O2", "dioxygen"
Reason: All species are identified as chemicals because they are metabolites involved in the Calvin-Benson cycle, a series of biochemical reactions in photosynthesis. RuBP is a substrate, PGA is a product, NADPH is a reducing agent, CO2 is a reactant, and O2 is not directly involved in the reactions listed but is a byproduct of photosynthesis. The standardized names and synonyms are based on common biochemical nomenclature.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose 1,5-biphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'O2': ['oxygen', 'O2', 'dioxygen']}
Evaluating 384/1075: BIOMD0000000384.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000384.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose 1,5-biphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced nicotinamide adenine dinucleotide phosphate"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
O2 (chemical): "oxygen", "O2", "dioxygen"
Reason: All species are identified as chemicals because they are metabolites involved in the Calvin-Benson cycle, a series of biochemical reactions that occur in photosynthetic organisms. The names provided are standardized or common synonyms for each species, based on their roles in the cycle and general biochemical nomenclature.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose 1,5-biphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced nicotinamide adenine dinucleotide phosphate'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'O2': ['oxygen', 'O2', 'dioxygen']}
Evaluating 385/1075: BIOMD0000000385.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000385.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose bisphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
O2 (chemical): "oxygen", "dioxygen", "O2"
Reason: All species are identified as chemicals because they are metabolites involved in the Calvin-Benson cycle, a series of biochemical reactions in photosynthesis. The names provided are standardized or common synonyms for each species, with RuBP being a key substrate in the RuBisCO reaction, PGA being a product of the Calvin cycle, NADPH being a reducing agent, CO2 being the carbon source for photosynthesis, and O2 being a byproduct of photosynthesis.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose bisphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'O2': ['oxygen', 'dioxygen', 'O2']}
Evaluating 386/1075: BIOMD0000000386.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000386.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose bisphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced nicotinamide adenine dinucleotide phosphate"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
O2 (chemical): "oxygen", "dioxygen", "molecular oxygen"
Reason: All species are identified as chemicals because they are metabolites involved in the Calvin-Benson cycle, a series of biochemical reactions. RuBP is a substrate for the RuBisCO enzyme, PGA is a product of the cycle, NADPH is a reducing agent, CO2 is the carbon source, and O2 is a byproduct of the light-dependent reactions. The names provided are standardized or common synonyms for each chemical species.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose bisphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced nicotinamide adenine dinucleotide phosphate'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'O2': ['oxygen', 'dioxygen', 'molecular oxygen']}
Evaluating 387/1075: BIOMD0000000387.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000387.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose 1,5-bisphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
O2 (chemical): "oxygen", "dioxygen", "O2"
Reason: All species are identified as chemicals because they are metabolites involved in the Calvin-Benson cycle, a series of biochemical reactions. RuBP is a substrate for the RuBisCO enzyme, PGA is a product of the cycle, NADPH is a reducing agent, CO2 is the carbon source, and O2 is a byproduct of the light-dependent reactions. The standardized names are based on common biochemical nomenclature.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose 1,5-bisphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'O2': ['oxygen', 'dioxygen', 'O2']}
Evaluating 388/1075: BIOMD0000000388.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000388.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose 1,5-bisphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
GAP (chemical): "glyceraldehyde-3-phosphate", "GAP", "glyceraldehyde 3-phosphate"
Ru5P (chemical): "ribulose-5-phosphate", "Ru5P", "ribulose 5-phosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
Pi (chemical): "inorganic phosphate", "phosphate", "Pi"
Reason: All species are assigned as chemicals because they are all metabolites involved in the Calvin cycle, a series of biochemical reactions that occur in the stroma of chloroplasts in photosynthetic organisms. The names provided are standardized or common synonyms for each metabolite, with the most likely names listed first. The model context and reaction equations support the identification of these species as chemicals.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose 1,5-bisphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'GAP': ['glyceraldehyde-3-phosphate', 'GAP', 'glyceraldehyde 3-phosphate'], 'Ru5P': ['ribulose-5-phosphate', 'Ru5P', 'ribulose 5-phosphate'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'Pi': ['inorganic phosphate', 'phosphate', 'Pi']}
Evaluating 389/1075: BIOMD0000000389.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000389.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "Ru-1,5-BP"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
Ru5P (chemical): "ribulose-5-phosphate", "Ru5P", "Ribu5P"
UTP (chemical): "uridine triphosphate", "UTP", "Uridine 5'-triphosphate"
UDP (chemical): "uridine diphosphate", "UDP", "Uridine 5'-diphosphate"
Pi (chemical): "inorganic phosphate", "phosphate", "Pi"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
Suc (chemical): "sucrose", "table sugar", "saccharose"
Pic (chemical): "phosphate group", "phosphoric acid", "inorganic phosphate"
SucV (unknown): "UNK", "SucV", "sucrose sink"
Reason: The species are identified based on their roles in the Calvin cycle and related metabolic pathways. RuBP, PGA, Ru5P, UTP, UDP, Pi, CO2, and Suc are all chemical intermediates or substrates in the Calvin cycle or sucrose synthesis. Pic is likely a phosphate group or inorganic phosphate, given its role in the reactions. SucV is unknown as it appears to be a sink or export term, but its exact nature is unclear from the provided information.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'Ru-1,5-BP'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'Ru5P': ['ribulose-5-phosphate', 'Ru5P', 'Ribu5P'], 'UTP': ['uridine triphosphate', 'UTP', "Uridine 5'-triphosphate"], 'UDP': ['uridine diphosphate', 'UDP', "Uridine 5'-diphosphate"], 'Pi': ['inorganic phosphate', 'phosphate', 'Pi'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'Suc': ['sucrose', 'table sugar', 'saccharose'], 'Pic': ['phosphate group', 'phosphoric acid', 'inorganic phosphate'], 'SucV': ['UNK', 'SucV', 'sucrose sink']}
Evaluating 390/1075: BIOMD0000000390.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000390.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose 1,5-bisphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
Ru5P (chemical): "ribulose-5-phosphate", "Ru5P", "ribulose 5-phosphate"
Pi (chemical): "inorganic phosphate", "phosphate", "Pi"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Pic (chemical): "inorganic bicarbonate", "bicarbonate", "HCO3-"

Reason: The model is of the Calvin-Benson cycle, a series of biochemical reactions that occur in the stroma of chloroplasts in photosynthetic organisms. All the species listed are known intermediates or cofactors in this cycle, and their display names match common abbreviations used in biochemistry. RuBP is the substrate for the cycle, PGA is an intermediate, Ru5P is a precursor to RuBP, Pi is inorganic phosphate, ATP and ADP are energy transfer molecules, and Pic is likely inorganic bicarbonate, which is involved in the cycle's regulation.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose 1,5-bisphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'Ru5P': ['ribulose-5-phosphate', 'Ru5P', 'ribulose 5-phosphate'], 'Pi': ['inorganic phosphate', 'phosphate', 'Pi'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'Pic': ['inorganic bicarbonate', 'bicarbonate', 'HCO3-']}
Evaluating 391/1075: BIOMD0000000391.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000391.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose 1,5-bisphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
GAP (chemical): "glyceraldehyde-3-phosphate", "GAP", "glyceraldehyde 3-phosphate"
DHAP (chemical): "dihydroxyacetone phosphate", "DHAP", "dihydroxyacetonephosphate"
FBP (chemical): "fructose-1,6-bisphosphate", "FBP", "fructose 1,6-bisphosphate"
F6P (chemical): "fructose-6-phosphate", "F6P", "fructose 6-phosphate"
SBP (chemical): "sedoheptulose-1,7-bisphosphate", "SBP", "sedoheptulose 1,7-bisphosphate"
S7P (chemical): "sedoheptulose-7-phosphate", "S7P", "sedoheptulose 7-phosphate"
X5P (chemical): "xylulose-5-phosphate", "X5P", "xylulose 5-phosphate"
R5P (chemical): "ribose-5-phosphate", "R5P", "ribose 5-phosphate"
Ru5P (chemical): "ribulose-5-phosphate", "Ru5P", "ribulose 5-phosphate"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced nicotinamide adenine dinucleotide phosphate"
H (chemical): "hydrogen ion", "H+", "proton"
Pi (chemical): "inorganic phosphate", "Pi", "phosphate ion"
Pext (unknown): "UNK"
Reason: All species except Pext can be identified as chemicals based on their display names and roles in the Calvin cycle. Pext is unknown because its display name "Pext" does not provide enough information to determine its entity type, but based on the context, it might be related to external phosphate.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose 1,5-bisphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'GAP': ['glyceraldehyde-3-phosphate', 'GAP', 'glyceraldehyde 3-phosphate'], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP', 'dihydroxyacetonephosphate'], 'FBP': ['fructose-1,6-bisphosphate', 'FBP', 'fructose 1,6-bisphosphate'], 'F6P': ['fructose-6-phosphate', 'F6P', 'fructose 6-phosphate'], 'SBP': ['sedoheptulose-1,7-bisphosphate', 'SBP', 'sedoheptulose 1,7-bisphosphate'], 'S7P': ['sedoheptulose-7-phosphate', 'S7P', 'sedoheptulose 7-phosphate'], 'X5P': ['xylulose-5-phosphate', 'X5P', 'xylulose 5-phosphate'], 'R5P': ['ribose-5-phosphate', 'R5P', 'ribose 5-phosphate'], 'Ru5P': ['ribulose-5-phosphate', 'Ru5P', 'ribulose 5-phosphate'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced nicotinamide adenine dinucleotide phosphate'], 'H': ['hydrogen ion', 'H+', 'proton'], 'Pi': ['inorganic phosphate', 'Pi', 'phosphate ion'], 'Pext': ['UNK']}
Evaluating 392/1075: BIOMD0000000392.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000392.txt
LLM response:
RuBP (chemical): "ribulose-1,5-bisphosphate", "RuBP", "ribulose-1,5-diphosphate"
PGA (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "PGA"
GAP (chemical): "glyceraldehyde-3-phosphate", "G3P", "glyceraldehyde phosphate"
DHAP (chemical): "dihydroxyacetone phosphate", "DHAP", "glycerone phosphate"
FBP (chemical): "fructose-1,6-bisphosphate", "FBP", "fructose-1,6-diphosphate"
F6P (chemical): "fructose-6-phosphate", "F6P", "fructose-6-phosphoric acid"
Ru5P (chemical): "ribulose-5-phosphate", "Ru5P", "ribulose monophosphate"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Pi (chemical): "inorganic phosphate", "orthophosphate", "phosphate ion"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
O2 (chemical): "oxygen", "O2", "dioxygen"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
PGAc (chemical): "3-phosphoglycerate (cytosol)", "PGAc", "3-phosphoglyceric acid (cytosol)"
GAPc (chemical): "glyceraldehyde-3-phosphate (cytosol)", "GAPc", "G3P (cytosol)"
DHAPc (chemical): "dihydroxyacetone phosphate (cytosol)", "DHAPc", "glycerone phosphate (cytosol)"
FBPc (chemical): "fructose-1,6-bisphosphate (cytosol)", "FBPc", "fructose-1,6-diphosphate (cytosol)"
F6Pc (chemical): "fructose-6-phosphate (cytosol)", "F6Pc", "fructose-6-phosphoric acid (cytosol)"
UTPc (chemical): "uridine triphosphate (cytosol)", "UTPc", "uridine 5'-triphosphate (cytosol)"
UDPc (chemical): "uridine diphosphate (cytosol)", "UDPc", "uridine 5'-diphosphate (cytosol)"
ATPc (chemical): "adenosine triphosphate (cytosol)", "ATPc", "adenosine 5'-triphosphate (cytosol)"
ADPc (chemical): "adenosine diphosphate (cytosol)", "ADPc", "adenosine 5'-diphosphate (cytosol)"
Succ (chemical): "sucrose", "sucrose phosphate", "sucrose-P"
Pic (chemical): "inorganic phosphate (cytosol)", "orthophosphate (cytosol)", "phosphate ion (cytosol)"
Hc (chemical): "proton", "hydrogen ion", "H+"
Reason: The model is a representation of the Calvin-Benson cycle, which is a series of light-independent reactions in photosynthesis. The species are mostly metabolites involved in the cycle, such as RuBP, PGA, GAP, and FBP, which are all chemicals. The "c" suffix in some species names (e.g., PGAc, GAPc) likely indicates that they are located in the cytosol. ATP, ADP, NADPH, and other energy-related molecules are also chemicals. CO2 and O2 are chemicals involved in photosynthesis. The entity types are determined based on the biochemical context and the names of the species.
Synonyms dict: {'RuBP': ['ribulose-1,5-bisphosphate', 'RuBP', 'ribulose-1,5-diphosphate'], 'PGA': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'PGA'], 'GAP': ['glyceraldehyde-3-phosphate', 'G3P', 'glyceraldehyde phosphate'], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP', 'glycerone phosphate'], 'FBP': ['fructose-1,6-bisphosphate', 'FBP', 'fructose-1,6-diphosphate'], 'F6P': ['fructose-6-phosphate', 'F6P', 'fructose-6-phosphoric acid'], 'Ru5P': ['ribulose-5-phosphate', 'Ru5P', 'ribulose monophosphate'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'Pi': ['inorganic phosphate', 'orthophosphate', 'phosphate ion'], 'CO2': ['carbon dioxide', 'CO2', 'carbonic acid'], 'O2': ['oxygen', 'O2', 'dioxygen'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'PGAc': ['3-phosphoglycerate (cytosol)', 'PGAc', '3-phosphoglyceric acid (cytosol)'], 'GAPc': ['glyceraldehyde-3-phosphate (cytosol)', 'GAPc', 'G3P (cytosol)'], 'DHAPc': ['dihydroxyacetone phosphate (cytosol)', 'DHAPc', 'glycerone phosphate (cytosol)'], 'FBPc': ['fructose-1,6-bisphosphate (cytosol)', 'FBPc', 'fructose-1,6-diphosphate (cytosol)'], 'F6Pc': ['fructose-6-phosphate (cytosol)', 'F6Pc', 'fructose-6-phosphoric acid (cytosol)'], 'UTPc': ['uridine triphosphate (cytosol)', 'UTPc', "uridine 5'-triphosphate (cytosol)"], 'UDPc': ['uridine diphosphate (cytosol)', 'UDPc', "uridine 5'-diphosphate (cytosol)"], 'ATPc': ['adenosine triphosphate (cytosol)', 'ATPc', "adenosine 5'-triphosphate (cytosol)"], 'ADPc': ['adenosine diphosphate (cytosol)', 'ADPc', "adenosine 5'-diphosphate (cytosol)"], 'Succ': ['sucrose', 'sucrose phosphate', 'sucrose-P'], 'Pic': ['inorganic phosphate (cytosol)', 'orthophosphate (cytosol)', 'phosphate ion (cytosol)'], 'Hc': ['proton', 'hydrogen ion', 'H+']}
Evaluating 393/1075: BIOMD0000000393.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000393.txt
LLM response:
SBP (chemical): "sedoheptulose-1,7-bisphosphate", "sedoheptulose 1,7-bisphosphate", "SBP"
S7P (chemical): "sedoheptulose-7-phosphate", "sedoheptulose 7-phosphate", "S7P"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced nicotinamide adenine dinucleotide phosphate"
Pi (chemical): "inorganic phosphate", "phosphate", "Pi"
CO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
GLYc (chemical): "glycine", "GLY", "aminoacetic acid"
SERc (chemical): "serine", "SER", "2-amino-3-hydroxypropanoic acid"
SucPc (chemical): "sucrose phosphate", "sucrose-6-phosphate", "SucP"
NADH (chemical): "nicotinamide adenine dinucleotide", "NADH", "reduced nicotinamide adenine dinucleotide"
GLUc (chemical): "glutamate", "GLU", "2-amino-4-carboxyglutaric acid"

2025-11-20 12:31:15,013 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:31:15,191 - WARNING - Skipping BIOMD0000000401.xml - no results generated
2025-11-20 12:31:15,194 - WARNING - Skipping BIOMD0000000402.xml - no results generated
2025-11-20 12:31:15,198 - WARNING - Skipping BIOMD0000000403.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000400.txt
LLM response:
Gd (unknown): "Gd", "UNK", "Unknown species"
Gt (unknown): "Gt", "UNK", "Unknown species"
Rg (protein): "receptor", "G protein", "G(alpha)GDP"
Rlg (protein): "ligand-bound receptor", "activated receptor", "G(alpha)GTP"
Rlgp (protein): "phosphorylated receptor", "activated receptor complex", "G protein complex"
Pc (chemical): "IP3", "inositol trisphosphate", "myo-inositol 1,4,5-trisphosphate"
Pcg (chemical): "cyclic GMP", "guanosine 3',5'-cyclic monophosphate", "cGMP"
Pg (chemical): "GTP", "guanosine triphosphate", "GTP molecule"
Ca (chemical): "calcium ion", "Ca2+", "calcium"

Reason: The model is based on the IP3 signal production system in cardiac myocytes, and the species names are likely related to this pathway. Rg, Rlg, and Rlgp are likely related to G protein receptors, which are proteins. Pc, Pcg, and Pg are likely related to IP3, cGMP, and GTP, which are chemicals. Ca is likely calcium ion, which is a chemical. Gd and Gt are unknown due to lack of information in the display names and reactions.
Synonyms dict: {'Gd': ['Gd', 'UNK', 'Unknown species'], 'Gt': ['Gt', 'UNK', 'Unknown species'], 'Rg': ['receptor', 'G protein', 'G(alpha)GDP'], 'Rlg': ['ligand-bound receptor', 'activated receptor', 'G(alpha)GTP'], 'Rlgp': ['phosphorylated receptor', 'activated receptor complex', 'G protein complex'], 'Pc': ['IP3', 'inositol trisphosphate', 'myo-inositol 1,4,5-trisphosphate'], 'Pcg': ['cyclic GMP', "guanosine 3',5'-cyclic monophosphate", 'cGMP'], 'Pg': ['GTP', 'guanosine triphosphate', 'GTP molecule'], 'Ca': ['calcium ion', 'Ca2+', 'calcium']}
Evaluating 401/1075: BIOMD0000000401.xml
Evaluating 402/1075: BIOMD0000000402.xml
Evaluating 403/1075: BIOMD0000000403.xml
Evaluating 404/1075: BIOMD0000000404.xml

2025-11-20 12:31:19,895 - WARNING - Skipping BIOMD0000000405.xml - no results generated
2025-11-20 12:31:19,910 - WARNING - Skipping BIOMD0000000406.xml - no results generated
2025-11-20 12:31:19,928 - WARNING - Skipping BIOMD0000000407.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000404.txt
LLM response:
asp (chemical): "aspartate", "aspartic acid", "L-aspartate"
ni (chemical): "nickel", "nickel ion", "Ni2+"
Tasp (complex): "aspartate receptor complex", "Tar-aspartate complex", "aspartate-bound Tar"
Tni (complex): "nickel receptor complex", "Tar-nickel complex", "nickel-bound Tar"
Tasp_W (complex): "aspartate receptor complex with WA", "Tar-aspartate-WA complex", "aspartate-bound Tar with WA"
Tni_W (complex): "nickel receptor complex with WA", "Tar-nickel-WA complex", "nickel-bound Tar with WA"
Tasp_A (complex): "aspartate receptor complex with A", "Tar-aspartate-A complex", "aspartate-bound Tar with A"
Tni_A (complex): "nickel receptor complex with A", "Tar-nickel-A complex", "nickel-bound Tar with A"
Tasp_WA (complex): "aspartate receptor complex with WA and A", "Tar-aspartate-WA-A complex", "aspartate-bound Tar with WA and A"
Tni_WA (complex): "nickel receptor complex with WA and A", "Tar-nickel-WA-A complex", "nickel-bound Tar with WA and A"
species_1 (chemical): "ATP", "adenosine triphosphate", "adenosine 5'-triphosphate"
Reason: The model is a chemotaxis model, and the species are involved in receptor complexes and signaling pathways. Aspartate (asp) and nickel (ni) are chemical species that bind to receptors. The Tasp and Tni species are complexes formed by the binding of aspartate and nickel to the Tar receptor, respectively. The other species (Tasp_W, Tni_W, etc.) are complexes formed by the binding of WA and/or A to the Tar-aspartate or Tar-nickel complexes. Species_1 is identified as ATP, a common chemical energy carrier in biological systems.
Synonyms dict: {'asp': ['aspartate', 'aspartic acid', 'L-aspartate'], 'ni': ['nickel', 'nickel ion', 'Ni2+'], 'Tasp': ['aspartate receptor complex', 'Tar-aspartate complex', 'aspartate-bound Tar'], 'Tni': ['nickel receptor complex', 'Tar-nickel complex', 'nickel-bound Tar'], 'Tasp_W': ['aspartate receptor complex with WA', 'Tar-aspartate-WA complex', 'aspartate-bound Tar with WA'], 'Tni_W': ['nickel receptor complex with WA', 'Tar-nickel-WA complex', 'nickel-bound Tar with WA'], 'Tasp_A': ['aspartate receptor complex with A', 'Tar-aspartate-A complex', 'aspartate-bound Tar with A'], 'Tni_A': ['nickel receptor complex with A', 'Tar-nickel-A complex', 'nickel-bound Tar with A'], 'Tasp_WA': ['aspartate receptor complex with WA and A', 'Tar-aspartate-WA-A complex', 'aspartate-bound Tar with WA and A'], 'Tni_WA': ['nickel receptor complex with WA and A', 'Tar-nickel-WA-A complex', 'nickel-bound Tar with WA and A'], 'species_1': ['ATP', 'adenosine triphosphate', "adenosine 5'-triphosphate"]}
Evaluating 405/1075: BIOMD0000000405.xml
Evaluating 406/1075: BIOMD0000000406.xml
Evaluating 407/1075: BIOMD0000000407.xml
Evaluating 408/1075: BIOMD0000000408.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000408.txt
LLM response:
ADPi (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
ATPi (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
Cri (chemical): "creatine", "Cr", "methylguanidine acetate"
PCri (chemical): "phosphocreatine", "PCr", "N-(phosphono)-creatine"
PCr (chemical): "phosphocreatine", "PCr", "N-(phosphono)-creatine"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
Cr (chemical): "creatine", "Cr", "methylguanidine acetate"
Reason: All species are identified as chemicals because they are involved in biochemical reactions and are known metabolites or energy transfer molecules in cellular processes. The creatine kinase model context and reaction equations support these identifications. ADPi and ATPi are likely intracellular forms of ADP and ATP, while Cri and PCri may represent intracellular or specific forms of creatine and phosphocreatine.
Synonyms dict: {'ADPi': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'ATPi': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'Cri': ['creatine', 'Cr', 'methylguanidine acetate'], 'PCri': ['phosphocreatine', 'PCr', 'N-(phosphono)-creatine'], 'PCr': ['phosphocreatine', 'PCr', 'N-(phosphono)-creatine'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'Cr': ['creatine', 'Cr', 'methylguanidine acetate']}
Evaluating 409/1075: BIOMD0000000409.xml

2025-11-20 12:31:24,213 - WARNING - Skipping BIOMD0000000409.xml - no results generated
2025-11-20 12:31:24,257 - WARNING - Skipping BIOMD0000000410.xml - no results generated
2025-11-20 12:31:24,268 - WARNING - Skipping BIOMD0000000411.xml - no results generated
2025-11-20 12:31:24,328 - WARNING - Skipping BIOMD0000000412.xml - no results generated
2025-11-20 12:31:24,333 - WARNING - Skipping BIOMD0000000413.xml - no results generated
2025-11-20 12:31:24,335 - WARNING - Skipping BIOMD0000000414.xml - no results generated

Evaluating 410/1075: BIOMD0000000410.xml
Evaluating 411/1075: BIOMD0000000411.xml
Evaluating 412/1075: BIOMD0000000412.xml
Evaluating 413/1075: BIOMD0000000413.xml
Evaluating 414/1075: BIOMD0000000414.xml
Evaluating 415/1075: BIOMD0000000415.xml

2025-11-20 12:31:28,871 - WARNING - Skipping BIOMD0000000416.xml - no results generated
2025-11-20 12:31:28,874 - WARNING - Skipping BIOMD0000000417.xml - no results generated
2025-11-20 12:31:28,877 - WARNING - Skipping BIOMD0000000418.xml - no results generated
2025-11-20 12:31:28,881 - WARNING - Skipping BIOMD0000000419.xml - no results generated
2025-11-20 12:31:28,886 - WARNING - Skipping BIOMD0000000420.xml - no results generated
2025-11-20 12:31:28,890 - WARNING - Skipping BIOMD0000000421.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000415.txt
LLM response:
species_1 (chemical): "linoleic acid", "LA", "cis,cis-9,12-octadecadienoic acid"
species_7 (chemical): "13-HODE", "13-hydroxy-9Z,11E-octadecadienoic acid", "13-hydroxylinoleic acid"
species_8 (chemical): "13-HODE", "13-hydroxy-9E,11E-octadecadienoic acid", "13-hydroxylinoleic acid"
species_9 (chemical): "13-HODE", "13-hydroxy-9Z,11E-octadecadienoic acid", "13-hydroxylinoleic acid"
species_10 (chemical): "13-HODE", "13-hydroxy-9E,11E-octadecadienoic acid", "13-hydroxylinoleic acid"
species_11 (chemical): "9-HODE", "9-hydroxy-10E,12Z-octadecadienoic acid", "9-hydroxylinoleic acid"
species_12 (chemical): "9-HODE", "9-hydroxy-10E,12E-octadecadienoic acid", "9-hydroxylinoleic acid"
species_13 (chemical): "9-HODE", "9-hydroxy-10E,12Z-octadecadienoic acid", "9-hydroxylinoleic acid"
species_14 (chemical): "9-HODE", "9-hydroxy-10E,12E-octadecadienoic acid", "9-hydroxylinoleic acid"
Reason: The species are all likely to be chemical entities, specifically fatty acids or their hydroxylated derivatives, given the context of the lipoxygenase pathway model. The names provided are based on common nomenclature for these types of molecules, with the most likely names given first. The model's focus on linoleic acid (LA) metabolism and the production of various hydroxyoctadecadienoic acids (HODEs) supports this interpretation.
Synonyms dict: {'species_1': ['linoleic acid', 'LA', 'cis,cis-9,12-octadecadienoic acid'], 'species_7': ['13-HODE', '13-hydroxy-9Z,11E-octadecadienoic acid', '13-hydroxylinoleic acid'], 'species_8': ['13-HODE', '13-hydroxy-9E,11E-octadecadienoic acid', '13-hydroxylinoleic acid'], 'species_9': ['13-HODE', '13-hydroxy-9Z,11E-octadecadienoic acid', '13-hydroxylinoleic acid'], 'species_10': ['13-HODE', '13-hydroxy-9E,11E-octadecadienoic acid', '13-hydroxylinoleic acid'], 'species_11': ['9-HODE', '9-hydroxy-10E,12Z-octadecadienoic acid', '9-hydroxylinoleic acid'], 'species_12': ['9-HODE', '9-hydroxy-10E,12E-octadecadienoic acid', '9-hydroxylinoleic acid'], 'species_13': ['9-HODE', '9-hydroxy-10E,12Z-octadecadienoic acid', '9-hydroxylinoleic acid'], 'species_14': ['9-HODE', '9-hydroxy-10E,12E-octadecadienoic acid', '9-hydroxylinoleic acid']}
Evaluating 416/1075: BIOMD0000000416.xml
Evaluating 417/1075: BIOMD0000000417.xml
Evaluating 418/1075: BIOMD0000000418.xml
Evaluating 419/1075: BIOMD0000000419.xml
Evaluating 420/1075: BIOMD0000000420.xml
Evaluating 421/1075: BIOMD0000000421.xml
Evaluating 422/1075: BIOMD0000000422.xml

2025-11-20 12:31:36,056 - WARNING - No valid database found for entity type 'gene' in allowed databases: ['chebi']
2025-11-20 12:31:36,074 - WARNING - Skipping BIOMD0000000423.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000422.txt
LLM response:
s1 (chemical): "gibberellin 4", "GA4", "gibberellic acid"
s23 (chemical): "gibberellin 12", "GA12", "gibberellin A12"
s24 (chemical): "gibberellin 15", "GA15", "gibberellin A15"
s25 (chemical): "gibberellin 24", "GA24", "gibberellin A24"
s26 (chemical): "gibberellin 9", "GA9", "gibberellin A9"
s65 (complex): "GA4-GID1 complex", "gibberellin-GID1 complex", "GA-GID complex"
s29 (gene): "GA3ox", "gibberellin 3-oxidase", "GA 3-oxidase"
s30 (gene): "GA20ox", "gibberellin 20-oxidase", "GA 20-oxidase"
s31 (gene): "GA20ox", "gibberellin 20-oxidase", "GA 20-oxidase"
s32 (gene): "GA20ox", "gibberellin 20-oxidase", "GA 20-oxidase"
s62 (complex): "GA4-GID1-closed", "gibberellin-GID1-closed complex", "GA-GID-closed complex"
s36 (complex): "GA4-GID1-DELLA2", "gibberellin-GID1-DELLA2 complex", "GA-GID-DELLA2 complex"
s45 (complex): "GA4-GID1-DELLA1", "gibberellin-GID1-DELLA1 complex", "GA-GID-DELLA1 complex"
s26 (chemical): "gibberellin 9", "GA9", "gibberellin A9"
s29 (gene): "GA3ox", "gibberellin 3-oxidase", "GA 3-oxidase"
s30 (gene): "GA20ox", "gibberellin 20-oxidase", "GA 20-oxidase"
s31 (gene): "GA20ox", "gibberellin 20-oxidase", "GA 20-oxidase"
s32 (gene): "GA20ox", "gibberellin 20-oxidase", "GA 20-oxidase"
s62 (complex): "GA4-GID1-closed", "gibberellin-GID1-closed complex", "GA-GID-closed complex"
s36 (complex): "GA4-GID1-DELLA2", "gibberellin-GID1-DELLA2 complex", "GA-GID-DELLA2 complex"
s45 (complex): "GA4-GID1-DELLA1", "gibberellin-GID1-DELLA1 complex", "GA-GID-DELLA1 complex"
s65 (complex): "GA4-GID1 complex", "gibberellin-GID1 complex", "GA-GID complex"
Reason: The species were identified based on their display names and roles in the gibberellin signaling pathway. The chemical species (s1, s23, s24, s25, s26) are gibberellin molecules, while the complex species (s65, s62, s36, s45) are formed by the interaction of gibberellin with GID1 and DELLA proteins. The gene species (s29, s30, s31, s32) are enzymes involved in gibberellin biosynthesis. The entity types were determined based on the context of the reactions and the display names.
Synonyms dict: {'s1': ['gibberellin 4', 'GA4', 'gibberellic acid'], 's23': ['gibberellin 12', 'GA12', 'gibberellin A12'], 's24': ['gibberellin 15', 'GA15', 'gibberellin A15'], 's25': ['gibberellin 24', 'GA24', 'gibberellin A24'], 's26': ['gibberellin 9', 'GA9', 'gibberellin A9'], 's65': ['GA4-GID1 complex', 'gibberellin-GID1 complex', 'GA-GID complex'], 's29': ['GA3ox', 'gibberellin 3-oxidase', 'GA 3-oxidase'], 's30': ['GA20ox', 'gibberellin 20-oxidase', 'GA 20-oxidase'], 's31': ['GA20ox', 'gibberellin 20-oxidase', 'GA 20-oxidase'], 's32': ['GA20ox', 'gibberellin 20-oxidase', 'GA 20-oxidase'], 's62': ['GA4-GID1-closed', 'gibberellin-GID1-closed complex', 'GA-GID-closed complex'], 's36': ['GA4-GID1-DELLA2', 'gibberellin-GID1-DELLA2 complex', 'GA-GID-DELLA2 complex'], 's45': ['GA4-GID1-DELLA1', 'gibberellin-GID1-DELLA1 complex', 'GA-GID-DELLA1 complex']}
Evaluating 423/1075: BIOMD0000000423.xml
Evaluating 424/1075: BIOMD0000000424.xml

2025-11-20 12:31:39,834 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:31:39,941 - WARNING - Skipping BIOMD0000000425.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000424.txt
LLM response:
RasGDP (protein): "Ras-GDP", "Ras guanine diphosphate", "GDP-bound Ras"
RasGTP (protein): "Ras-GTP", "Ras guanine triphosphate", "GTP-bound Ras"
PI2 (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PtdIns(4,5)P2", "PI(4,5)P2"
PIP3 (chemical): "Phosphatidylinositol 3,4,5-trisphosphate", "PtdIns(3,4,5)P3", "PI(3,4,5)P3"
PTEN_PI (protein): "PTEN", "Phosphatase and tensin homolog", "PTEN protein"
PI3Ka_PI (protein): "PI3K alpha", "Phosphatidylinositol 3-kinase alpha", "PI3Kα"
RasGTP (protein): "Ras-GTP", "Ras guanine triphosphate", "GTP-bound Ras"
Reason: RasGDP and RasGTP are proteins because they represent the GDP- and GTP-bound states of the Ras protein, a small GTPase involved in cell signaling. PI2 and PIP3 are chemicals as they are phosphoinositide lipids involved in cell signaling. PTEN_PI and PI3Ka_PI are proteins because they represent the PTEN and PI3K alpha proteins, respectively, which are involved in the regulation of cell signaling pathways. The "_PI" suffix likely indicates a specific state or complex of the protein, but the underlying entity is still a protein.
Synonyms dict: {'RasGDP': ['Ras-GDP', 'Ras guanine diphosphate', 'GDP-bound Ras'], 'RasGTP': ['Ras-GTP', 'Ras guanine triphosphate', 'GTP-bound Ras'], 'PI2': ['Phosphatidylinositol 4,5-bisphosphate', 'PtdIns(4,5)P2', 'PI(4,5)P2'], 'PIP3': ['Phosphatidylinositol 3,4,5-trisphosphate', 'PtdIns(3,4,5)P3', 'PI(3,4,5)P3'], 'PTEN_PI': ['PTEN', 'Phosphatase and tensin homolog', 'PTEN protein'], 'PI3Ka_PI': ['PI3K alpha', 'Phosphatidylinositol 3-kinase alpha', 'PI3Kα']}
Evaluating 425/1075: BIOMD0000000425.xml
Evaluating 426/1075: BIOMD0000000426.xml

2025-11-20 12:31:50,597 - WARNING - Skipping BIOMD0000000427.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000426.txt
LLM response:
species_1 (chemical): "glucose", "D-glucose", "blood sugar"
species_2 (chemical): "glucose-6-phosphate", "G6P", "D-glucose-6-phosphate"
species_3 (chemical): "ADP", "adenosine diphosphate", "adenosine 5'-diphosphate"
species_4 (chemical): "ATP", "adenosine triphosphate", "adenosine 5'-triphosphate"
species_5 (chemical): "fructose-6-phosphate", "F6P", "D-fructose-6-phosphate"
species_6 (chemical): "fructose-1,6-bisphosphate", "F16P", "D-fructose-1,6-bisphosphate"
species_7 (chemical): "erythrose-4-phosphate", "E4P", "D-erythrose-4-phosphate"
species_8 (chemical): "6-phosphogluconate", "6PG", "D-6-phosphogluconate"
species_9 (chemical): "glucose (extracellular)", "GLC_e", "extracellular glucose"
species_11 (chemical): "NADPH", "nicotinamide adenine dinucleotide phosphate", "reduced NADP"
species_13 (chemical): "ribulose-5-phosphate", "RU5P", "D-ribulose-5-phosphate"
species_14 (chemical): "xylulose-5-phosphate", "X5P", "D-xylulose-5-phosphate"
species_15 (chemical): "ribose-5-phosphate", "R5P", "D-ribose-5-phosphate"
species_16 (chemical): "glyceraldehyde-3-phosphate", "GAP", "D-glyceraldehyde-3-phosphate"
species_17 (chemical): "sedoheptulose-7-phosphate", "S7P", "D-sedoheptulose-7-phosphate"
species_20 (chemical): "AMP", "adenosine monophosphate", "adenosine 5'-monophosphate"
species_22 (chemical): "glucose-1-phosphate", "G1P", "D-glucose-1-phosphate"
species_23 (chemical): "inorganic phosphate", "Pi", "orthophosphate"
species_27 (chemical): "dihydroxyacetone phosphate", "DHAP", "D-dihydroxyacetone phosphate"
species_28 (chemical): "3-phosphoglycerate", "PG3", "D-3-phosphoglycerate"
species_29 (chemical): "2-phosphoglycerate", "PG2", "D-2-phosphoglycerate"
species_30 (chemical): "phosphoenolpyruvate", "PEP", "D-phosphoenolpyruvate"
species_31 (chemical): "pyruvate", "PYR", "pyruvic acid"
species_32 (chemical): "lactic acid", "LAC", "lactate"
species_33 (chemical): "carbon dioxide", "CO2", "carbonic acid"
species_34 (chemical): "oxygen", "O2", "molecular oxygen"
species_18 (chemical): "NADH", "nicotinamide adenine dinucleotide", "reduced NAD"
species_25 (chemical): "citrate", "CIT", "citric acid"
species_12 (chemical): "1,3-bisphosphoglycerate", "BPG", "D-1,3-bisphosphoglycerate"
species_19 (chemical): "NAD", "nicotinamide adenine dinucleotide", "NAD oxidized"
species_10 (chemical): "NADP", "nicotinamide adenine dinucleotide phosphate", "NADP oxidized"
species_24 (chemical): "glyceraldehyde", "GLY", "D-glyceraldehyde"
Reason: The model is based on central carbon metabolism, which involves various biochemical reactions and pathways, including glycolysis, pentose phosphate pathway, and citric acid cycle. Each species is identified based on its display name and its role in the reactions. For example, species_1 is identified as glucose, species_2 as glucose-6-phosphate, and species_4 as ATP, which are all key molecules in glycolysis. Species_11, species_18, and species_19 are identified as NADPH, NADH, and NAD, respectively, which are electron carriers involved in various redox reactions. Species_31 is identified as pyruvate, which is the end product of glycolysis and can be converted to lactic acid (species_32) or enter the citric acid cycle. Species_33 and species_34 are identified as carbon dioxide and oxygen, respectively, which are involved in cellular respiration.
Synonyms dict: {'species_1': ['glucose', 'D-glucose', 'blood sugar'], 'species_2': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'species_3': ['ADP', 'adenosine diphosphate', "adenosine 5'-diphosphate"], 'species_4': ['ATP', 'adenosine triphosphate', "adenosine 5'-triphosphate"], 'species_5': ['fructose-6-phosphate', 'F6P', 'D-fructose-6-phosphate'], 'species_6': ['fructose-1,6-bisphosphate', 'F16P', 'D-fructose-1,6-bisphosphate'], 'species_7': ['erythrose-4-phosphate', 'E4P', 'D-erythrose-4-phosphate'], 'species_8': ['6-phosphogluconate', '6PG', 'D-6-phosphogluconate'], 'species_9': ['glucose (extracellular)', 'GLC_e', 'extracellular glucose'], 'species_11': ['NADPH', 'nicotinamide adenine dinucleotide phosphate', 'reduced NADP'], 'species_13': ['ribulose-5-phosphate', 'RU5P', 'D-ribulose-5-phosphate'], 'species_14': ['xylulose-5-phosphate', 'X5P', 'D-xylulose-5-phosphate'], 'species_15': ['ribose-5-phosphate', 'R5P', 'D-ribose-5-phosphate'], 'species_16': ['glyceraldehyde-3-phosphate', 'GAP', 'D-glyceraldehyde-3-phosphate'], 'species_17': ['sedoheptulose-7-phosphate', 'S7P', 'D-sedoheptulose-7-phosphate'], 'species_20': ['AMP', 'adenosine monophosphate', "adenosine 5'-monophosphate"], 'species_22': ['glucose-1-phosphate', 'G1P', 'D-glucose-1-phosphate'], 'species_23': ['inorganic phosphate', 'Pi', 'orthophosphate'], 'species_27': ['dihydroxyacetone phosphate', 'DHAP', 'D-dihydroxyacetone phosphate'], 'species_28': ['3-phosphoglycerate', 'PG3', 'D-3-phosphoglycerate'], 'species_29': ['2-phosphoglycerate', 'PG2', 'D-2-phosphoglycerate'], 'species_30': ['phosphoenolpyruvate', 'PEP', 'D-phosphoenolpyruvate'], 'species_31': ['pyruvate', 'PYR', 'pyruvic acid'], 'species_32': ['lactic acid', 'LAC', 'lactate'], 'species_33': ['carbon dioxide', 'CO2', 'carbonic acid'], 'species_34': ['oxygen', 'O2', 'molecular oxygen'], 'species_18': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced NAD'], 'species_25': ['citrate', 'CIT', 'citric acid'], 'species_12': ['1,3-bisphosphoglycerate', 'BPG', 'D-1,3-bisphosphoglycerate'], 'species_19': ['NAD', 'nicotinamide adenine dinucleotide', 'NAD oxidized'], 'species_10': ['NADP', 'nicotinamide adenine dinucleotide phosphate', 'NADP oxidized'], 'species_24': ['glyceraldehyde', 'GLY', 'D-glyceraldehyde']}
Evaluating 427/1075: BIOMD0000000427.xml
Evaluating 428/1075: BIOMD0000000428.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000428.txt
LLM response:
ATP_g (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ATP_c (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
Pyr_c (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
DHAP_c (chemical): "dihydroxyacetone phosphate", "DHAP", "3-hydroxy-2-oxopropyl phosphate"
Pyr_e (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
Gly3P_c (chemical): "glycerol-3-phosphate", "G3P", "sn-glycerol 3-phosphate"
DHAP_g (chemical): "dihydroxyacetone phosphate", "DHAP", "3-hydroxy-2-oxopropyl phosphate"
Glc6P_g (chemical): "glucose-6-phosphate", "G6P", "d-glucose 6-phosphate"
Fru16BP_g (chemical): "fructose-1,6-bisphosphate", "F1,6BP", "d-fructose 1,6-bisphosphate"
ADP_c (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
_3PGA_c (chemical): "3-phosphoglycerate", "3-PGA", "3-phosphoglyceric acid"
Gly_g (chemical): "glycerol", "glycerin", "propan-1,2,3-triol"
Fru6P_g (chemical): "fructose-6-phosphate", "F6P", "d-fructose 6-phosphate"
Gly_e (chemical): "glycerol", "glycerin", "propan-1,2,3-triol"
_3PGA_g (chemical): "3-phosphoglycerate", "3-PGA", "3-phosphoglyceric acid"
Gly_c (chemical): "glycerol", "glycerin", "propan-1,2,3-triol"
Pi_g (chemical): "inorganic phosphate", "phosphate", "orthophosphate"
AMP_c (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
O2_c (chemical): "oxygen", "dioxygen", "molecular oxygen"
GA3P_g (chemical): "glyceraldehyde-3-phosphate", "G3P", "d-glyceraldehyde 3-phosphate"
Gly3P_g (chemical): "glycerol-3-phosphate", "G3P", "sn-glycerol 3-phosphate"
ADP_g (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
PEP_c (chemical): "phosphoenolpyruvate", "PEP", "2-phosphoenolpyruvate"
AMP_g (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
Glc_c (chemical): "glucose", "d-glucose", "blood sugar"
Glc_e (chemical): "glucose", "d-glucose", "blood sugar"
Glc_g (chemical): "glucose", "d-glucose", "blood sugar"
NADH_g (chemical): "nicotinamide adenine dinucleotide + hydrogen", "NADH", "reduced nicotinamide adenine dinucleotide"
Reason: All species are identified as chemicals based on their involvement in the glycolytic pathway, a metabolic process that converts glucose into pyruvate, producing energy for the cell. The names provided are standardized and commonly used in biochemical literature. The species IDs with "_g" and "_c" suffixes indicate the compartmentalization of the species, with "_g" representing the glycosome and "_c" representing the cytosol. The "_e" suffix indicates the external environment. The lack of gene or protein species in the model is consistent with the focus on metabolic pathways, where the emphasis is on the chemical reactions and intermediates rather than the genetic or proteomic aspects.
Synonyms dict: {'ATP_g': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ATP_c': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'Pyr_c': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'DHAP_c': ['dihydroxyacetone phosphate', 'DHAP', '3-hydroxy-2-oxopropyl phosphate'], 'Pyr_e': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'Gly3P_c': ['glycerol-3-phosphate', 'G3P', 'sn-glycerol 3-phosphate'], 'DHAP_g': ['dihydroxyacetone phosphate', 'DHAP', '3-hydroxy-2-oxopropyl phosphate'], 'Glc6P_g': ['glucose-6-phosphate', 'G6P', 'd-glucose 6-phosphate'], 'Fru16BP_g': ['fructose-1,6-bisphosphate', 'F1,6BP', 'd-fructose 1,6-bisphosphate'], 'ADP_c': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], '_3PGA_c': ['3-phosphoglycerate', '3-PGA', '3-phosphoglyceric acid'], 'Gly_g': ['glycerol', 'glycerin', 'propan-1,2,3-triol'], 'Fru6P_g': ['fructose-6-phosphate', 'F6P', 'd-fructose 6-phosphate'], 'Gly_e': ['glycerol', 'glycerin', 'propan-1,2,3-triol'], '_3PGA_g': ['3-phosphoglycerate', '3-PGA', '3-phosphoglyceric acid'], 'Gly_c': ['glycerol', 'glycerin', 'propan-1,2,3-triol'], 'Pi_g': ['inorganic phosphate', 'phosphate', 'orthophosphate'], 'AMP_c': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'O2_c': ['oxygen', 'dioxygen', 'molecular oxygen'], 'GA3P_g': ['glyceraldehyde-3-phosphate', 'G3P', 'd-glyceraldehyde 3-phosphate'], 'Gly3P_g': ['glycerol-3-phosphate', 'G3P', 'sn-glycerol 3-phosphate'], 'ADP_g': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'PEP_c': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvate'], 'AMP_g': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'Glc_c': ['glucose', 'd-glucose', 'blood sugar'], 'Glc_e': ['glucose', 'd-glucose', 'blood sugar'], 'Glc_g': ['glucose', 'd-glucose', 'blood sugar'], 'NADH_g': ['nicotinamide adenine dinucleotide + hydrogen', 'NADH', 'reduced nicotinamide adenine dinucleotide']}
Evaluating 429/1075: BIOMD0000000429.xml

2025-11-20 12:32:02,431 - WARNING - Skipping BIOMD0000000430.xml - no results generated
2025-11-20 12:32:02,446 - WARNING - Skipping BIOMD0000000431.xml - no results generated
2025-11-20 12:32:02,457 - WARNING - Skipping BIOMD0000000432.xml - no results generated
2025-11-20 12:32:02,469 - WARNING - Skipping BIOMD0000000433.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000429.txt
LLM response:
species_1 (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
species_13 (chemical): "glycine", "aminoacetic acid", "aminoethanoic acid"
Reason: The model is related to the yeast HOG pathway, which is involved in osmo-adaptation and glycerol production. Species_1 is likely "glycerol" as it is mentioned in the model notes as being produced in response to hyper-osmotic shock. Species_13 is annotated as "Glyex", which could be a typo or abbreviation for "glycine", but without further information, it is also possible that it refers to a different compound, however, based on the context, "glycine" is a plausible guess.
Synonyms dict: {'species_1': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'species_13': ['glycine', 'aminoacetic acid', 'aminoethanoic acid']}
Evaluating 430/1075: BIOMD0000000430.xml
Evaluating 431/1075: BIOMD0000000431.xml
Evaluating 432/1075: BIOMD0000000432.xml
Evaluating 433/1075: BIOMD0000000433.xml
Evaluating 434/1075: BIOMD0000000434.xml

2025-11-20 12:32:05,985 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:32:06,013 - WARNING - Skipping BIOMD0000000435.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000434.txt
LLM response:
species_1 (chemical): "dietary cholesterol", "cholesterol", "dietary cholesteryl ester"
species_2 (chemical): "intestinal cholesterol", "cholesterol", "unesterified cholesterol"
species_7 (chemical): "HFC", "free cholesterol", "cholesterol"
species_8 (chemical): "EC", "esterified cholesterol", "cholesteryl ester"
species_11 (chemical): "PFC", "phospholipid-free cholesterol", "unesterified cholesterol"
species_13 (chemical): "HCE", "HDL-cholesterol ester", "cholesteryl ester"
species_14 (protein): "ACAT", "acetyl-CoA acetyltransferase", "acyl-CoA:cholesterol acyltransferase"
species_28 (chemical): "PCE", "phospholipid-cholesterol ester", "cholesteryl ester"
Reason: The model is a whole-body cholesterol metabolism model, and most species are related to cholesterol or lipoproteins. Species_14 is an enzyme (ACAT) involved in cholesterol esterification. The other species are likely to be chemicals (cholesterol or lipoproteins) based on their names and the reactions they are involved in.
Synonyms dict: {'species_1': ['dietary cholesterol', 'cholesterol', 'dietary cholesteryl ester'], 'species_2': ['intestinal cholesterol', 'cholesterol', 'unesterified cholesterol'], 'species_7': ['HFC', 'free cholesterol', 'cholesterol'], 'species_8': ['EC', 'esterified cholesterol', 'cholesteryl ester'], 'species_11': ['PFC', 'phospholipid-free cholesterol', 'unesterified cholesterol'], 'species_13': ['HCE', 'HDL-cholesterol ester', 'cholesteryl ester'], 'species_14': ['ACAT', 'acetyl-CoA acetyltransferase', 'acyl-CoA:cholesterol acyltransferase'], 'species_28': ['PCE', 'phospholipid-cholesterol ester', 'cholesteryl ester']}
Evaluating 435/1075: BIOMD0000000435.xml
Evaluating 436/1075: BIOMD0000000436.xml

2025-11-20 12:32:11,270 - WARNING - Skipping BIOMD0000000437.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000436.txt
LLM response:
FA (chemical): "fatty acid", "free fatty acid", "fatty acyl"
PGH2 (chemical): "prostaglandin H2", "PGH2", "prostanoic acid"
PGF2a (chemical): "prostaglandin F2 alpha", "dinoprost", "PGF2α"
PGD2 (chemical): "prostaglandin D2", "PGD2", "prostanoic acid"
PGJ2 (chemical): "prostaglandin J2", "PGJ2", "prostanoic acid"
dPGJ2 (chemical): "15-deoxy-Δ12,14-prostaglandin J2", "15-deoxy-PGJ2", "dPGJ2"
AA (chemical): "arachidonic acid", "eicosatetraenoic acid", "all-cis-5,8,11,14-eicosatetraenoic acid"
DG (chemical): "diacylglycerol", "diglyceride", "diacylglyceride"
GPCho (chemical): "glycerophosphocholine", "1-glycerophosphocholine", "L-α-glycerophosphocholine"
HETE (chemical): "hydroxyeicosatetraenoic acid", "HETE", "hydroxy-arachidonic acid"
PGE2 (chemical): "prostaglandin E2", "dinoprostone", "PGE2"
dPGD2 (chemical): "15-deoxy-Δ12,14-prostaglandin D2", "15-deoxy-PGD2", "dPGD2"

Reason: The species are all part of the eicosanoid metabolism pathway, which involves the conversion of arachidonic acid (AA) into various prostaglandins and other eicosanoids. The entity types are all chemicals, as they are all metabolites or intermediates in the pathway. The names and synonyms provided are based on common names and abbreviations used in the field of biochemistry and lipid metabolism. FA is likely a fatty acid, which is a precursor to the synthesis of AA. DG and GPCho are likely involved in the synthesis of AA from phospholipids. The other species are all eicosanoids or intermediates in their synthesis.
Synonyms dict: {'FA': ['fatty acid', 'free fatty acid', 'fatty acyl'], 'PGH2': ['prostaglandin H2', 'PGH2', 'prostanoic acid'], 'PGF2a': ['prostaglandin F2 alpha', 'dinoprost', 'PGF2α'], 'PGD2': ['prostaglandin D2', 'PGD2', 'prostanoic acid'], 'PGJ2': ['prostaglandin J2', 'PGJ2', 'prostanoic acid'], 'dPGJ2': ['15-deoxy-Δ12,14-prostaglandin J2', '15-deoxy-PGJ2', 'dPGJ2'], 'AA': ['arachidonic acid', 'eicosatetraenoic acid', 'all-cis-5,8,11,14-eicosatetraenoic acid'], 'DG': ['diacylglycerol', 'diglyceride', 'diacylglyceride'], 'GPCho': ['glycerophosphocholine', '1-glycerophosphocholine', 'L-α-glycerophosphocholine'], 'HETE': ['hydroxyeicosatetraenoic acid', 'HETE', 'hydroxy-arachidonic acid'], 'PGE2': ['prostaglandin E2', 'dinoprostone', 'PGE2'], 'dPGD2': ['15-deoxy-Δ12,14-prostaglandin D2', '15-deoxy-PGD2', 'dPGD2']}
Evaluating 437/1075: BIOMD0000000437.xml
Evaluating 438/1075: BIOMD0000000438.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000438.txt
LLM response:
s4 (chemical): "3OC12HSL", "N-(3-oxododecanoyl)-L-homoserine lactone", "3-oxo-dodecanoyl-homoserine lactone"
s19 (protein): "LasR", "Pseudomonas aeruginosa LasR", "Trans-activator LasR"
s42 (complex): "LasR/AHL", "LasR-3OC12HSL complex", "3OC12HSL-LasR complex"
s5 (chemical): "sa6_degraded", "degraded 3OC12HSL", "3OC12HSL degradation product"
Reason: s4 is a chemical because it is a type of Acyl Homoserine Lactone (AHL), which is a signaling molecule. s19 is a protein because it is a transcriptional regulator (LasR) that binds to AHL. s42 is a complex because it is formed by the binding of LasR and AHL (3OC12HSL). s5 is a chemical because it is the degradation product of 3OC12HSL.
Synonyms dict: {'s4': ['3OC12HSL', 'N-(3-oxododecanoyl)-L-homoserine lactone', '3-oxo-dodecanoyl-homoserine lactone'], 's19': ['LasR', 'Pseudomonas aeruginosa LasR', 'Trans-activator LasR'], 's42': ['LasR/AHL', 'LasR-3OC12HSL complex', '3OC12HSL-LasR complex'], 's5': ['sa6_degraded', 'degraded 3OC12HSL', '3OC12HSL degradation product']}
Evaluating 439/1075: BIOMD0000000439.xml

2025-11-20 12:32:19,852 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:32:20,039 - WARNING - Skipping BIOMD0000000440.xml - no results generated
2025-11-20 12:32:20,049 - WARNING - Skipping BIOMD0000000441.xml - no results generated
2025-11-20 12:32:20,059 - WARNING - Skipping BIOMD0000000442.xml - no results generated
2025-11-20 12:32:20,077 - WARNING - Skipping BIOMD0000000443.xml - no results generated
2025-11-20 12:32:20,093 - WARNING - Skipping BIOMD0000000444.xml - no results generated
2025-11-20 12:32:20,132 - WARNING - Skipping BIOMD0000000445.xml - no results generated
2025-11-20 12:32:20,144 - WARNING - Skipping BIOMD0000000446.xml - no results generated
2025-11-20 12:32:20,155 - WARNING - Skipping BIOMD0000000447.xml - no results generated
2025-11-20 12:32:20,167 - WARNING - Skipping BIOMD0000000448.xml - no results generated
2025-11-20 12:32:20,178 - WARNING - Skipping BIOMD0000000449.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000439.txt
LLM response:
GaGTP (protein): "Galpha(GTP)", "G protein alpha subunit", "GTP-bound Galpha"
RGSGaGTP (complex): "RGS-Galpha(GTP) complex", "Regulator of G protein signaling-Galpha complex", "RGS-G protein complex"
GaGDPP (chemical): "GDP-bound Galpha", "GDP", "Guanosine diphosphate"
GaGTPEffector (complex): "Galpha(GTP)-effector complex", "G protein alpha subunit-effector complex", "Activated G protein complex"
inertGaGTP (protein): "Inactive Galpha(GTP)", "Galpha(GTP) inactive state", "Inert G protein alpha subunit"
RGSinertGaGTP (complex): "RGS-inactive Galpha(GTP) complex", "Regulator of G protein signaling-inactive Galpha complex", "RGS-inert G protein complex"
GaGDP (protein): "GDP-bound Galpha", "G protein alpha subunit", "Galpha(GDP)"
P (chemical): "Inorganic phosphate", "Phosphate group", "Pi"
RGabgL (complex): "Heterotrimeric G protein", "G protein complex", "Galpha-Gbeta-Gamma complex"
RL (unknown): "UNK",
Gabg (complex): "Heterotrimeric G protein", "G protein complex", "Galpha-Gbeta-Gamma complex"
Gbg (complex): "Gbeta-Gamma complex", "G protein beta-gamma subunits", "Gbeta-Gamma dimer"
Effector (unknown): "UNK",
RGS (protein): "Regulator of G protein signaling", "RGS protein", "GTPase-activating protein"
Reason: The entity types are determined based on the context of the model, which describes the G protein cycle and the regulation of G protein-coupled receptors (GPCRs) by GTP hydrolysis. The species are identified as proteins, complexes, or chemicals based on their roles in the reactions and their descriptions in the model. The standardized names and synonyms are provided based on common terminology in the field of molecular biology and biochemistry. The unknown species (RL and Effector) lack sufficient information to determine their entity types, and the inert and inactive states of GaGTP are considered as protein entities due to their association with the G protein alpha subunit.
Synonyms dict: {'GaGTP': ['Galpha(GTP)', 'G protein alpha subunit', 'GTP-bound Galpha'], 'RGSGaGTP': ['RGS-Galpha(GTP) complex', 'Regulator of G protein signaling-Galpha complex', 'RGS-G protein complex'], 'GaGDPP': ['GDP-bound Galpha', 'GDP', 'Guanosine diphosphate'], 'GaGTPEffector': ['Galpha(GTP)-effector complex', 'G protein alpha subunit-effector complex', 'Activated G protein complex'], 'inertGaGTP': ['Inactive Galpha(GTP)', 'Galpha(GTP) inactive state', 'Inert G protein alpha subunit'], 'RGSinertGaGTP': ['RGS-inactive Galpha(GTP) complex', 'Regulator of G protein signaling-inactive Galpha complex', 'RGS-inert G protein complex'], 'GaGDP': ['GDP-bound Galpha', 'G protein alpha subunit', 'Galpha(GDP)'], 'P': ['Inorganic phosphate', 'Phosphate group', 'Pi'], 'RGabgL': ['Heterotrimeric G protein', 'G protein complex', 'Galpha-Gbeta-Gamma complex'], 'RL': ['UNK'], 'Gabg': ['Heterotrimeric G protein', 'G protein complex', 'Galpha-Gbeta-Gamma complex'], 'Gbg': ['Gbeta-Gamma complex', 'G protein beta-gamma subunits', 'Gbeta-Gamma dimer'], 'Effector': ['UNK'], 'RGS': ['Regulator of G protein signaling', 'RGS protein', 'GTPase-activating protein']}
Evaluating 440/1075: BIOMD0000000440.xml
Evaluating 441/1075: BIOMD0000000441.xml
Evaluating 442/1075: BIOMD0000000442.xml
Evaluating 443/1075: BIOMD0000000443.xml
Evaluating 444/1075: BIOMD0000000444.xml
Evaluating 445/1075: BIOMD0000000445.xml
Evaluating 446/1075: BIOMD0000000446.xml
Evaluating 447/1075: BIOMD0000000447.xml
Evaluating 448/1075: BIOMD0000000448.xml
Evaluating 449/1075: BIOMD0000000449.xml
Evaluating 450/1075: BIOMD0000000450.xml

2025-11-20 12:32:42,766 - WARNING - Skipping BIOMD0000000451.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000450.txt
LLM response:
b_met (chemical): "methionine", "L-methionine", "L-Met"
b_ser (chemical): "serine", "L-serine", "L-Ser"
b_gly (chemical): "glycine", "L-glycine", "L-Gly"
b_glu (chemical): "glutamate", "L-glutamate", "L-Glu"
b_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
b_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
b_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
GAR (chemical): "glycinamide ribonucleotide", "GAR", "phosphoribosylglycinamide"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
BET (chemical): "betaine", "trimethylglycine", "TMG"
DUMP (chemical): "deoxyuridine monophosphate", "dUMP", "deoxyuridylate"
H2O2 (chemical): "hydrogen peroxide", "H2O2", "peroxide"
c_thf (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
c_5mf (chemical): "5-methyltetrahydrofolate", "5-MTHF", "L-methylfolate"
c_2cf (chemical): "5,10-methylenetetrahydrofolate", "5,10-CH2-THF", "methylenetetrahydrofolate"
c_10f (chemical): "10-formyltetrahydrofolate", "10-CHO-THF", "formyltetrahydrofolate"
c_dhf (chemical): "dihydrofolate", "DHF", "7,8-dihydrofolate"
aic (chemical): "5-aminoimidazole-4-carboxamide ribonucleotide", "AICAR", "ZMP"
c_glu (chemical): "glutamate", "L-glutamate", "L-Glu"
c_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
c_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
c_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
hcy (chemical): "homocysteine", "L-homocysteine", "L-Hcy"
c_ser (chemical): "serine", "L-serine", "L-Ser"
sah (chemical): "S-adenosylhomocysteine", "SAH", "AdoHcy"
sam (chemical): "S-adenosylmethionine", "SAM", "AdoMet"
met (chemical): "methionine", "L-methionine", "L-Met"
c_coo (chemical): "formate", "formic acid", "HCOOH"
species_1 (chemical): "decyl-S-adenosylmethionine", "dcSAM", "decyl-SAM"
species_2 (chemical): "putrescine", "1,4-diaminobutane", "Put"
species_3 (chemical): "spermine", "1,12-diamino-4,9-diazadodecane", "Spm"
species_4 (chemical): "spermidine", "1,8-diamino-4-azaoctane", "Spd"
species_5 (chemical): "acetylspermine", "N-acetylspermine", "AcSpm"
species_6 (chemical): "acetylspermidine", "N-acetylspermidine", "AcSpd"
species_7 (chemical): "ornithine", "L-ornithine", "L-Orn"
species_8 (chemical): "acetyl-CoA", "AcCoA", "acetyl coenzyme A"
species_9 (chemical): "CoA", "coenzyme A", "CoASH"
CO (chemical): "carbon monoxide", "CO", "carbonyl"
m_thf (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
m_2cf (chemical): "5,10-methylenetetrahydrofolate", "5,10-CH2-THF", "methylenetetrahydrofolate"
m_10f (chemical): "10-formyltetrahydrofolate", "10-CHO-THF", "formyltetrahydrofolate"
m_ser (chemical): "serine", "L-serine", "L-Ser"
m_gly (chemical): "glycine", "L-glycine", "L-Gly"
m_coo (chemical): "formate", "formic acid", "HCOOH"
Fol (chemical): "folic acid", "vitamin B9", "pteroylglutamic acid"
HCHO (chemical): "formaldehyde", "methanal", "HCHO"
src (chemical): "sarcosine", "N-methylglycine", "MGL"
dmg (chemical): "dimethylglycine", "DMG", "N,N-dimethylglycine"
glc (chemical): "glutamylcysteine", "γ-glutamylcysteine", "Glu-Cys"
c_gly (chemical): "glycine", "L-glycine", "L-Gly"
c_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
c_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
c_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
hcy (chemical): "homocysteine", "L-homocysteine", "L-Hcy"
c_ser (chemical): "serine", "L-serine", "L-Ser"
sah (chemical): "S-adenosylhomocysteine", "SAH", "AdoHcy"
sam (chemical): "S-adenosylmethionine", "SAM", "AdoMet"
met (chemical): "methionine", "L-methionine", "L-Met"
c_coo (chemical): "formate", "formic acid", "HCOOH"
species_1 (chemical): "decyl-S-adenosylmethionine", "dcSAM", "decyl-SAM"
species_2 (chemical): "putrescine", "1,4-diaminobutane", "Put"
species_3 (chemical): "spermine", "1,12-diamino-4,9-diazadodecane", "Spm"
species_4 (chemical): "spermidine", "1,8-diamino-4-azaoctane", "Spd"
species_5 (chemical): "acetylspermine", "N-acetylspermine", "AcSpm"
species_6 (chemical): "acetylspermidine", "N-acetylspermidine", "AcSpd"
species_7 (chemical): "ornithine", "L-ornithine", "L-Orn"
species_8 (chemical): "acetyl-CoA", "AcCoA", "acetyl coenzyme A"
species_9 (chemical): "CoA", "coenzyme A", "CoASH"
CO (chemical): "carbon monoxide", "CO", "carbonyl"
m_thf (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
m_2cf (chemical): "5,10-methylenetetrahydrofolate", "5,10-CH2-THF", "methylenetetrahydrofolate"
m_10f (chemical): "10-formyltetrahydrofolate", "10-CHO-THF", "formyltetrahydrofolate"
m_ser (chemical): "serine", "L-serine", "L-Ser"
m_gly (chemical): "glycine", "L-glycine", "L-Gly"
m_coo (chemical): "formate", "formic acid", "HCOOH"
Fol (chemical): "folic acid", "vitamin B9", "pteroylglutamic acid"
HCHO (chemical): "formaldehyde", "methanal", "HCHO"
src (chemical): "sarcosine", "N-methylglycine", "MGL"
dmg (chemical): "dimethylglycine", "DMG", "N,N-dimethylglycine"
glc (chemical): "glutamylcysteine", "γ-glutamylcysteine", "Glu-Cys"
c_gly (chemical): "glycine", "L-glycine", "L-Gly"
c_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
c_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
c_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
hcy (chemical): "homocysteine", "L-homocysteine", "L-Hcy"
c_ser (chemical): "serine", "L-serine", "L-Ser"
sah (chemical): "S-adenosylhomocysteine", "SAH", "AdoHcy"
sam (chemical): "S-adenosylmethionine", "SAM", "AdoMet"
met (chemical): "methionine", "L-methionine", "L-Met"
c_coo (chemical): "formate", "formic acid", "HCOOH"
Reason: The model is a combined model of hepatic polyamine and sulfur amino acid metabolism, and all species are chemicals involved in these metabolic pathways. The species are identified based on their display names and roles in the reactions. The entity type for each species is determined as chemical, as they are all metabolites or substrates involved in the metabolic reactions.
Synonyms dict: {'b_met': ['methionine', 'L-methionine', 'L-Met'], 'b_ser': ['serine', 'L-serine', 'L-Ser'], 'b_gly': ['glycine', 'L-glycine', 'L-Gly'], 'b_glu': ['glutamate', 'L-glutamate', 'L-Glu'], 'b_cys': ['cysteine', 'L-cysteine', 'L-Cys'], 'b_gsg': ['glutathione disulfide', 'GSSG', 'oxidized glutathione'], 'b_gsh': ['glutathione', 'GSH', 'reduced glutathione'], 'GAR': ['glycinamide ribonucleotide', 'GAR', 'phosphoribosylglycinamide'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'BET': ['betaine', 'trimethylglycine', 'TMG'], 'DUMP': ['deoxyuridine monophosphate', 'dUMP', 'deoxyuridylate'], 'H2O2': ['hydrogen peroxide', 'H2O2', 'peroxide'], 'c_thf': ['tetrahydrofolate', 'THF', 'tetrahydrofolic acid'], 'c_5mf': ['5-methyltetrahydrofolate', '5-MTHF', 'L-methylfolate'], 'c_2cf': ['5,10-methylenetetrahydrofolate', '5,10-CH2-THF', 'methylenetetrahydrofolate'], 'c_10f': ['10-formyltetrahydrofolate', '10-CHO-THF', 'formyltetrahydrofolate'], 'c_dhf': ['dihydrofolate', 'DHF', '7,8-dihydrofolate'], 'aic': ['5-aminoimidazole-4-carboxamide ribonucleotide', 'AICAR', 'ZMP'], 'c_glu': ['glutamate', 'L-glutamate', 'L-Glu'], 'c_cys': ['cysteine', 'L-cysteine', 'L-Cys'], 'c_gsg': ['glutathione disulfide', 'GSSG', 'oxidized glutathione'], 'c_gsh': ['glutathione', 'GSH', 'reduced glutathione'], 'hcy': ['homocysteine', 'L-homocysteine', 'L-Hcy'], 'c_ser': ['serine', 'L-serine', 'L-Ser'], 'sah': ['S-adenosylhomocysteine', 'SAH', 'AdoHcy'], 'sam': ['S-adenosylmethionine', 'SAM', 'AdoMet'], 'met': ['methionine', 'L-methionine', 'L-Met'], 'c_coo': ['formate', 'formic acid', 'HCOOH'], 'species_1': ['decyl-S-adenosylmethionine', 'dcSAM', 'decyl-SAM'], 'species_2': ['putrescine', '1,4-diaminobutane', 'Put'], 'species_3': ['spermine', '1,12-diamino-4,9-diazadodecane', 'Spm'], 'species_4': ['spermidine', '1,8-diamino-4-azaoctane', 'Spd'], 'species_5': ['acetylspermine', 'N-acetylspermine', 'AcSpm'], 'species_6': ['acetylspermidine', 'N-acetylspermidine', 'AcSpd'], 'species_7': ['ornithine', 'L-ornithine', 'L-Orn'], 'species_8': ['acetyl-CoA', 'AcCoA', 'acetyl coenzyme A'], 'species_9': ['CoA', 'coenzyme A', 'CoASH'], 'CO': ['carbon monoxide', 'CO', 'carbonyl'], 'm_thf': ['tetrahydrofolate', 'THF', 'tetrahydrofolic acid'], 'm_2cf': ['5,10-methylenetetrahydrofolate', '5,10-CH2-THF', 'methylenetetrahydrofolate'], 'm_10f': ['10-formyltetrahydrofolate', '10-CHO-THF', 'formyltetrahydrofolate'], 'm_ser': ['serine', 'L-serine', 'L-Ser'], 'm_gly': ['glycine', 'L-glycine', 'L-Gly'], 'm_coo': ['formate', 'formic acid', 'HCOOH'], 'Fol': ['folic acid', 'vitamin B9', 'pteroylglutamic acid'], 'HCHO': ['formaldehyde', 'methanal', 'HCHO'], 'src': ['sarcosine', 'N-methylglycine', 'MGL'], 'dmg': ['dimethylglycine', 'DMG', 'N,N-dimethylglycine'], 'glc': ['glutamylcysteine', 'γ-glutamylcysteine', 'Glu-Cys'], 'c_gly': ['glycine', 'L-glycine', 'L-Gly']}
Evaluating 451/1075: BIOMD0000000451.xml
Evaluating 452/1075: BIOMD0000000452.xml

2025-11-20 12:32:48,052 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000452.txt
LLM response:
mw8f5a7b5c_ca4c_4a4c_85b1_e5d640c426bf (protein): "Ras-GDP", "GDP-bound Ras", "Ras protein"
mwf40d6176_abfc_4a30_886f_83a19fcffc48 (complex): "pEGF-EGFR2-pShc-Grb2-SOS-Ras-GDP", "EGFR2 complex", "Ras-GDP bound complex"
mwa54a9c38_c98b_45e5_8432_4119fb777e44 (protein): "Ras-GTP", "GTP-bound Ras", "Ras protein"
mw28464aad_8013_4a23_ae09_a406954859a6 (complex): "pEGF-EGFR2-Grb2-SOS-Ras-GDP", "EGFR2 complex", "Ras-GDP bound complex"
mwdf82303e_323f_4c51_a858_56a59233cd98 (complex): "Ras-GTP-Ras-GAP", "Ras-GAP complex", "GTP-bound Ras complex"
mwd7bf31ba_b05c_4c45_bb2f_6a2468a2a507 (complex): "pEGF-EGFR2-Ras-GAP-Ras-GTP", "EGFR2 complex", "Ras-GAP bound complex"
mw83de7813_4941_45a6_a320_a551165bf22a (complex): "Raf1-Ras-GTP", "Raf1 complex", "GTP-bound Ras complex"
Reason: The species are annotated based on their display names and the reactions they are involved in. The model appears to be a signaling pathway model, specifically the EGFR signaling pathway. The species are identified as proteins, complexes, or unknown based on their names and interactions. For example, mw8f5a7b5c_ca4c_4a4c_85b1_e5d640c426bf is identified as a protein (Ras-GDP) because it is involved in a reaction where it binds to GDP. Similarly, mwa54a9c38_c98b_45e5_8432_4119fb777e44 is identified as a protein (Ras-GTP) because it is involved in a reaction where it binds to GTP. The complexes are identified based on their display names, which indicate the proteins they are composed of.
Synonyms dict: {'mw8f5a7b5c_ca4c_4a4c_85b1_e5d640c426bf': ['Ras-GDP', 'GDP-bound Ras', 'Ras protein'], 'mwf40d6176_abfc_4a30_886f_83a19fcffc48': ['pEGF-EGFR2-pShc-Grb2-SOS-Ras-GDP', 'EGFR2 complex', 'Ras-GDP bound complex'], 'mwa54a9c38_c98b_45e5_8432_4119fb777e44': ['Ras-GTP', 'GTP-bound Ras', 'Ras protein'], 'mw28464aad_8013_4a23_ae09_a406954859a6': ['pEGF-EGFR2-Grb2-SOS-Ras-GDP', 'EGFR2 complex', 'Ras-GDP bound complex'], 'mwdf82303e_323f_4c51_a858_56a59233cd98': ['Ras-GTP-Ras-GAP', 'Ras-GAP complex', 'GTP-bound Ras complex'], 'mwd7bf31ba_b05c_4c45_bb2f_6a2468a2a507': ['pEGF-EGFR2-Ras-GAP-Ras-GTP', 'EGFR2 complex', 'Ras-GAP bound complex'], 'mw83de7813_4941_45a6_a320_a551165bf22a': ['Raf1-Ras-GTP', 'Raf1 complex', 'GTP-bound Ras complex']}
Evaluating 453/1075: BIOMD0000000453.xml

2025-11-20 12:32:56,039 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:32:56,236 - WARNING - Skipping BIOMD0000000454.xml - no results generated
2025-11-20 12:32:56,241 - WARNING - Skipping BIOMD0000000455.xml - no results generated
2025-11-20 12:32:56,245 - WARNING - Skipping BIOMD0000000456.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000453.txt
LLM response:
mw8f5a7b5c_ca4c_4a4c_85b1_e5d640c426bf (protein): "Ras-GDP", "GDP-bound Ras", "Ras protein"
mwf40d6176_abfc_4a30_886f_83a19fcffc48 (complex): "pEGF-EGFR2-pShc-Grb2-SOS-Ras-GDP", "EGFR2 complex with Ras-GDP", "pEGFR2-Ras-GDP complex"
mwa54a9c38_c98b_45e5_8432_4119fb777e44 (protein): "Ras-GTP", "GTP-bound Ras", "Ras protein"
mw28464aad_8013_4a23_ae09_a406954859a6 (complex): "pEGF-EGFR2-Grb2-SOS-Ras-GDP", "EGFR2 complex with Ras-GDP", "pEGFR2-Ras-GDP complex"
mwdf82303e_323f_4c51_a858_56a59233cd98 (complex): "Ras-GTP-Ras-GAP", "Ras-GAP complex with Ras-GTP", "Ras-GTP-RasGAP complex"
mwd7bf31ba_b05c_4c45_bb2f_6a2468a2a507 (complex): "pEGF-EGFR2-Ras-GAP-Ras-GTP", "EGFR2 complex with Ras-GAP and Ras-GTP", "pEGFR2-Ras-GAP-Ras-GTP complex"
mw83de7813_4941_45a6_a320_a551165bf22a (complex): "Raf1-Ras-GTP", "Raf1 complex with Ras-GTP", "Raf1-Ras complex"

Reason: The entity types are determined based on the display names and the context of the EGFR signaling pathway. Ras-GDP and Ras-GTP are proteins, while the other species are complexes of proteins. The standardized names are based on common synonyms used in the literature. The ranking of the names is based on their likelihood of being used to refer to the species in question. The reasons for each species are as follows:
- mw8f5a7b5c_ca4c_4a4c_85b1_e5d640c426bf is a protein because it is referred to as "Ras-GDP", which is a common name for the GDP-bound form of the Ras protein.
- mwf40d6176_abfc_4a30_886f_83a19fcffc48 and mw28464aad_8013_4a23_ae09_a406954859a6 are complexes because they involve multiple proteins (EGFR2, Grb2, SOS, and Ras-GDP).
- mwa54a9c38_c98b_45e5_8432_4119fb777e44 is a protein because it is referred to as "Ras-GTP", which is a common name for the GTP-bound form of the Ras protein.
- mwdf82303e_323f_4c51_a858_56a59233cd98 is a complex because it involves two proteins (Ras-GTP and Ras-GAP).
- mwd7bf31ba_b05c_4c45_bb2f_6a2468a2a507 is a complex because it involves multiple proteins (EGFR2, Ras-GAP, and Ras-GTP).
- mw83de7813_4941_45a6_a320_a551165bf22a is a complex because it involves two proteins (Raf1 and Ras-GTP).
Synonyms dict: {'mw8f5a7b5c_ca4c_4a4c_85b1_e5d640c426bf': ['Ras-GDP', 'GDP-bound Ras', 'Ras protein'], 'mwf40d6176_abfc_4a30_886f_83a19fcffc48': ['pEGF-EGFR2-pShc-Grb2-SOS-Ras-GDP', 'EGFR2 complex with Ras-GDP', 'pEGFR2-Ras-GDP complex'], 'mwa54a9c38_c98b_45e5_8432_4119fb777e44': ['Ras-GTP', 'GTP-bound Ras', 'Ras protein'], 'mw28464aad_8013_4a23_ae09_a406954859a6': ['pEGF-EGFR2-Grb2-SOS-Ras-GDP', 'EGFR2 complex with Ras-GDP', 'pEGFR2-Ras-GDP complex'], 'mwdf82303e_323f_4c51_a858_56a59233cd98': ['Ras-GTP-Ras-GAP', 'Ras-GAP complex with Ras-GTP', 'Ras-GTP-RasGAP complex'], 'mwd7bf31ba_b05c_4c45_bb2f_6a2468a2a507': ['pEGF-EGFR2-Ras-GAP-Ras-GTP', 'EGFR2 complex with Ras-GAP and Ras-GTP', 'pEGFR2-Ras-GAP-Ras-GTP complex'], 'mw83de7813_4941_45a6_a320_a551165bf22a': ['Raf1-Ras-GTP', 'Raf1 complex with Ras-GTP', 'Raf1-Ras complex']}
Evaluating 454/1075: BIOMD0000000454.xml
Evaluating 455/1075: BIOMD0000000455.xml
Evaluating 456/1075: BIOMD0000000456.xml
Evaluating 457/1075: BIOMD0000000457.xml

2025-11-20 12:34:04,441 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000457.txt
LLM response:
species_143 (complex): "80S ribosome with eEF2 and aa-tRNA", "eukaryotic ribosome complex", "translation initiation complex"
species_144 (complex): "80S ribosome", "eukaryotic ribosome", "ribosomal complex"
species_145 (complex): "80S ribosome with eEF3 and tRNA", "eukaryotic ribosome complex", "translation elongation complex"
species_147 (complex): "80S ribosome with eEF1A and aa-tRNA", "eukaryotic ribosome complex", "translation initiation complex"
species_148 (complex): "80S ribosome with aa-tRNA", "eukaryotic ribosome complex", "ribosomal complex"
species_149 (complex): "80S ribosome with eEF2 and aa-tRNA", "eukaryotic ribosome complex", "translation elongation complex"
species_150 (complex): "80S ribosome", "eukaryotic ribosome", "ribosomal complex"
species_151 (complex): "80S ribosome with eEF3 and tRNA", "eukaryotic ribosome complex", "translation elongation complex"
species_153 (complex): "80S ribosome with eEF1A and aa-tRNA", "eukaryotic ribosome complex", "translation initiation complex"
species_154 (complex): "80S ribosome with aa-tRNA", "eukaryotic ribosome complex", "ribosomal complex"
species_155 (complex): "80S ribosome with eEF2 and aa-tRNA", "eukaryotic ribosome complex", "translation elongation complex"
species_156 (complex): "80S ribosome", "eukaryotic ribosome", "ribosomal complex"
species_157 (complex): "80S ribosome with eEF3 and tRNA", "eukaryotic ribosome complex", "translation elongation complex"
species_159 (complex): "80S ribosome", "eukaryotic ribosome", "ribosomal complex"
species_160 (complex): "80S ribosome with eEF3 and tRNA", "eukaryotic ribosome complex", "translation elongation complex"
species_161 (protein): "eRF3", "eukaryotic release factor 3", "translation termination factor"
species_162 (protein): "eRF3", "eukaryotic release factor 3", "translation termination factor"
species_164 (complex): "eRF1 and eRF3 complex", "translation termination complex", "eukaryotic release factor complex"
species_165 (complex): "80S ribosome with eRF1 and eRF3", "eukaryotic ribosome complex", "translation termination complex"
Reason: The species are mostly complexes of ribosomes with various translation factors and tRNAs, which are involved in the process of mRNA translation in eukaryotic cells. The entity types are determined based on the composition of each complex and the role it plays in the translation process. species_161 and species_162 are proteins, specifically eRF3, which is involved in translation termination. species_164 is a complex of eRF1 and eRF3, which is also involved in translation termination. The standardized names and synonyms are based on the common names used in the field of molecular biology and the specific components of each complex.
Synonyms dict: {'species_1': ['eIF2', 'eukaryotic translation initiation factor 2', 'eIF-2'], 'species_3': ['eIF2_GDP_eIF2B', 'eIF2-eIF2B complex', 'eIF2B-eIF2-GDP'], 'species_4': ['eIF2_GTP', 'eukaryotic translation initiation factor 2 GTP-bound', 'eIF2-GTP'], 'species_5': ['Met-tRNA', 'methionyl-tRNA', 'met-tRNAi'], 'species_6': ['eIF2_GTP_Met-tRNA', 'eIF2-GTP-met-tRNAi complex', '43S preinitiation complex'], 'species_10': ['eIF3_eIF5_eIF2_GTP_Met-tRNA', 'eIF3-eIF5-eIF2-GTP-met-tRNAi complex', '48S preinitiation complex'], 'species_12': ['eIF1_eIF3_eIF5_eIF2_GTP_Met-tRNA', 'eIF1-eIF3-eIF5-eIF2-GTP-met-tRNAi complex', '48S preinitiation complex'], 'species_31': ['eIF5B_GDP', 'eukaryotic translation initiation factor 5B GDP-bound', 'eIF5B-GDP'], 'species_32': ['eIF5B_GTP', 'eukaryotic translation initiation factor 5B GTP-bound', 'eIF5B-GTP'], 'species_33': ['48S_Ded1_eIF5B_GTP', '48S-Ded1-eIF5B-GTP complex', '48S preinitiation complex with Ded1 and eIF5B'], 'species_35': ['eEF1A_GDP', 'eukaryotic translation elongation factor 1A GDP-bound', 'eEF1A-GDP'], 'species_37': ['eEF1A_GDP_eEF1B', 'eEF1A-eEF1B complex', 'eEF1A-GDP-eEF1B'], 'species_38': ['eEF1A_GTP', 'eukaryotic translation elongation factor 1A GTP-bound', 'eEF1A-GTP'], 'species_40': ['aa-tRNA_eEF1A_GTP', 'aminoacyl-tRNA-eEF1A-GTP complex', 'aa-tRNA-eEF1A-GTP'], 'species_41': ['eEF2_GDP', 'eukaryotic translation elongation factor 2 GDP-bound', 'eEF2-GDP'], 'species_42': ['eEF2_GTP', 'eukaryotic translation elongation factor 2 GTP-bound', 'eEF2-GTP'], 'species_43': ['eEF3_GDP', 'eukaryotic translation elongation factor 3 GDP-bound', 'eEF3-GDP'], 'species_44': ['eEF3_GTP', 'eukaryotic translation elongation factor 3 GTP-bound', 'eEF3-GTP'], 'species_45': ['tRNA', 'transfer RNA', 'tRNA molecule'], 'species_47': ['80S_aa-tRNA_eEF1A_GTP_1', '80S-aa-tRNA-eEF1A-GTP complex 1', '80S ribosome with aa-tRNA and eEF1A-GTP'], 'species_48': ['80S_aa-tRNA_1', '80S-aa-tRNA complex 1', '80S ribosome with aa-tRNA'], 'species_49': ['80S_aa-tRNA_eEF2_GTP_1', '80S-aa-tRNA-eEF2-GTP complex 1', '80S ribosome with aa-tRNA and eEF2-GTP'], 'species_51': ['80S_aa-tRNA_eEF1A_GTP_2', '80S-aa-tRNA-eEF1A-GTP complex 2', '80S ribosome with aa-tRNA and eEF1A-GTP'], 'species_52': ['80S_aa-tRNA_2', '80S-aa-tRNA complex 2', '80S ribosome with aa-tRNA'], 'species_53': ['80S_aa-tRNA_eEF2_GTP_2', '80S-aa-tRNA-eEF2-GTP complex 2', '80S ribosome with aa-tRNA and eEF2-GTP'], 'species_54': ['80S_tRNA_2', '80S-tRNA complex 2', '80S ribosome with tRNA'], 'species_55': ['80S_tRNA_eEF3_GTP_2', '80S-tRNA-eEF3-GTP complex 2', '80S ribosome with tRNA and eEF3-GTP'], 'species_57': ['80S_aa-tRNA_eEF1A_GTP_3', '80S-aa-tRNA-eEF1A-GTP complex 3', '80S ribosome with aa-tRNA and eEF1A-GTP'], 'species_58': ['80S_aa-tRNA_3', '80S-aa-tRNA complex 3', '80S ribosome with aa-tRNA'], 'species_59': ['80S_aa-tRNA_eEF2_GTP_3', '80S-aa-tRNA-eEF2-GTP complex 3', '80S ribosome with aa-tRNA and eEF2-GTP'], 'species_60': ['80S_tRNA_3', '80S-tRNA complex 3', '80S ribosome with tRNA'], 'species_61': ['80S_tRNA_eEF3_GTP_3', '80S-tRNA-eEF3-GTP complex 3', '80S ribosome with tRNA and eEF3-GTP'], 'species_63': ['80S_aa-tRNA_eEF1A_GTP_4', '80S-aa-tRNA-eEF1A-GTP complex 4', '80S ribosome with aa-tRNA and eEF1A-GTP'], 'species_64': ['80S_aa-tRNA_4', '80S-aa-tRNA complex 4', '80S ribosome with aa-tRNA'], 'species_65': ['80S_aa-tRNA_eEF2_GTP_4', '80S-aa-tRNA-eEF2-GTP complex 4', '80S ribosome with aa-tRNA and eEF2-GTP'], 'species_66': ['80S_tRNA_4', '80S-tRNA complex 4', '80S ribosome with tRNA'], 'species_67': ['80S_tRNA_eEF3_GTP_4', '80S-tRNA-eEF3-GTP complex 4', '80S ribosome with tRNA and eEF3-GTP'], 'species_69': ['80S_aa-tRNA_eEF1A_GTP_5', '80S-aa-tRNA-eEF1A-GTP complex 5', '80S ribosome with aa-tRNA and eEF1A-GTP'], 'species_70': ['80S_aa-tRNA_5', '80S-aa-tRNA complex 5', '80S ribosome with aa-tRNA'], 'species_71': ['80S_aa-tRNA_eEF2_GTP_5', '80S-aa-tRNA-eEF2-GTP complex 5', '80S ribosome with aa-tRNA and eEF2-GTP'], 'species_72': ['80S_tRNA_5', '80S-tRNA complex 5', '80S ribosome with tRNA'], 'species_73': ['80S_tRNA_eEF3_GTP_5', '80S-tRNA-eEF3-GTP complex 5', '80S ribosome with tRNA and eEF3-GTP'], 'species_75': ['80S_aa-tRNA_eEF1A_GTP_6', '80S-aa-tRNA-eEF1A-GTP complex 6', '80S ribosome with aa-tRNA and eEF1A-GTP'], 'species_76': ['80S_aa-tRNA_6', '80S-aa-tRNA complex 6', '80S ribosome with aa-tRNA'], 'species_77': ['80S_aa-tRNA_eEF2_GTP_6', '80S-aa-tRNA-eEF2-GTP complex 6', '80S ribosome with aa-tRNA and eEF2-GTP'], 'species_78': ['80S_tRNA_6', '80S-tRNA complex 6', '80S ribosome with tRNA'], 'species_79': ['80S_tRNA_eEF3_GTP_6', '80S-tRNA-eEF3-GTP complex 6', '80S ribosome with tRNA and eEF3-GTP'], 'species_81': ['80S_aa-tRNA_eEF1A_GTP_7', '80S-aa-tRNA-eEF1A-GTP complex 7', '80S ribosome with aa-tRNA and eEF1A-GTP'], 'species_82': ['80S_aa-tRNA_7', '80S-aa-tRNA complex 7', '80S ribosome with aa-tRNA'], 'species_83': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex'], 'species_39': ['aa-tRNA', 'aminoacyl-tRNA', 'charged tRNA'], 'species_84': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_85': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_87': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_88': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_89': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_90': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_91': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_93': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_94': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_95': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_96': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_97': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_99': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_100': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_101': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_102': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_103': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_105': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_106': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_107': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_108': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_109': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_111': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_112': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_113': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_114': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_115': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_117': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_118': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_119': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_120': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_121': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_123': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_124': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_125': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_126': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_127': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_129': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_130': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_131': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_132': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_133': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_135': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_136': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_137': ['80S ribosome with eEF2 and tRNA', 'ribosome complex with eEF2', 'eukaryotic ribosome complex with eEF2'], 'species_138': ['80S ribosome', 'eukaryotic ribosome', 'ribosome complex'], 'species_139': ['80S ribosome with eEF3 and tRNA', 'ribosome complex with eEF3', 'eukaryotic ribosome complex with eEF3'], 'species_141': ['80S ribosome with eEF1A and tRNA', 'ribosome complex with eEF1A', 'eukaryotic ribosome complex with eEF1A'], 'species_142': ['80S ribosome with tRNA', 'ribosome complex', 'eukaryotic ribosome complex'], 'species_143': ['80S ribosome with eEF2 and aa-tRNA', 'eukaryotic ribosome complex', 'translation initiation complex'], 'species_144': ['80S ribosome', 'eukaryotic ribosome', 'ribosomal complex'], 'species_145': ['80S ribosome with eEF3 and tRNA', 'eukaryotic ribosome complex', 'translation elongation complex'], 'species_147': ['80S ribosome with eEF1A and aa-tRNA', 'eukaryotic ribosome complex', 'translation initiation complex'], 'species_148': ['80S ribosome with aa-tRNA', 'eukaryotic ribosome complex', 'ribosomal complex'], 'species_149': ['80S ribosome with eEF2 and aa-tRNA', 'eukaryotic ribosome complex', 'translation elongation complex'], 'species_150': ['80S ribosome', 'eukaryotic ribosome', 'ribosomal complex'], 'species_151': ['80S ribosome with eEF3 and tRNA', 'eukaryotic ribosome complex', 'translation elongation complex'], 'species_153': ['80S ribosome with eEF1A and aa-tRNA', 'eukaryotic ribosome complex', 'translation initiation complex'], 'species_154': ['80S ribosome with aa-tRNA', 'eukaryotic ribosome complex', 'ribosomal complex'], 'species_155': ['80S ribosome with eEF2 and aa-tRNA', 'eukaryotic ribosome complex', 'translation elongation complex'], 'species_156': ['80S ribosome', 'eukaryotic ribosome', 'ribosomal complex'], 'species_157': ['80S ribosome with eEF3 and tRNA', 'eukaryotic ribosome complex', 'translation elongation complex'], 'species_159': ['80S ribosome', 'eukaryotic ribosome', 'ribosomal complex'], 'species_160': ['80S ribosome with eEF3 and tRNA', 'eukaryotic ribosome complex', 'translation elongation complex'], 'species_161': ['eRF3', 'eukaryotic release factor 3', 'translation termination factor'], 'species_162': ['eRF3', 'eukaryotic release factor 3', 'translation termination factor'], 'species_164': ['eRF1 and eRF3 complex', 'translation termination complex', 'eukaryotic release factor complex'], 'species_165': ['80S ribosome with eRF1 and eRF3', 'eukaryotic ribosome complex', 'translation termination complex']}
Evaluating 458/1075: BIOMD0000000458.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000458.txt
LLM response:
p3g (chemical): "3-phosphoglycerate", "3-phosphoglyceric acid", "glycerate 3-phosphate"
php (chemical): "phosphohydroxypyruvate", "phosphohydroxypyruvic acid", "hydroxypyruvate phosphate"
pser (chemical): "phosphoserine", "O-phosphoserine", "L-phosphoserine"
ser (chemical): "serine", "L-serine", "amino acid serine"
Reason: All species are identified as chemicals because they are intermediates in the serine biosynthesis metabolic pathway, and their display names match known chemical compounds in the pathway. The standardized names and synonyms provided are based on common names used in biochemistry and metabolism.
Synonyms dict: {'p3g': ['3-phosphoglycerate', '3-phosphoglyceric acid', 'glycerate 3-phosphate'], 'php': ['phosphohydroxypyruvate', 'phosphohydroxypyruvic acid', 'hydroxypyruvate phosphate'], 'pser': ['phosphoserine', 'O-phosphoserine', 'L-phosphoserine'], 'ser': ['serine', 'L-serine', 'amino acid serine']}
Evaluating 459/1075: BIOMD0000000459.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000459.txt
LLM response:
IPTG (chemical): "isopropyl β-D-1-thiogalactopyranoside", "IPTG", "isopropylthiogalactoside"
sigb (protein): "sigma B", "σB", "sigB"
Reason: IPTG is a chemical inducer commonly used in molecular biology to activate the lac operon, and its full name is isopropyl β-D-1-thiogalactopyranoside. sigb refers to the sigma B protein, a transcription factor in B. subtilis, which is a protein entity.
Synonyms dict: {'IPTG': ['isopropyl β-D-1-thiogalactopyranoside', 'IPTG', 'isopropylthiogalactoside'], 'sigb': ['sigma B', 'σB', 'sigB']}
Evaluating 460/1075: BIOMD0000000460.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000460.txt
LLM response:
IPTG (chemical): "isopropyl β-D-1-thiogalactopyranoside", "IPTG", "isopropylthiogalactoside"
sigb (protein): "sigma B", "σB", "sigma factor B"
Reason: IPTG is a chemical inducer commonly used in molecular biology to induce gene expression, and its full name is isopropyl β-D-1-thiogalactopyranoside. sigb is a protein, specifically a sigma factor, which is a type of transcription factor in bacteria. The model description and notes confirm the role of IPTG as an inducer and sigb as a sigma factor.
Synonyms dict: {'IPTG': ['isopropyl β-D-1-thiogalactopyranoside', 'IPTG', 'isopropylthiogalactoside'], 'sigb': ['sigma B', 'σB', 'sigma factor B']}
Evaluating 461/1075: BIOMD0000000461.xml

2025-11-20 12:34:14,404 - WARNING - Skipping BIOMD0000000462.xml - no results generated
2025-11-20 12:34:14,431 - WARNING - Skipping BIOMD0000000463.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000461.txt
LLM response:
IPTG (chemical): "isopropyl β-D-1-thiogalactopyranoside", "IPTG", "isopropylthiogalactoside"
sigb (protein): "sigma B", "σB", "sigma factor B"
Reason: IPTG is a chemical inducer commonly used in molecular biology to induce gene expression, and its full name is isopropyl β-D-1-thiogalactopyranoside. sigb is a protein, specifically a sigma factor, which is a type of transcription factor involved in the regulation of gene expression in bacteria. The model description and notes confirm the roles of IPTG and sigb in the context of the B. subtilis transcription inhibition model.
Synonyms dict: {'IPTG': ['isopropyl β-D-1-thiogalactopyranoside', 'IPTG', 'isopropylthiogalactoside'], 'sigb': ['sigma B', 'σB', 'sigma factor B']}
Evaluating 462/1075: BIOMD0000000462.xml
Evaluating 463/1075: BIOMD0000000463.xml
Evaluating 464/1075: BIOMD0000000464.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000464.txt
LLM response:
s1 (chemical): "calcium ion", "Ca2+", "extracellular calcium"
s2 (chemical): "cytosolic calcium", "Ca2+", "calcium ion"
s3 (chemical): "intracellular calcium", "Ca2+", "calcium ion"
s4 (chemical): "bound calcium", "Ca2+", "calcium ion"
s6 (chemical): "inositol trisphosphate", "IP3", "myo-inositol 1,4,5-trisphosphate"
Reason: The model is related to calcium influx and eNOS activation, indicating that the species are related to calcium signaling. s1, s2, s3, and s4 are likely different forms or locations of calcium ions. s6 is identified as IP3, a known second messenger involved in calcium signaling. The reaction network and display names support these annotations, with calcium ions moving between different locations and IP3 playing a role in the signaling pathway.
Synonyms dict: {'s1': ['calcium ion', 'Ca2+', 'extracellular calcium'], 's2': ['cytosolic calcium', 'Ca2+', 'calcium ion'], 's3': ['intracellular calcium', 'Ca2+', 'calcium ion'], 's4': ['bound calcium', 'Ca2+', 'calcium ion'], 's6': ['inositol trisphosphate', 'IP3', 'myo-inositol 1,4,5-trisphosphate']}
Evaluating 465/1075: BIOMD0000000465.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000465.txt
LLM response:
s19 (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PIP2", "PtdIns(4,5)P2"
s17 (chemical): "Phosphatidylinositol 3-phosphate", "PI3P", "PtdIns3P"
Reason: s19 and s17 are annotated as chemical entities because they are involved in a biochemical reaction and their display names "PIP2" and "PI3P" are known phosphoinositide lipids, which are a class of chemical signaling molecules. The reaction s19 => s17 and s17 => s19 suggests a conversion between these two phosphoinositide species, further supporting their classification as chemicals.
Synonyms dict: {'s19': ['Phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'PtdIns(4,5)P2'], 's17': ['Phosphatidylinositol 3-phosphate', 'PI3P', 'PtdIns3P']}
Evaluating 466/1075: BIOMD0000000466.xml

2025-11-20 12:34:20,365 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:34:20,365 - WARNING - Skipping BIOMD0000000466.xml - no results generated

Evaluating 467/1075: BIOMD0000000467.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000467.txt
LLM response:
s3 (chemical): "calcium ion", "Ca2+", "calcium"
s45 (complex): "eNOS-CaM-Ca4", "endothelial nitric oxide synthase-calmodulin-calcium", "eNOS-calmodulin complex"
s47 (chemical): "calmodulin-calcium", "CaM-Ca4", "calcium-calmodulin"
s48 (chemical): "calmodulin-calcium", "CaM-Ca2", "calcium-calmodulin"
s50 (complex): "eNOS-CaM-Ca2", "endothelial nitric oxide synthase-calmodulin-calcium", "eNOS-calmodulin complex"
s58 (complex): "Hsp90-eNOS-CaM-Ca4", "Hsp90-endothelial nitric oxide synthase-calmodulin-calcium", "Hsp90-eNOS complex"
s60 (complex): "Hsp90-p-eNOS-CaM-Ca4", "Hsp90-phosphorylated endothelial nitric oxide synthase-calmodulin-calcium", "Hsp90-p-eNOS complex"
s61 (complex): "Hsp90-eNOS-CaM-Ca2", "Hsp90-endothelial nitric oxide synthase-calmodulin-calcium", "Hsp90-eNOS complex"
s62 (complex): "Hsp90-p-eNOS-CaM-Ca2", "Hsp90-phosphorylated endothelial nitric oxide synthase-calmodulin-calcium", "Hsp90-p-eNOS complex"
s63 (chemical): "L-arginine", "arginine", "L-arg"
s64 (chemical): "nitric oxide", "NO", "nitrogen monoxide"
Reason: The species were annotated based on their display names and the context of the model, which appears to be related to shear stress-induced NO production. The entity types were determined by the presence of specific keywords such as "eNOS" (endothelial nitric oxide synthase, a protein), "CaM" (calmodulin, a protein), "Ca" (calcium, a chemical), and "Hsp90" (heat shock protein 90, a protein). The complexes were identified by the presence of multiple protein and/or chemical components. s3 was identified as a chemical (calcium ion) based on its display name "Ca_c". s63 and s64 were identified as chemicals (L-arginine and nitric oxide, respectively) based on their display names and roles in the model.
Synonyms dict: {'s3': ['calcium ion', 'Ca2+', 'calcium'], 's45': ['eNOS-CaM-Ca4', 'endothelial nitric oxide synthase-calmodulin-calcium', 'eNOS-calmodulin complex'], 's47': ['calmodulin-calcium', 'CaM-Ca4', 'calcium-calmodulin'], 's48': ['calmodulin-calcium', 'CaM-Ca2', 'calcium-calmodulin'], 's50': ['eNOS-CaM-Ca2', 'endothelial nitric oxide synthase-calmodulin-calcium', 'eNOS-calmodulin complex'], 's58': ['Hsp90-eNOS-CaM-Ca4', 'Hsp90-endothelial nitric oxide synthase-calmodulin-calcium', 'Hsp90-eNOS complex'], 's60': ['Hsp90-p-eNOS-CaM-Ca4', 'Hsp90-phosphorylated endothelial nitric oxide synthase-calmodulin-calcium', 'Hsp90-p-eNOS complex'], 's61': ['Hsp90-eNOS-CaM-Ca2', 'Hsp90-endothelial nitric oxide synthase-calmodulin-calcium', 'Hsp90-eNOS complex'], 's62': ['Hsp90-p-eNOS-CaM-Ca2', 'Hsp90-phosphorylated endothelial nitric oxide synthase-calmodulin-calcium', 'Hsp90-p-eNOS complex'], 's63': ['L-arginine', 'arginine', 'L-arg'], 's64': ['nitric oxide', 'NO', 'nitrogen monoxide']}
Evaluating 468/1075: BIOMD0000000468.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000468.txt
LLM response:
s1 (chemical): "calcium ion", "Ca2+", "extracellular calcium"
s2 (chemical): "calcium ion", "Ca2+", "cytosolic calcium"
s3 (chemical): "calcium ion", "Ca2+", "cytosolic calcium"
s4 (chemical): "calcium ion", "Ca2+", "buffered calcium"
s6 (chemical): "inositol trisphosphate", "IP3", "myo-inositol 1,4,5-trisphosphate"
s19 (chemical): "phosphatidylinositol 4,5-bisphosphate", "PIP2", "phosphatidylinositol(4,5)P2"
s45 (complex): "eNOS-CaM-Ca4 complex", "endothelial nitric oxide synthase complex", "eNOS-calmodulin-Ca2+ complex"
s47 (complex): "CaM-Ca4 complex", "calmodulin-Ca2+ complex", "CaM-Ca4"
s48 (complex): "CaM-Ca2 complex", "calmodulin-Ca2+ complex", "CaM-Ca2"
s50 (complex): "eNOS-CaM-Ca2 complex", "endothelial nitric oxide synthase complex", "eNOS-calmodulin-Ca2+ complex"
s58 (complex): "Hsp90-eNOS-CaM-Ca4 complex", "Hsp90-endothelial nitric oxide synthase complex", "Hsp90-eNOS-calmodulin-Ca2+ complex"
s60 (complex): "Hsp90-p-eNOS-CaM-Ca4 complex", "Hsp90-phosphorylated endothelial nitric oxide synthase complex", "Hsp90-p-eNOS-calmodulin-Ca2+ complex"
s61 (complex): "Hsp90-eNOS-CaM-Ca2 complex", "Hsp90-endothelial nitric oxide synthase complex", "Hsp90-eNOS-calmodulin-Ca2+ complex"
s62 (complex): "Hsp90-p-eNOS-CaM-Ca2 complex", "Hsp90-phosphorylated endothelial nitric oxide synthase complex", "Hsp90-p-eNOS-calmodulin-Ca2+ complex"
s64 (chemical): "nitric oxide", "NO", "nitrogen monoxide"
s102 (complex): "Ras:GTP complex", "Ras protein-GTP complex", "Ras-GTP"
s103 (complex): "Ras:GDP complex", "Ras protein-GDP complex", "Ras-GDP"

Reason: The entity types were determined based on the display names and the reactions in the model. For example, s1, s2, and s3 are all related to calcium ions, so they are classified as chemicals. s45, s47, s48, s50, s58, s60, s61, and s62 are all complexes involving proteins such as eNOS, CaM, and Hsp90, so they are classified as complexes. s6 and s19 are classified as chemicals based on their display names, which match known chemical compounds. s64 is classified as a chemical based on its display name, which matches the common name for nitric oxide. s102 and s103 are classified as complexes involving the Ras protein and either GTP or GDP.
Synonyms dict: {'s1': ['calcium ion', 'Ca2+', 'extracellular calcium'], 's2': ['calcium ion', 'Ca2+', 'cytosolic calcium'], 's3': ['calcium ion', 'Ca2+', 'cytosolic calcium'], 's4': ['calcium ion', 'Ca2+', 'buffered calcium'], 's6': ['inositol trisphosphate', 'IP3', 'myo-inositol 1,4,5-trisphosphate'], 's19': ['phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'phosphatidylinositol(4,5)P2'], 's45': ['eNOS-CaM-Ca4 complex', 'endothelial nitric oxide synthase complex', 'eNOS-calmodulin-Ca2+ complex'], 's47': ['CaM-Ca4 complex', 'calmodulin-Ca2+ complex', 'CaM-Ca4'], 's48': ['CaM-Ca2 complex', 'calmodulin-Ca2+ complex', 'CaM-Ca2'], 's50': ['eNOS-CaM-Ca2 complex', 'endothelial nitric oxide synthase complex', 'eNOS-calmodulin-Ca2+ complex'], 's58': ['Hsp90-eNOS-CaM-Ca4 complex', 'Hsp90-endothelial nitric oxide synthase complex', 'Hsp90-eNOS-calmodulin-Ca2+ complex'], 's60': ['Hsp90-p-eNOS-CaM-Ca4 complex', 'Hsp90-phosphorylated endothelial nitric oxide synthase complex', 'Hsp90-p-eNOS-calmodulin-Ca2+ complex'], 's61': ['Hsp90-eNOS-CaM-Ca2 complex', 'Hsp90-endothelial nitric oxide synthase complex', 'Hsp90-eNOS-calmodulin-Ca2+ complex'], 's62': ['Hsp90-p-eNOS-CaM-Ca2 complex', 'Hsp90-phosphorylated endothelial nitric oxide synthase complex', 'Hsp90-p-eNOS-calmodulin-Ca2+ complex'], 's64': ['nitric oxide', 'NO', 'nitrogen monoxide'], 's102': ['Ras:GTP complex', 'Ras protein-GTP complex', 'Ras-GTP'], 's103': ['Ras:GDP complex', 'Ras protein-GDP complex', 'Ras-GDP']}
Evaluating 469/1075: BIOMD0000000469.xml

2025-11-20 12:41:22,549 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000469.txt
LLM response:
s_1672 (chemical): "trans-Hex-2-enoyl-CoA", "Hex-2-enoyl-CoA", "2-Hexenoyl-CoA"
s_1674 (chemical): "trans-Hexadec-2-enoyl-CoA", "Hexadec-2-enoyl-CoA", "2-Hexadecenoyl-CoA"
s_1676 (chemical): "trans-Oct-2-enoyl-CoA", "Oct-2-enoyl-CoA", "2-Octenoyl-CoA"
s_1680 (chemical): "trans-Tetradec-2-enoyl-CoA", "Tetradec-2-enoyl-CoA", "2-Tetradecenoyl-CoA"
s_1690 (complex): "tRNA (Glu)", "Glutamyl-tRNA", "Glu-tRNA"
s_1731 (chemical): "Ubiquinol-8", "Ubiquinol", "Coenzyme QH2"
s_1732 (chemical): "Ubiquinone-8", "Ubiquinone", "Coenzyme Q"
s_1733 (chemical): "UDP", "Uridine diphosphate", "Uridine 5'-diphosphate"
s_1734 (chemical): "UDP-2,3-bis(3-hydroxytetradecanoyl)glucosamine", "UDP-2,3-bis(3-hydroxytetradecanoyl)glucose", "UDP-disaccharide"
s_1735 (chemical): "UDP-3-O-(3-hydroxytetradecanoyl)-D-glucosamine", "UDP-3-O-(3-hydroxytetradecanoyl)glucose", "UDP-3-hydroxytetradecanoylglucosamine"
s_1736 (chemical): "UDP-3-O-(3-hydroxytetradecanoyl)-N-acetylglucosamine", "UDP-3-O-(3-hydroxytetradecanoyl)N-acetylglucosamine", "UDP-3-hydroxytetradecanoyl-N-acetylglucosamine"
s_1742 (chemical): "UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine", "UDP-N-acetyl-3-O-(1-carboxyvinyl)glucosamine", "UDP-N-acetylglucosamine"
s_1745 (chemical): "UDP-N-acetyl-D-glucosamine", "UDP-GlcNAc", "Uridine diphosphate N-acetylglucosamine"
s_1750 (chemical): "UDP-N-acetylmuramate", "UDP-N-acetylmuramic acid", "UDP-MurNAc"
s_1751 (chemical): "UDP-N-acetylmuramoyl-L-alanine", "UDP-MurNAc-L-Ala", "UDP-N-acetylmuramoylalanine"
s_1752 (chemical): "UDP-N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate", "UDP-MurNAc-L-Ala-D-Glu-meso-DAP", "UDP-N-acetylmuramoylpentapeptide"
s_1754 (chemical): "UDP-N-acetylmuramoyl-L-alanyl-D-glutamate", "UDP-MurNAc-L-Ala-D-Glu", "UDP-N-acetylmuramoyl dipeptide"
s_1755 (chemical): "UDP-N-acetylmuramoyl-L-alanyl-D-glutamyl-meso-2,6-diaminopimeloyl-D-alanyl-D-alanine", "UDP-MurNAc-L-Ala-D-Glu-meso-DAP-D-Ala-D-Ala", "UDP-N-acetylmuramoylheptapeptide"
s_1762 (chemical): "UMP", "Uridine monophosphate", "Uridine 5'-monophosphate"
s_1765 (chemical): "Undecaprenyl diphosphate", "Undecaprenyl pyrophosphate", "Bactoprenol"
s_1768 (chemical): "Undecaprenyl phosphate", "Undecaprenyl monophosphate", "Bactoprenol phosphate"
s_1776 (chemical): "Undecaprenyl-diphospho-N-acetylmuramoyl-(N-acetylglucosamine)-L-ala-D-glu-meso-2,6-diaminopimeloyl-D-ala-D-ala", "Lipid II", "Undecaprenyl-diphospho-MurNAc-pentapeptide"
s_1791 (chemical): "Uroporphyrinogen III", "Uroporphyrinogen", "Urogen III"
s_1792 (chemical): "UTP", "Uridine triphosphate", "Uridine 5'-triphosphate"
s_1799 (chemical): "Xanthosine 5'-phosphate", "Xanthosine monophosphate", "XMP"
s_1804 (chemical): "Zinc", "Zn2+", "Zinc ion"
s_1806 (chemical): "Zinc", "Zn2+", "Zinc ion"
s_2072 (chemical): "p-Cresol", "4-Methylphenol", "Cresol"
s_2093 (chemical): "S-Adenosyl-4-methylthio-2-oxobutanoate", "SAM", "S-Adenosylmethionine"

Reason: Most species are identified as chemicals due to their involvement in metabolic reactions and presence of chemical suffixes and prefixes. s_1690 is identified as a complex due to its description as tRNA, which is a complex molecule composed of RNA and proteins. The standardized names and synonyms provided are based on common biochemical nomenclature and may vary depending on the specific context or database used. The reactions listed in the model provide clues about the species' roles and relationships, allowing for more accurate identification of entity types and standardized names.

2025-11-20 12:47:10,202 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000470.txt
LLM response:
s_1672 (chemical): "trans-Hex-2-enoyl-CoA", "Hex-2-enoyl-CoA", "2-Hexenoyl-CoA"
s_1674 (chemical): "trans-Hexadec-2-enoyl-CoA", "Hexadec-2-enoyl-CoA", "2-Hexadecenoyl-CoA"
s_1676 (chemical): "trans-Oct-2-enoyl-CoA", "Oct-2-enoyl-CoA", "2-Octenoyl-CoA"
s_1680 (chemical): "trans-Tetradec-2-enoyl-CoA", "Tetradec-2-enoyl-CoA", "2-Tetradecenoyl-CoA"
s_1690 (complex): "tRNA (Glu)", "Glutamyl-tRNA", "Glu-tRNA"
s_1731 (chemical): "Ubiquinol-8", "Coenzyme Q8", "Ubiquinol"
s_1732 (chemical): "Ubiquinone-8", "Coenzyme Q8", "Ubiquinone"
s_1733 (chemical): "UDP", "Uridine diphosphate", "Uridine 5'-diphosphate"
s_1734 (chemical): "UDP-2,3-bis(3-hydroxytetradecanoyl)glucosamine", "UDP-2,3-bis(3-hydroxytetradecanoyl)-GlcN", "UDP-bis(3-hydroxytetradecanoyl)glucosamine"
s_1735 (chemical): "UDP-3-O-(3-hydroxytetradecanoyl)-D-glucosamine", "UDP-3-O-(3-hydroxytetradecanoyl)-GlcN", "UDP-3-hydroxytetradecanoylglucosamine"
s_1736 (chemical): "UDP-3-O-(3-hydroxytetradecanoyl)-N-acetylglucosamine", "UDP-3-O-(3-hydroxytetradecanoyl)-GlcNAc", "UDP-3-hydroxytetradecanoyl-N-acetylglucosamine"
s_1742 (chemical): "UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine", "UDP-N-acetyl-3-O-(1-carboxyvinyl)-GlcN", "UDP-N-acetyl-3-O-(1-carboxyvinyl)glucosamine"
s_1745 (chemical): "UDP-N-acetyl-D-glucosamine", "UDP-GlcNAc", "Uridine diphosphate N-acetylglucosamine"
s_1750 (chemical): "UDP-N-acetylmuramate", "UDP-MurNAc", "Uridine diphosphate N-acetylmuramic acid"
s_1751 (chemical): "UDP-N-acetylmuramoyl-L-alanine", "UDP-MurNAc-L-Ala", "Uridine diphosphate N-acetylmuramoyl-L-alanine"
s_1752 (chemical): "UDP-N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate", "UDP-MurNAc-L-Ala-D-Glu-meso-DAP", "Uridine diphosphate N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate"
s_1754 (chemical): "UDP-N-acetylmuramoyl-L-alanyl-D-glutamate", "UDP-MurNAc-L-Ala-D-Glu", "Uridine diphosphate N-acetylmuramoyl-L-alanyl-D-glutamate"
s_1755 (chemical): "UDP-N-acetylmuramoyl-L-alanyl-D-glutamyl-meso-2,6-diaminopimeloyl-D-alanyl-D-alanine", "UDP-MurNAc-L-Ala-D-Glu-meso-DAP-D-Ala-D-Ala", "Uridine diphosphate N-acetylmuramoyl-L-alanyl-D-glutamyl-meso-2,6-diaminopimeloyl-D-alanyl-D-alanine"
s_1762 (chemical): "UMP", "Uridine monophosphate", "Uridine 5'-monophosphate"
s_1765 (chemical): "Undecaprenyl diphosphate", "Undecaprenyl pyrophosphate", "Bactoprenol"
s_1768 (chemical): "Undecaprenyl phosphate", "Undecaprenyl monophosphate", "Bactoprenol phosphate"
s_1776 (chemical): "Undecaprenyl-diphospho-N-acetylmuramoyl-(N-acetylglucosamine)-L-ala-D-glu-meso-2,6-diaminopimeloyl-D-ala-D-ala", "Lipid II", "Undecaprenyl-diphospho-MurNAc-GlcNAc-L-Ala-D-Glu-meso-DAP-D-Ala-D-Ala"
s_1791 (chemical): "Uroporphyrinogen III", "Urogen III", "Uroporphyrinogen 3"
s_1792 (chemical): "UTP", "Uridine triphosphate", "Uridine 5'-triphosphate"
s_1799 (chemical): "Xanthosine 5'-phosphate", "Xanthosine monophosphate", "Xanthylic acid"
s_1804 (chemical): "Zinc", "Zn2+", "Zinc ion"
s_1806 (chemical): "Zinc", "Zn2+", "Zinc ion"
s_2072 (chemical): "p-Cresol", "4-Methylphenol", "Cresol"
s_2093 (chemical): "S-Adenosyl-4-methylthio-2-oxobutanoate", "S-Adenosyl-4-methylthio-2-oxobutyrate", "AdoMet"

Reason: The entity types are determined based on the display names and the reactions in which the species participate. For example, s_1672, s_1674, and s_1676 are classified as chemicals because they have "CoA" in their display names, which is a common suffix for coenzyme A derivatives. s_1690 is classified as a complex because it is a tRNA molecule. s_1731 and s_1732 are classified as chemicals because they are ubiquinol and ubiquinone, respectively, which are electron carriers in the electron transport chain. The other species are classified similarly based on their display names and reaction participation. The synonyms provided are based on common names and abbreviations used in biochemistry.

2025-11-20 12:51:04,926 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000471.txt
LLM response:
s_1416 (chemical): "S-adenosyl-L-methionine", "AdoMet", "SAM"
s_1427 (chemical): "sedoheptulose 7-phosphate", "Sed-7-P", "SH7P"
s_1428 (complex): "Ser-tRNA(Ser)", "seryl-tRNA(Ser)", "tRNA(Ser)"
s_1429 (chemical): "shikimate", "shikimic acid", "SA"
s_1445 (chemical): "sphinganine", "dihydrosphingosine", "DHS"
s_1447 (chemical): "squalene", "all-trans-squalene", "SQ"
s_1449 (chemical): "stearate", "stearic acid", "C18:0"
s_1454 (chemical): "stearoyl-CoA", "stearoyl-coenzyme A", "C18:0-CoA"
s_1467 (chemical): "sulphate", "sulfate", "SO4"
s_1468 (chemical): "sulphate", "sulfate", "SO4"
s_1469 (chemical): "sulphite", "sulfite", "SO3"
s_1476 (unknown): "UNK"
s_1487 (chemical): "THF", "tetrahydrofolate", "FH4"
s_1491 (complex): "Thr-tRNA(Thr)", "threonyl-tRNA(Thr)", "tRNA(Thr)"
s_1520 (chemical): "trehalose", "mycose", "C12H22O11"
s_1524 (chemical): "triglyceride", "triacylglycerol", "TAG"
s_1527 (complex): "Trp-tRNA(Trp)", "tryptophyl-tRNA(Trp)", "tRNA(Trp)"
s_1535 (chemical): "ubiquinol-6", "coenzyme Q6", "Q6H2"
s_1537 (chemical): "ubiquinone-6", "coenzyme Q6", "Q6"
s_1538 (chemical): "UDP", "uridine diphosphate", "Uridine 5'-diphosphate"
s_1543 (chemical): "UDP-D-glucose", "Uridine 5'-diphosphate-D-glucose", "UDP-Glc"
s_1545 (chemical): "UMP", "uridine monophosphate", "Uridine 5'-monophosphate"
s_1559 (chemical): "UTP", "uridine triphosphate", "Uridine 5'-triphosphate"
s_1561 (complex): "Val-tRNA(Val)", "valyl-tRNA(Val)", "tRNA(Val)"
s_1565 (chemical): "xanthosine-5-phosphate", "Xan-5-P", "XMP"
s_1569 (chemical): "zymosterol", "cholesta-8,24-dien-3beta-ol", "C27H44O"
s_1576 (chemical): "zymosterol intermediate 1a", "Zym-1a", "C27H44O"
s_1577 (chemical): "zymosterol intermediate 1b", "Zym-1b", "C27H44O"
s_1578 (chemical): "zymosterol intermediate 1c", "Zym-1c", "C27H44O"
s_1579 (chemical): "zymosterol intermediate 2", "Zym-2", "C27H44O"
s_1582 (complex): "tRNA(Ala)", "alanyl-tRNA(Ala)", "tRNA(Ala)"
s_1583 (complex): "tRNA(Arg)", "arginyl-tRNA(Arg)", "tRNA(Arg)"
s_1585 (complex): "tRNA(Asn)", "asparaginyl-tRNA(Asn)", "tRNA(Asn)"
s_1587 (complex): "tRNA(Asp)", "aspartyl-tRNA(Asp)", "tRNA(Asp)"
s_1590 (complex): "tRNA(Gln)", "glutaminyl-tRNA(Gln)", "tRNA(Gln)"
s_1591 (complex): "tRNA(Glu)", "glutamyl-tRNA(Glu)", "tRNA(Glu)"
s_1593 (complex): "tRNA(Gly)", "glycyl-tRNA(Gly)", "tRNA(Gly)"
s_1594 (complex): "tRNA(His)", "histidyl-tRNA(His)", "tRNA(His)"
s_1596 (complex): "tRNA(Ile)", "isoleucyl-tRNA(Ile)", "tRNA(Ile)"
s_1598 (complex): "tRNA(Leu)", "leucyl-tRNA(Leu)", "tRNA(Leu)"
s_1600 (complex): "tRNA(Lys)", "lysyl-tRNA(Lys)", "tRNA(Lys)"
s_1602 (complex): "tRNA(Met)", "methionyl-tRNA(Met)", "tRNA(Met)"
s_1604 (complex): "tRNA(Phe)", "phenylalanyl-tRNA(Phe)", "tRNA(Phe)"
s_1606 (complex): "tRNA(Pro)", "prolyl-tRNA(Pro)", "tRNA(Pro)"
s_1607 (complex): "tRNA(Ser)", "seryl-tRNA(Ser)", "tRNA(Ser)"
s_1608 (complex): "tRNA(Thr)", "threonyl-tRNA(Thr)", "tRNA(Thr)"
s_1610 (complex): "tRNA(Trp)", "tryptophyl-tRNA(Trp)", "tRNA(Trp)"
s_1612 (complex): "tRNA(Tyr)", "tyrosyl-tRNA(Tyr)", "tRNA(Tyr)"
s_1614 (complex): "tRNA(Val)", "valyl-tRNA(Val)", "tRNA(Val)"
s_1616 (protein): "TRX1", "thioredoxin 1", "TXN1"
s_1620 (protein): "TRX1 disulphide", "thioredoxin 1 disulfide", "TXN1 disulfide"

Reason: The species were annotated based on their display names and participation in biochemical reactions. Species with names containing "tRNA" were annotated as complexes, as they represent transfer RNA molecules charged with specific amino acids. Species with names containing chemical formulas or common biochemical names (e.g., "S-adenosyl-L-methionine", "squalene") were annotated as chemicals. The protein TRX1 and its disulfide form were annotated as proteins. Species without clear names or reactions were annotated as unknown.

2025-11-20 12:54:44,785 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000472.txt
LLM response:
s_1416 (chemical): "S-adenosyl-L-methionine", "SAM", "AdoMet"
s_1427 (chemical): "sedoheptulose 7-phosphate", "Sed7P", "SH7P"
s_1428 (complex): "Ser-tRNA(Ser)", "seryl-tRNA", "tRNA(Ser)"
s_1429 (chemical): "shikimate", "3,4,5-trihydroxybenzoate", "SA"
s_1445 (chemical): "sphinganine", "dihydrosphingosine", "DHS"
s_1447 (chemical): "squalene", "all-trans-squalene", "SQ"
s_1449 (chemical): "stearate", "octadecanoate", "C18:0"
s_1454 (chemical): "stearoyl-CoA", "octadecanoyl-CoA", "C18:0-CoA"
s_1467 (chemical): "sulphate", "sulfate", "SO4"
s_1468 (chemical): "sulphate", "sulfate", "SO4"
s_1469 (chemical): "sulphite", "sulfite", "SO3"
s_1476 (unknown): "UNK"
s_1487 (chemical): "THF", "tetrahydrofolate", "5,6,7,8-tetrahydrofolic acid"
s_1491 (complex): "Thr-tRNA(Thr)", "threonyl-tRNA", "tRNA(Thr)"
s_1520 (chemical): "trehalose", "mycose", "C12H22O11"
s_1524 (chemical): "triglyceride", "triacylglycerol", "TAG"
s_1527 (complex): "Trp-tRNA(Trp)", "tryptophanyl-tRNA", "tRNA(Trp)"
s_1535 (chemical): "ubiquinol-6", "coenzyme Q6", "CoQ6H2"
s_1537 (chemical): "ubiquinone-6", "coenzyme Q6", "CoQ6"
s_1538 (chemical): "UDP", "uridine 5'-diphosphate", "Uridine diphosphate"
s_1543 (chemical): "UDP-D-glucose", "uridine diphosphate glucose", "UDPG"
s_1545 (chemical): "UMP", "uridine 5'-monophosphate", "Uridine monophosphate"
s_1559 (chemical): "UTP", "uridine 5'-triphosphate", "Uridine triphosphate"
s_1561 (complex): "Val-tRNA(Val)", "valyl-tRNA", "tRNA(Val)"
s_1565 (chemical): "xanthosine-5-phosphate", "Xan5P", "XMP"
s_1569 (chemical): "zymosterol", "lanosterol derivative", "C27H44O"
s_1576 (chemical): "zymosterol intermediate 1a", "zymosterol intermediate", "ZI1a"
s_1577 (chemical): "zymosterol intermediate 1b", "zymosterol intermediate", "ZI1b"
s_1578 (chemical): "zymosterol intermediate 1c", "zymosterol intermediate", "ZI1c"
s_1579 (chemical): "zymosterol intermediate 2", "zymosterol intermediate", "ZI2"
s_1582 (complex): "tRNA(Ala)", "alanyl-tRNA", "tRNA(Ala)"
s_1583 (complex): "tRNA(Arg)", "arginyl-tRNA", "tRNA(Arg)"
s_1585 (complex): "tRNA(Asn)", "asparaginyl-tRNA", "tRNA(Asn)"
s_1587 (complex): "tRNA(Asp)", "aspartyl-tRNA", "tRNA(Asp)"
s_1590 (complex): "tRNA(Gln)", "glutaminyl-tRNA", "tRNA(Gln)"
s_1591 (complex): "tRNA(Glu)", "glutamyl-tRNA", "tRNA(Glu)"
s_1593 (complex): "tRNA(Gly)", "glycyl-tRNA", "tRNA(Gly)"
s_1594 (complex): "tRNA(His)", "histidyl-tRNA", "tRNA(His)"
s_1596 (complex): "tRNA(Ile)", "isoleucyl-tRNA", "tRNA(Ile)"
s_1598 (complex): "tRNA(Leu)", "leucyl-tRNA", "tRNA(Leu)"
s_1600 (complex): "tRNA(Lys)", "lysyl-tRNA", "tRNA(Lys)"
s_1602 (complex): "tRNA(Met)", "methionyl-tRNA", "tRNA(Met)"
s_1604 (complex): "tRNA(Phe)", "phenylalanyl-tRNA", "tRNA(Phe)"
s_1606 (complex): "tRNA(Pro)", "prolyl-tRNA", "tRNA(Pro)"
s_1607 (complex): "tRNA(Ser)", "seryl-tRNA", "tRNA(Ser)"
s_1608 (complex): "tRNA(Thr)", "threonyl-tRNA", "tRNA(Thr)"
s_1610 (complex): "tRNA(Trp)", "tryptophanyl-tRNA", "tRNA(Trp)"
s_1612 (complex): "tRNA(Tyr)", "tyrosyl-tRNA", "tRNA(Tyr)"
s_1614 (complex): "tRNA(Val)", "valyl-tRNA", "tRNA(Val)"
s_1616 (protein): "TRX1", "thioredoxin 1", "TXN1"
s_1620 (protein): "TRX1 disulphide", "thioredoxin 1 disulfide", "TXN1 disulfide"

Reason: Most of the species are identified as chemicals, which is expected in a metabolic model. The tRNA species are identified as complexes, as they are composed of RNA and amino acids. The TRX1 and TRX1 disulphide species are identified as proteins, as they are involved in redox reactions and are known to be proteins in the yeast metabolic network. Some species, such as s_1476, are unknown due to lack of information. The entity types are determined based on the names and reactions in the model, as well as general knowledge of biochemical pathways.

2025-11-20 12:58:46,282 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000473.txt
LLM response:
s_1604 (chemical): "tRNA(Phe)", "phenylalanine tRNA", "tRNA for phenylalanine"
s_1606 (chemical): "tRNA(Pro)", "proline tRNA", "tRNA for proline"
s_1607 (chemical): "tRNA(Ser)", "serine tRNA", "tRNA for serine"
s_1608 (chemical): "tRNA(Thr)", "threonine tRNA", "tRNA for threonine"
s_1610 (chemical): "tRNA(Trp)", "tryptophan tRNA", "tRNA for tryptophan"
s_1612 (chemical): "tRNA(Tyr)", "tyrosine tRNA", "tRNA for tyrosine"
s_1614 (chemical): "tRNA(Val)", "valine tRNA", "tRNA for valine"
s_1616 (protein): "TRX1", "thioredoxin 1", "yeast thioredoxin"
s_1620 (protein): "TRX1 disulphide", "oxidized thioredoxin 1", "disulfide bonded TRX1"
F26bP (chemical): "beta-D-fructose 2,6-bisphosphate", "fructose 2,6-bisphosphate", "F2,6BP"
Reason: The species s_1604 to s_1614 and F26bP are identified as chemicals because they are involved in metabolic reactions and have names that correspond to known biochemical compounds. s_1616 and s_1620 are identified as proteins because they are involved in redox reactions and have names that correspond to known proteins, with s_1620 being the oxidized form of s_1616.

2025-11-20 12:58:54,965 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 12:58:55,093 - WARNING - Skipping BIOMD0000000475.xml - no results generated
2025-11-20 12:58:55,106 - WARNING - Skipping BIOMD0000000476.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000474.txt
LLM response:
GSH (chemical): "glutathione", "reduced glutathione", "GSH"
GSSG (chemical): "oxidized glutathione", "glutathione disulfide", "GSSG"
dnabound_Foxo1_Pa0_Pd0_Pe0_pUb0 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa0_Pd0_Pe0_pUb1 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa0_Pd1_Pe0_pUb0 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa0_Pd1_Pe0_pUb1 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa0_Pd1_Pe1_pUb0 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa0_Pd1_Pe1_pUb1 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd0_Pe0_pUb0 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd0_Pe0_pUb1 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd0_Pe1_pUb0 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd0_Pe1_pUb1 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd1_Pe0_pUb0 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd1_Pe0_pUb1 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd1_Pe1_pUb0 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_Pa1_Pd1_Pe1_pUb1 (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
dnabound_Foxo1_tot (protein): "DNA-bound FoxO1", "FOXO1 protein", "Forkhead box O1"
Reason: GSH and GSSG are clearly chemical species as they are involved in redox reactions. The dnabound_Foxo1 species are proteins as they are described as DNA-bound forms of the FOXO1 transcription factor, which is a protein. The names provided are standardized based on common names for these species in the context of the model.
Synonyms dict: {'GSH': ['glutathione', 'reduced glutathione', 'GSH'], 'GSSG': ['oxidized glutathione', 'glutathione disulfide', 'GSSG'], 'dnabound_Foxo1_Pa0_Pd0_Pe0_pUb0': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa0_Pd0_Pe0_pUb1': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa0_Pd1_Pe0_pUb0': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa0_Pd1_Pe0_pUb1': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa0_Pd1_Pe1_pUb0': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa0_Pd1_Pe1_pUb1': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd0_Pe0_pUb0': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd0_Pe0_pUb1': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd0_Pe1_pUb0': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd0_Pe1_pUb1': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd1_Pe0_pUb0': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd1_Pe0_pUb1': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd1_Pe1_pUb0': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_Pa1_Pd1_Pe1_pUb1': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1'], 'dnabound_Foxo1_tot': ['DNA-bound FoxO1', 'FOXO1 protein', 'Forkhead box O1']}
Evaluating 475/1075: BIOMD0000000475.xml
Evaluating 476/1075: BIOMD0000000476.xml
Evaluating 477/1075: BIOMD0000000477.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000477.txt
LLM response:
mw05469f51_73f7_4ba1_9f1a_bce5fea143c2 (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PIP2", "Phosphatidylinositol(4,5)P2"
mwf20834c8_a115_460b_859c_4e3ca1ffd953 (chemical): "Diacylglycerol", "DAG", "1,2-Diacylglycerol"
Reason: The species mw05469f51_73f7_4ba1_9f1a_bce5fea143c2 is identified as PIP2, a phospholipid component of cell membranes, and mwf20834c8_a115_460b_859c_4e3ca1ffd953 is identified as DAG, a lipid molecule, based on the display names and the reactions involving PLC gamma and PKC, which are enzymes known to interact with these molecules in immune signal transduction pathways.
Synonyms dict: {'mw05469f51_73f7_4ba1_9f1a_bce5fea143c2': ['Phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'Phosphatidylinositol(4,5)P2'], 'mwf20834c8_a115_460b_859c_4e3ca1ffd953': ['Diacylglycerol', 'DAG', '1,2-Diacylglycerol']}
Evaluating 478/1075: BIOMD0000000478.xml

2025-11-20 12:59:04,710 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000478.txt
LLM response:
Ras2_GDP (protein): "Ras2 GDP-bound", "Ras2-GDP", "Ras2 guanine diphosphate"
Ras2_GDP_Cdc25 (complex): "Ras2-GDP-Cdc25 complex", "Ras2 GDP-bound Cdc25", "Cdc25-Ras2-GDP"
GDP (chemical): "guanosine diphosphate", "GDP", "guanine diphosphate"
GTP (chemical): "guanosine triphosphate", "GTP", "guanine triphosphate"
Ras2_GTP_Cdc25 (complex): "Ras2-GTP-Cdc25 complex", "Ras2 GTP-bound Cdc25", "Cdc25-Ras2-GTP"
Ras2_GTP (protein): "Ras2 GTP-bound", "Ras2-GTP", "Ras2 guanine triphosphate"
Ras2_GTP_Ira2 (complex): "Ras2-GTP-Ira2 complex", "Ras2 GTP-bound Ira2", "Ira2-Ras2-GTP"
Ras2_GTP_CYR1 (complex): "Ras2-GTP-CYR1 complex", "Ras2 GTP-bound CYR1", "CYR1-Ras2-GTP"
ATP (chemical): "adenosine triphosphate", "ATP", "adenine triphosphate"
cAMP (chemical): "cyclic adenosine monophosphate", "cAMP", "cyclic AMP"
cAMP_PKA (complex): "cAMP-PKA complex", "cAMP-protein kinase A", "PKA-cAMP"
IIcAMP_PKA (complex): "cAMP-PKA dimer", "II cAMP-PKA complex", "PKA-cAMP dimer"
IIIcAMP_PKA (complex): "cAMP-PKA trimer", "III cAMP-PKA complex", "PKA-cAMP trimer"
IVcAMP_PKA (complex): "cAMP-PKA tetramer", "IV cAMP-PKA complex", "PKA-cAMP tetramer"
R_2cAMP (unknown): "UNK", "unknown", "R2cAMP"
cAMP_Pde1f (complex): "cAMP-Pde1f complex", "cAMP-phosphodiesterase 1f", "Pde1f-cAMP"
cAMP_Pde2 (complex): "cAMP-Pde2 complex", "cAMP-phosphodiesterase 2", "Pde2-cAMP"
AMP (chemical): "adenosine monophosphate", "AMP", "adenine monophosphate"
Ras2_GTP_Ira2P (complex): "Ras2-GTP-Ira2P complex", "Ras2 GTP-bound Ira2P", "Ira2P-Ras2-GTP"
Reason: The entity types were determined based on the context of the reactions and the names of the species. Ras2_GDP, Ras2_GTP, and other similar species are proteins because they are associated with GDP or GTP binding. Cdc25, CYR1, and Ira2 are also proteins that form complexes with Ras2. GDP, GTP, ATP, cAMP, and AMP are chemicals because they are small molecules involved in the reactions. The cAMP_PKA, IIcAMP_PKA, IIIcAMP_PKA, and IVcAMP_PKA species are complexes because they represent the binding of cAMP to PKA. R_2cAMP is unknown because its composition is not clear from the reactions. The standardized names and synonyms were chosen based on common names and abbreviations used in biochemistry and molecular biology.
Synonyms dict: {'Ras2_GDP': ['Ras2 GDP-bound', 'Ras2-GDP', 'Ras2 guanine diphosphate'], 'Ras2_GDP_Cdc25': ['Ras2-GDP-Cdc25 complex', 'Ras2 GDP-bound Cdc25', 'Cdc25-Ras2-GDP'], 'GDP': ['guanosine diphosphate', 'GDP', 'guanine diphosphate'], 'GTP': ['guanosine triphosphate', 'GTP', 'guanine triphosphate'], 'Ras2_GTP_Cdc25': ['Ras2-GTP-Cdc25 complex', 'Ras2 GTP-bound Cdc25', 'Cdc25-Ras2-GTP'], 'Ras2_GTP': ['Ras2 GTP-bound', 'Ras2-GTP', 'Ras2 guanine triphosphate'], 'Ras2_GTP_Ira2': ['Ras2-GTP-Ira2 complex', 'Ras2 GTP-bound Ira2', 'Ira2-Ras2-GTP'], 'Ras2_GTP_CYR1': ['Ras2-GTP-CYR1 complex', 'Ras2 GTP-bound CYR1', 'CYR1-Ras2-GTP'], 'ATP': ['adenosine triphosphate', 'ATP', 'adenine triphosphate'], 'cAMP': ['cyclic adenosine monophosphate', 'cAMP', 'cyclic AMP'], 'cAMP_PKA': ['cAMP-PKA complex', 'cAMP-protein kinase A', 'PKA-cAMP'], 'IIcAMP_PKA': ['cAMP-PKA dimer', 'II cAMP-PKA complex', 'PKA-cAMP dimer'], 'IIIcAMP_PKA': ['cAMP-PKA trimer', 'III cAMP-PKA complex', 'PKA-cAMP trimer'], 'IVcAMP_PKA': ['cAMP-PKA tetramer', 'IV cAMP-PKA complex', 'PKA-cAMP tetramer'], 'R_2cAMP': ['UNK', 'unknown', 'R2cAMP'], 'cAMP_Pde1f': ['cAMP-Pde1f complex', 'cAMP-phosphodiesterase 1f', 'Pde1f-cAMP'], 'cAMP_Pde2': ['cAMP-Pde2 complex', 'cAMP-phosphodiesterase 2', 'Pde2-cAMP'], 'AMP': ['adenosine monophosphate', 'AMP', 'adenine monophosphate'], 'Ras2_GTP_Ira2P': ['Ras2-GTP-Ira2P complex', 'Ras2 GTP-bound Ira2P', 'Ira2P-Ras2-GTP']}
Evaluating 479/1075: BIOMD0000000479.xml

2025-11-20 12:59:11,224 - WARNING - Skipping BIOMD0000000480.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000479.txt
LLM response:
GaGTP (chemical): "GTP-bound G alpha subunit", "Gα-GTP", "Guanine nucleotide-binding protein G alpha subunit"
GaGTPEffector (complex): "Gα-GTP-Effector complex", "G protein-Effector complex", "Gα-Effector complex"
RGSmGaGTP (complex): "RGS-Gα-GTP complex", "Regulator of G protein signaling-Gα-GTP complex", "RGS-Gα complex"
GaGTPEffectorOFF (complex): "Gα-GTP-Effector inactive complex", "Gα-GTP-Effector off-state complex", "G protein-Effector inactive complex"
RGSmGaGTPEffectorOFF (complex): "RGS-Gα-GTP-Effector inactive complex", "Regulator of G protein signaling-Gα-GTP-Effector off-state complex", "RGS-Gα-Effector inactive complex"
GaGDPP (chemical): "GDP-bound G alpha subunit", "Gα-GDP", "Guanine nucleotide-binding protein G alpha subunit-GDP"
LRRGSmGaGTP (complex): "LRR-RGS-Gα-GTP complex", "Leucine-rich repeat Regulator of G protein signaling-Gα-GTP complex", "LRR-RGS-Gα complex"
RRGSmGaGTP (complex): "RR-RGS-Gα-GTP complex", "RR Regulator of G protein signaling-Gα-GTP complex", "RR-RGS-Gα complex"
LRRGSmGaGTPEffectorOFF (complex): "LRR-RGS-Gα-GTP-Effector inactive complex", "Leucine-rich repeat Regulator of G protein signaling-Gα-GTP-Effector off-state complex", "LRR-RGS-Gα-Effector inactive complex"
GaGDP (chemical): "GDP-bound G alpha subunit", "Gα-GDP", "Guanine nucleotide-binding protein G alpha subunit-GDP"
P (chemical): "Inorganic phosphate", "Phosphate ion", "Pi"
Reason: The entity types are determined based on the context of the model, which describes G protein-coupled receptor (GPCR) signaling and the interaction between G proteins, regulators of G protein signaling (RGS), and effectors. The species IDs are annotated based on their roles in the signaling pathway, with GaGTP and GaGDP representing the GTP-bound and GDP-bound states of the G alpha subunit, respectively. The complexes (e.g., RGSmGaGTP, GaGTPEffector) represent the interactions between these proteins. The chemical species P represents inorganic phosphate, which is a product of the GTP hydrolysis reaction.
Synonyms dict: {'GaGTP': ['GTP-bound G alpha subunit', 'Gα-GTP', 'Guanine nucleotide-binding protein G alpha subunit'], 'GaGTPEffector': ['Gα-GTP-Effector complex', 'G protein-Effector complex', 'Gα-Effector complex'], 'RGSmGaGTP': ['RGS-Gα-GTP complex', 'Regulator of G protein signaling-Gα-GTP complex', 'RGS-Gα complex'], 'GaGTPEffectorOFF': ['Gα-GTP-Effector inactive complex', 'Gα-GTP-Effector off-state complex', 'G protein-Effector inactive complex'], 'RGSmGaGTPEffectorOFF': ['RGS-Gα-GTP-Effector inactive complex', 'Regulator of G protein signaling-Gα-GTP-Effector off-state complex', 'RGS-Gα-Effector inactive complex'], 'GaGDPP': ['GDP-bound G alpha subunit', 'Gα-GDP', 'Guanine nucleotide-binding protein G alpha subunit-GDP'], 'LRRGSmGaGTP': ['LRR-RGS-Gα-GTP complex', 'Leucine-rich repeat Regulator of G protein signaling-Gα-GTP complex', 'LRR-RGS-Gα complex'], 'RRGSmGaGTP': ['RR-RGS-Gα-GTP complex', 'RR Regulator of G protein signaling-Gα-GTP complex', 'RR-RGS-Gα complex'], 'LRRGSmGaGTPEffectorOFF': ['LRR-RGS-Gα-GTP-Effector inactive complex', 'Leucine-rich repeat Regulator of G protein signaling-Gα-GTP-Effector off-state complex', 'LRR-RGS-Gα-Effector inactive complex'], 'GaGDP': ['GDP-bound G alpha subunit', 'Gα-GDP', 'Guanine nucleotide-binding protein G alpha subunit-GDP'], 'P': ['Inorganic phosphate', 'Phosphate ion', 'Pi']}
Evaluating 480/1075: BIOMD0000000480.xml
Evaluating 481/1075: BIOMD0000000481.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000481.txt
LLM response:
E2 (chemical): "estradiol", "17β-estradiol", "E2"
P4 (chemical): "progesterone", "pregn-4-ene-3,20-dione", "P4"
OT (unknown): "UNK"
PGF (chemical): "prostaglandin F2α", "dinoprost", "PGF2α"
Reason: E2 and P4 are likely chemicals as they are well-known hormones involved in the estrous cycle. PGF is also a chemical, specifically a prostaglandin, which is mentioned in the model name. OT is unknown as there is no clear information provided about its identity, and it does not match any well-known chemicals or genes related to the estrous cycle.
Synonyms dict: {'E2': ['estradiol', '17β-estradiol', 'E2'], 'P4': ['progesterone', 'pregn-4-ene-3,20-dione', 'P4'], 'OT': ['UNK'], 'PGF': ['prostaglandin F2α', 'dinoprost', 'PGF2α']}
Evaluating 482/1075: BIOMD0000000482.xml

2025-11-20 12:59:16,759 - WARNING - Skipping BIOMD0000000483.xml - no results generated
2025-11-20 12:59:16,761 - WARNING - Skipping BIOMD0000000484.xml - no results generated
2025-11-20 12:59:16,763 - WARNING - Skipping BIOMD0000000485.xml - no results generated
2025-11-20 12:59:16,765 - WARNING - Skipping BIOMD0000000486.xml - no results generated
2025-11-20 12:59:16,768 - WARNING - Skipping BIOMD0000000487.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000482.txt
LLM response:
PYRout (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
GLCex (chemical): "glucose", "d-glucose", "blood sugar"
F16P (chemical): "fructose 1,6-bisphosphate", "fructose-1,6-diphosphate", "F1,6BP"
PYRin (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
LAC (chemical): "lactic acid", "lactate", "2-hydroxypropanoic acid"
OAA (chemical): "oxaloacetic acid", "oxaloacetate", "2-oxobutanedioic acid"
G1P (chemical): "glucose-1-phosphate", "glucose 1-phosphate", "G-1-P"

Reason: The species can be identified based on common biochemical knowledge and the context of the "Insulin dependent glucose metabolism" model. PYRout and PYRin are likely the same chemical species, pyruvate, but with different locations or contexts (e.g., outside and inside the cell). The other species can be identified based on their display names and roles in the reactions, which match known biochemical pathways such as glycolysis and gluconeogenesis.
Synonyms dict: {'PYRout': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'GLCex': ['glucose', 'd-glucose', 'blood sugar'], 'F16P': ['fructose 1,6-bisphosphate', 'fructose-1,6-diphosphate', 'F1,6BP'], 'PYRin': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'LAC': ['lactic acid', 'lactate', '2-hydroxypropanoic acid'], 'OAA': ['oxaloacetic acid', 'oxaloacetate', '2-oxobutanedioic acid'], 'G1P': ['glucose-1-phosphate', 'glucose 1-phosphate', 'G-1-P']}
Evaluating 483/1075: BIOMD0000000483.xml
Evaluating 484/1075: BIOMD0000000484.xml
Evaluating 485/1075: BIOMD0000000485.xml
Evaluating 486/1075: BIOMD0000000486.xml
Evaluating 487/1075: BIOMD0000000487.xml
Evaluating 488/1075: BIOMD0000000488.xml

2025-11-20 12:59:18,460 - WARNING - Skipping BIOMD0000000489.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000488.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP molecule", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP molecule", "adenosine 5'-diphosphate"
AMP (chemical): "adenosine monophosphate", "AMP molecule", "adenosine 5'-monophosphate"
Reason: All three species are recognized as nucleotide molecules involved in energy transfer within cells, which is a fundamental biochemical process. Their involvement in the reactions (e.g., ATP being converted to ADP and AMP) further supports their classification as chemicals.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP molecule', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP molecule', "adenosine 5'-diphosphate"], 'AMP': ['adenosine monophosphate', 'AMP molecule', "adenosine 5'-monophosphate"]}
Evaluating 489/1075: BIOMD0000000489.xml
Evaluating 490/1075: BIOMD0000000490.xml

2025-11-20 12:59:22,655 - WARNING - Unknown entity type: cell

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000490.txt
LLM response:
AA_b (chemical): "arachidonic acid", "eicosatetraenoic acid", "5,8,11,14-eicosatetraenoic acid"
Hn_b (cell): "eosinophil", "eosinophilic granulocyte", "eosinophilic leukocyte"
AA_aw (chemical): "arachidonic acid", "eicosatetraenoic acid", "5,8,11,14-eicosatetraenoic acid"
Hn_aw (cell): "eosinophil", "eosinophilic granulocyte", "eosinophilic leukocyte"
ZF_intes (chemical): "zileuton", "5-lipoxygenase inhibitor", "ABT-761"
ZF_blood (chemical): "zileuton", "5-lipoxygenase inhibitor", "ABT-761"
ZF_airways (chemical): "zileuton", "5-lipoxygenase inhibitor", "ABT-761"
ML_intes (chemical): "leukotriene", "cysteinyl leukotriene", "LT"
ML_blood (chemical): "leukotriene", "cysteinyl leukotriene", "LT"
Reason: The model is related to the 5-lipoxygenase inhibitors and the species are likely related to the biochemical pathway of leukotriene synthesis and eosinophil trafficking. AA_b and AA_aw are likely arachidonic acid, the precursor to leukotrienes. Hn_b and Hn_aw are likely eosinophils, a type of white blood cell involved in inflammation. ZF_intes, ZF_blood, and ZF_airways are likely zileuton, a 5-lipoxygenase inhibitor. ML_intes and ML_blood are likely leukotrienes, which are involved in the biochemical pathway. The entity types are determined based on the context of the model and the display names.
Synonyms dict: {'AA_b': ['arachidonic acid', 'eicosatetraenoic acid', '5,8,11,14-eicosatetraenoic acid'], 'Hn_b': ['eosinophil', 'eosinophilic granulocyte', 'eosinophilic leukocyte'], 'AA_aw': ['arachidonic acid', 'eicosatetraenoic acid', '5,8,11,14-eicosatetraenoic acid'], 'Hn_aw': ['eosinophil', 'eosinophilic granulocyte', 'eosinophilic leukocyte'], 'ZF_intes': ['zileuton', '5-lipoxygenase inhibitor', 'ABT-761'], 'ZF_blood': ['zileuton', '5-lipoxygenase inhibitor', 'ABT-761'], 'ZF_airways': ['zileuton', '5-lipoxygenase inhibitor', 'ABT-761'], 'ML_intes': ['leukotriene', 'cysteinyl leukotriene', 'LT'], 'ML_blood': ['leukotriene', 'cysteinyl leukotriene', 'LT']}
Evaluating 491/1075: BIOMD0000000491.xml

2025-11-20 12:59:24,863 - WARNING - Skipping BIOMD0000000492.xml - no results generated
2025-11-20 12:59:24,867 - WARNING - Skipping BIOMD0000000493.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000491.txt
LLM response:
s2 (chemical): "sodium chloride", "NaCl", "salt"
s4 (chemical): "hydrogen peroxide", "H2O2", "oxidative stress"
s6 (chemical): "ethene", "C2H4", "ethylene"

Reason: s2 is annotated as "Salt" which is likely referring to sodium chloride, a chemical compound. s4 is annotated as "H2O2" which is the chemical formula for hydrogen peroxide. s6 is annotated as "Ethylene" which is a chemical compound, a plant hormone involved in plant growth and development. All three species are likely chemicals as they are involved in triggering abiotic stress responses in plants.
Synonyms dict: {'s2': ['sodium chloride', 'NaCl', 'salt'], 's4': ['hydrogen peroxide', 'H2O2', 'oxidative stress'], 's6': ['ethene', 'C2H4', 'ethylene']}
Evaluating 492/1075: BIOMD0000000492.xml
Evaluating 493/1075: BIOMD0000000493.xml
Evaluating 494/1075: BIOMD0000000494.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000494.txt
LLM response:
E2 (chemical): "estradiol", "estra-1,3,5(10)-triene-3,17-diol", "17β-estradiol"
P4 (chemical): "progesterone", "pregn-4-ene-3,20-dione", "4-pregnene-3,20-dione"
Reason: E2 and P4 are identified as chemical entities because they are mentioned in the model notes and the article abstract as hormones, specifically estradiol and progesterone, which are well-known steroid hormones involved in the menstrual cycle. The synonyms provided are standardized names and common synonyms for these hormones.
Synonyms dict: {'E2': ['estradiol', 'estra-1,3,5(10)-triene-3,17-diol', '17β-estradiol'], 'P4': ['progesterone', 'pregn-4-ene-3,20-dione', '4-pregnene-3,20-dione']}
Evaluating 495/1075: BIOMD0000000495.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000495.txt
LLM response:
mw73259e20_240e_4f3a_b2e0_9ca248658898 (chemical): "Serine ethyl ester", "L-Serine ethyl ester", "Serine ester"
mw15abaa48_d7d0_4845_ae04_c573d289d495 (chemical): "Serine", "L-Serine", "Ser"
mwfcfaf604_14d4_47a6_b021_226d1fb5497c (chemical): "Phosphatidylserine", "PS", "L-Phosphatidylserine"
mw8796c919_9251_4970_8f87_0bca9ecfeb5c (chemical): "Ethanolamine", "Etn", "2-Aminoethanol"
mw849ed3fd_87d9_44d2_9f3e_4d631b900d41 (chemical): "Phosphatidylethanolamine", "PEtn", "Phosphatidylethanolamine lipid"
mwcb834e43_dc57_45ae_9452_f4c10955caf1 (chemical): "Phosphocholine", "PCho", "Phosphocholine lipid"
mwf166ad55_4ff0_49fb_95d2_b657ad7653d5 (chemical): "Phosphatidylethanolamine", "PE", "Phosphatidylethanolamine lipid"
mwee54b5b4_b8c0_41df_8dda_5b160c5e10a5 (chemical): "Phosphatidylcholine", "PC", "L-Phosphatidylcholine"
mw919f8a86_e702_4b24_9cd7_adad694fcf9b (chemical): "Choline ester", "Choline ethyl ester", "Choline derivative"
mw812f63db_4cb0_40ad_b92b_9874be969dfe (chemical): "Choline", "Cho", "2-Hydroxyethyltrimethylammonium"
mw08818dfe_fb12_45cc_8c1d_d965f142d0ce (chemical): "Ethanolamine ester", "Ethanolamine derivative", "Etn ester"
Reason: The species are annotated based on their display names and the context of the phospholipid synthesis model. The display names provide a clear indication of the chemical structure or function of each species, allowing for the assignment of a chemical entity type. The synonyms are selected based on common names and abbreviations used in the field of biochemistry and phospholipid metabolism. The model's context and the display names suggest that all species are chemicals involved in phospholipid synthesis, with no evidence of genes, proteins, or complexes.
Synonyms dict: {'mw73259e20_240e_4f3a_b2e0_9ca248658898': ['Serine ethyl ester', 'L-Serine ethyl ester', 'Serine ester'], 'mw15abaa48_d7d0_4845_ae04_c573d289d495': ['Serine', 'L-Serine', 'Ser'], 'mwfcfaf604_14d4_47a6_b021_226d1fb5497c': ['Phosphatidylserine', 'PS', 'L-Phosphatidylserine'], 'mw8796c919_9251_4970_8f87_0bca9ecfeb5c': ['Ethanolamine', 'Etn', '2-Aminoethanol'], 'mw849ed3fd_87d9_44d2_9f3e_4d631b900d41': ['Phosphatidylethanolamine', 'PEtn', 'Phosphatidylethanolamine lipid'], 'mwcb834e43_dc57_45ae_9452_f4c10955caf1': ['Phosphocholine', 'PCho', 'Phosphocholine lipid'], 'mwf166ad55_4ff0_49fb_95d2_b657ad7653d5': ['Phosphatidylethanolamine', 'PE', 'Phosphatidylethanolamine lipid'], 'mwee54b5b4_b8c0_41df_8dda_5b160c5e10a5': ['Phosphatidylcholine', 'PC', 'L-Phosphatidylcholine'], 'mw919f8a86_e702_4b24_9cd7_adad694fcf9b': ['Choline ester', 'Choline ethyl ester', 'Choline derivative'], 'mw812f63db_4cb0_40ad_b92b_9874be969dfe': ['Choline', 'Cho', '2-Hydroxyethyltrimethylammonium'], 'mw08818dfe_fb12_45cc_8c1d_d965f142d0ce': ['Ethanolamine ester', 'Ethanolamine derivative', 'Etn ester']}
Evaluating 496/1075: BIOMD0000000496.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000496.txt
LLM response:
s_1315 (chemical): "sn-glycerol 3-phosphate", "glycerol 3-phosphate", "L-glycerol 3-phosphate"
s_1325 (chemical): "sphinganine", "dihydrosphingosine", "2-amino-1,3-octadecanediol"
s_1327 (chemical): "squalene", "all-trans-squalene", "trans,trans-squalene"
s_1329 (chemical): "stearic acid", "octadecanoic acid", "n-octadecanoic acid"
s_1334 (chemical): "stearoyl-CoA", "octadecanoyl-CoA", "stearoyl coenzyme A"
s_1338 (chemical): "succinic acid", "butanedioic acid", "succinate"
s_1342 (chemical): "succinyl-CoA", "succinyl coenzyme A", "butanedioyl-CoA"
s_1347 (chemical): "sulfate", "sulfuric acid", "sulfate ion"
s_1349 (chemical): "sulfite", "sulfurous acid", "sulfite ion"
s_1355 (chemical): "tetracosanoyl-CoA", "lignoceroyl-CoA", "tetracosanoyl coenzyme A"
s_1379 (chemical): "trans-4-hydroxy-L-proline", "4-hydroxyproline", "hydroxyproline"
s_1399 (chemical): "triglyceride", "triacylglycerol", "glycerol triester"
s_1411 (chemical): "UDP", "uridine diphosphate", "uridine 5'-diphosphate"
s_1415 (chemical): "UDP-D-glucose", "uridine diphosphate glucose", "UDP-glucose"
s_1417 (chemical): "UMP", "uridine monophosphate", "uridine 5'-monophosphate"
s_1430 (chemical): "UTP", "uridine triphosphate", "uridine 5'-triphosphate"
s_1447 (chemical): "zymosterol", "delta-5-cholesta-7,24-dien-3-beta-ol", "zymosterol intermediate"
s_1455 (chemical): "zymosterol intermediate 1a", "zymosterol intermediate", "lanosterol intermediate"
s_1456 (chemical): "zymosterol intermediate 1b", "zymosterol intermediate", "lanosterol intermediate"
s_1457 (chemical): "zymosterol intermediate 1c", "zymosterol intermediate", "lanosterol intermediate"
s_1458 (chemical): "zymosterol intermediate 2", "zymosterol intermediate", "lanosterol intermediate"
s_1517 (chemical): "thioredoxin dithiol", "thioredoxin reduced", "thioredoxin (reduced)"
s_1521 (chemical): "thioredoxin disulfide", "thioredoxin oxidized", "thioredoxin (oxidized)"
s_0763_b (chemical): "hydrogen ion", "proton", "H+"
s_1434_b (chemical): "water", "H2O", "dihydrogen oxide"
s_0431_b (chemical): "ammonium ion", "ammonium", "NH4+"
s_0472_b (chemical): "carbon dioxide", "CO2", "carbonic acid"
s_0547_b (chemical): "D-glucose", "glucose", "dextrose"
s_0651_b (chemical): "ethanol", "ethyl alcohol", "alcohol"
s_0766_b (chemical): "hydrogen ion", "proton", "H+"
s_1162_b (chemical): "oxygen", "O2", "dioxygen"
s_1209_b (chemical): "phosphate", "phosphoric acid", "inorganic phosphate"
s_1339_b (chemical): "succinate", "succinic acid", "butanedioic acid"
s_1348_b (chemical): "sulfate", "sulfuric acid", "sulfate ion"

Reason: Most of the species are identified as chemicals based on their names and the context of the yeast metabolic network model. The names of the species are matched to common biochemical names and synonyms to determine their entity types and standardized names. The model's context and the names of the reactions and other species are used to infer the likely entity types and names for species that are not explicitly identified.

2025-11-20 13:07:30,258 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000497.txt
LLM response:
s_1315 (chemical): "sn-glycerol 3-phosphate", "glycerol 3-phosphate", "G3P"
s_1325 (chemical): "sphinganine", "dihydrosphingosine", "SPH"
s_1327 (chemical): "squalene", "all-trans-squalene", "SQE"
s_1329 (chemical): "stearate", "octadecanoate", "STE"
s_1334 (chemical): "stearoyl-CoA", "octadecanoyl-CoA", "STCOA"
s_1338 (chemical): "succinate", "succinic acid", "SUCC"
s_1342 (chemical): "succinyl-CoA", "succinyl coenzyme A", "SUCCOA"
s_1347 (chemical): "sulfate", "sulfuric acid", "SO4"
s_1349 (chemical): "sulfite", "sulfurous acid", "SO3"
s_1355 (chemical): "tetracosanoyl-CoA", "lignoceroyl-CoA", "TETCOA"
s_1379 (chemical): "trans-4-hydroxy-L-proline", "4-hydroxyproline", "HYP"
s_1399 (chemical): "triglyceride", "triacylglycerol", "TAG"
s_1411 (chemical): "UDP", "uridine diphosphate", "Uridine 5'-diphosphate"
s_1415 (chemical): "UDP-D-glucose", "uridine diphosphate glucose", "UDPG"
s_1417 (chemical): "UMP", "uridine monophosphate", "Uridine 5'-monophosphate"
s_1430 (chemical): "UTP", "uridine triphosphate", "Uridine 5'-triphosphate"
s_1447 (chemical): "zymosterol", "zymotic sterol", "ZYM"
s_1455 (chemical): "zymosterol intermediate 1a", "zymosterol intermediate", "ZIM1A"
s_1456 (chemical): "zymosterol intermediate 1b", "zymosterol intermediate", "ZIM1B"
s_1457 (chemical): "zymosterol intermediate 1c", "zymosterol intermediate", "ZIM1C"
s_1458 (chemical): "zymosterol intermediate 2", "zymosterol intermediate", "ZIM2"
s_1517 (protein): "thioredoxin dithiol", "thioredoxin", "TXD"
s_1521 (protein): "thioredoxin disulfide", "thioredoxin", "TXS"
s_0763_b (chemical): "H+", "hydrogen ion", "proton"
s_1434_b (chemical): "water", "H2O", "aqua"
s_0431_b (chemical): "ammonium", "ammonium ion", "NH4+"
s_0472_b (chemical): "carbon dioxide", "CO2", "carbonic acid"
s_0547_b (chemical): "D-glucose", "glucose", "GLC"
s_0651_b (chemical): "ethanol", "ethyl alcohol", "EtOH"
s_0766_b (chemical): "H+", "hydrogen ion", "proton"
s_1162_b (chemical): "oxygen", "O2", "dioxygen"
s_1209_b (chemical): "phosphate", "phosphoric acid", "PO4"
s_1339_b (chemical): "succinate", "succinic acid", "SUCC"
s_1348_b (chemical): "sulfate", "sulfuric acid", "SO4"

Reason: The species IDs were matched to their corresponding display names in the model, and then the entity types were determined based on the display names. The display names were then used to find standardized names and common synonyms for each species. The entity types were determined as follows: s_1315 to s_1458 are chemicals, s_1517 and s_1521 are proteins, and the rest are chemicals. The species with "_b" suffix are boundary species, which are also chemicals. The reasons for the entity types are based on the display names and the context of the model, which is a kinetic model of yeast metabolic network.

2025-11-20 13:07:34,950 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:07:35,110 - WARNING - Skipping BIOMD0000000499.xml - no results generated
2025-11-20 13:07:35,120 - WARNING - Skipping BIOMD0000000500.xml - no results generated
2025-11-20 13:07:35,142 - WARNING - Skipping BIOMD0000000501.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000498.txt
LLM response:
species_24 (chemical): "Ferritin", "Fe-FT", "Iron-Ferritin"
species_26 (protein): "Ferritin light chain", "FT1", "Ferritin subunit"
species_5 (chemical): "Heme", "Haem", "Iron protoporphyrin"
species_2 (chemical): "Labile Iron Pool", "LIP", "Free iron"
species_43 (complex): "Transferrin-Fe", "Tf-Fe", "Iron-transferrin complex"
species_12 (complex): "Tf-Fe-TfR1", "Transferrin-Fe-TfR1", "Iron-transferrin-TfR1 complex"
species_15 (complex): "Tf-Fe-TfR2", "Transferrin-Fe-TfR2", "Iron-transferrin-TfR2 complex"
species_16 (complex): "2(Tf-Fe)-TfR1", "Diiron-transferrin-TfR1 complex", "Iron-transferrin-TfR1 dimer"
species_19 (complex): "2(Tf-Fe)-TfR2", "Diiron-transferrin-TfR2 complex", "Iron-transferrin-TfR2 dimer"
species_11 (chemical): "Heme", "Haem", "Iron protoporphyrin"
Reason: The model "Mitchell2013 - Liver Iron Metabolism" describes the core regulatory components of human liver iron metabolism. Based on the display names and reactions, species can be identified as chemicals (e.g., iron, heme), proteins (e.g., ferritin), or complexes (e.g., transferrin-Fe, Tf-Fe-TfR1). The entity types are determined by the context of the reactions and the display names. For example, species_24 is a chemical because it is associated with iron and ferritin, while species_26 is a protein because it is a subunit of ferritin. Species_43 is a complex because it represents the binding of transferrin and iron.
Synonyms dict: {'species_24': ['Ferritin', 'Fe-FT', 'Iron-Ferritin'], 'species_26': ['Ferritin light chain', 'FT1', 'Ferritin subunit'], 'species_5': ['Heme', 'Haem', 'Iron protoporphyrin'], 'species_2': ['Labile Iron Pool', 'LIP', 'Free iron'], 'species_43': ['Transferrin-Fe', 'Tf-Fe', 'Iron-transferrin complex'], 'species_12': ['Tf-Fe-TfR1', 'Transferrin-Fe-TfR1', 'Iron-transferrin-TfR1 complex'], 'species_15': ['Tf-Fe-TfR2', 'Transferrin-Fe-TfR2', 'Iron-transferrin-TfR2 complex'], 'species_16': ['2(Tf-Fe)-TfR1', 'Diiron-transferrin-TfR1 complex', 'Iron-transferrin-TfR1 dimer'], 'species_19': ['2(Tf-Fe)-TfR2', 'Diiron-transferrin-TfR2 complex', 'Iron-transferrin-TfR2 dimer'], 'species_11': ['Heme', 'Haem', 'Iron protoporphyrin']}
Evaluating 499/1075: BIOMD0000000499.xml
Evaluating 500/1075: BIOMD0000000500.xml
Evaluating 501/1075: BIOMD0000000501.xml
Evaluating 502/1075: BIOMD0000000502.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000502.txt
LLM response:
E4P (chemical): "erythrose 4-phosphate", "D-erythrose 4-phosphate", "E4P"
G6L (chemical): "gluconolactone", "D-gluconolactone", "6-phosphogluconolactone"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP reduced", "NADPH"
P6G (chemical): "6-phosphogluconate", "6-phosphogluconic acid", "P6G"
R5P (chemical): "ribose 5-phosphate", "D-ribose 5-phosphate", "R5P"
Ru5P (chemical): "ribulose 5-phosphate", "D-ribulose 5-phosphate", "Ru5P"
S7P (chemical): "sedoheptulose 7-phosphate", "D-sedoheptulose 7-phosphate", "S7P"
X5P (chemical): "xylulose 5-phosphate", "D-xylulose 5-phosphate", "X5P"
NADP (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP", "NADP+"
G6P (chemical): "glucose 6-phosphate", "D-glucose 6-phosphate", "G6P"
F6P (chemical): "fructose 6-phosphate", "D-fructose 6-phosphate", "F6P"
GAP (chemical): "glyceraldehyde 3-phosphate", "D-glyceraldehyde 3-phosphate", "GAP"
Reason: All species are identified as chemicals because they are all metabolites involved in the pentose phosphate pathway, a metabolic pathway that generates NADPH and pentoses from glucose-6-phosphate. The names are standardized based on common biochemical nomenclature and synonyms.
Synonyms dict: {'E4P': ['erythrose 4-phosphate', 'D-erythrose 4-phosphate', 'E4P'], 'G6L': ['gluconolactone', 'D-gluconolactone', '6-phosphogluconolactone'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADP reduced', 'NADPH'], 'P6G': ['6-phosphogluconate', '6-phosphogluconic acid', 'P6G'], 'R5P': ['ribose 5-phosphate', 'D-ribose 5-phosphate', 'R5P'], 'Ru5P': ['ribulose 5-phosphate', 'D-ribulose 5-phosphate', 'Ru5P'], 'S7P': ['sedoheptulose 7-phosphate', 'D-sedoheptulose 7-phosphate', 'S7P'], 'X5P': ['xylulose 5-phosphate', 'D-xylulose 5-phosphate', 'X5P'], 'NADP': ['nicotinamide adenine dinucleotide phosphate', 'NADP', 'NADP+'], 'G6P': ['glucose 6-phosphate', 'D-glucose 6-phosphate', 'G6P'], 'F6P': ['fructose 6-phosphate', 'D-fructose 6-phosphate', 'F6P'], 'GAP': ['glyceraldehyde 3-phosphate', 'D-glyceraldehyde 3-phosphate', 'GAP']}
Evaluating 503/1075: BIOMD0000000503.xml

2025-11-20 13:07:52,355 - WARNING - Skipping BIOMD0000000504.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000503.txt
LLM response:
ADP (chemical): "adenosine diphosphate", "ADP molecule", "adenosine 5'-diphosphate"
ATP (chemical): "adenosine triphosphate", "ATP molecule", "adenosine 5'-triphosphate"
AcAld (chemical): "acetaldehyde", "ethanal", "acetaldehyde molecule"
BPG (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "BPG molecule"
DHAP (chemical): "dihydroxyacetone phosphate", "DHAP molecule", "glycerone phosphate"
F16bP (chemical): "fructose-1,6-bisphosphate", "F16bP molecule", "fructose 1,6-diphosphate"
F6P (chemical): "fructose-6-phosphate", "F6P molecule", "fructose 6-phosphate"
G1P (chemical): "glucose-1-phosphate", "G1P molecule", "glucose 1-phosphate"
G3P (chemical): "glyceraldehyde-3-phosphate", "G3P molecule", "3-phosphoglyceraldehyde"
G6P (chemical): "glucose-6-phosphate", "G6P molecule", "glucose 6-phosphate"
GAP (chemical): "glyceraldehyde-3-phosphate", "GAP molecule", "3-phosphoglyceraldehyde"
GLC (chemical): "glucose", "D-glucose", "blood sugar"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD molecule", "NAD+"
P2G (chemical): "2-phosphoglycerate", "P2G molecule", "2-phosphoglyceric acid"
P3G (chemical): "3-phosphoglycerate", "P3G molecule", "3-phosphoglyceric acid"
PEP (chemical): "phosphoenolpyruvate", "PEP molecule", "phosphoenolpyruvic acid"
PYR (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
T6P (chemical): "trehalose-6-phosphate", "T6P molecule", "trehalose 6-phosphate"
UDP (chemical): "uridine diphosphate", "UDP molecule", "uridine 5'-diphosphate"
UTP (chemical): "uridine triphosphate", "UTP molecule", "uridine 5'-triphosphate"
AMP (chemical): "adenosine monophosphate", "AMP molecule", "adenosine 5'-monophosphate"
NADH (chemical): "nicotinamide adenine dinucleotide + hydrogen", "NADH molecule", "reduced NAD"
UDG (chemical): "UDP-glucose", "UDG molecule", "uridine diphosphate glucose"
ACE (chemical): "acetic acid", "acetate", "ethanoic acid"
EtOH (chemical): "ethanol", "ethyl alcohol", "alcohol"
F26bP (chemical): "fructose-2,6-bisphosphate", "F26bP molecule", "fructose 2,6-diphosphate"
GLCx (chemical): "glucopyranose", "GLCx molecule", "D-glucopyranose"
GLY (chemical): "glycerol", "GLY molecule", "glycerin"
SUC (chemical): "succinate", "succinic acid", "butanedioic acid"
TRH (chemical): "trehalose", "TRH molecule", "mycose"
E4P (chemical): "erythrose-4-phosphate", "E4P molecule", "erythrose 4-phosphate"
G6L (chemical): "gluconolactone", "G6L molecule", "glucono-d-lactone"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate + hydrogen", "NADPH molecule", "reduced NADP"
P6G (chemical): "6-phosphogluconate", "P6G molecule", "6-phosphogluconic acid"
R5P (chemical): "ribose-5-phosphate", "R5P molecule", "ribose 5-phosphate"
Ru5P (chemical): "ribulose-5-phosphate", "Ru5P molecule", "ribulose 5-phosphate"
S7P (chemical): "sedoheptulose-7-phosphate", "S7P molecule", "sedoheptulose 7-phosphate"
X5P (chemical): "xylulose-5-phosphate", "X5P molecule", "xylulose 5-phosphate"
NADP (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP molecule", "NADP+"
Reason: All species are annotated as chemicals because they are all metabolites or molecules involved in the glycolysis and pentose phosphate pathways. The names and synonyms provided are based on common biochemical nomenclature and are ranked by likelihood based on their frequency of use in the scientific literature.
Synonyms dict: {'ADP': ['adenosine diphosphate', 'ADP molecule', "adenosine 5'-diphosphate"], 'ATP': ['adenosine triphosphate', 'ATP molecule', "adenosine 5'-triphosphate"], 'AcAld': ['acetaldehyde', 'ethanal', 'acetaldehyde molecule'], 'BPG': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', 'BPG molecule'], 'DHAP': ['dihydroxyacetone phosphate', 'DHAP molecule', 'glycerone phosphate'], 'F16bP': ['fructose-1,6-bisphosphate', 'F16bP molecule', 'fructose 1,6-diphosphate'], 'F6P': ['fructose-6-phosphate', 'F6P molecule', 'fructose 6-phosphate'], 'G1P': ['glucose-1-phosphate', 'G1P molecule', 'glucose 1-phosphate'], 'G3P': ['glyceraldehyde-3-phosphate', 'G3P molecule', '3-phosphoglyceraldehyde'], 'G6P': ['glucose-6-phosphate', 'G6P molecule', 'glucose 6-phosphate'], 'GAP': ['glyceraldehyde-3-phosphate', 'GAP molecule', '3-phosphoglyceraldehyde'], 'GLC': ['glucose', 'D-glucose', 'blood sugar'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD molecule', 'NAD+'], 'P2G': ['2-phosphoglycerate', 'P2G molecule', '2-phosphoglyceric acid'], 'P3G': ['3-phosphoglycerate', 'P3G molecule', '3-phosphoglyceric acid'], 'PEP': ['phosphoenolpyruvate', 'PEP molecule', 'phosphoenolpyruvic acid'], 'PYR': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'T6P': ['trehalose-6-phosphate', 'T6P molecule', 'trehalose 6-phosphate'], 'UDP': ['uridine diphosphate', 'UDP molecule', "uridine 5'-diphosphate"], 'UTP': ['uridine triphosphate', 'UTP molecule', "uridine 5'-triphosphate"], 'AMP': ['adenosine monophosphate', 'AMP molecule', "adenosine 5'-monophosphate"], 'NADH': ['nicotinamide adenine dinucleotide + hydrogen', 'NADH molecule', 'reduced NAD'], 'UDG': ['UDP-glucose', 'UDG molecule', 'uridine diphosphate glucose'], 'ACE': ['acetic acid', 'acetate', 'ethanoic acid'], 'EtOH': ['ethanol', 'ethyl alcohol', 'alcohol'], 'F26bP': ['fructose-2,6-bisphosphate', 'F26bP molecule', 'fructose 2,6-diphosphate'], 'GLCx': ['glucopyranose', 'GLCx molecule', 'D-glucopyranose'], 'GLY': ['glycerol', 'GLY molecule', 'glycerin'], 'SUC': ['succinate', 'succinic acid', 'butanedioic acid'], 'TRH': ['trehalose', 'TRH molecule', 'mycose'], 'E4P': ['erythrose-4-phosphate', 'E4P molecule', 'erythrose 4-phosphate'], 'G6L': ['gluconolactone', 'G6L molecule', 'glucono-d-lactone'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate + hydrogen', 'NADPH molecule', 'reduced NADP'], 'P6G': ['6-phosphogluconate', 'P6G molecule', '6-phosphogluconic acid'], 'R5P': ['ribose-5-phosphate', 'R5P molecule', 'ribose 5-phosphate'], 'Ru5P': ['ribulose-5-phosphate', 'Ru5P molecule', 'ribulose 5-phosphate'], 'S7P': ['sedoheptulose-7-phosphate', 'S7P molecule', 'sedoheptulose 7-phosphate'], 'X5P': ['xylulose-5-phosphate', 'X5P molecule', 'xylulose 5-phosphate'], 'NADP': ['nicotinamide adenine dinucleotide phosphate', 'NADP molecule', 'NADP+']}
Evaluating 504/1075: BIOMD0000000504.xml
Evaluating 505/1075: BIOMD0000000505.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000505.txt
LLM response:
C16AcylCoAMAT (chemical): "palmitoyl-CoA", "hexadecanoyl-CoA", "palmitoyl coenzyme A"
C16EnoylCoAMAT (chemical): "hexadecenoyl-CoA", "palmitoleoyl-CoA", "16-enoyl-CoA"
C16KetoacylCoAMAT (chemical): "hexadecanoyl-CoA(16-keto)", "16-ketoacyl-CoA", "palmitoyl-CoA(16-keto)"
C14AcylCoAMAT (chemical): "myristoyl-CoA", "tetradecanoyl-CoA", "myristoyl coenzyme A"
C14EnoylCoAMAT (chemical): "myristoleoyl-CoA", "tetradecenoyl-CoA", "14-enoyl-CoA"
C14KetoacylCoAMAT (chemical): "tetradecanoyl-CoA(14-keto)", "14-ketoacyl-CoA", "myristoyl-CoA(14-keto)"
C12AcylCoAMAT (chemical): "dodecanoyl-CoA", "lauroyl-CoA", "dodecanoyl coenzyme A"
C12EnoylCoAMAT (chemical): "dodecenoyl-CoA", "lauroleoyl-CoA", "12-enoyl-CoA"
C12KetoacylCoAMAT (chemical): "dodecanoyl-CoA(12-keto)", "12-ketoacyl-CoA", "lauroyl-CoA(12-keto)"
C10AcylCoAMAT (chemical): "decanoyl-CoA", "caprinoyl-CoA", "decanoyl coenzyme A"
C10EnoylCoAMAT (chemical): "decenoyl-CoA", "caprinoyleoyl-CoA", "10-enoyl-CoA"
C10KetoacylCoAMAT (chemical): "decanoyl-CoA(10-keto)", "10-ketoacyl-CoA", "caprinoyl-CoA(10-keto)"
C8AcylCoAMAT (chemical): "octanoyl-CoA", "capryloyl-CoA", "octanoyl coenzyme A"
C8EnoylCoAMAT (chemical): "octenoyl-CoA", "caproleoyl-CoA", "8-enoyl-CoA"
C8KetoacylCoAMAT (chemical): "octanoyl-CoA(8-keto)", "8-ketoacyl-CoA", "capryloyl-CoA(8-keto)"
C6AcylCoAMAT (chemical): "hexanoyl-CoA", "caproyl-CoA", "hexanoyl coenzyme A"
C6EnoylCoAMAT (chemical): "hexenoyl-CoA", "caproleyl-CoA", "6-enoyl-CoA"
C6KetoacylCoAMAT (chemical): "hexanoyl-CoA(6-keto)", "6-ketoacyl-CoA", "caproyl-CoA(6-keto)"
C4AcylCoAMAT (chemical): "butanoyl-CoA", "butyryl-CoA", "butanoyl coenzyme A"
C4EnoylCoAMAT (chemical): "butenoyl-CoA", "butyroleoyl-CoA", "4-enoyl-CoA"
C4AcetoacylCoAMAT (chemical): "acetoacetyl-CoA", "acetoacetyl coenzyme A", "3-oxobutanoyl-CoA"
AcetylCoAMAT (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
FADHMAT (chemical): "FADH2", "flavin adenine dinucleotide (reduced)", "dihydroflavin adenine dinucleotide"
NADHMAT (chemical): "NADH", "nicotinamide adenine dinucleotide (reduced)", "dihydronicotinamide adenine dinucleotide"
CoAMAT (chemical): "CoA", "coenzyme A", "coenzyme A (unacylated)"
C16AcylCoACYT (chemical): "palmitoyl-carnitine", "hexadecanoyl-carnitine", "palmitoyl-L-carnitine"
CarCYT (chemical): "L-carnitine", "carnitine", "vitamin Bt"
CoACYT (chemical): "acetyl-carnitine", "acetylcarnitine", "O-acetylcarnitine"
MalCoACYT (chemical): "malonyl-carnitine", "malonyl-L-carnitine", "3-carboxypropionyl-carnitine"
CarMAT (chemical): "carnitine", "L-carnitine", "vitamin Bt"
FADtMAT (chemical): "FAD", "flavin adenine dinucleotide", "oxidized flavin adenine dinucleotide"
CoAMATt (chemical): "CoA", "coenzyme A", "coenzyme A (unacylated)"

Reason: The species are all related to fatty acid β-oxidation, which is a process that breaks down fatty acids into acetyl-CoA units. The names and synonyms provided are based on common biochemical nomenclature and the structure of the fatty acid β-oxidation pathway. The entity types are all chemicals, as they are either fatty acid-CoA esters, carnitine esters, or coenzymes involved in the β-oxidation process. The lack of gene or protein species in the list is due to the fact that this is a metabolic model, which focuses on the biochemical reactions and metabolites rather than the genetic or proteomic aspects of the system.
Synonyms dict: {'C16AcylCoAMAT': ['palmitoyl-CoA', 'hexadecanoyl-CoA', 'palmitoyl coenzyme A'], 'C16EnoylCoAMAT': ['hexadecenoyl-CoA', 'palmitoleoyl-CoA', '16-enoyl-CoA'], 'C16KetoacylCoAMAT': ['hexadecanoyl-CoA(16-keto)', '16-ketoacyl-CoA', 'palmitoyl-CoA(16-keto)'], 'C14AcylCoAMAT': ['myristoyl-CoA', 'tetradecanoyl-CoA', 'myristoyl coenzyme A'], 'C14EnoylCoAMAT': ['myristoleoyl-CoA', 'tetradecenoyl-CoA', '14-enoyl-CoA'], 'C14KetoacylCoAMAT': ['tetradecanoyl-CoA(14-keto)', '14-ketoacyl-CoA', 'myristoyl-CoA(14-keto)'], 'C12AcylCoAMAT': ['dodecanoyl-CoA', 'lauroyl-CoA', 'dodecanoyl coenzyme A'], 'C12EnoylCoAMAT': ['dodecenoyl-CoA', 'lauroleoyl-CoA', '12-enoyl-CoA'], 'C12KetoacylCoAMAT': ['dodecanoyl-CoA(12-keto)', '12-ketoacyl-CoA', 'lauroyl-CoA(12-keto)'], 'C10AcylCoAMAT': ['decanoyl-CoA', 'caprinoyl-CoA', 'decanoyl coenzyme A'], 'C10EnoylCoAMAT': ['decenoyl-CoA', 'caprinoyleoyl-CoA', '10-enoyl-CoA'], 'C10KetoacylCoAMAT': ['decanoyl-CoA(10-keto)', '10-ketoacyl-CoA', 'caprinoyl-CoA(10-keto)'], 'C8AcylCoAMAT': ['octanoyl-CoA', 'capryloyl-CoA', 'octanoyl coenzyme A'], 'C8EnoylCoAMAT': ['octenoyl-CoA', 'caproleoyl-CoA', '8-enoyl-CoA'], 'C8KetoacylCoAMAT': ['octanoyl-CoA(8-keto)', '8-ketoacyl-CoA', 'capryloyl-CoA(8-keto)'], 'C6AcylCoAMAT': ['hexanoyl-CoA', 'caproyl-CoA', 'hexanoyl coenzyme A'], 'C6EnoylCoAMAT': ['hexenoyl-CoA', 'caproleyl-CoA', '6-enoyl-CoA'], 'C6KetoacylCoAMAT': ['hexanoyl-CoA(6-keto)', '6-ketoacyl-CoA', 'caproyl-CoA(6-keto)'], 'C4AcylCoAMAT': ['butanoyl-CoA', 'butyryl-CoA', 'butanoyl coenzyme A'], 'C4EnoylCoAMAT': ['butenoyl-CoA', 'butyroleoyl-CoA', '4-enoyl-CoA'], 'C4AcetoacylCoAMAT': ['acetoacetyl-CoA', 'acetoacetyl coenzyme A', '3-oxobutanoyl-CoA'], 'AcetylCoAMAT': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'FADHMAT': ['FADH2', 'flavin adenine dinucleotide (reduced)', 'dihydroflavin adenine dinucleotide'], 'NADHMAT': ['NADH', 'nicotinamide adenine dinucleotide (reduced)', 'dihydronicotinamide adenine dinucleotide'], 'CoAMAT': ['CoA', 'coenzyme A', 'coenzyme A (unacylated)'], 'C16AcylCoACYT': ['palmitoyl-carnitine', 'hexadecanoyl-carnitine', 'palmitoyl-L-carnitine'], 'CarCYT': ['L-carnitine', 'carnitine', 'vitamin Bt'], 'CoACYT': ['acetyl-carnitine', 'acetylcarnitine', 'O-acetylcarnitine'], 'MalCoACYT': ['malonyl-carnitine', 'malonyl-L-carnitine', '3-carboxypropionyl-carnitine'], 'CarMAT': ['carnitine', 'L-carnitine', 'vitamin Bt'], 'FADtMAT': ['FAD', 'flavin adenine dinucleotide', 'oxidized flavin adenine dinucleotide'], 'CoAMATt': ['CoA', 'coenzyme A', 'coenzyme A (unacylated)']}
Evaluating 506/1075: BIOMD0000000506.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000506.txt
LLM response:
C16AcylCoAMAT (chemical): "palmitoyl-CoA", "hexadecanoyl-CoA", "palmitoyl coenzyme A"
C16EnoylCoAMAT (chemical): "hexadecenoyl-CoA", "palmitoleoyl-CoA", "16-enoyl-CoA"
C16KetoacylCoAMAT (chemical): "hexadecanoyl-CoA(16-keto)", "16-ketoacyl-CoA", "palmitoyl-CoA(16-keto)"
C14AcylCoAMAT (chemical): "tetradecanoyl-CoA", "myristoyl-CoA", "myristoyl coenzyme A"
C14EnoylCoAMAT (chemical): "tetradecenoyl-CoA", "myristoleoyl-CoA", "14-enoyl-CoA"
C14KetoacylCoAMAT (chemical): "tetradecanoyl-CoA(14-keto)", "14-ketoacyl-CoA", "myristoyl-CoA(14-keto)"
C12AcylCoAMAT (chemical): "dodecanoyl-CoA", "lauronyl-CoA", "lauronyl coenzyme A"
C12EnoylCoAMAT (chemical): "dodecenoyl-CoA", "lauroleoyl-CoA", "12-enoyl-CoA"
C12KetoacylCoAMAT (chemical): "dodecanoyl-CoA(12-keto)", "12-ketoacyl-CoA", "lauronyl-CoA(12-keto)"
C10AcylCoAMAT (chemical): "decanoyl-CoA", "capronyl-CoA", "capronyl coenzyme A"
C10EnoylCoAMAT (chemical): "decenoyl-CoA", "caproleoyl-CoA", "10-enoyl-CoA"
C10KetoacylCoAMAT (chemical): "decanoyl-CoA(10-keto)", "10-ketoacyl-CoA", "capronyl-CoA(10-keto)"
C8AcylCoAMAT (chemical): "octanoyl-CoA", "capryloyl-CoA", "capryloyl coenzyme A"
C8EnoylCoAMAT (chemical): "octenoyl-CoA", "caproleoyl-CoA", "8-enoyl-CoA"
C8KetoacylCoAMAT (chemical): "octanoyl-CoA(8-keto)", "8-ketoacyl-CoA", "capryloyl-CoA(8-keto)"
C6AcylCoAMAT (chemical): "hexanoyl-CoA", "caproonyl-CoA", "caproonyl coenzyme A"
C6EnoylCoAMAT (chemical): "hexenoyl-CoA", "caprooleoyl-CoA", "6-enoyl-CoA"
C6KetoacylCoAMAT (chemical): "hexanoyl-CoA(6-keto)", "6-ketoacyl-CoA", "caproonyl-CoA(6-keto)"
C4AcylCoAMAT (chemical): "butanoyl-CoA", "butyryl-CoA", "butyryl coenzyme A"
C4EnoylCoAMAT (chemical): "butenoyl-CoA", "butyroleoyl-CoA", "4-enoyl-CoA"
C4AcetoacylCoAMAT (chemical): "acetoacetyl-CoA", "acetoacetyl coenzyme A", "2-oxobutanoyl-CoA"
AcetylCoAMAT (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
FADHMAT (chemical): "FADH2", "flavin adenine dinucleotide (reduced)", "reduced flavin adenine dinucleotide"
NADHMAT (chemical): "NADH", "nicotinamide adenine dinucleotide (reduced)", "reduced nicotinamide adenine dinucleotide"
CoAMAT (chemical): "CoA", "coenzyme A", "CoASH"
C16AcylCoACYT (chemical): "palmitoyl-carnitine", "hexadecanoyl-carnitine", "palmitoyl-L-carnitine"
CarCYT (chemical): "L-carnitine", "carnitine", "levocarnitine"
CoACYT (chemical): "acetyl-carnitine", "acetylcarnitine", "O-acetylcarnitine"
MalCoACYT (chemical): "malonyl-carnitine", "malonyl-L-carnitine", "3-carboxypropionyl-L-carnitine"
CarMAT (chemical): "carnitine", "L-carnitine", "levocarnitine"
FADtMAT (chemical): "FAD", "flavin adenine dinucleotide", "oxidized flavin adenine dinucleotide"
CoAMATt (chemical): "CoA", "coenzyme A", "CoASH"

Reason: The species are all related to fatty acid β-oxidation and are therefore classified as chemicals. The names are standardized based on common biochemical nomenclature. The reactions and model description provide context for the species' roles in the pathway, allowing for accurate classification and naming. The model's focus on fatty acid metabolism and the presence of CoA, carnitine, and FAD/NADH species support the chemical classification.
Synonyms dict: {'C16AcylCoAMAT': ['palmitoyl-CoA', 'hexadecanoyl-CoA', 'palmitoyl coenzyme A'], 'C16EnoylCoAMAT': ['hexadecenoyl-CoA', 'palmitoleoyl-CoA', '16-enoyl-CoA'], 'C16KetoacylCoAMAT': ['hexadecanoyl-CoA(16-keto)', '16-ketoacyl-CoA', 'palmitoyl-CoA(16-keto)'], 'C14AcylCoAMAT': ['tetradecanoyl-CoA', 'myristoyl-CoA', 'myristoyl coenzyme A'], 'C14EnoylCoAMAT': ['tetradecenoyl-CoA', 'myristoleoyl-CoA', '14-enoyl-CoA'], 'C14KetoacylCoAMAT': ['tetradecanoyl-CoA(14-keto)', '14-ketoacyl-CoA', 'myristoyl-CoA(14-keto)'], 'C12AcylCoAMAT': ['dodecanoyl-CoA', 'lauronyl-CoA', 'lauronyl coenzyme A'], 'C12EnoylCoAMAT': ['dodecenoyl-CoA', 'lauroleoyl-CoA', '12-enoyl-CoA'], 'C12KetoacylCoAMAT': ['dodecanoyl-CoA(12-keto)', '12-ketoacyl-CoA', 'lauronyl-CoA(12-keto)'], 'C10AcylCoAMAT': ['decanoyl-CoA', 'capronyl-CoA', 'capronyl coenzyme A'], 'C10EnoylCoAMAT': ['decenoyl-CoA', 'caproleoyl-CoA', '10-enoyl-CoA'], 'C10KetoacylCoAMAT': ['decanoyl-CoA(10-keto)', '10-ketoacyl-CoA', 'capronyl-CoA(10-keto)'], 'C8AcylCoAMAT': ['octanoyl-CoA', 'capryloyl-CoA', 'capryloyl coenzyme A'], 'C8EnoylCoAMAT': ['octenoyl-CoA', 'caproleoyl-CoA', '8-enoyl-CoA'], 'C8KetoacylCoAMAT': ['octanoyl-CoA(8-keto)', '8-ketoacyl-CoA', 'capryloyl-CoA(8-keto)'], 'C6AcylCoAMAT': ['hexanoyl-CoA', 'caproonyl-CoA', 'caproonyl coenzyme A'], 'C6EnoylCoAMAT': ['hexenoyl-CoA', 'caprooleoyl-CoA', '6-enoyl-CoA'], 'C6KetoacylCoAMAT': ['hexanoyl-CoA(6-keto)', '6-ketoacyl-CoA', 'caproonyl-CoA(6-keto)'], 'C4AcylCoAMAT': ['butanoyl-CoA', 'butyryl-CoA', 'butyryl coenzyme A'], 'C4EnoylCoAMAT': ['butenoyl-CoA', 'butyroleoyl-CoA', '4-enoyl-CoA'], 'C4AcetoacylCoAMAT': ['acetoacetyl-CoA', 'acetoacetyl coenzyme A', '2-oxobutanoyl-CoA'], 'AcetylCoAMAT': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'FADHMAT': ['FADH2', 'flavin adenine dinucleotide (reduced)', 'reduced flavin adenine dinucleotide'], 'NADHMAT': ['NADH', 'nicotinamide adenine dinucleotide (reduced)', 'reduced nicotinamide adenine dinucleotide'], 'CoAMAT': ['CoA', 'coenzyme A', 'CoASH'], 'C16AcylCoACYT': ['palmitoyl-carnitine', 'hexadecanoyl-carnitine', 'palmitoyl-L-carnitine'], 'CarCYT': ['L-carnitine', 'carnitine', 'levocarnitine'], 'CoACYT': ['acetyl-carnitine', 'acetylcarnitine', 'O-acetylcarnitine'], 'MalCoACYT': ['malonyl-carnitine', 'malonyl-L-carnitine', '3-carboxypropionyl-L-carnitine'], 'CarMAT': ['carnitine', 'L-carnitine', 'levocarnitine'], 'FADtMAT': ['FAD', 'flavin adenine dinucleotide', 'oxidized flavin adenine dinucleotide'], 'CoAMATt': ['CoA', 'coenzyme A', 'CoASH']}
Evaluating 507/1075: BIOMD0000000507.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000507.txt
LLM response:
species_3 (chemical): "IPTG", "isopropyl β-D-1-thiogalactopyranoside", "isopropylthiogalactoside"
Reason: IPTG is a chemical compound commonly used in molecular biology as an inducer of gene expression, which is consistent with its role in the genetic toggle switch model.
Synonyms dict: {'species_3': ['IPTG', 'isopropyl β-D-1-thiogalactopyranoside', 'isopropylthiogalactoside']}
Evaluating 508/1075: BIOMD0000000508.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000508.txt
LLM response:
ip3 (chemical): "inositol trisphosphate", "IP3", "myo-inositol 1,4,5-trisphosphate"
atp (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
y (unknown): "UNK", "Cyclin D", "cell cycle regulator"
ca (chemical): "calcium", "Ca2+", "calcium ion"

Reason: ip3 is identified as a chemical because it is involved in the model as a reactant and is a well-known second messenger molecule. atp is also a chemical, being a key energy currency molecule in cellular processes. y is unknown because its identity is not explicitly stated in the model, although it is likely related to Cyclin D based on the model description. ca is a chemical, representing calcium ions, which play a crucial role in the model as a signaling molecule.
Synonyms dict: {'ip3': ['inositol trisphosphate', 'IP3', 'myo-inositol 1,4,5-trisphosphate'], 'atp': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'y': ['UNK', 'Cyclin D', 'cell cycle regulator'], 'ca': ['calcium', 'Ca2+', 'calcium ion']}
Evaluating 509/1075: BIOMD0000000509.xml

2025-11-20 13:09:41,470 - WARNING - Skipping BIOMD0000000517.xml - no results generated
2025-11-20 13:09:41,475 - WARNING - Skipping BIOMD0000000518.xml - no results generated
2025-11-20 13:09:41,479 - WARNING - Skipping BIOMD0000000519.xml - no results generated
2025-11-20 13:09:41,484 - WARNING - Skipping BIOMD0000000520.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000516.txt
LLM response:
DHAP_c (chemical): "dihydroxyacetone phosphate", "DHAP", "glycerone phosphate"
ATP_g (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
DHAP_g (chemical): "dihydroxyacetone phosphate", "DHAP", "glycerone phosphate"
ADP_g (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Glc6P_g (chemical): "glucose-6-phosphate", "G6P", "glucose 6-phosphate"
ADP_c (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
_3PGA_c (chemical): "3-phosphoglycerate", "3-PGA", "3-phosphoglyceric acid"
O2_c (chemical): "oxygen", "O2", "molecular oxygen"
NADP_c (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP+", "NADP"
ATP_c (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
NADP_g (chemical): "nicotinamide adenine dinucleotide phosphate", "NADP+", "NADP"
_6PG_g (chemical): "6-phosphogluconate", "6-PG", "6-phosphogluconic acid"
CO2_c (chemical): "carbon dioxide", "CO2", "carbonic acid"
Rul5P_c (chemical): "ribulose-5-phosphate", "R5P", "ribulose 5-phosphate"
_6PG_c (chemical): "6-phosphogluconate", "6-PG", "6-phosphogluconic acid"
Rul5P_g (chemical): "ribulose-5-phosphate", "R5P", "ribulose 5-phosphate"
Glc6P_c (chemical): "glucose-6-phosphate", "G6P", "glucose 6-phosphate"
Rib5P_c (chemical): "ribose-5-phosphate", "R5P", "ribose 5-phosphate"
Glc_c (chemical): "glucose", "Glc", "D-glucose"
Rib5P_g (chemical): "ribose-5-phosphate", "R5P", "ribose 5-phosphate"
Glc_g (chemical): "glucose", "Glc", "D-glucose"
Glc_e (chemical): "glucose", "Glc", "D-glucose"
NADPH_g (chemical): "nicotinamide adenine dinucleotide phosphate (reduced)", "NADPH", "NADP reduced"
NADPH_c (chemical): "nicotinamide adenine dinucleotide phosphate (reduced)", "NADPH", "NADP reduced"
Pyr_c (chemical): "pyruvate", "Pyr", "pyruvic acid"
Pyr_e (chemical): "pyruvate", "Pyr", "pyruvic acid"
Fru16BP_g (chemical): "fructose-1,6-bisphosphate", "F1,6BP", "fructose 1,6-bisphosphate"
GA3P_g (chemical): "glyceraldehyde-3-phosphate", "G3P", "glyceraldehyde 3-phosphate"
Gly_e (chemical): "glycine", "Gly", "aminoacetic acid"
TSH2_c (chemical): "trypanothione disulfide", "T(SH)2", "trypanothione"
CO2_g (chemical): "carbon dioxide", "CO2", "carbonic acid"
Gly3P_c (chemical): "glycerol-3-phosphate", "G3P", "glycerol 3-phosphate"
Gly3P_g (chemical): "glycerol-3-phosphate", "G3P", "glycerol 3-phosphate"
TS2_c (chemical): "trypanothione", "T(SH)2", "trypanothione"
PEP_c (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
AMP_g (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
_3PGA_g (chemical): "3-phosphoglycerate", "3-PGA", "3-phosphoglyceric acid"
AMP_c (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
NADH_g (chemical): "nicotinamide adenine dinucleotide (reduced)", "NADH", "NAD reduced"
Reason: The model is a biochemical network of glycolysis and pentose phosphate pathway in Trypanosoma brucei, and all species are identified as chemicals based on their roles in the metabolic pathways. The species IDs are assigned based on their compartments (e.g., _c for cytosol, _g for glycosome, _e for extracellular) and their biochemical names. The synonyms are provided based on common names and abbreviations used in biochemistry.
Synonyms dict: {'DHAP_c': ['dihydroxyacetone phosphate', 'DHAP', 'glycerone phosphate'], 'ATP_g': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'DHAP_g': ['dihydroxyacetone phosphate', 'DHAP', 'glycerone phosphate'], 'ADP_g': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'Glc6P_g': ['glucose-6-phosphate', 'G6P', 'glucose 6-phosphate'], 'ADP_c': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], '_3PGA_c': ['3-phosphoglycerate', '3-PGA', '3-phosphoglyceric acid'], 'O2_c': ['oxygen', 'O2', 'molecular oxygen'], 'NADP_c': ['nicotinamide adenine dinucleotide phosphate', 'NADP+', 'NADP'], 'ATP_c': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'NADP_g': ['nicotinamide adenine dinucleotide phosphate', 'NADP+', 'NADP'], '_6PG_g': ['6-phosphogluconate', '6-PG', '6-phosphogluconic acid'], 'CO2_c': ['carbon dioxide', 'CO2', 'carbonic acid'], 'Rul5P_c': ['ribulose-5-phosphate', 'R5P', 'ribulose 5-phosphate'], '_6PG_c': ['6-phosphogluconate', '6-PG', '6-phosphogluconic acid'], 'Rul5P_g': ['ribulose-5-phosphate', 'R5P', 'ribulose 5-phosphate'], 'Glc6P_c': ['glucose-6-phosphate', 'G6P', 'glucose 6-phosphate'], 'Rib5P_c': ['ribose-5-phosphate', 'R5P', 'ribose 5-phosphate'], 'Glc_c': ['glucose', 'Glc', 'D-glucose'], 'Rib5P_g': ['ribose-5-phosphate', 'R5P', 'ribose 5-phosphate'], 'Glc_g': ['glucose', 'Glc', 'D-glucose'], 'Glc_e': ['glucose', 'Glc', 'D-glucose'], 'NADPH_g': ['nicotinamide adenine dinucleotide phosphate (reduced)', 'NADPH', 'NADP reduced'], 'NADPH_c': ['nicotinamide adenine dinucleotide phosphate (reduced)', 'NADPH', 'NADP reduced'], 'Pyr_c': ['pyruvate', 'Pyr', 'pyruvic acid'], 'Pyr_e': ['pyruvate', 'Pyr', 'pyruvic acid'], 'Fru16BP_g': ['fructose-1,6-bisphosphate', 'F1,6BP', 'fructose 1,6-bisphosphate'], 'GA3P_g': ['glyceraldehyde-3-phosphate', 'G3P', 'glyceraldehyde 3-phosphate'], 'Gly_e': ['glycine', 'Gly', 'aminoacetic acid'], 'TSH2_c': ['trypanothione disulfide', 'T(SH)2', 'trypanothione'], 'CO2_g': ['carbon dioxide', 'CO2', 'carbonic acid'], 'Gly3P_c': ['glycerol-3-phosphate', 'G3P', 'glycerol 3-phosphate'], 'Gly3P_g': ['glycerol-3-phosphate', 'G3P', 'glycerol 3-phosphate'], 'TS2_c': ['trypanothione', 'T(SH)2', 'trypanothione'], 'PEP_c': ['phosphoenolpyruvate', 'PEP', 'phosphoenolpyruvic acid'], 'AMP_g': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], '_3PGA_g': ['3-phosphoglycerate', '3-PGA', '3-phosphoglyceric acid'], 'AMP_c': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'NADH_g': ['nicotinamide adenine dinucleotide (reduced)', 'NADH', 'NAD reduced']}
Evaluating 517/1075: BIOMD0000000517.xml
Evaluating 518/1075: BIOMD0000000518.xml
Evaluating 519/1075: BIOMD0000000519.xml
Evaluating 520/1075: BIOMD0000000520.xml
Evaluating 521/1075: BIOMD0000000521.xml

2025-11-20 13:09:42,604 - WARNING - Skipping BIOMD0000000522.xml - no results generated
2025-11-20 13:09:42,611 - WARNING - Skipping BIOMD0000000523.xml - no results generated
2025-11-20 13:09:42,619 - WARNING - Skipping BIOMD0000000524.xml - no results generated
2025-11-20 13:09:42,629 - WARNING - Skipping BIOMD0000000525.xml - no results generated
2025-11-20 13:09:42,639 - WARNING - Skipping BIOMD0000000526.xml - no results generated
2025-11-20 13:09:42,642 - WARNING - Skipping BIOMD0000000527.xml - no results generated
2025-11-20 13:09:42,648 - WARNING - Skipping BIOMD0000000528.xml - no results generated
2025-11-20 13:09:42,654 - WARNING - Skipping BIOMD0000000529.xml - no results generated
2025-11-20 13:09:42,662 - WARNING - Skipping BIOMD0000000530.xml - no results generated
2025-11-20 13:09:42,665 - WARNING - Skipping BIOMD0000000531.xml - no results generated
2025-11-20 13:09:42,668 - WARNING - Skipping BIOMD0000000532.xml - no results generated
2025-11-20 13:09:42,672 - WARNING - Skipping BIOMD0000000533.xml - no results generated
2025-11-20 13:09:42,698 - WARNING - Skipping BIOMD0000000534.xml - no results generated
2025-11-20 13:09:42,724 - WARNING - Skipping BIOMD0000000535.xml - no results generated
2025-11-20 13:09:42,749 - WARNING - Skipping BIOMD0000000536.xml - no results generated
2025-11-20 13:09:42,775 - WARNING - Skipping BIOMD0000000537.xml - no results generated
2025-11-20 13:09:42,779 - WARNING - Skipping BIOMD0000000538.xml - no results generated
2025-11-20 13:09:42,785 - WARNING - Skipping BIOMD0000000539.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000521.txt
LLM response:
C (chemical): "PCV", "Procarbazine, CCNU and Vincristine", "PCV chemotherapy"
Reason: The species C is annotated as "PCV_plasma" in the display names, which refers to the PCV chemotherapy regimen, a combination of procarbazine, lomustine (CCNU), and vincristine, indicating that C represents a chemical entity, specifically a chemotherapy agent.
Synonyms dict: {'C': ['PCV', 'Procarbazine, CCNU and Vincristine', 'PCV chemotherapy']}
Evaluating 522/1075: BIOMD0000000522.xml
Evaluating 523/1075: BIOMD0000000523.xml
Evaluating 524/1075: BIOMD0000000524.xml
Evaluating 525/1075: BIOMD0000000525.xml
Evaluating 526/1075: BIOMD0000000526.xml
Evaluating 527/1075: BIOMD0000000527.xml
Evaluating 528/1075: BIOMD0000000528.xml
Evaluating 529/1075: BIOMD0000000529.xml
Evaluating 530/1075: BIOMD0000000530.xml
Evaluating 531/1075: BIOMD0000000531.xml
Evaluating 532/1075: BIOMD0000000532.xml
Evaluating 533/1075: BIOMD0000000533.xml
Evaluating 534/1075: BIOMD0000000534.xml
Evaluating 535/1075: BIOMD0000000535.xml
Evaluating 536/1075: BIOMD0000000536.xml
Evaluating 537/1075: BIOMD0000000537.xml
Evaluating 538/1075: BIOMD0000000538.xml
Evaluating 539/1075: BIOMD0000000539.xml
Evaluating 540/1075: BIOMD0000000540.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000540.txt
LLM response:
s3 (chemical): "Fructose-6-phosphate", "F6P", "Fructose 6-phosphate"
s4 (chemical): "Fructose-1,6-bisphosphate", "F1,6BP", "Fructose 1,6-bisphosphate"
s5 (chemical): "Phosphoenolpyruvate", "PEP", "Phosphoenolpyric acid"
s6 (chemical): "Isocitrate", "Isocitric acid", "D-Isocitrate"
s7 (chemical): "2-Oxoglutarate", "Alpha-ketoglutarate", "2-Ketoglutarate"
s8 (chemical): "Malate", "Malic acid", "L-Malic acid"
s9 (chemical): "Fructose-2,6-bisphosphate", "F2,6BP", "Fructose 2,6-bisphosphate"
s10 (chemical): "Citrate", "Citric acid", "Sodium citrate"
s22 (chemical): "Fructose-6-phosphate proxy", "F6P proxy", "Fructose 6-phosphate surrogate"
Reason: The species are identified based on their display names and the context of the model, which appears to be a glycolytic pathway. The display names are used to determine the chemical names, and the entity type is determined to be chemical for all species as they are all metabolites in the glycolytic pathway. s22 is identified as a proxy for Fructose-6-phosphate, likely used for modeling purposes.
Synonyms dict: {'s3': ['Fructose-6-phosphate', 'F6P', 'Fructose 6-phosphate'], 's4': ['Fructose-1,6-bisphosphate', 'F1,6BP', 'Fructose 1,6-bisphosphate'], 's5': ['Phosphoenolpyruvate', 'PEP', 'Phosphoenolpyric acid'], 's6': ['Isocitrate', 'Isocitric acid', 'D-Isocitrate'], 's7': ['2-Oxoglutarate', 'Alpha-ketoglutarate', '2-Ketoglutarate'], 's8': ['Malate', 'Malic acid', 'L-Malic acid'], 's9': ['Fructose-2,6-bisphosphate', 'F2,6BP', 'Fructose 2,6-bisphosphate'], 's10': ['Citrate', 'Citric acid', 'Sodium citrate'], 's22': ['Fructose-6-phosphate proxy', 'F6P proxy', 'Fructose 6-phosphate surrogate']}
Evaluating 541/1075: BIOMD0000000541.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000541.txt
LLM response:
s3 (chemical): "Fructose-6-phosphate", "F6P", "Fructose 6-phosphate"
s4 (chemical): "Fructose-1,6-bisphosphate", "F1,6BP", "Fructose 1,6-bisphosphate"
s5 (chemical): "Phosphoenolpyruvate", "PEP", "Phosphoenolpyruvic acid"
s6 (chemical): "Isocitrate", "Isocitric acid", "D-Isocitrate"
s7 (chemical): "2-Oxoglutarate", "Alpha-ketoglutarate", "2-Ketoglutarate"
s8 (chemical): "Malate", "Malic acid", "L-Malate"
s9 (chemical): "Fructose-2,6-bisphosphate", "F2,6BP", "Fructose 2,6-bisphosphate"
s10 (chemical): "Citrate", "Citric acid", "Citrate ion"
s22 (chemical): "Fructose-6-phosphate proxy", "F6P proxy", "Fructose 6-phosphate surrogate"
Reason: The species are identified based on their display names and the context of the model, which is related to glycolysis and insulin-induced signaling. The entity types are determined as chemical because they are all metabolites involved in the glycolytic pathway. s22 is considered a chemical proxy for F6P, as indicated by its name and reaction with s4.
Synonyms dict: {'s3': ['Fructose-6-phosphate', 'F6P', 'Fructose 6-phosphate'], 's4': ['Fructose-1,6-bisphosphate', 'F1,6BP', 'Fructose 1,6-bisphosphate'], 's5': ['Phosphoenolpyruvate', 'PEP', 'Phosphoenolpyruvic acid'], 's6': ['Isocitrate', 'Isocitric acid', 'D-Isocitrate'], 's7': ['2-Oxoglutarate', 'Alpha-ketoglutarate', '2-Ketoglutarate'], 's8': ['Malate', 'Malic acid', 'L-Malate'], 's9': ['Fructose-2,6-bisphosphate', 'F2,6BP', 'Fructose 2,6-bisphosphate'], 's10': ['Citrate', 'Citric acid', 'Citrate ion'], 's22': ['Fructose-6-phosphate proxy', 'F6P proxy', 'Fructose 6-phosphate surrogate']}
Evaluating 542/1075: BIOMD0000000542.xml

2025-11-20 13:09:50,823 - WARNING - Skipping BIOMD0000000543.xml - no results generated
2025-11-20 13:09:50,883 - WARNING - Skipping BIOMD0000000544.xml - no results generated
2025-11-20 13:09:50,889 - WARNING - Skipping BIOMD0000000545.xml - no results generated
2025-11-20 13:09:50,910 - WARNING - Skipping BIOMD0000000546.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000542.txt
LLM response:
ADP (chemical): "adenosine diphosphate", "ADP molecule", "adenosine 5'-diphosphate"
ATP (chemical): "adenosine triphosphate", "ATP molecule", "adenosine 5'-triphosphate"
Reason: ADP and ATP are both chemical species as they are involved in energy transfer reactions within the cell, and their display names match common biochemical nomenclature. They are likely to be adenosine diphosphate and adenosine triphosphate, respectively, which are crucial molecules in cellular metabolism.
Synonyms dict: {'ADP': ['adenosine diphosphate', 'ADP molecule', "adenosine 5'-diphosphate"], 'ATP': ['adenosine triphosphate', 'ATP molecule', "adenosine 5'-triphosphate"]}
Evaluating 543/1075: BIOMD0000000543.xml
Evaluating 544/1075: BIOMD0000000544.xml
Evaluating 545/1075: BIOMD0000000545.xml
Evaluating 546/1075: BIOMD0000000546.xml
Evaluating 547/1075: BIOMD0000000547.xml

2025-11-20 13:09:53,605 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:09:53,624 - WARNING - Skipping BIOMD0000000548.xml - no results generated
2025-11-20 13:09:53,627 - WARNING - Skipping BIOMD0000000549.xml - no results generated
2025-11-20 13:09:53,630 - WARNING - Skipping BIOMD0000000550.xml - no results generated
2025-11-20 13:09:53,635 - WARNING - Skipping BIOMD0000000551.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000547.txt
LLM response:
species_6 (chemical): "arsenite", "arsenic(III)", "AsIII"
species_4 (chemical): "vacuolar arsenic-glutathione conjugate", "vAsGS3", "arsenic-glutathione complex"
species_3 (chemical): "arsenic-glutathione conjugate", "AsGS3", "glutathione-conjugated arsenic"
species_1 (chemical): "intracellular arsenite", "AsIIIin", "free arsenic(III)"
species_2 (protein): "arsenic-bound protein", "AsIIIprot", "protein-bound arsenic"
species_7 (chemical): "glutathione", "GSH", "reduced glutathione"
Reason: The entity types are determined based on the display names and the context of the model. species_6, species_4, species_3, species_1, and species_7 are classified as chemicals because they represent different forms of arsenic or glutathione. species_2 is classified as a protein because it represents protein-bound arsenic. The standardized names and synonyms are chosen based on the display names and the common terminology used in the field of biochemistry and toxicology.
Synonyms dict: {'species_6': ['arsenite', 'arsenic(III)', 'AsIII'], 'species_4': ['vacuolar arsenic-glutathione conjugate', 'vAsGS3', 'arsenic-glutathione complex'], 'species_3': ['arsenic-glutathione conjugate', 'AsGS3', 'glutathione-conjugated arsenic'], 'species_1': ['intracellular arsenite', 'AsIIIin', 'free arsenic(III)'], 'species_2': ['arsenic-bound protein', 'AsIIIprot', 'protein-bound arsenic'], 'species_7': ['glutathione', 'GSH', 'reduced glutathione']}
Evaluating 548/1075: BIOMD0000000548.xml
Evaluating 549/1075: BIOMD0000000549.xml
Evaluating 550/1075: BIOMD0000000550.xml
Evaluating 551/1075: BIOMD0000000551.xml
Evaluating 552/1075: BIOMD0000000552.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000552.txt
LLM response:
a (chemical): "acetylcholine", "ACh", "acetylcholine neurotransmitter"
aRel (unknown): "UNK", "unknown entity", "unspecified reactant"
Reason: a is likely acetylcholine due to the model's context, which focuses on the loss of acetylcholine in Alzheimer's disease. aRel is unknown because its display name and reactions do not provide sufficient information to determine its entity type or standardized name.
Synonyms dict: {'a': ['acetylcholine', 'ACh', 'acetylcholine neurotransmitter'], 'aRel': ['UNK', 'unknown entity', 'unspecified reactant']}
Evaluating 553/1075: BIOMD0000000553.xml

2025-11-20 13:09:55,654 - WARNING - Skipping BIOMD0000000553.xml - no results generated

Evaluating 554/1075: BIOMD0000000554.xml

2025-11-20 13:10:08,426 - WARNING - Skipping BIOMD0000000555.xml - no results generated
2025-11-20 13:10:08,432 - WARNING - Skipping BIOMD0000000556.xml - no results generated
2025-11-20 13:10:08,443 - WARNING - Skipping BIOMD0000000557.xml - no results generated
2025-11-20 13:10:08,448 - WARNING - Skipping BIOMD0000000558.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000554.txt
LLM response:
NAg (chemical): "sodium ion", "Na+", "sodium"
GLCg (chemical): "glucose", "D-glucose", "blood sugar"
G6Pg (chemical): "glucose-6-phosphate", "G6P", "glucose 6-phosphate"
F6Pg (chemical): "fructose-6-phosphate", "F6P", "fructose 6-phosphate"
GAPg (chemical): "glyceraldehyde-3-phosphate", "GAP", "glyceraldehyde 3-phosphate"
PEPg (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
PYRg (chemical): "pyruvate", "PYR", "pyruvic acid"
LACg (chemical): "lactate", "LAC", "lactic acid"
NADHg (chemical): "NADH", "nicotinamide adenine dinucleotide + hydrogen", "reduced NAD"
ATPg (chemical): "ATP", "adenosine triphosphate", "adenosine 5'-triphosphate"
PCrg (chemical): "phosphocreatine", "PCr", "creatine phosphate"
O2g (chemical): "oxygen", "O2", "molecular oxygen"
GLUg (chemical): "glutamate", "GLU", "L-glutamic acid"
NADg (chemical): "NAD+", "nicotinamide adenine dinucleotide", "oxidized NAD"
ADPg (chemical): "ADP", "adenosine diphosphate", "adenosine 5'-diphosphate"
CRg (chemical): "creatine", "CR", "methylguanidineacetic acid"
NADH_g_tot (chemical): "total NADH", "NADH total", "total reduced NAD"
PCrg_tot (chemical): "total phosphocreatine", "PCr total", "total creatine phosphate"
AMPg (chemical): "AMP", "adenosine monophosphate", "adenosine 5'-monophosphate"
O2c (chemical): "oxygen", "O2", "molecular oxygen"
GLCc (chemical): "glucose", "D-glucose", "blood sugar"
LACc (chemical): "lactate", "LAC", "lactic acid"
CO2c (chemical): "carbon dioxide", "CO2", "molecular carbon dioxide"
GLCe (chemical): "glucose", "D-glucose", "blood sugar"
LACe (chemical): "lactate", "LAC", "lactic acid"
GLUe (chemical): "glutamate", "GLU", "L-glutamic acid"
NAe (chemical): "sodium ion", "Na+", "sodium"
O2a (chemical): "oxygen", "O2", "molecular oxygen"
CO2a (chemical): "carbon dioxide", "CO2", "molecular carbon dioxide"
GLCa (chemical): "glucose", "D-glucose", "blood sugar"
LACa (chemical): "lactate", "LAC", "lactic acid"
NAn (chemical): "sodium ion", "Na+", "sodium"
GLCn (chemical): "glucose", "D-glucose", "blood sugar"
G6Pn (chemical): "glucose-6-phosphate", "G6P", "glucose 6-phosphate"
F6Pn (chemical): "fructose-6-phosphate", "F6P", "fructose 6-phosphate"
GAPn (chemical): "glyceraldehyde-3-phosphate", "GAP", "glyceraldehyde 3-phosphate"
PEPn (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
PYRn (chemical): "pyruvate", "PYR", "pyruvic acid"
LACn (chemical): "lactate", "LAC", "lactic acid"
NADHn (chemical): "NADH", "nicotinamide adenine dinucleotide + hydrogen", "reduced NAD"
ATPn (chemical): "ATP", "adenosine triphosphate", "adenosine 5'-triphosphate"
PCrn (chemical): "phosphocreatine", "PCr", "creatine phosphate"
O2n (chemical): "oxygen", "O2", "molecular oxygen"
GLUn (chemical): "glutamate", "GLU", "L-glutamic acid"
ADPn (chemical): "ADP", "adenosine diphosphate", "adenosine 5'-diphosphate"
CRn (chemical): "creatine", "CR", "methylguanidineacetic acid"
NADn (chemical): "NAD+", "nicotinamide adenine dinucleotide", "oxidized NAD"
NADH_n_tot (chemical): "total NADH", "NADH total", "total reduced NAD"
PCrn_tot (chemical): "total phosphocreatine", "PCr total", "total creatine phosphate"
AMPn (chemical): "AMP", "adenosine monophosphate", "adenosine 5'-monophosphate"
Reason: All species are metabolites or ions involved in brain energy metabolism, and their names and synonyms are based on standard biochemical nomenclature. The suffixes 'g', 'c', 'e', 'a', and 'n' likely refer to different cellular compartments or locations (e.g., glial cells, capillaries, extracellular space, astrocytes, and neurons), but do not affect the entity type or standardized names of the species.
Synonyms dict: {'NAg': ['sodium ion', 'Na+', 'sodium'], 'GLCg': ['glucose', 'D-glucose', 'blood sugar'], 'G6Pg': ['glucose-6-phosphate', 'G6P', 'glucose 6-phosphate'], 'F6Pg': ['fructose-6-phosphate', 'F6P', 'fructose 6-phosphate'], 'GAPg': ['glyceraldehyde-3-phosphate', 'GAP', 'glyceraldehyde 3-phosphate'], 'PEPg': ['phosphoenolpyruvate', 'PEP', 'phosphoenolpyruvic acid'], 'PYRg': ['pyruvate', 'PYR', 'pyruvic acid'], 'LACg': ['lactate', 'LAC', 'lactic acid'], 'NADHg': ['NADH', 'nicotinamide adenine dinucleotide + hydrogen', 'reduced NAD'], 'ATPg': ['ATP', 'adenosine triphosphate', "adenosine 5'-triphosphate"], 'PCrg': ['phosphocreatine', 'PCr', 'creatine phosphate'], 'O2g': ['oxygen', 'O2', 'molecular oxygen'], 'GLUg': ['glutamate', 'GLU', 'L-glutamic acid'], 'NADg': ['NAD+', 'nicotinamide adenine dinucleotide', 'oxidized NAD'], 'ADPg': ['ADP', 'adenosine diphosphate', "adenosine 5'-diphosphate"], 'CRg': ['creatine', 'CR', 'methylguanidineacetic acid'], 'NADH_g_tot': ['total NADH', 'NADH total', 'total reduced NAD'], 'PCrg_tot': ['total phosphocreatine', 'PCr total', 'total creatine phosphate'], 'AMPg': ['AMP', 'adenosine monophosphate', "adenosine 5'-monophosphate"], 'O2c': ['oxygen', 'O2', 'molecular oxygen'], 'GLCc': ['glucose', 'D-glucose', 'blood sugar'], 'LACc': ['lactate', 'LAC', 'lactic acid'], 'CO2c': ['carbon dioxide', 'CO2', 'molecular carbon dioxide'], 'GLCe': ['glucose', 'D-glucose', 'blood sugar'], 'LACe': ['lactate', 'LAC', 'lactic acid'], 'GLUe': ['glutamate', 'GLU', 'L-glutamic acid'], 'NAe': ['sodium ion', 'Na+', 'sodium'], 'O2a': ['oxygen', 'O2', 'molecular oxygen'], 'CO2a': ['carbon dioxide', 'CO2', 'molecular carbon dioxide'], 'GLCa': ['glucose', 'D-glucose', 'blood sugar'], 'LACa': ['lactate', 'LAC', 'lactic acid'], 'NAn': ['sodium ion', 'Na+', 'sodium'], 'GLCn': ['glucose', 'D-glucose', 'blood sugar'], 'G6Pn': ['glucose-6-phosphate', 'G6P', 'glucose 6-phosphate'], 'F6Pn': ['fructose-6-phosphate', 'F6P', 'fructose 6-phosphate'], 'GAPn': ['glyceraldehyde-3-phosphate', 'GAP', 'glyceraldehyde 3-phosphate'], 'PEPn': ['phosphoenolpyruvate', 'PEP', 'phosphoenolpyruvic acid'], 'PYRn': ['pyruvate', 'PYR', 'pyruvic acid'], 'LACn': ['lactate', 'LAC', 'lactic acid'], 'NADHn': ['NADH', 'nicotinamide adenine dinucleotide + hydrogen', 'reduced NAD'], 'ATPn': ['ATP', 'adenosine triphosphate', "adenosine 5'-triphosphate"], 'PCrn': ['phosphocreatine', 'PCr', 'creatine phosphate'], 'O2n': ['oxygen', 'O2', 'molecular oxygen'], 'GLUn': ['glutamate', 'GLU', 'L-glutamic acid'], 'ADPn': ['ADP', 'adenosine diphosphate', "adenosine 5'-diphosphate"], 'CRn': ['creatine', 'CR', 'methylguanidineacetic acid'], 'NADn': ['NAD+', 'nicotinamide adenine dinucleotide', 'oxidized NAD'], 'NADH_n_tot': ['total NADH', 'NADH total', 'total reduced NAD'], 'PCrn_tot': ['total phosphocreatine', 'PCr total', 'total creatine phosphate'], 'AMPn': ['AMP', 'adenosine monophosphate', "adenosine 5'-monophosphate"]}
Evaluating 555/1075: BIOMD0000000555.xml
Evaluating 556/1075: BIOMD0000000556.xml
Evaluating 557/1075: BIOMD0000000557.xml
Evaluating 558/1075: BIOMD0000000558.xml
Evaluating 559/1075: BIOMD0000000559.xml

2025-11-20 13:10:23,131 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:10:23,311 - WARNING - Skipping BIOMD0000000560.xml - no results generated
2025-11-20 13:10:23,314 - WARNING - Skipping BIOMD0000000561.xml - no results generated
2025-11-20 13:10:23,322 - WARNING - Skipping BIOMD0000000562.xml - no results generated
2025-11-20 13:10:23,329 - WARNING - Skipping BIOMD0000000563.xml - no results generated
2025-11-20 13:10:23,351 - WARNING - Skipping BIOMD0000000564.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000559.txt
LLM response:
s482 (protein): "alpha-synuclein dimer", "ASYN dimer", "Lewy Body protein dimer"
s483 (protein): "alpha-synuclein trimer", "ASYN trimer", "Lewy Body protein trimer"
s484 (protein): "alpha-synuclein tetramer", "ASYN tetramer", "Lewy Body protein tetramer"
s489 (protein): "alpha-synuclein heptamer", "ASYN heptamer", "Lewy Body protein heptamer"
s490 (protein): "alpha-synuclein hexamer on Lamp2a", "ASYN hexamer on Lamp2a", "Lewy Body protein hexamer on Lamp2a"
s491 (protein): "alpha-synuclein pentamer on Lamp2a", "ASYN pentamer on Lamp2a", "Lewy Body protein pentamer on Lamp2a"
s492 (protein): "alpha-synuclein octamer on Lamp2a", "ASYN octamer on Lamp2a", "Lewy Body protein octamer on Lamp2a"
s493 (protein): "alpha-synuclein nonamer on Lamp2a", "ASYN nonamer on Lamp2a", "Lewy Body protein nonamer on Lamp2a"
s536 (protein): "alpha-synuclein on Lamp2a", "ASYN on Lamp2a", "Lewy Body protein on Lamp2a"
s445 (protein): "alpha-synuclein dimer modified", "ASYN dimer modified", "Lewy Body protein dimer modified"
s446 (protein): "alpha-synuclein trimer modified", "ASYN trimer modified", "Lewy Body protein trimer modified"
s447 (protein): "alpha-synuclein tetramer modified", "ASYN tetramer modified", "Lewy Body protein tetramer modified"
s448 (protein): "alpha-synuclein hexamer modified", "ASYN hexamer modified", "Lewy Body protein hexamer modified"
s451 (protein): "alpha-synuclein octamer modified", "ASYN octamer modified", "Lewy Body protein octamer modified"
s524 (protein): "alpha-synuclein heptamer modified", "ASYN heptamer modified", "Lewy Body protein heptamer modified"
s525 (protein): "alpha-synuclein octamer", "ASYN octamer", "Lewy Body protein octamer"
s526 (protein): "alpha-synuclein heptamer", "ASYN heptamer", "Lewy Body protein heptamer"
s528 (protein): "alpha-synuclein hexamer", "ASYN hexamer", "Lewy Body protein hexamer"
s529 (protein): "alpha-synuclein pentamer", "ASYN pentamer", "Lewy Body protein pentamer"
s530 (protein): "alpha-synuclein tetramer", "ASYN tetramer", "Lewy Body protein tetramer"
s531 (protein): "alpha-synuclein trimer", "ASYN trimer", "Lewy Body protein trimer"
s535 (protein): "alpha-synuclein", "ASYN", "Lewy Body protein"
s527 (protein): "alpha-synuclein dimer", "ASYN dimer", "Lewy Body protein dimer"
s1 (protein): "alpha-synuclein pentamer", "ASYN pentamer", "Lewy Body protein pentamer"
s2 (protein): "alpha-synuclein tetramer", "ASYN tetramer", "Lewy Body protein tetramer"
s5 (protein): "alpha-synuclein trimer", "ASYN trimer", "Lewy Body protein trimer"
s6 (protein): "alpha-synuclein dimer", "ASYN dimer", "Lewy Body protein dimer"
s21 (protein): "alpha-synuclein hexamer", "ASYN hexamer", "Lewy Body protein hexamer"
s22 (chemical): "dopamine", "DA", "3,4-dihydroxyphenethylamine"
s25 (protein): "alpha-synuclein heptamer", "ASYN heptamer", "Lewy Body protein heptamer"
s26 (protein): "alpha-synuclein octamer", "ASYN octamer", "Lewy Body protein octamer"
s27 (protein): "alpha-synuclein nonamer", "ASYN nonamer", "Lewy Body protein nonamer"
s200 (chemical): "degraded dopamine", "DA degradation product", "3,4-dihydroxyphenylacetic acid"
s473 (protein): "proteasome-modified alpha-synuclein trimer", "ASYN trimer modified by proteasome", "Lewy Body protein trimer modified by proteasome"
s474 (protein): "proteasome-modified alpha-synuclein tetramer", "ASYN tetramer modified by proteasome", "Lewy Body protein tetramer modified by proteasome"
s475 (protein): "proteasome-modified alpha-synuclein pentamer", "ASYN pentamer modified by proteasome", "Lewy Body protein pentamer modified by proteasome"
s476 (protein): "proteasome-modified alpha-synuclein hexamer", "ASYN hexamer modified by proteasome", "Lewy Body protein hexamer modified by proteasome"
s477 (protein): "proteasome-modified alpha-synuclein heptamer", "ASYN heptamer modified by proteasome", "Lewy Body protein heptamer modified by proteasome"
s478 (protein): "proteasome-modified alpha-synuclein octamer", "ASYN octamer modified by proteasome", "Lewy Body protein octamer modified by proteasome"
s479 (protein): "proteasome-modified alpha-synuclein nonamer", "ASYN nonamer modified by proteasome", "Lewy Body protein nonamer modified by proteasome"
s482 (protein): "alpha-synuclein dimer on Lamp2a", "ASYN dimer on Lamp2a", "Lewy Body protein dimer on Lamp2a"
s483 (protein): "alpha-synuclein trimer on Lamp2a", "ASYN trimer on Lamp2a", "Lewy Body protein trimer on Lamp2a"
s484 (protein): "alpha-synuclein tetramer on Lamp2a", "ASYN tetramer on Lamp2a", "Lewy Body protein tetramer on Lamp2a"
s491 (protein): "alpha-synuclein pentamer on Lamp2a", "ASYN pentamer on Lamp2a", "Lewy Body protein pentamer on Lamp2a"
s492 (protein): "alpha-synuclein octamer on Lamp2a", "ASYN octamer on Lamp2a", "Lewy Body protein octamer on Lamp2a"
s493 (protein): "alpha-synuclein nonamer on Lamp2a", "ASYN nonamer on Lamp2a", "Lewy Body protein nonamer on Lamp2a"

Reason: Most species are related to alpha-synuclein (ASYN) and its oligomers, which are proteins associated with Parkinson's disease. The model describes the dynamics of ASYN oligomerization, degradation, and interaction with other cellular components. Species s22 and s200 are related to dopamine, a chemical neurotransmitter. The proteasome-modified species (s473-s479) are proteins modified by the proteasome, a protein degradation complex. The species on Lamp2a (s482-s484, s491-s493) are proteins interacting with the Lamp2a receptor, which is involved in chaperone-mediated autophagy.
Synonyms dict: {'s482': ['alpha-synuclein dimer on Lamp2a', 'ASYN dimer on Lamp2a', 'Lewy Body protein dimer on Lamp2a'], 's483': ['alpha-synuclein trimer on Lamp2a', 'ASYN trimer on Lamp2a', 'Lewy Body protein trimer on Lamp2a'], 's484': ['alpha-synuclein tetramer on Lamp2a', 'ASYN tetramer on Lamp2a', 'Lewy Body protein tetramer on Lamp2a'], 's489': ['alpha-synuclein heptamer', 'ASYN heptamer', 'Lewy Body protein heptamer'], 's490': ['alpha-synuclein hexamer on Lamp2a', 'ASYN hexamer on Lamp2a', 'Lewy Body protein hexamer on Lamp2a'], 's491': ['alpha-synuclein pentamer on Lamp2a', 'ASYN pentamer on Lamp2a', 'Lewy Body protein pentamer on Lamp2a'], 's492': ['alpha-synuclein octamer on Lamp2a', 'ASYN octamer on Lamp2a', 'Lewy Body protein octamer on Lamp2a'], 's493': ['alpha-synuclein nonamer on Lamp2a', 'ASYN nonamer on Lamp2a', 'Lewy Body protein nonamer on Lamp2a'], 's536': ['alpha-synuclein on Lamp2a', 'ASYN on Lamp2a', 'Lewy Body protein on Lamp2a'], 's445': ['alpha-synuclein dimer modified', 'ASYN dimer modified', 'Lewy Body protein dimer modified'], 's446': ['alpha-synuclein trimer modified', 'ASYN trimer modified', 'Lewy Body protein trimer modified'], 's447': ['alpha-synuclein tetramer modified', 'ASYN tetramer modified', 'Lewy Body protein tetramer modified'], 's448': ['alpha-synuclein hexamer modified', 'ASYN hexamer modified', 'Lewy Body protein hexamer modified'], 's451': ['alpha-synuclein octamer modified', 'ASYN octamer modified', 'Lewy Body protein octamer modified'], 's524': ['alpha-synuclein heptamer modified', 'ASYN heptamer modified', 'Lewy Body protein heptamer modified'], 's525': ['alpha-synuclein octamer', 'ASYN octamer', 'Lewy Body protein octamer'], 's526': ['alpha-synuclein heptamer', 'ASYN heptamer', 'Lewy Body protein heptamer'], 's528': ['alpha-synuclein hexamer', 'ASYN hexamer', 'Lewy Body protein hexamer'], 's529': ['alpha-synuclein pentamer', 'ASYN pentamer', 'Lewy Body protein pentamer'], 's530': ['alpha-synuclein tetramer', 'ASYN tetramer', 'Lewy Body protein tetramer'], 's531': ['alpha-synuclein trimer', 'ASYN trimer', 'Lewy Body protein trimer'], 's535': ['alpha-synuclein', 'ASYN', 'Lewy Body protein'], 's527': ['alpha-synuclein dimer', 'ASYN dimer', 'Lewy Body protein dimer'], 's1': ['alpha-synuclein pentamer', 'ASYN pentamer', 'Lewy Body protein pentamer'], 's2': ['alpha-synuclein tetramer', 'ASYN tetramer', 'Lewy Body protein tetramer'], 's5': ['alpha-synuclein trimer', 'ASYN trimer', 'Lewy Body protein trimer'], 's6': ['alpha-synuclein dimer', 'ASYN dimer', 'Lewy Body protein dimer'], 's21': ['alpha-synuclein hexamer', 'ASYN hexamer', 'Lewy Body protein hexamer'], 's22': ['dopamine', 'DA', '3,4-dihydroxyphenethylamine'], 's25': ['alpha-synuclein heptamer', 'ASYN heptamer', 'Lewy Body protein heptamer'], 's26': ['alpha-synuclein octamer', 'ASYN octamer', 'Lewy Body protein octamer'], 's27': ['alpha-synuclein nonamer', 'ASYN nonamer', 'Lewy Body protein nonamer'], 's200': ['degraded dopamine', 'DA degradation product', '3,4-dihydroxyphenylacetic acid'], 's473': ['proteasome-modified alpha-synuclein trimer', 'ASYN trimer modified by proteasome', 'Lewy Body protein trimer modified by proteasome'], 's474': ['proteasome-modified alpha-synuclein tetramer', 'ASYN tetramer modified by proteasome', 'Lewy Body protein tetramer modified by proteasome'], 's475': ['proteasome-modified alpha-synuclein pentamer', 'ASYN pentamer modified by proteasome', 'Lewy Body protein pentamer modified by proteasome'], 's476': ['proteasome-modified alpha-synuclein hexamer', 'ASYN hexamer modified by proteasome', 'Lewy Body protein hexamer modified by proteasome'], 's477': ['proteasome-modified alpha-synuclein heptamer', 'ASYN heptamer modified by proteasome', 'Lewy Body protein heptamer modified by proteasome'], 's478': ['proteasome-modified alpha-synuclein octamer', 'ASYN octamer modified by proteasome', 'Lewy Body protein octamer modified by proteasome'], 's479': ['proteasome-modified alpha-synuclein nonamer', 'ASYN nonamer modified by proteasome', 'Lewy Body protein nonamer modified by proteasome']}
Evaluating 560/1075: BIOMD0000000560.xml
Evaluating 561/1075: BIOMD0000000561.xml
Evaluating 562/1075: BIOMD0000000562.xml
Evaluating 563/1075: BIOMD0000000563.xml
Evaluating 564/1075: BIOMD0000000564.xml
Evaluating 565/1075: BIOMD0000000565.xml

2025-11-20 13:10:32,161 - WARNING - Skipping BIOMD0000000566.xml - no results generated
2025-11-20 13:10:32,165 - WARNING - Skipping BIOMD0000000567.xml - no results generated
2025-11-20 13:10:32,194 - WARNING - Skipping BIOMD0000000568.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000565.txt
LLM response:
cpep (chemical): "Phosphoenolpyruvate", "PEP", "Phosphoenol pyruvic acid"
cglcex (chemical): "Glucose", "D-Glucose", "Blood sugar"
cg6p (chemical): "Glucose-6-phosphate", "G6P", "D-Glucose-6-phosphate"
cpyr (chemical): "Pyruvate", "Pyruvic acid", "2-Oxopropanoic acid"
cg1p (chemical): "Glucose-1-phosphate", "G1P", "D-Glucose-1-phosphate"
cpg (chemical): "6-Phosphogluconate", "6-PG", "D-Gluconate-6-phosphate"
cfdp (chemical): "Fructose-1,6-bisphosphate", "F1,6BP", "D-Fructose-1,6-bisphosphate"
csed7p (chemical): "Sedoheptulose-7-phosphate", "S7P", "D-Sedoheptulose-7-phosphate"
cgap (chemical): "Glyceraldehyde-3-phosphate", "G3P", "D-Glyceraldehyde-3-phosphate"
ce4p (chemical): "Erythrose-4-phosphate", "E4P", "D-Erythrose-4-phosphate"
cxyl5p (chemical): "Xylulose-5-phosphate", "X5P", "D-Xylulose-5-phosphate"
crib5p (chemical): "Ribose-5-phosphate", "R5P", "D-Ribose-5-phosphate"
cdhap (chemical): "Dihydroxyacetonephosphate", "DHAP", "D-Glyceraldehyde-3-phosphate-1,3-diphosphate"
cpg3 (chemical): "3-Phosphoglycerate", "3-PG", "D-3-Phosphoglycerate"
cpg2 (chemical): "2-Phosphoglycerate", "2-PG", "D-2-Phosphoglycerate"
cribu5p (chemical): "Ribulose-5-phosphate", "Ru5P", "D-Ribulose-5-phosphate"
accoa (chemical): "Acetyl-CoA", "AcCoA", "Acetyl coenzyme A"
malcoa (chemical): "Malonyl-CoA", "MalCoA", "Malonyl coenzyme A"
fer (chemical): "Ferulic acid", "FA", "3-(4-Hydroxy-3-methoxyphenyl)propenoic acid"
fer_ext (chemical): "Extracellular Ferulic acid", "External Ferulic acid", "Ferulic acid (extracellular)"
fercoa (chemical): "Feruloyl-CoA", "FerCoA", "Feruloyl coenzyme A"
ferdicoa (chemical): "Feruloyl-CoA derivative", "FerCoA derivative", "Dihydroferuloyl-CoA"
cur (chemical): "Curcumin", "Diferuloylmethane", "1,7-Bis(4-hydroxy-3-methoxyphenyl)-1,6-heptadiene-3,5-dione"
cur_ext (chemical): "Extracellular Curcumin", "External Curcumin", "Curcumin (extracellular)"
cpgp (chemical): "1,3-Diphosphoglycerate", "1,3-DPG", "D-Glyceraldehyde-3-phosphate-1,3-diphosphate"

Reason: The species are identified based on their display names and the context of the curcumin production pathway in Escherichia coli. The entity types are determined as chemical because they are all metabolites or compounds involved in the biochemical reactions. The standardized names and synonyms are provided based on common usage in biochemistry and literature.
Synonyms dict: {'cpep': ['Phosphoenolpyruvate', 'PEP', 'Phosphoenol pyruvic acid'], 'cglcex': ['Glucose', 'D-Glucose', 'Blood sugar'], 'cg6p': ['Glucose-6-phosphate', 'G6P', 'D-Glucose-6-phosphate'], 'cpyr': ['Pyruvate', 'Pyruvic acid', '2-Oxopropanoic acid'], 'cg1p': ['Glucose-1-phosphate', 'G1P', 'D-Glucose-1-phosphate'], 'cpg': ['6-Phosphogluconate', '6-PG', 'D-Gluconate-6-phosphate'], 'cfdp': ['Fructose-1,6-bisphosphate', 'F1,6BP', 'D-Fructose-1,6-bisphosphate'], 'csed7p': ['Sedoheptulose-7-phosphate', 'S7P', 'D-Sedoheptulose-7-phosphate'], 'cgap': ['Glyceraldehyde-3-phosphate', 'G3P', 'D-Glyceraldehyde-3-phosphate'], 'ce4p': ['Erythrose-4-phosphate', 'E4P', 'D-Erythrose-4-phosphate'], 'cxyl5p': ['Xylulose-5-phosphate', 'X5P', 'D-Xylulose-5-phosphate'], 'crib5p': ['Ribose-5-phosphate', 'R5P', 'D-Ribose-5-phosphate'], 'cdhap': ['Dihydroxyacetonephosphate', 'DHAP', 'D-Glyceraldehyde-3-phosphate-1,3-diphosphate'], 'cpg3': ['3-Phosphoglycerate', '3-PG', 'D-3-Phosphoglycerate'], 'cpg2': ['2-Phosphoglycerate', '2-PG', 'D-2-Phosphoglycerate'], 'cribu5p': ['Ribulose-5-phosphate', 'Ru5P', 'D-Ribulose-5-phosphate'], 'accoa': ['Acetyl-CoA', 'AcCoA', 'Acetyl coenzyme A'], 'malcoa': ['Malonyl-CoA', 'MalCoA', 'Malonyl coenzyme A'], 'fer': ['Ferulic acid', 'FA', '3-(4-Hydroxy-3-methoxyphenyl)propenoic acid'], 'fer_ext': ['Extracellular Ferulic acid', 'External Ferulic acid', 'Ferulic acid (extracellular)'], 'fercoa': ['Feruloyl-CoA', 'FerCoA', 'Feruloyl coenzyme A'], 'ferdicoa': ['Feruloyl-CoA derivative', 'FerCoA derivative', 'Dihydroferuloyl-CoA'], 'cur': ['Curcumin', 'Diferuloylmethane', '1,7-Bis(4-hydroxy-3-methoxyphenyl)-1,6-heptadiene-3,5-dione'], 'cur_ext': ['Extracellular Curcumin', 'External Curcumin', 'Curcumin (extracellular)'], 'cpgp': ['1,3-Diphosphoglycerate', '1,3-DPG', 'D-Glyceraldehyde-3-phosphate-1,3-diphosphate']}
Evaluating 566/1075: BIOMD0000000566.xml
Evaluating 567/1075: BIOMD0000000567.xml
Evaluating 568/1075: BIOMD0000000568.xml
Evaluating 569/1075: BIOMD0000000569.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000569.txt
LLM response:
glu (chemical): "glutamate", "L-glutamic acid", "glutamic acid"
S1 (unknown): "S1", "state 1", "AMPA receptor state 1"
S2 (unknown): "S2", "state 2", "AMPA receptor state 2"
S3 (unknown): "S3", "state 3", "AMPA receptor state 3"
S4 (unknown): "S4", "state 4", "AMPA receptor state 4"
M0 (unknown): "M0", "state 0", "AMPA receptor state 0"
M1 (unknown): "M1", "state 1", "AMPA receptor state 1"
M2 (unknown): "M2", "state 2", "AMPA receptor state 2"
M3 (unknown): "M3", "state 3", "AMPA receptor state 3"
M4 (unknown): "M4", "state 4", "AMPA receptor state 4"
L1 (unknown): "L1", "state 1", "AMPA receptor state 1"
L2 (unknown): "L2", "state 2", "AMPA receptor state 2"
L3 (unknown): "L3", "state 3", "AMPA receptor state 3"
L4 (unknown): "L4", "state 4", "AMPA receptor state 4"
B0 (unknown): "B0", "state 0", "AMPA receptor state 0"
B1 (unknown): "B1", "state 1", "AMPA receptor state 1"
B2 (unknown): "B2", "state 2", "AMPA receptor state 2"
B3 (unknown): "B3", "state 3", "AMPA receptor state 3"
B4 (unknown): "B4", "state 4", "AMPA receptor state 4"
S0 (unknown): "S0", "state 0", "AMPA receptor state 0"
L0 (unknown): "L0", "state 0", "AMPA receptor state 0"
Reason: glu is identified as a chemical because it is reacting with other species and is likely glutamate, a neurotransmitter. The other species (S, M, L, B) are marked as unknown because they appear to represent different states of the AMPA receptor, but their exact nature (e.g., protein, complex) is unclear from the provided information.
Synonyms dict: {'glu': ['glutamate', 'L-glutamic acid', 'glutamic acid'], 'S1': ['S1', 'state 1', 'AMPA receptor state 1'], 'S2': ['S2', 'state 2', 'AMPA receptor state 2'], 'S3': ['S3', 'state 3', 'AMPA receptor state 3'], 'S4': ['S4', 'state 4', 'AMPA receptor state 4'], 'M0': ['M0', 'state 0', 'AMPA receptor state 0'], 'M1': ['M1', 'state 1', 'AMPA receptor state 1'], 'M2': ['M2', 'state 2', 'AMPA receptor state 2'], 'M3': ['M3', 'state 3', 'AMPA receptor state 3'], 'M4': ['M4', 'state 4', 'AMPA receptor state 4'], 'L1': ['L1', 'state 1', 'AMPA receptor state 1'], 'L2': ['L2', 'state 2', 'AMPA receptor state 2'], 'L3': ['L3', 'state 3', 'AMPA receptor state 3'], 'L4': ['L4', 'state 4', 'AMPA receptor state 4'], 'B0': ['B0', 'state 0', 'AMPA receptor state 0'], 'B1': ['B1', 'state 1', 'AMPA receptor state 1'], 'B2': ['B2', 'state 2', 'AMPA receptor state 2'], 'B3': ['B3', 'state 3', 'AMPA receptor state 3'], 'B4': ['B4', 'state 4', 'AMPA receptor state 4'], 'S0': ['S0', 'state 0', 'AMPA receptor state 0'], 'L0': ['L0', 'state 0', 'AMPA receptor state 0']}
Evaluating 570/1075: BIOMD0000000570.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000570.txt
LLM response:
species_1 (chemical): "sodium ion", "Na+", "sodium"
species_2 (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
species_3 (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
species_4 (chemical): "glucose", "GLC", "D-glucose"
species_5 (chemical): "glyceraldehyde 3-phosphate", "GAP", "3-phosphoglyceraldehyde"
species_6 (chemical): "nicotinamide adenine dinucleotide", "NAD+", "oxidized nicotinamide adenine dinucleotide"
species_7 (chemical): "nicotinamide adenine dinucleotide reduced", "NADH", "reduced nicotinamide adenine dinucleotide"
species_8 (chemical): "pyruvate", "PYR", "pyruvic acid"
species_9 (chemical): "phosphoenolpyruvate", "PEP", "2-phosphoenolpyruvate"
species_10 (chemical): "lactate", "LAC", "lactic acid"
species_11 (chemical): "phosphocreatine", "PCr", "creatine phosphate"
species_12 (chemical): "creatine", "Cr", "creatine monohydrate"
species_13 (chemical): "oxygen", "O2", "molecular oxygen"
species_14 (chemical): "oxygen", "O2", "molecular oxygen"
species_15 (chemical): "glucose", "GLC", "D-glucose"
species_16 (chemical): "lactate", "LAC", "lactic acid"
species_17 (chemical): "glucose", "GLC", "D-glucose"
species_18 (chemical): "lactate", "LAC", "lactic acid"
species_19 (chemical): "oxygen", "O2", "molecular oxygen"
Reason: The model appears to be a metabolic model, with species representing various metabolites involved in energy production and consumption. The display names and reaction equations provide strong evidence for the identification of each species as a specific chemical. The presence of species such as ATP, ADP, NAD+, and NADH suggests that the model is focused on energy metabolism, while the presence of glucose, pyruvate, and lactate suggests that glycolysis and mitochondrial respiration are also included. The use of standardized names and common synonyms for each species provides a high degree of confidence in the annotations.
Synonyms dict: {'species_1': ['sodium ion', 'Na+', 'sodium'], 'species_2': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'species_3': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'species_4': ['glucose', 'GLC', 'D-glucose'], 'species_5': ['glyceraldehyde 3-phosphate', 'GAP', '3-phosphoglyceraldehyde'], 'species_6': ['nicotinamide adenine dinucleotide', 'NAD+', 'oxidized nicotinamide adenine dinucleotide'], 'species_7': ['nicotinamide adenine dinucleotide reduced', 'NADH', 'reduced nicotinamide adenine dinucleotide'], 'species_8': ['pyruvate', 'PYR', 'pyruvic acid'], 'species_9': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvate'], 'species_10': ['lactate', 'LAC', 'lactic acid'], 'species_11': ['phosphocreatine', 'PCr', 'creatine phosphate'], 'species_12': ['creatine', 'Cr', 'creatine monohydrate'], 'species_13': ['oxygen', 'O2', 'molecular oxygen'], 'species_14': ['oxygen', 'O2', 'molecular oxygen'], 'species_15': ['glucose', 'GLC', 'D-glucose'], 'species_16': ['lactate', 'LAC', 'lactic acid'], 'species_17': ['glucose', 'GLC', 'D-glucose'], 'species_18': ['lactate', 'LAC', 'lactic acid'], 'species_19': ['oxygen', 'O2', 'molecular oxygen']}
Evaluating 571/1075: BIOMD0000000571.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000571.txt
LLM response:
CRP_cAMP (complex): "cAMP-CRP complex", "CRP-cAMP", "cyclic AMP receptor protein complex"
CRP_cAMP_CRPsiteI_crp (complex): "CRP-cAMP-CRP site I complex", "cAMP-CRP-CRP site I", "CRP site I complex"
CRP_cAMP_CRPsiteII_crp (complex): "CRP-cAMP-CRP site II complex", "cAMP-CRP-CRP site II", "CRP site II complex"
CRP_cAMP_CRPsite_cyaA (complex): "CRP-cAMP-CyaA complex", "cAMP-CRP-CyaA", "CyaA-CRP complex"
CRP_cAMP_CRPsite_genome (complex): "CRP-cAMP-genome complex", "cAMP-CRP-DNA complex", "CRP-DNA complex"
CRP_cAMP_CRPsite_ptsGp1 (complex): "CRP-cAMP-ptsGp1 complex", "cAMP-CRP-ptsGp1", "ptsGp1-CRP complex"
CRP_cAMP_CRPsite_ptsGp2 (complex): "CRP-cAMP-ptsGp2 complex", "cAMP-CRP-ptsGp2", "ptsGp2-CRP complex"
CRP_cAMP_CRPsite_ptsHp0 (complex): "CRP-cAMP-ptsHp0 complex", "cAMP-CRP-ptsHp0", "ptsHp0-CRP complex"
CRP_cAMP_CRPsite_ptsHp1 (complex): "CRP-cAMP-ptsHp1 complex", "cAMP-CRP-ptsHp1", "ptsHp1-CRP complex"
CRP_cAMP_CRPsite_ptsIp0 (complex): "CRP-cAMP-ptsIp0 complex", "cAMP-CRP-ptsIp0", "ptsIp0-CRP complex"
CRP_cAMP_CRPsite_ptsIp1 (complex): "CRP-cAMP-ptsIp1 complex", "cAMP-CRP-ptsIp1", "ptsIp1-CRP complex"
CRP_cAMP_CRPsite_mlcp1 (complex): "CRP-cAMP-mlcP1 complex", "cAMP-CRP-mlcP1", "mlcP1-CRP complex"
CRP_cAMP_CRPsite_mlcp2 (complex): "CRP-cAMP-mlcP2 complex", "cAMP-CRP-mlcP2", "mlcP2-CRP complex"
cAMP (chemical): "cyclic adenosine monophosphate", "cAMP", "adenosine 3',5'-cyclic phosphate"
Pyr (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
PEP (chemical): "phosphoenolpyruvate", "PEP", "2-phosphoenolpyruvic acid"
Glc6P (chemical): "glucose-6-phosphate", "G6P", "D-glucose-6-phosphate"
Glucose (chemical): "D-glucose", "glucose", "blood sugar"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"

Reason: The species are annotated based on their names and the context of the model. The CRP_cAMP species and its variants are complexes of the cAMP receptor protein (CRP) with cAMP and other proteins or DNA sites. The cAMP, Pyr, PEP, Glc6P, Glucose, and ATP species are chemicals involved in the phosphotransferase system and glucose metabolism. The entity types are determined based on the functional roles of the species in the model.
Synonyms dict: {'CRP_cAMP': ['cAMP-CRP complex', 'CRP-cAMP', 'cyclic AMP receptor protein complex'], 'CRP_cAMP_CRPsiteI_crp': ['CRP-cAMP-CRP site I complex', 'cAMP-CRP-CRP site I', 'CRP site I complex'], 'CRP_cAMP_CRPsiteII_crp': ['CRP-cAMP-CRP site II complex', 'cAMP-CRP-CRP site II', 'CRP site II complex'], 'CRP_cAMP_CRPsite_cyaA': ['CRP-cAMP-CyaA complex', 'cAMP-CRP-CyaA', 'CyaA-CRP complex'], 'CRP_cAMP_CRPsite_genome': ['CRP-cAMP-genome complex', 'cAMP-CRP-DNA complex', 'CRP-DNA complex'], 'CRP_cAMP_CRPsite_ptsGp1': ['CRP-cAMP-ptsGp1 complex', 'cAMP-CRP-ptsGp1', 'ptsGp1-CRP complex'], 'CRP_cAMP_CRPsite_ptsGp2': ['CRP-cAMP-ptsGp2 complex', 'cAMP-CRP-ptsGp2', 'ptsGp2-CRP complex'], 'CRP_cAMP_CRPsite_ptsHp0': ['CRP-cAMP-ptsHp0 complex', 'cAMP-CRP-ptsHp0', 'ptsHp0-CRP complex'], 'CRP_cAMP_CRPsite_ptsHp1': ['CRP-cAMP-ptsHp1 complex', 'cAMP-CRP-ptsHp1', 'ptsHp1-CRP complex'], 'CRP_cAMP_CRPsite_ptsIp0': ['CRP-cAMP-ptsIp0 complex', 'cAMP-CRP-ptsIp0', 'ptsIp0-CRP complex'], 'CRP_cAMP_CRPsite_ptsIp1': ['CRP-cAMP-ptsIp1 complex', 'cAMP-CRP-ptsIp1', 'ptsIp1-CRP complex'], 'CRP_cAMP_CRPsite_mlcp1': ['CRP-cAMP-mlcP1 complex', 'cAMP-CRP-mlcP1', 'mlcP1-CRP complex'], 'CRP_cAMP_CRPsite_mlcp2': ['CRP-cAMP-mlcP2 complex', 'cAMP-CRP-mlcP2', 'mlcP2-CRP complex'], 'cAMP': ['cyclic adenosine monophosphate', 'cAMP', "adenosine 3',5'-cyclic phosphate"], 'Pyr': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'PEP': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvic acid'], 'Glc6P': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'Glucose': ['D-glucose', 'glucose', 'blood sugar'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"]}
Evaluating 572/1075: BIOMD0000000572.xml

2025-11-20 13:10:57,544 - WARNING - Skipping BIOMD0000000573.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000572.txt
LLM response:
G6P (chemical): "glucose-6-phosphate", "D-glucose-6-phosphate", "G6P"
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
Pint (unknown): "inorganic phosphate", "phosphate", "Pi"
F6P (chemical): "fructose-6-phosphate", "D-fructose-6-phosphate", "F6P"
FBP (chemical): "fructose-1,6-bisphosphate", "D-fructose-1,6-bisphosphate", "FBP"
G3P (chemical): "glyceraldehyde-3-phosphate", "D-glyceraldehyde-3-phosphate", "G3P"
BPG (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "BPG"
PEP (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "NAD"
NADH (chemical): "nicotinamide adenine dinucleotide reduced", "NADH", "NADH2"
PYR (chemical): "pyruvate", "pyruvic acid", "PYR"
AcetCoA (chemical): "acetyl coenzyme A", "acetyl-CoA", "AcCoA"
Acetoin (chemical): "acetoine", "3-hydroxy-2-butanone", "Acetoin"
Mannitol (chemical): "mannitol", "D-mannitol", "Mtl"
Mannitol1Phosphate (chemical): "mannitol-1-phosphate", "D-mannitol-1-phosphate", "M1P"
CoA (chemical): "coenzyme A", "CoA", "CoASH"
Pext (unknown): "external phosphate", "extracellular phosphate", "Pext"
Lactate (chemical): "lactic acid", "lactate", "L-lactate"
Ethanol (chemical): "ethanol", "ethyl alcohol", "EtOH"
Acetate (chemical): "acetate", "acetic acid", "Ac"
Glucose (chemical): "glucose", "D-glucose", "GLC"
Acetoin_Ext (chemical): "extracellular acetoine", "external acetoine", "Acetoin_Ext"
Mannitol_Ext (chemical): "extracellular mannitol", "external mannitol", "Mannitol_Ext"
Formate (chemical): "formate", "formic acid", "HCOOH"
Reason: Most species are identified as chemicals based on their roles in metabolic reactions and their display names. Pint and Pext are marked as unknown due to lack of information about their specific identities, although they are likely related to inorganic phosphate. The model context and reaction equations provide clues for determining the entity types and standardized names for each species.
Synonyms dict: {'G6P': ['glucose-6-phosphate', 'D-glucose-6-phosphate', 'G6P'], 'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'Pint': ['inorganic phosphate', 'phosphate', 'Pi'], 'F6P': ['fructose-6-phosphate', 'D-fructose-6-phosphate', 'F6P'], 'FBP': ['fructose-1,6-bisphosphate', 'D-fructose-1,6-bisphosphate', 'FBP'], 'G3P': ['glyceraldehyde-3-phosphate', 'D-glyceraldehyde-3-phosphate', 'G3P'], 'BPG': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', 'BPG'], 'PEP': ['phosphoenolpyruvate', 'PEP', 'phosphoenolpyruvic acid'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'NAD'], 'NADH': ['nicotinamide adenine dinucleotide reduced', 'NADH', 'NADH2'], 'PYR': ['pyruvate', 'pyruvic acid', 'PYR'], 'AcetCoA': ['acetyl coenzyme A', 'acetyl-CoA', 'AcCoA'], 'Acetoin': ['acetoine', '3-hydroxy-2-butanone', 'Acetoin'], 'Mannitol': ['mannitol', 'D-mannitol', 'Mtl'], 'Mannitol1Phosphate': ['mannitol-1-phosphate', 'D-mannitol-1-phosphate', 'M1P'], 'CoA': ['coenzyme A', 'CoA', 'CoASH'], 'Pext': ['external phosphate', 'extracellular phosphate', 'Pext'], 'Lactate': ['lactic acid', 'lactate', 'L-lactate'], 'Ethanol': ['ethanol', 'ethyl alcohol', 'EtOH'], 'Acetate': ['acetate', 'acetic acid', 'Ac'], 'Glucose': ['glucose', 'D-glucose', 'GLC'], 'Acetoin_Ext': ['extracellular acetoine', 'external acetoine', 'Acetoin_Ext'], 'Mannitol_Ext': ['extracellular mannitol', 'external mannitol', 'Mannitol_Ext'], 'Formate': ['formate', 'formic acid', 'HCOOH']}
Evaluating 573/1075: BIOMD0000000573.xml
Evaluating 574/1075: BIOMD0000000574.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000574.txt
LLM response:
ca (chemical): "calcium", "calcium ion", "Ca2+"
Reason: The species 'ca' is likely to be calcium, a chemical element, based on its involvement in the calmodulin model and the reaction equations provided, where it binds to various calmodulin conformations. Calcium is a crucial component in many biological processes, including muscle contraction, cell signaling, and as a cofactor for various enzymes. Its presence in the model as a reactant with calmodulin suggests its role as a calcium ion (Ca2+), which is essential for the activation and regulation of calmodulin's activity.
Synonyms dict: {'ca': ['calcium', 'calcium ion', 'Ca2+']}
Evaluating 575/1075: BIOMD0000000575.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000575.txt
LLM response:
Dopamine (chemical): "Dopamine", "3,4-Dihydroxyphenethylamine", "DA"
OH (chemical): "Hydroxide", "Hydroxyl", "OH-"
OH_radical (chemical): "Hydroxyl radical", "OH.", "Hydroxy radical"
H2O2 (chemical): "Hydrogen peroxide", "H2O2", "Peroxide"
DA_quinone (chemical): "Dopamine quinone", "DA quinone", "3,4-Dihydroxyphenethylamine quinone"
Fragments (unknown): "UNK", "Fragments", "Unknown fragments"
L_Dopa (chemical): "Levodopa", "L-Dopa", "3,4-Dihydroxyphenylalanine"
DOPAL (chemical): "3,4-Dihydroxyphenylacetaldehyde", "DOPAL", "Dopamine aldehyde"
DOPAC (chemical): "3,4-Dihydroxyphenylacetic acid", "DOPAC", "Dopamine acid"
GSH (chemical): "Glutathione", "GSH", "Gamma-glutamylcysteinylglycine"
GSSG (chemical): "Glutathione disulfide", "GSSG", "Oxidized glutathione"
Fe2 (chemical): "Ferrous ion", "Fe2+", "Iron(II)"
Fe3 (chemical): "Ferric ion", "Fe3+", "Iron(III)"
DA_S_parkin (complex): "Dopamine-parkin complex", "DA-parkin", "Parkin-DA complex"
O2 (chemical): "Oxygen", "O2", "Molecular oxygen"
DA_GSH (complex): "Dopamine-glutathione complex", "DA-GSH", "Glutathione-DA complex"
Neuromelanin (chemical): "Neuromelanin", "NM", "Melanin"
Neuromelanin_ntox_Fe3 (complex): "Neuromelanin-iron complex", "Neuromelanin-ntox-Fe3+", "Toxic neuromelanin-iron complex"
ATP (chemical): "Adenosine triphosphate", "ATP", "Energy currency"
L_Tyr (chemical): "L-Tyrosine", "L-Tyr", "Tyrosine"
CO2 (chemical): "Carbon dioxide", "CO2", "Bicarbonate"
O2_0 (chemical): "Oxygen", "O2", "Molecular oxygen"
NH3 (chemical): "Ammonia", "NH3", "Ammonium"
NAD (chemical): "Nicotinamide adenine dinucleotide", "NAD+", "NAD"
NADH (chemical): "Nicotinamide adenine dinucleotide reduced", "NADH", "NAD reduced"
H2O (chemical): "Water", "H2O", "Dihydrogen monoxide"
Cysteine (chemical): "Cysteine", "Cys", "L-Cysteine"
V_DA (unknown): "V-DA", "UNK", "Unknown V-DA"
Reason: The entity types were determined based on the names and reactions provided in the model. Chemicals are typically small molecules, while complexes are formed by the interaction of two or more molecules. Proteins and genes are not explicitly mentioned in the model, but some species like Parkin and Neuromelanin may be related to proteins. Fragments and V_DA are unknown due to lack of information about their composition or structure.
Synonyms dict: {'Dopamine': ['Dopamine', '3,4-Dihydroxyphenethylamine', 'DA'], 'OH': ['Hydroxide', 'Hydroxyl', 'OH-'], 'OH_radical': ['Hydroxyl radical', 'OH.', 'Hydroxy radical'], 'H2O2': ['Hydrogen peroxide', 'H2O2', 'Peroxide'], 'DA_quinone': ['Dopamine quinone', 'DA quinone', '3,4-Dihydroxyphenethylamine quinone'], 'Fragments': ['UNK', 'Fragments', 'Unknown fragments'], 'L_Dopa': ['Levodopa', 'L-Dopa', '3,4-Dihydroxyphenylalanine'], 'DOPAL': ['3,4-Dihydroxyphenylacetaldehyde', 'DOPAL', 'Dopamine aldehyde'], 'DOPAC': ['3,4-Dihydroxyphenylacetic acid', 'DOPAC', 'Dopamine acid'], 'GSH': ['Glutathione', 'GSH', 'Gamma-glutamylcysteinylglycine'], 'GSSG': ['Glutathione disulfide', 'GSSG', 'Oxidized glutathione'], 'Fe2': ['Ferrous ion', 'Fe2+', 'Iron(II)'], 'Fe3': ['Ferric ion', 'Fe3+', 'Iron(III)'], 'DA_S_parkin': ['Dopamine-parkin complex', 'DA-parkin', 'Parkin-DA complex'], 'O2': ['Oxygen', 'O2', 'Molecular oxygen'], 'DA_GSH': ['Dopamine-glutathione complex', 'DA-GSH', 'Glutathione-DA complex'], 'Neuromelanin': ['Neuromelanin', 'NM', 'Melanin'], 'Neuromelanin_ntox_Fe3': ['Neuromelanin-iron complex', 'Neuromelanin-ntox-Fe3+', 'Toxic neuromelanin-iron complex'], 'ATP': ['Adenosine triphosphate', 'ATP', 'Energy currency'], 'L_Tyr': ['L-Tyrosine', 'L-Tyr', 'Tyrosine'], 'CO2': ['Carbon dioxide', 'CO2', 'Bicarbonate'], 'O2_0': ['Oxygen', 'O2', 'Molecular oxygen'], 'NH3': ['Ammonia', 'NH3', 'Ammonium'], 'NAD': ['Nicotinamide adenine dinucleotide', 'NAD+', 'NAD'], 'NADH': ['Nicotinamide adenine dinucleotide reduced', 'NADH', 'NAD reduced'], 'H2O': ['Water', 'H2O', 'Dihydrogen monoxide'], 'Cysteine': ['Cysteine', 'Cys', 'L-Cysteine'], 'V_DA': ['V-DA', 'UNK', 'Unknown V-DA']}
Evaluating 576/1075: BIOMD0000000576.xml

2025-11-20 13:11:19,532 - WARNING - No valid database found for entity type 'gene' in allowed databases: ['chebi']
2025-11-20 13:11:19,532 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:11:19,648 - WARNING - Skipping BIOMD0000000577.xml - no results generated
2025-11-20 13:11:19,669 - WARNING - Skipping BIOMD0000000578.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000576.txt
LLM response:
s114 (chemical): "cortisol", "hydrocortisone", "cortisone"
s84 (gene): "NR3C1", "glucocorticoid receptor gene", "GR gene"
s165 (gene): "CYP3A4", "cytochrome P450 3A4 gene", "CYP gene"
s109 (gene): "NR1I2", "pregnane X receptor gene", "PXR gene"
s87 (protein): "glucocorticoid receptor protein", "GR protein", "NR3C1 protein"
s119 (protein): "pregnane X receptor protein", "PXR protein", "NR1I2 protein"
s183 (gene): "TAT gene", "tyrosine aminotransferase gene", "TAT"
s2 (chemical): "cortisol", "hydrocortisone", "cortisone"
Cortisone (chemical): "cortisone", "11-dehydro-17-hydrocortisone", "17-hydroxy-11-dehydrocorticosterone"
DEX (chemical): "dexamethasone", "dex", "16α-methyl-9α-fluoroprednisolone"
GRprot_DEX (protein): "glucocorticoid receptor protein dexamethasone complex", "GR-DEX complex", "NR3C1-DEX complex"
PXRprot_DEX (protein): "pregnane X receptor protein dexamethasone complex", "PXR-DEX complex", "NR1I2-DEX complex"
CYPgene_PXRprot_DEX (gene): "CYP3A4 gene", "cytochrome P450 3A4 gene", "CYP gene"
PXRgene_GRprot_DEX (gene): "NR1I2 gene", "pregnane X receptor gene", "PXR gene"
GRgene_GRprot_DEX (gene): "NR3C1 gene", "glucocorticoid receptor gene", "GR gene"
TATgene_GRprot_DEX (gene): "TAT gene", "tyrosine aminotransferase gene", "TAT"
DEXout (chemical): "dexamethasone", "dex", "16α-methyl-9α-fluoroprednisolone"
CBG_CortOUT (complex): "corticosteroid-binding globulin cortisol complex", "CBG-cortisol complex", "transcortin-cortisol complex"
Alb_CortOUT (complex): "albumin cortisol complex", "Alb-cortisol complex", "human serum albumin cortisol complex"
CortAdded (chemical): "cortisol", "hydrocortisone", "cortisone"
s39 (protein): "glucocorticoid receptor protein", "GR protein", "NR3C1 protein"
s42 (protein): "pregnane X receptor protein", "PXR protein", "NR1I2 protein"
s40 (gene): "NR3C1 gene", "glucocorticoid receptor gene", "GR gene"
s46 (gene): "NR1I2 gene", "pregnane X receptor gene", "PXR gene"
s155 (gene): "CYP3A4 gene", "cytochrome P450 3A4 gene", "CYP gene"
s178 (gene): "TAT gene", "tyrosine aminotransferase gene", "TAT"
CBG (protein): "corticosteroid-binding globulin", "CBG", "transcortin"
Alb (protein): "albumin", "Alb", "human serum albumin"

Reason: The entity types were determined based on the display names and reactions in the model. For example, s114 is a chemical because it is referred to as "Cort" and is involved in reactions with other chemicals. s87 is a protein because it is referred to as "GRprot_Cort" and is involved in reactions with other proteins and chemicals. The standardized names and synonyms were determined based on common names and abbreviations used in the field of biochemistry and molecular biology. The ranking of the synonyms is based on the likelihood of each name being used to refer to the species in the context of the model.
Synonyms dict: {'s114': ['cortisol', 'hydrocortisone', 'cortisone'], 's84': ['NR3C1', 'glucocorticoid receptor gene', 'GR gene'], 's165': ['CYP3A4', 'cytochrome P450 3A4 gene', 'CYP gene'], 's109': ['NR1I2', 'pregnane X receptor gene', 'PXR gene'], 's87': ['glucocorticoid receptor protein', 'GR protein', 'NR3C1 protein'], 's119': ['pregnane X receptor protein', 'PXR protein', 'NR1I2 protein'], 's183': ['TAT gene', 'tyrosine aminotransferase gene', 'TAT'], 's2': ['cortisol', 'hydrocortisone', 'cortisone'], 'Cortisone': ['cortisone', '11-dehydro-17-hydrocortisone', '17-hydroxy-11-dehydrocorticosterone'], 'DEX': ['dexamethasone', 'dex', '16α-methyl-9α-fluoroprednisolone'], 'GRprot_DEX': ['glucocorticoid receptor protein dexamethasone complex', 'GR-DEX complex', 'NR3C1-DEX complex'], 'PXRprot_DEX': ['pregnane X receptor protein dexamethasone complex', 'PXR-DEX complex', 'NR1I2-DEX complex'], 'CYPgene_PXRprot_DEX': ['CYP3A4 gene', 'cytochrome P450 3A4 gene', 'CYP gene'], 'PXRgene_GRprot_DEX': ['NR1I2 gene', 'pregnane X receptor gene', 'PXR gene'], 'GRgene_GRprot_DEX': ['NR3C1 gene', 'glucocorticoid receptor gene', 'GR gene'], 'TATgene_GRprot_DEX': ['TAT gene', 'tyrosine aminotransferase gene', 'TAT'], 'DEXout': ['dexamethasone', 'dex', '16α-methyl-9α-fluoroprednisolone'], 'CBG_CortOUT': ['corticosteroid-binding globulin cortisol complex', 'CBG-cortisol complex', 'transcortin-cortisol complex'], 'Alb_CortOUT': ['albumin cortisol complex', 'Alb-cortisol complex', 'human serum albumin cortisol complex'], 'CortAdded': ['cortisol', 'hydrocortisone', 'cortisone'], 's39': ['glucocorticoid receptor protein', 'GR protein', 'NR3C1 protein'], 's42': ['pregnane X receptor protein', 'PXR protein', 'NR1I2 protein'], 's40': ['NR3C1 gene', 'glucocorticoid receptor gene', 'GR gene'], 's46': ['NR1I2 gene', 'pregnane X receptor gene', 'PXR gene'], 's155': ['CYP3A4 gene', 'cytochrome P450 3A4 gene', 'CYP gene'], 's178': ['TAT gene', 'tyrosine aminotransferase gene', 'TAT'], 'CBG': ['corticosteroid-binding globulin', 'CBG', 'transcortin'], 'Alb': ['albumin', 'Alb', 'human serum albumin']}
Evaluating 577/1075: BIOMD0000000577.xml
Evaluating 578/1075: BIOMD0000000578.xml
Evaluating 579/1075: BIOMD0000000579.xml

2025-11-20 13:13:14,548 - WARNING - Skipping BIOMD0000000580.xml - no results generated
2025-11-20 13:13:14,563 - WARNING - Skipping BIOMD0000000581.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000579.txt
LLM response:
s99 (chemical): "C14 L-3-hydroxyacyl-CoA", "3-hydroxytetradecanoyl-CoA", "3-hydroxy-myristoyl-CoA"
s98 (chemical): "C14 2-trans-enoyl-CoA", "2-tetradecenoyl-CoA", "tetradec-2-enoyl-CoA"
s101 (chemical): "C12Acyl-CoA", "dodecanoyl-CoA", "lauroyl-CoA"
s104 (chemical): "C12 L-3-hydroxyacyl-CoA", "3-hydroxydodecanoyl-CoA", "3-hydroxylauroyl-CoA"
s105 (chemical): "C12 2-trans-enoyl-CoA", "2-dodecenoyl-CoA", "dodec-2-enoyl-CoA"
s102 (chemical): "C10Acyl-CoA", "decanoyl-CoA", "caprinoyl-CoA"
s107 (chemical): "C10 L-3-hydroxyacyl-CoA", "3-hydroxydecanoyl-CoA", "3-hydroxycaprinoyl-CoA"
s106 (chemical): "C10 2-trans-enoyl-CoA", "2-decenoyl-CoA", "dec-2-enoyl-CoA"
s23 (chemical): "Aspartate", "aspartic acid", "L-aspartic acid"
s39 (chemical): "Arginosuccinate", "argininosuccinic acid", "N-(L-arginino)succinic acid"
s343 (chemical): "Arginine", "L-arginine", "2-amino-5-guanidinopentanoic acid"
s5 (chemical): "Alpha-KG", "α-ketoglutarate", "2-oxoglutarate"
s17 (chemical): "Alpha keto acid", "2-oxo acid", "ketone body"
s21 (chemical): "Alpha KG", "α-ketoglutarate", "2-oxoglutarate"
s14 (chemical): "Alanine", "L-alanine", "2-aminopropanoic acid"
s326 (chemical): "AcetylCoA", "acetyl coenzyme A", "CoA-S-acetyl"
s324 (chemical): "Acetone", "propan-2-one", "2-propanone"
s321 (chemical): "AcetoacetylCoA", "acetoacetyl coenzyme A", "CoA-S-acetoacetyl"
s323 (chemical): "Acetoacetate", "acetoacetic acid", "3-oxobutanedioic acid"
s63 (chemical): "ATP", "adenosine triphosphate", "9-β-D-ribofuranosyl-9H-purin-6-amine"
s47 (chemical): "AMP", "adenosine monophosphate", "9-β-D-ribofuranosyl-9H-purin-6-amine"
s46 (chemical): "ADP", "adenosine diphosphate", "5'-adenylic acid"
s345 (chemical): "ATP", "adenosine triphosphate", "9-β-D-ribofuranosyl-9H-purin-6-amine"
s348 (chemical): "A CoA", "coenzyme A", "CoA-SH"
s182 (chemical): "6PGluconate", "6-phosphogluconate", "6-phosphogluconic acid"
s300 (chemical): "2NADH", "nicotinamide adenine dinucleotide", "NADH"
s301 (chemical): "2NAD+", "nicotinamide adenine dinucleotide", "NAD+"
s358 (chemical): "2H+", "hydrogen ion", "proton"
s389 (chemical): "2H+", "hydrogen ion", "proton"
s29 (chemical): "2ATP", "adenosine triphosphate", "9-β-D-ribofuranosyl-9H-purin-6-amine"
s256 (chemical): "1/2O2", "oxygen", "dioxygen"
s39 (chemical): "Arginosuccinate", "argininosuccinic acid", "N-(L-arginino)succinic acid"
s342 (chemical): "Citrulline", "L-citrulline", "2-amino-5-ureidopentanoic acid"
s34 (chemical): "Ornithine", "L-ornithine", "2,5-diaminopentanoic acid"
s71 (chemical): "Glucose", "D-glucose", "dextrose"
s80 (chemical): "C18 Ketoacyl-CoA", "stearoyl-CoA", "octadecanoyl-CoA"
s103 (chemical): "C12 Ketoacyl-CoA", "lauroyl-CoA", "dodecanoyl-CoA"
s108 (chemical): "C10 Ketoacyl-CoA", "decanoyl-CoA", "caprinoyl-CoA"
s119 (chemical): "C4 Ketoacyl-CoA", "butyryl-CoA", "butanoyl-CoA"
s286 (chemical): "Fructose", "D-fructose", "levulose"
s335 (chemical): "UDP-Glucose", "uridine diphosphate glucose", "UDP-D-glucose"
s50 (chemical): "OAA", "oxaloacetate", "2-oxobutanedioic acid"
s66 (chemical): "C20 Ketoacyl-CoA", "arachidoyl-CoA", "eicosanoyl-CoA"
s116 (chemical): "C6 Ketoacyl-CoA", "hexanoyl-CoA", "caprooyl-CoA"
s7 (chemical): "Succinate", "succinic acid", "butanedioic acid"
s356 (chemical): "FAD", "flavin adenine dinucleotide", "riboflavin-5'-phosphate"
s269 (chemical): "FMN", "flavin mononucleotide", "riboflavin-5'-phosphate"
s183 (chemical): "D-Ribulose5P", "ribulose-5-phosphate", "5-phosphoribulose"
s95 (chemical): "LIPOATE", "lipoic acid", "thioctic acid"
s11 (chemical): "Pyruvate", "pyruvic acid", "2-oxopropanoic acid"
s40 (chemical): "Fumarate", "fumaric acid", "2-butenedioic acid"
s25 (chemical): "HCO3-+ NH4+", "bicarbonate", "ammonium ion"
s52 (chemical): "Isocitrate", "isocitric acid", "1,2,3-propanetricarboxylic acid"
s8 (chemical): "3-PGA", "3-phosphoglycerate", "3-phosphoglyceric acid"
s10 (chemical): "PEP", "phosphoenolpyruvate", "2-phosphoenolpyruvic acid"
s35 (chemical): "GA3P", "glyceraldehyde-3-phosphate", "3-phosphoglyceraldehyde"
s111 (chemical): "C8 Ketoacyl-CoA", "octanoyl-CoA", "capryloyl-CoA"
s2 (chemical): "Citrate", "citric acid", "2-hydroxy-1,2,3-propanetricarboxylic acid"
s3 (chemical): "F6P", "fructose-6-phosphate", "6-phosphofructose"
s64 (chemical): "H2O", "water", "dihydrogen monoxide"
s302 (chemical): "Galactose1P", "galactose-1-phosphate", "α-D-galactose-1-phosphate"
s37 (chemical): "C22 Ketoacyl-CoA", "behenoyl-CoA", "docosanoyl-CoA"
s237 (chemical): "CO2", "carbon dioxide", "carbonic anhydride"
s12 (chemical): "Amino acids", "proteinogenic amino acids", "α-amino acids"
s73 (chemical): "F1,6P", "fructose-1,6-bisphosphate", "6-phosphofructose-1-phosphate"
s361 (chemical): "H+", "hydrogen ion", "proton"
s334 (chemical): "NADP+", "nicotinamide adenine dinucleotide phosphate", "NADP+"
s379 (chemical): "Glutamate", "L-glutamate", "2-aminopentanedioic acid"
s119 (chemical): "C4 Ketoacyl-CoA", "butyryl-CoA", "butanoyl-CoA"
s335 (chemical): "UDP-Glucose", "uridine diphosphate glucose", "UDP-D-glucose"
s49 (chemical): "UREA", "urea", "carbamide"
s355 (chemical): "NAD+", "nicotinamide adenine dinucleotide", "NAD+"
s253 (chemical): "Unbranched alpha(1,4)polymer", "starch", "amylose"
s286 (chemical): "Fructose", "D-fructose", "levulose"
s293 (chemical): "Glyceraldehyde", "glyceraldehyde", "2,3-dihydroxypropanal"
s306 (chemical): "Galactose", "D-galactose", "galactopyranose"
s124 (chemical): "Creatine phosphate", "phosphocreatine", "N-(phosphono)creatine"
s123 (chemical): "Creatine", "creatine", "N-(aminoiminomethyl)-N-methylglycine"
s181 (chemical): "6PGDL", "6-phosphogluconolactone", "6-phosphoglucono-1,5-lactone"
s352 (chemical): "GDP", "guanosine diphosphate", "5'-guanylic acid"
s195 (chemical): "G1P", "glucose-1-phosphate", "α-D-glucose-1-phosphate"
s33 (chemical): "Carbamoyl phosphate", "carbamoyl phosphate", "ureidosuccinic acid"
s267 (chemical): "Q", "ubiquinone", "coenzyme Q"
s388 (chemical): "QH2", "ubiquinol", "reduced coenzyme Q"
s100 (chemical): "C14 Ketoacyl-CoA", "myristoyl-CoA", "tetradecanoyl-CoA"
s84 (chemical): "C14Acyl-CoA", "myristoyl-CoA", "tetradecanoyl-CoA"
s89 (chemical): "C16 Ketoacyl-CoA", "palmitoyl-CoA", "hexadecanoyl-CoA"
s322 (chemical): "HMGCoA", "3-hydroxy-3-methylglutaryl-CoA", "HMG-CoA"
s116 (chemical): "C6 Ketoacyl-CoA", "hexanoyl-CoA", "caprooyl-CoA"
s80 (chemical): "C18 Ketoacyl-CoA", "stearoyl-CoA", "octadecanoyl-CoA"
s66 (chemical): "C20 Ketoacyl-CoA", "arachidoyl-CoA", "eicosanoyl-CoA"
s111 (chemical): "C8 Ketoacyl-CoA", "octanoyl-CoA", "capryloyl-CoA"
s108 (chemical): "C10 Ketoacyl-CoA", "decanoyl-CoA", "caprinoyl-CoA"
s37 (chemical): "C22 Ketoacyl-CoA", "behenoyl-CoA", "docosanoyl-CoA"
s119 (chemical): "C4 Ketoacyl-CoA", "butyryl-CoA", "butanoyl-CoA"
s103 (chemical): "C12 Ketoacyl-CoA", "lauroyl-CoA", "dodecanoyl-CoA"
s92 (chemical): "Co-Ash", "coenzyme A", "CoA-SH"
s195 (chemical): "G1P", "glucose-1-phosphate", "α-D-glucose-1-phosphate"
s33 (chemical): "Carbamoyl phosphate", "carbamoyl phosphate", "ureidosuccinic acid"
s25 (chemical): "HCO3-+ NH4+", "bicarbonate", "ammonium ion"
s10 (chemical): "PEP", "phosphoenolpyruvate", "2-phosphoenolpyruvic acid"
s11 (chemical): "Pyruvate", "pyruvic acid", "2-oxopropanoic acid"
s94 (chemical): "TPP", "thiamine pyrophosphate", "cocarboxylase"
s81 (chemical): "OXALOACETATE", "oxaloacetate", "2-oxobutanedioic acid"
s190 (chemical): "NAPDH", "nicotinamide adenine dinucleotide phosphate", "NADPH"
s351 (chemical): "NADH", "nicotinamide adenine dinucleotide", "NADH"
s190 (chemical): "NAPDH", "nicotinamide adenine dinucleotide phosphate", "NADPH"
s108 (chemical): "C10 Ketoacyl-CoA", "decanoyl-CoA", "caprinoyl-CoA"
s119 (chemical): "C4 Ketoacyl-CoA", "butyryl-CoA", "butanoyl-CoA"
s71 (chemical): "Glucose", "D-glucose", "dextrose"
s234 (chemical): "G6P", "glucose-6-phosphate", "6-phosphogluucose"
s285 (chemical): "F1P", "fructose-1-phosphate", "1-phosphofructose"
s286 (chemical): "Fructose", "D-fructose", "levulose"
s306 (chemical): "Galactose", "D-galactose", "galactopyranose"
s302 (chemical): "Galactose1P", "galactose-1-phosphate", "α-D-galactose-1-phosphate"
s74 (chemical): "1,3-BiPGA", "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid"
s8 (chemical): "3-PGA", "3-phosphoglycerate", "3-phosphoglyceric acid"
s35 (chemical): "GA3P", "glyceraldehyde-3-phosphate", "3-phosphoglyceraldehyde"
s111 (chemical): "C8 Ketoacyl-CoA", "octanoyl-CoA", "capryloyl-CoA"
s37 (chemical): "C22 Ketoacyl-CoA", "behenoyl-CoA", "docosanoyl-CoA"
s237 (chemical): "CO2", "carbon dioxide", "carbonic anhydride"
s12 (chemical): "Amino acids", "proteinogenic amino acids", "α-amino acids"
s73 (chemical): "F1,6P", "fructose-1,6-bisphosphate", "6-phosphofructose-1-phosphate"
s361 (chemical): "H+", "hydrogen ion", "proton"
s334 (chemical): "NADP+", "nicotinamide adenine dinucleotide phosphate", "NADP+"
s379 (chemical): "Glutamate", "L-glutamate", "2-aminopentanedioic acid"
s49 (chemical): "UREA", "urea", "carbamide"
s355 (chemical): "NAD+", "nicotinamide adenine dinucleotide", "NAD+"
s253 (chemical): "Unbranched alpha(1,4)polymer", "starch", "amylose"
s293 (chemical): "Glyceraldehyde", "glyceraldehyde", "2,3-dihydroxypropanal"
s124 (chemical): "Creatine phosphate", "phosphocreatine", "N-(phosphono)creatine"
s123 (chemical): "Creatine", "creatine", "N-(aminoiminomethyl)-N-methylglycine"
s181 (chemical): "6PGDL", "6-phosphogluconolactone", "6-phosphoglucono-1,5-lactone"
s352 (chemical): "GDP", "guanosine diphosphate", "5'-guanylic acid"
s195 (chemical): "G1P", "glucose-1-phosphate", "α-D-glucose-1-phosphate"
s33 (chemical): "Carbamoyl phosphate", "carbamoyl phosphate", "ureidosuccinic acid"
s267 (chemical): "Q", "ubiquinone", "coenzyme Q"
s388 (chemical): "QH2", "ubiquinol", "reduced coenzyme Q"
s100 (chemical): "C14 Ketoacyl-CoA", "myristoyl-CoA", "tetradecanoyl-CoA"
s84 (chemical): "C14Acyl-CoA", "myristoyl-CoA", "tetradecanoyl-CoA"
s89 (chemical): "C16 Ketoacyl-CoA", "palmitoyl-CoA", "hexadecanoyl-CoA"
s322 (chemical): "HMGCoA", "3-hydroxy-3-methylglutaryl-CoA", "HMG-CoA"
s116 (chemical): "C6 Ketoacyl-CoA", "hexanoyl-CoA", "caprooyl-CoA"
s80 (chemical): "C18 Ketoacyl-CoA", "stearoyl-CoA", "octadecanoyl-CoA"
s66 (chemical): "C20 Ketoacyl-CoA", "arachidoyl-CoA", "eicosanoyl-CoA"
s111 (chemical): "C8 Ketoacyl-CoA", "oct

2025-11-20 13:13:15,827 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:13:15,828 - WARNING - Skipping BIOMD0000000582.xml - no results generated
2025-11-20 13:13:15,851 - WARNING - Skipping BIOMD0000000583.xml - no results generated
2025-11-20 13:13:15,863 - WARNING - Skipping BIOMD0000000584.xml - no results generated
2025-11-20 13:13:15,871 - WARNING - Skipping BIOMD0000000585.xml - no results generated
2025-11-20 13:13:15,884 - WARNING - Skipping BIOMD0000000586.xml - no results generated
2025-11-20 13:13:15,894 - WARNING - Skipping BIOMD0000000587.xml - no results generated
2025-11-20 13:13:15,933 - WARNING - Skipping BIOMD0000000588.xml - no results generated

Evaluating 583/1075: BIOMD0000000583.xml
Evaluating 584/1075: BIOMD0000000584.xml
Evaluating 585/1075: BIOMD0000000585.xml
Evaluating 586/1075: BIOMD0000000586.xml
Evaluating 587/1075: BIOMD0000000587.xml
Evaluating 588/1075: BIOMD0000000588.xml
Evaluating 589/1075: BIOMD0000000589.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000589.txt
LLM response:
NADPH (chemical): "Nicotinamide adenine dinucleotide phosphate", "NADP", "Triphosphopyridine nucleotide"
NADPplus (chemical): "Nicotinamide adenine dinucleotide phosphate oxidized form", "NADP+", "Oxidized nicotinamide adenine dinucleotide phosphate"
GSSG (chemical): "Glutathione disulfide", "Oxidized glutathione", "GSSG"
DHA (chemical): "Dehydroascorbic acid", "Dehydroascorbate", "DHA"
MDA (chemical): "Monodehydroascorbate", "Monodehydroascorbic acid", "MDA"
O2neg (chemical): "Superoxide", "Superoxide anion", "O2-"

Reason: The species can be identified based on their display names and the context of the Ascorbate-Glutathione cycle model. NADPH and NADPplus are electron carriers, GSSG is the oxidized form of glutathione, DHA is the oxidized form of ascorbate, MDA is a radical form of ascorbate, and O2neg is a reactive oxygen species. All of these species are chemicals involved in the metabolic pathway.
Synonyms dict: {'NADPH': ['Nicotinamide adenine dinucleotide phosphate', 'NADP', 'Triphosphopyridine nucleotide'], 'NADPplus': ['Nicotinamide adenine dinucleotide phosphate oxidized form', 'NADP+', 'Oxidized nicotinamide adenine dinucleotide phosphate'], 'GSSG': ['Glutathione disulfide', 'Oxidized glutathione', 'GSSG'], 'DHA': ['Dehydroascorbic acid', 'Dehydroascorbate', 'DHA'], 'MDA': ['Monodehydroascorbate', 'Monodehydroascorbic acid', 'MDA'], 'O2neg': ['Superoxide', 'Superoxide anion', 'O2-']}
Evaluating 590/1075: BIOMD0000000590.xml

2025-11-20 13:13:22,790 - WARNING - Skipping BIOMD0000000591.xml - no results generated
2025-11-20 13:13:22,794 - WARNING - Skipping BIOMD0000000592.xml - no results generated
2025-11-20 13:13:22,800 - WARNING - Skipping BIOMD0000000593.xml - no results generated
2025-11-20 13:13:22,833 - WARNING - Skipping BIOMD0000000594.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000590.txt
LLM response:
cp (chemical): "carbamoyl phosphate", "carbamoyl phosphate group", "phosphocarbamate"
ca (chemical): "carbamoyl aspartate", "N-carbamoyl-L-aspartate", "carbamoyl-L-aspartic acid"
dho (chemical): "dihydroorotate", "L-dihydroorotate", "6-hydroorotate"
oro (chemical): "orotate", "6-hydroxyuracil", "orotic acid"
omp (chemical): "orotidine 5'-monophosphate", "orotidine monophosphate", "OMP"
ump (chemical): "uridine 5'-monophosphate", "uridine monophosphate", "UMP"
udp (chemical): "uridine 5'-diphosphate", "uridine diphosphate", "UDP"
utp (chemical): "uridine 5'-triphosphate", "uridine triphosphate", "UTP"
ctp (chemical): "cytidine 5'-triphosphate", "cytidine triphosphate", "CTP"
Reason: All species are identified as chemicals because they are intermediates in the de novo biosynthesis of pyrimidines in yeast, a metabolic pathway. The names are standardized based on common biochemical nomenclature, and the synonyms are provided in order of likelihood based on their usage in the field. The model context and reaction equations support the identification of these species as chemicals involved in pyrimidine biosynthesis.
Synonyms dict: {'cp': ['carbamoyl phosphate', 'carbamoyl phosphate group', 'phosphocarbamate'], 'ca': ['carbamoyl aspartate', 'N-carbamoyl-L-aspartate', 'carbamoyl-L-aspartic acid'], 'dho': ['dihydroorotate', 'L-dihydroorotate', '6-hydroorotate'], 'oro': ['orotate', '6-hydroxyuracil', 'orotic acid'], 'omp': ["orotidine 5'-monophosphate", 'orotidine monophosphate', 'OMP'], 'ump': ["uridine 5'-monophosphate", 'uridine monophosphate', 'UMP'], 'udp': ["uridine 5'-diphosphate", 'uridine diphosphate', 'UDP'], 'utp': ["uridine 5'-triphosphate", 'uridine triphosphate', 'UTP'], 'ctp': ["cytidine 5'-triphosphate", 'cytidine triphosphate', 'CTP']}
Evaluating 591/1075: BIOMD0000000591.xml
Evaluating 592/1075: BIOMD0000000592.xml
Evaluating 593/1075: BIOMD0000000593.xml
Evaluating 594/1075: BIOMD0000000594.xml
Evaluating 595/1075: BIOMD0000000595.xml

2025-11-20 13:13:23,173 - WARNING - Skipping BIOMD0000000595.xml - no results generated
2025-11-20 13:13:23,296 - WARNING - Skipping BIOMD0000000596.xml - no results generated
2025-11-20 13:13:23,319 - WARNING - Skipping BIOMD0000000597.xml - no results generated
2025-11-20 13:13:23,340 - WARNING - Skipping BIOMD0000000598.xml - no results generated
2025-11-20 13:13:23,365 - WARNING - Skipping BIOMD0000000599.xml - no results generated
2025-11-20 13:13:23,394 - WARNING - Skipping BIOMD0000000600.xml - no results generated

Evaluating 596/1075: BIOMD0000000596.xml
Evaluating 597/1075: BIOMD0000000597.xml
Evaluating 598/1075: BIOMD0000000598.xml
Evaluating 599/1075: BIOMD0000000599.xml
Evaluating 600/1075: BIOMD0000000600.xml
Evaluating 601/1075: BIOMD0000000601.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000601.txt
LLM response:
mwd805cc43_4a96_472f_a894_c119a6aa895f (chemical): "calcium ion", "Ca2+", "sarcoplasmic reticulum calcium"
mw447078ee_8bc8_4358_abcd_ade10dba93b0 (chemical): "calcium ion", "Ca2+", "free sarcoplasmic reticulum calcium"
mw40a96ef6_32da_46d1_9712_4f53f60bad43 (chemical): "calcium ion", "Ca2+", "total cytosolic calcium"
mwe1a0a651_d2d5_4f75_8d45_9336c60eb9a6 (chemical): "calcium ion", "Ca2+", "free cytosolic calcium"
mw168e0d8a_b9f7_4d4c_b437_a81206c5d381 (chemical): "caffeine", "1,3,7-trimethylxanthine", "trimethylxanthine"

Reason: The species are all related to calcium ions or caffeine in the context of the sarcoplasmic reticulum and cytosol, as indicated by the model notes and display names. The entity types are determined based on the chemical nature of the species, with calcium ions being a chemical entity and caffeine being a chemical stimulant. The standardized names and synonyms are chosen based on common usage in biochemistry and physiology.
Synonyms dict: {'mwd805cc43_4a96_472f_a894_c119a6aa895f': ['calcium ion', 'Ca2+', 'sarcoplasmic reticulum calcium'], 'mw447078ee_8bc8_4358_abcd_ade10dba93b0': ['calcium ion', 'Ca2+', 'free sarcoplasmic reticulum calcium'], 'mw40a96ef6_32da_46d1_9712_4f53f60bad43': ['calcium ion', 'Ca2+', 'total cytosolic calcium'], 'mwe1a0a651_d2d5_4f75_8d45_9336c60eb9a6': ['calcium ion', 'Ca2+', 'free cytosolic calcium'], 'mw168e0d8a_b9f7_4d4c_b437_a81206c5d381': ['caffeine', '1,3,7-trimethylxanthine', 'trimethylxanthine']}
Evaluating 602/1075: BIOMD0000000602.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000602.txt
LLM response:
M_Xanthurenate (chemical): "Xanthurenic acid", "Xanthurenate", "4,8-Dihydroxyquinoline-2-carboxylic acid"
M_f5hoxkyn_c (chemical): "5-Hydroxykynurenine", "5-Hydroxy-L-kynurenine", "4,5-Dihydroxy-L-kynurenine"
M_nndmtrpta_c (chemical): "N'-Methyltryptamine", "N-Methyltryptamine", "3-(2-Aminoethyl)-N-methylindole"
M_nmsrtn_c (chemical): "N-Methylserotonin", "N-Methyl-5-hydroxytryptamine", "5-Hydroxy-N-methyltryptamine"
M_Nactrypta_c (chemical): "N-Acetyltryptamine", "N-Acetyl-2-(2-aminoethyl)indole", "2-(2-Aminoethyl)-N-acetylindole"
M_Lkynr_ex (chemical): "L-Kynurenine", "Kynurenine", "2-Amino-4-(2-aminophenyl)-4-oxobutanoic acid"
Reason: The species are all metabolites or intermediates in the tryptophan metabolism pathway, which is a biochemical pathway involving the breakdown of the amino acid tryptophan. The names and synonyms provided are based on common names and synonyms used in biochemistry and metabolism. M_Xanthurenate is a known metabolite in the kynurenine pathway, M_f5hoxkyn_c is a hydroxylated derivative of kynurenine, M_nndmtrpta_c and M_nmsrtn_c are methylated derivatives of tryptamine and serotonin, respectively, M_Nactrypta_c is an acetylated derivative of tryptamine, and M_Lkynr_ex is the external pool of L-kynurenine.
Synonyms dict: {'M_3hanthrn_c': ['3-Hydroxyanthranilic acid', '3-HAA', '3-Hydroxyanthranilate'], 'M_5hoxnfkyn_c': ['5-Hydroxykynurenine', '5-HKyn', '5-Hydroxy-L-kynurenine'], 'M_5htrp_c': ['5-Hydroxytryptophan', '5-HTP', '5-Hydroxy-L-tryptophan'], 'M_5hxkyn_c': ['5-Hydroxykynurenine', '5-HKyn', '5-Hydroxy-L-kynurenine'], 'M_Lfmkynr_c': ['N-Formylkynurenine', 'NFK', 'N-Formyl-L-kynurenine'], 'M_Lkynr_c': ['Kynurenine', 'L-Kynurenine', 'Kyn'], 'M_ahcys_c': ['S-Adenosylhomocysteine', 'SAH', 'S-Adenosylhomocysteine'], 'M_akg_c': ['Alpha-ketoglutarate', 'AKG', '2-Oxoglutarate'], 'M_ala_DASH_L_c': ['L-Alanine', 'Alanine', 'L-Ala'], 'M_amet_c': ['S-Adenosylmethionine', 'SAM', 'S-Adenosylmethionine'], 'M_anth_c': ['Anthranilic acid', 'AA', '2-Aminobenzoic acid'], 'M_cmusa_c': ['3-Hydroxyanthranilic acid', '3-HAA', '3-Hydroxyanthranilate'], 'M_dhbpt_c': ['Dihydrobiopterin', 'BH2', '7,8-Dihydrobiopterin'], 'M_for_c': ['Formate', 'HCOOH', 'Formic acid'], 'M_glu_DASH_L_c': ['L-Glutamate', 'Glutamate', 'L-Glu'], 'M_hLkynr_c': ['3-Hydroxykynurenine', '3-HKyn', '3-Hydroxy-L-kynurenine'], 'M_id3acald_c': ['Indole-3-acetaldehyde', 'IAAld', 'Indole-3-acetaldehyde'], 'M_indpyr_c': ['Indolepyruvic acid', 'IPA', 'Indole-3-pyruvic acid'], 'M_nmtrpta_c': ['N-Methyltryptophan', 'NMT', 'N-Methyl-L-tryptophan'], 'M_quln_c': ['Quinolinic acid', 'QA', 'Quinolinate'], 'M_srtn_c': ['Serotonin', '5-HT', '5-Hydroxytryptamine'], 'M_thbpt': ['Tetrahydrobiopterin', 'BH4', '5,6,7,8-Tetrahydrobiopterin'], 'M_trna_trp_c': ['tRNA-Tryptophan', 'tRNA-Trp', 'Tryptophan tRNA'], 'M_trp_DASH_L_c': ['L-Tryptophan', 'Tryptophan', 'L-Trp'], 'M_trp_L_trna_c': ['Tryptophan-tRNA', 'Trp-tRNA', 'Aminoacyl-tRNA'], 'M_trypta_c': ['Tryptamine', 'TAM', 'Tryptamine'], 'M_amp_c': ['Adenosine monophosphate', 'AMP', 'Adenylate'], 'M_atp_c': ['Adenosine triphosphate', 'ATP', "Adenosine 5'-triphosphate"], 'M_co2_c': ['Carbon dioxide', 'CO2', 'Carbonic acid'], 'M_h2o2_c': ['Hydrogen peroxide', 'H2O2', 'Hydrogen peroxide'], 'M_h2o_c': ['Water', 'H2O', 'Water'], 'M_h_c': ['Hydrogen ion', 'H+', 'Proton'], 'M_nadp_c': ['Nicotinamide adenine dinucleotide phosphate', 'NADP+', 'Nicotinamide adenine dinucleotide phosphate'], 'M_nadph_c': ['Nicotinamide adenine dinucleotide phosphate (reduced)', 'NADPH', 'Nicotinamide adenine dinucleotide phosphate (reduced)'], 'M_nh4_c': ['Ammonium ion', 'NH4+', 'Ammonium'], 'M_o2_c': ['Oxygen', 'O2', 'Oxygen'], 'M_o2s_c': ['Superoxide', 'O2-', 'Superoxide anion'], 'M_ppi_c': ['Pyrophosphate', 'PPi', 'Diphosphate'], 'M_Cinnavalininate_c': ['Cinnavalininate', 'Cinnavalinic acid', 'Cinnavaline'], 'M_kynate_c': ['Kynurenic acid', 'KYNA', '4-Hydroxyquinoline-2-carboxylic acid'], 'M_nicrnt_c': ['Nicotinamide riboside', 'NR', 'Nicotinamide riboside'], 'M_prpp_c': ['5-Phosphoribosyl-1-pyrophosphate', 'PRPP', '5-Phosphoribosyl-1-pyrophosphate'], 'M_nformanth_c': ['N-Formylanthranilic acid', 'NFAA', 'N-Formylanthranilate'], 'M_dnad_c': ['Deamino-NAD', 'Deamino-NAD+', 'Deamino-nicotinamide adenine dinucleotide'], 'M_am6sa_c': ['6-Hydroxynicotinamide', '6-HN', '6-Hydroxynicotinamide'], 'M_5hoxindact_c': ['5-Hydroxyindoleacetic acid', '5-HIAA', '5-Hydroxyindole-3-acetic acid'], 'M_Nacsertn_c': ['N-Acetylserotonin', 'NAS', 'N-Acetyl-5-hydroxytryptamine'], 'M_accoa_c': ['Acetyl-CoA', 'AcCoA', 'Acetyl coenzyme A'], 'M_coa_c': ['Coenzyme A', 'CoA', 'Coenzyme A'], 'TRP_ex': ['UNK', 'Unknown', 'External tryptophan'], 'M_Xanthurenate': ['Xanthurenic acid', 'Xanthurenate', '4,8-Dihydroxyquinoline-2-carboxylic acid'], 'M_f5hoxkyn_c': ['5-Hydroxykynurenine', '5-Hydroxy-L-kynurenine', '4,5-Dihydroxy-L-kynurenine'], 'M_nndmtrpta_c': ["N'-Methyltryptamine", 'N-Methyltryptamine', '3-(2-Aminoethyl)-N-methylindole'], 'M_nmsrtn_c': ['N-Methylserotonin', 'N-Methyl-5-hydroxytryptamine', '5-Hydroxy-N-methyltryptamine'], 'M_Nactrypta_c': ['N-Acetyltryptamine', 'N-Acetyl-2-(2-aminoethyl)indole', '2-(2-Aminoethyl)-N-acetylindole'], 'M_Lkynr_ex': ['L-Kynurenine', 'Kynurenine', '2-Amino-4-(2-aminophenyl)-4-oxobutanoic acid']}
Evaluating 603/1075: BIOMD0000000603.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000603.txt
LLM response:
glycerol_i (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_i (chemical): "glucose", "d-glucose", "blood sugar"
G6P (chemical): "glucose-6-phosphate", "d-glucose-6-phosphate", "G6P"
trehalose (chemical): "trehalose", "mycose", "trehalose sugar"
F16DP (chemical): "fructose-1,6-bisphosphate", "d-fructose-1,6-bisphosphate", "F1,6BP"
pyruvate (chemical): "pyruvic acid", "pyruvate", "2-oxopropanoic acid"
acetate_i (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_i (chemical): "ethanol", "ethyl alcohol", "alcohol"
glycerol_e (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_e (chemical): "glucose", "d-glucose", "blood sugar"
acetate_e (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_e (chemical): "ethanol", "ethyl alcohol", "alcohol"
trehalose_e (chemical): "trehalose", "mycose", "trehalose sugar"
Reason: All species have display names that match common biochemical compounds, and their involvement in reactions such as glycolysis and fermentation pathways confirms their identity as chemicals. The "_i" and "_e" suffixes likely indicate intracellular and extracellular compartments, respectively, but do not affect the entity type.
Synonyms dict: {'glycerol_i': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_i': ['glucose', 'd-glucose', 'blood sugar'], 'G6P': ['glucose-6-phosphate', 'd-glucose-6-phosphate', 'G6P'], 'trehalose': ['trehalose', 'mycose', 'trehalose sugar'], 'F16DP': ['fructose-1,6-bisphosphate', 'd-fructose-1,6-bisphosphate', 'F1,6BP'], 'pyruvate': ['pyruvic acid', 'pyruvate', '2-oxopropanoic acid'], 'acetate_i': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_i': ['ethanol', 'ethyl alcohol', 'alcohol'], 'glycerol_e': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_e': ['glucose', 'd-glucose', 'blood sugar'], 'acetate_e': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_e': ['ethanol', 'ethyl alcohol', 'alcohol'], 'trehalose_e': ['trehalose', 'mycose', 'trehalose sugar']}
Evaluating 604/1075: BIOMD0000000604.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000604.txt
LLM response:
glycerol_i (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_i (chemical): "glucose", "d-glucose", "blood sugar"
G6P (chemical): "glucose-6-phosphate", "d-glucose-6-phosphate", "G6P"
trehalose (chemical): "trehalose", "mycose", "trehalose dihydrate"
F16DP (chemical): "fructose-1,6-bisphosphate", "fructose-1,6-diphosphate", "F1,6BP"
pyruvate (chemical): "pyruvic acid", "pyruvate", "2-oxopropanoic acid"
acetate_i (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_i (chemical): "ethanol", "ethyl alcohol", "alcohol"
glycerol_e (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_e (chemical): "glucose", "d-glucose", "blood sugar"
acetate_e (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_e (chemical): "ethanol", "ethyl alcohol", "alcohol"
trehalose_e (chemical): "trehalose", "mycose", "trehalose dihydrate"
Reason: All species are identified as chemicals because they are involved in metabolic reactions and are known metabolites. The "_i" and "_e" suffixes likely indicate intracellular and extracellular compartments, respectively, but do not affect the entity type. The display names and reaction equations provide sufficient information to determine the chemical identities of each species.
Synonyms dict: {'glycerol_i': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_i': ['glucose', 'd-glucose', 'blood sugar'], 'G6P': ['glucose-6-phosphate', 'd-glucose-6-phosphate', 'G6P'], 'trehalose': ['trehalose', 'mycose', 'trehalose dihydrate'], 'F16DP': ['fructose-1,6-bisphosphate', 'fructose-1,6-diphosphate', 'F1,6BP'], 'pyruvate': ['pyruvic acid', 'pyruvate', '2-oxopropanoic acid'], 'acetate_i': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_i': ['ethanol', 'ethyl alcohol', 'alcohol'], 'glycerol_e': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_e': ['glucose', 'd-glucose', 'blood sugar'], 'acetate_e': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_e': ['ethanol', 'ethyl alcohol', 'alcohol'], 'trehalose_e': ['trehalose', 'mycose', 'trehalose dihydrate']}
Evaluating 605/1075: BIOMD0000000605.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000605.txt
LLM response:
glycerol_i (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_i (chemical): "glucose", "d-glucose", "blood sugar"
G6P (chemical): "glucose-6-phosphate", "d-glucose-6-phosphate", "G6P"
trehalose (chemical): "trehalose", "mycose", "trehalose sugar"
F16DP (chemical): "fructose-1,6-bisphosphate", "d-fructose-1,6-bisphosphate", "F1,6BP"
pyruvate (chemical): "pyruvic acid", "pyruvate", "2-oxopropanoic acid"
acetate_i (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_i (chemical): "ethanol", "ethyl alcohol", "alcohol"
glycerol_e (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_e (chemical): "glucose", "d-glucose", "blood sugar"
acetate_e (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_e (chemical): "ethanol", "ethyl alcohol", "alcohol"
trehalose_e (chemical): "trehalose", "mycose", "trehalose sugar"
Reason: All species are identified as chemicals because they are all involved in metabolic reactions and are known metabolites. The "_i" and "_e" suffixes likely indicate intracellular and extracellular compartments, respectively, but do not affect the entity type. The names provided are standardized and commonly used in biochemical literature.
Synonyms dict: {'glycerol_i': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_i': ['glucose', 'd-glucose', 'blood sugar'], 'G6P': ['glucose-6-phosphate', 'd-glucose-6-phosphate', 'G6P'], 'trehalose': ['trehalose', 'mycose', 'trehalose sugar'], 'F16DP': ['fructose-1,6-bisphosphate', 'd-fructose-1,6-bisphosphate', 'F1,6BP'], 'pyruvate': ['pyruvic acid', 'pyruvate', '2-oxopropanoic acid'], 'acetate_i': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_i': ['ethanol', 'ethyl alcohol', 'alcohol'], 'glycerol_e': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_e': ['glucose', 'd-glucose', 'blood sugar'], 'acetate_e': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_e': ['ethanol', 'ethyl alcohol', 'alcohol'], 'trehalose_e': ['trehalose', 'mycose', 'trehalose sugar']}
Evaluating 606/1075: BIOMD0000000606.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000606.txt
LLM response:
glycerol_i (chemical): "glycerol", "glycerin", "propanetriol"
glucose_i (chemical): "glucose", "d-glucose", "blood sugar"
G6P (chemical): "glucose-6-phosphate", "d-glucose-6-phosphate", "G6P"
trehalose (chemical): "trehalose", "mycose", "trehalose dihydrate"
F16DP (chemical): "fructose-1,6-bisphosphate", "d-fructose-1,6-bisphosphate", "F1,6BP"
pyruvate (chemical): "pyruvic acid", "pyruvate", "2-oxopropanoic acid"
acetate_i (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_i (chemical): "ethanol", "ethyl alcohol", "alcohol"
glycerol_e (chemical): "glycerol", "glycerin", "propanetriol"
glucose_e (chemical): "glucose", "d-glucose", "blood sugar"
acetate_e (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_e (chemical): "ethanol", "ethyl alcohol", "alcohol"
trehalose_e (chemical): "trehalose", "mycose", "trehalose dihydrate"
Reason: All species are annotated as chemicals because they are all metabolites involved in various biochemical reactions in the given model, such as glycolysis and fermentation. The suffixes "_i" and "_e" likely indicate intracellular and extracellular compartments, respectively, but do not affect the entity type. The standardized names and synonyms provided are based on common biochemical nomenclature.
Synonyms dict: {'glycerol_i': ['glycerol', 'glycerin', 'propanetriol'], 'glucose_i': ['glucose', 'd-glucose', 'blood sugar'], 'G6P': ['glucose-6-phosphate', 'd-glucose-6-phosphate', 'G6P'], 'trehalose': ['trehalose', 'mycose', 'trehalose dihydrate'], 'F16DP': ['fructose-1,6-bisphosphate', 'd-fructose-1,6-bisphosphate', 'F1,6BP'], 'pyruvate': ['pyruvic acid', 'pyruvate', '2-oxopropanoic acid'], 'acetate_i': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_i': ['ethanol', 'ethyl alcohol', 'alcohol'], 'glycerol_e': ['glycerol', 'glycerin', 'propanetriol'], 'glucose_e': ['glucose', 'd-glucose', 'blood sugar'], 'acetate_e': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_e': ['ethanol', 'ethyl alcohol', 'alcohol'], 'trehalose_e': ['trehalose', 'mycose', 'trehalose dihydrate']}
Evaluating 607/1075: BIOMD0000000607.xml

2025-11-20 13:14:07,072 - WARNING - Skipping BIOMD0000000608.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000607.txt
LLM response:
glycerol_i (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_i (chemical): "glucose", "d-glucose", "blood sugar"
G6P (chemical): "glucose-6-phosphate", "d-glucose-6-phosphate", "G6P"
trehalose (chemical): "trehalose", "mycose", "trehalose sugar"
F16DP (chemical): "fructose-1,6-bisphosphate", "d-fructose-1,6-bisphosphate", "F1,6BP"
pyruvate (chemical): "pyruvic acid", "pyruvate", "2-oxopropanoic acid"
acetate_i (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_i (chemical): "ethanol", "ethyl alcohol", "alcohol"
glycerol_e (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_e (chemical): "glucose", "d-glucose", "blood sugar"
acetate_e (chemical): "acetic acid", "acetate", "ethanoic acid"
ethanol_e (chemical): "ethanol", "ethyl alcohol", "alcohol"
trehalose_e (chemical): "trehalose", "mycose", "trehalose sugar"
Reason: All species are identified as chemicals because they are all involved in metabolic reactions and are known intermediates or products of glycolysis, gluconeogenesis, and other metabolic pathways. The "_i" and "_e" suffixes likely indicate intracellular and extracellular compartments, respectively. The display names and reaction equations provide sufficient information to determine the entity types and standardized names for each species.
Synonyms dict: {'glycerol_i': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_i': ['glucose', 'd-glucose', 'blood sugar'], 'G6P': ['glucose-6-phosphate', 'd-glucose-6-phosphate', 'G6P'], 'trehalose': ['trehalose', 'mycose', 'trehalose sugar'], 'F16DP': ['fructose-1,6-bisphosphate', 'd-fructose-1,6-bisphosphate', 'F1,6BP'], 'pyruvate': ['pyruvic acid', 'pyruvate', '2-oxopropanoic acid'], 'acetate_i': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_i': ['ethanol', 'ethyl alcohol', 'alcohol'], 'glycerol_e': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_e': ['glucose', 'd-glucose', 'blood sugar'], 'acetate_e': ['acetic acid', 'acetate', 'ethanoic acid'], 'ethanol_e': ['ethanol', 'ethyl alcohol', 'alcohol'], 'trehalose_e': ['trehalose', 'mycose', 'trehalose sugar']}
Evaluating 608/1075: BIOMD0000000608.xml
Evaluating 609/1075: BIOMD0000000609.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000609.txt
LLM response:
Sulphate__PAPS (chemical): "3'-phosphoadenosine-5'-phosphosulfate", "PAPS", "adenosine 3'-phosphate 5'-phosphosulfate"
GSH (chemical): "glutathione", "reduced glutathione", "GSH tripeptide"
Reason: Sulphate__PAPS is identified as a chemical because it is involved in a reaction with Paracetamol_APAP, which is a metabolite, and PAPS is a known cofactor in sulfation reactions. GSH is also identified as a chemical because it is a well-known antioxidant tripeptide involved in various metabolic processes, including detoxification reactions, and its involvement in reactions with NAPQI suggests a role in scavenging reactive metabolites.
Synonyms dict: {'Sulphate__PAPS': ["3'-phosphoadenosine-5'-phosphosulfate", 'PAPS', "adenosine 3'-phosphate 5'-phosphosulfate"], 'GSH': ['glutathione', 'reduced glutathione', 'GSH tripeptide']}
Evaluating 610/1075: BIOMD0000000610.xml

2025-11-20 13:14:13,227 - WARNING - Skipping BIOMD0000000611.xml - no results generated
2025-11-20 13:14:13,245 - WARNING - Skipping BIOMD0000000612.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000610.txt
LLM response:
glycerol_i (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_i (chemical): "glucose", "d-glucose", "blood sugar"
G6P (chemical): "glucose-6-phosphate", "d-glucose-6-phosphate", "G6P"
trehalose (chemical): "trehalose", "mycose", "trehalose dihydrate"
F16DP (chemical): "fructose-1,6-bisphosphate", "fructose 1,6-diphosphate", "F1,6BP"
pyruvate (chemical): "pyruvic acid", "pyruvate", "2-oxopropanoic acid"
acetate_i (chemical): "acetate", "acetic acid", "ethanoic acid"
ethanol_i (chemical): "ethanol", "ethyl alcohol", "alcohol"
glycerol_e (chemical): "glycerol", "glycerin", "propane-1,2,3-triol"
glucose_e (chemical): "glucose", "d-glucose", "blood sugar"
acetate_e (chemical): "acetate", "acetic acid", "ethanoic acid"
ethanol_e (chemical): "ethanol", "ethyl alcohol", "alcohol"
trehalose_e (chemical): "trehalose", "mycose", "trehalose dihydrate"
Reason: All species are identified as chemicals because they are all metabolites involved in the osmoadaptation and glycolytic pathways. The standardized names are based on common biochemical nomenclature, and the synonyms are provided in order of likelihood based on common usage in the field. The "_i" and "_e" suffixes on some species IDs likely indicate "internal" and "external" compartments, respectively, but do not affect the entity type or standardized names.
Synonyms dict: {'glycerol_i': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_i': ['glucose', 'd-glucose', 'blood sugar'], 'G6P': ['glucose-6-phosphate', 'd-glucose-6-phosphate', 'G6P'], 'trehalose': ['trehalose', 'mycose', 'trehalose dihydrate'], 'F16DP': ['fructose-1,6-bisphosphate', 'fructose 1,6-diphosphate', 'F1,6BP'], 'pyruvate': ['pyruvic acid', 'pyruvate', '2-oxopropanoic acid'], 'acetate_i': ['acetate', 'acetic acid', 'ethanoic acid'], 'ethanol_i': ['ethanol', 'ethyl alcohol', 'alcohol'], 'glycerol_e': ['glycerol', 'glycerin', 'propane-1,2,3-triol'], 'glucose_e': ['glucose', 'd-glucose', 'blood sugar'], 'acetate_e': ['acetate', 'acetic acid', 'ethanoic acid'], 'ethanol_e': ['ethanol', 'ethyl alcohol', 'alcohol'], 'trehalose_e': ['trehalose', 'mycose', 'trehalose dihydrate']}
Evaluating 611/1075: BIOMD0000000611.xml
Evaluating 612/1075: BIOMD0000000612.xml
Evaluating 613/1075: BIOMD0000000613.xml

2025-11-20 13:14:15,988 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:14:16,042 - WARNING - Skipping BIOMD0000000614.xml - no results generated
2025-11-20 13:14:16,049 - WARNING - Skipping BIOMD0000000615.xml - no results generated
2025-11-20 13:14:16,055 - WARNING - Skipping BIOMD0000000616.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000613.txt
LLM response:
B (chemical): "calcium ion", "Ca2+", "calcium"
P (protein): "parathyroid hormone", "PTH", "parathormone"
T (chemical): "calcitriol", "1,25-dihydroxyvitamin D3", "1,25-D3"
R (chemical): "phosphate ion", "PO4", "phosphoric acid"
Q (chemical): "calcium", "calcium ion", "Ca2+"
Qbone (complex): "bone tissue", "bone calcium", "hydroxyapatite"

Reason: Based on the model description and notes, B is likely calcium ion, which is a key component in calcium homeostasis. P is likely parathyroid hormone, a protein hormone that regulates calcium levels. T is likely calcitriol, a chemical involved in calcium homeostasis. R is likely phosphate ion, which is also involved in calcium homeostasis. Q is also likely calcium, given its relationship with B. Qbone is likely a complex representing bone tissue, given its relationship with Q.
Synonyms dict: {'B': ['calcium ion', 'Ca2+', 'calcium'], 'P': ['parathyroid hormone', 'PTH', 'parathormone'], 'T': ['calcitriol', '1,25-dihydroxyvitamin D3', '1,25-D3'], 'R': ['phosphate ion', 'PO4', 'phosphoric acid'], 'Q': ['calcium', 'calcium ion', 'Ca2+'], 'Qbone': ['bone tissue', 'bone calcium', 'hydroxyapatite']}
Evaluating 614/1075: BIOMD0000000614.xml
Evaluating 615/1075: BIOMD0000000615.xml
Evaluating 616/1075: BIOMD0000000616.xml
Evaluating 617/1075: BIOMD0000000617.xml

2025-11-20 13:14:17,507 - WARNING - Skipping BIOMD0000000617.xml - no results generated
2025-11-20 13:14:17,524 - WARNING - Skipping BIOMD0000000618.xml - no results generated
2025-11-20 13:14:17,533 - WARNING - Skipping BIOMD0000000619.xml - no results generated

Evaluating 618/1075: BIOMD0000000618.xml
Evaluating 619/1075: BIOMD0000000619.xml
Evaluating 620/1075: BIOMD0000000620.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000620.txt
LLM response:
Glucose (chemical): "glucose", "D-glucose", "blood sugar"
Reason: Glucose is a well-known chemical compound, a simple sugar that serves as a primary source of energy for cells. In the context of the model "Palmer2014 - Effect of IL-1β-Blocking therapies in T2DM - Disease Condition", glucose is a key species involved in the regulation of blood sugar levels and insulin dynamics, which is a critical aspect of type 2 diabetes mellitus (T2DM) management. The model's focus on the effects of IL-1β-blocking therapies on glucose metabolism and insulin function further supports the classification of glucose as a chemical entity.
Synonyms dict: {'Glucose': ['glucose', 'D-glucose', 'blood sugar']}
Evaluating 621/1075: BIOMD0000000621.xml

2025-11-20 13:14:20,284 - WARNING - Skipping BIOMD0000000622.xml - no results generated
2025-11-20 13:14:20,306 - WARNING - Skipping BIOMD0000000623.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000621.txt
LLM response:
Glucose (chemical): "glucose", "D-glucose", "blood sugar"
Reason: Glucose is a well-known chemical compound, a simple sugar that serves as a primary source of energy for cells; its presence in a model related to type 2 diabetes mellitus and its involvement in reactions without any indication of genetic or protein-related processes suggest it is a chemical entity.
Synonyms dict: {'Glucose': ['glucose', 'D-glucose', 'blood sugar']}
Evaluating 622/1075: BIOMD0000000622.xml
Evaluating 623/1075: BIOMD0000000623.xml
Evaluating 624/1075: BIOMD0000000624.xml

2025-11-20 13:14:23,481 - WARNING - Skipping BIOMD0000000625.xml - no results generated
2025-11-20 13:14:23,493 - WARNING - Skipping BIOMD0000000626.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000624.txt
LLM response:
APAP (chemical): "Acetaminophen", "Paracetamol", "APAP"
NAPQI (chemical): "N-acetyl-p-benzoquinone imine", "NAPQI", "P-benzoquinone imine"
GSH (chemical): "Glutathione", "GSH", "Gamma-glutamylcysteinylglycine"
NAPQIGSH (complex): "NAPQI-GSH conjugate", "NAPQI-glutathione adduct", "GS-NAPQI"
APAPconj_Glu (chemical): "Acetaminophen glucuronide", "APAP-Gluc", "N-acetyl-p-aminophenol glucuronide"
APAPconj_Sul (chemical): "Acetaminophen sulfate", "APAP-Sulfate", "N-acetyl-p-aminophenol sulfate"
Reason: APAP, NAPQI, GSH, APAPconj_Glu, and APAPconj_Sul are identified as chemicals based on their roles in the acetaminophen metabolism pathway. NAPQIGSH is classified as a complex because it is a conjugate formed between NAPQI and GSH. The standardized names and synonyms provided are based on common names and abbreviations used in the context of acetaminophen metabolism and biochemistry.
Synonyms dict: {'APAP': ['Acetaminophen', 'Paracetamol', 'APAP'], 'NAPQI': ['N-acetyl-p-benzoquinone imine', 'NAPQI', 'P-benzoquinone imine'], 'GSH': ['Glutathione', 'GSH', 'Gamma-glutamylcysteinylglycine'], 'NAPQIGSH': ['NAPQI-GSH conjugate', 'NAPQI-glutathione adduct', 'GS-NAPQI'], 'APAPconj_Glu': ['Acetaminophen glucuronide', 'APAP-Gluc', 'N-acetyl-p-aminophenol glucuronide'], 'APAPconj_Sul': ['Acetaminophen sulfate', 'APAP-Sulfate', 'N-acetyl-p-aminophenol sulfate']}
Evaluating 625/1075: BIOMD0000000625.xml
Evaluating 626/1075: BIOMD0000000626.xml
Evaluating 627/1075: BIOMD0000000627.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000627.txt
LLM response:
species_27 (chemical): "glucose", "D-glucose", "blood glucose"
species_28 (chemical): "lactate", "lactic acid", "L-lactate"
GLU_extracellular_space (chemical): "glutamate", "L-glutamate", "glutamic acid"
Na__extracellular_space (chemical): "sodium ion", "sodium", "Na+"
O2_artery (chemical): "oxygen", "dioxygen", "O2"
CO2_artery (chemical): "carbon dioxide", "CO2", "carbonic acid"
GLC_artery (chemical): "glucose", "D-glucose", "blood glucose"
LAC_artery (chemical): "lactate", "lactic acid", "L-lactate"
Reason: The species are identified based on their display names and the context of the brain energy metabolism model. species_27 and GLC_artery are identified as glucose due to their display names and reactions involving glucose metabolism. species_28 and LAC_artery are identified as lactate due to their display names and reactions involving lactate production and transport. GLU_extracellular_space is identified as glutamate due to its display name and reaction involving glutamate transport. Na__extracellular_space is identified as sodium ion due to its display name and reactions involving sodium transport. O2_artery and CO2_artery are identified as oxygen and carbon dioxide, respectively, due to their display names and roles in energy metabolism.
Synonyms dict: {'species_1': ['glucose', 'D-glucose', 'blood sugar'], 'species_2': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'species_3': ['ATP', 'adenosine triphosphate', 'energy currency'], 'species_4': ['glucose', 'D-glucose', 'blood sugar'], 'species_5': ['ATP', 'adenosine triphosphate', 'energy currency'], 'species_6': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'species_7': ['fructose-6-phosphate', 'F6P', 'D-fructose-6-phosphate'], 'species_8': ['fructose-6-phosphate', 'F6P', 'D-fructose-6-phosphate'], 'species_9': ['glyceraldehyde-3-phosphate', 'GAP', 'D-glyceraldehyde-3-phosphate'], 'species_10': ['glyceraldehyde-3-phosphate', 'GAP', 'D-glyceraldehyde-3-phosphate'], 'species_11': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced NAD'], 'species_12': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvate'], 'species_13': ['NADH', 'nicotinamide adenine dinucleotide', 'reduced NAD'], 'species_14': ['phosphoenolpyruvate', 'PEP', '2-phosphoenolpyruvate'], 'species_15': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'species_16': ['oxygen', 'O2', 'molecular oxygen'], 'species_17': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'species_18': ['lactate', 'lactic acid', '2-hydroxypropanoic acid'], 'species_19': ['lactate', 'lactic acid', '2-hydroxypropanoic acid'], 'species_20': ['oxygen', 'O2', 'molecular oxygen'], 'species_21': ['phosphocreatine', 'PCr', 'creatine phosphate'], 'species_22': ['phosphocreatine', 'PCr', 'creatine phosphate'], 'species_23': ['oxygen', 'O2', 'molecular oxygen'], 'species_24': ['carbon dioxide', 'CO2', 'molecular carbon dioxide'], 'species_25': ['glucose', 'D-glucose', 'blood sugar'], 'species_26': ['lactate', 'lactic acid', '2-hydroxypropanoic acid'], 'species_27': ['glucose', 'D-glucose', 'blood glucose'], 'species_28': ['lactate', 'lactic acid', 'L-lactate'], 'Na__neurons': ['sodium ion', 'Na+', 'sodium'], 'GLU_neurons': ['glutamate', 'L-glutamate', 'glutamic acid'], 'ADP_neurons': ['ADP', 'adenosine diphosphate', 'energy currency'], 'AMP_neurons': ['AMP', 'adenosine monophosphate', 'energy currency'], 'Cr_neurons': ['creatine', 'Cr', 'methylguanidineacetic acid'], 'G6L_neurons': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'P6G_neurons': ['6-phosphogluconate', '6PG', '6-phosphogluconic acid'], 'Ru5P_neurons': ['ribulose-5-phosphate', 'Ru5P', 'D-ribulose-5-phosphate'], 'X5P_neurons': ['xylulose-5-phosphate', 'X5P', 'D-xylulose-5-phosphate'], 'R5P_neurons': ['ribose-5-phosphate', 'R5P', 'D-ribose-5-phosphate'], 'S7P_neurons': ['sedoheptulose-7-phosphate', 'S7P', 'D-sedoheptulose-7-phosphate'], 'E4P_neurons': ['erythrose-4-phosphate', 'E4P', 'D-erythrose-4-phosphate'], 'NADPH_neurons': ['NADPH', 'nicotinamide adenine dinucleotide phosphate', 'reduced NADP'], 'Na__astrocytes': ['sodium ion', 'Na+', 'sodium'], 'GLU_astrocytes': ['glutamate', 'L-glutamate', 'glutamic acid'], 'ADP_astrocytes': ['ADP', 'adenosine diphosphate', 'energy currency'], 'AMP_astrocytes': ['AMP', 'adenosine monophosphate', 'energy currency'], 'Cr_astrocytes': ['creatine', 'Cr', 'methylguanidineacetic acid'], 'G6L_astrocytes': ['glucose-6-phosphate', 'G6P', 'D-glucose-6-phosphate'], 'P6G_astrocytes': ['6-phosphogluconate', '6PG', '6-phosphogluconic acid'], 'Ru5P_astrocytes': ['ribulose-5-phosphate', 'Ru5P', 'D-ribulose-5-phosphate'], 'X5P_astrocytes': ['xylulose-5-phosphate', 'X5P', 'D-xylulose-5-phosphate'], 'R5P_astrocytes': ['ribose-5-phosphate', 'R5P', 'D-ribose-5-phosphate'], 'S7P_astrocytes': ['sedoheptulose-7-phosphate', 'S7P', 'D-sedoheptulose-7-phosphate'], 'E4P_astrocytes': ['erythrose-4-phosphate', 'E4P', 'D-erythrose-4-phosphate'], 'NADPH_astrocytes': ['NADPH', 'nicotinamide adenine dinucleotide phosphate', 'reduced NADP'], 'GLU_extracellular_space': ['glutamate', 'L-glutamate', 'glutamic acid'], 'Na__extracellular_space': ['sodium ion', 'sodium', 'Na+'], 'O2_artery': ['oxygen', 'dioxygen', 'O2'], 'CO2_artery': ['carbon dioxide', 'CO2', 'carbonic acid'], 'GLC_artery': ['glucose', 'D-glucose', 'blood glucose'], 'LAC_artery': ['lactate', 'lactic acid', 'L-lactate']}
Evaluating 628/1075: BIOMD0000000628.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000628.txt
LLM response:
Ca (chemical): "calcium", "Ca2+", "calcium ion"
CBPfastCa (complex): "CBP-fast-Ca", "CBP fast calcium", "calcium bound CBP fast"
CBPmediaCa (complex): "CBP-media-Ca", "CBP media calcium", "calcium bound CBP media"
CBPslowCa (complex): "CBP-slow-Ca", "CBP slow calcium", "calcium bound CBP slow"
CBPvslowCa (complex): "CBP-vslow-Ca", "CBP vslow calcium", "calcium bound CBP vslow"
CamR (protein): "calmodulin", "CaM", "calcium modulated protein"
CamR_Ca1_A (complex): "calmodulin-Ca", "CaM-Ca", "calcium bound calmodulin"
CamR_Ca2_AB (complex): "calmodulin-Ca2", "CaM-Ca2", "calcium bound calmodulin dimer"
CamR_Ca3_ABC (complex): "calmodulin-Ca3", "CaM-Ca3", "calcium bound calmodulin trimer"
CamR_Ca4_ABCD (complex): "calmodulin-Ca4", "CaM-Ca4", "calcium bound calmodulin tetramer"
CamT (protein): "calcineurin", "CaN", "protein phosphatase 2B"
CamT_Ca1_A (complex): "calcineurin-Ca", "CaN-Ca", "calcium bound calcineurin"
CamT_Ca2_AB (complex): "calcineurin-Ca2", "CaN-Ca2", "calcium bound calcineurin dimer"
CamT_Ca3_ABC (complex): "calcineurin-Ca3", "CaN-Ca3", "calcium bound calcineurin trimer"
CamT_Ca4_ABCD (complex): "calcineurin-Ca4", "CaN-Ca4", "calcium bound calcineurin tetramer"
CaMKII (protein): "CaMKII", "calcium calmodulin dependent protein kinase II", "CaM kinase II"
CaMKIIp (protein): "phosphorylated CaMKII", "pCaMKII", "activated CaMKII"
PP2B (protein): "protein phosphatase 2B", "PP2B", "calcineurin"
PP1a (protein): "protein phosphatase 1a", "PP1a", "serine/threonine phosphatase"
PP2Bi (protein): "protein phosphatase 2B inhibitor", "PP2Bi", "calcineurin inhibitor"
D (unknown): "UNK", "unknown species", "unidentified molecule"
Dp (unknown): "UNK", "unknown species", "unidentified molecule"
CamR_CaMKII (complex): "calmodulin-CaMKII", "CaM-CaMKII", "calcium bound calmodulin CaMKII"
CamR_Ca1_A_CaMKII (complex): "calmodulin-Ca-CaMKII", "CaM-Ca-CaMKII", "calcium bound calmodulin CaMKII"
CamR_Ca2_AB_CaMKII (complex): "calmodulin-Ca2-CaMKII", "CaM-Ca2-CaMKII", "calcium bound calmodulin dimer CaMKII"
CamR_Ca3_ABC_CaMKII (complex): "calmodulin-Ca3-CaMKII", "CaM-Ca3-CaMKII", "calcium bound calmodulin trimer CaMKII"
CamR_Ca4_ABCD_CaMKII (complex): "calmodulin-Ca4-CaMKII", "CaM-Ca4-CaMKII", "calcium bound calmodulin tetramer CaMKII"
CamR_Ca1_A_PP2B (complex): "calmodulin-Ca-PP2B", "CaM-Ca-PP2B", "calcium bound calmodulin PP2B"
CamR_Ca2_AB_PP2B (complex): "calmodulin-Ca2-PP2B", "CaM-Ca2-PP2B", "calcium bound calmodulin dimer PP2B"
CamR_Ca3_ABC_PP2B (complex): "calmodulin-Ca3-PP2B", "CaM-Ca3-PP2B", "calcium bound calmodulin trimer PP2B"
CamR_Ca4_ABCD_PP2B (complex): "calmodulin-Ca4-PP2B", "CaM-Ca4-PP2B", "calcium bound calmodulin tetramer PP2B"
Dp_CamR_Ca1_A_PP2B (complex): "Dp-calmodulin-Ca-PP2B", "Dp-CaM-Ca-PP2B", "Dp calcium bound calmodulin PP2B"
Dp_CamR_Ca2_AB_PP2B (complex): "Dp-calmodulin-Ca2-PP2B", "Dp-CaM-Ca2-PP2B", "Dp calcium bound calmodulin dimer PP2B"
Dp_CamR_Ca3_ABC_PP2B (complex): "Dp-calmodulin-Ca3-PP2B", "Dp-CaM-Ca3-PP2B", "Dp calcium bound calmodulin trimer PP2B"
Dp_CamR_Ca4_ABCD_PP2B (complex): "Dp-calmodulin-Ca4-PP2B", "Dp-CaM-Ca4-PP2B", "Dp calcium bound calmodulin tetramer PP2B"
CamR_CaMKIIp (complex): "calmodulin-CaMKIIp", "CaM-CaMKIIp", "calcium bound calmodulin phosphorylated CaMKII"
CamR_Ca1_A_CaMKIIp (complex): "calmodulin-Ca-CaMKIIp", "CaM-Ca-CaMKIIp", "calcium bound calmodulin phosphorylated CaMKII"
CamR_Ca2_AB_CaMKIIp (complex): "calmodulin-Ca2-CaMKIIp", "CaM-Ca2-CaMKIIp", "calcium bound calmodulin dimer phosphorylated CaMKII"
CamR_Ca3_ABC_CaMKIIp (complex): "calmodulin-Ca3-CaMKIIp", "CaM-Ca3-CaMKIIp", "calcium bound calmodulin trimer phosphorylated CaMKII"
CamR_Ca4_ABCD_CaMKIIp (complex): "calmodulin-Ca4-CaMKIIp", "CaM-Ca4-CaMKIIp", "calcium bound calmodulin tetramer phosphorylated CaMKII"
CamR_Ca1_A_CaMKIIp_PP1a (complex): "calmodulin-Ca-CaMKIIp-PP1a", "CaM-Ca-CaMKIIp-PP1a", "calcium bound calmodulin phosphorylated CaMKII PP1a"
CamR_Ca2_AB_CaMKIIp_PP1a (complex): "calmodulin-Ca2-CaMKIIp-PP1a", "CaM-Ca2-CaMKIIp-PP1a", "calcium bound calmodulin dimer phosphorylated CaMKII PP1a"
CamR_Ca3_ABC_CaMKIIp_PP1a (complex): "calmodulin-Ca3-CaMKIIp-PP1a", "CaM-Ca3-CaMKIIp-PP1a", "calcium bound calmodulin trimer phosphorylated CaMKII PP1a"
CamR_Ca4_ABCD_CaMKIIp_PP1a (complex): "calmodulin-Ca4-CaMKIIp-PP1a", "CaM-Ca4-CaMKIIp-PP1a", "calcium bound calmodulin tetramer phosphorylated CaMKII PP1a"
CaMKIIp_PP1a (complex): "phosphorylated CaMKII-PP1a", "pCaMKII-PP1a", "activated CaMKII PP1a"
PP2Bi_Ca1 (complex): "PP2B inhibitor-Ca", "PP2Bi-Ca", "calcium bound PP2B inhibitor"
PP2Bi_Ca2 (complex): "PP2B inhibitor-Ca2", "PP2Bi-Ca2", "calcium bound PP2B inhibitor dimer"
PP2Bi_Ca3 (complex): "PP2B inhibitor-Ca3", "PP2Bi-Ca3", "calcium bound PP2B inhibitor trimer"

Reason: The model is based on the Li2012 Calcium mediated synaptic plasticity model, which describes the activation of calcineurin and CaMKII by calcium ions. The species are identified based on their names and reactions in the model. Calcium (Ca) is a chemical, while calmodulin (CamR), calcineurin (CamT), CaMKII, and PP2B are proteins. The complexes are formed by the binding of calcium ions to these proteins. The unknown species (D and Dp) are not identified in the model. The entity types are determined based on the species' roles in the model and their biological functions.
Synonyms dict: {'Ca': ['calcium', 'Ca2+', 'calcium ion'], 'CBPfastCa': ['CBP-fast-Ca', 'CBP fast calcium', 'calcium bound CBP fast'], 'CBPmediaCa': ['CBP-media-Ca', 'CBP media calcium', 'calcium bound CBP media'], 'CBPslowCa': ['CBP-slow-Ca', 'CBP slow calcium', 'calcium bound CBP slow'], 'CBPvslowCa': ['CBP-vslow-Ca', 'CBP vslow calcium', 'calcium bound CBP vslow'], 'CamR': ['calmodulin', 'CaM', 'calcium modulated protein'], 'CamR_Ca1_A': ['calmodulin-Ca', 'CaM-Ca', 'calcium bound calmodulin'], 'CamR_Ca2_AB': ['calmodulin-Ca2', 'CaM-Ca2', 'calcium bound calmodulin dimer'], 'CamR_Ca3_ABC': ['calmodulin-Ca3', 'CaM-Ca3', 'calcium bound calmodulin trimer'], 'CamR_Ca4_ABCD': ['calmodulin-Ca4', 'CaM-Ca4', 'calcium bound calmodulin tetramer'], 'CamT': ['calcineurin', 'CaN', 'protein phosphatase 2B'], 'CamT_Ca1_A': ['calcineurin-Ca', 'CaN-Ca', 'calcium bound calcineurin'], 'CamT_Ca2_AB': ['calcineurin-Ca2', 'CaN-Ca2', 'calcium bound calcineurin dimer'], 'CamT_Ca3_ABC': ['calcineurin-Ca3', 'CaN-Ca3', 'calcium bound calcineurin trimer'], 'CamT_Ca4_ABCD': ['calcineurin-Ca4', 'CaN-Ca4', 'calcium bound calcineurin tetramer'], 'CaMKII': ['CaMKII', 'calcium calmodulin dependent protein kinase II', 'CaM kinase II'], 'CaMKIIp': ['phosphorylated CaMKII', 'pCaMKII', 'activated CaMKII'], 'PP2B': ['protein phosphatase 2B', 'PP2B', 'calcineurin'], 'PP1a': ['protein phosphatase 1a', 'PP1a', 'serine/threonine phosphatase'], 'PP2Bi': ['protein phosphatase 2B inhibitor', 'PP2Bi', 'calcineurin inhibitor'], 'D': ['UNK', 'unknown species', 'unidentified molecule'], 'Dp': ['UNK', 'unknown species', 'unidentified molecule'], 'CamR_CaMKII': ['calmodulin-CaMKII', 'CaM-CaMKII', 'calcium bound calmodulin CaMKII'], 'CamR_Ca1_A_CaMKII': ['calmodulin-Ca-CaMKII', 'CaM-Ca-CaMKII', 'calcium bound calmodulin CaMKII'], 'CamR_Ca2_AB_CaMKII': ['calmodulin-Ca2-CaMKII', 'CaM-Ca2-CaMKII', 'calcium bound calmodulin dimer CaMKII'], 'CamR_Ca3_ABC_CaMKII': ['calmodulin-Ca3-CaMKII', 'CaM-Ca3-CaMKII', 'calcium bound calmodulin trimer CaMKII'], 'CamR_Ca4_ABCD_CaMKII': ['calmodulin-Ca4-CaMKII', 'CaM-Ca4-CaMKII', 'calcium bound calmodulin tetramer CaMKII'], 'CamR_Ca1_A_PP2B': ['calmodulin-Ca-PP2B', 'CaM-Ca-PP2B', 'calcium bound calmodulin PP2B'], 'CamR_Ca2_AB_PP2B': ['calmodulin-Ca2-PP2B', 'CaM-Ca2-PP2B', 'calcium bound calmodulin dimer PP2B'], 'CamR_Ca3_ABC_PP2B': ['calmodulin-Ca3-PP2B', 'CaM-Ca3-PP2B', 'calcium bound calmodulin trimer PP2B'], 'CamR_Ca4_ABCD_PP2B': ['calmodulin-Ca4-PP2B', 'CaM-Ca4-PP2B', 'calcium bound calmodulin tetramer PP2B'], 'Dp_CamR_Ca1_A_PP2B': ['Dp-calmodulin-Ca-PP2B', 'Dp-CaM-Ca-PP2B', 'Dp calcium bound calmodulin PP2B'], 'Dp_CamR_Ca2_AB_PP2B': ['Dp-calmodulin-Ca2-PP2B', 'Dp-CaM-Ca2-PP2B', 'Dp calcium bound calmodulin dimer PP2B'], 'Dp_CamR_Ca3_ABC_PP2B': ['Dp-calmodulin-Ca3-PP2B', 'Dp-CaM-Ca3-PP2B', 'Dp calcium bound calmodulin trimer PP2B'], 'Dp_CamR_Ca4_ABCD_PP2B': ['Dp-calmodulin-Ca4-PP2B', 'Dp-CaM-Ca4-PP2B', 'Dp calcium bound calmodulin tetramer PP2B'], 'CamR_CaMKIIp': ['calmodulin-CaMKIIp', 'CaM-CaMKIIp', 'calcium bound calmodulin phosphorylated CaMKII'], 'CamR_Ca1_A_CaMKIIp': ['calmodulin-Ca-CaMKIIp', 'CaM-Ca-CaMKIIp', 'calcium bound calmodulin phosphorylated CaMKII'], 'CamR_Ca2_AB_CaMKIIp': ['calmodulin-Ca2-CaMKIIp', 'CaM-Ca2-CaMKIIp', 'calcium bound calmodulin dimer phosphorylated CaMKII'], 'CamR_Ca3_ABC_CaMKIIp': ['calmodulin-Ca3-CaMKIIp', 'CaM-Ca3-CaMKIIp', 'calcium bound calmodulin trimer phosphorylated CaMKII'], 'CamR_Ca4_ABCD_CaMKIIp': ['calmodulin-Ca4-CaMKIIp', 'CaM-Ca4-CaMKIIp', 'calcium bound calmodulin tetramer phosphorylated CaMKII'], 'CamR_Ca1_A_CaMKIIp_PP1a': ['calmodulin-Ca-CaMKIIp-PP1a', 'CaM-Ca-CaMKIIp-PP1a', 'calcium bound calmodulin phosphorylated CaMKII PP1a'], 'CamR_Ca2_AB_CaMKIIp_PP1a': ['calmodulin-Ca2-CaMKIIp-PP1a', 'CaM-Ca2-CaMKIIp-PP1a', 'calcium bound calmodulin dimer phosphorylated CaMKII PP1a'], 'CamR_Ca3_ABC_CaMKIIp_PP1a': ['calmodulin-Ca3-CaMKIIp-PP1a', 'CaM-Ca3-CaMKIIp-PP1a', 'calcium bound calmodulin trimer phosphorylated CaMKII PP1a'], 'CamR_Ca4_ABCD_CaMKIIp_PP1a': ['calmodulin-Ca4-CaMKIIp-PP1a', 'CaM-Ca4-CaMKIIp-PP1a', 'calcium bound calmodulin tetramer phosphorylated CaMKII PP1a'], 'CaMKIIp_PP1a': ['phosphorylated CaMKII-PP1a', 'pCaMKII-PP1a', 'activated CaMKII PP1a'], 'PP2Bi_Ca1': ['PP2B inhibitor-Ca', 'PP2Bi-Ca', 'calcium bound PP2B inhibitor'], 'PP2Bi_Ca2': ['PP2B inhibitor-Ca2', 'PP2Bi-Ca2', 'calcium bound PP2B inhibitor dimer'], 'PP2Bi_Ca3': ['PP2B inhibitor-Ca3', 'PP2Bi-Ca3', 'calcium bound PP2B inhibitor trimer']}
Evaluating 629/1075: BIOMD0000000629.xml

2025-11-20 13:15:12,905 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:15:12,924 - WARNING - Skipping BIOMD0000000630.xml - no results generated
2025-11-20 13:15:12,936 - WARNING - Skipping BIOMD0000000631.xml - no results generated
2025-11-20 13:15:12,951 - WARNING - Skipping BIOMD0000000632.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000629.txt
LLM response:
L (chemical): "retinoic acid", "all-trans-retinoic acid", "ATRA"
R (protein): "retinoic acid receptor", "RAR", "nuclear receptor"
LR (complex): "Ligand-Receptor complex", "retinoic acid receptor complex", "RAR-ligand complex"
LRCA (complex): "Ligand-Receptor-CoActivator complex", "retinoic acid receptor coactivator complex", "RAR-ligand-coactivator complex"
CA (protein): "coactivator protein", "nuclear receptor coactivator", "transcriptional coactivator"
Reason: The species can be annotated based on the context of the model, which describes the interaction between retinoic acid analogues and retinoic acid receptors. L is likely a chemical (retinoic acid) that binds to the receptor R (retinoic acid receptor), forming a complex LR. The addition of CA (coactivator protein) to LR forms another complex, LRCA. The entity types are determined based on the biological context and the display names provided in the model.
Synonyms dict: {'L': ['retinoic acid', 'all-trans-retinoic acid', 'ATRA'], 'R': ['retinoic acid receptor', 'RAR', 'nuclear receptor'], 'LR': ['Ligand-Receptor complex', 'retinoic acid receptor complex', 'RAR-ligand complex'], 'LRCA': ['Ligand-Receptor-CoActivator complex', 'retinoic acid receptor coactivator complex', 'RAR-ligand-coactivator complex'], 'CA': ['coactivator protein', 'nuclear receptor coactivator', 'transcriptional coactivator']}
Evaluating 630/1075: BIOMD0000000630.xml
Evaluating 631/1075: BIOMD0000000631.xml
Evaluating 632/1075: BIOMD0000000632.xml
Evaluating 633/1075: BIOMD0000000633.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000633.txt
LLM response:
glc_ext (chemical): "glucose", "D-glucose", "blood glucose"
lac_ext (chemical): "lactate", "lactic acid", "L-lactate"
glc (chemical): "glucose", "D-glucose", "hexose"
bpg13 (chemical): "1,3-bisphosphoglycerate", "1,3-bisphosphoglyceric acid", "glycerate 1,3-bisphosphate"
lac (chemical): "lactate", "lactic acid", "L-lactate"
glc_er (chemical): "glucose", "D-glucose", "endoplasmic reticulum glucose"
Reason: The species are annotated based on their participation in the reactions and the context of the model, which is focused on hepatic glucose metabolism. glc_ext and lac_ext are likely external glucose and lactate, while glc and lac are their internal counterparts. bpg13 is a metabolite in the glycolytic pathway, and glc_er is glucose in the endoplasmic reticulum. All species are chemicals, as they are involved in metabolic reactions and are not genes, proteins, or complexes.
Synonyms dict: {'glc_ext': ['glucose', 'D-glucose', 'blood glucose'], 'lac_ext': ['lactate', 'lactic acid', 'L-lactate'], 'glc': ['glucose', 'D-glucose', 'hexose'], 'bpg13': ['1,3-bisphosphoglycerate', '1,3-bisphosphoglyceric acid', 'glycerate 1,3-bisphosphate'], 'lac': ['lactate', 'lactic acid', 'L-lactate'], 'glc_er': ['glucose', 'D-glucose', 'endoplasmic reticulum glucose']}
Evaluating 634/1075: BIOMD0000000634.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000634.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP molecule", "adenosine 5'-triphosphate"
ADP (chemical): "adenosine diphosphate", "ADP molecule", "adenosine 5'-diphosphate"
AMP (chemical): "adenosine monophosphate", "AMP molecule", "adenosine 5'-monophosphate"
Reason: All three species (ATP, ADP, AMP) are involved in energy transfer reactions in the cell, and are well-known chemical molecules that play a crucial role in various biological processes, including the reaction equations provided in the model.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP molecule', "adenosine 5'-triphosphate"], 'ADP': ['adenosine diphosphate', 'ADP molecule', "adenosine 5'-diphosphate"], 'AMP': ['adenosine monophosphate', 'AMP molecule', "adenosine 5'-monophosphate"]}
Evaluating 635/1075: BIOMD0000000635.xml

2025-11-20 13:16:02,542 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000635.txt
LLM response:
mwa2c44a01_28c9_4dbd_b034_364f9b5b6cc3 (protein): "Gai", "G protein alpha i", "G alpha i"
mwdb9dc389_2bf0_4039_9f09_282f5511958b (complex): "D1RDA", "D1 dopamine receptor", "DRD1"
mwd794c746_c826_4ba1_9e09_a9d1e122d925 (complex): "AC5GaolfGTPGaiGTP", "Adenylate cyclase 5", "AC5"
mw2075d2cf_955e_4150_98b8_847103c53845 (complex): "AC5GaiGTP*ATP", "Adenylate cyclase 5", "AC5"
mw74e54eed_0d25_4fb0_b677_1192f238c03b (complex): "PKAcAMP2", "Protein kinase A", "PKA"
mw724f1afe_8032_40ae_96ca_808ab7b8b943 (protein): "AC5", "Adenylate cyclase 5", "AC"
mwd8ea533a_c66e_4de4_8c5c_0d4201d8c8a2 (protein): "Gi", "G protein alpha i", "G alpha i"
mwbe974953_e869_4622_b4a8_745555c8d7fd (chemical): "DA", "Dopamine", "3,4-Dihydroxyphenethylamine"
mw56dff932_134c_4d88_a611_daad00623fd0 (complex): "AC5CaGaiGTP*ATP", "Adenylate cyclase 5", "AC5"
mw1f3b8982_3b8c_42b6_8b0f_49b037cbda43 (complex): "PDE10c*cAMP", "Phosphodiesterase 10A", "PDE10A"
mw68d3f409_9462_4515_8c07_bc105fa0eaf1 (protein): "PKAc", "Protein kinase A", "PKA"
mw9bcba6bc_9788_4f7f_afb5_1c8f3b33c3d1 (protein): "GaiGDP", "G protein alpha i", "G alpha i"
mw8e34c23f_1891_4dc9_8f97_dc2f12a1706c (protein): "GaolfGTP", "G protein alpha olf", "G alpha olf"
mw0b46978f_b522_4cde_97f0_574cd7dbbae7 (complex): "D1RGolf", "D1 dopamine receptor", "DRD1"
mw9710c658_a2a1_4f49_b494_af109853f251 (chemical): "AMP", "Adenosine monophosphate", "Adenylate"
mwc783c5e7_7bc8_425a_9bb6_1f01d463365c (protein): "PKA", "Protein kinase A", "PKA"
mwffd5a553_8e03_443d_a67e_0cf39d03f89f (complex): "PKAcAMP4", "Protein kinase A", "PKA"
mw4b358131_010c_4545_ac4a_13a6c8bc34c4 (protein): "CaM", "Calmodulin", "CaM"
mw25023179_9334_438e_bf3e_4e850f84406a (protein): "PP2B", "Protein phosphatase 2B", "PP2B"
mw3d9e6efb_8e12_49c9_a87f_e067914b951d (protein): "PDE10", "Phosphodiesterase 10A", "PDE10A"
mwfaf786e2_00b7_4e0c_b164_5aa1f4ef6356 (complex): "PP2BCaM", "Protein phosphatase 2B", "PP2B"
mw166e3335_56c3_41ef_af0f_b583860991c1 (complex): "AC5GaolfGTP*ATP", "Adenylate cyclase 5", "AC5"
mwfe9ed415_d5af_469c_a549_d8981f1eb01f (complex): "AC5GaolfGTP", "Adenylate cyclase 5", "AC5"
mw24435476_9c30_4878_b26f_4b3c5a0685c6 (protein): "DARPP32", "Dopamine- and cAMP-regulated phosphoprotein", "DARPP-32"
mwd1171b65_ed6c_4413_bf47_5ed80038a7bd (complex): "PP2BCaMCa2", "Protein phosphatase 2B", "PP2B"
mw2f3e9c55_e57f_416e_b4b1_cc49a26192c0 (protein): "D32p34", "DARPP-32", "DARPP32"
mw619502c3_e319_4e29_a677_b2b5f74fc2cf (complex): "AC5Ca*ATP", "Adenylate cyclase 5", "AC5"
mwe2fc02e6_2684_4071_932a_f7a8bd13b2fe (protein): "D1R", "D1 dopamine receptor", "DRD1"
mw9bfd7713_4c48_492c_8583_006bf1b54a1b (complex): "B72PP2ACa*D32p75", "Protein phosphatase 2A", "PP2A"
mw29ba9e7c_6865_4817_8775_be2dbc29651e (complex): "AC5GaiGTP", "Adenylate cyclase 5", "AC5"
mw522cacf1_5e61_4b95_8742_cf61cb824893 (protein): "B72PP2A", "Protein phosphatase 2A", "PP2A"
mw42919ead_5972_4151_85ac_fcc88ca105a6 (complex): "AC5CaGaolfGTP", "Adenylate cyclase 5", "AC5"
mw8a4a0733_64dd_4474_9aaf_7d750b27ae5b (complex): "CaMCa4", "Calmodulin", "CaM"
mw0a10f9cb_3f4b_4bfa_ace9_0ecd2bd74b5e (complex): "AC5GaolfGTPGaiGTP*ATP", "Adenylate cyclase 5", "AC5"
mw1184c368_03fc_435a_9086_dc6ed3067935 (protein): "D32p75", "DARPP-32", "DARPP32"
mw7086a13a_619e_4069_b163_d8a05fc55f42 (complex): "AC5*ATP", "Adenylate cyclase 5", "AC5"
mwe4e36b8e_18b8_4c76_bd46_13614b71da5c (complex): "M4RAChGi", "Muscarinic acetylcholine receptor M4", "M4R"
mwbae3bd11_0ab4_4587_a931_9c5dc5e777ba (complex): "AC5CaGaolfGTP*ATP", "Adenylate cyclase 5", "AC5"
mw3fcd1ec2_a459_49d4_89f7_361e276096d6 (complex): "B72PPA2Ca", "Protein phosphatase 2A", "PP2A"
mw6e845d87_603e_4463_874d_866f554303df (complex): "PDE10*cAMP", "Phosphodiesterase 10A", "PDE10A"
mw1f3b8982_3b8c_42b6_8b0f_49b037cbda43 (complex): "PDE10c*cAMP", "Phosphodiesterase 10A", "PDE10A"
mw46dccec6_6f0f_40f6_a10c_2f34ae7a005a (chemical): "ATP", "Adenosine triphosphate", "Adenylate"
mwed1b3928_8d78_44d1_aee7_9d11d6437cfc (complex): "AC5CaGaiGTP", "Adenylate cyclase 5", "AC5"
mw8825a609_0983_4fb4_a264_e2f7e43d17b3 (complex): "B72PP2ACa*D32p34", "Protein phosphatase 2A", "PP2A"
mwf46d3666_f0f3_4f05_9603_d7e6bb69005e (complex): "PDE4*cAMP", "Phosphodiesterase 4", "PDE4"
mwd86ce0dc_7329_4b27_9de0_ee6bffee3083 (protein): "M4RGi", "Muscarinic acetylcholine receptor M4", "M4R"
mwf82770b9_766a_4c4e_851a_d76da19e8517 (protein): "M4R", "Muscarinic acetylcholine receptor M4", "M4R"
mw2badefa3_32e8_4b66_9e69_245d9ec74e33 (complex): "AC5CaGaolfGTPGaiGTP", "Adenylate cyclase 5", "AC5"
mwb80e4fa1_4849_4ed5_b3b0_3e3025c61ad8 (protein): "Gbgi", "G protein beta gamma", "G beta gamma"
mw3e1a2fbf_37b1_490c_9528_6cb6bbf11b21 (chemical): "ACh", "Acetylcholine", "ACh"
mw1c97b02d_169a_4eb8_bc84_1be57c51a255 (chemical): "cAMP", "Cyclic adenosine monophosphate", "cAMP"
mwccd3a17c_e207_4663_9b16_327b78882497 (chemical): "Ca", "Calcium", "Ca2+"
mwfed0682b_39f1_4b09_94e8_c45a51744092 (protein): "GaolfGDP", "G protein alpha olf", "G alpha olf"
mw6b2f1c44_e0be_4406_bcef_ad5061d519e4 (complex): "D1RDAGolf", "D1 dopamine receptor", "DRD1"
mw7df45520_98cc_4c0b_91a7_c6e7297de98a (complex): "AC5Ca", "Adenylate cyclase 5", "AC5"
mw07c7392b_8d89_4b94_97c5_59f7e256b6f2 (complex): "AC5CaGaolfGTPGaiGTP*ATP", "Adenylate cyclase 5", "AC5"
mw65a14789_ffcf_4bfd_9d53_d2eb2f4d0896 (complex): "CaMCa2", "Calmodulin", "CaM"
mw4b358131_010c_4545_ac4a_13a6c8bc34c4 (protein): "CaM", "Calmodulin", "CaM"
mw25023179_9334_438e_bf3e_4e850f84406a (protein): "PP2B", "Protein phosphatase 2B", "PP2B"
mw4855b1cd_d7bc_4072_9736_dca30bbe448d (protein): "PP2Bc", "Protein phosphatase 2B", "PP2B"
mw3fcd1ec2_a459_49d4_89f7_361e276096d6 (complex): "B72PPA2Ca", "Protein phosphatase 2A", "PP2A"
mw9bfd7713_4c48_492c_8583_006bf1b54a1b (complex): "B72PP2ACa*D32p75", "Protein phosphatase 2A", "PP2A"
mw8825a609_0983_4fb4_a264_e2f7e43d17b3 (complex): "B72PP2ACa*D32p34", "Protein phosphatase 2A", "PP2A"
mwd1171b65_ed6c_4413_bf47_5ed80038a7bd (complex): "PP2BCaMCa2", "Protein phosphatase 2B", "PP2B"
mwfaf786e2_00b7_4e0c_b164_5aa1f4ef6356 (complex): "PP2BCaM", "Protein phosphatase 2B", "PP2B"
mw2f3e9c55_e57f_416e_b4b1_cc49a26192c0 (protein): "D32p34", "DARPP-32", "DARPP32"
mw219e8fae_a38b_4620_8726_e6bd1829a351 (protein): "PDE4", "Phosphodiesterase 4", "PDE4"
mw24435476_9c30_4878_b26f_4b3c5a0685c6 (protein): "DARPP32", "Dopamine- and cAMP-regulated phosphoprotein", "DARPP-32"
totalActivePKA (unknown): "UNK"
Reason:
The model provided describes the interaction between neuromodulators via GPCRs and their effect on cAMP/PKA signaling in D1 neurons. Based on the display names and reactions, the entity types for each species can be determined.
Proteins are identified by their names, such as "Gai", "AC5", "PKA", and "DARPP32".
Complexes are identified by their composition, such as "AC5GaolfGTPGaiGTP" and "PP2BCaMCa2".
Chemicals are identified by their names, such as "DA", "ATP", "ACh", and "cAMP".
The unknown entity type is assigned to "totalActivePKA" as it does not have a clear display name or reaction.
The standardized names and synonyms are provided based on the display names and common names used in the field of biochemistry and molecular biology.
Synonyms dict: {'mwa2c44a01_28c9_4dbd_b034_364f9b5b6cc3': ['Gai', 'G protein alpha i', 'G alpha i'], 'mwdb9dc389_2bf0_4039_9f09_282f5511958b': ['D1RDA', 'D1 dopamine receptor', 'DRD1'], 'mwd794c746_c826_4ba1_9e09_a9d1e122d925': ['AC5GaolfGTPGaiGTP', 'Adenylate cyclase 5', 'AC5'], 'mw2075d2cf_955e_4150_98b8_847103c53845': ['AC5GaiGTP*ATP', 'Adenylate cyclase 5', 'AC5'], 'mw74e54eed_0d25_4fb0_b677_1192f238c03b': ['PKAcAMP2', 'Protein kinase A', 'PKA'], 'mw724f1afe_8032_40ae_96ca_808ab7b8b943': ['AC5', 'Adenylate cyclase 5', 'AC'], 'mwd8ea533a_c66e_4de4_8c5c_0d4201d8c8a2': ['Gi', 'G protein alpha i', 'G alpha i'], 'mwbe974953_e869_4622_b4a8_745555c8d7fd': ['DA', 'Dopamine', '3,4-Dihydroxyphenethylamine'], 'mw56dff932_134c_4d88_a611_daad00623fd0': ['AC5CaGaiGTP*ATP', 'Adenylate cyclase 5', 'AC5'], 'mw1f3b8982_3b8c_42b6_8b0f_49b037cbda43': ['PDE10c*cAMP', 'Phosphodiesterase 10A', 'PDE10A'], 'mw68d3f409_9462_4515_8c07_bc105fa0eaf1': ['PKAc', 'Protein kinase A', 'PKA'], 'mw9bcba6bc_9788_4f7f_afb5_1c8f3b33c3d1': ['GaiGDP', 'G protein alpha i', 'G alpha i'], 'mw8e34c23f_1891_4dc9_8f97_dc2f12a1706c': ['GaolfGTP', 'G protein alpha olf', 'G alpha olf'], 'mw0b46978f_b522_4cde_97f0_574cd7dbbae7': ['D1RGolf', 'D1 dopamine receptor', 'DRD1'], 'mw9710c658_a2a1_4f49_b494_af109853f251': ['AMP', 'Adenosine monophosphate', 'Adenylate'], 'mwc783c5e7_7bc8_425a_9bb6_1f01d463365c': ['PKA', 'Protein kinase A', 'PKA'], 'mwffd5a553_8e03_443d_a67e_0cf39d03f89f': ['PKAcAMP4', 'Protein kinase A', 'PKA'], 'mw4b358131_010c_4545_ac4a_13a6c8bc34c4': ['CaM', 'Calmodulin', 'CaM'], 'mw25023179_9334_438e_bf3e_4e850f84406a': ['PP2B', 'Protein phosphatase 2B', 'PP2B'], 'mw3d9e6efb_8e12_49c9_a87f_e067914b951d': ['PDE10', 'Phosphodiesterase 10A', 'PDE10A'], 'mwfaf786e2_00b7_4e0c_b164_5aa1f4ef6356': ['PP2BCaM', 'Protein phosphatase 2B', 'PP2B'], 'mw166e3335_56c3_41ef_af0f_b583860991c1': ['AC5GaolfGTP*ATP', 'Adenylate cyclase 5', 'AC5'], 'mwfe9ed415_d5af_469c_a549_d8981f1eb01f': ['AC5GaolfGTP', 'Adenylate cyclase 5', 'AC5'], 'mw24435476_9c30_4878_b26f_4b3c5a0685c6': ['DARPP32', 'Dopamine- and cAMP-regulated phosphoprotein', 'DARPP-32'], 'mwd1171b65_ed6c_4413_bf47_5ed80038a7bd': ['PP2BCaMCa2', 'Protein phosphatase 2B', 'PP2B'], 'mw2f3e9c55_e57f_416e_b4b1_cc49a26192c0': ['D32p34', 'DARPP-32', 'DARPP32'], 'mw619502c3_e319_4e29_a677_b2b5f74fc2cf': ['AC5Ca*ATP', 'Adenylate cyclase 5', 'AC5'], 'mwe2fc02e6_2684_4071_932a_f7a8bd13b2fe': ['D1R', 'D1 dopamine receptor', 'DRD1'], 'mw9bfd7713_4c48_492c_8583_006bf1b54a1b': ['B72PP2ACa*D32p75', 'Protein phosphatase 2A', 'PP2A'], 'mw29ba9e7c_6865_4817_8775_be2dbc29651e': ['AC5GaiGTP', 'Adenylate cyclase 5', 'AC5'], 'mw522cacf1_5e61_4b95_8742_cf61cb824893': ['B72PP2A', 'Protein phosphatase 2A', 'PP2A'], 'mw42919ead_5972_4151_85ac_fcc88ca105a6': ['AC5CaGaolfGTP', 'Adenylate cyclase 5', 'AC5'], 'mw8a4a0733_64dd_4474_9aaf_7d750b27ae5b': ['CaMCa4', 'Calmodulin', 'CaM'], 'mw0a10f9cb_3f4b_4bfa_ace9_0ecd2bd74b5e': ['AC5GaolfGTPGaiGTP*ATP', 'Adenylate cyclase 5', 'AC5'], 'mw1184c368_03fc_435a_9086_dc6ed3067935': ['D32p75', 'DARPP-32', 'DARPP32'], 'mw7086a13a_619e_4069_b163_d8a05fc55f42': ['AC5*ATP', 'Adenylate cyclase 5', 'AC5'], 'mwe4e36b8e_18b8_4c76_bd46_13614b71da5c': ['M4RAChGi', 'Muscarinic acetylcholine receptor M4', 'M4R'], 'mwbae3bd11_0ab4_4587_a931_9c5dc5e777ba': ['AC5CaGaolfGTP*ATP', 'Adenylate cyclase 5', 'AC5'], 'mw3fcd1ec2_a459_49d4_89f7_361e276096d6': ['B72PPA2Ca', 'Protein phosphatase 2A', 'PP2A'], 'mw6e845d87_603e_4463_874d_866f554303df': ['PDE10*cAMP', 'Phosphodiesterase 10A', 'PDE10A'], 'mw46dccec6_6f0f_40f6_a10c_2f34ae7a005a': ['ATP', 'Adenosine triphosphate', 'Adenylate'], 'mwed1b3928_8d78_44d1_aee7_9d11d6437cfc': ['AC5CaGaiGTP', 'Adenylate cyclase 5', 'AC5'], 'mw8825a609_0983_4fb4_a264_e2f7e43d17b3': ['B72PP2ACa*D32p34', 'Protein phosphatase 2A', 'PP2A'], 'mwf46d3666_f0f3_4f05_9603_d7e6bb69005e': ['PDE4*cAMP', 'Phosphodiesterase 4', 'PDE4'], 'mwd86ce0dc_7329_4b27_9de0_ee6bffee3083': ['M4RGi', 'Muscarinic acetylcholine receptor M4', 'M4R'], 'mwf82770b9_766a_4c4e_851a_d76da19e8517': ['M4R', 'Muscarinic acetylcholine receptor M4', 'M4R'], 'mw2badefa3_32e8_4b66_9e69_245d9ec74e33': ['AC5CaGaolfGTPGaiGTP', 'Adenylate cyclase 5', 'AC5'], 'mwb80e4fa1_4849_4ed5_b3b0_3e3025c61ad8': ['Gbgi', 'G protein beta gamma', 'G beta gamma'], 'mw3e1a2fbf_37b1_490c_9528_6cb6bbf11b21': ['ACh', 'Acetylcholine', 'ACh'], 'mw1c97b02d_169a_4eb8_bc84_1be57c51a255': ['cAMP', 'Cyclic adenosine monophosphate', 'cAMP'], 'mwccd3a17c_e207_4663_9b16_327b78882497': ['Ca', 'Calcium', 'Ca2+'], 'mwfed0682b_39f1_4b09_94e8_c45a51744092': ['GaolfGDP', 'G protein alpha olf', 'G alpha olf'], 'mw6b2f1c44_e0be_4406_bcef_ad5061d519e4': ['D1RDAGolf', 'D1 dopamine receptor', 'DRD1'], 'mw7df45520_98cc_4c0b_91a7_c6e7297de98a': ['AC5Ca', 'Adenylate cyclase 5', 'AC5'], 'mw07c7392b_8d89_4b94_97c5_59f7e256b6f2': ['AC5CaGaolfGTPGaiGTP*ATP', 'Adenylate cyclase 5', 'AC5'], 'mw65a14789_ffcf_4bfd_9d53_d2eb2f4d0896': ['CaMCa2', 'Calmodulin', 'CaM'], 'mw4855b1cd_d7bc_4072_9736_dca30bbe448d': ['PP2Bc', 'Protein phosphatase 2B', 'PP2B'], 'mw219e8fae_a38b_4620_8726_e6bd1829a351': ['PDE4', 'Phosphodiesterase 4', 'PDE4'], 'totalActivePKA': ['UNK']}
Evaluating 636/1075: BIOMD0000000636.xml

2025-11-20 13:16:28,551 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000636.txt
LLM response:
mwa2c44a01_28c9_4dbd_b034_364f9b5b6cc3 (protein): "G protein", "GTP-binding protein", "Gai"
mwfed0682b_39f1_4b09_94e8_c45a51744092 (protein): "Gaolf", "Golf protein", "Golf subunit"
mw8e34c23f_1891_4dc9_8f97_dc2f12a1706c (protein): "GaolfGTP", "Golf-GTP", "GTP-bound Golf"
mw1c97b02d_169a_4eb8_bc84_1be57c51a255 (chemical): "cAMP", "cyclic AMP", "adenosine 3',5'-cyclic monophosphate"
mwccd3a17c_e207_4663_9b16_327b78882497 (chemical): "Ca2+", "calcium ion", "calcium"
mwfe9ed415_d5af_469c_a549_d8981f1eb01f (protein): "AC5GaolfGTP", "adenylyl cyclase 5", "AC5"
mw65a14789_ffcf_4bfd_9d53_d2eb2f4d0896 (protein): "CaMCa2", "calmodulin", "CaM"
mw8a4a0733_64dd_4474_9aaf_7d750b27ae5b (protein): "CaMCa4", "calmodulin", "CaM"
mw74e54eed_0d25_4fb0_b677_1192f238c03b (protein): "PKAcAMP2", "protein kinase A", "PKA"
mwffd5a553_8e03_443d_a67e_0cf39d03f89f (protein): "PKAcAMP4", "protein kinase A", "PKA"
mwd1171b65_ed6c_4413_bf47_5ed80038a7bd (protein): "PP2BCaMCa2", "protein phosphatase 2B", "PP2B"
mw3fcd1ec2_a459_49d4_89f7_361e276096d6 (protein): "B72PPA2Ca", "protein phosphatase 2A", "PP2A"
mw9bfd7713_4c48_492c_8583_006bf1b54a1b (protein): "B72PP2ACaD32p75", "protein phosphatase 2A", "PP2A"
mwbe974953_e869_4622_b4a8_745555c8d7fd (chemical): "Adn", "adenosine", "adenosine molecule"
mw7df45520_98cc_4c0b_91a7_c6e7297de98a (protein): "AC5Ca", "adenylyl cyclase 5", "AC5"
mw46dccec6_6f0f_40f6_a10c_2f34ae7a005a (chemical): "ATP", "adenosine triphosphate", "ATP molecule"
mwed1b3928_8d78_44d1_aee7_9d11d6437cfc (protein): "AC5CaGaiGTP", "adenylyl cyclase 5", "AC5"
mw8825a609_0983_4fb4_a264_e2f7e43d17b3 (protein): "B72PP2ACaD32p34", "protein phosphatase 2A", "PP2A"
mwf46d3666_f0f3_4f05_9603_d7e6bb69005e (protein): "PDE4cAMP", "phosphodiesterase 4", "PDE4"
mwd794c746_c826_4ba1_9e09_a9d1e122d925 (protein): "AC5GaolfGTPGaiGTP", "adenylyl cyclase 5", "AC5"
mw2badefa3_32e8_4b66_9e69_245d9ec74e33 (protein): "AC5CaGaolfGTPGaiGTP", "adenylyl cyclase 5", "AC5"
mw9d5c5c9d_301d_4e43_ba7b_7d21ccbdc2c2 (protein): "D2RDA", "dopamine receptor D2", "D2R"
mwe4e36b8e_18b8_4c76_bd46_13614b71da5c (protein): "D2RDAGi", "dopamine receptor D2", "D2R"
mw3e1a2fbf_37b1_490c_9528_6cb6bbf11b21 (chemical): "DA", "dopamine", "dopamine molecule"
mw6e845d87_603e_4463_874d_866f554303df (protein): "PDE10cAMP", "phosphodiesterase 10", "PDE10"
mw1f3b8982_3b8c_42b6_8b0f_49b037cbda43 (protein): "PDE10ccAMP", "phosphodiesterase 10", "PDE10"
mw0a10f9cb_3f4b_4bfa_ace9_0ecd2bd74b5e (protein): "AC5GaolfGTPGaiGTPATP", "adenylyl cyclase 5", "AC5"
mw2075d2cf_955e_4150_98b8_847103c53845 (protein): "AC5GaiGTPATP", "adenylyl cyclase 5", "AC5"
mw166e3335_56c3_41ef_af0f_b583860991c1 (protein): "AC5GaolfGTPATP", "adenylyl cyclase 5", "AC5"
mw7086a13a_619e_4069_b163_d8a05fc55f42 (protein): "AC5ATP", "adenylyl cyclase 5", "AC5"
mwbae3bd11_0ab4_4587_a931_9c5dc5e777ba (protein): "AC5CaGaolfGTPATP", "adenylyl cyclase 5", "AC5"
mw56dff932_134c_4d88_a611_daad00623fd0 (protein): "AC5CaGaiGTPATP", "adenylyl cyclase 5", "AC5"
mw07c7392b_8d89_4b94_97c5_59f7e256b6f2 (protein): "AC5CaGaolfGTPGaiGTPATP", "adenylyl cyclase 5", "AC5"
mw619502c3_e319_4e29_a677_b2b5f74fc2cf (protein): "AC5CaATP", "adenylyl cyclase 5", "AC5"
A2ARAdnGolf (protein): "A2A receptor", "adenosine receptor A2A", "A2AR"
A2ARAdn (protein): "A2A receptor", "adenosine receptor A2A", "A2AR"
totalActivePKA (protein): "protein kinase A", "PKA", "active PKA"
Reason: Based on the model description and reaction equations, most species are proteins or chemicals involved in the signaling pathways. The entity types are determined by the species' roles in the reactions and their display names. For example, mwa2c44a01_28c9_4dbd_b034_364f9b5b6cc3 is a protein because it is involved in a reaction with another protein (mw7df45520_98cc_4c0b_91a7_c6e7297de98a) and has a display name "GaiGTP", indicating it is a G protein. Similarly, mw1c97b02d_169a_4eb8_bc84_1be57c51a255 is a chemical because it is involved in a reaction with a protein (mw74e54eed_0d25_4fb0_b677_1192f238c03b) and has a display name "cAMP", indicating it is a cyclic AMP molecule.
Synonyms dict: {'mwa2c44a01_28c9_4dbd_b034_364f9b5b6cc3': ['G protein', 'GTP-binding protein', 'Gai'], 'mwfed0682b_39f1_4b09_94e8_c45a51744092': ['Gaolf', 'Golf protein', 'Golf subunit'], 'mw8e34c23f_1891_4dc9_8f97_dc2f12a1706c': ['GaolfGTP', 'Golf-GTP', 'GTP-bound Golf'], 'mw1c97b02d_169a_4eb8_bc84_1be57c51a255': ['cAMP', 'cyclic AMP', "adenosine 3',5'-cyclic monophosphate"], 'mwccd3a17c_e207_4663_9b16_327b78882497': ['Ca2+', 'calcium ion', 'calcium'], 'mwfe9ed415_d5af_469c_a549_d8981f1eb01f': ['AC5GaolfGTP', 'adenylyl cyclase 5', 'AC5'], 'mw65a14789_ffcf_4bfd_9d53_d2eb2f4d0896': ['CaMCa2', 'calmodulin', 'CaM'], 'mw8a4a0733_64dd_4474_9aaf_7d750b27ae5b': ['CaMCa4', 'calmodulin', 'CaM'], 'mw74e54eed_0d25_4fb0_b677_1192f238c03b': ['PKAcAMP2', 'protein kinase A', 'PKA'], 'mwffd5a553_8e03_443d_a67e_0cf39d03f89f': ['PKAcAMP4', 'protein kinase A', 'PKA'], 'mwd1171b65_ed6c_4413_bf47_5ed80038a7bd': ['PP2BCaMCa2', 'protein phosphatase 2B', 'PP2B'], 'mw3fcd1ec2_a459_49d4_89f7_361e276096d6': ['B72PPA2Ca', 'protein phosphatase 2A', 'PP2A'], 'mw9bfd7713_4c48_492c_8583_006bf1b54a1b': ['B72PP2ACaD32p75', 'protein phosphatase 2A', 'PP2A'], 'mwbe974953_e869_4622_b4a8_745555c8d7fd': ['Adn', 'adenosine', 'adenosine molecule'], 'mw7df45520_98cc_4c0b_91a7_c6e7297de98a': ['AC5Ca', 'adenylyl cyclase 5', 'AC5'], 'mw46dccec6_6f0f_40f6_a10c_2f34ae7a005a': ['ATP', 'adenosine triphosphate', 'ATP molecule'], 'mwed1b3928_8d78_44d1_aee7_9d11d6437cfc': ['AC5CaGaiGTP', 'adenylyl cyclase 5', 'AC5'], 'mw8825a609_0983_4fb4_a264_e2f7e43d17b3': ['B72PP2ACaD32p34', 'protein phosphatase 2A', 'PP2A'], 'mwf46d3666_f0f3_4f05_9603_d7e6bb69005e': ['PDE4cAMP', 'phosphodiesterase 4', 'PDE4'], 'mwd794c746_c826_4ba1_9e09_a9d1e122d925': ['AC5GaolfGTPGaiGTP', 'adenylyl cyclase 5', 'AC5'], 'mw2badefa3_32e8_4b66_9e69_245d9ec74e33': ['AC5CaGaolfGTPGaiGTP', 'adenylyl cyclase 5', 'AC5'], 'mw9d5c5c9d_301d_4e43_ba7b_7d21ccbdc2c2': ['D2RDA', 'dopamine receptor D2', 'D2R'], 'mwe4e36b8e_18b8_4c76_bd46_13614b71da5c': ['D2RDAGi', 'dopamine receptor D2', 'D2R'], 'mw3e1a2fbf_37b1_490c_9528_6cb6bbf11b21': ['DA', 'dopamine', 'dopamine molecule'], 'mw6e845d87_603e_4463_874d_866f554303df': ['PDE10cAMP', 'phosphodiesterase 10', 'PDE10'], 'mw1f3b8982_3b8c_42b6_8b0f_49b037cbda43': ['PDE10ccAMP', 'phosphodiesterase 10', 'PDE10'], 'mw0a10f9cb_3f4b_4bfa_ace9_0ecd2bd74b5e': ['AC5GaolfGTPGaiGTPATP', 'adenylyl cyclase 5', 'AC5'], 'mw2075d2cf_955e_4150_98b8_847103c53845': ['AC5GaiGTPATP', 'adenylyl cyclase 5', 'AC5'], 'mw166e3335_56c3_41ef_af0f_b583860991c1': ['AC5GaolfGTPATP', 'adenylyl cyclase 5', 'AC5'], 'mw7086a13a_619e_4069_b163_d8a05fc55f42': ['AC5ATP', 'adenylyl cyclase 5', 'AC5'], 'mwbae3bd11_0ab4_4587_a931_9c5dc5e777ba': ['AC5CaGaolfGTPATP', 'adenylyl cyclase 5', 'AC5'], 'mw56dff932_134c_4d88_a611_daad00623fd0': ['AC5CaGaiGTPATP', 'adenylyl cyclase 5', 'AC5'], 'mw07c7392b_8d89_4b94_97c5_59f7e256b6f2': ['AC5CaGaolfGTPGaiGTPATP', 'adenylyl cyclase 5', 'AC5'], 'mw619502c3_e319_4e29_a677_b2b5f74fc2cf': ['AC5CaATP', 'adenylyl cyclase 5', 'AC5'], 'A2ARAdnGolf': ['A2A receptor', 'adenosine receptor A2A', 'A2AR'], 'A2ARAdn': ['A2A receptor', 'adenosine receptor A2A', 'A2AR'], 'totalActivePKA': ['protein kinase A', 'PKA', 'active PKA']}
Evaluating 637/1075: BIOMD0000000637.xml

2025-11-20 13:16:31,870 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000637.txt
LLM response:
Gt (protein): "G protein", "Gt protein", "G alpha subunit"
Gd (protein): "Gd protein", "G alpha subunit GDP-bound", "inactive G protein"
LRGt (complex): "LRGt complex", "G protein-LR complex", "activated G protein-LR complex"
RGd (complex): "RGd complex", "R-Gd complex", "receptor-G protein complex"
RGt (complex): "RGt complex", "R-Gt complex", "activated receptor-G protein complex"
LRGd (complex): "LRGd complex", "LR-Gd complex", "inactive G protein-LR complex"
Reason: The model is a simplified carrousel model of GPCR, which involves G protein-coupled receptors and their interactions with G proteins and ligands. The species names and reactions suggest that Gt and Gd are different states of the G protein, with Gt being the active form and Gd being the inactive form. LRGt and LRGd are likely complexes between the G protein and a ligand or regulator (LR), while RGt and RGd are complexes between the receptor (R) and the G protein. The reactions and notes suggest that these complexes play a crucial role in the signaling pathway, with the G protein and its interactions with the receptor and ligand/regulator being key components.
Synonyms dict: {'Gt': ['G protein', 'Gt protein', 'G alpha subunit'], 'Gd': ['Gd protein', 'G alpha subunit GDP-bound', 'inactive G protein'], 'LRGt': ['LRGt complex', 'G protein-LR complex', 'activated G protein-LR complex'], 'RGd': ['RGd complex', 'R-Gd complex', 'receptor-G protein complex'], 'RGt': ['RGt complex', 'R-Gt complex', 'activated receptor-G protein complex'], 'LRGd': ['LRGd complex', 'LR-Gd complex', 'inactive G protein-LR complex']}
Evaluating 638/1075: BIOMD0000000638.xml

2025-11-20 13:16:35,821 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:16:36,025 - WARNING - Skipping BIOMD0000000639.xml - no results generated
2025-11-20 13:16:36,039 - WARNING - Skipping BIOMD0000000640.xml - no results generated
2025-11-20 13:16:36,045 - WARNING - Skipping BIOMD0000000641.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000638.txt
LLM response:
Gt (protein): "G protein alpha subunit", "Gt protein", "G alpha t"
Gd (protein): "G protein alpha subunit inactive", "Gd protein", "G alpha d"
LRGt (complex): "LRGt complex", "G protein coupled receptor complex", "LR-Gt complex"
RGd (complex): "RGd complex", "G protein coupled receptor complex", "R-Gd complex"
RGt (complex): "RGt complex", "G protein coupled receptor complex", "R-Gt complex"
LRGd (complex): "LRGd complex", "G protein coupled receptor complex", "LR-Gd complex"
LRrgsGt (complex): "LRrgsGt complex", "G protein coupled receptor-RGS complex", "LR-rgs-Gt complex"
RrgsGd (complex): "RrgsGd complex", "G protein coupled receptor-RGS complex", "R-rgs-Gd complex"
LRrgsGd (complex): "LRrgsGd complex", "G protein coupled receptor-RGS complex", "LR-rgs-Gd complex"
RrgsGt (complex): "RrgsGt complex", "G protein coupled receptor-RGS complex", "R-rgs-Gt complex"

Reason: The species are identified based on the context of the GPCR-RGS model, where Gt and Gd are likely G protein alpha subunits, and the other species are complexes formed between G proteins, receptors, and RGS proteins. The entity types are determined based on the composition of each species, with proteins being individual subunits and complexes being combinations of multiple subunits. The standardized names and synonyms are chosen based on common terminology in the field of GPCR signaling and RGS proteins.
Synonyms dict: {'Gt': ['G protein alpha subunit', 'Gt protein', 'G alpha t'], 'Gd': ['G protein alpha subunit inactive', 'Gd protein', 'G alpha d'], 'LRGt': ['LRGt complex', 'G protein coupled receptor complex', 'LR-Gt complex'], 'RGd': ['RGd complex', 'G protein coupled receptor complex', 'R-Gd complex'], 'RGt': ['RGt complex', 'G protein coupled receptor complex', 'R-Gt complex'], 'LRGd': ['LRGd complex', 'G protein coupled receptor complex', 'LR-Gd complex'], 'LRrgsGt': ['LRrgsGt complex', 'G protein coupled receptor-RGS complex', 'LR-rgs-Gt complex'], 'RrgsGd': ['RrgsGd complex', 'G protein coupled receptor-RGS complex', 'R-rgs-Gd complex'], 'LRrgsGd': ['LRrgsGd complex', 'G protein coupled receptor-RGS complex', 'LR-rgs-Gd complex'], 'RrgsGt': ['RrgsGt complex', 'G protein coupled receptor-RGS complex', 'R-rgs-Gt complex']}
Evaluating 639/1075: BIOMD0000000639.xml
Evaluating 640/1075: BIOMD0000000640.xml
Evaluating 641/1075: BIOMD0000000641.xml
Evaluating 642/1075: BIOMD0000000642.xml

2025-11-20 13:16:37,426 - WARNING - Skipping BIOMD0000000643.xml - no results generated
2025-11-20 13:16:37,434 - WARNING - Skipping BIOMD0000000644.xml - no results generated
2025-11-20 13:16:37,442 - WARNING - Skipping BIOMD0000000645.xml - no results generated
2025-11-20 13:16:37,461 - WARNING - Skipping BIOMD0000000646.xml - no results generated
2025-11-20 13:16:37,469 - WARNING - Skipping BIOMD0000000647.xml - no results generated
2025-11-20 13:16:37,504 - WARNING - Skipping BIOMD0000000648.xml - no results generated
2025-11-20 13:16:37,511 - WARNING - Skipping BIOMD0000000650.xml - no results generated
2025-11-20 13:16:37,524 - WARNING - Skipping BIOMD0000000651.xml - no results generated
2025-11-20 13:16:37,560 - WARNING - Skipping BIOMD0000000652.xml - no results generated
2025-11-20 13:16:37,594 - WARNING - Skipping BIOMD0000000653.xml - no results generated
2025-11-20 13:16:37,629 - WARNING - Skipping BIOMD0000000654.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000642.txt
LLM response:
E (chemical): "estrogen", "estradiol", "17β-estradiol"
Reason: The species E is identified as "estrogen" in the display names, and estrogen is a type of chemical hormone. The synonyms provided are common names for estrogen, with estradiol being a specific type of estrogen and 17β-estradiol being a more precise chemical name.
Synonyms dict: {'E': ['estrogen', 'estradiol', '17β-estradiol']}
Evaluating 643/1075: BIOMD0000000643.xml
Evaluating 644/1075: BIOMD0000000644.xml
Evaluating 645/1075: BIOMD0000000645.xml
Evaluating 646/1075: BIOMD0000000646.xml
Evaluating 647/1075: BIOMD0000000647.xml
Evaluating 648/1075: BIOMD0000000648.xml
Evaluating 649/1075: BIOMD0000000650.xml
Evaluating 650/1075: BIOMD0000000651.xml
Evaluating 651/1075: BIOMD0000000652.xml
Evaluating 652/1075: BIOMD0000000653.xml
Evaluating 653/1075: BIOMD0000000654.xml

2025-11-20 13:16:37,666 - WARNING - Skipping BIOMD0000000655.xml - no results generated
2025-11-20 13:16:37,701 - WARNING - Skipping BIOMD0000000656.xml - no results generated
2025-11-20 13:16:37,707 - WARNING - Skipping BIOMD0000000657.xml - no results generated

Evaluating 654/1075: BIOMD0000000655.xml
Evaluating 655/1075: BIOMD0000000656.xml
Evaluating 656/1075: BIOMD0000000657.xml
Evaluating 657/1075: BIOMD0000000658.xml

2025-11-20 13:16:39,283 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000658.txt
LLM response:
TCF (protein): "T-cell factor", "transcription factor 7", "TCF-1"
B_catenin_TCF (complex): "beta-catenin/TCF complex", "TCF/beta-catenin complex", "CTNNB1/TCF complex"
Reason: TCF is a transcription factor, which is a type of protein, and B_catenin_TCF is a complex formed by the interaction of beta-catenin and TCF, as indicated by the reaction B_catenin_0 + TCF -> B_catenin_TCF, suggesting a protein-protein interaction.
Synonyms dict: {'TCF': ['T-cell factor', 'transcription factor 7', 'TCF-1'], 'B_catenin_TCF': ['beta-catenin/TCF complex', 'TCF/beta-catenin complex', 'CTNNB1/TCF complex']}
Evaluating 658/1075: BIOMD0000000659.xml

2025-11-20 13:16:40,284 - WARNING - Skipping BIOMD0000000660.xml - no results generated
2025-11-20 13:16:40,298 - WARNING - Skipping BIOMD0000000661.xml - no results generated
2025-11-20 13:16:40,307 - WARNING - Skipping BIOMD0000000662.xml - no results generated
2025-11-20 13:16:40,313 - WARNING - Skipping BIOMD0000000663.xml - no results generated
2025-11-20 13:16:40,324 - WARNING - Skipping BIOMD0000000664.xml - no results generated
2025-11-20 13:16:40,337 - WARNING - Skipping BIOMD0000000665.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000659.txt
LLM response:
Ca (chemical): "calcium", "Ca2+", "calcium ion"
Reason: The species Ca is likely to be calcium, a chemical element, due to the mention of "calcium signaling" in the model notes, which suggests that Ca refers to the calcium ion playing a role in the signaling pathway.
Synonyms dict: {'Ca': ['calcium', 'Ca2+', 'calcium ion']}
Evaluating 659/1075: BIOMD0000000660.xml
Evaluating 660/1075: BIOMD0000000661.xml
Evaluating 661/1075: BIOMD0000000662.xml
Evaluating 662/1075: BIOMD0000000663.xml
Evaluating 663/1075: BIOMD0000000664.xml
Evaluating 664/1075: BIOMD0000000665.xml
Evaluating 665/1075: BIOMD0000000666.xml

2025-11-20 13:16:41,719 - WARNING - Skipping BIOMD0000000667.xml - no results generated
2025-11-20 13:16:41,731 - WARNING - Skipping BIOMD0000000668.xml - no results generated
2025-11-20 13:16:41,747 - WARNING - Skipping BIOMD0000000669.xml - no results generated
2025-11-20 13:16:41,750 - WARNING - Skipping BIOMD0000000670.xml - no results generated
2025-11-20 13:16:41,755 - WARNING - Skipping BIOMD0000000671.xml - no results generated
2025-11-20 13:16:41,760 - WARNING - Skipping BIOMD0000000672.xml - no results generated
2025-11-20 13:16:41,768 - WARNING - Skipping BIOMD0000000673.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000666.txt
LLM response:
Dabrafenib (chemical): "Dabrafenib", "GSK2118436", "Tafinlar"
Reason: Dabrafenib is a known chemical entity, specifically a drug used in the treatment of melanoma, which is consistent with the context of the PI3K/AKT and MAPK signaling pathways in melanoma cancer model. The synonyms provided are the generic name, a research code, and a trade name, respectively.
Synonyms dict: {'Dabrafenib': ['Dabrafenib', 'GSK2118436', 'Tafinlar']}
Evaluating 666/1075: BIOMD0000000667.xml
Evaluating 667/1075: BIOMD0000000668.xml
Evaluating 668/1075: BIOMD0000000669.xml
Evaluating 669/1075: BIOMD0000000670.xml
Evaluating 670/1075: BIOMD0000000671.xml
Evaluating 671/1075: BIOMD0000000672.xml
Evaluating 672/1075: BIOMD0000000673.xml
Evaluating 673/1075: BIOMD0000000674.xml

2025-11-20 13:16:56,830 - WARNING - Skipping BIOMD0000000675.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000674.txt
LLM response:
b_met (chemical): "methionine", "L-methionine", "L-Met"
b_ser (chemical): "serine", "L-serine", "L-Ser"
b_gly (chemical): "glycine", "L-glycine", "L-Gly"
b_glu (chemical): "glutamate", "L-glutamate", "L-Glu"
b_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
b_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
b_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
GAR (chemical): "glycinamide ribonucleotide", "GAR", "phosphoribosylglycinamide"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
BET (chemical): "betaine", "trimethylglycine", "TMG"
DUMP (chemical): "deoxyuridine monophosphate", "dUMP", "deoxyuridylate"
H2O2 (chemical): "hydrogen peroxide", "H2O2", "peroxide"
c_thf (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
c_5mf (chemical): "5-methyltetrahydrofolate", "5-MTHF", "L-methylfolate"
c_2cf (chemical): "5,10-methylenetetrahydrofolate", "5,10-MTHF", "methylenetetrahydrofolate"
c_10f (chemical): "10-formyltetrahydrofolate", "10-CHO-THF", "formyltetrahydrofolate"
c_dhf (chemical): "dihydrofolate", "DHF", "7,8-dihydrofolate"
aic (chemical): "5-aminoimidazole-4-carboxamide ribonucleotide", "AICAR", "ZMP"
c_glu (chemical): "glutamate", "L-glutamate", "L-Glu"
c_cys (chemical): "cysteine", "L-cysteine", "L-Cys"
c_gly (chemical): "glycine", "L-glycine", "L-Gly"
c_gsg (chemical): "glutathione disulfide", "GSSG", "oxidized glutathione"
c_gsh (chemical): "glutathione", "GSH", "reduced glutathione"
hcy (chemical): "homocysteine", "L-homocysteine", "L-Hcy"
c_ser (chemical): "serine", "L-serine", "L-Ser"
sah (chemical): "S-adenosylhomocysteine", "SAH", "AdoHcy"
sam (chemical): "S-adenosylmethionine", "SAM", "AdoMet"
met (chemical): "methionine", "L-methionine", "L-Met"
c_coo (chemical): "formate", "formic acid", "HCOOH"
species_1 (chemical): "decarnitine", "dcSAM", "decarnitine-SAM"
species_2 (chemical): "putrescine", "1,4-diaminobutane", "PUT"
species_3 (chemical): "spermine", "1,12-diamino-4,9-diazadodecane", "SPM"
species_4 (chemical): "spermidine", "1,8-diamino-4-azaoctane", "SPD"
species_5 (chemical): "acetylspermine", "N-acetylspermine", "AcSPM"
species_6 (chemical): "acetylspermidine", "N-acetylspermidine", "AcSPD"
species_7 (chemical): "ornithine", "L-ornithine", "L-Orn"
species_8 (chemical): "acetyl-CoA", "acetyl coenzyme A", "AcCoA"
species_9 (chemical): "CoA", "coenzyme A", "CoASH"
CO (chemical): "carbon dioxide", "CO2", "carbonic acid"
m_thf (chemical): "tetrahydrofolate", "THF", "tetrahydrofolic acid"
m_2cf (chemical): "5,10-methylenetetrahydrofolate", "5,10-MTHF", "methylenetetrahydrofolate"
m_10f (chemical): "10-formyltetrahydrofolate", "10-CHO-THF", "formyltetrahydrofolate"
m_ser (chemical): "serine", "L-serine", "L-Ser"
m_gly (chemical): "glycine", "L-glycine", "L-Gly"
m_coo (chemical): "formate", "formic acid", "HCOOH"
Fol (chemical): "folic acid", "vitamin B9", "pteroylglutamic acid"
HCHO (chemical): "formaldehyde", "methanal", "HCHO"
src (chemical): "sarcosine", "N-methylglycine", "MGL"
dmg (chemical): "dimethylglycine", "DMG", "N,N-dimethylglycine"
glc (chemical): "glutamylcysteine", "gamma-glutamylcysteine", "GluCys"
c_1cf (chemical): "5,10-methenyltetrahydrofolate", "5,10-MTHF", "methenyltetrahydrofolate"
m_1cf (chemical): "5,10-methenyltetrahydrofolate", "5,10-MTHF", "methenyltetrahydrofolate"

Reason: All species are identified as chemicals based on their involvement in metabolic reactions and their names, which are consistent with biochemical nomenclature. The standardized names and synonyms provided are based on common usage in biochemistry and metabolism.
Synonyms dict: {'b_met': ['methionine', 'L-methionine', 'L-Met'], 'b_ser': ['serine', 'L-serine', 'L-Ser'], 'b_gly': ['glycine', 'L-glycine', 'L-Gly'], 'b_glu': ['glutamate', 'L-glutamate', 'L-Glu'], 'b_cys': ['cysteine', 'L-cysteine', 'L-Cys'], 'b_gsg': ['glutathione disulfide', 'GSSG', 'oxidized glutathione'], 'b_gsh': ['glutathione', 'GSH', 'reduced glutathione'], 'GAR': ['glycinamide ribonucleotide', 'GAR', 'phosphoribosylglycinamide'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'BET': ['betaine', 'trimethylglycine', 'TMG'], 'DUMP': ['deoxyuridine monophosphate', 'dUMP', 'deoxyuridylate'], 'H2O2': ['hydrogen peroxide', 'H2O2', 'peroxide'], 'c_thf': ['tetrahydrofolate', 'THF', 'tetrahydrofolic acid'], 'c_5mf': ['5-methyltetrahydrofolate', '5-MTHF', 'L-methylfolate'], 'c_2cf': ['5,10-methylenetetrahydrofolate', '5,10-MTHF', 'methylenetetrahydrofolate'], 'c_10f': ['10-formyltetrahydrofolate', '10-CHO-THF', 'formyltetrahydrofolate'], 'c_dhf': ['dihydrofolate', 'DHF', '7,8-dihydrofolate'], 'aic': ['5-aminoimidazole-4-carboxamide ribonucleotide', 'AICAR', 'ZMP'], 'c_glu': ['glutamate', 'L-glutamate', 'L-Glu'], 'c_cys': ['cysteine', 'L-cysteine', 'L-Cys'], 'c_gly': ['glycine', 'L-glycine', 'L-Gly'], 'c_gsg': ['glutathione disulfide', 'GSSG', 'oxidized glutathione'], 'c_gsh': ['glutathione', 'GSH', 'reduced glutathione'], 'hcy': ['homocysteine', 'L-homocysteine', 'L-Hcy'], 'c_ser': ['serine', 'L-serine', 'L-Ser'], 'sah': ['S-adenosylhomocysteine', 'SAH', 'AdoHcy'], 'sam': ['S-adenosylmethionine', 'SAM', 'AdoMet'], 'met': ['methionine', 'L-methionine', 'L-Met'], 'c_coo': ['formate', 'formic acid', 'HCOOH'], 'species_1': ['decarnitine', 'dcSAM', 'decarnitine-SAM'], 'species_2': ['putrescine', '1,4-diaminobutane', 'PUT'], 'species_3': ['spermine', '1,12-diamino-4,9-diazadodecane', 'SPM'], 'species_4': ['spermidine', '1,8-diamino-4-azaoctane', 'SPD'], 'species_5': ['acetylspermine', 'N-acetylspermine', 'AcSPM'], 'species_6': ['acetylspermidine', 'N-acetylspermidine', 'AcSPD'], 'species_7': ['ornithine', 'L-ornithine', 'L-Orn'], 'species_8': ['acetyl-CoA', 'acetyl coenzyme A', 'AcCoA'], 'species_9': ['CoA', 'coenzyme A', 'CoASH'], 'CO': ['carbon dioxide', 'CO2', 'carbonic acid'], 'm_thf': ['tetrahydrofolate', 'THF', 'tetrahydrofolic acid'], 'm_2cf': ['5,10-methylenetetrahydrofolate', '5,10-MTHF', 'methylenetetrahydrofolate'], 'm_10f': ['10-formyltetrahydrofolate', '10-CHO-THF', 'formyltetrahydrofolate'], 'm_ser': ['serine', 'L-serine', 'L-Ser'], 'm_gly': ['glycine', 'L-glycine', 'L-Gly'], 'm_coo': ['formate', 'formic acid', 'HCOOH'], 'Fol': ['folic acid', 'vitamin B9', 'pteroylglutamic acid'], 'HCHO': ['formaldehyde', 'methanal', 'HCHO'], 'src': ['sarcosine', 'N-methylglycine', 'MGL'], 'dmg': ['dimethylglycine', 'DMG', 'N,N-dimethylglycine'], 'glc': ['glutamylcysteine', 'gamma-glutamylcysteine', 'GluCys'], 'c_1cf': ['5,10-methenyltetrahydrofolate', '5,10-MTHF', 'methenyltetrahydrofolate'], 'm_1cf': ['5,10-methenyltetrahydrofolate', '5,10-MTHF', 'methenyltetrahydrofolate']}
Evaluating 674/1075: BIOMD0000000675.xml
Evaluating 675/1075: BIOMD0000000676.xml

2025-11-20 13:17:02,483 - WARNING - Skipping BIOMD0000000677.xml - no results generated
2025-11-20 13:17:02,488 - WARNING - Skipping BIOMD0000000678.xml - no results generated
2025-11-20 13:17:02,495 - WARNING - Skipping BIOMD0000000679.xml - no results generated
2025-11-20 13:17:02,501 - WARNING - Skipping BIOMD0000000680.xml - no results generated
2025-11-20 13:17:02,507 - WARNING - Skipping BIOMD0000000681.xml - no results generated
2025-11-20 13:17:02,515 - WARNING - Skipping BIOMD0000000682.xml - no results generated
2025-11-20 13:17:02,522 - WARNING - Skipping BIOMD0000000683.xml - no results generated
2025-11-20 13:17:02,529 - WARNING - Skipping BIOMD0000000684.xml - no results generated
2025-11-20 13:17:02,534 - WARNING - Skipping BIOMD0000000685.xml - no results generated
2025-11-20 13:17:02,539 - WARNING - Skipping BIOMD0000000686.xml - no results generated
2025-11-20 13:17:02,552 - WARNING - Skipping BIOMD0000000687.xml - no results generated
2025-11-20 13:17:02,565 - WARNING - Skipping BIOMD0000000688.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000676.txt
LLM response:
Arg (chemical): "arginine", "L-arginine", "arg"
Fe3__enos (complex): "ferric enzyme complex", "Fe3+ enzyme complex", "oxidized enzyme complex"
Fe3__Arg (complex): "ferric arginine complex", "Fe3+ arginine complex", "arginine ferric complex"
Fe2 (chemical): "ferrous ion", "Fe2+ ion", "iron(II) ion"
Fe2__Arg (complex): "ferrous arginine complex", "Fe2+ arginine complex", "arginine ferrous complex"
Fe3__NO (complex): "ferric nitric oxide complex", "Fe3+ NO complex", "nitric oxide ferric complex"
NO (chemical): "nitric oxide", "nitrogen monoxide", "NO molecule"
Fe2__NO (complex): "ferrous nitric oxide complex", "Fe2+ NO complex", "nitric oxide ferrous complex"
Fe3__NOHA (complex): "ferric N-hydroxyarginine complex", "Fe3+ NOHA complex", "N-hydroxyarginine ferric complex"
Fe2__NOHA (complex): "ferrous N-hydroxyarginine complex", "Fe2+ NOHA complex", "N-hydroxyarginine ferrous complex"
O2 (chemical): "oxygen molecule", "dioxygen", "O2 molecule"
Fe3__O2__Arg (complex): "ferric oxygen arginine complex", "Fe3+ O2 arginine complex", "arginine ferric oxygen complex"
Fe3__O2__NOHA (complex): "ferric oxygen N-hydroxyarginine complex", "Fe3+ O2 NOHA complex", "N-hydroxyarginine ferric oxygen complex"
Citrulline (chemical): "L-citrulline", "citrulline amino acid", "2-amino-5-ureidopentanoic acid"
Reason: The entity types are determined based on the context of the model, which is related to nitric oxide release from endothelial cells. Arg, Fe2, NO, O2, and Citrulline are identified as chemicals as they are simple molecules or ions. The Fe3__ and Fe2__ species are identified as complexes as they represent iron ions bound to other molecules. The names and synonyms provided are based on common biochemical nomenclature and the context of the model.
Synonyms dict: {'Arg': ['arginine', 'L-arginine', 'arg'], 'Fe3__enos': ['ferric enzyme complex', 'Fe3+ enzyme complex', 'oxidized enzyme complex'], 'Fe3__Arg': ['ferric arginine complex', 'Fe3+ arginine complex', 'arginine ferric complex'], 'Fe2': ['ferrous ion', 'Fe2+ ion', 'iron(II) ion'], 'Fe2__Arg': ['ferrous arginine complex', 'Fe2+ arginine complex', 'arginine ferrous complex'], 'Fe3__NO': ['ferric nitric oxide complex', 'Fe3+ NO complex', 'nitric oxide ferric complex'], 'NO': ['nitric oxide', 'nitrogen monoxide', 'NO molecule'], 'Fe2__NO': ['ferrous nitric oxide complex', 'Fe2+ NO complex', 'nitric oxide ferrous complex'], 'Fe3__NOHA': ['ferric N-hydroxyarginine complex', 'Fe3+ NOHA complex', 'N-hydroxyarginine ferric complex'], 'Fe2__NOHA': ['ferrous N-hydroxyarginine complex', 'Fe2+ NOHA complex', 'N-hydroxyarginine ferrous complex'], 'O2': ['oxygen molecule', 'dioxygen', 'O2 molecule'], 'Fe3__O2__Arg': ['ferric oxygen arginine complex', 'Fe3+ O2 arginine complex', 'arginine ferric oxygen complex'], 'Fe3__O2__NOHA': ['ferric oxygen N-hydroxyarginine complex', 'Fe3+ O2 NOHA complex', 'N-hydroxyarginine ferric oxygen complex'], 'Citrulline': ['L-citrulline', 'citrulline amino acid', '2-amino-5-ureidopentanoic acid']}
Evaluating 676/1075: BIOMD0000000677.xml
Evaluating 677/1075: BIOMD0000000678.xml
Evaluating 678/1075: BIOMD0000000679.xml
Evaluating 679/1075: BIOMD0000000680.xml
Evaluating 680/1075: BIOMD0000000681.xml
Evaluating 681/1075: BIOMD0000000682.xml
Evaluating 682/1075: BIOMD0000000683.xml
Evaluating 683/1075: BIOMD0000000684.xml
Evaluating 684/1075: BIOMD0000000685.xml
Evaluating 685/1075: BIOMD0000000686.xml
Evaluating 686/1075: BIOMD0000000687.xml
Evaluating 687/1075: BIOMD0000000688.xml
Evaluating 688/1075: BIOMD0000000689.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000689.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
p_ABA (chemical): "p-aminobenzoate", "p-ABA", "4-aminobenzoic acid"
H2_Pteroate (chemical): "dihydropterote", "H2-pterote", "dihydropteroic acid"
L_Glutamate (chemical): "L-glutamic acid", "glutamate", "L-glutamate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
DHF (chemical): "dihydrofolate", "DHF", "7,8-dihydrofolate"
L_serine (chemical): "L-serine", "serine", "L-α-amino-β-hydroxypropionic acid"
Glycine (chemical): "glycine", "aminoacetic acid", "aminoethanoic acid"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced nicotinamide adenine dinucleotide phosphate"
CH2_THF (chemical): "5,10-methylenetetrahydrofolate", "CH2-THF", "5,10-methylene-THF"
Reason: All species are identified as chemicals because they are all metabolites or cofactors involved in the folate pathway model. The standardized names and synonyms are based on common biochemical nomenclature and the display names provided in the model.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'p_ABA': ['p-aminobenzoate', 'p-ABA', '4-aminobenzoic acid'], 'H2_Pteroate': ['dihydropterote', 'H2-pterote', 'dihydropteroic acid'], 'L_Glutamate': ['L-glutamic acid', 'glutamate', 'L-glutamate'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'DHF': ['dihydrofolate', 'DHF', '7,8-dihydrofolate'], 'L_serine': ['L-serine', 'serine', 'L-α-amino-β-hydroxypropionic acid'], 'Glycine': ['glycine', 'aminoacetic acid', 'aminoethanoic acid'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced nicotinamide adenine dinucleotide phosphate'], 'CH2_THF': ['5,10-methylenetetrahydrofolate', 'CH2-THF', '5,10-methylene-THF']}
Evaluating 689/1075: BIOMD0000000690.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000690.txt
LLM response:
ATP (chemical): "adenosine triphosphate", "ATP", "adenosine 5'-triphosphate"
AMP (chemical): "adenosine monophosphate", "AMP", "adenosine 5'-monophosphate"
p_ABA (chemical): "para-aminobenzoic acid", "p-ABA", "4-aminobenzoic acid"
H2_Pteroate (chemical): "dihydropterote", "H2-pterote", "pterotic acid"
L_Glutamate (chemical): "L-glutamic acid", "glutamate", "L-glutamate"
ADP (chemical): "adenosine diphosphate", "ADP", "adenosine 5'-diphosphate"
DHF (chemical): "dihydrofolate", "DHF", "7,8-dihydrofolate"
L_serine (chemical): "L-serine", "serine", "L-2-amino-3-hydroxypropanoic acid"
Glycine (chemical): "glycine", "aminoacetic acid", "2-aminoethanoic acid"
NADPH (chemical): "nicotinamide adenine dinucleotide phosphate", "NADPH", "reduced NADP"
CH2_THF (chemical): "5,10-methylenetetrahydrofolate", "CH2-THF", "5,10-CH2-THF"
Reason: All species are identified as chemicals because they are all involved in the folate pathway model as reactants or products, and their names match known chemical compounds. The standardized names and synonyms provided are based on common names used in biochemistry and the provided display names.
Synonyms dict: {'ATP': ['adenosine triphosphate', 'ATP', "adenosine 5'-triphosphate"], 'AMP': ['adenosine monophosphate', 'AMP', "adenosine 5'-monophosphate"], 'p_ABA': ['para-aminobenzoic acid', 'p-ABA', '4-aminobenzoic acid'], 'H2_Pteroate': ['dihydropterote', 'H2-pterote', 'pterotic acid'], 'L_Glutamate': ['L-glutamic acid', 'glutamate', 'L-glutamate'], 'ADP': ['adenosine diphosphate', 'ADP', "adenosine 5'-diphosphate"], 'DHF': ['dihydrofolate', 'DHF', '7,8-dihydrofolate'], 'L_serine': ['L-serine', 'serine', 'L-2-amino-3-hydroxypropanoic acid'], 'Glycine': ['glycine', 'aminoacetic acid', '2-aminoethanoic acid'], 'NADPH': ['nicotinamide adenine dinucleotide phosphate', 'NADPH', 'reduced NADP'], 'CH2_THF': ['5,10-methylenetetrahydrofolate', 'CH2-THF', '5,10-CH2-THF']}
Evaluating 690/1075: BIOMD0000000691.xml

2025-11-20 13:17:14,847 - WARNING - Skipping BIOMD0000000692.xml - no results generated
2025-11-20 13:17:14,855 - WARNING - Skipping BIOMD0000000693.xml - no results generated
2025-11-20 13:17:14,886 - WARNING - Skipping BIOMD0000000695.xml - no results generated
2025-11-20 13:17:14,904 - WARNING - Skipping BIOMD0000000696.xml - no results generated
2025-11-20 13:17:14,928 - WARNING - Skipping BIOMD0000000697.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000691.txt
LLM response:
S1__Cell_1_ (chemical): "glucose", "D-glucose", "blood sugar"
S1__Cell_2_ (chemical): "glucose", "D-glucose", "blood sugar"
S3__Cell_1_ (chemical): "fructose-1,6-bisphosphate", "fructose 1,6-bisphosphate", "FBP"
S3__Cell_2_ (chemical): "fructose-1,6-bisphosphate", "fructose 1,6-bisphosphate", "FBP"
N2__Cell_1_ (chemical): "acetaldehyde", "ethanal", "CH3CHO"
N2__Cell_2_ (chemical): "acetaldehyde", "ethanal", "CH3CHO"
A3__Cell_1_ (chemical): "ATP", "adenosine triphosphate", "adenosine 5'-triphosphate"
A3__Cell_2_ (chemical): "ATP", "adenosine triphosphate", "adenosine 5'-triphosphate"
N1__Cell_1_ (chemical): "NAD+", "nicotinamide adenine dinucleotide", "NAD plus"
N1__Cell_2_ (chemical): "NAD+", "nicotinamide adenine dinucleotide", "NAD plus"
A2__Cell_1_ (chemical): "ADP", "adenosine diphosphate", "adenosine 5'-diphosphate"
A2__Cell_2_ (chemical): "ADP", "adenosine diphosphate", "adenosine 5'-diphosphate"
Reason: The model is a glycolytic oscillations model in yeast, and the species are involved in the glycolytic pathway. S1 is likely glucose, the starting material of glycolysis. S3 is likely fructose-1,6-bisphosphate, an intermediate in the pathway. N2 is likely acetaldehyde, a product of pyruvate decarboxylation and a mediator of intercellular interaction. A3 is likely ATP, the energy currency of the cell. N1 is likely NAD+, a coenzyme involved in redox reactions. A2 is likely ADP, the product of ATP dephosphorylation.
Synonyms dict: {'S1__Cell_1_': ['glucose', 'D-glucose', 'blood sugar'], 'S1__Cell_2_': ['glucose', 'D-glucose', 'blood sugar'], 'S3__Cell_1_': ['fructose-1,6-bisphosphate', 'fructose 1,6-bisphosphate', 'FBP'], 'S3__Cell_2_': ['fructose-1,6-bisphosphate', 'fructose 1,6-bisphosphate', 'FBP'], 'N2__Cell_1_': ['acetaldehyde', 'ethanal', 'CH3CHO'], 'N2__Cell_2_': ['acetaldehyde', 'ethanal', 'CH3CHO'], 'A3__Cell_1_': ['ATP', 'adenosine triphosphate', "adenosine 5'-triphosphate"], 'A3__Cell_2_': ['ATP', 'adenosine triphosphate', "adenosine 5'-triphosphate"], 'N1__Cell_1_': ['NAD+', 'nicotinamide adenine dinucleotide', 'NAD plus'], 'N1__Cell_2_': ['NAD+', 'nicotinamide adenine dinucleotide', 'NAD plus'], 'A2__Cell_1_': ['ADP', 'adenosine diphosphate', "adenosine 5'-diphosphate"], 'A2__Cell_2_': ['ADP', 'adenosine diphosphate', "adenosine 5'-diphosphate"]}
Evaluating 691/1075: BIOMD0000000692.xml
Evaluating 692/1075: BIOMD0000000693.xml
Evaluating 693/1075: BIOMD0000000695.xml
Evaluating 694/1075: BIOMD0000000696.xml
Evaluating 695/1075: BIOMD0000000697.xml
Evaluating 696/1075: BIOMD0000000698.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000698.txt
LLM response:
Methionine (chemical): "L-methionine", "methionine", "L-Methionine"
AdoMet (chemical): "S-adenosylmethionine", "SAM", "AdoMet"
Homocysteine (chemical): "L-homocysteine", "homocysteine", "Hcy"
Cystathionine (chemical): "L-cystathionine", "cystathionine", "Cth"

Reason: All species are identified as chemicals because they are metabolites involved in the methionine cycle, a biochemical pathway. Methionine is an amino acid, AdoMet is a sulfonium compound, Homocysteine is a non-protein amino acid, and Cystathionine is an amino acid. The provided display names and the context of the methionine cycle model support these identifications.
Synonyms dict: {'Methionine': ['L-methionine', 'methionine', 'L-Methionine'], 'AdoMet': ['S-adenosylmethionine', 'SAM', 'AdoMet'], 'Homocysteine': ['L-homocysteine', 'homocysteine', 'Hcy'], 'Cystathionine': ['L-cystathionine', 'cystathionine', 'Cth']}
Evaluating 697/1075: BIOMD0000000699.xml

2025-11-20 13:17:27,124 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:17:27,583 - WARNING - Skipping BIOMD0000000700.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000699.txt
LLM response:
Tem1GTP (protein): "Tem1 GTP-bound", "Tem1-GTP", "GTP-bound Tem1"
Tem1GDP (protein): "Tem1 GDP-bound", "Tem1-GDP", "GDP-bound Tem1"
T_Tem1GTP (complex): "T-Tem1 GTP-bound complex", "SPB-T-Tem1-GTP", "Tem1-GTP-SPB-T"
T_Tem1GDP (complex): "T-Tem1 GDP-bound complex", "SPB-T-Tem1-GDP", "Tem1-GDP-SPB-T"
B_Bfa1_Tem1GTP (complex): "B-Bfa1-Tem1 GTP-bound complex", "Bfa1-Bub2-Tem1-GTP", "Tem1-GTP-Bfa1-Bub2"
B_Bfa1_Tem1GDP (complex): "B-Bfa1-Tem1 GDP-bound complex", "Bfa1-Bub2-Tem1-GDP", "Tem1-GDP-Bfa1-Bub2"
B_Bfa1P4_Tem1GTP (complex): "B-Bfa1P4-Tem1 GTP-bound complex", "Phosphorylated Bfa1-Bub2-Tem1-GTP", "Tem1-GTP-pBfa1-Bub2"
B_Bfa1P4_Tem1GDP (complex): "B-Bfa1P4-Tem1 GDP-bound complex", "Phosphorylated Bfa1-Bub2-Tem1-GDP", "Tem1-GDP-pBfa1-Bub2"
B_Bfa1P5_Tem1GTP (complex): "B-Bfa1P5-Tem1 GTP-bound complex", "Hyperphosphorylated Bfa1-Bub2-Tem1-GTP", "Tem1-GTP-ppBfa1-Bub2"
B_Bfa1P5_Tem1GDP (complex): "B-Bfa1P5-Tem1 GDP-bound complex", "Hyperphosphorylated Bfa1-Bub2-Tem1-GDP", "Tem1-GDP-ppBfa1-Bub2"
Bfa1_Tem1GTP (complex): "Bfa1-Tem1 GTP-bound complex", "Bfa1-Tem1-GTP", "Tem1-GTP-Bfa1"
Bfa1_Tem1GDP (complex): "Bfa1-Tem1 GDP-bound complex", "Bfa1-Tem1-GDP", "Tem1-GDP-Bfa1"
Bfa1P4_Tem1GTP (complex): "Bfa1P4-Tem1 GTP-bound complex", "Phosphorylated Bfa1-Tem1-GTP", "Tem1-GTP-pBfa1"
Bfa1P4_Tem1GDP (complex): "Bfa1P4-Tem1 GDP-bound complex", "Phosphorylated Bfa1-Tem1-GDP", "Tem1-GDP-pBfa1"
Bfa1P5_Tem1GTP (complex): "Bfa1P5-Tem1 GTP-bound complex", "Hyperphosphorylated Bfa1-Tem1-GTP", "Tem1-GTP-ppBfa1"
Bfa1P5_Tem1GDP (complex): "Bfa1P5-Tem1 GDP-bound complex", "Hyperphosphorylated Bfa1-Tem1-GDP", "Tem1-GDP-ppBfa1"
Bfa1 (protein): "Bfa1 protein", "Bud formation protein", "Bub2-associated protein"
Bfa1P4 (protein): "Phosphorylated Bfa1", "pBfa1", "Bfa1 phosphate"
Bfa1P5 (protein): "Hyperphosphorylated Bfa1", "ppBfa1", "Bfa1 hyperphosphate"
SPB_B (unknown): "SPB B", "Spindle pole body B", "SPB component B"
SPB_T (unknown): "SPB T", "Spindle pole body T", "SPB component T"

Reason: The species are annotated based on their names and the context of the model. Tem1GTP and Tem1GDP are likely protein species, as they are described as GTP-bound and GDP-bound forms of the Tem1 protein. The B_Bfa1 and Bfa1 species are also likely proteins, as they are described as components of the Bfa1-Bub2 complex. The T_Tem1GTP and T_Tem1GDP species are likely complexes, as they are described as T-Tem1 GTP-bound and GDP-bound complexes. The B_Bfa1_Tem1GTP and B_Bfa1_Tem1GDP species are also likely complexes, as they are described as B-Bfa1-Tem1 GTP-bound and GDP-bound complexes. The Bfa1P4 and Bfa1P5 species are likely phosphorylated and hyperphosphorylated forms of the Bfa1 protein. The SPB_B and SPB_T species are unknown, as their exact nature is not clear from the model.
Synonyms dict: {'Tem1GTP': ['Tem1 GTP-bound', 'Tem1-GTP', 'GTP-bound Tem1'], 'Tem1GDP': ['Tem1 GDP-bound', 'Tem1-GDP', 'GDP-bound Tem1'], 'T_Tem1GTP': ['T-Tem1 GTP-bound complex', 'SPB-T-Tem1-GTP', 'Tem1-GTP-SPB-T'], 'T_Tem1GDP': ['T-Tem1 GDP-bound complex', 'SPB-T-Tem1-GDP', 'Tem1-GDP-SPB-T'], 'B_Bfa1_Tem1GTP': ['B-Bfa1-Tem1 GTP-bound complex', 'Bfa1-Bub2-Tem1-GTP', 'Tem1-GTP-Bfa1-Bub2'], 'B_Bfa1_Tem1GDP': ['B-Bfa1-Tem1 GDP-bound complex', 'Bfa1-Bub2-Tem1-GDP', 'Tem1-GDP-Bfa1-Bub2'], 'B_Bfa1P4_Tem1GTP': ['B-Bfa1P4-Tem1 GTP-bound complex', 'Phosphorylated Bfa1-Bub2-Tem1-GTP', 'Tem1-GTP-pBfa1-Bub2'], 'B_Bfa1P4_Tem1GDP': ['B-Bfa1P4-Tem1 GDP-bound complex', 'Phosphorylated Bfa1-Bub2-Tem1-GDP', 'Tem1-GDP-pBfa1-Bub2'], 'B_Bfa1P5_Tem1GTP': ['B-Bfa1P5-Tem1 GTP-bound complex', 'Hyperphosphorylated Bfa1-Bub2-Tem1-GTP', 'Tem1-GTP-ppBfa1-Bub2'], 'B_Bfa1P5_Tem1GDP': ['B-Bfa1P5-Tem1 GDP-bound complex', 'Hyperphosphorylated Bfa1-Bub2-Tem1-GDP', 'Tem1-GDP-ppBfa1-Bub2'], 'Bfa1_Tem1GTP': ['Bfa1-Tem1 GTP-bound complex', 'Bfa1-Tem1-GTP', 'Tem1-GTP-Bfa1'], 'Bfa1_Tem1GDP': ['Bfa1-Tem1 GDP-bound complex', 'Bfa1-Tem1-GDP', 'Tem1-GDP-Bfa1'], 'Bfa1P4_Tem1GTP': ['Bfa1P4-Tem1 GTP-bound complex', 'Phosphorylated Bfa1-Tem1-GTP', 'Tem1-GTP-pBfa1'], 'Bfa1P4_Tem1GDP': ['Bfa1P4-Tem1 GDP-bound complex', 'Phosphorylated Bfa1-Tem1-GDP', 'Tem1-GDP-pBfa1'], 'Bfa1P5_Tem1GTP': ['Bfa1P5-Tem1 GTP-bound complex', 'Hyperphosphorylated Bfa1-Tem1-GTP', 'Tem1-GTP-ppBfa1'], 'Bfa1P5_Tem1GDP': ['Bfa1P5-Tem1 GDP-bound complex', 'Hyperphosphorylated Bfa1-Tem1-GDP', 'Tem1-GDP-ppBfa1'], 'Bfa1': ['Bfa1 protein', 'Bud formation protein', 'Bub2-associated protein'], 'Bfa1P4': ['Phosphorylated Bfa1', 'pBfa1', 'Bfa1 phosphate'], 'Bfa1P5': ['Hyperphosphorylated Bfa1', 'ppBfa1', 'Bfa1 hyperphosphate'], 'SPB_B': ['SPB B', 'Spindle pole body B', 'SPB component B'], 'SPB_T': ['SPB T', 'Spindle pole body T', 'SPB component T']}
Evaluating 698/1075: BIOMD0000000700.xml
Evaluating 699/1075: BIOMD0000000701.xml

2025-11-20 13:17:36,133 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000701.txt
LLM response:
Tem1GTP (protein): "Tem1 GTP-bound", "Tem1-GTP", "Tem1p GTP"
Tem1GDP (protein): "Tem1 GDP-bound", "Tem1-GDP", "Tem1p GDP"
T_Tem1GTP (complex): "SPB-bound Tem1 GTP", "T- Tem1-GTP", "Tem1 GTP SPB"
T_Tem1GDP (complex): "SPB-bound Tem1 GDP", "T- Tem1-GDP", "Tem1 GDP SPB"
B_Bfa1_Tem1GTP (complex): "Bfa1-Bub2-Tem1 GTP complex", "B-Bfa1-Tem1-GTP", "Bfa1-Tem1 GTP complex"
B_Bfa1P4_Tem1GTP (complex): "Bfa1P4-Bub2-Tem1 GTP complex", "B-Bfa1P4-Tem1-GTP", "Bfa1P4-Tem1 GTP complex"
B_Bfa1P5_Tem1GTP (complex): "Bfa1P5-Bub2-Tem1 GTP complex", "B-Bfa1P5-Tem1-GTP", "Bfa1P5-Tem1 GTP complex"
B_Bfa1_Tem1GDP (complex): "Bfa1-Bub2-Tem1 GDP complex", "B-Bfa1-Tem1-GDP", "Bfa1-Tem1 GDP complex"
B_Bfa1P4_Tem1GDP (complex): "Bfa1P4-Bub2-Tem1 GDP complex", "B-Bfa1P4-Tem1-GDP", "Bfa1P4-Tem1 GDP complex"
B_Bfa1P5_Tem1GDP (complex): "Bfa1P5-Bub2-Tem1 GDP complex", "B-Bfa1P5-Tem1-GDP", "Bfa1P5-Tem1 GDP complex"
Bfa1_Tem1GTP (complex): "Bfa1-Tem1 GTP complex", "Bfa1-Tem1-GTP", "Tem1-Bfa1 GTP complex"
Bfa1P4_Tem1GTP (complex): "Bfa1P4-Tem1 GTP complex", "Bfa1P4-Tem1-GTP", "Tem1-Bfa1P4 GTP complex"
Bfa1P5_Tem1GTP (complex): "Bfa1P5-Tem1 GTP complex", "Bfa1P5-Tem1-GTP", "Tem1-Bfa1P5 GTP complex"
Bfa1_Tem1GDP (complex): "Bfa1-Tem1 GDP complex", "Bfa1-Tem1-GDP", "Tem1-Bfa1 GDP complex"
Bfa1P4_Tem1GDP (complex): "Bfa1P4-Tem1 GDP complex", "Bfa1P4-Tem1-GDP", "Tem1-Bfa1P4 GDP complex"
Bfa1P5_Tem1GDP (complex): "Bfa1P5-Tem1 GDP complex", "Bfa1P5-Tem1-GDP", "Tem1-Bfa1P5 GDP complex"
Bfa1 (protein): "Bfa1 protein", "Bfa1p", "Bub2-associated protein"
Bfa1P4 (protein): "Phosphorylated Bfa1", "Bfa1p phosphorylated", "Bfa1-P"
Bfa1P5 (protein): "Phosphorylated Bfa1", "Bfa1p phosphorylated", "Bfa1-P"
SPB_B (unknown): "SPB component B", "SPB_B", "Unknown"
SPB_T (unknown): "SPB component T", "SPB_T", "Unknown"

Reason: The species are identified based on the context of the spindle position checkpoint model. Tem1 is a GTPase, and Bfa1 is a protein that interacts with Tem1. The complexes are formed by the interaction of these proteins. The phosphorylated forms of Bfa1 (Bfa1P4 and Bfa1P5) are also proteins. The SPB components (SPB_B and SPB_T) are unknown as their exact nature is not specified in the model.
Synonyms dict: {'Tem1GTP': ['Tem1 GTP-bound', 'Tem1-GTP', 'Tem1p GTP'], 'Tem1GDP': ['Tem1 GDP-bound', 'Tem1-GDP', 'Tem1p GDP'], 'T_Tem1GTP': ['SPB-bound Tem1 GTP', 'T- Tem1-GTP', 'Tem1 GTP SPB'], 'T_Tem1GDP': ['SPB-bound Tem1 GDP', 'T- Tem1-GDP', 'Tem1 GDP SPB'], 'B_Bfa1_Tem1GTP': ['Bfa1-Bub2-Tem1 GTP complex', 'B-Bfa1-Tem1-GTP', 'Bfa1-Tem1 GTP complex'], 'B_Bfa1P4_Tem1GTP': ['Bfa1P4-Bub2-Tem1 GTP complex', 'B-Bfa1P4-Tem1-GTP', 'Bfa1P4-Tem1 GTP complex'], 'B_Bfa1P5_Tem1GTP': ['Bfa1P5-Bub2-Tem1 GTP complex', 'B-Bfa1P5-Tem1-GTP', 'Bfa1P5-Tem1 GTP complex'], 'B_Bfa1_Tem1GDP': ['Bfa1-Bub2-Tem1 GDP complex', 'B-Bfa1-Tem1-GDP', 'Bfa1-Tem1 GDP complex'], 'B_Bfa1P4_Tem1GDP': ['Bfa1P4-Bub2-Tem1 GDP complex', 'B-Bfa1P4-Tem1-GDP', 'Bfa1P4-Tem1 GDP complex'], 'B_Bfa1P5_Tem1GDP': ['Bfa1P5-Bub2-Tem1 GDP complex', 'B-Bfa1P5-Tem1-GDP', 'Bfa1P5-Tem1 GDP complex'], 'Bfa1_Tem1GTP': ['Bfa1-Tem1 GTP complex', 'Bfa1-Tem1-GTP', 'Tem1-Bfa1 GTP complex'], 'Bfa1P4_Tem1GTP': ['Bfa1P4-Tem1 GTP complex', 'Bfa1P4-Tem1-GTP', 'Tem1-Bfa1P4 GTP complex'], 'Bfa1P5_Tem1GTP': ['Bfa1P5-Tem1 GTP complex', 'Bfa1P5-Tem1-GTP', 'Tem1-Bfa1P5 GTP complex'], 'Bfa1_Tem1GDP': ['Bfa1-Tem1 GDP complex', 'Bfa1-Tem1-GDP', 'Tem1-Bfa1 GDP complex'], 'Bfa1P4_Tem1GDP': ['Bfa1P4-Tem1 GDP complex', 'Bfa1P4-Tem1-GDP', 'Tem1-Bfa1P4 GDP complex'], 'Bfa1P5_Tem1GDP': ['Bfa1P5-Tem1 GDP complex', 'Bfa1P5-Tem1-GDP', 'Tem1-Bfa1P5 GDP complex'], 'Bfa1': ['Bfa1 protein', 'Bfa1p', 'Bub2-associated protein'], 'Bfa1P4': ['Phosphorylated Bfa1', 'Bfa1p phosphorylated', 'Bfa1-P'], 'Bfa1P5': ['Phosphorylated Bfa1', 'Bfa1p phosphorylated', 'Bfa1-P'], 'SPB_B': ['SPB component B', 'SPB_B', 'Unknown'], 'SPB_T': ['SPB component T', 'SPB_T', 'Unknown']}
Evaluating 700/1075: BIOMD0000000702.xml

2025-11-20 13:17:45,862 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:17:46,266 - WARNING - Skipping BIOMD0000000703.xml - no results generated
2025-11-20 13:17:46,286 - WARNING - Skipping BIOMD0000000704.xml - no results generated
2025-11-20 13:17:46,317 - WARNING - Skipping BIOMD0000000705.xml - no results generated
2025-11-20 13:17:46,382 - WARNING - Skipping BIOMD0000000706.xml - no results generated
2025-11-20 13:17:46,389 - WARNING - Skipping BIOMD0000000707.xml - no results generated
2025-11-20 13:17:46,397 - WARNING - Skipping BIOMD0000000708.xml - no results generated
2025-11-20 13:17:46,403 - WARNING - Skipping BIOMD0000000709.xml - no results generated
2025-11-20 13:17:46,413 - WARNING - Skipping BIOMD0000000710.xml - no results generated
2025-11-20 13:17:46,428 - WARNING - Skipping BIOMD0000000711.xml - no results generated
2025-11-20 13:17:46,433 - WARNING - Skipping BIOMD0000000712.xml - no results generated
2025-11-20 13:17:46,439 - WARNING - Skipping BIOMD0000000713.xml - no results generated
2025-11-20 13:17:46,445 - WARNING - Skipping BIOMD0000000714.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000702.txt
LLM response:
Tem1GTP (protein): "Tem1 GTP-bound", "Tem1-GTP", "GTP-bound Tem1"
Tem1GDP (protein): "Tem1 GDP-bound", "Tem1-GDP", "GDP-bound Tem1"
T_Tem1GTP (complex): "T-bound Tem1 GTP", "T-Tem1-GTP", "SPB_T-Tem1GTP"
T_Tem1GDP (complex): "T-bound Tem1 GDP", "T-Tem1-GDP", "SPB_T-Tem1GDP"
B_Bfa1_Tem1GTP (complex): "B-Bfa1-Tem1 GTP", "Bfa1-Bub2-Tem1GTP", "SPB_B-Bfa1-Tem1GTP"
B_Bfa1P4_Tem1GTP (complex): "B-Bfa1P4-Tem1 GTP", "Phospho-Bfa1-Tem1GTP", "SPB_B-Bfa1P4-Tem1GTP"
B_Bfa1P5_Tem1GTP (complex): "B-Bfa1P5-Tem1 GTP", "Phospho-Bfa1-Tem1GTP", "SPB_B-Bfa1P5-Tem1GTP"
B_Bfa1_Tem1GDP (complex): "B-Bfa1-Tem1 GDP", "Bfa1-Bub2-Tem1GDP", "SPB_B-Bfa1-Tem1GDP"
B_Bfa1P4_Tem1GDP (complex): "B-Bfa1P4-Tem1 GDP", "Phospho-Bfa1-Tem1GDP", "SPB_B-Bfa1P4-Tem1GDP"
B_Bfa1P5_Tem1GDP (complex): "B-Bfa1P5-Tem1 GDP", "Phospho-Bfa1-Tem1GDP", "SPB_B-Bfa1P5-Tem1GDP"
Bfa1_Tem1GTP (complex): "Bfa1-Tem1 GTP", "Bfa1-Tem1GTP", "Cytoplasmic Bfa1-Tem1GTP"
Bfa1P4_Tem1GTP (complex): "Bfa1P4-Tem1 GTP", "Phospho-Bfa1-Tem1GTP", "Cytoplasmic Bfa1P4-Tem1GTP"
Bfa1P5_Tem1GTP (complex): "Bfa1P5-Tem1 GTP", "Phospho-Bfa1-Tem1GTP", "Cytoplasmic Bfa1P5-Tem1GTP"
Bfa1_Tem1GDP (complex): "Bfa1-Tem1 GDP", "Bfa1-Tem1GDP", "Cytoplasmic Bfa1-Tem1GDP"
Bfa1P4_Tem1GDP (complex): "Bfa1P4-Tem1 GDP", "Phospho-Bfa1-Tem1GDP", "Cytoplasmic Bfa1P4-Tem1GDP"
Bfa1P5_Tem1GDP (complex): "Bfa1P5-Tem1 GDP", "Phospho-Bfa1-Tem1GDP", "Cytoplasmic Bfa1P5-Tem1GDP"
Bfa1 (protein): "Bfa1 protein", "Bfa1", "GAP complex component"
Bfa1P4 (protein): "Phospho-Bfa1", "Bfa1P4", "Phosphorylated Bfa1"
Bfa1P5 (protein): "Phospho-Bfa1", "Bfa1P5", "Phosphorylated Bfa1"
SPB_B (unknown): "SPB_B", "Spindle Pole Body B", "SPB component B"
SPB_T (unknown): "SPB_T", "Spindle Pole Body T", "SPB component T"
Reason: The species are classified based on their names and the context of the model. Tem1GTP and Tem1GDP are classified as proteins because they are GTP-bound and GDP-bound forms of the Tem1 protein. The species with prefixes T_ and B_ are classified as complexes because they represent Tem1 bound to other proteins or components at the spindle pole body (SPB). Bfa1, Bfa1P4, and Bfa1P5 are classified as proteins because they are components of the GAP complex. SPB_B and SPB_T are classified as unknown because their exact nature is not clear from the model. The standardized names and synonyms are based on common naming conventions in the field of molecular biology.
Synonyms dict: {'Tem1GTP': ['Tem1 GTP-bound', 'Tem1-GTP', 'GTP-bound Tem1'], 'Tem1GDP': ['Tem1 GDP-bound', 'Tem1-GDP', 'GDP-bound Tem1'], 'T_Tem1GTP': ['T-bound Tem1 GTP', 'T-Tem1-GTP', 'SPB_T-Tem1GTP'], 'T_Tem1GDP': ['T-bound Tem1 GDP', 'T-Tem1-GDP', 'SPB_T-Tem1GDP'], 'B_Bfa1_Tem1GTP': ['B-Bfa1-Tem1 GTP', 'Bfa1-Bub2-Tem1GTP', 'SPB_B-Bfa1-Tem1GTP'], 'B_Bfa1P4_Tem1GTP': ['B-Bfa1P4-Tem1 GTP', 'Phospho-Bfa1-Tem1GTP', 'SPB_B-Bfa1P4-Tem1GTP'], 'B_Bfa1P5_Tem1GTP': ['B-Bfa1P5-Tem1 GTP', 'Phospho-Bfa1-Tem1GTP', 'SPB_B-Bfa1P5-Tem1GTP'], 'B_Bfa1_Tem1GDP': ['B-Bfa1-Tem1 GDP', 'Bfa1-Bub2-Tem1GDP', 'SPB_B-Bfa1-Tem1GDP'], 'B_Bfa1P4_Tem1GDP': ['B-Bfa1P4-Tem1 GDP', 'Phospho-Bfa1-Tem1GDP', 'SPB_B-Bfa1P4-Tem1GDP'], 'B_Bfa1P5_Tem1GDP': ['B-Bfa1P5-Tem1 GDP', 'Phospho-Bfa1-Tem1GDP', 'SPB_B-Bfa1P5-Tem1GDP'], 'Bfa1_Tem1GTP': ['Bfa1-Tem1 GTP', 'Bfa1-Tem1GTP', 'Cytoplasmic Bfa1-Tem1GTP'], 'Bfa1P4_Tem1GTP': ['Bfa1P4-Tem1 GTP', 'Phospho-Bfa1-Tem1GTP', 'Cytoplasmic Bfa1P4-Tem1GTP'], 'Bfa1P5_Tem1GTP': ['Bfa1P5-Tem1 GTP', 'Phospho-Bfa1-Tem1GTP', 'Cytoplasmic Bfa1P5-Tem1GTP'], 'Bfa1_Tem1GDP': ['Bfa1-Tem1 GDP', 'Bfa1-Tem1GDP', 'Cytoplasmic Bfa1-Tem1GDP'], 'Bfa1P4_Tem1GDP': ['Bfa1P4-Tem1 GDP', 'Phospho-Bfa1-Tem1GDP', 'Cytoplasmic Bfa1P4-Tem1GDP'], 'Bfa1P5_Tem1GDP': ['Bfa1P5-Tem1 GDP', 'Phospho-Bfa1-Tem1GDP', 'Cytoplasmic Bfa1P5-Tem1GDP'], 'Bfa1': ['Bfa1 protein', 'Bfa1', 'GAP complex component'], 'Bfa1P4': ['Phospho-Bfa1', 'Bfa1P4', 'Phosphorylated Bfa1'], 'Bfa1P5': ['Phospho-Bfa1', 'Bfa1P5', 'Phosphorylated Bfa1'], 'SPB_B': ['SPB_B', 'Spindle Pole Body B', 'SPB component B'], 'SPB_T': ['SPB_T', 'Spindle Pole Body T', 'SPB component T']}
Evaluating 701/1075: BIOMD0000000703.xml
Evaluating 702/1075: BIOMD0000000704.xml
Evaluating 703/1075: BIOMD0000000705.xml
Evaluating 704/1075: BIOMD0000000706.xml
Evaluating 705/1075: BIOMD0000000707.xml
Evaluating 706/1075: BIOMD0000000708.xml
Evaluating 707/1075: BIOMD0000000709.xml
Evaluating 708/1075: BIOMD0000000710.xml
Evaluating 709/1075: BIOMD0000000711.xml
Evaluating 710/1075: BIOMD0000000712.xml
Evaluating 711/1075: BIOMD0000000713.xml
Evaluating 712/1075: BIOMD0000000714.xml
Evaluating 713/1075: BIOMD0000000715.xml

2025-11-20 13:17:46,450 - WARNING - Skipping BIOMD0000000715.xml - no results generated
2025-11-20 13:17:46,460 - WARNING - Skipping BIOMD0000000716.xml - no results generated
2025-11-20 13:17:46,468 - WARNING - Skipping BIOMD0000000717.xml - no results generated
2025-11-20 13:17:46,488 - WARNING - Skipping BIOMD0000000718.xml - no results generated
2025-11-20 13:17:46,498 - WARNING - Skipping BIOMD0000000719.xml - no results generated
2025-11-20 13:17:46,506 - WARNING - Skipping BIOMD0000000720.xml - no results generated
2025-11-20 13:17:46,516 - WARNING - Skipping BIOMD0000000721.xml - no results generated
2025-11-20 13:17:46,524 - WARNING - Skipping BIOMD0000000722.xml - no results generated
2025-11-20 13:17:46,556 - WARNING - Skipping BIOMD0000000723.xml - no results generated
2025-11-20 13:17:46,579 - WARNING - Skipping BIOMD0000000724.xml - no results generated
2025-11-20 13:17:46,604 - WARNING - Skipping BIOMD0000000725.xml - no results generated
2025-11-20 13:17:46,615 - WARNING - Skipping BIOMD0000000726.xml - no results generated
2025-11-20 13:17:46,650 - WARNING - Skipping BIOMD0000000727.xml - no results generated
2025-11-20 13:17:46,655 - WARNING - Skipping BIOMD0000000728.xml - no results generated

Evaluating 714/1075: BIOMD0000000716.xml
Evaluating 715/1075: BIOMD0000000717.xml
Evaluating 716/1075: BIOMD0000000718.xml
Evaluating 717/1075: BIOMD0000000719.xml
Evaluating 718/1075: BIOMD0000000720.xml
Evaluating 719/1075: BIOMD0000000721.xml
Evaluating 720/1075: BIOMD0000000722.xml
Evaluating 721/1075: BIOMD0000000723.xml
Evaluating 722/1075: BIOMD0000000724.xml
Evaluating 723/1075: BIOMD0000000725.xml
Evaluating 724/1075: BIOMD0000000726.xml
Evaluating 725/1075: BIOMD0000000727.xml
Evaluating 726/1075: BIOMD0000000728.xml
Evaluating 727/1075: BIOMD0000000729.xml

2025-11-20 13:17:46,662 - WARNING - Skipping BIOMD0000000729.xml - no results generated
2025-11-20 13:17:46,733 - WARNING - Skipping BIOMD0000000730.xml - no results generated
2025-11-20 13:17:46,751 - WARNING - Skipping BIOMD0000000731.xml - no results generated
2025-11-20 13:17:46,757 - WARNING - Skipping BIOMD0000000732.xml - no results generated
2025-11-20 13:17:46,762 - WARNING - Skipping BIOMD0000000733.xml - no results generated

Evaluating 728/1075: BIOMD0000000730.xml
Evaluating 729/1075: BIOMD0000000731.xml
Evaluating 730/1075: BIOMD0000000732.xml
Evaluating 731/1075: BIOMD0000000733.xml
Evaluating 732/1075: BIOMD0000000734.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000734.txt
LLM response:
FeDuo (chemical): "iron", "ferric ion", "Fe3+"
FeDuo_0 (chemical): "iron", "ferric ion", "Fe3+"
FeRBC (chemical): "iron in red blood cells", "ferric ion in erythrocytes", "RBC iron"
FeRBC_0 (chemical): "iron in red blood cells", "ferric ion in erythrocytes", "RBC iron"
FeSpleen (chemical): "iron in spleen", "spleen ferric ion", "spleen iron"
FeSpleen_0 (chemical): "iron in spleen", "spleen ferric ion", "spleen iron"
FeLiver (chemical): "iron in liver", "liver ferric ion", "liver iron"
FeLiver_0 (chemical): "iron in liver", "liver ferric ion", "liver iron"
Fe2Tf (chemical): "diferric transferrin", "Fe2-transferrin", "holo-transferrin"
NTBI (chemical): "non-transferrin bound iron", "free iron", "labile iron"
Fe1Tf (chemical): "monoferric transferrin", "Fe-transferrin", "mono-Fe transferrin"
Fe2Tf_0 (chemical): "diferric transferrin", "Fe2-transferrin", "holo-transferrin"
Fe1Tf_0 (chemical): "monoferric transferrin", "Fe-transferrin", "mono-Fe transferrin"
NTBI_0 (chemical): "non-transferrin bound iron", "free iron", "labile iron"
Fe2Tf_ (chemical): "diferric transferrin", "Fe2-transferrin", "holo-transferrin"
FeRest (chemical): "iron in rest of body", "ferric ion in rest of body", "rest iron"
FeOutside (chemical): "iron outside of cells", "extracellular iron", "extracellular ferric ion"
FeRest_0 (chemical): "iron in rest of body", "ferric ion in rest of body", "rest iron"
FeOutside_0 (chemical): "iron outside of cells", "extracellular iron", "extracellular ferric ion"
FeBM (chemical): "iron in bone marrow", "bone marrow ferric ion", "bone marrow iron"
FeBM_0 (chemical): "iron in bone marrow", "bone marrow ferric ion", "bone marrow iron"
Tf (protein): "transferrin", "serotransferrin", "siderophilin"

Reason: Most species are related to iron distribution in the body, with FeDuo, FeRBC, FeSpleen, FeLiver, FeRest, FeOutside, and FeBM representing iron in different tissues or compartments. Fe2Tf and Fe1Tf represent diferric and monoferric transferrin, respectively, which are proteins that bind iron. NTBI represents non-transferrin bound iron, which is iron that is not bound to transferrin. Tf is the protein transferrin, which binds iron. The species with _0 suffixes appear to be related to the same entities as those without the suffix, possibly representing different states or compartments. The entity types are determined based on the context of the model and the names of the species.
Synonyms dict: {'FeDuo': ['iron', 'ferric ion', 'Fe3+'], 'FeDuo_0': ['iron', 'ferric ion', 'Fe3+'], 'FeRBC': ['iron in red blood cells', 'ferric ion in erythrocytes', 'RBC iron'], 'FeRBC_0': ['iron in red blood cells', 'ferric ion in erythrocytes', 'RBC iron'], 'FeSpleen': ['iron in spleen', 'spleen ferric ion', 'spleen iron'], 'FeSpleen_0': ['iron in spleen', 'spleen ferric ion', 'spleen iron'], 'FeLiver': ['iron in liver', 'liver ferric ion', 'liver iron'], 'FeLiver_0': ['iron in liver', 'liver ferric ion', 'liver iron'], 'Fe2Tf': ['diferric transferrin', 'Fe2-transferrin', 'holo-transferrin'], 'NTBI': ['non-transferrin bound iron', 'free iron', 'labile iron'], 'Fe1Tf': ['monoferric transferrin', 'Fe-transferrin', 'mono-Fe transferrin'], 'Fe2Tf_0': ['diferric transferrin', 'Fe2-transferrin', 'holo-transferrin'], 'Fe1Tf_0': ['monoferric transferrin', 'Fe-transferrin', 'mono-Fe transferrin'], 'NTBI_0': ['non-transferrin bound iron', 'free iron', 'labile iron'], 'Fe2Tf_': ['diferric transferrin', 'Fe2-transferrin', 'holo-transferrin'], 'FeRest': ['iron in rest of body', 'ferric ion in rest of body', 'rest iron'], 'FeOutside': ['iron outside of cells', 'extracellular iron', 'extracellular ferric ion'], 'FeRest_0': ['iron in rest of body', 'ferric ion in rest of body', 'rest iron'], 'FeOutside_0': ['iron outside of cells', 'extracellular iron', 'extracellular ferric ion'], 'FeBM': ['iron in bone marrow', 'bone marrow ferric ion', 'bone marrow iron'], 'FeBM_0': ['iron in bone marrow', 'bone marrow ferric ion', 'bone marrow iron'], 'Tf': ['transferrin', 'serotransferrin', 'siderophilin']}
Evaluating 733/1075: BIOMD0000000735.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000735.txt
LLM response:
FeDuo (chemical): "iron", "ferric ion", "Fe3+"
FeDuo_0 (chemical): "iron", "ferric ion", "Fe3+"
FeRBC (chemical): "iron in red blood cells", "ferric ion in RBC", "RBC iron"
FeRBC_0 (chemical): "iron in red blood cells", "ferric ion in RBC", "RBC iron"
FeSpleen (chemical): "iron in spleen", "spleen iron", "ferric ion in spleen"
FeSpleen_0 (chemical): "iron in spleen", "spleen iron", "ferric ion in spleen"
FeLiver (chemical): "iron in liver", "liver iron", "ferric ion in liver"
FeLiver_0 (chemical): "iron in liver", "liver iron", "ferric ion in liver"
Fe2Tf (complex): "diferric transferrin", "transferrin with two iron ions", "Fe2-Tf"
Fe1Tf (complex): "monoferric transferrin", "transferrin with one iron ion", "Fe-Tf"
NTBI (chemical): "non-transferrin-bound iron", "free iron", "labile iron"
NTBI_0 (chemical): "non-transferrin-bound iron", "free iron", "labile iron"
Fe2Tf_0 (complex): "diferric transferrin", "transferrin with two iron ions", "Fe2-Tf"
Fe1Tf_0 (complex): "monoferric transferrin", "transferrin with one iron ion", "Fe-Tf"
FeRest (chemical): "iron in rest of body", "rest of body iron", "ferric ion in rest of body"
FeOutside (chemical): "iron outside of cells", "extracellular iron", "ferric ion outside of cells"
FeRest_0 (chemical): "iron in rest of body", "rest of body iron", "ferric ion in rest of body"
FeOutside_0 (chemical): "iron outside of cells", "extracellular iron", "ferric ion outside of cells"
FeBM (chemical): "iron in bone marrow", "bone marrow iron", "ferric ion in bone marrow"
FeBM_0 (chemical): "iron in bone marrow", "bone marrow iron", "ferric ion in bone marrow"
Fe2Tf_ (complex): "diferric transferrin", "transferrin with two iron ions", "Fe2-Tf"
Tf (protein): "transferrin", "serotransferrin", "siderophilin"

Reason: The species are identified based on their names and roles in the iron distribution model. Species with "Fe" in their names are likely to be iron-related chemicals. Species with "Tf" in their names are related to transferrin, a protein that binds iron. The "_0" suffix likely indicates a different state or compartment of the same species. The entity types are determined based on the species' roles in the model and their names. Fe2Tf and Fe1Tf are complexes because they represent transferrin with one or two iron ions bound. Tf is a protein because it is a transferrin molecule without bound iron.
Synonyms dict: {'FeDuo': ['iron', 'ferric ion', 'Fe3+'], 'FeDuo_0': ['iron', 'ferric ion', 'Fe3+'], 'FeRBC': ['iron in red blood cells', 'ferric ion in RBC', 'RBC iron'], 'FeRBC_0': ['iron in red blood cells', 'ferric ion in RBC', 'RBC iron'], 'FeSpleen': ['iron in spleen', 'spleen iron', 'ferric ion in spleen'], 'FeSpleen_0': ['iron in spleen', 'spleen iron', 'ferric ion in spleen'], 'FeLiver': ['iron in liver', 'liver iron', 'ferric ion in liver'], 'FeLiver_0': ['iron in liver', 'liver iron', 'ferric ion in liver'], 'Fe2Tf': ['diferric transferrin', 'transferrin with two iron ions', 'Fe2-Tf'], 'Fe1Tf': ['monoferric transferrin', 'transferrin with one iron ion', 'Fe-Tf'], 'NTBI': ['non-transferrin-bound iron', 'free iron', 'labile iron'], 'NTBI_0': ['non-transferrin-bound iron', 'free iron', 'labile iron'], 'Fe2Tf_0': ['diferric transferrin', 'transferrin with two iron ions', 'Fe2-Tf'], 'Fe1Tf_0': ['monoferric transferrin', 'transferrin with one iron ion', 'Fe-Tf'], 'FeRest': ['iron in rest of body', 'rest of body iron', 'ferric ion in rest of body'], 'FeOutside': ['iron outside of cells', 'extracellular iron', 'ferric ion outside of cells'], 'FeRest_0': ['iron in rest of body', 'rest of body iron', 'ferric ion in rest of body'], 'FeOutside_0': ['iron outside of cells', 'extracellular iron', 'ferric ion outside of cells'], 'FeBM': ['iron in bone marrow', 'bone marrow iron', 'ferric ion in bone marrow'], 'FeBM_0': ['iron in bone marrow', 'bone marrow iron', 'ferric ion in bone marrow'], 'Fe2Tf_': ['diferric transferrin', 'transferrin with two iron ions', 'Fe2-Tf'], 'Tf': ['transferrin', 'serotransferrin', 'siderophilin']}
Evaluating 734/1075: BIOMD0000000736.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000736.txt
LLM response:
FeDuo (chemical): "iron", "ferric ion", "Fe3+"
FeRBC (chemical): "iron in red blood cells", "hemoglobin iron", "RBC iron"
FeSpleen (chemical): "spleen iron", "iron in spleen", "spleenic iron"
FeLiver (chemical): "liver iron", "iron in liver", "hepatic iron"
Fe2Tf (complex): "diferric transferrin", "holo-transferrin", "Fe2-transferrin"
Fe1Tf (complex): "monoferric transferrin", "half-saturated transferrin", "Fe-transferrin"
NTBI (chemical): "non-transferrin-bound iron", "free iron", "labile iron"
FeRest (chemical): "iron in rest of body", "peripheral iron", "tissue iron"
FeOutside (chemical): "extracellular iron", "plasma iron", "serum iron"
FeBM (chemical): "bone marrow iron", "iron in bone marrow", "marrow iron"
Tf (protein): "transferrin", "siderophilin", "beta-1 metal-binding globulin"
Reason: The species IDs are annotated based on their names and roles in the iron distribution model. FeDuo, FeRBC, FeSpleen, FeLiver, NTBI, FeRest, FeOutside, and FeBM are likely to be chemical species representing different forms or locations of iron in the body. Fe2Tf and Fe1Tf are complexes of iron with transferrin, a protein that binds and transports iron. Tf is the protein transferrin itself. The annotations are based on the display names and the reactions in which each species participates, as well as general knowledge of iron metabolism and transport.
Synonyms dict: {'FeDuo': ['iron', 'ferric ion', 'Fe3+'], 'FeRBC': ['iron in red blood cells', 'hemoglobin iron', 'RBC iron'], 'FeSpleen': ['spleen iron', 'iron in spleen', 'spleenic iron'], 'FeLiver': ['liver iron', 'iron in liver', 'hepatic iron'], 'Fe2Tf': ['diferric transferrin', 'holo-transferrin', 'Fe2-transferrin'], 'Fe1Tf': ['monoferric transferrin', 'half-saturated transferrin', 'Fe-transferrin'], 'NTBI': ['non-transferrin-bound iron', 'free iron', 'labile iron'], 'FeRest': ['iron in rest of body', 'peripheral iron', 'tissue iron'], 'FeOutside': ['extracellular iron', 'plasma iron', 'serum iron'], 'FeBM': ['bone marrow iron', 'iron in bone marrow', 'marrow iron'], 'Tf': ['transferrin', 'siderophilin', 'beta-1 metal-binding globulin']}
Evaluating 735/1075: BIOMD0000000737.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000737.txt
LLM response:
FeDuo (chemical): "iron", "ferric ion", "Fe3+"
FeRBC (chemical): "iron in red blood cells", "hemoglobin iron", "RBC iron"
FeSpleen (chemical): "spleen iron", "iron in spleen", "splenic iron"
FeLiver (chemical): "liver iron", "iron in liver", "hepatic iron"
Fe2Tf (complex): "diferric transferrin", "holotransferrin", "Fe2-transferrin"
Fe1Tf (complex): "monoferric transferrin", "monoferric transferrin", "Fe-transferrin"
NTBI (chemical): "non-transferrin-bound iron", "free iron", "labile iron"
FeRest (chemical): "iron in rest of body", "residual iron", "iron in other tissues"
FeOutside (chemical): "extracellular iron", "plasma iron", "serum iron"
FeBM (chemical): "bone marrow iron", "iron in bone marrow", "marrow iron"
Tf (protein): "transferrin", "serotransferrin", "siderophilin"
Reason: The model describes iron distribution in mice, and most species are related to iron in different tissues or forms. Fe2Tf and Fe1Tf are complexes of iron with transferrin, a protein that transports iron in the blood. Tf is the protein itself. Other species are chemicals, representing iron in different forms or locations. The names and synonyms are based on common terminology in biochemistry and physiology.
Synonyms dict: {'FeDuo': ['iron', 'ferric ion', 'Fe3+'], 'FeRBC': ['iron in red blood cells', 'hemoglobin iron', 'RBC iron'], 'FeSpleen': ['spleen iron', 'iron in spleen', 'splenic iron'], 'FeLiver': ['liver iron', 'iron in liver', 'hepatic iron'], 'Fe2Tf': ['diferric transferrin', 'holotransferrin', 'Fe2-transferrin'], 'Fe1Tf': ['monoferric transferrin', 'monoferric transferrin', 'Fe-transferrin'], 'NTBI': ['non-transferrin-bound iron', 'free iron', 'labile iron'], 'FeRest': ['iron in rest of body', 'residual iron', 'iron in other tissues'], 'FeOutside': ['extracellular iron', 'plasma iron', 'serum iron'], 'FeBM': ['bone marrow iron', 'iron in bone marrow', 'marrow iron'], 'Tf': ['transferrin', 'serotransferrin', 'siderophilin']}
Evaluating 736/1075: BIOMD0000000738.xml

2025-11-20 13:18:12,430 - WARNING - Skipping BIOMD0000000739.xml - no results generated
2025-11-20 13:18:12,443 - WARNING - Skipping BIOMD0000000740.xml - no results generated
2025-11-20 13:18:12,454 - WARNING - Skipping BIOMD0000000741.xml - no results generated
2025-11-20 13:18:12,461 - WARNING - Skipping BIOMD0000000742.xml - no results generated
2025-11-20 13:18:12,475 - WARNING - Skipping BIOMD0000000743.xml - no results generated
2025-11-20 13:18:12,489 - WARNING - Skipping BIOMD0000000744.xml - no results generated
2025-11-20 13:18:12,499 - WARNING - Skipping BIOMD0000000745.xml - no results generated
2025-11-20 13:18:12,511 - WARNING - Skipping BIOMD0000000746.xml - no results generated
2025-11-20 13:18:12,527 - WARNING - Skipping BIOMD0000000747.xml - no results generated
2025-11-20 13:18:12,535 - WARNING - Skipping BIOMD0000000748.xml - no results generated
2025-11-20 13:18:12,544 - WARNING - Skipping BIOMD0000000749.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000738.txt
LLM response:
FeDuo (chemical): "iron", "ferric ion", "Fe3+"
FeRBC (chemical): "iron in red blood cells", "ferric ion in RBC", "RBC iron"
FeSpleen (chemical): "iron in spleen", "spleen iron", "ferric ion in spleen"
FeLiver (chemical): "iron in liver", "liver iron", "ferric ion in liver"
Fe2Tf (complex): "diferric transferrin", "holo-transferrin", "Fe2-Tf"
Fe1Tf (complex): "monoferric transferrin", "mono-Fe transferrin", "Fe-Tf"
NTBI (chemical): "non-transferrin bound iron", "labile plasma iron", "free iron"
FeRest (chemical): "iron in rest of body", "resting iron", "ferric ion in rest"
FeOutside (chemical): "extracellular iron", "outside iron", "extracellular ferric ion"
FeBM (chemical): "iron in bone marrow", "bone marrow iron", "ferric ion in BM"
Tf (protein): "transferrin", "serotransferrin", "siderophilin"

Reason: The model is about iron distribution in mice, so most species are related to iron in different forms or locations, which are chemicals. Fe2Tf and Fe1Tf are complexes because they represent transferrin with one or two iron ions bound, which is a protein complex. Tf is a protein because it is the transferrin protein itself. The names and synonyms are chosen based on common terminology in biochemistry and the context of the model.
Synonyms dict: {'FeDuo': ['iron', 'ferric ion', 'Fe3+'], 'FeRBC': ['iron in red blood cells', 'ferric ion in RBC', 'RBC iron'], 'FeSpleen': ['iron in spleen', 'spleen iron', 'ferric ion in spleen'], 'FeLiver': ['iron in liver', 'liver iron', 'ferric ion in liver'], 'Fe2Tf': ['diferric transferrin', 'holo-transferrin', 'Fe2-Tf'], 'Fe1Tf': ['monoferric transferrin', 'mono-Fe transferrin', 'Fe-Tf'], 'NTBI': ['non-transferrin bound iron', 'labile plasma iron', 'free iron'], 'FeRest': ['iron in rest of body', 'resting iron', 'ferric ion in rest'], 'FeOutside': ['extracellular iron', 'outside iron', 'extracellular ferric ion'], 'FeBM': ['iron in bone marrow', 'bone marrow iron', 'ferric ion in BM'], 'Tf': ['transferrin', 'serotransferrin', 'siderophilin']}
Evaluating 737/1075: BIOMD0000000739.xml
Evaluating 738/1075: BIOMD0000000740.xml
Evaluating 739/1075: BIOMD0000000741.xml
Evaluating 740/1075: BIOMD0000000742.xml
Evaluating 741/1075: BIOMD0000000743.xml
Evaluating 742/1075: BIOMD0000000744.xml
Evaluating 743/1075: BIOMD0000000745.xml
Evaluating 744/1075: BIOMD0000000746.xml
Evaluating 745/1075: BIOMD0000000747.xml
Evaluating 746/1075: BIOMD0000000748.xml
Evaluating 747/1075: BIOMD0000000749.xml
Evaluating 748/1075: BIOMD0000000750.xml

2025-11-20 13:18:14,269 - WARNING - Skipping BIOMD0000000751.xml - no results generated
2025-11-20 13:18:14,276 - WARNING - Skipping BIOMD0000000752.xml - no results generated
2025-11-20 13:18:14,282 - WARNING - Skipping BIOMD0000000753.xml - no results generated
2025-11-20 13:18:14,291 - WARNING - Skipping BIOMD0000000754.xml - no results generated
2025-11-20 13:18:14,298 - WARNING - Skipping BIOMD0000000755.xml - no results generated
2025-11-20 13:18:14,309 - WARNING - Skipping BIOMD0000000756.xml - no results generated
2025-11-20 13:18:14,324 - WARNING - Skipping BIOMD0000000757.xml - no results generated
2025-11-20 13:18:14,329 - WARNING - Skipping BIOMD0000000758.xml - no results generated
2025-11-20 13:18:14,343 - WARNING - Skipping BIOMD0000000759.xml - no results generated
2025-11-20 13:18:14,349 - WARNING - Skipping BIOMD0000000760.xml - no results generated
2025-11-20 13:18:14,359 - WARNING - Skipping BIOMD0000000761.xml - no results generated
2025-11-20 13:18:14,365 - WARNING - Skipping BIOMD0000000762.xml - no results generated
2025-11-20 13:18:14,371 - WARNING - Skipping BIOMD0000000763.xml - no results generated
2025-11-20 13:18:14,380 - WARNING - Skipping BIOMD0000000764.xml - no results generated
2025-11-20 13:18:14,386 - WARNING - Skipping BIOMD0000000765.xml - no results generated
2025-11-20 13:18:14,396 - WARNING - Skipping BIOMD0000000766.xml - no results generated
2025-11-20 13:18:14,402 - WARNING - Skipping BIOMD0000000767.xml - no results generated
2025-11-20 13:18:14,414 - WARNING - Skipping BIOMD0000000768.xml - no results generated
2025-11-20 13:18:14,428 - WARNING - Skipping BIOMD0000000769.xml - no results generated
2025-11-20 13:18:14,438 - WARNING - Skipping BIOMD0000000770.xml - no results generated
2025-11-20 13:18:14,443 - WARNING - Skipping BIOMD0000000771.xml - no results generated
2025-11-20 13:18:14,449 - WARNING - Skipping BIOMD0000000772.xml - no results generated
2025-11-20 13:18:14,456 - WARNING - Skipping BIOMD0000000773.xml - no results generated
2025-11-20 13:18:14,462 - WARNING - Skipping BIOMD0000000774.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000750.txt
LLM response:
Nn (unknown): "UNK", "neuron", "nerve cell"
Na (chemical): "sodium", "sodium ion", "Na+"

Reason: Nn is unknown because the display name "Nn" does not provide enough information to determine its entity type, but based on the model description, it is likely related to neurons or nerve cells. Na is likely a chemical, specifically the sodium ion, due to its common abbreviation "Na" in biochemical contexts.
Synonyms dict: {'Nn': ['UNK', 'neuron', 'nerve cell'], 'Na': ['sodium', 'sodium ion', 'Na+']}
Evaluating 749/1075: BIOMD0000000751.xml
Evaluating 750/1075: BIOMD0000000752.xml
Evaluating 751/1075: BIOMD0000000753.xml
Evaluating 752/1075: BIOMD0000000754.xml
Evaluating 753/1075: BIOMD0000000755.xml
Evaluating 754/1075: BIOMD0000000756.xml
Evaluating 755/1075: BIOMD0000000757.xml
Evaluating 756/1075: BIOMD0000000758.xml
Evaluating 757/1075: BIOMD0000000759.xml
Evaluating 758/1075: BIOMD0000000760.xml
Evaluating 759/1075: BIOMD0000000761.xml
Evaluating 760/1075: BIOMD0000000762.xml
Evaluating 761/1075: BIOMD0000000763.xml
Evaluating 762/1075: BIOMD0000000764.xml
Evaluating 763/1075: BIOMD0000000765.xml
Evaluating 764/1075: BIOMD0000000766.xml
Evaluating 765/1075: BIOMD0000000767.xml
Evaluating 766/1075: BIOMD0000000768.xml
Evaluating 767/1075: BIOMD0000000769.xml
Evaluating 768/1075: BIOMD0000000770.xml
Evaluating 769/1075: BIOMD0000000771.xml
Evaluating 770/1075: BIOMD0000000772.xml
Evaluating 771/1075: BIOMD0000000773.xml
Evaluating 772/1075: BIOMD0000000774.xml
Evaluating 773/1075: BIOMD0000000775.xml

2025-11-20 13:18:14,472 - WARNING - Skipping BIOMD0000000775.xml - no results generated
2025-11-20 13:18:14,478 - WARNING - Skipping BIOMD0000000776.xml - no results generated
2025-11-20 13:18:14,483 - WARNING - Skipping BIOMD0000000777.xml - no results generated
2025-11-20 13:18:14,493 - WARNING - Skipping BIOMD0000000778.xml - no results generated

Evaluating 774/1075: BIOMD0000000776.xml
Evaluating 775/1075: BIOMD0000000777.xml
Evaluating 776/1075: BIOMD0000000778.xml
Evaluating 777/1075: BIOMD0000000779.xml

2025-11-20 13:18:15,748 - WARNING - Skipping BIOMD0000000780.xml - no results generated
2025-11-20 13:18:15,754 - WARNING - Skipping BIOMD0000000781.xml - no results generated
2025-11-20 13:18:15,760 - WARNING - Skipping BIOMD0000000782.xml - no results generated
2025-11-20 13:18:15,764 - WARNING - Skipping BIOMD0000000783.xml - no results generated
2025-11-20 13:18:15,771 - WARNING - Skipping BIOMD0000000784.xml - no results generated
2025-11-20 13:18:15,775 - WARNING - Skipping BIOMD0000000785.xml - no results generated
2025-11-20 13:18:15,849 - WARNING - Skipping BIOMD0000000786.xml - no results generated
2025-11-20 13:18:15,856 - WARNING - Skipping BIOMD0000000787.xml - no results generated
2025-11-20 13:18:15,868 - WARNING - Skipping BIOMD0000000788.xml - no results generated
2025-11-20 13:18:15,874 - WARNING - Skipping BIOMD0000000789.xml - no results generated
2025-11-20 13:18:15,883 - WARNING - Skipping BIOMD0000000790.xml - no results generated
2025-11-20 13:18:15,892 - WARNING - Skipping BIOMD0000000791.xml - no results generated
2025-11-20 13:18:15,901 - WARNING - Skipping BIOMD0000000792.xml - no results generated
2025-11-20 13:18:15,906 - WARNING - Skipping BIOMD0000000793.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000779.txt
LLM response:
M_Chemotherapy_Drug (chemical): "chemotherapy drug", "anticancer drug", "cytotoxic agent"
Reason: The species is named "M_Chemotherapy_Drug" and is involved in a model of cancer chemo-immunotherapy, indicating that it is a chemical substance used to treat cancer. The lack of more specific information about its composition or mechanism of action makes "chemotherapy drug" the most general and likely name, with "anticancer drug" and "cytotoxic agent" being common synonyms in the context of cancer treatment.
Synonyms dict: {'M_Chemotherapy_Drug': ['chemotherapy drug', 'anticancer drug', 'cytotoxic agent']}
Evaluating 778/1075: BIOMD0000000780.xml
Evaluating 779/1075: BIOMD0000000781.xml
Evaluating 780/1075: BIOMD0000000782.xml
Evaluating 781/1075: BIOMD0000000783.xml
Evaluating 782/1075: BIOMD0000000784.xml
Evaluating 783/1075: BIOMD0000000785.xml
Evaluating 784/1075: BIOMD0000000786.xml
Evaluating 785/1075: BIOMD0000000787.xml
Evaluating 786/1075: BIOMD0000000788.xml
Evaluating 787/1075: BIOMD0000000789.xml
Evaluating 788/1075: BIOMD0000000790.xml
Evaluating 789/1075: BIOMD0000000791.xml
Evaluating 790/1075: BIOMD0000000792.xml
Evaluating 791/1075: BIOMD0000000793.xml
Evaluating 792/1075: BIOMD0000000794.xml

2025-11-20 13:18:15,976 - WARNING - Skipping BIOMD0000000794.xml - no results generated
2025-11-20 13:18:15,982 - WARNING - Skipping BIOMD0000000795.xml - no results generated
2025-11-20 13:18:15,995 - WARNING - Skipping BIOMD0000000796.xml - no results generated
2025-11-20 13:18:16,002 - WARNING - Skipping BIOMD0000000797.xml - no results generated
2025-11-20 13:18:16,010 - WARNING - Skipping BIOMD0000000798.xml - no results generated
2025-11-20 13:18:16,014 - WARNING - Skipping BIOMD0000000799.xml - no results generated
2025-11-20 13:18:16,019 - WARNING - Skipping BIOMD0000000800.xml - no results generated

Evaluating 793/1075: BIOMD0000000795.xml
Evaluating 794/1075: BIOMD0000000796.xml
Evaluating 795/1075: BIOMD0000000797.xml
Evaluating 796/1075: BIOMD0000000798.xml
Evaluating 797/1075: BIOMD0000000799.xml
Evaluating 798/1075: BIOMD0000000800.xml
Evaluating 799/1075: BIOMD0000000801.xml

2025-11-20 13:18:16,945 - WARNING - Skipping BIOMD0000000801.xml - no results generated
2025-11-20 13:18:16,958 - WARNING - Skipping BIOMD0000000802.xml - no results generated
2025-11-20 13:18:16,966 - WARNING - Skipping BIOMD0000000803.xml - no results generated
2025-11-20 13:18:16,979 - WARNING - Skipping BIOMD0000000804.xml - no results generated

Evaluating 800/1075: BIOMD0000000802.xml
Evaluating 801/1075: BIOMD0000000803.xml
Evaluating 802/1075: BIOMD0000000804.xml
Evaluating 803/1075: BIOMD0000000805.xml

2025-11-20 13:18:18,426 - WARNING - Skipping BIOMD0000000806.xml - no results generated
2025-11-20 13:18:18,439 - WARNING - Skipping BIOMD0000000807.xml - no results generated
2025-11-20 13:18:18,452 - WARNING - Skipping BIOMD0000000808.xml - no results generated
2025-11-20 13:18:18,460 - WARNING - Skipping BIOMD0000000809.xml - no results generated
2025-11-20 13:18:18,493 - WARNING - Skipping BIOMD0000000810.xml - no results generated
2025-11-20 13:18:18,509 - WARNING - Skipping BIOMD0000000811.xml - no results generated
2025-11-20 13:18:18,515 - WARNING - Skipping BIOMD0000000812.xml - no results generated
2025-11-20 13:18:18,521 - WARNING - Skipping BIOMD0000000813.xml - no results generated
2025-11-20 13:18:18,530 - WARNING - Skipping BIOMD0000000814.xml - no results generated
2025-11-20 13:18:18,535 - WARNING - Skipping BIOMD0000000815.xml - no results generated
2025-11-20 13:18:18,548 - WARNING - Skipping BIOMD0000000816.xml - no results generated
2025-11-20 13:18:18,560 - WARNING - Skipping BIOMD0000000817.xml - no results generated
2025-11-20 13:18:18,569 - WARNING - Skipping BIOMD0000000818.xml - no results generated
2025-11-20 13:18:18,588 - WARNING - Skipping BIOMD0000000819.xml - no results generated
2025-11-20 13:18:18,594 - WARNING - Skipping BIOMD0000000820.xml - no results generated
2025-11-20 13:18:18,600 - WARNING - Skipping BIOMD0000000821.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000805.txt
LLM response:
Li (chemical): "lactate", "lactic acid", "CH3CH(OH)COO-"
Le (chemical): "H+", "hydrogen ion", "proton"
Reason: Based on the model description and reaction equations, Li is likely lactate, a chemical involved in pH regulation, and Le is likely H+, a hydrogen ion, which plays a crucial role in pH control and is a reactant in the model's reactions. The names are chosen based on their relevance to the context of pH regulation and lactate metabolism in tumor cells.
Synonyms dict: {'Li': ['lactate', 'lactic acid', 'CH3CH(OH)COO-'], 'Le': ['H+', 'hydrogen ion', 'proton']}
Evaluating 804/1075: BIOMD0000000806.xml
Evaluating 805/1075: BIOMD0000000807.xml
Evaluating 806/1075: BIOMD0000000808.xml
Evaluating 807/1075: BIOMD0000000809.xml
Evaluating 808/1075: BIOMD0000000810.xml
Evaluating 809/1075: BIOMD0000000811.xml
Evaluating 810/1075: BIOMD0000000812.xml
Evaluating 811/1075: BIOMD0000000813.xml
Evaluating 812/1075: BIOMD0000000814.xml
Evaluating 813/1075: BIOMD0000000815.xml
Evaluating 814/1075: BIOMD0000000816.xml
Evaluating 815/1075: BIOMD0000000817.xml
Evaluating 816/1075: BIOMD0000000818.xml
Evaluating 817/1075: BIOMD0000000819.xml
Evaluating 818/1075: BIOMD0000000820.xml
Evaluating 819/1075: BIOMD0000000821.xml
Evaluating 820/1075: BIOMD0000000822.xml

2025-11-20 13:18:21,009 - WARNING - Skipping BIOMD0000000823.xml - no results generated
2025-11-20 13:18:21,012 - WARNING - Skipping BIOMD0000000824.xml - no results generated
2025-11-20 13:18:21,017 - WARNING - Skipping BIOMD0000000825.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000822.txt
LLM response:
Cytosolic_Rapamycin (chemical): "Rapamycin", "Sirolimus", "AY-22989"
mTOR_Rapamycin (complex): "mTOR:Rapamycin", "mTOR-Rapamycin complex", "Rapamycin-bound mTOR"
mTORC1_Rapamycin (complex): "mTORC1:Rapamycin", "mTORC1-Rapamycin complex", "Rapamycin-bound mTORC1"
Reason: Cytosolic_Rapamycin is a chemical as it refers to the drug Rapamycin in the cytosol. mTOR_Rapamycin and mTORC1_Rapamycin are complexes as they represent the binding of Rapamycin to the mTOR and mTORC1 proteins, respectively. The display names and reactions in the model suggest these bindings, and the notes provide context on the role of Rapamycin in inhibiting mTOR complexes.
Synonyms dict: {'Cytosolic_Rapamycin': ['Rapamycin', 'Sirolimus', 'AY-22989'], 'mTOR_Rapamycin': ['mTOR:Rapamycin', 'mTOR-Rapamycin complex', 'Rapamycin-bound mTOR'], 'mTORC1_Rapamycin': ['mTORC1:Rapamycin', 'mTORC1-Rapamycin complex', 'Rapamycin-bound mTORC1']}
Evaluating 821/1075: BIOMD0000000823.xml
Evaluating 822/1075: BIOMD0000000824.xml
Evaluating 823/1075: BIOMD0000000825.xml
Evaluating 824/1075: BIOMD0000000826.xml

2025-11-20 13:18:21,975 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:18:21,975 - WARNING - Skipping BIOMD0000000826.xml - no results generated

Evaluating 825/1075: BIOMD0000000827.xml

2025-11-20 13:18:23,643 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:18:23,644 - WARNING - Skipping BIOMD0000000827.xml - no results generated

Evaluating 826/1075: BIOMD0000000828.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000828.txt
LLM response:
Glucose_G (chemical): "Glucose", "D-Glucose", "Blood sugar"
Reason: Glucose_G is likely a chemical because it is mentioned as being controlled and administered intravenously to activate miR-451, and glucose is a well-known simple sugar and energy source for cells. The display name "Glucose G" suggests it is glucose, and the context of the model is regulating cellular signaling pathways, which involves biochemical interactions.
Synonyms dict: {'Glucose_G': ['Glucose', 'D-Glucose', 'Blood sugar']}
Evaluating 827/1075: BIOMD0000000829.xml

2025-11-20 13:18:26,169 - WARNING - Skipping BIOMD0000000830.xml - no results generated
2025-11-20 13:18:26,176 - WARNING - Skipping BIOMD0000000831.xml - no results generated
2025-11-20 13:18:26,197 - WARNING - Skipping BIOMD0000000832.xml - no results generated
2025-11-20 13:18:26,243 - WARNING - Skipping BIOMD0000000833.xml - no results generated
2025-11-20 13:18:26,285 - WARNING - Skipping BIOMD0000000834.xml - no results generated
2025-11-20 13:18:26,327 - WARNING - Skipping BIOMD0000000835.xml - no results generated
2025-11-20 13:18:26,330 - WARNING - Skipping BIOMD0000000836.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000829.txt
LLM response:
Glucose_G (chemical): "Glucose", "D-Glucose", "Blood sugar"
Reason: Glucose_G is likely a chemical entity as it is mentioned to be controlled and administered to regulate intracellular signaling pathways, and glucose is a common chemical name in biological contexts. The model's focus on cell cycle dynamics and glioblastoma signaling pathways also supports this classification, as glucose is a key energy source for cells and plays a role in various cellular processes.
Synonyms dict: {'Glucose_G': ['Glucose', 'D-Glucose', 'Blood sugar']}
Evaluating 828/1075: BIOMD0000000830.xml
Evaluating 829/1075: BIOMD0000000831.xml
Evaluating 830/1075: BIOMD0000000832.xml
Evaluating 831/1075: BIOMD0000000833.xml
Evaluating 832/1075: BIOMD0000000834.xml
Evaluating 833/1075: BIOMD0000000835.xml
Evaluating 834/1075: BIOMD0000000836.xml
Evaluating 835/1075: BIOMD0000000837.xml

2025-11-20 13:18:26,342 - WARNING - Skipping BIOMD0000000837.xml - no results generated
2025-11-20 13:18:26,348 - WARNING - Skipping BIOMD0000000838.xml - no results generated
2025-11-20 13:18:26,359 - WARNING - Skipping BIOMD0000000839.xml - no results generated
2025-11-20 13:18:26,366 - WARNING - Skipping BIOMD0000000840.xml - no results generated
2025-11-20 13:18:26,371 - WARNING - Skipping BIOMD0000000841.xml - no results generated

Evaluating 836/1075: BIOMD0000000838.xml
Evaluating 837/1075: BIOMD0000000839.xml
Evaluating 838/1075: BIOMD0000000840.xml
Evaluating 839/1075: BIOMD0000000841.xml
Evaluating 840/1075: BIOMD0000000842.xml

2025-11-20 13:18:28,543 - WARNING - Skipping BIOMD0000000843.xml - no results generated
2025-11-20 13:18:28,560 - WARNING - Skipping BIOMD0000000844.xml - no results generated
2025-11-20 13:18:28,566 - WARNING - Skipping BIOMD0000000845.xml - no results generated
2025-11-20 13:18:28,573 - WARNING - Skipping BIOMD0000000846.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000842.txt
LLM response:
PIP2 (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PtdIns(4,5)P2", "PIP2"
DAG (chemical): "Diacylglycerol", "Diglyceride", "DAG"
Reason: PIP2 and DAG are both well-known chemical species involved in cell signaling pathways, particularly in the phospholipase C (PLC) signaling pathway, which is related to GPCR signaling as described in the model. Their roles as chemical intermediates in the reactions provided also support their classification as chemicals.
Synonyms dict: {'PIP2': ['Phosphatidylinositol 4,5-bisphosphate', 'PtdIns(4,5)P2', 'PIP2'], 'DAG': ['Diacylglycerol', 'Diglyceride', 'DAG']}
Evaluating 841/1075: BIOMD0000000843.xml
Evaluating 842/1075: BIOMD0000000844.xml
Evaluating 843/1075: BIOMD0000000845.xml
Evaluating 844/1075: BIOMD0000000846.xml
Evaluating 845/1075: BIOMD0000000847.xml

2025-11-20 13:18:31,242 - WARNING - Skipping BIOMD0000000848.xml - no results generated
2025-11-20 13:18:31,325 - WARNING - Skipping BIOMD0000000849.xml - no results generated
2025-11-20 13:18:31,330 - WARNING - Skipping BIOMD0000000850.xml - no results generated
2025-11-20 13:18:31,335 - WARNING - Skipping BIOMD0000000851.xml - no results generated
2025-11-20 13:18:31,347 - WARNING - Skipping BIOMD0000000852.xml - no results generated
2025-11-20 13:18:31,358 - WARNING - Skipping BIOMD0000000853.xml - no results generated
2025-11-20 13:18:31,364 - WARNING - Skipping BIOMD0000000854.xml - no results generated
2025-11-20 13:18:31,374 - WARNING - Skipping BIOMD0000000855.xml - no results generated
2025-11-20 13:18:31,391 - WARNING - Skipping BIOMD0000000856.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000847.txt
LLM response:
X_1 (chemical): "phenylalanine", "L-phenylalanine", "Phe"
X_2 (chemical): "shikimate", "shikimic acid", "3,4,5-trihydroxy-1-cyclohexene-1-carboxylic acid"
X_3 (chemical): "chorismate", "chorismic acid", "4-((1-carboxyvinyl)oxy)-3-hydroxybenzoic acid"
X_4 (chemical): "prephenate", "prephenic acid", "3-((2-carboxyphenyl)amino)-3-oxopropanoic acid"
Reason: The model is related to phenylalanine metabolism in plants, and shikimate is mentioned as an influencing factor. Based on the reactions, X_1 is likely the substrate phenylalanine, X_2 is shikimate, X_3 is chorismate (an intermediate in the shikimate pathway), and X_4 is prephenate (another intermediate in the pathway). The reactions and notes suggest a biochemical pathway, so all species are likely chemicals.
Synonyms dict: {'X_1': ['phenylalanine', 'L-phenylalanine', 'Phe'], 'X_2': ['shikimate', 'shikimic acid', '3,4,5-trihydroxy-1-cyclohexene-1-carboxylic acid'], 'X_3': ['chorismate', 'chorismic acid', '4-((1-carboxyvinyl)oxy)-3-hydroxybenzoic acid'], 'X_4': ['prephenate', 'prephenic acid', '3-((2-carboxyphenyl)amino)-3-oxopropanoic acid']}
Evaluating 846/1075: BIOMD0000000848.xml
Evaluating 847/1075: BIOMD0000000849.xml
Evaluating 848/1075: BIOMD0000000850.xml
Evaluating 849/1075: BIOMD0000000851.xml
Evaluating 850/1075: BIOMD0000000852.xml
Evaluating 851/1075: BIOMD0000000853.xml
Evaluating 852/1075: BIOMD0000000854.xml
Evaluating 853/1075: BIOMD0000000855.xml
Evaluating 854/1075: BIOMD0000000856.xml
Evaluating 855/1075: BIOMD0000000857.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000857.txt
LLM response:
sucr (chemical): "sucrose", "table sugar", "saccharose"
Ephe (unknown): "UNK"
N (chemical): "nitrogen", "nitrate", "ammonia"
Next (unknown): "UNK"
Enitrate (chemical): "nitrate", "nitric acid", "nitrite"
ECO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
Reason: sucr is likely sucrose due to its involvement in reactions related to starch and trioseP, which are related to carbohydrate metabolism. Ephe and Next are unknown due to lack of information about their reactants or products. N is likely related to nitrogen or nitrate due to the model's focus on nitrate fertilization. Enitrate is likely nitrate due to its name and the model's context. ECO2 is likely carbon dioxide due to its name and the model's focus on carbon flux.
Synonyms dict: {'sucr': ['sucrose', 'table sugar', 'saccharose'], 'Ephe': ['UNK'], 'N': ['nitrogen', 'nitrate', 'ammonia'], 'Next': ['UNK'], 'Enitrate': ['nitrate', 'nitric acid', 'nitrite'], 'ECO2': ['carbon dioxide', 'CO2', 'carbonic acid']}
Evaluating 856/1075: BIOMD0000000858.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000858.txt
LLM response:
sucr (chemical): "sucrose", "table sugar", "saccharose"
Ephe (unknown): "UNK"
N (chemical): "nitrogen", "nitrate", "ammonia"
Next (unknown): "UNK"
Enitrate (chemical): "nitrate", "nitric acid", "nitrate ion"
ECO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"

Reason: sucr is likely sucrose, a common sugar, given its involvement in reactions with starch and trioseP, and the model's focus on carbon partitioning. Ephe and Next are unknown due to lack of information about their reactants or products. N is likely a nitrogen source, given the model's consideration of nitrate fertilization. Enitrate is likely nitrate, given its name and the model's context. ECO2 is likely carbon dioxide, given its name and the model's focus on photosynthetic activity.
Synonyms dict: {'sucr': ['sucrose', 'table sugar', 'saccharose'], 'Ephe': ['UNK'], 'N': ['nitrogen', 'nitrate', 'ammonia'], 'Next': ['UNK'], 'Enitrate': ['nitrate', 'nitric acid', 'nitrate ion'], 'ECO2': ['carbon dioxide', 'CO2', 'carbonic acid']}
Evaluating 857/1075: BIOMD0000000859.xml

2025-11-20 13:18:37,590 - WARNING - Skipping BIOMD0000000860.xml - no results generated
2025-11-20 13:18:37,611 - WARNING - Skipping BIOMD0000000861.xml - no results generated
2025-11-20 13:18:37,617 - WARNING - Skipping BIOMD0000000862.xml - no results generated
2025-11-20 13:18:37,629 - WARNING - Skipping BIOMD0000000863.xml - no results generated
2025-11-20 13:18:37,634 - WARNING - Skipping BIOMD0000000864.xml - no results generated
2025-11-20 13:18:37,643 - WARNING - Skipping BIOMD0000000865.xml - no results generated
2025-11-20 13:18:37,648 - WARNING - Skipping BIOMD0000000866.xml - no results generated
2025-11-20 13:18:37,664 - WARNING - Skipping BIOMD0000000867.xml - no results generated
2025-11-20 13:18:37,670 - WARNING - Skipping BIOMD0000000868.xml - no results generated
2025-11-20 13:18:37,675 - WARNING - Skipping BIOMD0000000869.xml - no results generated
2025-11-20 13:18:37,682 - WARNING - Skipping BIOMD0000000870.xml - no results generated
2025-11-20 13:18:37,691 - WARNING - Skipping BIOMD0000000871.xml - no results generated
2025-11-20 13:18:37,761 - WARNING - Skipping BIOMD0000000872.xml - no results generated
2025-11-20 13:18:37,782 - WARNING - Skipping BIOMD0000000873.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000859.txt
LLM response:
sucr (chemical): "sucrose", "table sugar", "saccharose"
Ephe (unknown): "UNK"
N (chemical): "nitrogen", "nitrate", "ammonia"
Next (unknown): "UNK"
Enitrate (chemical): "nitrate", "nitric acid", "nitric oxide"
ECO2 (chemical): "carbon dioxide", "CO2", "carbonic acid"
Reason: sucr is likely sucrose due to its involvement in starch metabolism and carbon flux. Ephe and Next are unknown due to lack of information. N is likely related to nitrogen or nitrate given the model's focus on nitrate fertilization. Enitrate is likely nitrate due to its name and the model's context. ECO2 is likely carbon dioxide given its abbreviation and the model's focus on photosynthetic activity and carbon metabolism.
Synonyms dict: {'sucr': ['sucrose', 'table sugar', 'saccharose'], 'Ephe': ['UNK'], 'N': ['nitrogen', 'nitrate', 'ammonia'], 'Next': ['UNK'], 'Enitrate': ['nitrate', 'nitric acid', 'nitric oxide'], 'ECO2': ['carbon dioxide', 'CO2', 'carbonic acid']}
Evaluating 858/1075: BIOMD0000000860.xml
Evaluating 859/1075: BIOMD0000000861.xml
Evaluating 860/1075: BIOMD0000000862.xml
Evaluating 861/1075: BIOMD0000000863.xml
Evaluating 862/1075: BIOMD0000000864.xml
Evaluating 863/1075: BIOMD0000000865.xml
Evaluating 864/1075: BIOMD0000000866.xml
Evaluating 865/1075: BIOMD0000000867.xml
Evaluating 866/1075: BIOMD0000000868.xml
Evaluating 867/1075: BIOMD0000000869.xml
Evaluating 868/1075: BIOMD0000000870.xml
Evaluating 869/1075: BIOMD0000000871.xml
Evaluating 870/1075: BIOMD0000000872.xml
Evaluating 871/1075: BIOMD0000000873.xml
Evaluating 872/1075: BIOMD0000000874.xml

2025-11-20 13:18:37,789 - WARNING - Skipping BIOMD0000000874.xml - no results generated
2025-11-20 13:18:37,795 - WARNING - Skipping BIOMD0000000875.xml - no results generated
2025-11-20 13:18:37,802 - WARNING - Skipping BIOMD0000000876.xml - no results generated
2025-11-20 13:18:37,809 - WARNING - Skipping BIOMD0000000877.xml - no results generated
2025-11-20 13:18:37,816 - WARNING - Skipping BIOMD0000000878.xml - no results generated

Evaluating 873/1075: BIOMD0000000875.xml
Evaluating 874/1075: BIOMD0000000876.xml
Evaluating 875/1075: BIOMD0000000877.xml
Evaluating 876/1075: BIOMD0000000878.xml
Evaluating 877/1075: BIOMD0000000879.xml

2025-11-20 13:18:39,152 - WARNING - Skipping BIOMD0000000879.xml - no results generated
2025-11-20 13:18:39,173 - WARNING - Skipping BIOMD0000000880.xml - no results generated
2025-11-20 13:18:39,185 - WARNING - Skipping BIOMD0000000881.xml - no results generated
2025-11-20 13:18:39,193 - WARNING - Skipping BIOMD0000000882.xml - no results generated

Evaluating 878/1075: BIOMD0000000880.xml
Evaluating 879/1075: BIOMD0000000881.xml
Evaluating 880/1075: BIOMD0000000882.xml
Evaluating 881/1075: BIOMD0000000883.xml

2025-11-20 13:18:41,653 - WARNING - Skipping BIOMD0000000884.xml - no results generated
2025-11-20 13:18:41,657 - WARNING - Skipping BIOMD0000000885.xml - no results generated
2025-11-20 13:18:41,664 - WARNING - Skipping BIOMD0000000886.xml - no results generated
2025-11-20 13:18:41,670 - WARNING - Skipping BIOMD0000000887.xml - no results generated
2025-11-20 13:18:41,677 - WARNING - Skipping BIOMD0000000888.xml - no results generated
2025-11-20 13:18:41,690 - WARNING - Skipping BIOMD0000000889.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000883.txt
LLM response:
PIP3Active (chemical): "Phosphatidylinositol 3,4,5-trisphosphate", "PIP3", "PtdIns(3,4,5)P3"
PIP3Inactive (chemical): "Phosphatidylinositol 4,5-bisphosphate", "PIP2", "PtdIns(4,5)P2"
PLX4032 (chemical): "Vemurafenib", "PLX4032", "RG7204"
Reason: PIP3Active and PIP3Inactive are likely chemical species as they represent different phosphorylation states of phosphatidylinositol, a type of lipid. PLX4032 is a chemical species as it is a known inhibitor of BRAF kinase, specifically Vemurafenib, which is used in cancer treatment.
Synonyms dict: {'PIP3Active': ['Phosphatidylinositol 3,4,5-trisphosphate', 'PIP3', 'PtdIns(3,4,5)P3'], 'PIP3Inactive': ['Phosphatidylinositol 4,5-bisphosphate', 'PIP2', 'PtdIns(4,5)P2'], 'PLX4032': ['Vemurafenib', 'PLX4032', 'RG7204']}
Evaluating 882/1075: BIOMD0000000884.xml
Evaluating 883/1075: BIOMD0000000885.xml
Evaluating 884/1075: BIOMD0000000886.xml
Evaluating 885/1075: BIOMD0000000887.xml
Evaluating 886/1075: BIOMD0000000888.xml
Evaluating 887/1075: BIOMD0000000889.xml
Evaluating 888/1075: BIOMD0000000890.xml

2025-11-20 13:18:43,097 - WARNING - Skipping BIOMD0000000891.xml - no results generated
2025-11-20 13:18:43,104 - WARNING - Skipping BIOMD0000000892.xml - no results generated
2025-11-20 13:18:43,110 - WARNING - Skipping BIOMD0000000893.xml - no results generated
2025-11-20 13:18:43,115 - WARNING - Skipping BIOMD0000000894.xml - no results generated
2025-11-20 13:18:43,130 - WARNING - Skipping BIOMD0000000895.xml - no results generated
2025-11-20 13:18:43,141 - WARNING - Skipping BIOMD0000000896.xml - no results generated
2025-11-20 13:18:43,145 - WARNING - Skipping BIOMD0000000897.xml - no results generated
2025-11-20 13:18:43,153 - WARNING - Skipping BIOMD0000000898.xml - no results generated
2025-11-20 13:18:43,200 - WARNING - Skipping BIOMD0000000899.xml - no results generated
2025-11-20 13:18:43,205 - WARNING - Skipping BIOMD0000000900.xml - no results generated
2025-11-20 13:18:43,209 - WARNING - Skipping BIOMD0000000901.xml - no results generated
2025-11-20 13:18:43,215 - WARNING - Skipping BIOMD0000000902.xml - no results generated
2025-11-20 13:18:43,221 - WARNING - Skipping BIOMD0000000903.xml - no results generated
2025-11-20 13:18:43,227 - WARNING - Skipping BIOMD0000000904.xml - no results generated
2025-11-20 13:18:43,233 - WARNING - Skipping BIOMD0000000905.xml - no results generated
2025-11-20 13:18:43,237 - WARNING - Skipping BIOMD0000000906.xml - no results generated
2025-11-20 13:18:43,253 - WARNING - Skipping BIOMD0000000907.xml - no results generated
2025-11-20 13:18:43,262 - WARNING - Skipping BIOMD0000000908.xml - no results generated
2025-11-20 13:18:43,268 - WARNING - Skipping BIOMD0000000909.xml - no results generated
2025-11-20 13:18:43,273 - WARNING - Skipping BIOMD0000000910.xml - no results generated
2025-11-20 13:18:43,278 - WARNING - Skipping BIOMD0000000911.xml - no results generated
2025-11-20 13:18:43,283 - WARNING - Skipping BIOMD0000000912.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000890.txt
LLM response:
c (chemical): "cholesterol", "cholest-5-en-3-beta-ol", "chol"
Reason: The model is about the cholesterol biosynthesis pathway, and the reaction suggests that 'c' is being produced and consumed, which is consistent with cholesterol being a chemical intermediate in this pathway. The lack of a specific display name for 'c' makes it difficult to determine a more specific identity, but given the context, cholesterol is a likely candidate.
Synonyms dict: {'c': ['cholesterol', 'cholest-5-en-3-beta-ol', 'chol']}
Evaluating 889/1075: BIOMD0000000891.xml
Evaluating 890/1075: BIOMD0000000892.xml
Evaluating 891/1075: BIOMD0000000893.xml
Evaluating 892/1075: BIOMD0000000894.xml
Evaluating 893/1075: BIOMD0000000895.xml
Evaluating 894/1075: BIOMD0000000896.xml
Evaluating 895/1075: BIOMD0000000897.xml
Evaluating 896/1075: BIOMD0000000898.xml
Evaluating 897/1075: BIOMD0000000899.xml
Evaluating 898/1075: BIOMD0000000900.xml
Evaluating 899/1075: BIOMD0000000901.xml
Evaluating 900/1075: BIOMD0000000902.xml
Evaluating 901/1075: BIOMD0000000903.xml
Evaluating 902/1075: BIOMD0000000904.xml
Evaluating 903/1075: BIOMD0000000905.xml
Evaluating 904/1075: BIOMD0000000906.xml
Evaluating 905/1075: BIOMD0000000907.xml
Evaluating 906/1075: BIOMD0000000908.xml
Evaluating 907/1075: BIOMD0000000909.xml
Evaluating 908/1075: BIOMD0000000910.xml
Evaluating 909/1075: BIOMD0000000911.xml
Evaluating 910/1075: BIOMD0000000912.xml
Evaluating 911/1075: BIOMD0000000913.xml

2025-11-20 13:18:43,292 - WARNING - Skipping BIOMD0000000913.xml - no results generated
2025-11-20 13:18:43,297 - WARNING - Skipping BIOMD0000000914.xml - no results generated
2025-11-20 13:18:43,307 - WARNING - Skipping BIOMD0000000915.xml - no results generated
2025-11-20 13:18:43,313 - WARNING - Skipping BIOMD0000000916.xml - no results generated
2025-11-20 13:18:43,321 - WARNING - Skipping BIOMD0000000917.xml - no results generated
2025-11-20 13:18:43,330 - WARNING - Skipping BIOMD0000000918.xml - no results generated
2025-11-20 13:18:43,334 - WARNING - Skipping BIOMD0000000919.xml - no results generated
2025-11-20 13:18:43,342 - WARNING - Skipping BIOMD0000000920.xml - no results generated
2025-11-20 13:18:43,352 - WARNING - Skipping BIOMD0000000921.xml - no results generated
2025-11-20 13:18:43,357 - WARNING - Skipping BIOMD0000000922.xml - no results generated
2025-11-20 13:18:43,363 - WARNING - Skipping BIOMD0000000923.xml - no results generated
2025-11-20 13:18:43,371 - WARNING - Skipping BIOMD0000000924.xml - no results generated
2025-11-20 13:18:43,424 - WARNING - Skipping BIOMD0000000925.xml - no results generated
2025-11-20 13:18:43,446 - WARNING - Skipping BIOMD0000000926.xml - no results generated

Evaluating 912/1075: BIOMD0000000914.xml
Evaluating 913/1075: BIOMD0000000915.xml
Evaluating 914/1075: BIOMD0000000916.xml
Evaluating 915/1075: BIOMD0000000917.xml
Evaluating 916/1075: BIOMD0000000918.xml
Evaluating 917/1075: BIOMD0000000919.xml
Evaluating 918/1075: BIOMD0000000920.xml
Evaluating 919/1075: BIOMD0000000921.xml
Evaluating 920/1075: BIOMD0000000922.xml
Evaluating 921/1075: BIOMD0000000923.xml
Evaluating 922/1075: BIOMD0000000924.xml
Evaluating 923/1075: BIOMD0000000925.xml
Evaluating 924/1075: BIOMD0000000926.xml
Evaluating 925/1075: BIOMD0000000927.xml

2025-11-20 13:18:44,696 - WARNING - Skipping BIOMD0000000928.xml - no results generated
2025-11-20 13:18:44,710 - WARNING - Skipping BIOMD0000000929.xml - no results generated
2025-11-20 13:18:44,719 - WARNING - Skipping BIOMD0000000930.xml - no results generated
2025-11-20 13:18:44,724 - WARNING - Skipping BIOMD0000000931.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000927.txt
LLM response:
IAA (chemical): "indole-3-acetic acid", "indole-3-butyric acid", "auxin"
Reason: IAA is likely a chemical because it is mentioned as a phytohormone, specifically auxin, which is a plant hormone involved in signaling. The display name "IAA" is commonly used as an abbreviation for indole-3-acetic acid, a type of auxin. The reactions also suggest that IAA is a signaling molecule, which further supports its classification as a chemical.
Synonyms dict: {'IAA': ['indole-3-acetic acid', 'indole-3-butyric acid', 'auxin']}
Evaluating 926/1075: BIOMD0000000928.xml
Evaluating 927/1075: BIOMD0000000929.xml
Evaluating 928/1075: BIOMD0000000930.xml
Evaluating 929/1075: BIOMD0000000931.xml
Evaluating 930/1075: BIOMD0000000932.xml

2025-11-20 13:18:46,001 - WARNING - Skipping BIOMD0000000932.xml - no results generated
2025-11-20 13:18:46,017 - WARNING - Skipping BIOMD0000000933.xml - no results generated
2025-11-20 13:18:46,041 - WARNING - Skipping BIOMD0000000934.xml - no results generated
2025-11-20 13:18:46,048 - WARNING - Skipping BIOMD0000000935.xml - no results generated
2025-11-20 13:18:46,052 - WARNING - Skipping BIOMD0000000936.xml - no results generated
2025-11-20 13:18:46,059 - WARNING - Skipping BIOMD0000000937.xml - no results generated
2025-11-20 13:18:46,067 - WARNING - Skipping BIOMD0000000938.xml - no results generated
2025-11-20 13:18:46,133 - WARNING - Skipping BIOMD0000000939.xml - no results generated
2025-11-20 13:18:46,156 - WARNING - Skipping BIOMD0000000940.xml - no results generated
2025-11-20 13:18:46,166 - WARNING - Skipping BIOMD0000000941.xml - no results generated
2025-11-20 13:18:46,177 - WARNING - Skipping BIOMD0000000942.xml - no results generated

Evaluating 931/1075: BIOMD0000000933.xml
Evaluating 932/1075: BIOMD0000000934.xml
Evaluating 933/1075: BIOMD0000000935.xml
Evaluating 934/1075: BIOMD0000000936.xml
Evaluating 935/1075: BIOMD0000000937.xml
Evaluating 936/1075: BIOMD0000000938.xml
Evaluating 937/1075: BIOMD0000000939.xml
Evaluating 938/1075: BIOMD0000000940.xml
Evaluating 939/1075: BIOMD0000000941.xml
Evaluating 940/1075: BIOMD0000000942.xml
Evaluating 941/1075: BIOMD0000000943.xml

2025-11-20 13:18:46,218 - WARNING - Skipping BIOMD0000000943.xml - no results generated
2025-11-20 13:18:46,224 - WARNING - Skipping BIOMD0000000944.xml - no results generated
2025-11-20 13:18:46,232 - WARNING - Skipping BIOMD0000000945.xml - no results generated
2025-11-20 13:18:46,241 - WARNING - Skipping BIOMD0000000946.xml - no results generated

Evaluating 942/1075: BIOMD0000000944.xml
Evaluating 943/1075: BIOMD0000000945.xml
Evaluating 944/1075: BIOMD0000000946.xml
Evaluating 945/1075: BIOMD0000000947.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000947.txt
LLM response:
C_para_Apical (chemical): "paracetamol", "acetaminophen", "APAP"
C_para_Caco_2 (chemical): "paracetamol", "acetaminophen", "APAP"
C_para__Basolateral___HepG2_ (chemical): "paracetamol", "acetaminophen", "APAP"
C_sulf_Apical (chemical): "paracetamol sulfate", "acetaminophen sulfate", "APAP sulfate"
C_sulf_Caco_2 (chemical): "paracetamol sulfate", "acetaminophen sulfate", "APAP sulfate"
C_sulf__Basolateral___HepG2_ (chemical): "paracetamol sulfate", "acetaminophen sulfate", "APAP sulfate"
C_glu_Apical (chemical): "paracetamol glucuronide", "acetaminophen glucuronide", "APAP glucuronide"
C_glu_Caco_2 (chemical): "paracetamol glucuronide", "acetaminophen glucuronide", "APAP glucuronide"
C_glu__Basolateral___HepG2_ (chemical): "paracetamol glucuronide", "acetaminophen glucuronide", "APAP glucuronide"
Reason: The model is a first-pass metabolism PK model for paracetamol, and the species names suggest different locations (Apical, Caco_2, Basolateral, HepG2) and metabolic forms (para, sulf, glu) of paracetamol, indicating they are all chemical entities related to paracetamol and its metabolites.
Synonyms dict: {'C_para_Apical': ['paracetamol', 'acetaminophen', 'APAP'], 'C_para_Caco_2': ['paracetamol', 'acetaminophen', 'APAP'], 'C_para__Basolateral___HepG2_': ['paracetamol', 'acetaminophen', 'APAP'], 'C_sulf_Apical': ['paracetamol sulfate', 'acetaminophen sulfate', 'APAP sulfate'], 'C_sulf_Caco_2': ['paracetamol sulfate', 'acetaminophen sulfate', 'APAP sulfate'], 'C_sulf__Basolateral___HepG2_': ['paracetamol sulfate', 'acetaminophen sulfate', 'APAP sulfate'], 'C_glu_Apical': ['paracetamol glucuronide', 'acetaminophen glucuronide', 'APAP glucuronide'], 'C_glu_Caco_2': ['paracetamol glucuronide', 'acetaminophen glucuronide', 'APAP glucuronide'], 'C_glu__Basolateral___HepG2_': ['paracetamol glucuronide', 'acetaminophen glucuronide', 'APAP glucuronide']}
Evaluating 946/1075: BIOMD0000000948.xml

2025-11-20 13:18:51,308 - WARNING - Skipping BIOMD0000000949.xml - no results generated
2025-11-20 13:18:51,316 - WARNING - Skipping BIOMD0000000950.xml - no results generated
2025-11-20 13:18:51,340 - WARNING - Skipping BIOMD0000000951.xml - no results generated
2025-11-20 13:18:51,352 - WARNING - Skipping BIOMD0000000952.xml - no results generated
2025-11-20 13:18:51,371 - WARNING - Skipping BIOMD0000000953.xml - no results generated
2025-11-20 13:18:51,402 - WARNING - Skipping BIOMD0000000954.xml - no results generated
2025-11-20 13:18:51,415 - WARNING - Skipping BIOMD0000000955.xml - no results generated
2025-11-20 13:18:51,422 - WARNING - Skipping BIOMD0000000956.xml - no results generated
2025-11-20 13:18:51,426 - WARNING - Skipping BIOMD0000000957.xml - no results generated
2025-11-20 13:18:51,435 - WARNING - Skipping BIOMD0000000958.xml - no results generated
2025-11-20 13:18:51,472 - WARNING - Skipping BIOMD0000000959.xml - no results generated
2025-11-20 13:18:51,495 - WARNING - Skipping BIOMD0000000960.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000948.txt
LLM response:
AR_A1 (chemical): "alkylresorcinol", "AR", "resorcinol"
AR_A2 (chemical): "alkylresorcinol", "AR", "resorcinol"
AR_Central (unknown): "central compartment", "systemic circulation", "UNK"
AR_Dose (chemical): "alkylresorcinol dose", "AR dose", "resorcinol dose"
Reason: All species except AR_Central are likely related to alkylresorcinol, a chemical compound. AR_Central is unknown because it seems to represent a compartment or a system rather than a specific chemical or biological entity, given its role in the reactions as a central hub.
Synonyms dict: {'AR_A1': ['alkylresorcinol', 'AR', 'resorcinol'], 'AR_A2': ['alkylresorcinol', 'AR', 'resorcinol'], 'AR_Central': ['central compartment', 'systemic circulation', 'UNK'], 'AR_Dose': ['alkylresorcinol dose', 'AR dose', 'resorcinol dose']}
Evaluating 947/1075: BIOMD0000000949.xml
Evaluating 948/1075: BIOMD0000000950.xml
Evaluating 949/1075: BIOMD0000000951.xml
Evaluating 950/1075: BIOMD0000000952.xml
Evaluating 951/1075: BIOMD0000000953.xml
Evaluating 952/1075: BIOMD0000000954.xml
Evaluating 953/1075: BIOMD0000000955.xml
Evaluating 954/1075: BIOMD0000000956.xml
Evaluating 955/1075: BIOMD0000000957.xml
Evaluating 956/1075: BIOMD0000000958.xml
Evaluating 957/1075: BIOMD0000000959.xml
Evaluating 958/1075: BIOMD0000000960.xml
Evaluating 959/1075: BIOMD0000000961.xml

2025-11-20 13:19:11,684 - WARNING - Skipping BIOMD0000000962.xml - no results generated
2025-11-20 13:19:11,688 - WARNING - Skipping BIOMD0000000963.xml - no results generated
2025-11-20 13:19:11,698 - WARNING - Skipping BIOMD0000000964.xml - no results generated
2025-11-20 13:19:11,729 - WARNING - Skipping BIOMD0000000965.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000961.txt
LLM response:
s1 (chemical): "hydrogen ion", "proton", "H+"
s2 (chemical): "hydrogen ion", "proton", "H+"
s7 (chemical): "hydroxide ion", "OH-", "hydroxyl"
s8 (chemical): "hydroxide ion", "OH-", "hydroxyl"
s24 (chemical): "sodium ion", "Na+", "sodium"
s25 (chemical): "sodium ion", "Na+", "sodium"
s26 (chemical): "bicarbonate ion", "HCO3-", "hydrogen carbonate"
s27 (chemical): "bicarbonate ion", "HCO3-", "hydrogen carbonate"
s28 (chemical): "chloride ion", "Cl-", "chloride"
s29 (chemical): "chloride ion", "Cl-", "chloride"
s30 (chemical): "ATP", "adenosine triphosphate", "ATP molecule"
s31 (chemical): "ADP", "adenosine diphosphate", "ADP molecule"
s33 (chemical): "creatine phosphate", "CrP", "phosphocreatine"
s34 (chemical): "creatine", "Cr", "creatine molecule"
s35 (chemical): "AMP", "adenosine monophosphate", "AMP molecule"
s36 (chemical): "glycogen", "glycogen molecule", "animal starch"
s38 (chemical): "lactate", "lactic acid", "L-"
s39 (chemical): "lactate", "lactic acid", "L-"
s52 (chemical): "lactic acid", "lactate", "L-"
s56 (chemical): "glucose", "blood sugar", "dextrose"
s57 (chemical): "glucose-6-phosphate", "G6P", "glucose 6-phosphate"
s58 (chemical): "fructose-6-phosphate", "F6P", "fructose 6-phosphate"
s59 (chemical): "glyceraldehyde-3-phosphate", "GAP", "glyceraldehyde 3-phosphate"
s60 (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
s61 (chemical): "pyruvate", "PYR", "pyruvic acid"
s62 (chemical): "NAD+", "nicotinamide adenine dinucleotide", "NAD plus"
s63 (chemical): "NADH", "nicotinamide adenine dinucleotide", "NADH molecule"
s64 (chemical): "carbon dioxide", "CO2", "carbonic acid"
s65 (chemical): "oxygen", "O2", "dioxygen"
s66 (chemical): "fructose-1,6-bisphosphate", "F16BP", "fructose 1,6-bisphosphate"
s67 (chemical): "dihydroxyacetone phosphate", "DHAP", "dihydroxyacetonephosphate"
s68 (chemical): "1,3-bisphosphoglycerate", "13BPG", "1,3-bisphosphoglyceric acid"
s69 (chemical): "3-phosphoglycerate", "3PG", "3-phosphoglyceric acid"
s70 (chemical): "2-phosphoglycerate", "2PG", "2-phosphoglyceric acid"
s71 (chemical): "water", "H2O", "dihydrogen monoxide"
s72 (chemical): "glucose-1-phosphate", "G1P", "glucose 1-phosphate"
s73 (chemical): "UDP-glucose", "UDPG", "uridine diphosphate glucose"
s74 (chemical): "UTP", "uridine triphosphate", "UTP molecule"
s75 (chemical): "UDP", "uridine diphosphate", "UDP molecule"
s76 (chemical): "6-phosphogluconate", "6PGN", "6-phosphogluconic acid"
s77 (chemical): "glycerol-3-phosphate", "Glycerol-3-P", "glycerol phosphate"
s79 (chemical): "glucose-1,6-bisphosphate", "G16BP", "glucose 1,6-bisphosphate"
s81 (chemical): "oxygen", "O2", "dioxygen"
s82 (chemical): "oxygen", "O2", "dioxygen"
s83 (chemical): "myoglobin", "Mb", "myoglobin molecule"
s84 (chemical): "oxymyoglobin", "MbO2", "oxymyoglobin molecule"
s24 (chemical): "sodium ion", "Na+", "sodium"
s25 (chemical): "sodium ion", "Na+", "sodium"
s26 (chemical): "bicarbonate ion", "HCO3-", "hydrogen carbonate"
s27 (chemical): "bicarbonate ion", "HCO3-", "hydrogen carbonate"
s28 (chemical): "chloride ion", "Cl-", "chloride"
s29 (chemical): "chloride ion", "Cl-", "chloride"
s30 (chemical): "ATP", "adenosine triphosphate", "ATP molecule"
s31 (chemical): "ADP", "adenosine diphosphate", "ADP molecule"
s33 (chemical): "creatine phosphate", "CrP", "phosphocreatine"
s34 (chemical): "creatine", "Cr", "creatine molecule"
s35 (chemical): "AMP", "adenosine monophosphate", "AMP molecule"
s36 (chemical): "glycogen", "glycogen molecule", "animal starch"
s38 (chemical): "lactate", "lactic acid", "L-"
s39 (chemical): "lactate", "lactic acid", "L-"
s52 (chemical): "lactic acid", "lactate", "L-"
s56 (chemical): "glucose", "blood sugar", "dextrose"
s57 (chemical): "glucose-6-phosphate", "G6P", "glucose 6-phosphate"
s58 (chemical): "fructose-6-phosphate", "F6P", "fructose 6-phosphate"
s59 (chemical): "glyceraldehyde-3-phosphate", "GAP", "glyceraldehyde 3-phosphate"
s60 (chemical): "phosphoenolpyruvate", "PEP", "phosphoenolpyruvic acid"
s61 (chemical): "pyruvate", "PYR", "pyruvic acid"
s62 (chemical): "NAD+", "nicotinamide adenine dinucleotide", "NAD plus"
s63 (chemical): "NADH", "nicotinamide adenine dinucleotide", "NADH molecule"
s64 (chemical): "carbon dioxide", "CO2", "carbonic acid"
s65 (chemical): "oxygen", "O2", "dioxygen"
s66 (chemical): "fructose-1,6-bisphosphate", "F16BP", "fructose 1,6-bisphosphate"
s67 (chemical): "dihydroxyacetone phosphate", "DHAP", "dihydroxyacetonephosphate"
s68 (chemical): "1,3-bisphosphoglycerate", "13BPG", "1,3-bisphosphoglyceric acid"
s69 (chemical): "3-phosphoglycerate", "3PG", "3-phosphoglyceric acid"
s70 (chemical): "2-phosphoglycerate", "2PG", "2-phosphoglyceric acid"
s71 (chemical): "water", "H2O", "dihydrogen monoxide"
s72 (chemical): "glucose-1-phosphate", "G1P", "glucose 1-phosphate"
s73 (chemical): "UDP-glucose", "UDPG", "uridine diphosphate glucose"
s74 (chemical): "UTP", "uridine triphosphate", "UTP molecule"
s75 (chemical): "UDP", "uridine diphosphate", "UDP molecule"
s76 (chemical): "6-phosphogluconate", "6PGN", "6-phosphogluconic acid"
s77 (chemical): "glycerol-3-phosphate", "Glycerol-3-P", "glycerol phosphate"
s79 (chemical): "glucose-1,6-bisphosphate", "G16BP", "glucose 1,6-bisphosphate"
s81 (chemical): "oxygen", "O2", "dioxygen"
s82 (chemical): "oxygen", "O2", "dioxygen"
s83 (chemical): "myoglobin", "Mb", "myoglobin molecule"
s84 (chemical): "oxymyoglobin", "MbO2", "oxymyoglobin molecule"
Reason: Most of the species are identified as chemicals based on their names and roles in the metabolic reactions. The model appears to be focused on glycolytic metabolism, and the species are involved in various biochemical reactions, such as glycolysis, gluconeogenesis, and energy production. The species s83 and s84 are identified as proteins (myoglobin and oxymyoglobin), as they are involved in oxygen binding and transport. The other species are identified as chemicals, including ions, sugars, phosphates, and other metabolites.
Synonyms dict: {'s1': ['hydrogen ion', 'proton', 'H+'], 's2': ['hydrogen ion', 'proton', 'H+'], 's7': ['hydroxide ion', 'OH-', 'hydroxyl'], 's8': ['hydroxide ion', 'OH-', 'hydroxyl'], 's24': ['sodium ion', 'Na+', 'sodium'], 's25': ['sodium ion', 'Na+', 'sodium'], 's26': ['bicarbonate ion', 'HCO3-', 'hydrogen carbonate'], 's27': ['bicarbonate ion', 'HCO3-', 'hydrogen carbonate'], 's28': ['chloride ion', 'Cl-', 'chloride'], 's29': ['chloride ion', 'Cl-', 'chloride'], 's30': ['ATP', 'adenosine triphosphate', 'ATP molecule'], 's31': ['ADP', 'adenosine diphosphate', 'ADP molecule'], 's33': ['creatine phosphate', 'CrP', 'phosphocreatine'], 's34': ['creatine', 'Cr', 'creatine molecule'], 's35': ['AMP', 'adenosine monophosphate', 'AMP molecule'], 's36': ['glycogen', 'glycogen molecule', 'animal starch'], 's38': ['lactate', 'lactic acid', 'L-'], 's39': ['lactate', 'lactic acid', 'L-'], 's52': ['lactic acid', 'lactate', 'L-'], 's56': ['glucose', 'blood sugar', 'dextrose'], 's57': ['glucose-6-phosphate', 'G6P', 'glucose 6-phosphate'], 's58': ['fructose-6-phosphate', 'F6P', 'fructose 6-phosphate'], 's59': ['glyceraldehyde-3-phosphate', 'GAP', 'glyceraldehyde 3-phosphate'], 's60': ['phosphoenolpyruvate', 'PEP', 'phosphoenolpyruvic acid'], 's61': ['pyruvate', 'PYR', 'pyruvic acid'], 's62': ['NAD+', 'nicotinamide adenine dinucleotide', 'NAD plus'], 's63': ['NADH', 'nicotinamide adenine dinucleotide', 'NADH molecule'], 's64': ['carbon dioxide', 'CO2', 'carbonic acid'], 's65': ['oxygen', 'O2', 'dioxygen'], 's66': ['fructose-1,6-bisphosphate', 'F16BP', 'fructose 1,6-bisphosphate'], 's67': ['dihydroxyacetone phosphate', 'DHAP', 'dihydroxyacetonephosphate'], 's68': ['1,3-bisphosphoglycerate', '13BPG', '1,3-bisphosphoglyceric acid'], 's69': ['3-phosphoglycerate', '3PG', '3-phosphoglyceric acid'], 's70': ['2-phosphoglycerate', '2PG', '2-phosphoglyceric acid'], 's71': ['water', 'H2O', 'dihydrogen monoxide'], 's72': ['glucose-1-phosphate', 'G1P', 'glucose 1-phosphate'], 's73': ['UDP-glucose', 'UDPG', 'uridine diphosphate glucose'], 's74': ['UTP', 'uridine triphosphate', 'UTP molecule'], 's75': ['UDP', 'uridine diphosphate', 'UDP molecule'], 's76': ['6-phosphogluconate', '6PGN', '6-phosphogluconic acid'], 's77': ['glycerol-3-phosphate', 'Glycerol-3-P', 'glycerol phosphate'], 's79': ['glucose-1,6-bisphosphate', 'G16BP', 'glucose 1,6-bisphosphate'], 's81': ['oxygen', 'O2', 'dioxygen'], 's82': ['oxygen', 'O2', 'dioxygen'], 's83': ['myoglobin', 'Mb', 'myoglobin molecule'], 's84': ['oxymyoglobin', 'MbO2', 'oxymyoglobin molecule']}
Evaluating 960/1075: BIOMD0000000962.xml
Evaluating 961/1075: BIOMD0000000963.xml
Evaluating 962/1075: BIOMD0000000964.xml
Evaluating 963/1075: BIOMD0000000965.xml
Evaluating 964/1075: BIOMD0000000966.xml

2025-11-20 13:19:13,362 - WARNING - Skipping BIOMD0000000967.xml - no results generated
2025-11-20 13:19:13,373 - WARNING - Skipping BIOMD0000000968.xml - no results generated
2025-11-20 13:19:13,397 - WARNING - Skipping BIOMD0000000969.xml - no results generated
2025-11-20 13:19:13,402 - WARNING - Skipping BIOMD0000000970.xml - no results generated
2025-11-20 13:19:13,413 - WARNING - Skipping BIOMD0000000971.xml - no results generated
2025-11-20 13:19:13,423 - WARNING - Skipping BIOMD0000000972.xml - no results generated
2025-11-20 13:19:13,429 - WARNING - Skipping BIOMD0000000973.xml - no results generated
2025-11-20 13:19:13,434 - WARNING - Skipping BIOMD0000000974.xml - no results generated
2025-11-20 13:19:13,467 - WARNING - Skipping BIOMD0000000975.xml - no results generated
2025-11-20 13:19:13,473 - WARNING - Skipping BIOMD0000000976.xml - no results generated
2025-11-20 13:19:13,484 - WARNING - Skipping BIOMD0000000977.xml - no results generated
2025-11-20 13:19:13,489 - WARNING - Skipping BIOMD0000000978.xml - no results generated
2025-11-20 13:19:13,494 - WARNING - Skipping BIOMD0000000979.xml - no results generated
2025-11-20 13:19:13,499 - WARNING - Skipping BIOMD0000000980.xml - no results generated
2025-11-20 13:19:13,510 - WARNING - Skipping BIOMD0000000981.xml - no results generated
2025-11-20 13:19:13,515 - WARNING - Skipping BIOMD0000000982.xml - no results generated
2025-11-20 13:19:13,524 - WARNING - Skipping BIOMD0000000983.xml - no results generated
2025-11-20 13:19:13,529 - WARNING - Skipping BIOMD0000000984.xml - no results generated
2025-11-20 13:19:13,536 - WARNING - Skipping BIOMD0000000985.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000966.txt
LLM response:
Zn_2 (chemical): "zinc ion", "zinc(2+)", "Zn²⁺"
Py1 (unknown): "UNK"
Py (unknown): "UNK"
Reason: Zn_2 is likely a chemical entity because it is represented as "Zn^2" in the display names, which is a common notation for zinc ions. The model also describes the zinc homeostasis system, which further supports the classification of Zn_2 as a chemical entity. Py1 and Py are unknown because there is not enough information in the display names or the model to determine their entity types, and they do not match common names for genes, proteins, or chemicals in the context of the zinc homeostasis system.
Synonyms dict: {'Zn_2': ['zinc ion', 'zinc(2+)', 'Zn²⁺'], 'Py1': ['UNK'], 'Py': ['UNK']}
Evaluating 965/1075: BIOMD0000000967.xml
Evaluating 966/1075: BIOMD0000000968.xml
Evaluating 967/1075: BIOMD0000000969.xml
Evaluating 968/1075: BIOMD0000000970.xml
Evaluating 969/1075: BIOMD0000000971.xml
Evaluating 970/1075: BIOMD0000000972.xml
Evaluating 971/1075: BIOMD0000000973.xml
Evaluating 972/1075: BIOMD0000000974.xml
Evaluating 973/1075: BIOMD0000000975.xml
Evaluating 974/1075: BIOMD0000000976.xml
Evaluating 975/1075: BIOMD0000000977.xml
Evaluating 976/1075: BIOMD0000000978.xml
Evaluating 977/1075: BIOMD0000000979.xml
Evaluating 978/1075: BIOMD0000000980.xml
Evaluating 979/1075: BIOMD0000000981.xml
Evaluating 980/1075: BIOMD0000000982.xml
Evaluating 981/1075: BIOMD0000000983.xml
Evaluating 982/1075: BIOMD0000000984.xml
Evaluating 983/1075: BIOMD0000000985.xml
Evaluating 984/1075: BIOMD0000000986.xml

2025-11-20 13:19:16,495 - WARNING - Skipping BIOMD0000000987.xml - no results generated
2025-11-20 13:19:16,530 - WARNING - Skipping BIOMD0000000988.xml - no results generated
2025-11-20 13:19:16,566 - WARNING - Skipping BIOMD0000000989.xml - no results generated
2025-11-20 13:19:16,603 - WARNING - Skipping BIOMD0000000990.xml - no results generated
2025-11-20 13:19:16,612 - WARNING - Skipping BIOMD0000000991.xml - no results generated
2025-11-20 13:19:16,650 - WARNING - Skipping BIOMD0000000994.xml - no results generated
2025-11-20 13:19:16,686 - WARNING - Skipping BIOMD0000000995.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000000986.txt
LLM response:
Pyranine_single_compartment_model (chemical): "Pyranine", "8-Hydroxypyrene-1,3,6-trisulfonic acid", "HPTS"
Pyranine_three_compartment_model_compartment_1 (chemical): "Pyranine", "8-Hydroxypyrene-1,3,6-trisulfonic acid", "HPTS"
Pyranine_three_compartment_model_compartment_2 (chemical): "Pyranine", "8-Hydroxypyrene-1,3,6-trisulfonic acid", "HPTS"
Pyranine_three_compartment_model_compartment_3 (chemical): "Pyranine", "8-Hydroxypyrene-1,3,6-trisulfonic acid", "HPTS"
Reason: All species are likely to be the chemical "Pyranine" (also known as 8-Hydroxypyrene-1,3,6-trisulfonic acid or HPTS) because the model is studying fluid-phase endocytosis kinetics using a marker, and Pyranine is a fluorescent dye often used in biological studies, similar to the fluorescein-labelled dextran mentioned in the notes. The different compartment models likely refer to the same chemical in different cellular compartments.
Synonyms dict: {'Pyranine_single_compartment_model': ['Pyranine', '8-Hydroxypyrene-1,3,6-trisulfonic acid', 'HPTS'], 'Pyranine_three_compartment_model_compartment_1': ['Pyranine', '8-Hydroxypyrene-1,3,6-trisulfonic acid', 'HPTS'], 'Pyranine_three_compartment_model_compartment_2': ['Pyranine', '8-Hydroxypyrene-1,3,6-trisulfonic acid', 'HPTS'], 'Pyranine_three_compartment_model_compartment_3': ['Pyranine', '8-Hydroxypyrene-1,3,6-trisulfonic acid', 'HPTS']}
Evaluating 985/1075: BIOMD0000000987.xml
Evaluating 986/1075: BIOMD0000000988.xml
Evaluating 987/1075: BIOMD0000000989.xml
Evaluating 988/1075: BIOMD0000000990.xml
Evaluating 989/1075: BIOMD0000000991.xml
Evaluating 990/1075: BIOMD0000000994.xml
Evaluating 991/1075: BIOMD0000000995.xml
Evaluating 992/1075: BIOMD0000000996.xml

2025-11-20 13:19:16,718 - WARNING - Skipping BIOMD0000000996.xml - no results generated
2025-11-20 13:19:16,751 - WARNING - Skipping BIOMD0000000997.xml - no results generated
2025-11-20 13:19:16,783 - WARNING - Skipping BIOMD0000000998.xml - no results generated
2025-11-20 13:19:16,813 - WARNING - Skipping BIOMD0000000999.xml - no results generated
2025-11-20 13:19:16,844 - WARNING - Skipping BIOMD0000001000.xml - no results generated
2025-11-20 13:19:16,875 - WARNING - Skipping BIOMD0000001001.xml - no results generated
2025-11-20 13:19:16,905 - WARNING - Skipping BIOMD0000001002.xml - no results generated
2025-11-20 13:19:16,938 - WARNING - Skipping BIOMD0000001003.xml - no results generated
2025-11-20 13:19:16,947 - WARNING - Skipping BIOMD0000001004.xml - no results generated

Evaluating 993/1075: BIOMD0000000997.xml
Evaluating 994/1075: BIOMD0000000998.xml
Evaluating 995/1075: BIOMD0000000999.xml
Evaluating 996/1075: BIOMD0000001000.xml
Evaluating 997/1075: BIOMD0000001001.xml
Evaluating 998/1075: BIOMD0000001002.xml
Evaluating 999/1075: BIOMD0000001003.xml
Evaluating 1000/1075: BIOMD0000001004.xml
Evaluating 1001/1075: BIOMD0000001005.xml

2025-11-20 13:19:18,554 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:19:18,673 - WARNING - Skipping BIOMD0000001006.xml - no results generated
2025-11-20 13:19:18,680 - WARNING - Skipping BIOMD0000001007.xml - no results generated
2025-11-20 13:19:18,684 - WARNING - Skipping BIOMD0000001008.xml - no results generated
2025-11-20 13:19:18,692 - WARNING - Skipping BIOMD0000001009.xml - no results generated
2025-11-20 13:19:18,699 - WARNING - Skipping BIOMD0000001010.xml - no results generated
2025-11-20 13:19:18,705 - WARNING - Skipping BIOMD0000001011.xml - no results generated
2025-11-20 13:19:18,711 - WARNING - Skipping BIOMD0000001012.xml - no results generated
2025-11-20 13:19:18,716 - WARNING - Skipping BIOMD0000001013.xml - no results generated
2025-11-20 13:19:18,724 - WARNING - Skipping BIOMD0000001014.xml - no results generated
2025-11-20 13:19:18,732 - WARNING - Skipping BIOMD0000001015.xml - no results generated
2025-11-20 13:19:18,739 - WARNING - Skipping BIOMD0000001016.xml - no results generated
2025-11-20 13:19:18,749 - WARNING - Skipping BIOMD0000001017.xml - no results generated
2025-11-20 13:19:18,768 - WARNING - Skipping BIOMD0000001018.xml - no results generated
2025-11-20 13:19:18,773 - WARNING - Skipping BIOMD0000001019.xml - no results generated
2025-11-20 13:19:18,779 - WARNING - Skipping BIOMD0000001020.xml - no results generated
2025-11-20 13:19:18,787 - WARNING - Skipping BIOMD0000001021.xml - no results generated
2025-11-20 13:19:18,792 - WARNING - Skipping BIOMD0000001022.xml - no results generated
2025-11-20 13:19:18,798 - WARNING - Skipping BIOMD0000001023.xml - no results generated
2025-11-20 13:19:18,803 - WARNING - Skipping BIOMD0000001024.xml - no results generated
2025-11-20 13:19:18,808 - WARNING - Skipping BIOMD0000001025.xml - no results generated
2025-11-20 13:19:18,813 - WARNING - Skipping BIOMD0000001026.xml - no results generated
2025-11-20 13:19:18,837 - WARNING - Skipping BIOMD0000001027.xml - no results generated
2025-11-20 13:19:18,864 - WARNING - Skipping BIOMD0000001028.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001005.txt
LLM response:
ACTH (protein): "adrenocorticotropic hormone", "corticotropin", "ACTH hormone"
NAD (chemical): "nicotinamide adenine dinucleotide", "NAD+", "diphosphopyridine nucleotide"
NAM (chemical): "nicotinamide", "niacinamide", "vitamin B3"

Reason: ACTH is a protein as it is a hormone produced by the pituitary gland. NAD and NAM are chemicals as they are involved in metabolic reactions, with NAD being a coenzyme and NAM being a form of vitamin B3. The model context and display names support these annotations.
Synonyms dict: {'ACTH': ['adrenocorticotropic hormone', 'corticotropin', 'ACTH hormone'], 'NAD': ['nicotinamide adenine dinucleotide', 'NAD+', 'diphosphopyridine nucleotide'], 'NAM': ['nicotinamide', 'niacinamide', 'vitamin B3']}
Evaluating 1002/1075: BIOMD0000001006.xml
Evaluating 1003/1075: BIOMD0000001007.xml
Evaluating 1004/1075: BIOMD0000001008.xml
Evaluating 1005/1075: BIOMD0000001009.xml
Evaluating 1006/1075: BIOMD0000001010.xml
Evaluating 1007/1075: BIOMD0000001011.xml
Evaluating 1008/1075: BIOMD0000001012.xml
Evaluating 1009/1075: BIOMD0000001013.xml
Evaluating 1010/1075: BIOMD0000001014.xml
Evaluating 1011/1075: BIOMD0000001015.xml
Evaluating 1012/1075: BIOMD0000001016.xml
Evaluating 1013/1075: BIOMD0000001017.xml
Evaluating 1014/1075: BIOMD0000001018.xml
Evaluating 1015/1075: BIOMD0000001019.xml
Evaluating 1016/1075: BIOMD0000001020.xml
Evaluating 1017/1075: BIOMD0000001021.xml
Evaluating 1018/1075: BIOMD0000001022.xml
Evaluating 1019/1075: BIOMD0000001023.xml
Evaluating 1020/1075: BIOMD0000001024.xml
Evaluating 1021/1075: BIOMD0000001025.xml
Evaluating 1022/1075: BIOMD0000001026.xml
Evaluating 1023/1075: BIOMD0000001027.xml
Evaluating 1024/1075: BIOMD0000001028.xml

2025-11-20 13:19:18,891 - WARNING - Skipping BIOMD0000001029.xml - no results generated
2025-11-20 13:19:18,896 - WARNING - Skipping BIOMD0000001030.xml - no results generated
2025-11-20 13:19:18,901 - WARNING - Skipping BIOMD0000001031.xml - no results generated
2025-11-20 13:19:18,908 - WARNING - Skipping BIOMD0000001032.xml - no results generated
2025-11-20 13:19:18,919 - WARNING - Skipping BIOMD0000001033.xml - no results generated
2025-11-20 13:19:18,926 - WARNING - Skipping BIOMD0000001034.xml - no results generated
2025-11-20 13:19:18,932 - WARNING - Skipping BIOMD0000001035.xml - no results generated
2025-11-20 13:19:18,938 - WARNING - Skipping BIOMD0000001036.xml - no results generated
2025-11-20 13:19:18,941 - WARNING - Skipping BIOMD0000001037.xml - no results generated
2025-11-20 13:19:18,947 - WARNING - Skipping BIOMD0000001038.xml - no results generated
2025-11-20 13:19:18,971 - WARNING - Skipping BIOMD0000001039.xml - no results generated
2025-11-20 13:19:18,976 - WARNING - Skipping BIOMD0000001040.xml - no results generated
2025-11-20 13:19:18,981 - WARNING - Skipping BIOMD0000001041.xml - no results generated
2025-11-20 13:19:18,990 - WARNING - Skipping BIOMD0000001042.xml - no results generated
2025-11-20 13:19:18,996 - WARNING - Skipping BIOMD0000001043.xml - no results generated
2025-11-20 13:19:19,072 - WARNING - Skipping BIOMD0000001044.xml - no results generated
2025-11-20 13:19:19,076 - WARNING - Skipping BIOMD0000001045.xml - no results generated

Evaluating 1025/1075: BIOMD0000001029.xml
Evaluating 1026/1075: BIOMD0000001030.xml
Evaluating 1027/1075: BIOMD0000001031.xml
Evaluating 1028/1075: BIOMD0000001032.xml
Evaluating 1029/1075: BIOMD0000001033.xml
Evaluating 1030/1075: BIOMD0000001034.xml
Evaluating 1031/1075: BIOMD0000001035.xml
Evaluating 1032/1075: BIOMD0000001036.xml
Evaluating 1033/1075: BIOMD0000001037.xml
Evaluating 1034/1075: BIOMD0000001038.xml
Evaluating 1035/1075: BIOMD0000001039.xml
Evaluating 1036/1075: BIOMD0000001040.xml
Evaluating 1037/1075: BIOMD0000001041.xml
Evaluating 1038/1075: BIOMD0000001042.xml
Evaluating 1039/1075: BIOMD0000001043.xml
Evaluating 1040/1075: BIOMD0000001044.xml
Evaluating 1041/1075: BIOMD0000001045.xml
Evaluating 1042/1075: BIOMD0000001046.xml

2025-11-20 13:21:48,571 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:21:48,714 - WARNING - Skipping BIOMD0000001047.xml - no results generated
2025-11-20 13:21:48,721 - WARNING - Skipping BIOMD0000001048.xml - no results generated
2025-11-20 13:21:48,731 - WARNING - Skipping BIOMD0000001052.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001046.txt
LLM response:
M_trans_delta_2_enoyl_C54_acyl_ACP (chemical): "trans-delta-2-enoyl-C54-acyl-ACP", "trans-2-enoyl-C54-acyl-ACP", "C54-enoyl-ACP"
M_C54_acyl_ACP (chemical): "C54-acyl-ACP", "acyl-ACP C54", "C54-acyl carrier protein"
M_beta_keto_C56_acyl_ACP (chemical): "beta-keto-C56-acyl-ACP", "3-keto-C56-acyl-ACP", "C56-beta-ketoacyl-ACP"
M_D_3_hydroxy_C56_acyl_ACP (chemical): "D-3-hydroxy-C56-acyl-ACP", "3-hydroxy-C56-acyl-ACP", "C56-3-hydroxyacyl-ACP"
M_trans_delta_2_enoyl_C56_acyl_ACP (chemical): "trans-delta-2-enoyl-C56-acyl-ACP", "trans-2-enoyl-C56-acyl-ACP", "C56-enoyl-ACP"
M_C56_acyl_ACP (chemical): "C56-acyl-ACP", "acyl-ACP C56", "C56-acyl carrier protein"
M_beta_keto_C58_acyl_ACP (chemical): "beta-keto-C58-acyl-ACP", "3-keto-C58-acyl-ACP", "C58-beta-ketoacyl-ACP"
M_D_3_hydroxy_C58_acyl_ACP (chemical): "D-3-hydroxy-C58-acyl-ACP", "3-hydroxy-C58-acyl-ACP", "C58-3-hydroxyacyl-ACP"
M_trans_delta_2_enoyl_C58_acyl_ACP (chemical): "trans-delta-2-enoyl-C58-acyl-ACP", "trans-2-enoyl-C58-acyl-ACP", "C58-enoyl-ACP"
M_C58_acyl_ACP (chemical): "C58-acyl-ACP", "acyl-ACP C58", "C58-acyl carrier protein"
M_cis_delta_2_19_31_enoyl_C52_acyl_ACP (chemical): "cis-delta-2-19,31-enoyl-C52-acyl-ACP", "cis-2-enoyl-C52-acyl-ACP", "C52-enoyl-ACP"
M_cis_delta_2_19_37_enoyl_C54_acyl_ACP (chemical): "cis-delta-2-19,37-enoyl-C54-acyl-ACP", "cis-2-enoyl-C54-acyl-ACP", "C54-enoyl-ACP"
M_cis_delta_2_19_37_enoyl_C58_acyl_ACP (chemical): "cis-delta-2-19,37-enoyl-C58-acyl-ACP", "cis-2-enoyl-C58-acyl-ACP", "C58-enoyl-ACP"
M_S_adenosyl_L_methionine (chemical): "S-adenosyl-L-methionine", "SAM", "AdoMet"
M_cis_delta_1_31_enoyl_19_cp_C53_acyl_ACP (chemical): "cis-delta-1-31-enoyl-19-cp-C53-acyl-ACP", "cis-1-enoyl-C53-acyl-ACP", "C53-enoyl-ACP"
M_S_adenosyl_L_homocysteine (chemical): "S-adenosyl-L-homocysteine", "SAH", "AdoHcy"
M_19_31_cp_C54_acyl_ACP (chemical): "19,31-cp-C54-acyl-ACP", "C54-acyl-ACP cp", "C54-acyl carrier protein cp"
M_19_31_cp_C54_acyl_ACP_AMP (chemical): "19,31-cp-C54-acyl-ACP-AMP", "C54-acyl-ACP-AMP cp", "C54-acyl carrier protein-AMP cp"
M_cis_delta_37_methyl_hydroxy_C55_acyl_ACP (chemical): "cis-delta-37-methyl-hydroxy-C55-acyl-ACP", "cis-37-methyl-hydroxy-C55-acyl-ACP", "C55-methyl-hydroxyacyl-ACP"
M_cis_delta_37_methyl_hydroxymethyl_C56_acyl_ACP (chemical): "cis-delta-37-methyl-hydroxymethyl-C56-acyl-ACP", "cis-37-methyl-hydroxymethyl-C56-acyl-ACP", "C56-methyl-hydroxymethylacyl-ACP"
M_cis_methoxy_C57_meroacyl_cp_ACP (chemical): "cis-methoxy-C57-meroacyl-cp-ACP", "cis-methoxy-C57-meroacyl-ACP", "C57-methoxy-meroacyl-ACP"
M_cis_methoxy_C57_meroacyl_cp_ACP_AMP (chemical): "cis-methoxy-C57-meroacyl-cp-ACP-AMP", "cis-methoxy-C57-meroacyl-ACP-AMP", "C57-methoxy-meroacyl-ACP-AMP"
M_cis_methoxy_mycolate (chemical): "cis-methoxy-mycolate", "methoxy-mycolic acid", "cis-mycolic acid"
M_delta_2_cis_19_trans_37_enoyl_methyl_C55_acyl_ACP (chemical): "delta-2-cis-19,trans-37-enoyl-methyl-C55-acyl-ACP", "enoyl-methyl-C55-acyl-ACP", "C55-enoyl-methyl-ACP"
M_trans_delta_37_methyl_hydroxy_C56_acyl_ACP (chemical): "trans-delta-37-methyl-hydroxy-C56-acyl-ACP", "trans-37-methyl-hydroxy-C56-acyl-ACP", "C56-methyl-hydroxyacyl-ACP"
M_trans_delta_3_methyl_hydroxymethyl_C57_acyl_ACP (chemical): "trans-delta-37-methyl-hydroxymethyl-C57-acyl-ACP", "trans-37-methyl-hydroxymethyl-C57-acyl-ACP", "C57-methyl-hydroxymethylacyl-ACP"
M_trans_methoxy_C58_meroacyl_cp_ACP (chemical): "trans-methoxy-C58-meroacyl-cp-ACP", "trans-methoxy-C58-meroacyl-ACP", "C58-methoxy-meroacyl-ACP"
M_trans_methoxy_C58_meroacyl_cp_ACP_AMP (chemical): "trans-methoxy-C58-meroacyl-cp-ACP-AMP", "trans-methoxy-C58-meroacyl-ACP-AMP", "C58-methoxy-meroacyl-ACP-AMP"
M_trans_methoxy_mycolate (chemical): "trans-methoxy-mycolate", "methoxy-mycolic acid", "trans-mycolic acid"
M_cis_delta_37_methyl_hydroxy_C59_acyl_ACP (chemical): "cis-delta-37-methyl-hydroxy-C59-acyl-ACP", "cis-37-methyl-hydroxy-C59-acyl-ACP", "C59-methyl-hydroxyacyl-ACP"
M_cis_delta_37_methyl_keto_C59_acyl_ACP (chemical): "cis-delta-37-methyl-keto-C59-acyl-ACP", "cis-37-methyl-keto-C59-acyl-ACP", "C59-methyl-ketoacyl-ACP"
M_cis_keto_C60_meroacyl_ACP (chemical): "cis-keto-C60-meroacyl-ACP", "cis-keto-C60-acyl-ACP", "C60-ketoacyl-ACP"
M_cis_keto_C60_meroacyl_ACP_AMP (chemical): "cis-keto-C60-meroacyl-ACP-AMP", "cis-keto-C60-acyl-ACP-AMP", "C60-ketoacyl-ACP-AMP"
M_cis_keto_mycolate (chemical): "cis-keto-mycolate", "keto-mycolic acid", "cis-mycolic acid"
M_trans_delta_37_methyl_hydroxy_C60_acyl_ACP (chemical): "trans-delta-37-methyl-hydroxy-C60-acyl-ACP", "trans-37-methyl-hydroxy-C60-acyl-ACP", "C60-methyl-hydroxyacyl-ACP"
M_trans_delta_37_methyl_keto_C60_acyl_ACP (chemical): "trans-delta-37-methyl-keto-C60-acyl-ACP", "trans-37-methyl-keto-C60-acyl-ACP", "C60-methyl-ketoacyl-ACP"
M_trans_keto_C61_meroacyl_ACP (chemical): "trans-keto-C61-meroacyl-ACP", "trans-keto-C61-acyl-ACP", "C61-ketoacyl-ACP"
M_trans_keto_C61_meroacyl_ACP_AMP (chemical): "trans-keto-C61-meroacyl-ACP-AMP", "trans-keto-C61-acyl-ACP-AMP", "C61-ketoacyl-ACP-AMP"
M_trans_keto_mycolate (chemical): "trans-keto-mycolate", "keto-mycolic acid", "trans-mycolic acid"
M_S_adenosyl_L_methionine (chemical): "S-adenosyl-L-methionine", "SAM", "AdoMet"
M_S_adenosyl_L_homocysteine (chemical): "S-adenosyl-L-homocysteine", "SAH", "AdoHcy"
M_cis_methoxy_mycolate (chemical): "cis-methoxy-mycolate", "methoxy-mycolic acid", "cis-mycolic acid"
M_trans_methoxy_mycolate (chemical): "trans-methoxy-mycolate", "methoxy-mycolic acid", "trans-mycolic acid"
M_cis_keto_mycolate (chemical): "cis-keto-mycolate", "keto-mycolic acid", "cis-mycolic acid"
M_trans_keto_mycolate (chemical): "trans-keto-mycolate", "keto-mycolic acid", "trans-mycolic acid"
M_alpha_mycolate (chemical): "alpha-mycolate", "mycolic acid", "alpha-mycolic acid"
M_biomass (complex): "biomass", "cellular biomass", "mycobacterial biomass"
M_acyl_carrier_protein (protein): "acyl carrier protein", "ACP", "acyl-CP"
M_coenzyme_A (chemical): "coenzyme A", "CoA", "CoASH"
M_NAD (chemical): "NAD", "nicotinamide adenine dinucleotide", "NAD+"
M_2_carboxyl_C24_acyl_CoA (chemical): "2-carboxyl-C24-acyl-CoA", "2-carboxyl-acyl-CoA C24", "C24-2-carboxyl-acyl-CoA"
M_AMP (chemical): "AMP", "adenosine monophosphate", "AMP nucleotide"
M_NADH (chemical): "NADH", "nicotinamide adenine dinucleotide reduced", "NADH+"
M_NADP (chemical): "NADP", "nicotinamide adenine dinucleotide phosphate", "NADP+"
M_NADPH (chemical): "NADPH", "nicotinamide adenine dinucleotide phosphate reduced", "NADPH+"
M_CO2 (chemical): "CO2", "carbon dioxide", "carbonic acid"
M_pyrophosphate (chemical): "pyrophosphate", "diphosphate", "PPi"
M_ATP (chemical): "ATP", "adenosine triphosphate", "ATP nucleotide"
M_H2O (chemical): "H2O", "water", "dihydrogen monoxide"
M_malonyl_ACP (chemical): "malonyl-ACP", "malonyl acyl carrier protein", "malonyl-CoA"

Reason: The model provided is a biochemical model of the mycolic acid pathway in M. tuberculosis. The species in the model are primarily biochemical compounds, including fatty acids, acyl carrier proteins, and nucleotides. Based on the names and the context of the model, the entity types of the species can be determined. The majority of the species are chemicals, including the mycolic acids, acyl-ACPs, and other fatty acid intermediates. The acyl carrier protein (ACP) is a protein, and the biomass is a complex entity representing the cellular biomass of M. tuberculosis. The other species, including NAD, NADH, NADP, NADPH, ATP, AMP, and coenzyme A, are all chemicals that play important roles in the biochemical reactions of the mycolic acid pathway.

2025-11-20 13:21:50,229 - WARNING - Skipping BIOMD0000001053.xml - no results generated

Evaluating 1047/1075: BIOMD0000001054.xml

2025-11-20 13:21:52,201 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:21:52,202 - WARNING - Skipping BIOMD0000001054.xml - no results generated

Evaluating 1048/1075: BIOMD0000001055.xml

2025-11-20 13:21:54,666 - WARNING - Skipping BIOMD0000001056.xml - no results generated
2025-11-20 13:21:54,671 - WARNING - Skipping BIOMD0000001057.xml - no results generated
2025-11-20 13:21:54,688 - WARNING - Skipping BIOMD0000001058.xml - no results generated
2025-11-20 13:21:54,700 - WARNING - Skipping BIOMD0000001059.xml - no results generated
2025-11-20 13:21:54,707 - WARNING - Skipping BIOMD0000001060.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001055.txt
LLM response:
Glucose (chemical): "glucose", "d-glucose", "blood sugar"
Phosphoenolpyruvate (chemical): "phosphoenolpyruvate", "pep", "2-phosphoenolpyruvate"
Pyruvate (chemical): "pyruvate", "pyruvic acid", "2-oxopropanoic acid"
Oxaloacetate (chemical): "oxaloacetate", "oxaloacetic acid", "2-oxosuccinic acid"
Reason: All species are identified as chemicals because they are intermediates in glucose metabolism, specifically in glycolysis and related pathways, and have display names that match common biochemical names. The reactions also indicate conversions between these species, consistent with known biochemical pathways.
Synonyms dict: {'Glucose': ['glucose', 'd-glucose', 'blood sugar'], 'Phosphoenolpyruvate': ['phosphoenolpyruvate', 'pep', '2-phosphoenolpyruvate'], 'Pyruvate': ['pyruvate', 'pyruvic acid', '2-oxopropanoic acid'], 'Oxaloacetate': ['oxaloacetate', 'oxaloacetic acid', '2-oxosuccinic acid']}
Evaluating 1049/1075: BIOMD0000001056.xml
Evaluating 1050/1075: BIOMD0000001057.xml
Evaluating 1051/1075: BIOMD0000001058.xml
Evaluating 1052/1075: BIOMD0000001059.xml
Evaluating 1053/1075: BIOMD0000001060.xml
Evaluating 1054/1075: BIOMD0000001061.xml

2025-11-20 13:32:06,976 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:32:06,977 - WARNING - Unknown entity type: rna

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001061.txt
LLM response:
M_cl_p (chemical): "Chloride", "Cl-", "Chloride ion"
M_cu_e (chemical): "Copper(I) ion", "Cu+", "Cuprous ion"
M_ca2_p (chemical): "Calcium", "Ca2+", "Calcium ion"
M_orot_p (chemical): "Orotate", "Uracil-6-carboxylate", "6-Uracilcarboxylic acid"
M_fe3_c (chemical): "Iron(III) ion", "Fe3+", "Ferric ion"
M_mththf_p (chemical): "(2R,4S)-2-methyl-2,3,3,4-tetrahydroxytetrahydrofuran", "MTHF", "5,10-Methylenetetrahydrofolate"
M_hco3_p (chemical): "Bicarbonate", "HCO3-", "Hydrogen carbonate"
M_uaagmda_p (complex): "Undecaprenyl-diphospho-N-acetylmuramoyl-(N-acetylglucosamine)-L-ala-D-glu-meso-2,6-diaminopimeloyl-D-ala-D-ala", "UDP-N-acetylmuramoyl-pentapeptide", "Lipid II"
M_ch4_e (chemical): "Methane", "CH4", "Natural gas"
M_ch4_p (chemical): "Methane", "CH4", "Natural gas"
M_phenol_p (chemical): "Phenol", "C6H5OH", "Hydroxybenzene"
M_phenol_e (chemical): "Phenol", "C6H5OH", "Hydroxybenzene"
M_hqn_p (chemical): "Hydroquinone", "C6H4(OH)2", "1,4-Dihydroxybenzene"
M_hqn_e (chemical): "Hydroquinone", "C6H4(OH)2", "1,4-Dihydroxybenzene"
M_tol_e (chemical): "Toluene", "C6H5CH3", "Methylbenzene"
M_tol_p (chemical): "Toluene", "C6H5CH3", "Methylbenzene"
M_bzalc_p (chemical): "Benzyl alcohol", "C6H5CH2OH", "Phenylmethanol"
M_bzal_p (chemical): "Benzaldehyde", "C6H5CHO", "Benzenecarbaldehyde"
M_bzal_e (chemical): "Benzaldehyde", "C6H5CHO", "Benzenecarbaldehyde"
M_rb15bp_c (chemical): "D-Ribulose 1,5-bisphosphate", "RuBP", "Ribulose-1,5-bisphosphate"
M_2pglyc_c (chemical): "2-Phosphoglycolate", "2-PGA", "2-Phosphoglycolic acid"
M_r1p_c (chemical): "Alpha-D-Ribose 1-phosphate", "R1P", "Ribose-1-phosphate"

Reason: Most species have been identified based on their display names, which provide a clear indication of their chemical structure or function. For example, M_cl_p is identified as "Chloride" due to its display name, and M_orot_p is identified as "Orotate" based on its display name and chemical structure. Some species, such as M_uaagmda_p, have been identified as complexes due to their complex chemical structure and function. In cases where the display name is not sufficient, the species has been identified based on its participation in reactions and its likely role in the metabolic pathway. For example, M_ch4_e and M_ch4_p are both identified as "Methane" due to their participation in reactions involving methane oxidation.

2025-11-20 13:54:55,931 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 13:54:56,475 - WARNING - Unknown entity type: rna

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001062.txt
LLM response:
M_xylt_e (chemical): "Xylitol", "Xylite", "C5H12O5"
M_oxa_e (chemical): "Oxalate", "Oxalic acid", "C2H2O4"
M_gly_asp__L_e (chemical): "Glycine-aspartate", "Gly-Asp", "C6H9N2O5"
M_glx_e (chemical): "Glyoxylate", "Glyoxylic acid", "C2H2O3"
M_srb__L_e (chemical): "L-Sorbose", "Sorbose", "C6H12O6"
M_abt__L_e (chemical): "L-Arabinitol", "Arabinitol", "C5H12O5"
M_madg_e (chemical): "Alpha-Methyl-D-glucoside", "Methyl glucoside", "C7H14O6"
M_pala_e (chemical): "Palatinose", "Isomaltulose", "C12H22O11"
M_2obut_e (chemical): "2-Oxobutanoate", "Alpha-ketobutyrate", "C4H6O3"
M_gly_asp__L_c (chemical): "Glycine-aspartate", "Gly-Asp", "C6H9N2O5"
M_lys__D_e (chemical): "D-Lysine", "Lysine", "C6H14N2O2"
M_5aptn_e (chemical): "5-Aminopentanoate", "5-Aminovalerate", "C5H11NO2"
M_asp__D_e (chemical): "D-Aspartate", "Aspartate", "C4H7NO4"
M_hista_e (chemical): "Histamine", "Histamine extracellular", "C5H9N3"
M_CE0074_e (chemical): "Alloxan", "5,5'-Diethylbarbituric acid", "C4H2N2O4"
M_glu__D_e (chemical): "D-Glutamate", "Glutamate", "C5H9NO4"
M_citr__L_e (chemical): "L-Citrulline", "Citrulline", "C6H13N3O3"
M_ala_L_asp__L_e (chemical): "Alanyl-aspartate", "Ala-Asp", "C7H11N2O5"
M_ala_L_gln__L_e (chemical): "Alanyl-glutamine", "Ala-Gln", "C8H15N3O4"
M_L_alagly_e (chemical): "L-Alanylglycine", "Ala-Gly", "C5H10N2O3"
M_ala_L_leu__L_e (chemical): "Alanyl-leucine", "Ala-Leu", "C9H18N2O3"
M_gly_gln__L_e (chemical): "Glycyl-glutamine", "Gly-Gln", "C7H13N3O4"
M_gly_met__L_e (chemical): "Glycyl-methionine", "Gly-Met", "C7H14N2O3S"
M_acglu_e (chemical): "N-Acetyl-L-glutamate", "Acetylglutamate", "C7H13NO5"
M_ad_e (chemical): "Acetamide", "Acetic amide", "C2H5NO"
M_ham_e (chemical): "Hydroxylamine", "NH2OH", "H3NO"
M_mma_e (chemical): "Methylamine", "Aminomethane", "CH5N"
M_C02356_e (chemical): "(S)-2-Aminobutanoate", "2-Aminobutyrate", "C4H9NO2"
M_ala_L_asp__L_c (chemical): "Alanyl-aspartate", "Ala-Asp", "C7H11N2O5"
M_dkmpp_c (chemical): "2,3-Diketo-5-methylthio-1-phosphopentane", "DKMPP", "C6H11O5PS"
M_gly_asp__L_p (chemical): "Glycine-aspartate", "Gly-Asp", "C6H9N2O5"
M_gly_asp__L_c (chemical): "Glycine-aspartate", "Gly-Asp", "C6H9N2O5"
M_gly_met__L_p (chemical): "Glycyl-methionine", "Gly-Met", "C7H14N2O3S"
M_gly_gln__L_p (chemical): "Glycyl-glutamine", "Gly-Gln", "C7H13N3O4"
M_ala_L_gln__L_p (chemical): "Alanyl-glutamine", "Ala-Gln", "C8H15N3O4"
M_L_alagly_p (chemical): "L-Alanylglycine", "Ala-Gly", "C5H10N2O3"
M_ala_L_leu__L_p (chemical): "Alanyl-leucine", "Ala-Leu", "C9H18N2O3"
M_gly_met__L_p (chemical): "Glycyl-methionine", "Gly-Met", "C7H14N2O3S"
M_5mdru1p_c (chemical): "5-Methylthio-5-deoxy-D-ribulose 1-phosphate", "5-MDRU1P", "C6H13O8PS"
M_atp_c (chemical): "ATP", "Adenosine triphosphate", "C10H12N5O13P3"
M_adp_c (chemical): "ADP", "Adenosine diphosphate", "C10H12N5O10P2"
M_pi_c (chemical): "Phosphate", "Inorganic phosphate", "PO4"
M_h2o_c (chemical): "Water", "H2O", "H2O"
M_h_c (chemical): "Hydrogen ion", "H+", "H+"
M_h_p (chemical): "Hydrogen ion", "H+", "H+"
M_ala__L_c (chemical): "L-Alanine", "Alanine", "C3H7NO2"
M_asp__L_c (chemical): "L-Aspartate", "Aspartate", "C4H7NO4"
M_gly_c (chemical): "Glycine", "Gly", "C2H5NO2"

Reason: The species are annotated based on their display names and the reactions they participate in. Most species are annotated as chemicals, as they are metabolites or compounds involved in the metabolic reactions. The annotations are based on the display names and the chemical formulas provided. The reactions also provide clues about the species, such as the involvement of ATP, ADP, and phosphate in energy transfer reactions, and the presence of hydrogen ions in acid-base reactions. The species without display names or reactions are annotated as unknown, but based on their IDs, they can be inferred to be chemicals.

2025-11-20 14:32:43,523 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 14:32:43,611 - WARNING - Unknown entity type: rna
2025-11-20 14:32:45,989 - WARNING - Skipping BIOMD0000001064.xml - no results generated

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001063.txt
LLM response:
s_4252__91__p__93__ (chemical): "propionyl-CoA", "propanoyl-CoA", "propionyl coenzyme A"
s_4253__91__m__93__ (chemical): "ethyl propionate", "propionate ethyl ester", "ethyl propanoate"
s_4258__91__c__93__ (chemical): "propyl acetate", "acetic acid propyl ester", "propyl ethanoate"
s_4259__91__e__93__ (chemical): "propyl acetate", "acetic acid propyl ester", "propyl ethanoate"
s_4261__91__c__93__ (chemical): "ethyl propionate", "propionate ethyl ester", "ethyl propanoate"
s_4262__91__e__93__ (chemical): "ethyl propionate", "propionate ethyl ester", "ethyl propanoate"
Reason: All species have display names that correspond to known chemical compounds, and their involvement in metabolic reactions further supports their classification as chemicals. The display names and reaction contexts provide sufficient information to determine their standardized names and synonyms.

2025-11-20 14:32:46,080 - WARNING - Skipping BIOMD0000001065.xml - no results generated
2025-11-20 14:32:46,091 - WARNING - Skipping BIOMD0000001072.xml - no results generated
2025-11-20 14:32:46,107 - WARNING - Skipping BIOMD0000001077.xml - no results generated
2025-11-20 14:32:46,113 - WARNING - Skipping BIOMD0000001078.xml - no results generated
2025-11-20 14:32:46,118 - WARNING - Skipping BIOMD0000001079.xml - no results generated
2025-11-20 14:32:46,124 - WARNING - Skipping BIOMD0000001080.xml - no results generated
2025-11-20 14:32:46,422 - WARNING - Skipping BIOMD0000001090.xml - no results generated

Evaluating 1059/1075: BIOMD0000001072.xml
Evaluating 1060/1075: BIOMD0000001077.xml
Evaluating 1061/1075: BIOMD0000001078.xml
Evaluating 1062/1075: BIOMD0000001079.xml
Evaluating 1063/1075: BIOMD0000001080.xml
Evaluating 1064/1075: BIOMD0000001090.xml
Evaluating 1065/1075: BIOMD0000001091.xml

2025-11-20 14:32:47,738 - WARNING - Skipping BIOMD0000001091.xml - no results generated

Evaluating 1066/1075: BIOMD0000001092.xml
LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001092.txt
LLM response:
M_xylb_c (chemical): "Xylobiose", "4-O-β-D-xylopyranosyl-D-xylose", "Xylo-biose"
M_xylb_e (chemical): "Xylobiose", "4-O-β-D-xylopyranosyl-D-xylose", "Xylo-biose"
M_rbl__L_c (chemical): "L-Ribulose", "L-erythro-2,3-dihydroxy-4-oxopentose", "Ribulose"
M_gal1p_c (chemical): "Alpha-D-Galactose 1-phosphate", "Galactose-1-phosphate", "D-Galactose 1-phosphate"
M_udpgal_c (chemical): "UDPgalactose", "Uridine diphosphate galactose", "UDP-D-galactose"
M_xyl4_c (chemical): "Xylotetraose", "Xylo-tetraose", "4-α-D-xylopyranosyl-D-xylopyranosyl-D-xylopyranosyl-D-xylopyranose"
M_hco3_e (chemical): "Bicarbonate", "Hydrogen carbonate", "HCO3-"
M_man6p_c (chemical): "D-Mannose 6-phosphate", "Mannose-6-phosphate", "D-Mannose-6-phosphate"
M_lald__L_c (chemical): "L-Lactaldehyde", "L-2-hydroxypropanal", "L-1,2-dihydroxypropane"
M_mnl_c (chemical): "D-Mannitol", "Mannitol", "D-Mannite"
M_ru5p__L_c (chemical): "L-Ribulose 5-phosphate", "L-Ribulose-5-phosphate", "5-O-phosphono-L-ribulose"
M_rml_c (chemical): "L-Rhamnulose", "L-Rhamnulo-1,4-lactone", "L-Rhamnulose-1,4-lactone"
M_rml1p_c (chemical): "L-Rhamnulose 1-phosphate", "L-Rhamnulose-1-phosphate", "1-O-phosphono-L-rhamnulose"
M_xylu__D_c (chemical): "D-Xylulose", "D-xylo-2-pentulose", "D-Xylulose-5-phosphate"
M_s_c (chemical): "Elemental sulfur", "Sulfur", "S0"
M_s_e (chemical): "Elemental sulfur", "Sulfur", "S0"
M_tsul_c (chemical): "Thiosulfate", "Sodium thiosulfate", "S2O3-"
M_tsul_e (chemical): "Thiosulfate", "Sodium thiosulfate", "S2O3-"
M_rib__D_c (chemical): "D-Ribose", "D-ribo-pentose", "D-Ribose-5-phosphate"
M_rib__D_e (chemical): "D-Ribose", "D-ribo-pentose", "D-Ribose-5-phosphate"
M_malt_c (chemical): "Maltose", "Malt sugar", "α-D-Glucopyranosyl-(1→4)-D-glucose"
M_malt_e (chemical): "Maltose", "Malt sugar", "α-D-Glucopyranosyl-(1→4)-D-glucose"
M_ppap_c (chemical): "Propanoyl phosphate", "Propionyl phosphate", "Propanoylphosphate"
M_etoh_c (chemical): "Ethanol", "Ethyl alcohol", "C2H5OH"
M_etoh_e (chemical): "Ethanol", "Ethyl alcohol", "C2H5OH"
M_meoh_c (chemical): "Methanol", "Methyl alcohol", "CH3OH"
M_meoh_e (chemical): "Methanol", "Methyl alcohol", "CH3OH"
M_8aonn_c (chemical): "8-Amino-7-oxononanoate", "8-Amino-7-ketononanoate", "7-Oxo-8-aminononanoate"
M_amob_c (chemical): "S-Adenosyl-4-methylthio-2-oxobutanoate", "S-Adenosyl-4-methylthio-2-oxobutyrate", "4-Methylthio-2-oxobutanoate"
M_dann_c (chemical): "7,8-Diaminononanoate", "7,8-Diaminononanoic acid", "7,8-Diaminononanoate"
M_dtbt_c (chemical): "Dethiobiotin", "7,8-Diaminopelargonic acid", "Dethiobiotin"
M_btn_c (chemical): "Biotin", "Vitamin B7", "Vitamin H"
M_15dap_c (chemical): "1,5-Diaminopentane", "1,5-Pentanediamine", "Cadaverine"
M_sprm_c (chemical): "Spermine", "N,N'-Bis(3-aminopropyl)tetramethylenediamine", "Spermine"
M_24dab_c (chemical): "L-2,4-Diaminobutanoate", "L-2,4-Diaminobutyrate", "2,4-Diaminobutanoic acid"
M_ahcys_c (chemical): "S-Adenosyl-L-homocysteine", "SAH", "S-Adenosylhomocysteine"
M_rhcys_c (chemical): "S-Ribosyl-L-homocysteine", "SRH", "S-Ribosylhomocysteine"
M_malcoame_c (chemical): "Malonyl-CoA methyl ester", "Malonyl-CoA", "Malonyl-coenzyme A methyl ester"

Reason: Most species are identified as chemicals based on their names and roles in the metabolic network. The model includes various biochemical reactions involving these chemicals, such as glycolysis, pentose phosphate pathway, and amino acid metabolism. The species are matched to their corresponding chemical names and synonyms based on their display names and roles in the reactions. Some species, like M_xylb_c and M_xylb_e, have the same chemical name but differ in their compartment (cytosol or extracellular), and are therefore considered the same chemical entity.

2025-11-20 14:54:23,059 - WARNING - No valid database found for entity type 'protein' in allowed databases: ['chebi']
2025-11-20 14:54:23,060 - WARNING - Unknown entity type: rna
2025-11-20 14:54:23,060 - WARNING - Unknown entity type: lipid

LLM results saved to: autoType/Llama-3.3-70B-instruct-Meta/auto/20251120_1219/BIOMD0000001093.txt
LLM response:
M_13ppd_c (chemical): "1,3-Propanediol", "Propane-1,3-diol", "Trimethylene glycol"
M_cholp_c (chemical): "Choline phosphate", "Phosphocholine", "Choline phosphoric acid"
M_ethamp_c (chemical): "Ethanolamine phosphate", "Phosphoethanolamine", "Ethanolamine phosphoric acid"
M_val__L_c (chemical): "L-Valine", "Valine", "2-Amino-3-methylbutanoic acid"
M_val__L_e (chemical): "L-Valine", "Valine", "2-Amino-3-methylbutanoic acid"
M_val__L_p (chemical): "L-Valine", "Valine", "2-Amino-3-methylbutanoic acid"
M_valtrna_c (chemical): "L-Valyl-tRNA", "Valyl transfer RNA", "tRNA-Val"
M_vanln_c (chemical): "Vanillin", "4-Hydroxy-3-methoxybenzaldehyde", "Vanillic aldehyde"
M_vanln_e (chemical): "Vanillin", "4-Hydroxy-3-methoxybenzaldehyde", "Vanillic aldehyde"
M_vanln_p (chemical): "Vanillin", "4-Hydroxy-3-methoxybenzaldehyde", "Vanillic aldehyde"
M_vanlt_c (chemical): "Vanillate", "4-Hydroxy-3-methoxybenzoate", "Vanillic acid"
M_vanlt_e (chemical): "Vanillate", "4-Hydroxy-3-methoxybenzoate", "Vanillic acid"
M_vanlt_p (chemical): "Vanillate", "4-Hydroxy-3-methoxybenzoate", "Vanillic acid"
M_xan_c (chemical): "Xanthine", "3,7-Dihydropurine-2,6-dione", "1H-Purine-2,6-dione"
M_xan_e (chemical): "Xanthine", "3,7-Dihydropurine-2,6-dione", "1H-Purine-2,6-dione"
M_xan_p (chemical): "Xanthine", "3,7-Dihydropurine-2,6-dione", "1H-Purine-2,6-dione"
M_xmp_c (chemical): "Xanthosine 5'-monophosphate", "Xanthosine monophosphate", "5'-Xanthosine monophosphate"
M_xmp_p (chemical): "Xanthosine 5'-monophosphate", "Xanthosine monophosphate", "5'-Xanthosine monophosphate"
M_xtp_c (chemical): "Xanthosine 5'-triphosphate", "Xanthosine triphosphate", "5'-Xanthosine triphosphate"
M_xtsn_c (chemical): "Xanthosine", "9-β-D-Ribofuranosylxanthine", "Xanthine riboside"
M_xtsn_p (chemical): "Xanthosine", "9-β-D-Ribofuranosylxanthine", "Xanthine riboside"
M_xu5p__D_c (chemical): "D-Xylulose 5-phosphate", "Xylulose-5-phosphate", "D-Xylulose-5-P"
M_zn2_c (chemical): "Zinc", "Zinc ion", "Zn2+"
M_zn2_e (chemical): "Zinc", "Zinc ion", "Zn2+"
M_zn2_p (chemical): "Zinc", "Zinc ion", "Zn2+"
M_S2hglut_c (chemical): "(S)-2-Hydroxyglutarate", "(S)-2-Hydroxyglutaric acid", "L-2-Hydroxyglutarate"
M_malttr_c (chemical): "Maltotriose", "Maltotriose sugar", "3-α-D-Glucosylmaltose"
Reason: The species were identified as chemicals based on their names and the context of the metabolic network model. The names of the species are consistent with known chemical compounds, and the reactions they participate in are typical of biochemical reactions. The entity types were determined based on the suffixes and prefixes of the species names, which are commonly used in biochemical nomenclature. For example, species with the suffix "_c" are likely to be chemicals, while those with the suffix "_p" are likely to be phosphates or other derivatives. The synonyms provided are based on common names and alternative names for the chemical compounds.

2025-11-20 14:54:25,699 - WARNING - Skipping BIOMD0000001094.xml - no results generated
2025-11-20 14:54:25,963 - WARNING - Skipping BIOMD0000001095.xml - no results generated

Evaluating 1069/1075: BIOMD0000001095.xml
Evaluating 1070/1075: BIOMD0000001096.xml

2025-11-20 14:54:26,351 - WARNING - Skipping BIOMD0000001096.xml - no results generated
2025-11-20 14:54:26,603 - WARNING - Skipping BIOMD0000001097.xml - no results generated
2025-11-20 14:54:26,778 - WARNING - Skipping BIOMD0000001098.xml - no results generated

Evaluating 1071/1075: BIOMD0000001097.xml
Evaluating 1072/1075: BIOMD0000001098.xml
Evaluating 1073/1075: BIOMD0000001099.xml

2025-11-20 14:54:26,966 - WARNING - Skipping BIOMD0000001099.xml - no results generated
2025-11-20 14:54:26,975 - WARNING - Skipping BIOMD0000001102.xml - no results generated
2025-11-20 14:54:26,988 - WARNING - Skipping BIOMD0000001103.xml - no results generated

Evaluating 1074/1075: BIOMD0000001102.xml
Evaluating 1075/1075: BIOMD0000001103.xml

In [5]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-3_top10_autoType.csv")

Filtered results to 9312 entries that exist in reference: /Users/luna/Desktop/CRBM/AMAS_proj/Results/biomd_species_accuracy_AMAS.csv
Number of models assessed: 303
Number of models with predictions: 303
Number of annotations evaluated: 9312
Average accuracy (per model): 0.94
Ave. recall (formula): 0.94
Ave. precision (formula): 0.23
Ave. recall (exact): 0.88
Ave. precision (exact): 0.09
Average accuracy (per species): 0.94
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.22
Ave. recall (exact, per species): 0.74
Ave. precision (exact, per species): 0.11
Ave. total time (per model): 21.80
Ave. total time (per element, per model): 0.71
Ave. LLM time (per model): 21.00
Ave. LLM time (per element, per model): 0.68
Average number of predictions per species: 9.94

## Uniprot

In [ ]:
# Run batch evaluation on updated BioModels
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database='uniprot',
    method="direct",
    top_k = 3,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_uniprot_direct_llama-4_top3_autoType_updated_prompts.csv",
    start_at=1
)

In [13]:
print_evaluation_results("autoType/biomd251106_uniprot_direct_llama-4_top3_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 472
Number of models with predictions: 352
Number of annotations evaluated: 7825
Average accuracy (per model): 0.07
Ave. recall (formula): 0.00
Ave. precision (formula): 0.00
Ave. recall (exact): 0.07
Ave. precision (exact): 0.06
Average accuracy (per species): 0.03
Ave. recall (formula, per species): 0.00
Ave. precision (formula, per species): 0.00
Ave. recall (exact, per species): 0.03
Ave. precision (exact, per species): 0.02
Ave. total time (per model): 11.71
Ave. total time (per element, per model): 0.71
Ave. LLM time (per model): 11.51
Ave. LLM time (per element, per model): 0.69
Average number of predictions per species: 0.32

In [19]:
model_dir = '/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioDivine/'

# Check if model directory exists
if os.path.exists(model_dir):
    model_files = [f for f in os.listdir(model_dir) if f.endswith('.sbml')]
    print(f"✓ Model directory found: {model_dir}")
    print(f"  - Found {len(model_files)} SBML files")

✓ Model directory found: /Users/luna/Desktop/CRBM/AMAS_proj/Models/BioDivine/
  - Found 190 SBML files

In [ ]:
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    top_k=3,
    entity_type='auto',
    database='uniprot',
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biodivine_uniprot_direct_llama-3_top5_9606_autoType.csv",
    start_at=1,
    tax_id = 9606
)

In [22]:
print_evaluation_results("autoType/biodivine_uniprot_direct_llama-3_top5_9606_autoType.csv", ref_results_csv=None)

Showing all results
Number of models assessed: 15
Number of models with predictions: 8
Number of annotations evaluated: 605
Average accuracy (per model): 0.00
Ave. recall (formula): 0.00
Ave. precision (formula): 0.00
Ave. recall (exact): 0.00
Ave. precision (exact): 0.00
Average accuracy (per species): 0.00
Ave. recall (formula, per species): 0.00
Ave. precision (formula, per species): 0.00
Ave. recall (exact, per species): 0.00
Ave. precision (exact, per species): 0.00
Ave. total time (per model): 14.54
Ave. total time (per element, per model): 0.36
Ave. LLM time (per model): 14.34
Ave. LLM time (per element, per model): 0.36
Average number of predictions per species: 0.08

## chebi + uniprot

In [10]:
batch_results_df = evaluate_models_in_folder(
    model_dir=model_dir,
    llm_model="Llama-4-Maverick-17B-128E-Instruct-FP8",
    entity_type='auto',
    database=['chebi', 'uniprot'],
    method="direct",
    top_k = 3,
    save_llm_results=True,
    output_dir=output_dir,
    output_file="biomd251106_chebi+uniprot_direct_llama-4_top3_autoType.csv",
    start_at=1
)

2025-12-06 22:37:18,134 - WARNING - Skipping BIOMD0000000001.xml - no results generated

LLM results will be saved to: ./autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237
Saved configuration to ./autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/config.txt
Evaluating 1/1075: BIOMD0000000001.xml
Evaluating 2/1075: BIOMD0000000002.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000002.txt
Evaluating 3/1075: BIOMD0000000003.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000003.txt
Evaluating 4/1075: BIOMD0000000004.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000004.txt
Evaluating 5/1075: BIOMD0000000005.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000005.txt
Evaluating 6/1075: BIOMD0000000006.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000006.txt
Evaluating 7/1075: BIOMD0000000007.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000007.txt
Evaluating 8/1075: BIOMD0000000008.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000008.txt
Evaluating 9/1075: BIOMD0000000009.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000009.txt
Evaluating 10/1075: BIOMD0000000010.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000010.txt
Evaluating 11/1075: BIOMD0000000011.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000011.txt
Evaluating 12/1075: BIOMD0000000012.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000012.txt
Evaluating 13/1075: BIOMD0000000013.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000013.txt
Evaluating 14/1075: BIOMD0000000014.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000014.txt
Evaluating 15/1075: BIOMD0000000015.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000015.txt
Evaluating 16/1075: BIOMD0000000016.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000016.txt
Evaluating 17/1075: BIOMD0000000017.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000017.txt
Evaluating 18/1075: BIOMD0000000018.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000018.txt
Evaluating 19/1075: BIOMD0000000019.xml

2025-12-06 22:39:42,915 - WARNING - Skipping BIOMD0000000020.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000019.txt
Evaluating 20/1075: BIOMD0000000020.xml
Evaluating 21/1075: BIOMD0000000021.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000021.txt
Evaluating 22/1075: BIOMD0000000022.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000022.txt
Evaluating 23/1075: BIOMD0000000023.xml

2025-12-06 22:39:53,391 - WARNING - Skipping BIOMD0000000024.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000023.txt
Evaluating 24/1075: BIOMD0000000024.xml
Evaluating 25/1075: BIOMD0000000025.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000025.txt
Evaluating 26/1075: BIOMD0000000026.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000026.txt
Evaluating 27/1075: BIOMD0000000027.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000027.txt
Evaluating 28/1075: BIOMD0000000028.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000028.txt
Evaluating 29/1075: BIOMD0000000029.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000029.txt
Evaluating 30/1075: BIOMD0000000030.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000030.txt
Evaluating 31/1075: BIOMD0000000031.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000031.txt
Evaluating 32/1075: BIOMD0000000032.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000032.txt
Evaluating 33/1075: BIOMD0000000033.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000033.txt
Evaluating 34/1075: BIOMD0000000034.xml

2025-12-06 22:40:54,101 - WARNING - Skipping BIOMD0000000035.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000034.txt
Evaluating 35/1075: BIOMD0000000035.xml
Evaluating 36/1075: BIOMD0000000036.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000036.txt
Evaluating 37/1075: BIOMD0000000037.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000037.txt
Evaluating 38/1075: BIOMD0000000038.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000038.txt
Evaluating 39/1075: BIOMD0000000039.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000039.txt
Evaluating 40/1075: BIOMD0000000040.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000040.txt
Evaluating 41/1075: BIOMD0000000041.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000041.txt
Evaluating 42/1075: BIOMD0000000042.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000042.txt
Evaluating 43/1075: BIOMD0000000043.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000043.txt
Evaluating 44/1075: BIOMD0000000044.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000044.txt
Evaluating 45/1075: BIOMD0000000045.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000045.txt
Evaluating 46/1075: BIOMD0000000046.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000046.txt
Evaluating 47/1075: BIOMD0000000047.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000047.txt
Evaluating 48/1075: BIOMD0000000048.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000048.txt
Evaluating 49/1075: BIOMD0000000049.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000049.txt
Evaluating 50/1075: BIOMD0000000050.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000050.txt
Evaluating 51/1075: BIOMD0000000051.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000051.txt
Evaluating 52/1075: BIOMD0000000052.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000052.txt
Evaluating 53/1075: BIOMD0000000053.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000053.txt
Evaluating 54/1075: BIOMD0000000054.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000054.txt
Evaluating 55/1075: BIOMD0000000055.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000055.txt
Evaluating 56/1075: BIOMD0000000056.xml

2025-12-06 22:43:21,265 - WARNING - Skipping BIOMD0000000057.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000056.txt
Evaluating 57/1075: BIOMD0000000057.xml
Evaluating 58/1075: BIOMD0000000058.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000058.txt
Evaluating 59/1075: BIOMD0000000059.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000059.txt
Evaluating 60/1075: BIOMD0000000060.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000060.txt
Evaluating 61/1075: BIOMD0000000061.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000061.txt
Evaluating 62/1075: BIOMD0000000062.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000062.txt
Evaluating 63/1075: BIOMD0000000063.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000063.txt
Evaluating 64/1075: BIOMD0000000064.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000064.txt
Evaluating 65/1075: BIOMD0000000065.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000065.txt
Evaluating 66/1075: BIOMD0000000066.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000066.txt
Evaluating 67/1075: BIOMD0000000067.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000067.txt
Evaluating 68/1075: BIOMD0000000068.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000068.txt
Evaluating 69/1075: BIOMD0000000069.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000069.txt
Evaluating 70/1075: BIOMD0000000070.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000070.txt
Evaluating 71/1075: BIOMD0000000071.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000071.txt
Evaluating 72/1075: BIOMD0000000072.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000072.txt
Evaluating 73/1075: BIOMD0000000073.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000073.txt
Evaluating 74/1075: BIOMD0000000074.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000074.txt
Evaluating 75/1075: BIOMD0000000075.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000075.txt
Evaluating 76/1075: BIOMD0000000076.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000076.txt
Evaluating 77/1075: BIOMD0000000077.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000077.txt
Evaluating 78/1075: BIOMD0000000078.xml

2025-12-06 22:44:56,593 - WARNING - Skipping BIOMD0000000079.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000078.txt
Evaluating 79/1075: BIOMD0000000079.xml
Evaluating 80/1075: BIOMD0000000080.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000080.txt
Evaluating 81/1075: BIOMD0000000081.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000081.txt
Evaluating 82/1075: BIOMD0000000082.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000082.txt
Evaluating 83/1075: BIOMD0000000083.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000083.txt
Evaluating 84/1075: BIOMD0000000084.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000084.txt
Evaluating 85/1075: BIOMD0000000085.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000085.txt
Evaluating 86/1075: BIOMD0000000086.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000086.txt
Evaluating 87/1075: BIOMD0000000087.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000087.txt
Evaluating 88/1075: BIOMD0000000088.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000088.txt
Evaluating 89/1075: BIOMD0000000089.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000089.txt
Evaluating 90/1075: BIOMD0000000090.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000090.txt
Evaluating 91/1075: BIOMD0000000091.xml

2025-12-06 22:46:51,942 - WARNING - Skipping BIOMD0000000092.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000091.txt
Evaluating 92/1075: BIOMD0000000092.xml
Evaluating 93/1075: BIOMD0000000093.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000093.txt
Evaluating 94/1075: BIOMD0000000094.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000094.txt
Evaluating 95/1075: BIOMD0000000095.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000095.txt
Evaluating 96/1075: BIOMD0000000096.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000096.txt
Evaluating 97/1075: BIOMD0000000097.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000097.txt
Evaluating 98/1075: BIOMD0000000098.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000098.txt
Evaluating 99/1075: BIOMD0000000099.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000099.txt
Evaluating 100/1075: BIOMD0000000100.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000100.txt
Evaluating 101/1075: BIOMD0000000101.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000101.txt
Evaluating 102/1075: BIOMD0000000102.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000102.txt
Evaluating 103/1075: BIOMD0000000103.xml

2025-12-06 22:47:59,726 - WARNING - Skipping BIOMD0000000104.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000103.txt
Evaluating 104/1075: BIOMD0000000104.xml
Evaluating 105/1075: BIOMD0000000105.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000105.txt
Evaluating 106/1075: BIOMD0000000106.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000106.txt
Evaluating 107/1075: BIOMD0000000107.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000107.txt
Evaluating 108/1075: BIOMD0000000108.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000108.txt
Evaluating 109/1075: BIOMD0000000109.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000109.txt
Evaluating 110/1075: BIOMD0000000110.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000110.txt
Evaluating 111/1075: BIOMD0000000111.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000111.txt
Evaluating 112/1075: BIOMD0000000112.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000112.txt
Evaluating 113/1075: BIOMD0000000113.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000113.txt
Evaluating 114/1075: BIOMD0000000114.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000114.txt
Evaluating 115/1075: BIOMD0000000115.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000115.txt
Evaluating 116/1075: BIOMD0000000116.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000116.txt
Evaluating 117/1075: BIOMD0000000117.xml

2025-12-06 22:49:04,767 - WARNING - Skipping BIOMD0000000118.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000117.txt
Evaluating 118/1075: BIOMD0000000118.xml
Evaluating 119/1075: BIOMD0000000119.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000119.txt
Evaluating 120/1075: BIOMD0000000120.xml

2025-12-06 22:49:08,352 - WARNING - Skipping BIOMD0000000121.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000120.txt
Evaluating 121/1075: BIOMD0000000121.xml
Evaluating 122/1075: BIOMD0000000122.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000122.txt
Evaluating 123/1075: BIOMD0000000123.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000123.txt
Evaluating 124/1075: BIOMD0000000124.xml

2025-12-06 22:49:22,142 - WARNING - Skipping BIOMD0000000125.xml - no results generated
2025-12-06 22:49:22,155 - WARNING - Skipping BIOMD0000000126.xml - no results generated
2025-12-06 22:49:22,159 - WARNING - Skipping BIOMD0000000127.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000124.txt
Evaluating 125/1075: BIOMD0000000125.xml
Evaluating 126/1075: BIOMD0000000126.xml
Evaluating 127/1075: BIOMD0000000127.xml
Evaluating 128/1075: BIOMD0000000128.xml

2025-12-06 22:49:23,737 - WARNING - Skipping BIOMD0000000129.xml - no results generated
2025-12-06 22:49:23,741 - WARNING - Skipping BIOMD0000000130.xml - no results generated
2025-12-06 22:49:23,744 - WARNING - Skipping BIOMD0000000131.xml - no results generated
2025-12-06 22:49:23,749 - WARNING - Skipping BIOMD0000000132.xml - no results generated
2025-12-06 22:49:23,753 - WARNING - Skipping BIOMD0000000133.xml - no results generated
2025-12-06 22:49:23,757 - WARNING - Skipping BIOMD0000000134.xml - no results generated
2025-12-06 22:49:23,761 - WARNING - Skipping BIOMD0000000135.xml - no results generated
2025-12-06 22:49:23,765 - WARNING - Skipping BIOMD0000000136.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000128.txt
Evaluating 129/1075: BIOMD0000000129.xml
Evaluating 130/1075: BIOMD0000000130.xml
Evaluating 131/1075: BIOMD0000000131.xml
Evaluating 132/1075: BIOMD0000000132.xml
Evaluating 133/1075: BIOMD0000000133.xml
Evaluating 134/1075: BIOMD0000000134.xml
Evaluating 135/1075: BIOMD0000000135.xml
Evaluating 136/1075: BIOMD0000000136.xml
Evaluating 137/1075: BIOMD0000000137.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000137.txt
Evaluating 138/1075: BIOMD0000000138.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000138.txt
Evaluating 139/1075: BIOMD0000000139.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000139.txt
Evaluating 140/1075: BIOMD0000000140.xml

2025-12-06 22:49:56,883 - WARNING - Skipping BIOMD0000000141.xml - no results generated
2025-12-06 22:49:56,886 - WARNING - Skipping BIOMD0000000142.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000140.txt
Evaluating 141/1075: BIOMD0000000141.xml
Evaluating 142/1075: BIOMD0000000142.xml
Evaluating 143/1075: BIOMD0000000143.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000143.txt
Evaluating 144/1075: BIOMD0000000144.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000144.txt
Evaluating 145/1075: BIOMD0000000145.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000145.txt
Evaluating 146/1075: BIOMD0000000146.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000146.txt
Evaluating 147/1075: BIOMD0000000147.xml

2025-12-06 22:50:38,158 - WARNING - Skipping BIOMD0000000148.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000147.txt
Evaluating 148/1075: BIOMD0000000148.xml
Evaluating 149/1075: BIOMD0000000149.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000149.txt
Evaluating 150/1075: BIOMD0000000150.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000150.txt
Evaluating 151/1075: BIOMD0000000151.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000151.txt
Evaluating 152/1075: BIOMD0000000152.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000152.txt
Evaluating 153/1075: BIOMD0000000153.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000153.txt
Evaluating 154/1075: BIOMD0000000154.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000154.txt
Evaluating 155/1075: BIOMD0000000155.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000155.txt
Evaluating 156/1075: BIOMD0000000156.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000156.txt
Evaluating 157/1075: BIOMD0000000157.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000157.txt
Evaluating 158/1075: BIOMD0000000158.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000158.txt
Evaluating 159/1075: BIOMD0000000159.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000159.txt
Evaluating 160/1075: BIOMD0000000160.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000160.txt
Evaluating 161/1075: BIOMD0000000161.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000161.txt
Evaluating 162/1075: BIOMD0000000162.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000162.txt
Evaluating 163/1075: BIOMD0000000163.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000163.txt
Evaluating 164/1075: BIOMD0000000164.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000164.txt
Evaluating 165/1075: BIOMD0000000165.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000165.txt
Evaluating 166/1075: BIOMD0000000166.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000166.txt
Evaluating 167/1075: BIOMD0000000167.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000167.txt
Evaluating 168/1075: BIOMD0000000168.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000168.txt
Evaluating 169/1075: BIOMD0000000169.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000169.txt
Evaluating 170/1075: BIOMD0000000170.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000170.txt
Evaluating 171/1075: BIOMD0000000171.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000171.txt
Evaluating 172/1075: BIOMD0000000172.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000172.txt
Evaluating 173/1075: BIOMD0000000173.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000173.txt
Evaluating 174/1075: BIOMD0000000174.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000174.txt
Evaluating 175/1075: BIOMD0000000175.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000175.txt
Evaluating 176/1075: BIOMD0000000176.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000176.txt
Evaluating 177/1075: BIOMD0000000177.xml

2025-12-06 22:54:42,104 - WARNING - Skipping BIOMD0000000178.xml - no results generated
2025-12-06 22:54:42,114 - WARNING - Skipping BIOMD0000000179.xml - no results generated
2025-12-06 22:54:42,125 - WARNING - Skipping BIOMD0000000180.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000177.txt
Evaluating 178/1075: BIOMD0000000178.xml
Evaluating 179/1075: BIOMD0000000179.xml
Evaluating 180/1075: BIOMD0000000180.xml
Evaluating 181/1075: BIOMD0000000181.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000181.txt
Evaluating 182/1075: BIOMD0000000182.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000182.txt
Evaluating 183/1075: BIOMD0000000183.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000183.txt
Evaluating 184/1075: BIOMD0000000184.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000184.txt
Evaluating 185/1075: BIOMD0000000185.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000185.txt
Evaluating 186/1075: BIOMD0000000186.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000186.txt
Evaluating 187/1075: BIOMD0000000187.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000187.txt
Evaluating 188/1075: BIOMD0000000188.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000188.txt
Evaluating 189/1075: BIOMD0000000189.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000189.txt
Evaluating 190/1075: BIOMD0000000190.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000190.txt
Evaluating 191/1075: BIOMD0000000191.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000191.txt
Evaluating 192/1075: BIOMD0000000192.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000192.txt
Evaluating 193/1075: BIOMD0000000193.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000193.txt
Evaluating 194/1075: BIOMD0000000194.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000194.txt
Evaluating 195/1075: BIOMD0000000195.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000195.txt
Evaluating 196/1075: BIOMD0000000196.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000196.txt
Evaluating 197/1075: BIOMD0000000197.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000197.txt
Evaluating 198/1075: BIOMD0000000198.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000198.txt
Evaluating 199/1075: BIOMD0000000199.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000199.txt
Evaluating 200/1075: BIOMD0000000200.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000200.txt
Evaluating 201/1075: BIOMD0000000201.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000201.txt
Evaluating 202/1075: BIOMD0000000202.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000202.txt
Evaluating 203/1075: BIOMD0000000203.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000203.txt
Evaluating 204/1075: BIOMD0000000204.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000204.txt
Evaluating 205/1075: BIOMD0000000205.xml
Error querying Llama: Error code: 400 - {'title': 'Timeout', 'detail': 'This request took too long to complete. Enable streaming mode and try again.', 'status': 400}
Failed to parse response:

Error response saved to: error_response_1765090748.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000205.txt
Evaluating 206/1075: BIOMD0000000206.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000206.txt
Evaluating 207/1075: BIOMD0000000207.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000207.txt
Evaluating 208/1075: BIOMD0000000208.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000208.txt
Evaluating 209/1075: BIOMD0000000209.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000209.txt
Evaluating 210/1075: BIOMD0000000210.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000210.txt
Evaluating 211/1075: BIOMD0000000211.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000211.txt
Evaluating 212/1075: BIOMD0000000212.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000212.txt
Evaluating 213/1075: BIOMD0000000213.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000213.txt
Evaluating 214/1075: BIOMD0000000214.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000214.txt
Evaluating 215/1075: BIOMD0000000215.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000215.txt
Evaluating 216/1075: BIOMD0000000216.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000216.txt
Evaluating 217/1075: BIOMD0000000217.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000217.txt
Evaluating 218/1075: BIOMD0000000218.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000218.txt
Evaluating 219/1075: BIOMD0000000219.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000219.txt
Evaluating 220/1075: BIOMD0000000220.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000220.txt
Evaluating 221/1075: BIOMD0000000221.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000221.txt
Evaluating 222/1075: BIOMD0000000222.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000222.txt
Evaluating 223/1075: BIOMD0000000223.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000223.txt
Evaluating 224/1075: BIOMD0000000224.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000224.txt
Evaluating 225/1075: BIOMD0000000225.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000225.txt
Evaluating 226/1075: BIOMD0000000226.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000226.txt
Evaluating 227/1075: BIOMD0000000227.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000227.txt
Evaluating 228/1075: BIOMD0000000228.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000228.txt
Evaluating 229/1075: BIOMD0000000229.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000229.txt
Evaluating 230/1075: BIOMD0000000230.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000230.txt
Evaluating 231/1075: BIOMD0000000231.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000231.txt
Evaluating 232/1075: BIOMD0000000232.xml

2025-12-06 23:04:33,334 - WARNING - Skipping BIOMD0000000233.xml - no results generated
2025-12-06 23:04:33,340 - WARNING - Skipping BIOMD0000000234.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000232.txt
Evaluating 233/1075: BIOMD0000000233.xml
Evaluating 234/1075: BIOMD0000000234.xml
Evaluating 235/1075: BIOMD0000000235.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000235.txt
Evaluating 236/1075: BIOMD0000000236.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000236.txt
Evaluating 237/1075: BIOMD0000000237.xml

2025-12-06 23:06:13,619 - WARNING - Skipping BIOMD0000000238.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000237.txt
Evaluating 238/1075: BIOMD0000000238.xml
Evaluating 239/1075: BIOMD0000000239.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000239.txt
Evaluating 240/1075: BIOMD0000000240.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000240.txt
Evaluating 241/1075: BIOMD0000000241.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000241.txt
Evaluating 242/1075: BIOMD0000000242.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000242.txt
Evaluating 243/1075: BIOMD0000000243.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000243.txt
Evaluating 244/1075: BIOMD0000000244.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000244.txt
Evaluating 245/1075: BIOMD0000000245.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000245.txt
Evaluating 246/1075: BIOMD0000000246.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000246.txt
Evaluating 247/1075: BIOMD0000000247.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000247.txt
Evaluating 248/1075: BIOMD0000000248.xml

2025-12-06 23:07:27,740 - WARNING - Skipping BIOMD0000000249.xml - no results generated
2025-12-06 23:07:27,776 - WARNING - Skipping BIOMD0000000250.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000248.txt
Evaluating 249/1075: BIOMD0000000249.xml
Evaluating 250/1075: BIOMD0000000250.xml
Evaluating 251/1075: BIOMD0000000251.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000251.txt
Evaluating 252/1075: BIOMD0000000252.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000252.txt
Evaluating 253/1075: BIOMD0000000253.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000253.txt
Evaluating 254/1075: BIOMD0000000254.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000254.txt
Evaluating 255/1075: BIOMD0000000255.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000255.txt
Evaluating 256/1075: BIOMD0000000256.xml

2025-12-06 23:08:23,495 - WARNING - Skipping BIOMD0000000257.xml - no results generated
2025-12-06 23:08:23,499 - WARNING - Skipping BIOMD0000000258.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000256.txt
Evaluating 257/1075: BIOMD0000000257.xml
Evaluating 258/1075: BIOMD0000000258.xml
Evaluating 259/1075: BIOMD0000000259.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000259.txt
Evaluating 260/1075: BIOMD0000000260.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000260.txt
Evaluating 261/1075: BIOMD0000000261.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000261.txt
Evaluating 262/1075: BIOMD0000000262.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000262.txt
Evaluating 263/1075: BIOMD0000000263.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000263.txt
Evaluating 264/1075: BIOMD0000000264.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000264.txt
Evaluating 265/1075: BIOMD0000000265.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000265.txt
Evaluating 266/1075: BIOMD0000000266.xml

2025-12-06 23:09:12,934 - WARNING - Skipping BIOMD0000000267.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000266.txt
Evaluating 267/1075: BIOMD0000000267.xml
Evaluating 268/1075: BIOMD0000000268.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000268.txt
Evaluating 269/1075: BIOMD0000000269.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000269.txt
Evaluating 270/1075: BIOMD0000000270.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000270.txt
Evaluating 271/1075: BIOMD0000000271.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000271.txt
Evaluating 272/1075: BIOMD0000000272.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000272.txt
Evaluating 273/1075: BIOMD0000000273.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000273.txt
Evaluating 274/1075: BIOMD0000000274.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000274.txt
Evaluating 275/1075: BIOMD0000000275.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000275.txt
Evaluating 276/1075: BIOMD0000000276.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000276.txt
Evaluating 277/1075: BIOMD0000000277.xml

2025-12-06 23:10:01,343 - WARNING - Skipping BIOMD0000000278.xml - no results generated
2025-12-06 23:10:01,348 - WARNING - Skipping BIOMD0000000279.xml - no results generated
2025-12-06 23:10:01,352 - WARNING - Skipping BIOMD0000000280.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000277.txt
Evaluating 278/1075: BIOMD0000000278.xml
Evaluating 279/1075: BIOMD0000000279.xml
Evaluating 280/1075: BIOMD0000000280.xml
Evaluating 281/1075: BIOMD0000000281.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000281.txt
Evaluating 282/1075: BIOMD0000000282.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000282.txt
Evaluating 283/1075: BIOMD0000000283.xml

2025-12-06 23:10:16,488 - WARNING - Skipping BIOMD0000000284.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000283.txt
Evaluating 284/1075: BIOMD0000000284.xml
Evaluating 285/1075: BIOMD0000000285.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000285.txt
Evaluating 286/1075: BIOMD0000000286.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000286.txt
Evaluating 287/1075: BIOMD0000000287.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000287.txt
Evaluating 288/1075: BIOMD0000000288.xml

2025-12-06 23:13:01,086 - WARNING - Skipping BIOMD0000000289.xml - no results generated
2025-12-06 23:13:01,096 - WARNING - Skipping BIOMD0000000290.xml - no results generated

Error querying Llama: Error code: 400 - {'title': 'Timeout', 'detail': 'This request took too long to complete. Enable streaming mode and try again.', 'status': 400}
Failed to parse response:

Error response saved to: error_response_1765091581.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000288.txt
Evaluating 289/1075: BIOMD0000000289.xml
Evaluating 290/1075: BIOMD0000000290.xml
Evaluating 291/1075: BIOMD0000000291.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091589.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000291.txt
Evaluating 292/1075: BIOMD0000000292.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091597.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000292.txt
Evaluating 293/1075: BIOMD0000000293.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091605.txt
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091613.txt

2025-12-06 23:13:41,384 - WARNING - Skipping BIOMD0000000294.xml - no results generated

Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091621.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000293.txt
Evaluating 294/1075: BIOMD0000000294.xml
Evaluating 295/1075: BIOMD0000000295.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091629.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000295.txt
Evaluating 296/1075: BIOMD0000000296.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091637.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000296.txt
Evaluating 297/1075: BIOMD0000000297.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091646.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000297.txt
Evaluating 298/1075: BIOMD0000000298.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091652.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000298.txt
Evaluating 299/1075: BIOMD0000000299.xml
Error querying Llama: Error code: 429 - {'title': 'too_many_requests', 'detail': 'You have exceeded the maximum number of requests allowed within a given time frame. Wait a bit and try again.', 'status': 429}
Failed to parse response:

Error response saved to: error_response_1765091660.txt
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000299.txt
Evaluating 300/1075: BIOMD0000000300.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000300.txt
Evaluating 301/1075: BIOMD0000000301.xml

2025-12-06 23:14:35,987 - WARNING - Skipping BIOMD0000000302.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000301.txt
Evaluating 302/1075: BIOMD0000000302.xml
Evaluating 303/1075: BIOMD0000000303.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000303.txt
Evaluating 304/1075: BIOMD0000000304.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000304.txt
Evaluating 305/1075: BIOMD0000000305.xml

2025-12-06 23:15:03,292 - WARNING - Skipping BIOMD0000000306.xml - no results generated
2025-12-06 23:15:03,298 - WARNING - Skipping BIOMD0000000307.xml - no results generated
2025-12-06 23:15:03,305 - WARNING - Skipping BIOMD0000000308.xml - no results generated
2025-12-06 23:15:03,312 - WARNING - Skipping BIOMD0000000309.xml - no results generated
2025-12-06 23:15:03,320 - WARNING - Skipping BIOMD0000000310.xml - no results generated
2025-12-06 23:15:03,326 - WARNING - Skipping BIOMD0000000311.xml - no results generated
2025-12-06 23:15:03,331 - WARNING - Skipping BIOMD0000000312.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000305.txt
Evaluating 306/1075: BIOMD0000000306.xml
Evaluating 307/1075: BIOMD0000000307.xml
Evaluating 308/1075: BIOMD0000000308.xml
Evaluating 309/1075: BIOMD0000000309.xml
Evaluating 310/1075: BIOMD0000000310.xml
Evaluating 311/1075: BIOMD0000000311.xml
Evaluating 312/1075: BIOMD0000000312.xml
Evaluating 313/1075: BIOMD0000000313.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000313.txt
Evaluating 314/1075: BIOMD0000000314.xml

2025-12-06 23:15:22,822 - WARNING - Skipping BIOMD0000000315.xml - no results generated
2025-12-06 23:15:22,828 - WARNING - Skipping BIOMD0000000316.xml - no results generated
2025-12-06 23:15:22,836 - WARNING - Skipping BIOMD0000000317.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000314.txt
Evaluating 315/1075: BIOMD0000000315.xml
Evaluating 316/1075: BIOMD0000000316.xml
Evaluating 317/1075: BIOMD0000000317.xml
Evaluating 318/1075: BIOMD0000000318.xml

2025-12-06 23:15:26,467 - WARNING - Skipping BIOMD0000000319.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000318.txt
Evaluating 319/1075: BIOMD0000000319.xml
Evaluating 320/1075: BIOMD0000000320.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000320.txt
Evaluating 321/1075: BIOMD0000000321.xml

2025-12-06 23:15:30,957 - WARNING - Skipping BIOMD0000000322.xml - no results generated
2025-12-06 23:15:30,967 - WARNING - Skipping BIOMD0000000323.xml - no results generated
2025-12-06 23:15:30,972 - WARNING - Skipping BIOMD0000000324.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000321.txt
Evaluating 322/1075: BIOMD0000000322.xml
Evaluating 323/1075: BIOMD0000000323.xml
Evaluating 324/1075: BIOMD0000000324.xml
Evaluating 325/1075: BIOMD0000000325.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000325.txt
Evaluating 326/1075: BIOMD0000000326.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000326.txt
Evaluating 327/1075: BIOMD0000000327.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000327.txt
Evaluating 328/1075: BIOMD0000000328.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000328.txt
Evaluating 329/1075: BIOMD0000000329.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000329.txt
Evaluating 330/1075: BIOMD0000000330.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000330.txt
Evaluating 331/1075: BIOMD0000000331.xml

2025-12-06 23:16:24,988 - WARNING - Skipping BIOMD0000000332.xml - no results generated
2025-12-06 23:16:25,022 - WARNING - Skipping BIOMD0000000333.xml - no results generated
2025-12-06 23:16:25,074 - WARNING - Skipping BIOMD0000000334.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000331.txt
Evaluating 332/1075: BIOMD0000000332.xml
Evaluating 333/1075: BIOMD0000000333.xml
Evaluating 334/1075: BIOMD0000000334.xml
Evaluating 335/1075: BIOMD0000000335.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000335.txt
Evaluating 336/1075: BIOMD0000000336.xml

2025-12-06 23:16:46,610 - WARNING - Skipping BIOMD0000000337.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000336.txt
Evaluating 337/1075: BIOMD0000000337.xml
Evaluating 338/1075: BIOMD0000000338.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000338.txt
Evaluating 339/1075: BIOMD0000000339.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000339.txt
Evaluating 340/1075: BIOMD0000000340.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000340.txt
Evaluating 341/1075: BIOMD0000000341.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000341.txt
Evaluating 342/1075: BIOMD0000000342.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000342.txt
Evaluating 343/1075: BIOMD0000000343.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000343.txt
Evaluating 344/1075: BIOMD0000000344.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000344.txt
Evaluating 345/1075: BIOMD0000000345.xml

2025-12-06 23:18:03,629 - WARNING - Skipping BIOMD0000000346.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000345.txt
Evaluating 346/1075: BIOMD0000000346.xml
Evaluating 347/1075: BIOMD0000000347.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000347.txt
Evaluating 348/1075: BIOMD0000000348.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000348.txt
Evaluating 349/1075: BIOMD0000000349.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000349.txt
Evaluating 350/1075: BIOMD0000000350.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000350.txt
Evaluating 351/1075: BIOMD0000000351.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000351.txt
Evaluating 352/1075: BIOMD0000000352.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000352.txt
Evaluating 353/1075: BIOMD0000000353.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000353.txt
Evaluating 354/1075: BIOMD0000000354.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000354.txt
Evaluating 355/1075: BIOMD0000000355.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000355.txt
Evaluating 356/1075: BIOMD0000000356.xml

2025-12-06 23:18:49,828 - WARNING - Skipping BIOMD0000000357.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000356.txt
Evaluating 357/1075: BIOMD0000000357.xml
Evaluating 358/1075: BIOMD0000000358.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000358.txt
Evaluating 359/1075: BIOMD0000000359.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000359.txt
Evaluating 360/1075: BIOMD0000000360.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000360.txt
Evaluating 361/1075: BIOMD0000000361.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000361.txt
Evaluating 362/1075: BIOMD0000000362.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000362.txt
Evaluating 363/1075: BIOMD0000000363.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000363.txt
Evaluating 364/1075: BIOMD0000000364.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000364.txt
Evaluating 365/1075: BIOMD0000000365.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000365.txt
Evaluating 366/1075: BIOMD0000000366.xml

2025-12-06 23:19:41,189 - WARNING - Skipping BIOMD0000000367.xml - no results generated
2025-12-06 23:19:41,192 - WARNING - Skipping BIOMD0000000368.xml - no results generated
2025-12-06 23:19:41,196 - WARNING - Skipping BIOMD0000000369.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000366.txt
Evaluating 367/1075: BIOMD0000000367.xml
Evaluating 368/1075: BIOMD0000000368.xml
Evaluating 369/1075: BIOMD0000000369.xml
Evaluating 370/1075: BIOMD0000000370.xml

2025-12-06 23:19:54,156 - WARNING - Skipping BIOMD0000000371.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000370.txt
Evaluating 371/1075: BIOMD0000000371.xml
Evaluating 372/1075: BIOMD0000000372.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000372.txt
Evaluating 373/1075: BIOMD0000000373.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000373.txt
Evaluating 374/1075: BIOMD0000000374.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000374.txt
Evaluating 375/1075: BIOMD0000000375.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000375.txt
Evaluating 376/1075: BIOMD0000000376.xml

2025-12-06 23:20:06,901 - WARNING - Skipping BIOMD0000000377.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000376.txt
Evaluating 377/1075: BIOMD0000000377.xml
Evaluating 378/1075: BIOMD0000000378.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000378.txt
Evaluating 379/1075: BIOMD0000000379.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000379.txt
Evaluating 380/1075: BIOMD0000000380.xml

2025-12-06 23:20:17,444 - WARNING - Skipping BIOMD0000000381.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000380.txt
Evaluating 381/1075: BIOMD0000000381.xml
Evaluating 382/1075: BIOMD0000000382.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000382.txt
Evaluating 383/1075: BIOMD0000000383.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000383.txt
Evaluating 384/1075: BIOMD0000000384.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000384.txt
Evaluating 385/1075: BIOMD0000000385.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000385.txt
Evaluating 386/1075: BIOMD0000000386.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000386.txt
Evaluating 387/1075: BIOMD0000000387.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000387.txt
Evaluating 388/1075: BIOMD0000000388.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000388.txt
Evaluating 389/1075: BIOMD0000000389.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000389.txt
Evaluating 390/1075: BIOMD0000000390.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000390.txt
Evaluating 391/1075: BIOMD0000000391.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000391.txt
Evaluating 392/1075: BIOMD0000000392.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000392.txt
Evaluating 393/1075: BIOMD0000000393.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000393.txt
Evaluating 394/1075: BIOMD0000000394.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000394.txt
Evaluating 395/1075: BIOMD0000000395.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000395.txt
Evaluating 396/1075: BIOMD0000000396.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000396.txt
Evaluating 397/1075: BIOMD0000000397.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000397.txt
Evaluating 398/1075: BIOMD0000000398.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000398.txt
Evaluating 399/1075: BIOMD0000000399.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000399.txt
Evaluating 400/1075: BIOMD0000000400.xml

2025-12-06 23:22:51,577 - WARNING - Skipping BIOMD0000000401.xml - no results generated
2025-12-06 23:22:51,583 - WARNING - Skipping BIOMD0000000402.xml - no results generated
2025-12-06 23:22:51,589 - WARNING - Skipping BIOMD0000000403.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000400.txt
Evaluating 401/1075: BIOMD0000000401.xml
Evaluating 402/1075: BIOMD0000000402.xml
Evaluating 403/1075: BIOMD0000000403.xml
Evaluating 404/1075: BIOMD0000000404.xml

2025-12-06 23:23:04,671 - WARNING - Skipping BIOMD0000000405.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000404.txt
Evaluating 405/1075: BIOMD0000000405.xml
Evaluating 406/1075: BIOMD0000000406.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000406.txt
Evaluating 407/1075: BIOMD0000000407.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000407.txt
Evaluating 408/1075: BIOMD0000000408.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000408.txt
Evaluating 409/1075: BIOMD0000000409.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000409.txt
Evaluating 410/1075: BIOMD0000000410.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000410.txt
Evaluating 411/1075: BIOMD0000000411.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000411.txt
Evaluating 412/1075: BIOMD0000000412.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000412.txt
Evaluating 413/1075: BIOMD0000000413.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000413.txt
Evaluating 414/1075: BIOMD0000000414.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000414.txt
Evaluating 415/1075: BIOMD0000000415.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000415.txt
Evaluating 416/1075: BIOMD0000000416.xml

2025-12-06 23:24:34,379 - WARNING - Skipping BIOMD0000000417.xml - no results generated
2025-12-06 23:24:34,382 - WARNING - Skipping BIOMD0000000418.xml - no results generated
2025-12-06 23:24:34,388 - WARNING - Skipping BIOMD0000000419.xml - no results generated
2025-12-06 23:24:34,393 - WARNING - Skipping BIOMD0000000420.xml - no results generated
2025-12-06 23:24:34,398 - WARNING - Skipping BIOMD0000000421.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000416.txt
Evaluating 417/1075: BIOMD0000000417.xml
Evaluating 418/1075: BIOMD0000000418.xml
Evaluating 419/1075: BIOMD0000000419.xml
Evaluating 420/1075: BIOMD0000000420.xml
Evaluating 421/1075: BIOMD0000000421.xml
Evaluating 422/1075: BIOMD0000000422.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000422.txt
Evaluating 423/1075: BIOMD0000000423.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000423.txt
Evaluating 424/1075: BIOMD0000000424.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000424.txt
Evaluating 425/1075: BIOMD0000000425.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000425.txt
Evaluating 426/1075: BIOMD0000000426.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000426.txt
Evaluating 427/1075: BIOMD0000000427.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000427.txt
Evaluating 428/1075: BIOMD0000000428.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000428.txt
Evaluating 429/1075: BIOMD0000000429.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000429.txt
Evaluating 430/1075: BIOMD0000000430.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000430.txt
Evaluating 431/1075: BIOMD0000000431.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000431.txt
Evaluating 432/1075: BIOMD0000000432.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000432.txt
Evaluating 433/1075: BIOMD0000000433.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000433.txt
Evaluating 434/1075: BIOMD0000000434.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000434.txt
Evaluating 435/1075: BIOMD0000000435.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000435.txt
Evaluating 436/1075: BIOMD0000000436.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000436.txt
Evaluating 437/1075: BIOMD0000000437.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000437.txt
Evaluating 438/1075: BIOMD0000000438.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000438.txt
Evaluating 439/1075: BIOMD0000000439.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000439.txt
Evaluating 440/1075: BIOMD0000000440.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000440.txt
Evaluating 441/1075: BIOMD0000000441.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000441.txt
Evaluating 442/1075: BIOMD0000000442.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000442.txt
Evaluating 443/1075: BIOMD0000000443.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000443.txt
Evaluating 444/1075: BIOMD0000000444.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000444.txt
Evaluating 445/1075: BIOMD0000000445.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000445.txt
Evaluating 446/1075: BIOMD0000000446.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000446.txt
Evaluating 447/1075: BIOMD0000000447.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000447.txt
Evaluating 448/1075: BIOMD0000000448.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000448.txt
Evaluating 449/1075: BIOMD0000000449.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000449.txt
Evaluating 450/1075: BIOMD0000000450.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000450.txt
Evaluating 451/1075: BIOMD0000000451.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000451.txt
Evaluating 452/1075: BIOMD0000000452.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000452.txt
Evaluating 453/1075: BIOMD0000000453.xml

2025-12-06 23:32:03,025 - WARNING - Skipping BIOMD0000000454.xml - no results generated
2025-12-06 23:32:03,032 - WARNING - Skipping BIOMD0000000455.xml - no results generated
2025-12-06 23:32:03,040 - WARNING - Skipping BIOMD0000000456.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000453.txt
Evaluating 454/1075: BIOMD0000000454.xml
Evaluating 455/1075: BIOMD0000000455.xml
Evaluating 456/1075: BIOMD0000000456.xml
Evaluating 457/1075: BIOMD0000000457.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000457.txt
Evaluating 458/1075: BIOMD0000000458.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000458.txt
Evaluating 459/1075: BIOMD0000000459.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000459.txt
Evaluating 460/1075: BIOMD0000000460.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000460.txt
Evaluating 461/1075: BIOMD0000000461.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000461.txt
Evaluating 462/1075: BIOMD0000000462.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000462.txt
Evaluating 463/1075: BIOMD0000000463.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000463.txt
Evaluating 464/1075: BIOMD0000000464.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000464.txt
Evaluating 465/1075: BIOMD0000000465.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000465.txt
Evaluating 466/1075: BIOMD0000000466.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000466.txt
Evaluating 467/1075: BIOMD0000000467.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000467.txt
Evaluating 468/1075: BIOMD0000000468.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000468.txt
Evaluating 469/1075: BIOMD0000000469.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000469.txt
Evaluating 470/1075: BIOMD0000000470.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000470.txt
Evaluating 471/1075: BIOMD0000000471.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000471.txt
Evaluating 472/1075: BIOMD0000000472.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000472.txt
Evaluating 473/1075: BIOMD0000000473.xml

2025-12-07 00:03:18,633 - WARNING - Unknown entity type: acetaldehyde

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000473.txt
Evaluating 474/1075: BIOMD0000000474.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000474.txt
Evaluating 475/1075: BIOMD0000000475.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000475.txt
Evaluating 476/1075: BIOMD0000000476.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000476.txt
Evaluating 477/1075: BIOMD0000000477.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000477.txt
Evaluating 478/1075: BIOMD0000000478.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000478.txt
Evaluating 479/1075: BIOMD0000000479.xml

2025-12-07 00:05:43,105 - WARNING - Skipping BIOMD0000000480.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000479.txt
Evaluating 480/1075: BIOMD0000000480.xml
Evaluating 481/1075: BIOMD0000000481.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000481.txt
Evaluating 482/1075: BIOMD0000000482.xml

2025-12-07 00:05:55,656 - WARNING - Skipping BIOMD0000000483.xml - no results generated
2025-12-07 00:05:55,659 - WARNING - Skipping BIOMD0000000484.xml - no results generated
2025-12-07 00:05:55,663 - WARNING - Skipping BIOMD0000000485.xml - no results generated
2025-12-07 00:05:55,666 - WARNING - Skipping BIOMD0000000486.xml - no results generated
2025-12-07 00:05:55,672 - WARNING - Skipping BIOMD0000000487.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000482.txt
Evaluating 483/1075: BIOMD0000000483.xml
Evaluating 484/1075: BIOMD0000000484.xml
Evaluating 485/1075: BIOMD0000000485.xml
Evaluating 486/1075: BIOMD0000000486.xml
Evaluating 487/1075: BIOMD0000000487.xml
Evaluating 488/1075: BIOMD0000000488.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000488.txt
Evaluating 489/1075: BIOMD0000000489.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000489.txt
Evaluating 490/1075: BIOMD0000000490.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000490.txt
Evaluating 491/1075: BIOMD0000000491.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000491.txt
Evaluating 492/1075: BIOMD0000000492.xml

2025-12-07 00:07:18,937 - WARNING - Skipping BIOMD0000000493.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000492.txt
Evaluating 493/1075: BIOMD0000000493.xml
Evaluating 494/1075: BIOMD0000000494.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000494.txt
Evaluating 495/1075: BIOMD0000000495.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000495.txt
Evaluating 496/1075: BIOMD0000000496.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000496.txt
Evaluating 497/1075: BIOMD0000000497.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000497.txt
Evaluating 498/1075: BIOMD0000000498.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000498.txt
Evaluating 499/1075: BIOMD0000000499.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000499.txt
Evaluating 500/1075: BIOMD0000000500.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000500.txt
Evaluating 501/1075: BIOMD0000000501.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000501.txt
Evaluating 502/1075: BIOMD0000000502.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000502.txt
Evaluating 503/1075: BIOMD0000000503.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000503.txt
Evaluating 504/1075: BIOMD0000000504.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000504.txt
Evaluating 505/1075: BIOMD0000000505.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000505.txt
Evaluating 506/1075: BIOMD0000000506.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000506.txt
Evaluating 507/1075: BIOMD0000000507.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000507.txt
Evaluating 508/1075: BIOMD0000000508.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000508.txt
Evaluating 509/1075: BIOMD0000000509.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000509.txt
Evaluating 510/1075: BIOMD0000000510.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000510.txt
Evaluating 511/1075: BIOMD0000000511.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000511.txt
Evaluating 512/1075: BIOMD0000000512.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000512.txt
Evaluating 513/1075: BIOMD0000000513.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000513.txt
Evaluating 514/1075: BIOMD0000000514.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000514.txt
Evaluating 515/1075: BIOMD0000000515.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000515.txt
Evaluating 516/1075: BIOMD0000000516.xml

2025-12-07 00:15:57,921 - WARNING - Skipping BIOMD0000000517.xml - no results generated
2025-12-07 00:15:57,931 - WARNING - Skipping BIOMD0000000518.xml - no results generated
2025-12-07 00:15:57,939 - WARNING - Skipping BIOMD0000000519.xml - no results generated
2025-12-07 00:15:57,946 - WARNING - Skipping BIOMD0000000520.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000516.txt
Evaluating 517/1075: BIOMD0000000517.xml
Evaluating 518/1075: BIOMD0000000518.xml
Evaluating 519/1075: BIOMD0000000519.xml
Evaluating 520/1075: BIOMD0000000520.xml
Evaluating 521/1075: BIOMD0000000521.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000521.txt
Evaluating 522/1075: BIOMD0000000522.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000522.txt
Evaluating 523/1075: BIOMD0000000523.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000523.txt
Evaluating 524/1075: BIOMD0000000524.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000524.txt
Evaluating 525/1075: BIOMD0000000525.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000525.txt
Evaluating 526/1075: BIOMD0000000526.xml

2025-12-07 00:16:31,255 - WARNING - Skipping BIOMD0000000527.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000526.txt
Evaluating 527/1075: BIOMD0000000527.xml
Evaluating 528/1075: BIOMD0000000528.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000528.txt
Evaluating 529/1075: BIOMD0000000529.xml

2025-12-07 00:16:36,376 - WARNING - Skipping BIOMD0000000530.xml - no results generated
2025-12-07 00:16:36,380 - WARNING - Skipping BIOMD0000000531.xml - no results generated
2025-12-07 00:16:36,387 - WARNING - Skipping BIOMD0000000532.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000529.txt
Evaluating 530/1075: BIOMD0000000530.xml
Evaluating 531/1075: BIOMD0000000531.xml
Evaluating 532/1075: BIOMD0000000532.xml
Evaluating 533/1075: BIOMD0000000533.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000533.txt
Evaluating 534/1075: BIOMD0000000534.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000534.txt
Evaluating 535/1075: BIOMD0000000535.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000535.txt
Evaluating 536/1075: BIOMD0000000536.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000536.txt
Evaluating 537/1075: BIOMD0000000537.xml

2025-12-07 00:18:19,694 - WARNING - Skipping BIOMD0000000538.xml - no results generated
2025-12-07 00:18:19,705 - WARNING - Skipping BIOMD0000000539.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000537.txt
Evaluating 538/1075: BIOMD0000000538.xml
Evaluating 539/1075: BIOMD0000000539.xml
Evaluating 540/1075: BIOMD0000000540.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000540.txt
Evaluating 541/1075: BIOMD0000000541.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000541.txt
Evaluating 542/1075: BIOMD0000000542.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000542.txt
Evaluating 543/1075: BIOMD0000000543.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000543.txt
Evaluating 544/1075: BIOMD0000000544.xml

2025-12-07 00:20:57,136 - WARNING - Unknown entity type: mrna

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000544.txt
Evaluating 545/1075: BIOMD0000000545.xml

2025-12-07 00:21:05,244 - WARNING - Skipping BIOMD0000000546.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000545.txt
Evaluating 546/1075: BIOMD0000000546.xml
Evaluating 547/1075: BIOMD0000000547.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000547.txt
Evaluating 548/1075: BIOMD0000000548.xml

2025-12-07 00:21:14,466 - WARNING - Skipping BIOMD0000000549.xml - no results generated
2025-12-07 00:21:14,472 - WARNING - Skipping BIOMD0000000550.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000548.txt
Evaluating 549/1075: BIOMD0000000549.xml
Evaluating 550/1075: BIOMD0000000550.xml
Evaluating 551/1075: BIOMD0000000551.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000551.txt
Evaluating 552/1075: BIOMD0000000552.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000552.txt
Evaluating 553/1075: BIOMD0000000553.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000553.txt
Evaluating 554/1075: BIOMD0000000554.xml

2025-12-07 00:21:31,670 - WARNING - Skipping BIOMD0000000555.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000554.txt
Evaluating 555/1075: BIOMD0000000555.xml
Evaluating 556/1075: BIOMD0000000556.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000556.txt
Evaluating 557/1075: BIOMD0000000557.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000557.txt
Evaluating 558/1075: BIOMD0000000558.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000558.txt
Evaluating 559/1075: BIOMD0000000559.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000559.txt
Evaluating 560/1075: BIOMD0000000560.xml

2025-12-07 00:22:51,803 - WARNING - Skipping BIOMD0000000561.xml - no results generated
2025-12-07 00:22:51,817 - WARNING - Skipping BIOMD0000000562.xml - no results generated
2025-12-07 00:22:51,831 - WARNING - Skipping BIOMD0000000563.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000560.txt
Evaluating 561/1075: BIOMD0000000561.xml
Evaluating 562/1075: BIOMD0000000562.xml
Evaluating 563/1075: BIOMD0000000563.xml
Evaluating 564/1075: BIOMD0000000564.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000564.txt
Evaluating 565/1075: BIOMD0000000565.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000565.txt
Evaluating 566/1075: BIOMD0000000566.xml

2025-12-07 00:23:04,965 - WARNING - Skipping BIOMD0000000567.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000566.txt
Evaluating 567/1075: BIOMD0000000567.xml
Evaluating 568/1075: BIOMD0000000568.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000568.txt
Evaluating 569/1075: BIOMD0000000569.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000569.txt
Evaluating 570/1075: BIOMD0000000570.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000570.txt
Evaluating 571/1075: BIOMD0000000571.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000571.txt
Evaluating 572/1075: BIOMD0000000572.xml

2025-12-07 00:24:01,867 - WARNING - Skipping BIOMD0000000573.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000572.txt
Evaluating 573/1075: BIOMD0000000573.xml
Evaluating 574/1075: BIOMD0000000574.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000574.txt
Evaluating 575/1075: BIOMD0000000575.xml

2025-12-07 00:24:52,385 - WARNING - Species 's28': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:24:52,386 - WARNING - Species 'Ligand2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:24:52,408 - WARNING - Species 's28': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:24:52,409 - WARNING - Species 'Ligand2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000575.txt
Evaluating 576/1075: BIOMD0000000576.xml

2025-12-07 00:25:04,834 - WARNING - Skipping BIOMD0000000577.xml - no results generated
2025-12-07 00:25:04,873 - WARNING - Skipping BIOMD0000000578.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000576.txt
Evaluating 577/1075: BIOMD0000000577.xml
Evaluating 578/1075: BIOMD0000000578.xml
Evaluating 579/1075: BIOMD0000000579.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000579.txt
Evaluating 580/1075: BIOMD0000000580.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000580.txt
Evaluating 581/1075: BIOMD0000000581.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000581.txt
Evaluating 582/1075: BIOMD0000000582.xml

2025-12-07 00:27:08,647 - WARNING - Skipping BIOMD0000000583.xml - no results generated
2025-12-07 00:27:08,657 - WARNING - Skipping BIOMD0000000584.xml - no results generated
2025-12-07 00:27:08,667 - WARNING - Skipping BIOMD0000000585.xml - no results generated
2025-12-07 00:27:08,688 - WARNING - Skipping BIOMD0000000586.xml - no results generated
2025-12-07 00:27:08,707 - WARNING - Skipping BIOMD0000000587.xml - no results generated
2025-12-07 00:27:08,780 - WARNING - Skipping BIOMD0000000588.xml - no results generated
2025-12-07 00:27:08,792 - WARNING - Species 'GSH': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:27:08,793 - WARNING - Species 'H2O2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:27:08,804 - WARNING - Species 'GSH': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:27:08,805 - WARNING - Species 'H2O2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000582.txt
Evaluating 583/1075: BIOMD0000000583.xml
Evaluating 584/1075: BIOMD0000000584.xml
Evaluating 585/1075: BIOMD0000000585.xml
Evaluating 586/1075: BIOMD0000000586.xml
Evaluating 587/1075: BIOMD0000000587.xml
Evaluating 588/1075: BIOMD0000000588.xml
Evaluating 589/1075: BIOMD0000000589.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000589.txt
Evaluating 590/1075: BIOMD0000000590.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000590.txt
Evaluating 591/1075: BIOMD0000000591.xml

2025-12-07 00:27:20,763 - WARNING - Skipping BIOMD0000000592.xml - no results generated
2025-12-07 00:27:20,775 - WARNING - Skipping BIOMD0000000593.xml - no results generated
2025-12-07 00:27:20,807 - WARNING - Species 'Grb2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:27:20,837 - WARNING - Species 'Grb2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000591.txt
Evaluating 592/1075: BIOMD0000000592.xml
Evaluating 593/1075: BIOMD0000000593.xml
Evaluating 594/1075: BIOMD0000000594.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000594.txt
Evaluating 595/1075: BIOMD0000000595.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000595.txt
Evaluating 596/1075: BIOMD0000000596.xml

2025-12-07 00:27:34,738 - WARNING - Skipping BIOMD0000000597.xml - no results generated
2025-12-07 00:27:34,780 - WARNING - Skipping BIOMD0000000598.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000596.txt
Evaluating 597/1075: BIOMD0000000597.xml
Evaluating 598/1075: BIOMD0000000598.xml
Evaluating 599/1075: BIOMD0000000599.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000599.txt
Evaluating 600/1075: BIOMD0000000600.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000600.txt
Evaluating 601/1075: BIOMD0000000601.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000601.txt
Evaluating 602/1075: BIOMD0000000602.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000602.txt
Evaluating 603/1075: BIOMD0000000603.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000603.txt
Evaluating 604/1075: BIOMD0000000604.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000604.txt
Evaluating 605/1075: BIOMD0000000605.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000605.txt
Evaluating 606/1075: BIOMD0000000606.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000606.txt
Evaluating 607/1075: BIOMD0000000607.xml

2025-12-07 00:28:59,370 - WARNING - Skipping BIOMD0000000608.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000607.txt
Evaluating 608/1075: BIOMD0000000608.xml
Evaluating 609/1075: BIOMD0000000609.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000609.txt
Evaluating 610/1075: BIOMD0000000610.xml

2025-12-07 00:29:08,926 - WARNING - Skipping BIOMD0000000611.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000610.txt
Evaluating 611/1075: BIOMD0000000611.xml
Evaluating 612/1075: BIOMD0000000612.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000612.txt
Evaluating 613/1075: BIOMD0000000613.xml

2025-12-07 00:29:27,659 - WARNING - Species 'f': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:29:27,661 - WARNING - Species 'f': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000613.txt
Evaluating 614/1075: BIOMD0000000614.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000614.txt
Evaluating 615/1075: BIOMD0000000615.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000615.txt
Evaluating 616/1075: BIOMD0000000616.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000616.txt
Evaluating 617/1075: BIOMD0000000617.xml

2025-12-07 00:29:34,092 - WARNING - Skipping BIOMD0000000618.xml - no results generated
2025-12-07 00:29:34,107 - WARNING - Skipping BIOMD0000000619.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000617.txt
Evaluating 618/1075: BIOMD0000000618.xml
Evaluating 619/1075: BIOMD0000000619.xml
Evaluating 620/1075: BIOMD0000000620.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000620.txt
Evaluating 621/1075: BIOMD0000000621.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000621.txt
Evaluating 622/1075: BIOMD0000000622.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000622.txt
Evaluating 623/1075: BIOMD0000000623.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000623.txt
Evaluating 624/1075: BIOMD0000000624.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000624.txt
Evaluating 625/1075: BIOMD0000000625.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000625.txt
Evaluating 626/1075: BIOMD0000000626.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000626.txt
Evaluating 627/1075: BIOMD0000000627.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000627.txt
Evaluating 628/1075: BIOMD0000000628.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000628.txt
Evaluating 629/1075: BIOMD0000000629.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000629.txt
Evaluating 630/1075: BIOMD0000000630.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000630.txt
Evaluating 631/1075: BIOMD0000000631.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000631.txt
Evaluating 632/1075: BIOMD0000000632.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000632.txt
Evaluating 633/1075: BIOMD0000000633.xml

2025-12-07 00:31:36,487 - WARNING - Species 'Mdm2_P_Ub2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:31:36,488 - WARNING - Species 'Mdm2_P_Ub3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:31:36,518 - WARNING - Species 'Mdm2_P_Ub2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:31:36,519 - WARNING - Species 'Mdm2_P_Ub3': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000633.txt
Evaluating 634/1075: BIOMD0000000634.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000634.txt
Evaluating 635/1075: BIOMD0000000635.xml

2025-12-07 00:33:10,955 - WARNING - Species 'mw9710c658_a2a1_4f49_b494_af109853f251': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:33:10,997 - WARNING - Species 'mw9710c658_a2a1_4f49_b494_af109853f251': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000635.txt
Evaluating 636/1075: BIOMD0000000636.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000636.txt
Evaluating 637/1075: BIOMD0000000637.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000637.txt
Evaluating 638/1075: BIOMD0000000638.xml

2025-12-07 00:34:39,711 - WARNING - Skipping BIOMD0000000639.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000638.txt
Evaluating 639/1075: BIOMD0000000639.xml
Evaluating 640/1075: BIOMD0000000640.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000640.txt
Evaluating 641/1075: BIOMD0000000641.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000641.txt
Evaluating 642/1075: BIOMD0000000642.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000642.txt
Evaluating 643/1075: BIOMD0000000643.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000643.txt
Evaluating 644/1075: BIOMD0000000644.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000644.txt
Evaluating 645/1075: BIOMD0000000645.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000645.txt
Evaluating 646/1075: BIOMD0000000646.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000646.txt
Evaluating 647/1075: BIOMD0000000647.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000647.txt
Evaluating 648/1075: BIOMD0000000648.xml

2025-12-07 00:35:19,351 - WARNING - Skipping BIOMD0000000650.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000648.txt
Evaluating 649/1075: BIOMD0000000650.xml
Evaluating 650/1075: BIOMD0000000651.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000651.txt
Evaluating 651/1075: BIOMD0000000652.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000652.txt
Evaluating 652/1075: BIOMD0000000653.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000653.txt
Evaluating 653/1075: BIOMD0000000654.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000654.txt
Evaluating 654/1075: BIOMD0000000655.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000655.txt
Evaluating 655/1075: BIOMD0000000656.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000656.txt
Evaluating 656/1075: BIOMD0000000657.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000657.txt
Evaluating 657/1075: BIOMD0000000658.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000658.txt
Evaluating 658/1075: BIOMD0000000659.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000659.txt
Evaluating 659/1075: BIOMD0000000660.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000660.txt
Evaluating 660/1075: BIOMD0000000661.xml

2025-12-07 00:37:18,005 - WARNING - Skipping BIOMD0000000662.xml - no results generated
2025-12-07 00:37:18,017 - WARNING - Skipping BIOMD0000000663.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000661.txt
Evaluating 661/1075: BIOMD0000000662.xml
Evaluating 662/1075: BIOMD0000000663.xml
Evaluating 663/1075: BIOMD0000000664.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000664.txt
Evaluating 664/1075: BIOMD0000000665.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000665.txt
Evaluating 665/1075: BIOMD0000000666.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000666.txt
Evaluating 666/1075: BIOMD0000000667.xml

2025-12-07 00:38:30,964 - WARNING - Species 'Inh_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,964 - WARNING - Species 'Inh_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,965 - WARNING - Species 'Sti_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,965 - WARNING - Species 'Sti_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,976 - WARNING - Species 'Inh_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,976 - WARNING - Species 'Inh_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,977 - WARNING - Species 'Sti_g': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,977 - WARNING - Species 'Sti_b': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:38:30,979 - WARNING - Skipping BIOMD0000000668.xml - no results generated
2025-12-07 00:38:31,013 - WARNING - Skipping BIOMD0000000669.xml - no results generated
2025-12-07 00:38:31,019 - WARNING - Skipping BIOMD0000000670.xml - no results generated
2025-12-07 00:38:31,026 - WARNING - Skipping BIOMD0000000671.xml - no results generated
2025-12-07 00:38:31,036 - WARNING - Skipping BIOMD0000000672.xml - no results generated
2025-12-07 00:38:31,051 - WARNING - Skipping BIOMD0000000673.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000667.txt
Evaluating 667/1075: BIOMD0000000668.xml
Evaluating 668/1075: BIOMD0000000669.xml
Evaluating 669/1075: BIOMD0000000670.xml
Evaluating 670/1075: BIOMD0000000671.xml
Evaluating 671/1075: BIOMD0000000672.xml
Evaluating 672/1075: BIOMD0000000673.xml
Evaluating 673/1075: BIOMD0000000674.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000674.txt
Evaluating 674/1075: BIOMD0000000675.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000675.txt
Evaluating 675/1075: BIOMD0000000676.xml

2025-12-07 00:39:01,320 - WARNING - Skipping BIOMD0000000677.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000676.txt
Evaluating 676/1075: BIOMD0000000677.xml
Evaluating 677/1075: BIOMD0000000678.xml

2025-12-07 00:39:03,609 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:39:03,616 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:39:03,617 - WARNING - Skipping BIOMD0000000679.xml - no results generated
2025-12-07 00:39:03,623 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:39:03,627 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:39:03,628 - WARNING - Skipping BIOMD0000000680.xml - no results generated
2025-12-07 00:39:03,634 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:39:03,639 - WARNING - Species 'K_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:39:03,640 - WARNING - Skipping BIOMD0000000681.xml - no results generated
2025-12-07 00:39:03,656 - WARNING - Skipping BIOMD0000000682.xml - no results generated
2025-12-07 00:39:03,671 - WARNING - Skipping BIOMD0000000683.xml - no results generated
2025-12-07 00:39:03,686 - WARNING - Skipping BIOMD0000000684.xml - no results generated
2025-12-07 00:39:03,696 - WARNING - Skipping BIOMD0000000685.xml - no results generated
2025-12-07 00:39:03,706 - WARNING - Skipping BIOMD0000000686.xml - no results generated
2025-12-07 00:39:03,731 - WARNING - Skipping BIOMD0000000687.xml - no results generated
2025-12-07 00:39:03,759 - WARNING - Skipping BIOMD0000000688.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000678.txt
Evaluating 678/1075: BIOMD0000000679.xml
Evaluating 679/1075: BIOMD0000000680.xml
Evaluating 680/1075: BIOMD0000000681.xml
Evaluating 681/1075: BIOMD0000000682.xml
Evaluating 682/1075: BIOMD0000000683.xml
Evaluating 683/1075: BIOMD0000000684.xml
Evaluating 684/1075: BIOMD0000000685.xml
Evaluating 685/1075: BIOMD0000000686.xml
Evaluating 686/1075: BIOMD0000000687.xml
Evaluating 687/1075: BIOMD0000000688.xml
Evaluating 688/1075: BIOMD0000000689.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000689.txt
Evaluating 689/1075: BIOMD0000000690.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000690.txt
Evaluating 690/1075: BIOMD0000000691.xml

2025-12-07 00:39:18,282 - WARNING - Skipping BIOMD0000000692.xml - no results generated
2025-12-07 00:39:18,300 - WARNING - Skipping BIOMD0000000693.xml - no results generated
2025-12-07 00:39:18,354 - WARNING - Skipping BIOMD0000000695.xml - no results generated
2025-12-07 00:39:18,386 - WARNING - Skipping BIOMD0000000696.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000691.txt
Evaluating 691/1075: BIOMD0000000692.xml
Evaluating 692/1075: BIOMD0000000693.xml
Evaluating 693/1075: BIOMD0000000695.xml
Evaluating 694/1075: BIOMD0000000696.xml
Evaluating 695/1075: BIOMD0000000697.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000697.txt
Evaluating 696/1075: BIOMD0000000698.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000698.txt
Evaluating 697/1075: BIOMD0000000699.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000699.txt
Evaluating 698/1075: BIOMD0000000700.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000700.txt
Evaluating 699/1075: BIOMD0000000701.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000701.txt
Evaluating 700/1075: BIOMD0000000702.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000702.txt
Evaluating 701/1075: BIOMD0000000703.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000703.txt
Evaluating 702/1075: BIOMD0000000704.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000704.txt
Evaluating 703/1075: BIOMD0000000705.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000705.txt
Evaluating 704/1075: BIOMD0000000706.xml

2025-12-07 00:41:31,132 - WARNING - Skipping BIOMD0000000707.xml - no results generated
2025-12-07 00:41:31,146 - WARNING - Skipping BIOMD0000000708.xml - no results generated
2025-12-07 00:41:31,158 - WARNING - Skipping BIOMD0000000709.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000706.txt
Evaluating 705/1075: BIOMD0000000707.xml
Evaluating 706/1075: BIOMD0000000708.xml
Evaluating 707/1075: BIOMD0000000709.xml
Evaluating 708/1075: BIOMD0000000710.xml

2025-12-07 00:41:32,559 - WARNING - Skipping BIOMD0000000711.xml - no results generated
2025-12-07 00:41:32,568 - WARNING - Skipping BIOMD0000000712.xml - no results generated
2025-12-07 00:41:32,583 - WARNING - Skipping BIOMD0000000713.xml - no results generated
2025-12-07 00:41:32,596 - WARNING - Skipping BIOMD0000000714.xml - no results generated
2025-12-07 00:41:32,606 - WARNING - Skipping BIOMD0000000715.xml - no results generated
2025-12-07 00:41:32,622 - WARNING - Skipping BIOMD0000000716.xml - no results generated
2025-12-07 00:41:32,637 - WARNING - Skipping BIOMD0000000717.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000710.txt
Evaluating 709/1075: BIOMD0000000711.xml
Evaluating 710/1075: BIOMD0000000712.xml
Evaluating 711/1075: BIOMD0000000713.xml
Evaluating 712/1075: BIOMD0000000714.xml
Evaluating 713/1075: BIOMD0000000715.xml
Evaluating 714/1075: BIOMD0000000716.xml
Evaluating 715/1075: BIOMD0000000717.xml
Evaluating 716/1075: BIOMD0000000718.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000718.txt
Evaluating 717/1075: BIOMD0000000719.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000719.txt
Evaluating 718/1075: BIOMD0000000720.xml

2025-12-07 00:41:44,943 - WARNING - Skipping BIOMD0000000721.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000720.txt
Evaluating 719/1075: BIOMD0000000721.xml
Evaluating 720/1075: BIOMD0000000722.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000722.txt
Evaluating 721/1075: BIOMD0000000723.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000723.txt
Evaluating 722/1075: BIOMD0000000724.xml

2025-12-07 00:42:13,341 - WARNING - Skipping BIOMD0000000725.xml - no results generated
2025-12-07 00:42:13,362 - WARNING - Skipping BIOMD0000000726.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000724.txt
Evaluating 723/1075: BIOMD0000000725.xml
Evaluating 724/1075: BIOMD0000000726.xml
Evaluating 725/1075: BIOMD0000000727.xml

2025-12-07 00:42:19,597 - WARNING - Skipping BIOMD0000000728.xml - no results generated
2025-12-07 00:42:19,610 - WARNING - Skipping BIOMD0000000729.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000727.txt
Evaluating 726/1075: BIOMD0000000728.xml
Evaluating 727/1075: BIOMD0000000729.xml
Evaluating 728/1075: BIOMD0000000730.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000730.txt
Evaluating 729/1075: BIOMD0000000731.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000731.txt
Evaluating 730/1075: BIOMD0000000732.xml

2025-12-07 00:42:34,263 - WARNING - Skipping BIOMD0000000733.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000732.txt
Evaluating 731/1075: BIOMD0000000733.xml
Evaluating 732/1075: BIOMD0000000734.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000734.txt
Evaluating 733/1075: BIOMD0000000735.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000735.txt
Evaluating 734/1075: BIOMD0000000736.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000736.txt
Evaluating 735/1075: BIOMD0000000737.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000737.txt
Evaluating 736/1075: BIOMD0000000738.xml

2025-12-07 00:43:04,658 - WARNING - Species 'Va_i_306': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,658 - WARNING - Species 'Va_1_306_Va_LC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,659 - WARNING - Species 'Va_307_506': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,659 - WARNING - Species 'Va_507_679_709': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,670 - WARNING - Species 'Va_i_306': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,670 - WARNING - Species 'Va_1_306_Va_LC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,671 - WARNING - Species 'Va_307_506': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,671 - WARNING - Species 'Va_507_679_709': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,672 - WARNING - Skipping BIOMD0000000739.xml - no results generated
2025-12-07 00:43:04,684 - WARNING - Species 'Xa_TFPI': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,685 - WARNING - Species 'Xa_VIIa_TF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,699 - WARNING - Species 'Xa_TFPI': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,699 - WARNING - Species 'Xa_VIIa_TF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:04,700 - WARNING - Skipping BIOMD0000000740.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000738.txt
Evaluating 737/1075: BIOMD0000000739.xml
Evaluating 738/1075: BIOMD0000000740.xml
Evaluating 739/1075: BIOMD0000000741.xml

2025-12-07 00:43:06,296 - WARNING - Skipping BIOMD0000000742.xml - no results generated
2025-12-07 00:43:06,322 - WARNING - Skipping BIOMD0000000743.xml - no results generated
2025-12-07 00:43:06,348 - WARNING - Skipping BIOMD0000000744.xml - no results generated
2025-12-07 00:43:06,369 - WARNING - Skipping BIOMD0000000745.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000741.txt
Evaluating 740/1075: BIOMD0000000742.xml
Evaluating 741/1075: BIOMD0000000743.xml
Evaluating 742/1075: BIOMD0000000744.xml
Evaluating 743/1075: BIOMD0000000745.xml
Evaluating 744/1075: BIOMD0000000746.xml

2025-12-07 00:43:07,453 - WARNING - Skipping BIOMD0000000747.xml - no results generated
2025-12-07 00:43:07,468 - WARNING - Skipping BIOMD0000000748.xml - no results generated
2025-12-07 00:43:07,482 - WARNING - Skipping BIOMD0000000749.xml - no results generated
2025-12-07 00:43:07,501 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:43:07,520 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000746.txt
Evaluating 745/1075: BIOMD0000000747.xml
Evaluating 746/1075: BIOMD0000000748.xml
Evaluating 747/1075: BIOMD0000000749.xml
Evaluating 748/1075: BIOMD0000000750.xml

2025-12-07 00:43:09,445 - WARNING - Skipping BIOMD0000000751.xml - no results generated
2025-12-07 00:43:09,458 - WARNING - Skipping BIOMD0000000752.xml - no results generated
2025-12-07 00:43:09,471 - WARNING - Skipping BIOMD0000000753.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000750.txt
Evaluating 749/1075: BIOMD0000000751.xml
Evaluating 750/1075: BIOMD0000000752.xml
Evaluating 751/1075: BIOMD0000000753.xml
Evaluating 752/1075: BIOMD0000000754.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000754.txt
Evaluating 753/1075: BIOMD0000000755.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000755.txt
Evaluating 754/1075: BIOMD0000000756.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000756.txt
Evaluating 755/1075: BIOMD0000000757.xml

2025-12-07 00:43:17,258 - WARNING - Skipping BIOMD0000000758.xml - no results generated
2025-12-07 00:43:17,287 - WARNING - Skipping BIOMD0000000759.xml - no results generated
2025-12-07 00:43:17,297 - WARNING - Skipping BIOMD0000000760.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000757.txt
Evaluating 756/1075: BIOMD0000000758.xml
Evaluating 757/1075: BIOMD0000000759.xml
Evaluating 758/1075: BIOMD0000000760.xml
Evaluating 759/1075: BIOMD0000000761.xml

2025-12-07 00:43:18,501 - WARNING - Skipping BIOMD0000000762.xml - no results generated
2025-12-07 00:43:18,512 - WARNING - Skipping BIOMD0000000763.xml - no results generated
2025-12-07 00:43:18,529 - WARNING - Skipping BIOMD0000000764.xml - no results generated
2025-12-07 00:43:18,544 - WARNING - Skipping BIOMD0000000765.xml - no results generated
2025-12-07 00:43:18,563 - WARNING - Skipping BIOMD0000000766.xml - no results generated
2025-12-07 00:43:18,574 - WARNING - Skipping BIOMD0000000767.xml - no results generated
2025-12-07 00:43:18,597 - WARNING - Skipping BIOMD0000000768.xml - no results generated
2025-12-07 00:43:18,626 - WARNING - Skipping BIOMD0000000769.xml - no results generated
2025-12-07 00:43:18,645 - WARNING - Skipping BIOMD0000000770.xml - no results generated
2025-12-07 00:43:18,654 - WARNING - Skipping BIOMD0000000771.xml - no results generated
2025-12-07 00:43:18,664 - WARNING - Skipping BIOMD0000000772.xml - no results generated
2025-12-07 00:43:18,680 - WARNING - Skipping BIOMD0000000773.xml - no results generated
2025-12-07 00:43:18,691 - WARNING - Skipping BIOMD0000000774.xml - no results generated
2025-12-07 00:43:18,708 - WARNING - Skipping BIOMD0000000775.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000761.txt
Evaluating 760/1075: BIOMD0000000762.xml
Evaluating 761/1075: BIOMD0000000763.xml
Evaluating 762/1075: BIOMD0000000764.xml
Evaluating 763/1075: BIOMD0000000765.xml
Evaluating 764/1075: BIOMD0000000766.xml
Evaluating 765/1075: BIOMD0000000767.xml
Evaluating 766/1075: BIOMD0000000768.xml
Evaluating 767/1075: BIOMD0000000769.xml
Evaluating 768/1075: BIOMD0000000770.xml
Evaluating 769/1075: BIOMD0000000771.xml
Evaluating 770/1075: BIOMD0000000772.xml
Evaluating 771/1075: BIOMD0000000773.xml
Evaluating 772/1075: BIOMD0000000774.xml
Evaluating 773/1075: BIOMD0000000775.xml

2025-12-07 00:43:18,717 - WARNING - Skipping BIOMD0000000776.xml - no results generated
2025-12-07 00:43:18,727 - WARNING - Skipping BIOMD0000000777.xml - no results generated
2025-12-07 00:43:18,742 - WARNING - Skipping BIOMD0000000778.xml - no results generated

Evaluating 774/1075: BIOMD0000000776.xml
Evaluating 775/1075: BIOMD0000000777.xml
Evaluating 776/1075: BIOMD0000000778.xml
Evaluating 777/1075: BIOMD0000000779.xml

2025-12-07 00:43:20,551 - WARNING - Skipping BIOMD0000000780.xml - no results generated
2025-12-07 00:43:20,566 - WARNING - Skipping BIOMD0000000781.xml - no results generated
2025-12-07 00:43:20,575 - WARNING - Skipping BIOMD0000000782.xml - no results generated
2025-12-07 00:43:20,585 - WARNING - Skipping BIOMD0000000783.xml - no results generated
2025-12-07 00:43:20,597 - WARNING - Skipping BIOMD0000000784.xml - no results generated
2025-12-07 00:43:20,604 - WARNING - Skipping BIOMD0000000785.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000779.txt
Evaluating 778/1075: BIOMD0000000780.xml
Evaluating 779/1075: BIOMD0000000781.xml
Evaluating 780/1075: BIOMD0000000782.xml
Evaluating 781/1075: BIOMD0000000783.xml
Evaluating 782/1075: BIOMD0000000784.xml
Evaluating 783/1075: BIOMD0000000785.xml
Evaluating 784/1075: BIOMD0000000786.xml

2025-12-07 00:43:27,943 - WARNING - Skipping BIOMD0000000787.xml - no results generated
2025-12-07 00:43:27,967 - WARNING - Skipping BIOMD0000000788.xml - no results generated
2025-12-07 00:43:27,981 - WARNING - Skipping BIOMD0000000789.xml - no results generated
2025-12-07 00:43:28,000 - WARNING - Skipping BIOMD0000000790.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000786.txt
Evaluating 785/1075: BIOMD0000000787.xml
Evaluating 786/1075: BIOMD0000000788.xml
Evaluating 787/1075: BIOMD0000000789.xml
Evaluating 788/1075: BIOMD0000000790.xml
Evaluating 789/1075: BIOMD0000000791.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000791.txt
Evaluating 790/1075: BIOMD0000000792.xml

2025-12-07 00:43:30,277 - WARNING - Skipping BIOMD0000000793.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000792.txt
Evaluating 791/1075: BIOMD0000000793.xml
Evaluating 792/1075: BIOMD0000000794.xml

2025-12-07 00:43:39,967 - WARNING - Skipping BIOMD0000000795.xml - no results generated
2025-12-07 00:43:39,991 - WARNING - Skipping BIOMD0000000796.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000794.txt
Evaluating 793/1075: BIOMD0000000795.xml
Evaluating 794/1075: BIOMD0000000796.xml
Evaluating 795/1075: BIOMD0000000797.xml

2025-12-07 00:43:41,352 - WARNING - Skipping BIOMD0000000798.xml - no results generated
2025-12-07 00:43:41,360 - WARNING - Skipping BIOMD0000000799.xml - no results generated
2025-12-07 00:43:41,372 - WARNING - Skipping BIOMD0000000800.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000797.txt
Evaluating 796/1075: BIOMD0000000798.xml
Evaluating 797/1075: BIOMD0000000799.xml
Evaluating 798/1075: BIOMD0000000800.xml
Evaluating 799/1075: BIOMD0000000801.xml

2025-12-07 00:43:42,608 - WARNING - Skipping BIOMD0000000802.xml - no results generated
2025-12-07 00:43:42,619 - WARNING - Skipping BIOMD0000000803.xml - no results generated
2025-12-07 00:43:42,636 - WARNING - Skipping BIOMD0000000804.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000801.txt
Evaluating 800/1075: BIOMD0000000802.xml
Evaluating 801/1075: BIOMD0000000803.xml
Evaluating 802/1075: BIOMD0000000804.xml
Evaluating 803/1075: BIOMD0000000805.xml

2025-12-07 00:43:44,158 - WARNING - Skipping BIOMD0000000806.xml - no results generated
2025-12-07 00:43:44,182 - WARNING - Skipping BIOMD0000000807.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000805.txt
Evaluating 804/1075: BIOMD0000000806.xml
Evaluating 805/1075: BIOMD0000000807.xml
Evaluating 806/1075: BIOMD0000000808.xml

2025-12-07 00:43:45,734 - WARNING - Skipping BIOMD0000000809.xml - no results generated
2025-12-07 00:43:45,795 - WARNING - Skipping BIOMD0000000810.xml - no results generated
2025-12-07 00:43:45,824 - WARNING - Skipping BIOMD0000000811.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000808.txt
Evaluating 807/1075: BIOMD0000000809.xml
Evaluating 808/1075: BIOMD0000000810.xml
Evaluating 809/1075: BIOMD0000000811.xml
Evaluating 810/1075: BIOMD0000000812.xml

2025-12-07 00:43:46,921 - WARNING - Skipping BIOMD0000000813.xml - no results generated
2025-12-07 00:43:46,939 - WARNING - Skipping BIOMD0000000814.xml - no results generated
2025-12-07 00:43:46,949 - WARNING - Skipping BIOMD0000000815.xml - no results generated
2025-12-07 00:43:46,976 - WARNING - Skipping BIOMD0000000816.xml - no results generated
2025-12-07 00:43:46,999 - WARNING - Skipping BIOMD0000000817.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000812.txt
Evaluating 811/1075: BIOMD0000000813.xml
Evaluating 812/1075: BIOMD0000000814.xml
Evaluating 813/1075: BIOMD0000000815.xml
Evaluating 814/1075: BIOMD0000000816.xml
Evaluating 815/1075: BIOMD0000000817.xml
Evaluating 816/1075: BIOMD0000000818.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000818.txt
Evaluating 817/1075: BIOMD0000000819.xml

2025-12-07 00:43:57,620 - WARNING - Skipping BIOMD0000000820.xml - no results generated
2025-12-07 00:43:57,631 - WARNING - Skipping BIOMD0000000821.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000819.txt
Evaluating 818/1075: BIOMD0000000820.xml
Evaluating 819/1075: BIOMD0000000821.xml
Evaluating 820/1075: BIOMD0000000822.xml

2025-12-07 00:44:00,792 - WARNING - Skipping BIOMD0000000823.xml - no results generated
2025-12-07 00:44:00,798 - WARNING - Skipping BIOMD0000000824.xml - no results generated
2025-12-07 00:44:00,807 - WARNING - Skipping BIOMD0000000825.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000822.txt
Evaluating 821/1075: BIOMD0000000823.xml
Evaluating 822/1075: BIOMD0000000824.xml
Evaluating 823/1075: BIOMD0000000825.xml
Evaluating 824/1075: BIOMD0000000826.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000826.txt
Evaluating 825/1075: BIOMD0000000827.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000827.txt
Evaluating 826/1075: BIOMD0000000828.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000828.txt
Evaluating 827/1075: BIOMD0000000829.xml

2025-12-07 00:44:12,012 - WARNING - Skipping BIOMD0000000830.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000829.txt
Evaluating 828/1075: BIOMD0000000830.xml
Evaluating 829/1075: BIOMD0000000831.xml

2025-12-07 00:44:14,365 - WARNING - Species 'LATS1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:14,382 - WARNING - Species 'LATS1': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000831.txt
Evaluating 830/1075: BIOMD0000000832.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000832.txt
Evaluating 831/1075: BIOMD0000000833.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000833.txt
Evaluating 832/1075: BIOMD0000000834.xml

2025-12-07 00:44:35,728 - WARNING - Skipping BIOMD0000000835.xml - no results generated
2025-12-07 00:44:35,732 - WARNING - Skipping BIOMD0000000836.xml - no results generated
2025-12-07 00:44:35,754 - WARNING - Skipping BIOMD0000000837.xml - no results generated
2025-12-07 00:44:35,766 - WARNING - Skipping BIOMD0000000838.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000834.txt
Evaluating 833/1075: BIOMD0000000835.xml
Evaluating 834/1075: BIOMD0000000836.xml
Evaluating 835/1075: BIOMD0000000837.xml
Evaluating 836/1075: BIOMD0000000838.xml
Evaluating 837/1075: BIOMD0000000839.xml

2025-12-07 00:44:37,577 - WARNING - Skipping BIOMD0000000840.xml - no results generated
2025-12-07 00:44:37,588 - WARNING - Skipping BIOMD0000000841.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000839.txt
Evaluating 838/1075: BIOMD0000000840.xml
Evaluating 839/1075: BIOMD0000000841.xml
Evaluating 840/1075: BIOMD0000000842.xml

2025-12-07 00:44:46,810 - WARNING - Skipping BIOMD0000000843.xml - no results generated
2025-12-07 00:44:46,837 - WARNING - Skipping BIOMD0000000844.xml - no results generated
2025-12-07 00:44:46,846 - WARNING - Skipping BIOMD0000000845.xml - no results generated
2025-12-07 00:44:46,857 - WARNING - Skipping BIOMD0000000846.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000842.txt
Evaluating 841/1075: BIOMD0000000843.xml
Evaluating 842/1075: BIOMD0000000844.xml
Evaluating 843/1075: BIOMD0000000845.xml
Evaluating 844/1075: BIOMD0000000846.xml
Evaluating 845/1075: BIOMD0000000847.xml

2025-12-07 00:44:49,322 - WARNING - Skipping BIOMD0000000848.xml - no results generated
2025-12-07 00:44:49,489 - WARNING - Skipping BIOMD0000000849.xml - no results generated
2025-12-07 00:44:49,497 - WARNING - Skipping BIOMD0000000850.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000847.txt
Evaluating 846/1075: BIOMD0000000848.xml
Evaluating 847/1075: BIOMD0000000849.xml
Evaluating 848/1075: BIOMD0000000850.xml
Evaluating 849/1075: BIOMD0000000851.xml

2025-12-07 00:44:49,515 - WARNING - Skipping BIOMD0000000851.xml - no results generated
2025-12-07 00:44:49,535 - WARNING - Skipping BIOMD0000000852.xml - no results generated
2025-12-07 00:44:49,545 - WARNING - Species 'STAB': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:49,555 - WARNING - Species 'STAB': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:49,556 - WARNING - Skipping BIOMD0000000853.xml - no results generated
2025-12-07 00:44:49,566 - WARNING - Skipping BIOMD0000000854.xml - no results generated
2025-12-07 00:44:49,585 - WARNING - Skipping BIOMD0000000855.xml - no results generated
2025-12-07 00:44:49,620 - WARNING - Skipping BIOMD0000000856.xml - no results generated

Evaluating 850/1075: BIOMD0000000852.xml
Evaluating 851/1075: BIOMD0000000853.xml
Evaluating 852/1075: BIOMD0000000854.xml
Evaluating 853/1075: BIOMD0000000855.xml
Evaluating 854/1075: BIOMD0000000856.xml
Evaluating 855/1075: BIOMD0000000857.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000857.txt
Evaluating 856/1075: BIOMD0000000858.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000858.txt
Evaluating 857/1075: BIOMD0000000859.xml

2025-12-07 00:44:57,724 - WARNING - Species 'miR': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:57,725 - WARNING - Species 'TF1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:57,729 - WARNING - Species 'miR': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:57,729 - WARNING - Species 'TF1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:57,729 - WARNING - Skipping BIOMD0000000860.xml - no results generated
2025-12-07 00:44:57,750 - WARNING - Species 'p12EpoRpJAK2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:44:57,770 - WARNING - Species 'p12EpoRpJAK2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000859.txt
Evaluating 858/1075: BIOMD0000000860.xml
Evaluating 859/1075: BIOMD0000000861.xml

2025-12-07 00:45:01,490 - WARNING - Skipping BIOMD0000000862.xml - no results generated
2025-12-07 00:45:01,515 - WARNING - Skipping BIOMD0000000863.xml - no results generated
2025-12-07 00:45:01,525 - WARNING - Skipping BIOMD0000000864.xml - no results generated
2025-12-07 00:45:01,544 - WARNING - Skipping BIOMD0000000865.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000861.txt
Evaluating 860/1075: BIOMD0000000862.xml
Evaluating 861/1075: BIOMD0000000863.xml
Evaluating 862/1075: BIOMD0000000864.xml
Evaluating 863/1075: BIOMD0000000865.xml
Evaluating 864/1075: BIOMD0000000866.xml

2025-12-07 00:45:03,975 - WARNING - Skipping BIOMD0000000867.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000866.txt
Evaluating 865/1075: BIOMD0000000867.xml
Evaluating 866/1075: BIOMD0000000868.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000868.txt
Evaluating 867/1075: BIOMD0000000869.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000869.txt
Evaluating 868/1075: BIOMD0000000870.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000870.txt
Evaluating 869/1075: BIOMD0000000871.xml

2025-12-07 00:45:15,956 - WARNING - Species 's2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:15,957 - WARNING - Species 's4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:15,957 - WARNING - Species 's14': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:15,957 - WARNING - Species 's16': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:15,958 - WARNING - Species 's13': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:15,958 - WARNING - Species 's12': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,030 - WARNING - Species 's2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,031 - WARNING - Species 's4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,034 - WARNING - Species 's14': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,034 - WARNING - Species 's16': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,034 - WARNING - Species 's13': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,035 - WARNING - Species 's12': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,036 - WARNING - Skipping BIOMD0000000872.xml - no results generated
2025-12-07 00:45:16,054 - WARNING - Species 'mw5b252d78_9ab9_438c_8b81_2189b1f76357': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,055 - WARNING - Species 'mw869055b5_5d27_4f4a_a390_b3fa48d6780e': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,055 - WARNING - Species 'mw6f8ce639_1c28_444f_b6e6_30ff06ab0d6e': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,056 - WARNING - Species 'mwb9a40fab_a7c9_4984_805f_045fefc4ff32': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,056 - WARNING - Species 'mw4fc13b75_10cc_41fb_b9f8_1ce95fccae73': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,073 - WARNING - Species 'mw5b252d78_9ab9_438c_8b81_2189b1f76357': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,074 - WARNING - Species 'mw869055b5_5d27_4f4a_a390_b3fa48d6780e': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,074 - WARNING - Species 'mw6f8ce639_1c28_444f_b6e6_30ff06ab0d6e': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,074 - WARNING - Species 'mwb9a40fab_a7c9_4984_805f_045fefc4ff32': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:16,075 - WARNING - Species 'mw4fc13b75_10cc_41fb_b9f8_1ce95fccae73': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000871.txt
Evaluating 870/1075: BIOMD0000000872.xml
Evaluating 871/1075: BIOMD0000000873.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000873.txt
Evaluating 872/1075: BIOMD0000000874.xml

2025-12-07 00:45:49,832 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:49,838 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:49,839 - WARNING - Skipping BIOMD0000000875.xml - no results generated
2025-12-07 00:45:49,855 - WARNING - Skipping BIOMD0000000876.xml - no results generated
2025-12-07 00:45:49,863 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:49,869 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:49,869 - WARNING - Skipping BIOMD0000000877.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000874.txt
Evaluating 873/1075: BIOMD0000000875.xml
Evaluating 874/1075: BIOMD0000000876.xml
Evaluating 875/1075: BIOMD0000000877.xml
Evaluating 876/1075: BIOMD0000000878.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000878.txt
Evaluating 877/1075: BIOMD0000000879.xml

2025-12-07 00:45:51,617 - WARNING - Skipping BIOMD0000000880.xml - no results generated
2025-12-07 00:45:51,634 - WARNING - Skipping BIOMD0000000881.xml - no results generated
2025-12-07 00:45:51,640 - WARNING - Species 'Susceptible': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,640 - WARNING - Species 'Removal': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,645 - WARNING - Species 'Susceptible': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,645 - WARNING - Species 'Removal': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,646 - WARNING - Skipping BIOMD0000000882.xml - no results generated
2025-12-07 00:45:51,695 - WARNING - Species 'mTORC2Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,696 - WARNING - Species 'mTORC1Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,697 - WARNING - Species 'mTORC1Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,706 - WARNING - Species 'mTORC2Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,752 - WARNING - Species 'mTORC2Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,753 - WARNING - Species 'mTORC1Active': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,753 - WARNING - Species 'mTORC1Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:45:51,759 - WARNING - Species 'mTORC2Inactive': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000879.txt
Evaluating 878/1075: BIOMD0000000880.xml
Evaluating 879/1075: BIOMD0000000881.xml
Evaluating 880/1075: BIOMD0000000882.xml
Evaluating 881/1075: BIOMD0000000883.xml

2025-12-07 00:46:29,872 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,873 - WARNING - Species 'V': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,878 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,879 - WARNING - Species 'V': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,880 - WARNING - Skipping BIOMD0000000884.xml - no results generated
2025-12-07 00:46:29,885 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,885 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,890 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,890 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,890 - WARNING - Skipping BIOMD0000000885.xml - no results generated
2025-12-07 00:46:29,898 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,898 - WARNING - Species 'Th': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,898 - WARNING - Species 'B': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,899 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,905 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,905 - WARNING - Species 'Th': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,906 - WARNING - Species 'B': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,906 - WARNING - Species 'A': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,906 - WARNING - Skipping BIOMD0000000886.xml - no results generated
2025-12-07 00:46:29,919 - WARNING - Skipping BIOMD0000000887.xml - no results generated
2025-12-07 00:46:29,929 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,929 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,929 - WARNING - Species 'D': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,930 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,938 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,939 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,939 - WARNING - Species 'D': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,939 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:29,940 - WARNING - Skipping BIOMD0000000888.xml - no results generated
2025-12-07 00:46:29,964 - WARNING - Skipping BIOMD0000000889.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000883.txt
Evaluating 882/1075: BIOMD0000000884.xml
Evaluating 883/1075: BIOMD0000000885.xml
Evaluating 884/1075: BIOMD0000000886.xml
Evaluating 885/1075: BIOMD0000000887.xml
Evaluating 886/1075: BIOMD0000000888.xml
Evaluating 887/1075: BIOMD0000000889.xml
Evaluating 888/1075: BIOMD0000000890.xml

2025-12-07 00:46:30,996 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:30,997 - WARNING - Species 'v': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:30,998 - WARNING - Species 'w': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,003 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,004 - WARNING - Species 'v': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,004 - WARNING - Species 'w': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,005 - WARNING - Skipping BIOMD0000000891.xml - no results generated
2025-12-07 00:46:31,011 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,017 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,018 - WARNING - Skipping BIOMD0000000892.xml - no results generated
2025-12-07 00:46:31,027 - WARNING - Skipping BIOMD0000000893.xml - no results generated
2025-12-07 00:46:31,033 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,033 - WARNING - Species 'y': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,034 - WARNING - Species 'z': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,039 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,039 - WARNING - Species 'y': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,039 - WARNING - Species 'z': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,040 - WARNING - Skipping BIOMD0000000894.xml - no results generated
2025-12-07 00:46:31,069 - WARNING - Skipping BIOMD0000000895.xml - no results generated
2025-12-07 00:46:31,079 - WARNING - Species 'HSF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,089 - WARNING - Species 'HSF': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,090 - WARNING - Skipping BIOMD0000000896.xml - no results generated
2025-12-07 00:46:31,097 - WARNING - Skipping BIOMD0000000897.xml - no results generated
2025-12-07 00:46:31,111 - WARNING - Skipping BIOMD0000000898.xml - no results generated
2025-12-07 00:46:31,211 - WARNING - Skipping BIOMD0000000899.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000890.txt
Evaluating 889/1075: BIOMD0000000891.xml
Evaluating 890/1075: BIOMD0000000892.xml
Evaluating 891/1075: BIOMD0000000893.xml
Evaluating 892/1075: BIOMD0000000894.xml
Evaluating 893/1075: BIOMD0000000895.xml
Evaluating 894/1075: BIOMD0000000896.xml
Evaluating 895/1075: BIOMD0000000897.xml
Evaluating 896/1075: BIOMD0000000898.xml
Evaluating 897/1075: BIOMD0000000899.xml

2025-12-07 00:46:31,217 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,222 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,222 - WARNING - Skipping BIOMD0000000900.xml - no results generated
2025-12-07 00:46:31,231 - WARNING - Skipping BIOMD0000000901.xml - no results generated
2025-12-07 00:46:31,242 - WARNING - Skipping BIOMD0000000902.xml - no results generated
2025-12-07 00:46:31,250 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,250 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,250 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,258 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,258 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,259 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,259 - WARNING - Skipping BIOMD0000000903.xml - no results generated
2025-12-07 00:46:31,265 - WARNING - Species 'Ti': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,265 - WARNING - Species 'Tm': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,272 - WARNING - Species 'Ti': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,272 - WARNING - Species 'Tm': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,273 - WARNING - Skipping BIOMD0000000904.xml - no results generated
2025-12-07 00:46:31,279 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,280 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,280 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,287 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,288 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,288 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,289 - WARNING - Skipping BIOMD0000000905.xml - no results generated
2025-12-07 00:46:31,294 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,294 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,299 - WARNING - Species 'P': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,299 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,300 - WARNING - Skipping BIOMD0000000906.xml - no results generated
2025-12-07 00:46:31,335 - WARNING - Skipping BIOMD0000000907.xml - no results generated
2025-12-07 00:46:31,346 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,346 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,346 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,347 - WARNING - Species 'R': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,347 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,347 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,348 - WARNING - Species 'S': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,358 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,358 - WARNING - Species 'N': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,359 - WARNING - Species 'L': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,359 - WARNING - Species 'R': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,359 - WARNING - Species 'C': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,360 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,360 - WARNING - Species 'S': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,360 - WARNING - Skipping BIOMD0000000908.xml - no results generated
2025-12-07 00:46:31,366 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,367 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,367 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,372 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,373 - WARNING - Species 'I': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,373 - WARNING - Species 'u': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,373 - WARNING - Skipping BIOMD0000000909.xml - no results generated
2025-12-07 00:46:31,378 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,378 - WARNING - Species 'I2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,381 - WARNING - Species 'T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:31,382 - WARNING - Species 'I2': Found bqmodel qualifier instead of bqbiol - incorrect usage

Evaluating 898/1075: BIOMD0000000900.xml
Evaluating 899/1075: BIOMD0000000901.xml
Evaluating 900/1075: BIOMD0000000902.xml
Evaluating 901/1075: BIOMD0000000903.xml
Evaluating 902/1075: BIOMD0000000904.xml
Evaluating 903/1075: BIOMD0000000905.xml
Evaluating 904/1075: BIOMD0000000906.xml
Evaluating 905/1075: BIOMD0000000907.xml
Evaluating 906/1075: BIOMD0000000908.xml
Evaluating 907/1075: BIOMD0000000909.xml
Evaluating 908/1075: BIOMD0000000910.xml

2025-12-07 00:46:32,601 - WARNING - Skipping BIOMD0000000911.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000910.txt
Evaluating 909/1075: BIOMD0000000911.xml
Evaluating 910/1075: BIOMD0000000912.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000912.txt
Evaluating 911/1075: BIOMD0000000913.xml

2025-12-07 00:46:35,427 - WARNING - Species 'SVAC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,435 - WARNING - Species 'SVAC': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,439 - WARNING - Skipping BIOMD0000000914.xml - no results generated
2025-12-07 00:46:35,466 - WARNING - Skipping BIOMD0000000915.xml - no results generated
2025-12-07 00:46:35,479 - WARNING - Skipping BIOMD0000000916.xml - no results generated
2025-12-07 00:46:35,495 - WARNING - Skipping BIOMD0000000917.xml - no results generated
2025-12-07 00:46:35,515 - WARNING - Skipping BIOMD0000000918.xml - no results generated
2025-12-07 00:46:35,521 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,525 - WARNING - Species 'x': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,526 - WARNING - Skipping BIOMD0000000919.xml - no results generated
2025-12-07 00:46:35,542 - WARNING - Skipping BIOMD0000000920.xml - no results generated
2025-12-07 00:46:35,553 - WARNING - Species 'G': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,553 - WARNING - Species 'M': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,554 - WARNING - Species 'C_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,554 - WARNING - Species 'T_beta': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,554 - WARNING - Species 'I_gamma': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,563 - WARNING - Species 'G': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,564 - WARNING - Species 'M': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,564 - WARNING - Species 'C_T': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,565 - WARNING - Species 'T_beta': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,565 - WARNING - Species 'I_gamma': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:46:35,565 - WARNING - Skipping BIOMD0000000921.xml - no results generated
2025-12-07 00:46:35,573 - WARNING - Skipping BIOMD0000000922.xml - no results generated
2025-12-07 00:46:35,585 - WARNING - Skipping BIOMD0000000923.xml - no results generated
2025-12-07 00:46:35,606 - WARNING - Skipping BIOMD0000000924.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000913.txt
Evaluating 912/1075: BIOMD0000000914.xml
Evaluating 913/1075: BIOMD0000000915.xml
Evaluating 914/1075: BIOMD0000000916.xml
Evaluating 915/1075: BIOMD0000000917.xml
Evaluating 916/1075: BIOMD0000000918.xml
Evaluating 917/1075: BIOMD0000000919.xml
Evaluating 918/1075: BIOMD0000000920.xml
Evaluating 919/1075: BIOMD0000000921.xml
Evaluating 920/1075: BIOMD0000000922.xml
Evaluating 921/1075: BIOMD0000000923.xml
Evaluating 922/1075: BIOMD0000000924.xml
Evaluating 923/1075: BIOMD0000000925.xml

2025-12-07 00:46:35,718 - WARNING - Skipping BIOMD0000000925.xml - no results generated
2025-12-07 00:46:35,761 - WARNING - Skipping BIOMD0000000926.xml - no results generated

Evaluating 924/1075: BIOMD0000000926.xml
Evaluating 925/1075: BIOMD0000000927.xml

2025-12-07 00:46:37,126 - WARNING - Skipping BIOMD0000000928.xml - no results generated
2025-12-07 00:46:37,152 - WARNING - Skipping BIOMD0000000929.xml - no results generated
2025-12-07 00:46:37,167 - WARNING - Skipping BIOMD0000000930.xml - no results generated
2025-12-07 00:46:37,176 - WARNING - Skipping BIOMD0000000931.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000927.txt
Evaluating 926/1075: BIOMD0000000928.xml
Evaluating 927/1075: BIOMD0000000929.xml
Evaluating 928/1075: BIOMD0000000930.xml
Evaluating 929/1075: BIOMD0000000931.xml
Evaluating 930/1075: BIOMD0000000932.xml

2025-12-07 00:46:38,705 - WARNING - Skipping BIOMD0000000933.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000932.txt
Evaluating 931/1075: BIOMD0000000933.xml
Evaluating 932/1075: BIOMD0000000934.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000934.txt
Evaluating 933/1075: BIOMD0000000935.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000935.txt
Evaluating 934/1075: BIOMD0000000936.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000936.txt
Evaluating 935/1075: BIOMD0000000937.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000937.txt
Evaluating 936/1075: BIOMD0000000938.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000938.txt
Evaluating 937/1075: BIOMD0000000939.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000939.txt
Evaluating 938/1075: BIOMD0000000940.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000940.txt
Evaluating 939/1075: BIOMD0000000941.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000941.txt
Evaluating 940/1075: BIOMD0000000942.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000942.txt
Evaluating 941/1075: BIOMD0000000943.xml

2025-12-07 00:48:01,040 - WARNING - Skipping BIOMD0000000944.xml - no results generated
2025-12-07 00:48:01,052 - WARNING - Skipping BIOMD0000000945.xml - no results generated
2025-12-07 00:48:01,067 - WARNING - Skipping BIOMD0000000946.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000943.txt
Evaluating 942/1075: BIOMD0000000944.xml
Evaluating 943/1075: BIOMD0000000945.xml
Evaluating 944/1075: BIOMD0000000946.xml
Evaluating 945/1075: BIOMD0000000947.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000947.txt
Evaluating 946/1075: BIOMD0000000948.xml

2025-12-07 00:48:06,948 - WARNING - Skipping BIOMD0000000949.xml - no results generated
2025-12-07 00:48:06,964 - WARNING - Skipping BIOMD0000000950.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000948.txt
Evaluating 947/1075: BIOMD0000000949.xml
Evaluating 948/1075: BIOMD0000000950.xml
Evaluating 949/1075: BIOMD0000000951.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000951.txt
Evaluating 950/1075: BIOMD0000000952.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000952.txt
Evaluating 951/1075: BIOMD0000000953.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000953.txt
Evaluating 952/1075: BIOMD0000000954.xml

2025-12-07 00:48:43,172 - WARNING - Skipping BIOMD0000000955.xml - no results generated
2025-12-07 00:48:43,185 - WARNING - Skipping BIOMD0000000956.xml - no results generated
2025-12-07 00:48:43,191 - WARNING - Skipping BIOMD0000000957.xml - no results generated
2025-12-07 00:48:43,209 - WARNING - Skipping BIOMD0000000958.xml - no results generated
2025-12-07 00:48:43,244 - WARNING - Species 'STAT1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,245 - WARNING - Species 'STAT1_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,245 - WARNING - Species 'STAT1_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,246 - WARNING - Species 'STAT2_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,246 - WARNING - Species 'STAT2_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,246 - WARNING - Species 'STAT2_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,247 - WARNING - Species 'STAT2_LC_4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,247 - WARNING - Species 'STAT2_LC_5': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,247 - WARNING - Species 'IRF9_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,249 - WARNING - Species 'IRF9_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,250 - WARNING - Species 'USP18_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,250 - WARNING - Species 'USP18_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,250 - WARNING - Species 'SOCS1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,285 - WARNING - Species 'STAT1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,286 - WARNING - Species 'STAT1_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,286 - WARNING - Species 'STAT1_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,287 - WARNING - Species 'STAT2_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,287 - WARNING - Species 'STAT2_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,287 - WARNING - Species 'STAT2_LC_3': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,288 - WARNING - Species 'STAT2_LC_4': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,288 - WARNING - Species 'STAT2_LC_5': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,288 - WARNING - Species 'IRF9_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,289 - WARNING - Species 'IRF9_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,289 - WARNING - Species 'USP18_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,289 - WARNING - Species 'USP18_LC_2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:48:43,290 - WARNING - Species 'SOCS1_LC_1': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000954.txt
Evaluating 953/1075: BIOMD0000000955.xml
Evaluating 954/1075: BIOMD0000000956.xml
Evaluating 955/1075: BIOMD0000000957.xml
Evaluating 956/1075: BIOMD0000000958.xml
Evaluating 957/1075: BIOMD0000000959.xml

2025-12-07 00:48:56,806 - WARNING - Skipping BIOMD0000000960.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000959.txt
Evaluating 958/1075: BIOMD0000000960.xml
Evaluating 959/1075: BIOMD0000000961.xml

2025-12-07 00:49:12,029 - WARNING - Skipping BIOMD0000000962.xml - no results generated
2025-12-07 00:49:12,036 - WARNING - Skipping BIOMD0000000963.xml - no results generated
2025-12-07 00:49:12,056 - WARNING - Skipping BIOMD0000000964.xml - no results generated
2025-12-07 00:49:12,085 - WARNING - Species 'I1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,114 - WARNING - Species 'I1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,115 - WARNING - Skipping BIOMD0000000965.xml - no results generated
2025-12-07 00:49:12,132 - WARNING - Species 'Py': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,133 - WARNING - Species 'Py1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,134 - WARNING - Species 'Dw': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,134 - WARNING - Species 'Qw1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,134 - WARNING - Species 'Qw2': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,151 - WARNING - Species 'Py': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,152 - WARNING - Species 'Py1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,152 - WARNING - Species 'Dw': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,153 - WARNING - Species 'Qw1': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:12,153 - WARNING - Species 'Qw2': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000961.txt
Evaluating 960/1075: BIOMD0000000962.xml
Evaluating 961/1075: BIOMD0000000963.xml
Evaluating 962/1075: BIOMD0000000964.xml
Evaluating 963/1075: BIOMD0000000965.xml
Evaluating 964/1075: BIOMD0000000966.xml

2025-12-07 00:49:14,518 - WARNING - Skipping BIOMD0000000967.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000966.txt
Evaluating 965/1075: BIOMD0000000967.xml
Evaluating 966/1075: BIOMD0000000968.xml

2025-12-07 00:49:22,712 - WARNING - Skipping BIOMD0000000969.xml - no results generated
2025-12-07 00:49:22,721 - WARNING - Skipping BIOMD0000000970.xml - no results generated
2025-12-07 00:49:22,741 - WARNING - Skipping BIOMD0000000971.xml - no results generated
2025-12-07 00:49:22,762 - WARNING - Skipping BIOMD0000000972.xml - no results generated
2025-12-07 00:49:22,772 - WARNING - Skipping BIOMD0000000973.xml - no results generated
2025-12-07 00:49:22,783 - WARNING - Skipping BIOMD0000000974.xml - no results generated
2025-12-07 00:49:22,819 - WARNING - Species 'PCC_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:22,820 - WARNING - Species 'PCN_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:22,820 - WARNING - Species 'PCNP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:22,820 - WARNING - Species 'PCCP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:22,855 - WARNING - Species 'PCC_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:22,855 - WARNING - Species 'PCN_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:22,856 - WARNING - Species 'PCNP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:22,856 - WARNING - Species 'PCCP_0': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000968.txt
Evaluating 967/1075: BIOMD0000000969.xml
Evaluating 968/1075: BIOMD0000000970.xml
Evaluating 969/1075: BIOMD0000000971.xml
Evaluating 970/1075: BIOMD0000000972.xml
Evaluating 971/1075: BIOMD0000000973.xml
Evaluating 972/1075: BIOMD0000000974.xml
Evaluating 973/1075: BIOMD0000000975.xml

2025-12-07 00:49:28,832 - WARNING - Skipping BIOMD0000000976.xml - no results generated
2025-12-07 00:49:28,850 - WARNING - Skipping BIOMD0000000977.xml - no results generated
2025-12-07 00:49:28,859 - WARNING - Skipping BIOMD0000000978.xml - no results generated
2025-12-07 00:49:28,869 - WARNING - Skipping BIOMD0000000979.xml - no results generated
2025-12-07 00:49:28,879 - WARNING - Skipping BIOMD0000000980.xml - no results generated
2025-12-07 00:49:28,902 - WARNING - Skipping BIOMD0000000981.xml - no results generated
2025-12-07 00:49:28,910 - WARNING - Skipping BIOMD0000000982.xml - no results generated
2025-12-07 00:49:28,929 - WARNING - Skipping BIOMD0000000983.xml - no results generated
2025-12-07 00:49:28,938 - WARNING - Skipping BIOMD0000000984.xml - no results generated
2025-12-07 00:49:28,953 - WARNING - Skipping BIOMD0000000985.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000975.txt
Evaluating 974/1075: BIOMD0000000976.xml
Evaluating 975/1075: BIOMD0000000977.xml
Evaluating 976/1075: BIOMD0000000978.xml
Evaluating 977/1075: BIOMD0000000979.xml
Evaluating 978/1075: BIOMD0000000980.xml
Evaluating 979/1075: BIOMD0000000981.xml
Evaluating 980/1075: BIOMD0000000982.xml
Evaluating 981/1075: BIOMD0000000983.xml
Evaluating 982/1075: BIOMD0000000984.xml
Evaluating 983/1075: BIOMD0000000985.xml
Evaluating 984/1075: BIOMD0000000986.xml

2025-12-07 00:49:31,999 - WARNING - Skipping BIOMD0000000987.xml - no results generated
2025-12-07 00:49:32,072 - WARNING - Skipping BIOMD0000000988.xml - no results generated
2025-12-07 00:49:32,111 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:32,151 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000986.txt
Evaluating 985/1075: BIOMD0000000987.xml
Evaluating 986/1075: BIOMD0000000988.xml
Evaluating 987/1075: BIOMD0000000989.xml

2025-12-07 00:49:42,716 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage
2025-12-07 00:49:42,750 - WARNING - Species 'pS2_pS2_pS2_n': Found bqmodel qualifier instead of bqbiol - incorrect usage

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000989.txt
Evaluating 988/1075: BIOMD0000000990.xml

2025-12-07 00:49:54,975 - WARNING - Skipping BIOMD0000000991.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000990.txt
Evaluating 989/1075: BIOMD0000000991.xml
Evaluating 990/1075: BIOMD0000000994.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000994.txt
Evaluating 991/1075: BIOMD0000000995.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000995.txt
Evaluating 992/1075: BIOMD0000000996.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000996.txt
Evaluating 993/1075: BIOMD0000000997.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000997.txt
Evaluating 994/1075: BIOMD0000000998.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000998.txt
Evaluating 995/1075: BIOMD0000000999.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000000999.txt
Evaluating 996/1075: BIOMD0000001000.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001000.txt
Evaluating 997/1075: BIOMD0000001001.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001001.txt
Evaluating 998/1075: BIOMD0000001002.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001002.txt
Evaluating 999/1075: BIOMD0000001003.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001003.txt
Evaluating 1000/1075: BIOMD0000001004.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001004.txt
Evaluating 1001/1075: BIOMD0000001005.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001005.txt
Evaluating 1002/1075: BIOMD0000001006.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001006.txt
Evaluating 1003/1075: BIOMD0000001007.xml

2025-12-07 00:52:17,991 - WARNING - Skipping BIOMD0000001008.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001007.txt
Evaluating 1004/1075: BIOMD0000001008.xml
Evaluating 1005/1075: BIOMD0000001009.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001009.txt
Evaluating 1006/1075: BIOMD0000001010.xml

2025-12-07 00:52:22,938 - WARNING - Skipping BIOMD0000001011.xml - no results generated
2025-12-07 00:52:22,951 - WARNING - Skipping BIOMD0000001012.xml - no results generated
2025-12-07 00:52:22,960 - WARNING - Skipping BIOMD0000001013.xml - no results generated
2025-12-07 00:52:22,975 - WARNING - Skipping BIOMD0000001014.xml - no results generated
2025-12-07 00:52:22,992 - WARNING - Skipping BIOMD0000001015.xml - no results generated
2025-12-07 00:52:23,005 - WARNING - Skipping BIOMD0000001016.xml - no results generated
2025-12-07 00:52:23,026 - WARNING - Skipping BIOMD0000001017.xml - no results generated
2025-12-07 00:52:23,057 - WARNING - Skipping BIOMD0000001018.xml - no results generated
2025-12-07 00:52:23,067 - WARNING - Skipping BIOMD0000001019.xml - no results generated
2025-12-07 00:52:23,077 - WARNING - Skipping BIOMD0000001020.xml - no results generated
2025-12-07 00:52:23,091 - WARNING - Skipping BIOMD0000001021.xml - no results generated
2025-12-07 00:52:23,101 - WARNING - Skipping BIOMD0000001022.xml - no results generated
2025-12-07 00:52:23,113 - WARNING - Skipping BIOMD0000001023.xml - no results generated
2025-12-07 00:52:23,121 - WARNING - Skipping BIOMD0000001024.xml - no results generated
2025-12-07 00:52:23,130 - WARNING - Skipping BIOMD0000001025.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001010.txt
Evaluating 1007/1075: BIOMD0000001011.xml
Evaluating 1008/1075: BIOMD0000001012.xml
Evaluating 1009/1075: BIOMD0000001013.xml
Evaluating 1010/1075: BIOMD0000001014.xml
Evaluating 1011/1075: BIOMD0000001015.xml
Evaluating 1012/1075: BIOMD0000001016.xml
Evaluating 1013/1075: BIOMD0000001017.xml
Evaluating 1014/1075: BIOMD0000001018.xml
Evaluating 1015/1075: BIOMD0000001019.xml
Evaluating 1016/1075: BIOMD0000001020.xml
Evaluating 1017/1075: BIOMD0000001021.xml
Evaluating 1018/1075: BIOMD0000001022.xml
Evaluating 1019/1075: BIOMD0000001023.xml
Evaluating 1020/1075: BIOMD0000001024.xml
Evaluating 1021/1075: BIOMD0000001025.xml
Evaluating 1022/1075: BIOMD0000001026.xml

2025-12-07 00:52:23,139 - WARNING - Skipping BIOMD0000001026.xml - no results generated
2025-12-07 00:52:23,189 - WARNING - Skipping BIOMD0000001027.xml - no results generated
2025-12-07 00:52:23,242 - WARNING - Skipping BIOMD0000001028.xml - no results generated
2025-12-07 00:52:23,302 - WARNING - Skipping BIOMD0000001029.xml - no results generated
2025-12-07 00:52:23,313 - WARNING - Skipping BIOMD0000001030.xml - no results generated
2025-12-07 00:52:23,324 - WARNING - Skipping BIOMD0000001031.xml - no results generated
2025-12-07 00:52:23,337 - WARNING - Skipping BIOMD0000001032.xml - no results generated
2025-12-07 00:52:23,362 - WARNING - Skipping BIOMD0000001033.xml - no results generated

Evaluating 1023/1075: BIOMD0000001027.xml
Evaluating 1024/1075: BIOMD0000001028.xml
Evaluating 1025/1075: BIOMD0000001029.xml
Evaluating 1026/1075: BIOMD0000001030.xml
Evaluating 1027/1075: BIOMD0000001031.xml
Evaluating 1028/1075: BIOMD0000001032.xml
Evaluating 1029/1075: BIOMD0000001033.xml
Evaluating 1030/1075: BIOMD0000001034.xml

2025-12-07 00:52:23,376 - WARNING - Skipping BIOMD0000001034.xml - no results generated
2025-12-07 00:52:23,395 - WARNING - Skipping BIOMD0000001035.xml - no results generated
2025-12-07 00:52:23,406 - WARNING - Skipping BIOMD0000001036.xml - no results generated
2025-12-07 00:52:23,414 - WARNING - Skipping BIOMD0000001037.xml - no results generated
2025-12-07 00:52:23,426 - WARNING - Skipping BIOMD0000001038.xml - no results generated
2025-12-07 00:52:23,476 - WARNING - Skipping BIOMD0000001039.xml - no results generated
2025-12-07 00:52:23,484 - WARNING - Skipping BIOMD0000001040.xml - no results generated
2025-12-07 00:52:23,493 - WARNING - Skipping BIOMD0000001041.xml - no results generated
2025-12-07 00:52:23,512 - WARNING - Skipping BIOMD0000001042.xml - no results generated
2025-12-07 00:52:23,524 - WARNING - Skipping BIOMD0000001043.xml - no results generated

Evaluating 1031/1075: BIOMD0000001035.xml
Evaluating 1032/1075: BIOMD0000001036.xml
Evaluating 1033/1075: BIOMD0000001037.xml
Evaluating 1034/1075: BIOMD0000001038.xml
Evaluating 1035/1075: BIOMD0000001039.xml
Evaluating 1036/1075: BIOMD0000001040.xml
Evaluating 1037/1075: BIOMD0000001041.xml
Evaluating 1038/1075: BIOMD0000001042.xml
Evaluating 1039/1075: BIOMD0000001043.xml
Evaluating 1040/1075: BIOMD0000001044.xml

2025-12-07 00:52:34,943 - WARNING - Skipping BIOMD0000001045.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001044.txt
Evaluating 1041/1075: BIOMD0000001045.xml
Evaluating 1042/1075: BIOMD0000001046.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001046.txt
Evaluating 1043/1075: BIOMD0000001047.xml

2025-12-07 00:55:03,543 - WARNING - Skipping BIOMD0000001048.xml - no results generated
2025-12-07 00:55:03,560 - WARNING - Skipping BIOMD0000001052.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001047.txt
Evaluating 1044/1075: BIOMD0000001048.xml
Evaluating 1045/1075: BIOMD0000001052.xml
Evaluating 1046/1075: BIOMD0000001053.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001053.txt
Evaluating 1047/1075: BIOMD0000001054.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001054.txt
Evaluating 1048/1075: BIOMD0000001055.xml

2025-12-07 00:55:16,152 - WARNING - Skipping BIOMD0000001056.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001055.txt
Evaluating 1049/1075: BIOMD0000001056.xml
Evaluating 1050/1075: BIOMD0000001057.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001057.txt
Evaluating 1051/1075: BIOMD0000001058.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001058.txt
Evaluating 1052/1075: BIOMD0000001059.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001059.txt
Evaluating 1053/1075: BIOMD0000001060.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001060.txt
Evaluating 1054/1075: BIOMD0000001061.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001061.txt
Evaluating 1055/1075: BIOMD0000001062.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001062.txt
Evaluating 1056/1075: BIOMD0000001063.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001063.txt
Evaluating 1057/1075: BIOMD0000001064.xml

2025-12-07 02:12:03,510 - WARNING - Skipping BIOMD0000001064.xml - no results generated

Evaluating 1058/1075: BIOMD0000001065.xml

2025-12-07 02:12:04,238 - ERROR - Error loading SBML file with antimony: Unable to read SBML file '/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106/BIOMD0000001065.xml' due to errors encountered when parsing the file.  Error(s) from libSBML:

line 102: (10102 [Error]) An SBML XML document must not contain undefined elements or attributes in the SBML namespace. Documents containing unknown elements or attributes placed in the SBML namespace do not conform to the SBML specification.
Reference: L3V1 Section 4.1
 Element 'globalRenderInformation' is not part of the definition of 'listOfGlobalRenderInformation' in SBML Level 3 Version 1 Package render Version 1.


2025-12-07 02:12:18,770 - ERROR - Error loading SBML file with antimony: Unable to read SBML file '/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106/BIOMD0000001065.xml' due to errors encountered when parsing the file.  Error(s) from libSBML:

line 102: (10102 [Error]) An SBML XML document must not contain undefined elements or attributes in the SBML namespace. Documents containing unknown elements or attributes placed in the SBML namespace do not conform to the SBML specification.
Reference: L3V1 Section 4.1
 Element 'globalRenderInformation' is not part of the definition of 'listOfGlobalRenderInformation' in SBML Level 3 Version 1 Package render Version 1.


2025-12-07 02:12:32,596 - ERROR - Error loading SBML file with antimony: Unable to read SBML file '/Users/luna/Desktop/CRBM/AMAS_proj/Models/BioModels_251106/BIOMD0000001065.xml' due to errors encountered when parsing the file.  Error(s) from libSBML:

line 102: (10102 [Error]) An SBML XML document must not contain undefined elements or attributes in the SBML namespace. Documents containing unknown elements or attributes placed in the SBML namespace do not conform to the SBML specification.
Reference: L3V1 Section 4.1
 Element 'globalRenderInformation' is not part of the definition of 'listOfGlobalRenderInformation' in SBML Level 3 Version 1 Package render Version 1.


2025-12-07 02:12:41,063 - WARNING - Skipping BIOMD0000001072.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001065.txt
Evaluating 1059/1075: BIOMD0000001072.xml
Evaluating 1060/1075: BIOMD0000001077.xml

2025-12-07 02:12:48,465 - WARNING - Skipping BIOMD0000001078.xml - no results generated
2025-12-07 02:12:48,470 - WARNING - Skipping BIOMD0000001079.xml - no results generated

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001077.txt
Evaluating 1061/1075: BIOMD0000001078.xml
Evaluating 1062/1075: BIOMD0000001079.xml
Evaluating 1063/1075: BIOMD0000001080.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001080.txt
Evaluating 1064/1075: BIOMD0000001090.xml

2025-12-07 02:12:50,172 - WARNING - Skipping BIOMD0000001090.xml - no results generated

Evaluating 1065/1075: BIOMD0000001091.xml

2025-12-07 02:12:52,571 - WARNING - Skipping BIOMD0000001091.xml - no results generated

Evaluating 1066/1075: BIOMD0000001092.xml

2025-12-07 02:15:59,548 - WARNING - Unknown entity type: phospho

LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001092.txt
Evaluating 1067/1075: BIOMD0000001093.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001093.txt
Evaluating 1068/1075: BIOMD0000001094.xml

2025-12-07 02:28:56,708 - WARNING - Skipping BIOMD0000001094.xml - no results generated
2025-12-07 02:28:57,209 - WARNING - Skipping BIOMD0000001095.xml - no results generated

Evaluating 1069/1075: BIOMD0000001095.xml
Evaluating 1070/1075: BIOMD0000001096.xml

2025-12-07 02:28:57,875 - WARNING - Skipping BIOMD0000001096.xml - no results generated

Evaluating 1071/1075: BIOMD0000001097.xml

2025-12-07 02:28:58,281 - WARNING - Skipping BIOMD0000001097.xml - no results generated
2025-12-07 02:28:58,551 - WARNING - Skipping BIOMD0000001098.xml - no results generated
2025-12-07 02:28:58,889 - WARNING - Skipping BIOMD0000001099.xml - no results generated

Evaluating 1072/1075: BIOMD0000001098.xml
Evaluating 1073/1075: BIOMD0000001099.xml

2025-12-07 02:28:58,906 - WARNING - Skipping BIOMD0000001102.xml - no results generated

Evaluating 1074/1075: BIOMD0000001102.xml
Evaluating 1075/1075: BIOMD0000001103.xml
LLM results saved to: autoType/llama-4-maverick-17b-128e-instruct-fp8/auto/20251206_2237/BIOMD0000001103.txt

In [11]:
print_evaluation_results("autoType/biomd251106_chebi+uniprot_direct_llama-4_top3_autoType.csv", ref_results_csv=None)

Showing all results
Number of models assessed: 683
Number of models with predictions: 617
Number of annotations evaluated: 23765
Average accuracy (per model): 0.28
Ave. recall (formula): 0.25
Ave. precision (formula): 0.23
Ave. recall (exact): 0.24
Ave. precision (exact): 0.14
Average accuracy (per species): 0.44
Ave. recall (formula, per species): 0.42
Ave. precision (formula, per species): 0.40
Ave. recall (exact, per species): 0.28
Ave. precision (exact, per species): 0.28
Ave. total time (per model): 17.26
Ave. total time (per element, per model): 0.50
Ave. LLM time (per model): 16.18
Ave. LLM time (per element, per model): 0.46
Average number of predictions per species: 1.10

# Statistics

In [6]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts_updated.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 312
Number of annotations evaluated: 11373
Average accuracy (per model): 0.86
Ave. recall (formula): 0.86
Ave. precision (formula): 0.65
Ave. recall (exact): 0.73
Ave. precision (exact): 0.26
Average accuracy (per species): 0.93
Ave. recall (formula, per species): 0.93
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.60
Ave. precision (exact, per species): 0.39
Ave. total time (per model): 19.55
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.97
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 2.77

In [7]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 308
Number of annotations evaluated: 11370
Average accuracy (per model): 0.85
Ave. recall (formula): 0.85
Ave. precision (formula): 0.64
Ave. recall (exact): 0.72
Ave. precision (exact): 0.25
Average accuracy (per species): 0.91
Ave. recall (formula, per species): 0.91
Ave. precision (formula, per species): 0.67
Ave. recall (exact, per species): 0.59
Ave. precision (exact, per species): 0.37
Ave. total time (per model): 19.25
Ave. total time (per element, per model): 0.54
Ave. LLM time (per model): 18.57
Ave. LLM time (per element, per model): 0.52
Average number of predictions per species: 2.79

In [9]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts_updated.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 313
Number of annotations evaluated: 11373
Average accuracy (per model): 0.89
Ave. recall (formula): 0.89
Ave. precision (formula): 0.23
Ave. recall (exact): 0.84
Ave. precision (exact): 0.09
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.95
Ave. precision (formula, per species): 0.26
Ave. recall (exact, per species): 0.68
Ave. precision (exact, per species): 0.15
Ave. total time (per model): 19.59
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.90
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 8.93

In [8]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 306
Number of annotations evaluated: 11370
Average accuracy (per model): 0.87
Ave. recall (formula): 0.87
Ave. precision (formula): 0.23
Ave. recall (exact): 0.82
Ave. precision (exact): 0.09
Average accuracy (per species): 0.93
Ave. recall (formula, per species): 0.93
Ave. precision (formula, per species): 0.25
Ave. recall (exact, per species): 0.67
Ave. precision (exact, per species): 0.14
Ave. total time (per model): 18.79
Ave. total time (per element, per model): 0.53
Ave. LLM time (per model): 18.12
Ave. LLM time (per element, per model): 0.51
Average number of predictions per species: 8.97

In [7]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'], entity_types=['chemical'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Filtering results by entity types: ['chemical']
Number of models assessed: 305
Number of models with predictions: 305
Number of annotations evaluated: 10850
Average accuracy (per model): 0.93
Ave. recall (formula): 0.93
Ave. precision (formula): 0.24
Ave. recall (exact): 0.88
Ave. precision (exact): 0.09
Average accuracy (per species): 0.96
Ave. recall (formula, per species): 0.96
Ave. precision (formula, per species): 0.26
Ave. recall (exact, per species): 0.69
Ave. precision (exact, per species): 0.15
Ave. total time (per model): 19.60
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.89
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 9.28

In [5]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'], entity_types=['chemical'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Filtering results by entity types: ['chemical']
Number of models assessed: 307
Number of models with predictions: 307
Number of annotations evaluated: 10814
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.69
Ave. recall (exact): 0.77
Ave. precision (exact): 0.27
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.60
Ave. precision (exact, per species): 0.38
Ave. total time (per model): 19.96
Ave. total time (per element, per model): 0.57
Ave. LLM time (per model): 19.26
Ave. LLM time (per element, per model): 0.55
Average number of predictions per species: 2.88

In [4]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated_prompts.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 308
Number of annotations evaluated: 11370
Average accuracy (per model): 0.85
Ave. recall (formula): 0.85
Ave. precision (formula): 0.64
Ave. recall (exact): 0.72
Ave. precision (exact): 0.25
Average accuracy (per species): 0.91
Ave. recall (formula, per species): 0.91
Ave. precision (formula, per species): 0.67
Ave. recall (exact, per species): 0.59
Ave. precision (exact, per species): 0.37
Ave. total time (per model): 19.25
Ave. total time (per element, per model): 0.54
Ave. LLM time (per model): 18.57
Ave. LLM time (per element, per model): 0.52
Average number of predictions per species: 2.79

In [5]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'], entity_types=['chemical'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Filtering results by entity types: ['chemical']
Number of models assessed: 308
Number of models with predictions: 308
Number of annotations evaluated: 10815
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.68
Ave. recall (exact): 0.77
Ave. precision (exact): 0.27
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.61
Ave. precision (exact, per species): 0.38
Ave. total time (per model): 19.98
Ave. total time (per element, per model): 0.57
Ave. LLM time (per model): 19.28
Ave. LLM time (per element, per model): 0.55
Average number of predictions per species: 2.88

In [14]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top3_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 316
Number of models with predictions: 310
Number of annotations evaluated: 11154
Average accuracy (per model): 0.88
Ave. recall (formula): 0.88
Ave. precision (formula): 0.66
Ave. recall (exact): 0.75
Ave. precision (exact): 0.26
Average accuracy (per species): 0.94
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.69
Ave. recall (exact, per species): 0.61
Ave. precision (exact, per species): 0.38
Ave. total time (per model): 19.10
Ave. total time (per element, per model): 0.54
Ave. LLM time (per model): 18.40
Ave. LLM time (per element, per model): 0.52
Average number of predictions per species: 2.83

In [ ]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-4_top10_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 315
Number of models with predictions: 309
Number of annotations evaluated: 11145
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.24
Ave. recall (exact): 0.85
Ave. precision (exact): 0.09
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.95
Ave. precision (formula, per species): 0.25
Ave. recall (exact, per species): 0.69
Ave. precision (exact, per species): 0.14
Ave. total time (per model): 19.39
Ave. total time (per element, per model): 0.55
Ave. LLM time (per model): 18.64
Ave. LLM time (per element, per model): 0.53
Average number of predictions per species: 9.20

In [4]:
print_evaluation_results("autoType/biomd251106_chebi_direct_llama-3_top10_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 306
Number of models with predictions: 301
Number of annotations evaluated: 10806
Average accuracy (per model): 0.85
Ave. recall (formula): 0.85
Ave. precision (formula): 0.73
Ave. recall (exact): 0.79
Ave. precision (exact): 0.36
Average accuracy (per species): 0.90
Ave. recall (formula, per species): 0.90
Ave. precision (formula, per species): 0.77
Ave. recall (exact, per species): 0.59
Ave. precision (exact, per species): 0.48
Ave. total time (per model): 25.95
Ave. total time (per element, per model): 0.73
Ave. LLM time (per model): 23.66
Ave. LLM time (per element, per model): 0.67
Average number of predictions per species: 2.77

In [6]:
print_evaluation_results("results/biomd251106_chebi_direct_llama-3_top10.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 316
Number of annotations evaluated: 11370
Average accuracy (per model): 0.87
Ave. recall (formula): 0.87
Ave. precision (formula): 0.76
Ave. recall (exact): 0.79
Ave. precision (exact): 0.36
Average accuracy (per species): 0.87
Ave. recall (formula, per species): 0.86
Ave. precision (formula, per species): 0.74
Ave. recall (exact, per species): 0.57
Ave. precision (exact, per species): 0.46
Ave. total time (per model): 25.23
Ave. total time (per element, per model): 0.71
Ave. LLM time (per model): 22.73
Ave. LLM time (per element, per model): 0.64
Average number of predictions per species: 2.67

In [7]:
print_evaluation_results("autoType/biomd251106_chebi_rag_llama-3_top10_autoType.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 307
Number of models with predictions: 307
Number of annotations evaluated: 10826
Average accuracy (per model): 0.94
Ave. recall (formula): 0.94
Ave. precision (formula): 0.23
Ave. recall (exact): 0.88
Ave. precision (exact): 0.09
Average accuracy (per species): 0.95
Ave. recall (formula, per species): 0.94
Ave. precision (formula, per species): 0.22
Ave. recall (exact, per species): 0.68
Ave. precision (exact, per species): 0.13
Ave. total time (per model): 24.71
Ave. total time (per element, per model): 0.70
Ave. LLM time (per model): 23.80
Ave. LLM time (per element, per model): 0.67
Average number of predictions per species: 9.94

In [8]:
print_evaluation_results("results/biomd251106_chebi_rag_llama-3_top10.csv", ref_results_csv=None, bqbiol_qualifiers=['is', 'isVersionOf'])

Showing all results
Filtering results by qualifiers: ['is', 'isVersionOf']
Number of models assessed: 320
Number of models with predictions: 320
Number of annotations evaluated: 11370
Average accuracy (per model): 0.91
Ave. recall (formula): 0.91
Ave. precision (formula): 0.23
Ave. recall (exact): 0.85
Ave. precision (exact): 0.09
Average accuracy (per species): 0.91
Ave. recall (formula, per species): 0.91
Ave. precision (formula, per species): 0.22
Ave. recall (exact, per species): 0.65
Ave. precision (exact, per species): 0.12
Ave. total time (per model): 23.79
Ave. total time (per element, per model): 0.67
Ave. LLM time (per model): 22.84
Ave. LLM time (per element, per model): 0.64
Average number of predictions per species: 9.89

In [8]:
# find different model, species pairs
df1 = pd.read_csv('results/biomd251106_chebi_rag_llama-4_top3.csv')
df2 = pd.read_csv('autoType/biomd251106_chebi_rag_llama-4_top3_autoType_updated.csv')
# only consider is, isVersionOf
df1 = df1[df1['qualifier'].isin(['is', 'isVersionOf'])]
df2 = df2[df2['qualifier'].isin(['is', 'isVersionOf'])]

# find pairs in df1 but not in df2
df1['model_species_pair'] = df1['model'] + '_' + df1['species_id']
df2['model_species_pair'] = df2['model'] + '_' + df2['species_id']
df1[~df1['model_species_pair'].isin(df2['model_species_pair'])].to_csv('autoType/biomd251106_chebi_rag_llama-4_top3_auto_diff.csv', index=False)